### ISSUE TITLE
Zero salt length RSA signatures doesn't work

### ISSUE THREAD

**Issue by andrewbelcher** [phpseclib/phpseclib#1002]
When checking whether we have a salt length, it uses a non-strict TRUE comparison, which results in a zero length not being distinguished from a NULL. This results in you not being able to generate signatures with a zero salt length (which is useful for testing).

**Comment by andrewbelcher** [comment]
This if fixed by #1001

**Comment by terrafrost** [comment]
Fixed. Thanks!
