### ISSUE TITLE
SFTP: Relative symlinks

### ISSUE THREAD

**Issue by dphoyes** [phpseclib/phpseclib#1004]
Hi

With regular SFTP, I am able to create a relative symlink like this:

```
sftp> symlink normal_file some_folder/my_link
```

This would create a link called `my_link` inside `some_folder` that points to the file at `some_folder/normal_file`. In other words, the link-target argument (`normal_file`) specifies a path relative to the directory containing the link, and is completely independent of the current working directory. The link-target argument is also equal to the value that would be returned by a subsequent call to readlink().

It seems that the SFTP::symlink function unintentionally changes these semantics. Firstly, it forces the target to always be converted to an absolute path, making it impossible to create relative symlinks. Secondly, the conversion performed assumes that the link-target is specified relative to the current working directory, rather than the link directory. So if I pass the same arguments as I would for the raw SFTP command, the new symlink would likely be created with a broken target-path. This is particularly unhelpful when I simply want to copy a relative symlink from one machine to another, keeping the relative target unchanged.

I think this issue could be fixed by simply removing the line: `$target = $this->_realpath($target);`. This gives the expected behaviour for me. Would this be an acceptable change?

**Comment by terrafrost** [comment]
The following PR should do what you want:

https://github.com/phpseclib/phpseclib/pull/1005

I also made it so that `realpath` is publicly exposed if you want to use it. I'll let it sit for a few days so people have a chance to chime in and will then (assuming there are no concerns raised) merge it.

Thanks!

**Comment by dphoyes** [comment]
Looks good to me. Cheers!

**Comment by terrafrost** [comment]
The fix has been committed. Thanks!
