### ISSUE TITLE
Can't run phpseclib - Branch 2.0

### ISSUE THREAD

**Issue by C1562956** [phpseclib/phpseclib#1010]
I've followed the guide you provided (along with the Composer Download instructions you also suggest) to download and try to install the composer but I get the following on the terminal

![image](https://cloud.githubusercontent.com/assets/19784597/16902466/3755234c-4c57-11e6-97e8-b0312cdfde40.png)

Do you know what could be causing the issue? I was using branch 1.0 initially but when I put it on my lampp package I had DEPRECATED errors so was apparent that branch 2.0 would fix this issue...?

Thanks, Gareth

**Comment by bantu** [comment]
What are you trying to achieve?
Develop improvements for phpseclib? Or do you want to use phpseclib in your project?

In the first case `php composer.phar install` is correct and you should install the `dom` and simplexml` PHP extensions as indicated by the error message you are seeing. In the second case you can probably get away with `php composer.phar install --no-dev` which will not install phpseclib development dependencies.

**Comment by C1562956** [comment]
Hi there. Sorry for not being clear, I want to use phpseclib in my project. I'm not very familiar with the command line in Linux so can I ask you what commands I'd need to put to install `dom` and `simplexml`?  Can I ask you also... I want to use this library in a plugin I'm developing.. would the library be portable? i.e. the end-user wouldn't have to install phpseclib dependencies when they will install my plugin?

**Comment by C1562956** [comment]
I entered `php composer.phar install --no-dev` on the command line and it created a folder called **vendor** with by the looks of it all the required files in it (**autoload.php** etc). My files which require to use the library are in the **htdocs** directory along with the **phpseclib** folder also... when I run my file which tries to use the library I get following errors:

![image](https://cloud.githubusercontent.com/assets/19784597/16902625/a041b212-4c5c-11e6-8ad5-ffa5d4d32a89.png)

Here's my code:

![image](https://cloud.githubusercontent.com/assets/19784597/16902627/b6382c40-4c5c-11e6-8d8f-7290153c97ad.png)

**Comment by terrafrost** [comment]
If you installed phpseclib with composer I'd just use it's autoloader:

```
require __DIR__ . '/vendor/autoload.php';
```

**Comment by C1562956** [comment]
Ah waw that's certainly a good way to condense the code.. This is what I have at the moment:

![image](https://cloud.githubusercontent.com/assets/19784597/16903181/c3d6bfee-4c6e-11e6-83a6-e8282dc31ef5.png)

Does that seem correct to you? It works anyway..well kind of... The setPublicKeyFormat call doesn't work.. I get this error when running the code when trying to set the public key format:

![image](https://cloud.githubusercontent.com/assets/19784597/16903186/fae2d19e-4c6e-11e6-8396-4b63ea9391a9.png)

**Comment by Sxderp** [comment]
You get that error because the constant 'PUBLIC_FORMAT_OPENSSH' does not exist in RSA. [link](https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA.php)

Although looking at the commit history... It seems to have vanished without a commit?

--
It's here: commit 868ced
https://github.com/phpseclib/phpseclib/blob/8686ced6d3ce9f4feaed709c2e59a9790f2a6eec/phpseclib/Crypt/AES.php

But not here (next commit): commit 31c140
https://github.com/phpseclib/phpseclib/blob/31c14063fa82697c53bb531483c6f31925212dd6/phpseclib/Crypt/RSA.php

... ??

**Comment by C1562956** [comment]
Ah that's weird... what do you recommend I do?

**Comment by Sxderp** [comment]
Change RSA::PUBLIC_FORMAT_OPENSSH to the string literal 'openssh'

Valid options for this parameter is the name of any file located in the Crypt\RSA directory.
[link](https://github.com/phpseclib/phpseclib/tree/master/phpseclib/Crypt/RSA)
If you ask me that's a weird way to go about setting this up but I suppose it allows people to drop in replacements.

**Comment by C1562956** [comment]
Thanks for that but I changed it to `openssh` and had no errors appearing but the public key format was unchanged. Here's my updated code:

![image](https://cloud.githubusercontent.com/assets/19784597/16903447/5ee5a106-4c76-11e6-8b9b-74c769afb039.png)

**Comment by Sxderp** [comment]
1)
Looks like composer pulls from 2.0.
2)
Master and 2.0 are very different..
3)
Since the API for this library is weird, (as far as I can tell) doing a createKey() doesn't seem to respect the current state of the RSA object, nor does it load the RSA object's properties. Honestly, it looks like it should really be a static function call, as it currently stands, though that's a discussion for later.
4)
In order for this to work the created key needs to be loaded:
```
$rsa = new RSA();
rsa->loadKey($rsa->createKey()['privatekey']);

file_put_contents('/home/frrz/leten/pub', $rsa->getPublicKey(RSA::PUBLIC_FORMAT_OPENSSH));
file_put_contents('/home/frrz/leten/priv', $rsa->getPrivateKey());

... (some other instance or whatever) ...

$rsa = new RSA();
$rsa->loadKey(file_get_contents('/home/frrz/leten/priv'));
```

**Comment by C1562956** [comment]
So what I have at the moment is creating a keypair and storing them... the loading I have takes place in a different file which is exactly as you showed. I changed my code to what you have as so:

![image](https://cloud.githubusercontent.com/assets/19784597/16903656/f9a68b56-4c7b-11e6-89ad-2d210d095901.png)


But when I run it I get:

![image](https://cloud.githubusercontent.com/assets/19784597/16903654/f02517e6-4c7b-11e6-9391-868bdba81c5e.png)

**Comment by Sxderp** [comment]
That's weird.
What version are you using? I grabbed from packagist
```
composer require phpseclib/phpseclib
```
Current version I have
```
composer show -- phpseclib/phpseclib
...
versions : * 2.0.2
...
```

**Comment by terrafrost** [comment]
@C1562956 - I think you're using the master branch. The master branch is a developmental branch with an unstable API. It should not be used in a production environment.

The 2.0 branch does have the `PUBLIC_FORMAT_OPENSSH` constant defined:

https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Crypt/RSA.php#L228

**Comment by terrafrost** [comment]
@Sxderp 

> Since the API for this library is weird, (as far as I can tell) doing a createKey() doesn't seem to respect the current state of the RSA object, nor does it load the RSA object's properties. Honestly, it looks like it should really be a static function call, as it currently stands, though that's a discussion for later.

It is, in the master branch:

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA.php#L406

Can't very well change it in the 1.0 or 2.0 branches, however, since doing so would break BC.

**Comment by C1562956** [comment]
Problem solved! You were right _terrafrost_, I was using the master branch -_- I downloaded branch 2.0 and it all worked perfectly :-) thanks to you also _Sxderp_ for all your help.

**Comment by C1562956** [comment]
Can I ask, is this library easily portable? Can I copy it over to a new computer and expect it to work? If not is it possible to do so?

**Comment by terrafrost** [comment]
Yah - it was designed to be portable. Obviously you'll need php to be installed on the new computer bu that's about it :)

**Comment by C1562956** [comment]
So once I do the installation into the directory I need, I can then copy the files over to a new computer and it should all work given PHP is installed?

**Comment by terrafrost** [comment]
Yup.

**Comment by C1562956** [comment]
Hi again guys. I don't know if you are aware of this issue I'm having.. since a few days now I've been creating the keys like I've done before..copying the public key over to my server thus connecting without the use of a password....but for some reason I just can't connect like this anymore. When I report the errors using `$ssh->getLastError()`, it displays: `SSH_MSG_USERAUTH_FAILURE: publickey,password`

Do you know what could be causing the problem? It's really bugging me :(
