### ISSUE TITLE
2.0 - Logging in w/o password

### ISSUE THREAD

**Issue by ethanclevenger91** [phpseclib/phpseclib#1023]
I'm trying to log into a virtual machine (hence the no password) with the following (2.0 branch installed via composer):

```
$ssh = new SSH2('192.168.7.7');
        if (!$ssh->login('vagrant')) {
            var_dump($ssh->getErrors());
            exit('Login failed');
        }
```

Right now, this is spitting out the `Login failed` message. For reference, from the command line I can get in with `ssh vagrant@192.168.7.7` no problem. Thoughts?

**Comment by bantu** [comment]
Pass an instance of ssh agent to the login method.

**Comment by ethanclevenger91** [comment]
Thanks for the tip. So now I've got:

```
$agent = new Agent();
$ssh = new SSH2('192.168.7.7');
        if (!$ssh->login('vagrant', $agent)) {
            var_dump($ssh->getErrors());
            exit('Login failed');
        }
```

This throws a notice ` SSH_AUTH_SOCK not found in ...\vendor\phpseclib\phpseclib\phpseclib\System\SSH\Agent.php on line 130` and then still fails.

**Comment by ethanclevenger91** [comment]
Could be relevant: I'm using PHP 7

**Comment by bantu** [comment]
Hmm. Ok. Looks like i do not remember how this works, then. Can you post
your .ssh/config file?

**Comment by ethanclevenger91** [comment]
```
Host willisdetailcenter.com
HostName 23.235.214.214
Port 22
User willisdetailcent
IdentityFile ~/.ssh/elite_willisdetailcenter.com_rsa
IdentitiesOnly yes
```
Repeated for myriad sites I work on, none of which are my vagrant box.

**Comment by bantu** [comment]
I am afraid then I don't know why `ssh vagrant@192.168.7.7` works for you. Maybe `ssh` is defined as an alias for something. Maybe you can use the RSA private key at `~/.vagrant.d/insecure_private_key` which some documentation seems to suggest.

**Comment by ethanclevenger91** [comment]
Ah! So I tagged a `-vv` on my `ssh` and it does, in fact, use my default public key:

```
debug1: Next authentication method: publickey
debug1: Offering RSA public key: /c/Users/Ethan/.ssh/id_rsa
```

So I need to do something like:

```
$key = new RSA();
$key->loadKey(file_get_contents('private-key.txt'));
```
But load my `is_rsa` file?

**Comment by bantu** [comment]
Yes, construct and RSA object and load id_rsa into it. Pass that as the second argument to the SSH login method. If id_rsa is passphrase-protected, you also have to decrypt it. But in any way, it would be better to use an SSH agent (e.g. Pageant).

**Comment by ethanclevenger91** [comment]
Yes, it did! Sorry for not following up. Just to recap for anyone reading - when SSH-ing into a Vagrant box, it uses your default public SSH key.
