### ISSUE TITLE
mcrypt is deprecated in PHP 7.1

### ISSUE THREAD

**Issue by BrunoDeBarros** [phpseclib/phpseclib#1028]
I've been testing my projects with PHP 7.1 and came across this. It's just a deprecation notice, so easily silenced, but probably worth looking at sooner rather than later, as mcrypt will likely be removed from PHP in 7.2 at the earliest.

https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by terrafrost** [comment]
mcrypt is only used if it's available. If mcrypt is not available either a pure-PHP implementation is used or OpenSSL is used. The prioritization is as follows: OpenSSL > mcrypt > pure-PHP. mcrypt and OpenSSL are loads faster than the pure-PHP implementation.

On PHP 7.1.0 Beta 3 with http://phpseclib.sourceforge.net/crypt/phpseclib.phps (slightly modified to work with 1.0.3) I get 0.595s with internal mode. With mcrypt I get 0.013s. With OpenSSL I get 0.002s.

So mcrypt offers a 45x speedup over the internal mode. OpenSSL offers a 6.5x speedup over mcrypt.

If you're getting notices about mcrypt that, in all likelihood, means that you don't have OpenSSL installed but that you do have mcrypt installed.

I could make it so that mcrypt isn't called, even if it's available, on PHP 7.1+, but then your cryptography would be much much slower. Which isn't to say that the pure-PHP implementation is slow - I submit that it's the fastest pure-PHP implementation out there and I think doing a megabyte of data in half a second is still pretty good but....  it can be a lot better. And if you're doing gigabytes of data it probably needs to be a lot better. But, still, the pure-PHP version is a lot slower. And, personally, I think a few E_DEPRECATED warnings is preferable to hit in speed that people in your shoes (who have mcrypt installed but not OpenSSL) would experience if I suppressed it on 7.1+.

**Comment by BrunoDeBarros** [comment]
Wow, thank you for the detailed response! I agree that switching away from mcrypt isn't appropriate (and not even necessary, since in PHP 7.1+ the mcrypt extension won't be there, and phpseclib will automatically use pure PHP or OpenSSL if available and skip mcrypt altogether).

In my particular case, though, I'm just developing locally, and have both mcrypt and openssl, which is why I was surprised to see the mcrypt deprecation notices - I assumed it was using it regardless. I did check if I had OpenSSL before starting the issue.

Now that you mentioned that phpseclib checks for OpenSSL first, I went to check the code. I checked the output of `_setEngine()` in the `__construct()` of Crypt\Base, and it yielded 3 (ENGINE_OPENSSL). So it's using OpenSSL, but reverting to mcrypt later on in the code.

An exception thrown at the point when the engine switched to 2 (ENGINE_MCRYPT) reveals that this happened while trying to use the SSH2 portion of phpseclib. After going through the code a bit more, I found out that this is triggered in Crypt\RC4's `isValidEngine()`, which returns false for me because `strlen($this->key) == 1` (which I don't understand, because it implies an 8-byte key) and that's not supported by the OpenSSL implementation, so it falls back on mcrypt.

I don't have a problem with silencing the deprecation notices, but it seems that this highlighted an area in which the OpenSSL side of phpseclib is lacking. Is this something that can be worked around with the OpenSSL library? If mcrypt can handle this, surely OpenSSL should be able to as well (though granted, this is probably bottom-of-the-priority-list stuff, so I completely understand if this doesn't matter too much to you). I don't know what'd need be involved in making this work, but I'd love to help in any way I can.

**Comment by terrafrost** [comment]
> If mcrypt can handle this, surely OpenSSL should be able to as well

It actually doesn't in a lot of cases. With OpenSSL you specify the the key length and mode when you're specifying the algorithm. ie. you do aes-128-cbc or rc4-128 or whatever. This poses several problems. First, the algorithm may support larger keys than OpenSSL provides options for. It'd probably be an easy enough fix for OpenSSL to expose them but that'd have to be done on the OpenSSL side and then in the PHP bindings to OpenSSL probably.

Also, OpenSSL doesn't operate in "continuous mode". So normally `encrypt($a)` done twice yields the same result. But in continuous mode you wouldn't want it to. In continuous mode you'd want `encrypt($a) . encrypt($a) == encrypt($a . $a)`. SSH operates in continuous mode and phpseclib emulates continuous mode with OpenSSL for block ciphers. But it can't emulate continuous mode for stream ciphers such as RC4, hence why mcrypt is used over OpenSSL in the case of SSH.

**Comment by BrunoDeBarros** [comment]
It's probably not worth it; I set the preferred engine to the internal one, and it worked correctly without any mcrypt notices, so it's clear that phpseclib -can- handle it, OpenSSL or not, which is what matters (I was worried that it might be relying exclusively on mcrypt to handle my particular situation).

So silencing deprecation warnings is a good workaround if you've got mcrypt and you're in 7.1 (best solution is to just remove mcrypt though), and in 7.2 there won't even be mcrypt anymore, so it won't matter.

Thank you so much for responding so thoroughly, though, I really appreciate your responsiveness.

**Comment by terrafrost** [comment]
The 1.0.4 release uses error suppression to hide mcrypt notices.

**Comment by pinakin7664** [comment]
i have find solution for php 7.1 mcyrpt issue :
https://www.cadence-labs.com/2016/09/magento-2-php-7-1-fix-function-mcyrpt_module_open-deprecated/

**Comment by nirbd** [comment]
Looks like these messages still appear in phpseclib V2 php 7.3.8.

/phpseclib/phpseclib/Crypt/Base.php line:1174 . Function mdecrypt_generic() is deprecated 

How can I tell phpseclib in some settings not to use/test for mycrypt ?
My code is very simple sftp file fetch

		$sftp = new \phpseclib\Net\SFTP($parsed_url['host'], $parsed_url['port']);
			
			if (!$sftp->login($parsed_url['user'], $parsed_url['pass'])) {
				$return['success'].= "<br/> sftp login failed ";
			}
			$path_parts = pathinfo($parsed_url['path']);
			$sftp->chdir($path_parts['dirname']);
			$result = $sftp->get($path_parts['basename'], $this->feed_filename);

**Comment by terrafrost** [comment]
Based on the line numbers I'd guess that you were using the latest version:

https://github.com/phpseclib/phpseclib/blob/2.0.21/phpseclib/Crypt/Base.php#L1174

Given that it is not clear why you're getting that error message. The error suppression operator is being used. If there is a way to get errors to show up in spite of the error suppression operator being used I am unaware of it.

> How can I tell phpseclib in some settings not to use/test for mycrypt ?

Personally, I think that's ill advised. If phpseclib is using mcrypt it's doing so for speed purposes. Either (1) OpenSSL (which is faster than mcrypt) is unavailable or (2) it's unsuitable for the given algorithm in question (eg. arcfour128 is being used or something; OpenSSL doesn't support "incremental encryption" as mcrypt did; it can be emulated for block ciphers but not for stream ciphers).

The pure-PHP implementation aims to be as fast as possible but it's simply not going to be able to compete with mcrypt. To go out of your way to use the pure-PHP implementation when mcrypt is available is like choosing to use Windows 95 when Windows 10 is available.

That said, you're free to do what you want. If you insist on _not_ using mcrypt you can do so by doing `$ssh->setCryptoEngine(CRYPT_MODE_INTERNAL);`.

**Comment by nirbd** [comment]
Thank you very much @terrafrost . Following your answer I realized my custom error handling was overriding the suppression.
