### ISSUE TITLE
Using a call-time pass-by-reference is prohibited since php 5.4

### ISSUE THREAD

**Issue by rtenny** [phpseclib/phpseclib#1029]
I get this warning in file/X509.php in various place like the below

$extensions = &$this->_subArrayUnchecked($root, $path);

I presume i can just change this to 
$extensions = $this->_subArrayUnchecked($root, $path);

**Comment by terrafrost** [comment]
Can you copy / paste that warning? Because I'm pretty skeptical that that's an actual PHP warning. In fact it seems very possible that you're using phpcs on phpseclib and you're running into the same issue #337 ran into. eg.

> call-time pass-by-reference is when you do `foo(&$a);` - not when you do `&foo($a);` What phpseclib is doing in the lines of code you mentioned is [returning by reference](http://www.php.net/manual/en/language.references.return.php)
