### ISSUE TITLE
2.0.3 infinite transmission issue

### ISSUE THREAD

**Issue by rmnanney** [phpseclib/phpseclib#1033]
Heads up on a surprise we just found in production :)

We upgraded to 2.0.3 (from 2.0.2) and have found a issue where a script which has been working for months, ran into a situation where a file was transmitting indefinitely.  We have rolled back to 2.0.2 and transmissions are functioning again.

Here is the code we are using to transmit the files.  Please let me know if I can provide any additional details for you.

`if ($files_exist) {
        // create SFTP connection
        $sftp = new \phpseclib\Net\SFTP($wc->remoteHost);
        if (!$sftp->login($wc->remoteUser, $wc->remotePass)) {
            throw new Exception('SFTP Login to ' . $wc->remoteHost . ' with username ' . $wc->remoteUser . ' failed');
        }
        
        // for each file, lets transmit it over
        foreach ($files as $file) {
            if (file_exists($file) && is_file($file)) {
                $remote_file = basename($file);
                $sftp->put($wc->remotePath . '/' . $remote_file, $file, $sftp::SOURCE_LOCAL_FILE);
            }
        }
    }`

Best,
Ryan

**Comment by terrafrost** [comment]
#995 seems like the most likely culprit but I'd need more information to develop a fix.

Try this:

```
#
#-----[ OPEN ]------------------------------------------
#
Net/SFTP.php
#
#-----[ FIND ]------------------------------------------
#
                $temp = isset($fp) ? fread($fp, $sftp_packet_size) : substr($data, $sent, $sftp_packet_size);
#
#-----[ AFTER, ADD ]------------------------------------
#
if ($data == 'problemfilename.txt') {
var_dump($temp);
}
```
That requires you figure out what file it's hanging on. You could comment out the if condition as well to just dump `$temp` out 24/7. Anyawy, if you run that via the CLI it should just output perpetually until you break the process. You can then copy / paste the output and post it here or on pastebin.com (and then post the link here).

Thanks!

**Comment by terrafrost** [comment]
#1026, which has been merged, should fix this. It's in the latest git version if you want to try it out.

Thanks!

**Comment by rmnanney** [comment]
I've updated our composer.json to

"require": {
   "phpseclib/phpseclib": "2.0.x-dev",
   ...
}

Ran the same test again, after a composer update, and bingo!  We'll look for the 2.0.4 and switch to that in prod when it hits =)

Thanks @terrafrost
