### ISSUE TITLE
SFTP download takes long time to complete for file sized 50mb

### ISSUE THREAD

**Issue by kherP** [phpseclib/phpseclib#1035]
Hi, SFTP seems to take longer time to download. Can i configure the READ size of phpseclib so the file can be downloaded faster?

**Comment by terrafrost** [comment]
I recently backported #945 to the 1.0 and 2.0 branches so maybe try the latest git version of either of those branches and see if that doesn't result in a speedup for you.

**Comment by kherP** [comment]
Nope, it doesn't speed up. It took me 82s to download the file.

time taken: 82s
size of file: 59.708493MB
MBytes/second: 0.728152 mbps

**Comment by terrafrost** [comment]
I tried it myself. With the changes it takes 0.250s, 0.240s and 0.279s to download 10MB from 127.0.0.1.

Without the changes (ie. the 1.0.3 branch) it took 0.411s, 0.4155s and 0.4109s.

The exact speed depends on a number of factors including, among others, the performance of your network. But there's also the cipher used, the use of compression (which phpseclib doesn't support), etc.

In your case....  well for one I'm wondering if actually are using the latest git version. Also, you say that with the latest git version it took 82s, but you don't say how long it takes with the orig version.

I guess what I'd be interested in are two things.

1. The simple SFTP log, which you can get by doing `define('NET_SFTP_LOGGING', 1)` at the top of the file and then `print_r($sftp->getSFTPLog())` after the file upload. Altho maybe get this with a smaller file.
2. The SSH2 logs showing the initial handshaking. You can get these by doing `define('NET_SSH2_LOGGING', 2)` at the top of the file and then `echo `echo $sftp->getLog()` after you've logged into the server.

**Comment by kherP** [comment]
Hi, just realized I have been calling the wrong version of phpseclib from another folder. The download speed boosted after using latest version of 1.0 branch. Thanks for taking your time to solve my issue.
