### ISSUE TITLE
PHP 7.1 Support ....

### ISSUE THREAD

**Issue by DeepDiver1975** [phpseclib/phpseclib#1037]
Let's collect to dos for php 7.1

- 7.1 to travis shows some warnings - https://github.com/phpseclib/phpseclib/pull/1036
- 'A non-numeric value encountered' in https://github.com/phpseclib/phpseclib/blob/master/phpseclib/File/ASN1.php#L507

**Comment by oanhnn** [comment]
Please support PHP 7.1
https://travis-ci.org/deployphp/deployer/jobs/162086438#L352

**Comment by terrafrost** [comment]
See https://github.com/phpseclib/phpseclib/pull/1036#issuecomment-248585831

I want to do a PR, give people a chance to review it, and then merge it. I'm going to try to do that later today.

**Comment by terrafrost** [comment]
phpseclib is now passing on Travis CI  with PHP 7.1:

https://travis-ci.org/phpseclib/phpseclib/builds/164359081

Thanks!
