### ISSUE TITLE
Not expecting @phpinfo code in 2.0.3 release

### ISSUE THREAD

**Issue by weshooper** [phpseclib/phpseclib#1039]
Since was removed here https://github.com/phpseclib/phpseclib/commit/7a628c62b0071d03bde6be82c2f77acdadb20df2 and is listed as the first item in the 2.0.3 release notes.

**Comment by terrafrost** [comment]
The release notes say "BigInteger/RSA: don't compare openssl versions > 1.0". Here's the commit that does that:

https://github.com/phpseclib/phpseclib/commit/6ff421d3547bdb2a79b1014d660a508a2a37c9c3

The https://github.com/phpseclib/phpseclib/commit/7a628c62b0071d03bde6be82c2f77acdadb20df2 commit is in the master branch. The master branch doesn't check phpinfo at all. The 1.0 and 2.0 branches do check it - they just don't disable OpenSSL if both the header and library versions of OpenSSL are above 1.0.

**Comment by weshooper** [comment]
Aha - understood, great thanks!
