### ISSUE TITLE
Code hangs since switch to stream_get_contents() (2.0.3)

### ISSUE THREAD

**Issue by duncan3dc** [phpseclib/phpseclib#1042]
It looks like 25503016784a3b36320cc4c75f138a72148b9799 has introduced/highlighted a bug.

Calls to `stream_get_contents()` block until the requested number of bytes have been read, if the requested number of bytes is greater than the stream is providing then the function just sits and waits, leaving the PHP script hanging.

I have a script that works fine on `2.0.2` but just hangs on `2.0.3`. I think it's caused by uploading an empty file, but I can't be sure

**Comment by terrafrost** [comment]
I think #1026 should fix the issue. If so then I think I'll do a release this weekend.

**Comment by duncan3dc** [comment]
Yes that does the trick, I've just run our test suite using `2.0.x-dev` and all passes now, thanks :+1:

**Comment by terrafrost** [comment]
I just released 1.0.4 and 2.0.4, which includes fixes for this issue.

Thanks!
