### ISSUE TITLE
Why error? How it fix?

### ISSUE THREAD

**Issue by Ennorath** [phpseclib/phpseclib#1047]
Fatal error: Uncaught exception 'UnexpectedValueException' with message 'Overloading of string functions using mbstring.func_overload is not supported by phpseclib.' in /var/www/****/data/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php:11 Stack trace: #0 /var/www/****/data/vendor/composer/autoload_real.php(66): require() #1 /var/www/****/data/vendor/composer/autoload_real.php(56): composerRequirebe08aa26605a9f1bf4fcb08b313738b1('decc78cc4436b12...', '/var/www/****...') #2 /var/www/****/data/vendor/autoload.php(7): ComposerAutoloaderInitbe08aa26605a9f1bf4fcb08b313738b1::getLoader() #3 /var/www/****/data/www/mysite.com/vendor/google/apiclient/examples/simple-query.php(17): include_once('/var/www/****...') #4 {main} thrown in /var/www/****/data/vendor/phpseclib/phpseclib/phpseclib/bootstrap.php on line 11

**Comment by bantu** [comment]
Disable mbstring function overloading: http://php.net/manual/en/mbstring.overload.php

**Comment by Ennorath** [comment]
Thank you, it help me :) @bantu
