### ISSUE TITLE
Autoloading in 1.* does not work

### ISSUE THREAD

**Issue by Wirone** [phpseclib/phpseclib#1048]
I have updated phpseclib from 0.* to 1.* (1.0.4 actually) in my Yii project and I had issues with autoloading.

After debugging I found that this is not valid PSR-4 entry because files under `phpseclib` are not namespaced.
```
    "autoload": {
        "files": [
            "phpseclib/bootstrap.php"
        ],
        "psr-4": {
            "phpseclib\\": "phpseclib/"
        }
    }
```

After adding in my root's `composer.json`:

```
    "autoload": {
        "psr-4": {
            "": "protected/vendor/phpseclib/phpseclib/phpseclib/"
        }
    }
```

files are loaded correctly.

PS. There is another issue with Yii, when loading via `Yii::import()` - files are not named like classes (`AES.php` -> `Crypt_AES`), but this is whole different story...

**Comment by Wirone** [comment]
Probably related to #243?

**Comment by bantu** [comment]
1.0 is supposed to be PSR-0.
https://github.com/phpseclib/phpseclib/commit/29659f877d5be1720cff70eafc0b4687ec842449
broke this.

As a workaround maybe you can upgrade to 2.0 right away, which is PSR-4.
But its also namespaces, so you would have to do some refactoring.

**Comment by Wirone** [comment]
I had to update library because we wanted application to be PHP7-compatible (0.3.10 has old-fashioned constructors so it does not work), but without changing app's codebase, so I've updated it to 1.*.

It is bug in autoloading definition, since there is not any namespace in 1.0 branch (composer thinks its under `phpseclib` namespace).

**Comment by Wirone** [comment]
I think tests should (in bootstrap file) use Composer's autoloading, not `set_include_path()` since it's not real-world usage strategy (or at least not 100%).

**Comment by bantu** [comment]
Did you try undoing the changes I linked to for PSR-0 support?

set_include_path in tests is a leftover from PHP 5.2 support. It can
probably indeed be removed and made consistent with the 2.0 and master
branches.

**Comment by Wirone** [comment]
No, I did not try, I've fixed it with app's `composer.json`. I can test it later.

**Comment by terrafrost** [comment]
How does https://github.com/terrafrost/phpseclib/tree/1.0-composer-fix look?

If it looks good LMK and I'll tag a 1.0.4a release.

Thanks!

**Comment by Wirone** [comment]
Looks good. I've changed my `composer.json`:

```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/terrafrost/phpseclib/"
    }
],
"require": {
        "phpseclib/phpseclib": "dev-1.0-composer-fix",
}
```

and package was downloaded and autoloaded correctly.

But I suggest to mark it with 1.0.5 since it's a bugfix, and I don't know if Composer works good with such "a" suffixes ;-)

**Comment by terrafrost** [comment]
I'll hold off until bantu has had a chance to chime in.

Doing a 1.0.5 release does not have a lot of appeal to me. If there's a 1.0.5 tag but not a 1.0.5 downloadable zip file from phpseclib.sourceforge.net that's going to cause confusion. If there's a 1.0.5 downloadable zip version the version in phpseclib's PEAR channel needs to be 1.0.5 as well, etc. And for what? For no code changes at all? Just a composer.json change?

I could do 1.0.4-1 too if that'd work better..

**Comment by Wirone** [comment]
For me this IS a change in codebase. You maintain and keep versioning of a *package* and composer.json is integral part of it. If you want to maintain only crypt classes without vendoring it, remove it from Packagist and tell people to download it by hand :-)

But I'll not tell you what to do. As far as I know Composer supports 4-level versions (each version is normalized to x.x.x.x format) so you can tag it `1.0.4.1`. From my point of view it could be everything which would be valid for `~1.0` constraint with `minimum-stability: stable` configuration.

**Comment by bantu** [comment]
@terrafrost Please let's do things properly: 1.0.5 and update everything. If doing a release is time-consuming, we need to (further) automate it.

Btw. https://github.com/phpseclib/phpseclib/commit/29659f877d5be1720cff70eafc0b4687ec842449 looks like a broken cherry-pick of https://github.com/phpseclib/phpseclib/commit/cd57bf31ae576a178016209576c8a3c305c7b82f which probably could have been detected if it went through a pull request.

> How does https://github.com/terrafrost/phpseclib/tree/1.0-composer-fix look?

Please always send pull requests right away. In the worst case, the patch is not good and the PR has to be closed.

**Comment by terrafrost** [comment]
> For me this IS a change in codebase.

Fair enough, but composer.json doesn't even exist in the PEAR version or in the zip version you download from phpseclib.sourceforge.net. So, in so far as those install sources are concerned there are zero code changes. You do md5sum on v1.0.4's zip and you'll get the same hash as you would on v1.0.5.

**Comment by terrafrost** [comment]
> If doing a release is time-consuming, we need to (further) automate it.

**Comment by terrafrost** [comment]
I didn't mean to close this. I was trying to close my draft. I was going to say that the rpm releases (which I don't do) would take time for the maintainers of those but it looks like those are the 2.0 branch - not the 1.0 branch - so they'd be unaffected.
