### ISSUE TITLE
is_dir() does not work

### ISSUE THREAD

**Issue by moyarich** [phpseclib/phpseclib#1053]
$sftp->is_dir() does not work, It returns false  even when the directory is on the sftp server

**Comment by terrafrost** [comment]
`is_dir()` is tested several times in the unit tests:

https://github.com/phpseclib/phpseclib/blob/1.0/tests/Functional/Net/SFTPUserStoryTest.php

...and the unit tests are passing for every version of phpseclib.

I guess you could give me the SFTP logs and I could give you a more detailed explanation based on that. You can get the logs by doing `define('NET_SFTP_LOGGING', 2)` at the top and then `echo $sftp->getSFTPLog()` after the `is_dir()` call.

**Comment by bantu** [comment]
Please show minimal code snippet for reproduction.

**Comment by moyarich** [comment]
# LOG Result:

<code>
log:  mkdir:  NET_SFTP_STATUS_NO_SUCH_FILE:  


Array ( [0] => -> NET_SFTP_MKDIR (0s) [1] => <- NET_SFTP_STATUS (0.4836s) [2] => -> NET_SFTP_STAT (0s) [3] => <- NET_SFTP_STATUS (0.6084s) [4] => -> NET_SFTP_MKDIR (0s) [5] => <- NET_SFTP_STATUS (0.468s) )
SFTP Log : 1
</code>

# PHP Code:
```php
define('NET_SFTP_LOGGING', 2);
$backUpDirectory = '+test_dir';
$sftp->mkdir($backUpDirectory,-1, true);


if ($sftp->is_dir($backUpDirectory)){
	// do nothing, directory already exists
	echo '<br /><pre>log:  is_dir:  ' . print_r($sftp->getLastSFTPError() ,true) .' </pre><br />';
}
else {
	// create recursive directory
	$sftp->mkdir($backUpDirectory,-1, true);
	echo '<br /><pre>log:  mkdir:  ' . print_r($sftp->getLastSFTPError() ,true) .' </pre><br />';
}

echo '<br /> SFTP Log : ' . print_r($sftp->getSFTPLog());

**Comment by bantu** [comment]
Can you try without the + in the dir name?

**Comment by moyarich** [comment]
@bantu  same result

mkdir(),  works, is_dir() does not return true

**Comment by terrafrost** [comment]
As is the case with https://github.com/phpseclib/phpseclib/issues/1052#issuecomment-257099131 I think this is an issue with your event handler. I don't know of other SFTP clients that have an `is_dir` method so idk that suggesting you test this in another client is gonna be that worthwhile but maybe post on stackoverflow or some such your event handler code. You could post a link to the SO post here, as well. I'm not a node.js expert but who knows maybe I might have some insight none-the-less.
