### ISSUE TITLE
Encrypt multiple public keys

### ISSUE THREAD

**Issue by byinff** [phpseclib/phpseclib#1054]
this class has support for encryption with multiple public keys?

**Comment by terrafrost** [comment]
You could do this?:

```php
$ciphertext = $rsa->encrypt('plaintext');
$rsa2->encrypt($ciphertext);
```

Altho if you're using padded RSA each successive key would need to be larger than the last since PKCS1 / OAEP modes add data to the plaintext prior to encryption.

**Comment by bantu** [comment]
Please define/explain "support for encryption with multiple public keys".

**Comment by byinff** [comment]
Mmm no, i need to know if this library can cipher encryption encryption end to end like whatsapp or OpenPGP

**Comment by bantu** [comment]
@byinff The generic approach for encrypting large data to multiple public keys is to generate a session key and then encrypt the session key using the set of public keys. This can be done with phpseclib, but is outside of any standard such as OpenPGP. If you looked at #68 you may have noticed that there is a link to https://github.com/singpolyma/openpgp-php which is a project using phpseclib to implement OpenPGP. I am not sure it fits your needs.

**Comment by byinff** [comment]
@bantu Thank you very much for the reply, is aware of the library openpgp but referred with multiple public keys? I am wanting to make an example system on whatsapp messages

**Comment by bantu** [comment]
The whatsapp protocol is more complicated and provides security guarantees
beyond OpenPGP. I think the protocol is called axolotl.

**Comment by byinff** [comment]
@bantu very thanks for your help
