### ISSUE TITLE
Missing setSignatureMode( RSA::SIGNATURE_PKCS1 ) in the master branch?

### ISSUE THREAD

**Issue by Overtonesinger** [phpseclib/phpseclib#1055]
What can I do to **make sure  SIGNATURE_PKCS1** signature **mode** is used?

Is the **PADDING_PKCS1** taking care of it **completely**?

I could not find the deprecation of the method **setSignatureMode** it in the Changelog. IMHO, there _should be_ a note about it  and about **what** replaces it.

Thank You so much for the answer in advance.
Filip

**Comment by terrafrost** [comment]
The master branch should not be used. It's API is not set in stone and is not guaranteed to remain the same from commit to commit. CHANGELOG.md is only for tagged releases. Only the 1.0 and 2.0 branches have tagged releases. The current master branch will eventually become the 3.0 branch, at which point, we'll start seeing tagged releases, but until that time, changes to the master branch are not going to be notated in CHANGELOG.md. After the 3.0 branch is created then the API will be considered stable but only for the 3.0 branch. The master branch will still exist but the possibility for BC breaking changes will always exist in that branch.

Anyway, #902 explains the change.
