### ISSUE TITLE
Fatal error: Uncaught Error: Class 'ParagonIE\ConstantTime\Hex' not found in phpseclib/Math/BigInteger.php:523

### ISSUE THREAD

**Issue by andrrrl** [phpseclib/phpseclib#1057]
Library was working fine until recently.
- Server: CentOS 7
- PHP 7.0.12

```
Fatal error: Uncaught Error: Class 'ParagonIE\ConstantTime\Hex' not found in phpseclib/Math/BigInteger.php:523 
Stack trace: 
#0 phpseclib/Math/BigInteger.php(3075): phpseclib\Math\BigInteger->toBytes() 
#1 phpseclib/Net/SSH2.php(1518): phpseclib\Math\BigInteger::randomRange(Object(phpseclib\Math\BigInteger), Object(phpseclib\Math\BigInteger)) 
#2 phpseclib/Net/SSH2.php(1125): phpseclib\Net\SSH2->_key_exchange('\x140!`\x175W*x\e?\x1A`\xCF\xB6...') 
#3 phpseclib/Net/SSH2.php(1901): phpseclib\Net\SSH2->_connect() 
#4 [internal function]: phpseclib\Net\SSH2->_login('user', 'shhh') 
#5 phpseclib/Net/SSH2.php(1885): call_user_func_array(Array, Array)
```

**Comment by bantu** [comment]
Please provide more context. E.g. how was phpseclib installed?

**Comment by terrafrost** [comment]
Looks like you're using the master branch, which is under active development and should not be used.

All 1.0.x should be BC with each other and all 2.0.x releases should be BC with one another. The master branch, otoh, has not yet had any releases and there should be no expectation of BC from commit to commit. In fact, I'd say quite the opposite - there have been and will continue to be a lot of commits that /do/ change

**Comment by andrrrl** [comment]
You're right @terrafrost, thanks for the explanation, I don't have much expertise in file repositories and their logic. So, moved to 2.0 and that was it.
By the way, I finally could make the master branch work by (auto)loading the Paragonie package.

**Comment by andrrrl** [comment]
@bantu, I just downloaded this folder: https://github.com/phpseclib/phpseclib/tree/master/phpseclib
Again I don't have much expertise with repositories, and this is good learning, thanks again!

**Comment by bantu** [comment]
@andrrrl I see, thank you. I am going ahead and close this issue as it seems to be resolved for you.
@terrafrost Since support requests like this one have increased recently, maybe we should improve a bit on our README.md.
