### ISSUE TITLE
AES/CDC/NoPADDING

### ISSUE THREAD

**Issue by AndriySvirin** [phpseclib/phpseclib#1058]
Hello,
Is it possible to use phphseclib for this java code for analog PHP?
```
SecretKeySpec skeySpec = new SecretKeySpec(transactionKey, "AES");
Cipher cipher2 = Cipher.getInstance("AES/CBC/NoPadding", "BC");
cipher2.init(Cipher.DECRYPT_MODE, skeySpec, new IvParameterSpec(new byte[cipher2.getBlockSize()]));
byte[] data = cipher2.doFinal(orderData);
```

Thanks a lot

**Comment by bantu** [comment]
Yes that should be possible.

**Comment by AndriySvirin** [comment]
```
$aes = new AES(AES::MODE_CBC);
$aes->disablePadding();
$iv = mcrypt_create_iv(mcrypt_get_iv_size(MCRYPT_RIJNDAEL_128, MCRYPT_MODE_CBC));
$aes->setIV($iv);
$aes->setPassword($transactionKey);
$d = $aes->decrypt($orderData);
```

But it doesnt decrypt. May be i made mistake. Can you look on it?

**Comment by bantu** [comment]
Do not mix mcrypt with phpseclib. In your Java code it looks like you're
using a key, so you have to use setKey instead of setPassword. You do not
need a new IV for decryption. (You might want to read up on the theory of
AES CBC encryption.)

**Comment by bantu** [comment]
@AndriySvirin Did you figure it out?

**Comment by AndriySvirin** [comment]
Yes. I have used native php method
