### ISSUE TITLE
SFTP 2.0.4 get file is truncated

### ISSUE THREAD

**Issue by xian13** [phpseclib/phpseclib#1062]
Hi @terrafrost,

I have a bug with get the file contents from sftp using phpseclib SFTP 2.0.4, where it always truncated, after downgrading to 2.0.3 the problem is resolved.

I try to debug and suspect a code in this [commit](https://github.com/phpseclib/phpseclib/commit/398a795e1fef877004f7fa9b7bb31606727e8066) may cause the problem.
The code I use is not using offset and length so the offset is 0 and length is -1, I assume that if the length -1 then I want to get all of the contents of the file without chunking.

In [this](https://github.com/phpseclib/phpseclib/commit/398a795e1fef877004f7fa9b7bb31606727e8066#diff-f0500f119a16ba4ff6303ba9008b1ce1R2070) line, the length is -1 so it will looping until it reach NET_SFTP_QUEUE_SIZE(50), where in the 2.0.3 version, it will not loop until 50, and only loop until get EOF packet.

Because the looping is reach 50 in 2.0.4, so the $i value also 50 and it will loop _get_sftp_packet to 50.
Can this is the cause the file is truncated when _get_sftp_packet is called?

**Comment by terrafrost** [comment]
Well I'm not able to duplicate the problem.

I did `$sftp->size('filename.ext')` and `strlen($sftp->get('filename.ext'))` and the numbers consistently match.

You say "in this line" but you link to a commit - not to an actual line. And the commit that likely would have caused the issue (that I cannot duplicate) is https://github.com/phpseclib/phpseclib/pull/945

Anyway, calling _get_sftp_packet 50 times isn't a problem. See, for example, this log:

http://pastebin.com/QUNqgmiv

It sends NET_SFTP_READ 50 times and then gets NET_SFTP_DATA or NET_SFTP_STATUS for each of those 50 requests.

I guess what'd be really helpful is if you could sent me the phpseclib logs. You can get them by doing ``define('NET_SFTP_LOGGING', SFTP::LOG_COMPLEX);` at the top of the file and then by doing `echo $sftp->getSFTPLog()` at the end of the file. In testing it out there was apparently a bug in the 2.0 branch w.r.t. SFTP logging:

https://github.com/phpseclib/phpseclib/commit/8b4208ee60407efe3d13753eb92d0a41dda613d5

This bug has been fixed. If the SFTP logs don't yield anything fruitful the full SSH logs might be useful. You can get those by doing `define('NET_SSH2_LOGGING', SSH2::LOG_COMPLEX)` at the top and `echo $sftp->getLog()` after your download attempt.

**Comment by xian13** [comment]
Thank you, from your explanation, I think i know what cause the problem.

From the log, I got :

<- NET_SFTP_STATUS (0.0004s)
00000000  00:00:00:01:00:00:00:0b:72:65:61:64:20:66:61:69  ........read fai
00000010  6c:65:64:00:00:00:00                             led....

<- NET_SFTP_STATUS (0.0002s)
00000000  00:00:00:01:00:00:00:0b:72:65:61:64:20:66:61:69  ........read fai
00000010  6c:65:64:00:00:00:00                             led....

<- NET_SFTP_STATUS (0.0001s)
00000000  00:00:00:01:00:00:00:0b:72:65:61:64:20:66:61:69  ........read fai
00000010  6c:65:64:00:00:00:00                             led....

<- NET_SFTP_STATUS (0.0001s)
00000000  00:00:00:01:00:00:00:0b:72:65:61:64:20:66:61:69  ........read fai
00000010  6c:65:64:00:00:00:00                             led....

and when i define NET_SFTP_QUEUE_SIZE to some value, the error gone, what I think is that my provider sftp server limit the number of connection, is this correct?

and when I try to print the log, I got some error :

Use of undefined constant NET_SFTP_LOG_REALTIME - assumed 'NET_SFTP_LOG_REALTIME' in SFTP.php line 2794
and
Use of undefined constant NET_SFTP_LOG_COMPLEX - assumed 'NET_SFTP_LOG_COMPLEX' in SFTP.php line 2800

Maybe line 2794 need to be updated to using SFTP::LOG_REALTIME and line 2800 to SFTP::LOG_COMPLEX?

**Comment by terrafrost** [comment]
> and when i define NET_SFTP_QUEUE_SIZE to some value, the error gone, what I think is that my provider sftp server limit the number of connection, is this correct?

Interesting. Yah - that's what it looks like. The first four bytes of the NET_SFTP_STATUS packets are for the error / status code. The status code in your responses (1) corresponds to SSH_FX_EOF. You're getting the same status in your "read failed" responses that I got in my "End of file" responses. That's about as useful as throwing just a generic `\Exception` and expecting programs to parse the response to take the appropriate action.

Like in theory it seems like what could be done is to dynamically set the NET_SFTP_QUEUE_SIZE. So if, after 25 reads you started to get a SSH_FX_FAILURE response instead of SSH_FX_OK or SSH_FX_EOF you set NET_SFTP_QUEUE_SIZE to 25 instead of 50. But nope - can't do that with your server ugh. And idk that I want to read the message itself.

What are you using as your server? You can find out by doing `$sftp->getServerIdentification();`

> and when I try to print the log, I got some error :

Yah, I got that too, when I tried it last night. It's fixed in the 2.0 and master branches but not in any tagged version yet:

https://github.com/phpseclib/phpseclib/commit/8b4208ee60407efe3d13753eb92d0a41dda613d5

**Comment by terrafrost** [comment]
It looks like PuTTY does 32 requests at a time with each request requested 32KB of data. 32 * 32KB = 1024KB. I guess it started doing this in 0.54: http://www.chiark.greenend.org.uk/~sgtatham/putty/faq.html#faq-psftp-slow / http://www.chiark.greenend.org.uk/~sgtatham/putty/changes.html

phpseclib does, by default, does 50 requests at a time, each 32KB long, which is 1.5625MB.

Does setting NET_SFTP_QUEUE_SIZE to 32 solve the problem for you? I'd be willing to change it from 50 to 32 in phpseclib.

**Comment by terrafrost** [comment]
I've gone ahead and changed the queue size to 32:

https://github.com/phpseclib/phpseclib/commit/6fb34887c5bf06f5757f35d341bd0e79f5a017d7

**Comment by xian13** [comment]
> What are you using as your server? You can find out by doing $sftp->getServerIdentification();

SSH-2.0-SwFTP

> Does setting NET_SFTP_QUEUE_SIZE to 32 solve the problem for you? I'd be willing to change it from 50 to 32 in phpseclib.

Sometimes it works, sometimes it doesn't work, if i change the number to <= 17 the success chance is high (only some failure in 17), but when i increase to 18 it will have more failure.

**Comment by terrafrost** [comment]
Where can I download that?

Since it's not OpenSSH what I can do is add a condition in the SFTP constructor that sets NET_SFTP_QUEUE_SIZE to, let's say, 10, or something.

**Comment by xian13** [comment]
I use sftp to connect to OpenStack object storage, for simplicity in code I use sftp, I think the server use [this](https://github.com/softlayer/swftp)

Because you use ! defined, currently i can use define('NET_SFTP_QUEUE_SIZE', 15) before calling in first time, so it is ok.
