### ISSUE TITLE
MCRYPT ext. deprecated in PHP 7.1.x and will be removed in PHP 7.2.x

### ISSUE THREAD

**Issue by nuxwin** [phpseclib/phpseclib#1067]
See the title. It is maybe time to switch to openssl to avoid any suprise.

See also https://wiki.php.net/rfc/mcrypt-viking-funeral

Thank you.

**Comment by terrafrost** [comment]
Duplicate of #1028. See, also, #1040.

**Comment by nuxwin** [comment]
@terrafrost 

Sorry for the duplicate report... Next time, I'll look better ;)

**Comment by terrafrost** [comment]
No worries! I'd rather have a dupe report than no report at all lol
