### ISSUE TITLE
SFTP Issue cannot use object of type stdclass as array

### ISSUE THREAD

**Issue by jimmaay** [phpseclib/phpseclib#1069]
Getting the follow fatal error when connected to SFTP and running $sftp->file_exists() which looks like:

```
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /composer/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:1127
Stack trace:
#0 /composer/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2258): phpseclib\Net\SFTP->_query_stat_cache('/.')
#1 script.php(128): phpseclib\Net\SFTP->file_exists('/')
#2 {main}
  thrown in /composer/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 1127
```

Looks like $temp is an object in that function _query_stat_cache which causes $temp[$dir] to fail. The json output of $temp before the crash looks like:

`{"home":{"folder":{".softaculous":[],"access-logs":{"lstat":{"size":31,"uid":508,"gid":521,"permissions":41471,"mode":41471,"type":3,"atime":1480766771,"mtime":1437444250}},".":{"lstat":{"size":4096,"uid":0,"gid":0,"permissions":16877,"mode":16877,"type":2,"atime":1480067963,"mtime":1480067963}}}}`

**Comment by terrafrost** [comment]
The fact that `file_exists` [is unit tested](https://github.com/phpseclib/phpseclib/blob/2.0/tests/Functional/Net/SFTPUserStoryTest.php) (and passing) not withstanding, I am unable to duplicate the issue on either the 1.0.5 or 2.0.4 versions.

I looked at several different versions of phpseclib to see what was on line 2258.

In 2.0.4 it's `$i++` in the `_delete_recursive` method:
https://github.com/phpseclib/phpseclib/blob/2.0.4/phpseclib/Net/SFTP.php#L2258

In 2.0.3 it's `/**':
https://github.com/phpseclib/phpseclib/blob/2.0.3/phpseclib/Net/SFTP.php#L2258

In 2.0.2 it's an empty line:
https://github.com/phpseclib/phpseclib/blob/2.0.2/phpseclib/Net/SFTP.php#L2258

What version of phpseclib are you using? Maybe post your line 2258 and surrounding lines as well.

**Comment by jimmaay** [comment]
Looks like it's 1.0, I'll try upgrading in the future and report back. One thing to note is that it didn't happen in the past so it's probably an incompatibility with the newer openssh

**Comment by terrafrost** [comment]
What version of 1.0? 1.0 is a branch - the tagged versions are 1.0.0 - 1.0.5.

**Comment by jimmaay** [comment]
1.0.0

**Comment by terrafrost** [comment]
The latest version of the 1.0 series is 1.0.5. But that said, I tried to reproduce your problem on 1.0.0. No luck.

#402 gave a similar error but that was fixed years ago, before 1.0.0 was released.

I'd just recommend you upgrade to the latest 1.0 version. If you're still having the issue after you upgrade lmk.

**Comment by jimmaay** [comment]
Yeah I'll try upgrading later in the future and report back. For now I just patched mine with an is_array check

**Comment by bantu** [comment]
I am closing this. Feel free to reopen after confirming the latest version of 1.0 (or any other supported branch) is affected.

**Comment by lintaba** [comment]
Having the same issue with the latest (2.0.6) branch.

FatalThrowableError in SFTP.php line 1139:
Cannot use object of type stdClass as array

It seems to happen during copy, when the destination folder does not exists.
