### ISSUE TITLE
error with new Crypt_RSA

### ISSUE THREAD

**Issue by rommeq** [phpseclib/phpseclib#1072]
Hello
I'm trying to use phpseclib library

   ```
 include 'phpseclib/vendor/autoload.php';
    $loader = new \Composer\Autoload\ClassLoader();
    $loader->addPsr4('phpseclib\\', DRUPAL_ROOT . '/path/phpseclib/');
    $loader->register();
    use phpseclib\Crypt\RSA;
    use phpseclib\Net\SSH2;
```
if I use $rsa = new RSA();

   ```
 function my_function() {
     $rsa = new RSA();
    }
```
I have an error: 

> Constants may only evaluate to scalar values in include() ... in
> ...Crypt/RSA/PKCS1.php

If I'm writing

   ` $rsa = new Crypt_RSA();` as this example http://phpseclib.sourceforge.net/x509/guide.html
I have an error:

> Class 'Crypt_RSA' not found in ...my_module.

 What I do wrong?

The version phpseclib from this https://github.com/phpseclib/phpseclib from master branch

php -v is 5.3

**Comment by rommeq** [comment]
I had an error with my version of PHP.

**Comment by terrafrost** [comment]
The master branch shouldn't be used. It is under active development and it's API may change significantly from commit to commit.

**Comment by bantu** [comment]
I take it that this can be closed. On a side note, the readme file now contains descriptions of branches.
