### ISSUE TITLE
SSH2 Login Failed

### ISSUE THREAD

**Issue by MoAlyan** [phpseclib/phpseclib#1081]
Hi,
I am using phpseclib 1.0.5 - SSH2 and it always says login failed, here its my code

```php
include('phpseclib/Net/SSH2.php');
define('NET_SSH2_LOGGING', NET_SSH2_LOG_COMPLEX);

class Buzlin_Createstore_TrialController extends Mage_Core_Controller_Front_Action
{
	public function createAction()
	{
			$ssh = new Net_SSH2('server ip');
			if (!$ssh->login('user', 'pass')) {
				print_r($ssh->getLog());
				exit('Login Failed');
			}
			echo 'logged in';
	}
}
```
**Log:**
[Pastebin](http://pastebin.com/raw/07dfxVFG)

**Putty SSH Packets (if needed)**
[Pastebin](http://pastebin.com/raw/es0vavdz)

**php info**
[php info](http://buzlin.live/phpinfo.php)

**Comment by terrafrost** [comment]
You're not using 1.0.5. From your phpseclib logs:

```
->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:30:2e:32:20:28:6d:63:72:79:70:74:2c:20:67  b_0.2 (mcrypt, g
00000020  6d:70:29:0d:0a                                   mp)..
```
Note the 0.2 bit. phpseclib 1.0.5 identifies itself as 1.0 per this:

https://github.com/phpseclib/phpseclib/blob/1.0.5/phpseclib/Net/SSH2.php#L1151

phpseclib 1.0.0 identified itself as 0.3 per this:

https://github.com/phpseclib/phpseclib/blob/1.0.0/phpseclib/Net/SSH2.php#L1137

phpseclib 0.3.0 identified itself as 0.3 as well per this:

https://github.com/phpseclib/phpseclib/blob/0.3.0/phpseclib/Net/SSH2.php#L201

In fact the last version of phpseclib to identify itself as 0.2 was 0.2.2:

https://github.com/phpseclib/phpseclib/blob/0.2.2/phpseclib/Net/SSH2.php#L177

0.2.2 is almost six years old.

More evidence that you're not running an ancient version of phpseclib can be found in the outgoing NET_SSH2_MSG_KEXINIT packet. 0.3.5 added support for blowfish and yet the outgoing NET_SSH2_MSG_KEXINIT packet doesn't mention blowfish. 1.0.0 added support for diffie-hellman-group-exchange-sha{1,256} and yet that's not in the outgoing packet either.

So the first thing I'd try: upgrading your version of phpseclib.

**Comment by MoAlyan** [comment]
ops, you are right. include was using phpseclib that installed with magento by default.
but i replaced the files and now it's working fine. Thank you

keep up the good work 👍
