### ISSUE TITLE
composer necessary?

### ISSUE THREAD

**Issue by s22l1g11** [phpseclib/phpseclib#1091]
Hey!
I just wanted to update phpseclib from 1.0.5 to 2.0.4 but saw, that you recommend to install it via composer. Well I didn't do that and pressed on. 
After some troubleshooting every file seems to be integrated but now I get the following error:
`Fatal error: Uncaught Error: Class 'AES' not found in`

This is, how I include the file and start the AES class:
`require_once('lib/phpseclib/Crypt/AES.php');
    $aes = new AES(CRYPT_AES_MODE_ECB);`

Do I really have to use composer, or is there another possible way?

**Comment by bantu** [comment]
@s22l1g11 Composer is the recommended approach for installing phpseclib 2.0. However, as 2.0 has no production dependencies onto other composer packages, you can probably get away without composer. phpseclib 2.0 relies on autoloading for loading classes, so you'll need a PSR4 autoloader configured appropriately (https://github.com/phpseclib/phpseclib/blob/2.0/composer.json#L70) or another approach for loading classes (e.g. just loading php files al using include()l).

**Comment by s22l1g11** [comment]
Ok, thanks for the fast reply.
I included in my file AES.php and in AES, as well as in Rijndael I used some of your old code like this:
`
/**
 * Include Crypt_Rijndael
 */
if (!class_exists('Rijndael')) {
    include_once 'Rijndael.php';
}


So, when I just include the bootstrap.php instead of a direct link to AES and so on it should work, right?`

**Comment by s22l1g11** [comment]
It works now!
But somehow dirty...

`require_once('lib/phpseclib/Crypt/Base.php');
require_once('lib/phpseclib/Crypt/Rijndael.php');
require_once('lib/phpseclib/Crypt/AES.php');
$aes = new phpseclib\Crypt\AES(CRYPT_AES_MODE_ECB);`

**Comment by bantu** [comment]
Yes, dirty. I'd suggest you make yourself familiar with the concept of
autoloading.

**Comment by bantu** [comment]
Also see e.g. https://github.com/php-fig/fig-standards/blob/master/accepted/PSR-4-autoloader-examples.md

**Comment by bantu** [comment]
I think this can be closed.
