### ISSUE TITLE
version 1.0 the include path is all error

### ISSUE THREAD

**Issue by snails118** [phpseclib/phpseclib#1101]
version 1.0 the include path is all error, and the name style is so terribly

**Comment by snails118** [comment]
and the name style is so terribly

**Comment by terrafrost** [comment]
I'm not sure if you're asking a question or making a complaint.

If the former...  here's how you do include path's:

```php
<?php
set_include_path(get_include_path() . PATH_SEPARATOR . 'phpseclib');

include('Net/SSH2.php');
?>
```

If the later then try the 2.0 branch. I'm not gonna break BC because someone on the internet said I should.
