### ISSUE TITLE
 Fatal error: Cannot redeclare class Math_BigInteger in /home/

### ISSUE THREAD

**Issue by weltonwe** [phpseclib/phpseclib#1106]
Fatal error: Cannot redeclare class Math_BigInteger in /home/xxxxxxxxxxx /modules/servers/w3esxi/libs/Math/BigInteger.php on line 193

**Comment by terrafrost** [comment]
You'll need to share some code. I mean, I can reproduce the issue easily enough:

```php
<?php
include('Math/BigInteger.php');
include('Math/BigInteger.php');
```

If that's what you were doing I'd suggest either deleting one of the `include`'s or replacing both with `include_once`. But as is idk what you're doing. Based on the error you've posted you could be doing exactly what my code snippet is doing - I have no way of knowing.
