### ISSUE TITLE
Fatal error: Arrays are not allowed in class constants 

### ISSUE THREAD

**Issue by hifiSteven** [phpseclib/phpseclib#1107]
Hi, I am implementing your library in a project and I have and I get the error:

Fatal error: Arrays are not allowed in class constants in /phpseclib/File/ASN1.php on line 197

I run php version 5.5.30 - so it should be compatible w/ the latest version of phpseclib, right? Yet, I found out that using arrays in constants is only available from 5.6? 

Any ideas?

**Comment by bantu** [comment]
You're probably using the master branch, which you probably should not. See
README.

**Comment by hifiSteven** [comment]
thank you for your reply, that is probably it
