### ISSUE TITLE
No compatible server to client encryption algorithms

### ISSUE THREAD

**Issue by Gabyfle** [phpseclib/phpseclib#1108]
Hello ! I want try this library but there is a problem when I've tried to connect to my private server : 
`[25-Mar-2017 10:31:32 Europe/Paris] PHP Notice:  No compatible server to client encryption algorithms found in /home/test/public_html/ssh/Net/SSH2.php on line 1388`

I've see all posts who are speaking about this but nothing fixe this error. Here my `define('NET_SSH2_LOGGING', 3);`
`<-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  36:2e:30:70:31:20:44:65:62:69:61:6e:2d:34:0d:0a  6.0p1 Debian-4..

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:31:2e:30:20:28:6f:70:65:6e:73:73:6c:2c:20  b_1.0 (openssl, 
00000020  67:6d:70:29:0d:0a                                gmp)..

<- NET_SSH2_MSG_KEXINIT (since last: 0.207, network: 0.0011s)
00000000  e1:73:8b:76:f4:56:9f:4b:a1:5f:4a:17:00:97:d4:06  .s.v.V.K._J.....
00000010  00:00:00:b7:65:63:64:68:2d:73:68:61:32:2d:6e:69  ....ecdh-sha2-ni
00000020  73:74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32  stp256,ecdh-sha2
00000030  2d:6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73  -nistp384,ecdh-s
00000040  68:61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66  ha2-nistp521,dif
00000050  66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75  fie-hellman-grou
00000060  70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35  p-exchange-sha25
00000070  36:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e  6,diffie-hellman
00000080  2d:67:72:6f:75:70:2d:65:78:63:68:61:6e:67:65:2d  -group-exchange-
00000090  73:68:61:31:2c:64:69:66:66:69:65:2d:68:65:6c:6c  sha1,diffie-hell
000000a0  6d:61:6e:2d:67:72:6f:75:70:31:34:2d:73:68:61:31  man-group14-sha1
000000b0  2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d  ,diffie-hellman-
000000c0  67:72:6f:75:70:31:2d:73:68:61:31:00:00:00:23:73  group1-sha1...#s
000000d0  73:68:2d:72:73:61:2c:73:73:68:2d:64:73:73:2c:65  sh-rsa,ssh-dss,e
000000e0  63:64:73:61:2d:73:68:61:32:2d:6e:69:73:74:70:32  cdsa-sha2-nistp2
000000f0  35:36:00:00:00:9d:61:65:73:31:32:38:2d:63:74:72  56....aes128-ctr
00000100  2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73:32  ,aes192-ctr,aes2
00000110  35:36:2d:63:74:72:2c:61:72:63:66:6f:75:72:32:35  56-ctr,arcfour25
00000120  36:2c:61:72:63:66:6f:75:72:31:32:38:2c:61:65:73  6,arcfour128,aes
00000130  31:32:38:2d:63:62:63:2c:33:64:65:73:2d:63:62:63  128-cbc,3des-cbc
00000140  2c:62:6c:6f:77:66:69:73:68:2d:63:62:63:2c:63:61  ,blowfish-cbc,ca
00000150  73:74:31:32:38:2d:63:62:63:2c:61:65:73:31:39:32  st128-cbc,aes192
00000160  2d:63:62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c  -cbc,aes256-cbc,
00000170  61:72:63:66:6f:75:72:2c:72:69:6a:6e:64:61:65:6c  arcfour,rijndael
00000180  2d:63:62:63:40:6c:79:73:61:74:6f:72:2e:6c:69:75  -cbc@lysator.liu
00000190  2e:73:65:00:00:00:9d:61:65:73:31:32:38:2d:63:74  .se....aes128-ct
000001a0  72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73  r,aes192-ctr,aes
000001b0  32:35:36:2d:63:74:72:2c:61:72:63:66:6f:75:72:32  256-ctr,arcfour2
000001c0  35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c:61:65  56,arcfour128,ae
000001d0  73:31:32:38:2d:63:62:63:2c:33:64:65:73:2d:63:62  s128-cbc,3des-cb
000001e0  63:2c:62:6c:6f:77:66:69:73:68:2d:63:62:63:2c:63  c,blowfish-cbc,c
000001f0  61:73:74:31:32:38:2d:63:62:63:2c:61:65:73:31:39  ast128-cbc,aes19
00000200  32:2d:63:62:63:2c:61:65:73:32:35:36:2d:63:62:63  2-cbc,aes256-cbc
00000210  2c:61:72:63:66:6f:75:72:2c:72:69:6a:6e:64:61:65  ,arcfour,rijndae
00000220  6c:2d:63:62:63:40:6c:79:73:61:74:6f:72:2e:6c:69  l-cbc@lysator.li
00000230  75:2e:73:65:00:00:00:a7:68:6d:61:63:2d:6d:64:35  u.se....hmac-md5
00000240  2c:68:6d:61:63:2d:73:68:61:31:2c:75:6d:61:63:2d  ,hmac-sha1,umac-
00000250  36:34:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68  64@openssh.com,h
00000260  6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61  mac-sha2-256,hma
00000270  63:2d:73:68:61:32:2d:32:35:36:2d:39:36:2c:68:6d  c-sha2-256-96,hm
00000280  61:63:2d:73:68:61:32:2d:35:31:32:2c:68:6d:61:63  ac-sha2-512,hmac
00000290  2d:73:68:61:32:2d:35:31:32:2d:39:36:2c:68:6d:61  -sha2-512-96,hma
000002a0  63:2d:72:69:70:65:6d:64:31:36:30:2c:68:6d:61:63  c-ripemd160,hmac
000002b0  2d:72:69:70:65:6d:64:31:36:30:40:6f:70:65:6e:73  -ripemd160@opens
000002c0  73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:31  sh.com,hmac-sha1
000002d0  2d:39:36:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:00  -96,hmac-md5-96.
000002e0  00:00:a7:68:6d:61:63:2d:6d:64:35:2c:68:6d:61:63  ...hmac-md5,hmac
000002f0  2d:73:68:61:31:2c:75:6d:61:63:2d:36:34:40:6f:70  -sha1,umac-64@op
00000300  65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73  enssh.com,hmac-s
00000310  68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61  ha2-256,hmac-sha
00000320  32:2d:32:35:36:2d:39:36:2c:68:6d:61:63:2d:73:68  2-256-96,hmac-sh
00000330  61:32:2d:35:31:32:2c:68:6d:61:63:2d:73:68:61:32  a2-512,hmac-sha2
00000340  2d:35:31:32:2d:39:36:2c:68:6d:61:63:2d:72:69:70  -512-96,hmac-rip
00000350  65:6d:64:31:36:30:2c:68:6d:61:63:2d:72:69:70:65  emd160,hmac-ripe
00000360  6d:64:31:36:30:40:6f:70:65:6e:73:73:68:2e:63:6f  md160@openssh.co
00000370  6d:2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c:68  m,hmac-sha1-96,h
00000380  6d:61:63:2d:6d:64:35:2d:39:36:00:00:00:15:6e:6f  mac-md5-96....no
00000390  6e:65:2c:7a:6c:69:62:40:6f:70:65:6e:73:73:68:2e  ne,zlib@openssh.
000003a0  63:6f:6d:00:00:00:15:6e:6f:6e:65:2c:7a:6c:69:62  com....none,zlib
000003b0  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:00  @openssh.com....
000003c0  00:00:00:00:00:00:00:00:00                       .........

-> NET_SSH2_MSG_KEXINIT (since last: 0.002, network: 0s)
00000000  82:8e:9c:68:56:6f:4a:4d:b5:72:04:82:d3:e3:b3:42  ...hVoJM.r.....B
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  56....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:00:00:00:00:00:00:00:00  h-dss...........
000000b0  39:68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68  9hmac-sha2-256,h
000000c0  6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63  mac-sha1-96,hmac
000000d0  2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39  -sha1,hmac-md5-9
000000e0  36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:39:68:6d  6,hmac-md5...9hm
000000f0  61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63  ac-sha2-256,hmac
00000100  2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68  -sha1-96,hmac-sh
00000110  61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68  a1,hmac-md5-96,h
00000120  6d:61:63:2d:6d:64:35:00:00:00:04:6e:6f:6e:65:00  mac-md5....none.
00000130  00:00:04:6e:6f:6e:65:00:00:00:00:00:00:00:00:00  ...none.........
00000140  00:00:00:00                                      ....

`

And my code : 
`	define('NET_SSH2_LOGGING', 3);
	include 'Net/SSH2.php';
	
	$ssh = new Net_SSH2('IP.IP.IP.IP.IP');
	if (!$ssh->login('root', 'efgef')) {
		exit('Login Failed');
	}
	echo $ssh->exec('pwd');
	echo $ssh->exec('ls -la');`

**Comment by bantu** [comment]
@GabrielEnraged phpseclib's SSH2 class can not find any usable ciphers. How did you install phpseclib? If you only downloaded and included SSH2.php, that is why. I'd recommend using phpseclib 2.0 with autoloading via composer.
