### ISSUE TITLE
Do I have a way to connect my ssh server through the Socks5 agent?

### ISSUE THREAD

**Issue by shirakun** [phpseclib/phpseclib#1130]
我在本地使用tor建立了一个socks5代理
我想通过它来连接我的服务器
但我发现我ssh2_connect()无法通过socks5代理链接
我这找到了phpseclib
phpseclib可以实现它吗
我在本地使用tor建立了一个socks5代理
我想通过它来连接我的服务器
但我发现我ssh2_connect()无法通过socks5代理链接
我这找到了phpseclib
phpseclib可以实现它吗?

I built a Socks5 proxy locally using tor
I want to connect to my server through it
But I found my ssh2_connect () failed to link through the Socks5 proxy
I found it, phpseclib
Can phpseclib implement it?

**Comment by terrafrost** [comment]
You can cal `fsockopen`, do whatever prep work to it is necessary, and then pass that to the constructor as the only parameter and connect that way. https://github.com/phpseclib/phpseclib/issues/1117#issuecomment-295662545 demonstrates the concept with a CONNECT proxy.

**Comment by terrafrost** [comment]
#1460 demos SOCKS5 proxy support.
