### ISSUE TITLE
Is it safe to continue, if random_bytes fails in Crypt/Random.php?

### ISSUE THREAD

**Issue by oittaa** [phpseclib/phpseclib#1133]
Maybe it'd be better to just throw an exception, if `random_bytes` fails to read in [Crypt/Random.php](https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/Random.php).

**Comment by terrafrost** [comment]
Well that'd be a pretty major BC break. Maybe phpseclib should also refuse to do any crypto if OpenSSL is available (again a major BC break).

If you have a specific issue with the fallback option phpseclib please elaborate but BC breaks are pretty much non-starters save for in the master branch.
