### ISSUE TITLE
Bug fixing

### ISSUE THREAD

**Issue by rmmohamedi** [phpseclib/phpseclib#1135]
( ! ) Notice: Undefined variable: error in login.php on line 70

//The variable is defined in line 26

<?php
 include("config.php");
 session_start();

 if($_SERVER["REQUEST_METHOD"] == "POST") {
 // username and password sent from form

 $myusername = mysqli_real_escape_string($db,$_POST['username']);
 $mypassword = mysqli_real_escape_string($db,$_POST['password']);

 $sql = "SELECT id FROM login_admin WHERE user_name = '$myusername' and user_pass = '$mypassword'";
 $result = mysqli_query($db,$sql);
 $row = mysqli_fetch_array($result,MYSQLI_ASSOC);
 //$active = $row['active'];

 $count = mysqli_num_rows($result);

 // If result matched $myusername and $mypassword, table row must be 1 row

 if($count==1) {
 $_SESSION["myusername"];
 $_SESSION['login_user']=$myusername;

 header("location: welcome.php");
 }else {
 $error="Your Login Name or Password is invalid";
 }
 }
?>
<html>

 <head>
 <title>Login Page</title>

 <style type = "text/css">
 body {
 font-family:Arial, Helvetica, sans-serif;
 font-size:14px;
 }

 label {
 font-weight:bold;
 width:100px;
 font-size:14px;
 }

 .box {
 border:#666666 solid 1px;
 }
 </style>

 </head>

 <body bgcolor = "#FFFFFF">
<div align = "center">
 <div style = "width:300px; border: solid 1px #333333; " align = "left">
 <div style = "background-color:#333333; color:#FFFFFF; padding:3px;"><b>Login</b></div>

 <div style = "margin:30px">

 <form action = "" method = "post">
 <label>UserName :</label><input type = "text" name = "username" class = "box"/><br
/><br />
 <label>Password :</label><input type = "password" name = "password" class = "box"
/><br/><br />
 <input type = "submit" value = " Submit "/><br />
 </form>

 <div style = "font-size:11px; color:#cc0000; margin-top:10px">
 <?php echo $error;?>
 </div>

 </div>

 </div>

 </div>
 </body>
</html>

**Comment by terrafrost** [comment]
Like the error message says, the error you're reporting is in login.php. phpseclib doesn't have a file named that...

I mean, I guess you could post your login.php, but keep in mind, this really doesn't look like a phpseclib issue atm...

**Comment by rmmohamedi** [comment]
Thanks for your comment @terrafrost, finally i managed to fix the error. I fixed it by commenting the header line  which was initially not commented. When you use Macromedia Dreamweaver automatically the header codes showing DocType, language Translational etc is created automatically. Therefore when you use header location anywhere in code a header limiter error results.

I appreciate your contribution
