### ISSUE TITLE
test Unit_File_X509_X509Test::testUtcTimeWithoutSeconds requires date.timezone to be unset

### ISSUE THREAD

**Issue by bleve** [phpseclib/phpseclib#1139]
There is a problem in test Unit_File_X509_X509Test::testUtcTimeWithoutSeconds. That test only runs successfully if date.timezone is set to UTC or unset. I tested with date.timezone = Europe/Helsinki and test failed.
If UTC is required, date.timezone should really be set to UTC in test.

This issue is in version 2.0.6. 2.0.4 didn't have this test or test worked with date.timezone set.

**Comment by remicollet** [comment]
>  If UTC is required, date.timezone should really be set to UTC in test.

See https://github.com/phpseclib/phpseclib/blob/master/tests/bootstrap.php#L8

So timezone is properly set to UTC for the test suite.
