### ISSUE TITLE
SFTP data integrity: some packets full of null bytes

### ISSUE THREAD

**Issue by lewa** [phpseclib/phpseclib#1147]
I ran into a data integrity issue today: got 64K of null bytes in a 200+ MB file via Net\SFTP::get('remote.file', 'local.file'). Never happened before, nor after. Got it right on retry in a couple of minutes.

File size: 239 977 550 bytes (is correct).

File content: 33 685 504 correct bytes + 65 536 null bytes + 206 226 510 correct bytes.

Is this a known issue?

It seems fputs($fp, $temp) in Net\SFTP::get() did write 1 052 672 "correct" 32-KB chunks, then 2 "null" 32-KB chunks, then the rest of the file. No errors, no warnings.

getServerIdentification() says "SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.8"

phpseclib 2.0.6

**Comment by terrafrost** [comment]
It's the first I've heard of an issue like this.

If *I* were able to reproduce the problem I'd create real time logs and log them to a file. But for a 239mb file those real time logs could possibly be in the gigabytes. None-the-less, I'd parse through them and try to identify what happened. But as is it sounds like you're maybe not able to reproduce the issue? And even if you were getting me multi gigabyte logs could be difficult.

I guess one thing you could do is tell me what `$ssh->getErrors()` returns. It'll return an array but what's in the array?

**Comment by lewa** [comment]
I've been downloading gigabytes without issues; I've got to be very (un)lucky to get the nulls again any time soon. However, I will enable the logging to have some food for thought next time the null bytes occur.

PS there's an undefined class constant LOG_REALTIME_FILENAME in SSH2.php; fixed in the master branch though.

**Comment by terrafrost** [comment]
> PS there's an undefined class constant LOG_REALTIME_FILENAME in SSH2.php; fixed in the master branch though.

You're supposed to define that yourself.

I don't actually like the way logging works too much in the 1.0 / 2.0 branches. The master branch (which will eventually become the 3.0 branch) is due for a complete logging revamp. idk, off hand, what the master branch does to "fix" it since it's not being defined doesn't really constitute broken behavior.

Quoting Net/SSH2.php:

```
            // basically the same thing as self::LOG_REALTIME with the caveat that NET_SFTP_LOG_REALTIME_FILENAME
            // needs to be defined and that the resultant log file will be capped out at self::LOG_MAX_SIZE.
            // the earliest part of the log file is denoted by the first <<< START >>> and is not going to necessarily
            // at the beginning of the file
```

**Comment by lewa** [comment]
NET_SFTP_LOG_REALTIME_FILENAME vs self::LOG_REALTIME_FILENAME

The difference between the master branch and the 2.0 branch: it's a class constant in the latter.

**Comment by Sxderp** [comment]
Not to be dismissive, but are you sure the bytes were sent correctly, that is, no errors on the sender side? 

Don't know if you'd be able to check that easily. Though, if this is a problem with phpseclib, it's interesting nevertheless.

**Comment by lewa** [comment]
I don't have access to the sending server, apart from SFTP. The only thing I am sure about is that the file had no null bytes on the sending server (it is immensely unlikely that they could disappear between the two back-to-back download attempts with the modification time intact) and that the file had null bytes on the receiving server.

**Comment by lewa** [comment]
Never happened again. Case closed.
