### ISSUE TITLE
SFTP put operation fails if used with remote file stream as resource

### ISSUE THREAD

**Issue by mirfilip** [phpseclib/phpseclib#1177]
Hi,
I'm using version `2.0.6` of `phpseclib` via `flysystem-sftp` (bridge/adapter for flysystem).

I want to "stream" a remote file directly to sftp server, avoiding disk usage on a machine I run the script on. For that, I:
1. `fopen` a remote file using `http` stream wrapper
2. Executing `SFTP::put` with opened remote file handle as `$data`

```
$remoteFileStream = fopen(
    'http://www.example.org/someResource.mp4',
    'r'
);
$sftpFilesystem = new \phpseclib\Net\SFTP($host, $port, 30);
$loginSuccess = $sftpFileSystem->login($user, $pass);
if ($loginSuccess) {
   $success = $sftpFilesystem->put('/path/to/remote/file.mp4', $remoteFileStream);
   var_dump($success); // true but empty file is created
}
```
**The result is an empty file created on sftp server.** 

Reading [documentation](http://phpseclib.sourceforge.net/sftp/examples.html#put), I have noticed a `SOURCE_LOCAL_FILE` mode. I have already seen #1119 which treats about somewhat similar case, but for local files.

Conceptually, I'd expect [this case](https://github.com/phpseclib/phpseclib/blob/2.0.6/phpseclib/Net/SFTP.php#L1917) to handle that.

Is that the case that `put` with remote file as a stream is not supported?

**Comment by mirfilip** [comment]
Crux of the problem seems to be a failure of [reading http stream stats with fstat](https://github.com/phpseclib/phpseclib/blob/2.0.6/phpseclib/Net/SFTP.php#L1940). It returns `false`.

There is a disclaimer on [docs page](http://php.net/manual/en/function.fstat.php):
>Note: This function will not work on remote files as the file to be examined must be accessible via the server's filesystem.

A simple snippet to reproduce:
```
$remoteFileStream = fopen(
    'http://www.example.org/',
    'r'
);
$stats = fstat($remoteFileStream);
var_dump($stats); // false
```

Of course, handling remote streams bears more questions like resumes via range header, efficiently copying it chunk by chunk, as it's not viable to just copy the remote stream to memory stream.

**Comment by bantu** [comment]
There is a stream wrapper for phpseclib's SFTP implementation which you
might want to use as a workaround.
https://github.com/phpseclib/phpseclib/blob/2.0.6/
phpseclib/Net/SFTP/Stream.php

**Comment by mirfilip** [comment]
Here is my usage example of stream wrapper:
```
<?php
$remoteFileStream = fopen(
    'http://www.example.org/,
    'r'
);

$to = "test123.txt";
\phpseclib\Net\SFTP\Stream::register();
$sftpFilesystem = new \phpseclib\Net\SFTP($hostname, $port, 30);
if (!$sftpFilesystem->login($user, $pass)) {
    exit(1);
}

$context = [
    'sftp' => [
        'sftp' => $sftpFilesystem
    ],
];
$sftpStream = fopen("sftp://upload/$to", 'w+', null, stream_context_create($context));
if (!$sftpStream) {
    exit(1);
}

$bytes = stream_copy_to_stream($remoteFileStream, $sftpStream);

if ($bytes > 0) {
 exit(0);
} else {
    exit(1);
}
```

It indeed works, but file gets uploaded to root directory instead. I'm fiddling with that nuisance now.

**Comment by bantu** [comment]
Guessing: sftp://host/./path to upload to home/pwd.

**Comment by mirfilip** [comment]
@bantu 👏 
Indeed, changing to `fopen("sftp://./upload/$to", 'w+, ...)` handles that. I pass host, port, user, pass directly to `SFTP` instance.

I just wish interaction via `Stream` wrapper was documented. Maybe I'll contribute with some simplest use case.

Also, how about disallowing using remote streams with `SFTP` methods if they don't handle that? At very least, I feel it should return success false in that case.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/deb485c0e1e32de4408d3d5e69ab64366abc7ff8 seemed to fix the issue for me.

**Comment by mirfilip** [comment]
@terrafrost Thank you. 

I confirm https://github.com/phpseclib/phpseclib/commit/deb485c0e1e32de4408d3d5e69ab64366abc7ff8 fixes the issue.

Now using a stream wrapper and `put` both work.
