### ISSUE TITLE
RSA md5 PKCS1 generated signature is not the same as C# generated

### ISSUE THREAD

**Issue by UniFreak** [phpseclib/phpseclib#1183]
here is the code of C# to generate a signature: https://ideone.com/2o52vC
here is my php code: https://ideone.com/FUCrE7

they both use md5 hash and PKCS1 mode, but I got two different result. the C#'s signature is 

```
Ds2jUTToMlg8ReNmr5G+s6INTBmEaNNYaWc2l1Tj0i76Twm0HZAE3LpovdEsJRqgJ5pVynGdSLgYi4NOVj2Yk1ZfNYg5bBXVseSkaFAlyF0GdSrSEw0Z3mHiCutH6Sb1ZqiSQUHvA3tdpPvKU4G7mqi/qAoXgLY4o/C92+nLnKg=
```

well the php generated is 

```
LVIQ9BfvzR9oHIGp9nmmB0S2kU9gqb9YKSeS9KPVy4fMRICL/AkMCegAYosNX3kvcoY6ncUO2JMCyWyayNG1gHsH+49uux+10G20Um5EozH+h+pwFddIsB68swWwttJlz5eS4ohaTeFRDlgqKzLiCoq9iDqOWuyNx40xHlSf6sU=
```

I wonder why this happen, and how to make them the same.

**Comment by terrafrost** [comment]
I was able to get the PHP signature to match the C# one by doing this:

```php
#
#-----[ FIND ]------------------------------------------
#
$md5 = md5($gb2312, true);
$base64 = base64_encode($md5);
#
#-----[ REPLACE WITH ]----------------------------------
#
$base64 = base64_encode($gb2312);
```

eg. your PHP code is essentially double md5 encoding the data you're trying to sign whereas the C# code you're using isn't. It's like the C# code could let you create a signature that's signed by a different hash than it actually is whereas the PHP code doesn't. Or maybe the C# code throws an exception when you try to do that idk.

**Comment by UniFreak** [comment]
Although I don't know why, and don't quite understand your explanation, as I see it, the C# md5 twice. but that indeed solve the problem. So it's not a phpseclib problem. Thanks :)
