### ISSUE TITLE
Mocking RSA with load method

### ISSUE THREAD

**Issue by ShahidH** [phpseclib/phpseclib#1185]
I think this might be a design bug in the phpseclib library on the master branch (aka develop branch).

If I try to mock RSA with a `load` method:
```
$rsaMock = m::mock('phpseclib\Crypt\RSA');
$rsaMock->shouldReceive('load')->with('keystuff')->once();
```

I get an error on the console:

> InvalidArgumentException: load() cannot be mocked as it a protected method and mocking protected methods is not allowed for this mock

The RSA class is inheriting from `AsymetricKey` which have a protected load().

**Comment by terrafrost** [comment]
Nice find! I'll try to fix this as time permits. I'm traveling Europe right now (just a few more days left on this trip) so I'm a bit distracted with that but I'll try to remember to fix this after I'm done.

Thanks!

**Comment by terrafrost** [comment]
Should be working better now:

https://github.com/phpseclib/phpseclib/commit/af6048b48e25187e549136195a3df67571b22fd0

Thanks!
