### ISSUE TITLE
Documentation Down/Missing

### ISSUE THREAD

**Issue by timothymarois** [phpseclib/phpseclib#1187]
http://phpseclib.sourceforge.net/

No longer exist.

**Comment by terrafrost** [comment]
Looks like it's working to me. My guess: sourceforge.net had a temporary outage.

**Comment by timothymarois** [comment]
Interesting, on another device and location I’m getting this, like DNS for that sub domain doesn’t exist. 

![248b45d3-570f-434b-92c4-de0f76cff924](https://user-images.githubusercontent.com/2489333/31014902-3e3a1e7c-a4eb-11e7-8af8-dc9721566f0a.png)

**Comment by terrafrost** [comment]
I think sourceforge.net is just acting up today. I think this is causing intermittent issues with the PEAR channel as well:

https://github.com/phpseclib/phpseclib/issues/1188
