### ISSUE TITLE
Slow downloads (using version 2.0.6)

### ISSUE THREAD

**Issue by MrProvolone** [phpseclib/phpseclib#1189]
Hello!  Thanks for a great library! I apologize if this is a duplicate issue I tried to make sure it isn't...

My problem is that I can't get the download to run more than 100kb/s.  I am using 'new SFTP()' and $sftp->get().

I have tried tinkering with the max_sftp_packet value (both on the bitwise operator and by setting it manually) and I have tinkered with the NET_SFTP_QUEUE_SIZE to no avail.  When I download the file manually through filezilla I get it at 10mb/s (my usual download speed). 

Have you ever seen this before?  Any help would be appreciated!

**Comment by terrafrost** [comment]
Could relate to the cipher's that are being used and what extensions you have available locally (eg. mcrypt, OpenSSL, bcmath, gmp, etc). Could you get me the server logs? You can get them by doing `define('NET_SSH2_LOGGING', 2);` and then `echo $sftp->getLog();` afterwards. Maybe do that for a 100kb file or something.

**Comment by terrafrost** [comment]
Closed due to inactivity.
