### ISSUE TITLE
SFTP - Connect - Invalid

### ISSUE THREAD

**Issue by faca5** [phpseclib/phpseclib#1191]
Hello.

We got this error.

PHP code:
		$sftp = new Net_SFTP($host);
		if (!$sftp->login($user, $pass)) {
		  exit('Login Failed');
		}

Error:
PHP Notice:  Invalid size in Net\SSH2.php on line 2721
PHP Notice:  Connection closed by server in Net\SSH2.php on line 1865 

Output:
Login Failed

phpseclib downloaded via http://phpseclib.sourceforge.net/sftp/intro.html.

Any idea how to fix?

Thank you!

**Comment by terrafrost** [comment]
Seems like this could be the same thing as #1171. If so then try the latest git version of phpseclib. The 1.0 branch.

**Comment by terrafrost** [comment]
Closed due to inactivity.
