### ISSUE TITLE
Read tail -f output in PTY

### ISSUE THREAD

**Issue by P4sca1** [phpseclib/phpseclib#1195]
I want to echo the output of a remote tail -f command. It works fine with the exec callback, however I need to run tail in a pseudo-terminal, so I enabled PTY, which disables the exec callback. Another reason why I can't use the existing callback is, that I need my own logic in the while loop. Here's my code for better understanding:

I have a function called tailScreenLog:
```
public function tailScreenLog()
    {
        set_time_limit(0);

        $this->disableOutputBuffer();

        if ($this->masterServer->sshConnect()) {
            $ssh = $this->masterServer->sshObject;
            $ssh->enablePTY();
            $ssh->setTimeout(0);

            $command = "/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 ";
            $command .= "sudo -u " . $this->username() . " ";
            $command .= "/home/master/scripts/useraction.sh gameserver_tail_screenlog " . $this->game_short;

            $ssh->write($command . "\n");

            return $ssh;        
        }

        return false;
    }
````

And here's the code that uses the function:
```
    public function screenLog(GameServer $gameServer)
    {
        $this->checkPermission($gameServer);

        $ssh = $gameServer->tailScreenLog();
        $lastAbortCheck = 0;

        if ($ssh !== false) {
            while (true) {
                $time = microtime(true);

                // only do the abort Check once every second
                if ($lastAbortCheck + 1 < $time) {
                    echo "abort check"; // we need to echo something for PHP's user abort system to work
                    $lastAbortCheck = $time;
                }

                // echo everything that ssh has read, if there is any output
                // basically we would need the same functionality that the package handler provides here.
                // I tried $ssh->read() here, but that does not work.
            }   
        }
    }
```

**Comment by P4sca1** [comment]
I am using it for tail -f.
Would be perfect if something like this works.

while (true) {
// get ssh pty output here
}

**Comment by P4sca1** [comment]
I updated my issue to include more details.

**Comment by P4sca1** [comment]
I guess the read() function waits for the write() function to finish, but because tail -f never finishes, I do not get any output. If that's true I would need a function (e.g. tempRead()) to read the output that has been produced since the last tempRead() call. I think the exec command callback is doing exactly that,  but I do not really understand the code. Would it be possible to implement a tempRead() function? @terrafrost

**Comment by P4sca1** [comment]
Here's a solution with php's ssh2 library:

```
public function tailScreenLog()
    {
        set_time_limit(0);

        $this->disableOutputBuffer();

        if ($ssh = ssh2_connect($this->masterServer->ip, 22)) {
            if (ssh2_auth_password($ssh, "username", $this->masterServer->password)) {
                $stream = ssh2_shell($ssh); // request an interactive shell

                $command = "/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 ";
                $command .= "sudo -u " . $this->username() . " ";
                $command .= "/home/master/scripts/useraction.sh gameserver_tail_screenlog " . $this->game_short;

                stream_set_blocking($stream, false);

                fwrite($stream, $command . PHP_EOL);

                return $stream;
            }
        }

        return false;
    }
```

```
$stream = $gameServer->tailScreenLog();
        $lastAbortCheck = 0;
        $isTailOutput = false;

        if (is_resource($stream)) {
            while (true) {
                $time = microtime(true);

                // only do the abort Check once every second
                if ($lastAbortCheck + 1 < $time) {
                    echo "abort check"; // we need to echo something for PHP's user abort system to work
                    $lastAbortCheck = $time;
                }
                
                // **basically this part is what I am missing in phpseclib!**
                if ($content = fgets($stream)) {
                    echo $content == "success";
                    if (! $isTailOutput && strpos($content, "success") !== false) {
                        $isTailOutput = true;
                    } elseif ($isTailOutput) {
                        echo str_replace("\n", "<br>", $content);
                    }
                }
            }
        }
```

**Comment by terrafrost** [comment]
A few things.

First, you don't need to do `$ssh->enablePTY()` with `$ssh->write()`. `$ssh->enablePTY)` lets `$ssh->exec()` use a PTY, after which you'd need to use `$ssh->read()`.

> I guess the read() function waits for the write() function to finish, but because tail -f never finishes, I do not get any output.

That is incorrect. What you _do_ need to do, however, is wait for the prompt. Until the shell presents the prompt sending commands will likely not work.

**Comment by P4sca1** [comment]
Okay, thank you for your answer.
I don't quite get what you meant by that:

> What you do need to do, however, is wait for the prompt. Until the shell presents the prompt sending commands will likely not work.

How can I wait for the prompt?

**Comment by terrafrost** [comment]
Do `$ssh->read('[prompt]');` before you do `$ssh->write("$command\n");`

**Comment by P4sca1** [comment]
Hmm, now the page does not stop loading:

```
if ($this->masterServer->sshConnect()) {
            $ssh = $this->masterServer->sshObject();
            $ssh->setTimeout(0);
            // $ssh->enablePTY(); // not needed for $ssh->write()
            
            $showOldLines = $showOldLines ? "1" : "0";

            $command = "/usr/bin/nice -n 19 /usr/bin/ionice -c2 -n7 ";
            $command .= "sudo -u " . $this->username() . " ";
            $command .= "/home/master/scripts/useraction.sh gameserver_tail_sessionlog ";
            $command .= $this->game_short . " " . $showOldLines;

            $ssh->read('[prompt]'); // wait for the prompt
            $ssh->write($command . "\n");
            echo $ssh->read();

            // return $ssh;
        }
```

**Comment by terrafrost** [comment]
`[prompt]` is a placeholder. It could be that you're not waiting for the right prompt.

Another possibility: there are invisible characters you're not seeing in the prompt. ANSI escape codes for example. Maybe your prompt has color in it and you're waiting for an uncolored string.

One thing you could do to figure out what the prompt is...  do `$ssh->setTimeout(3); echo $ssh->read();`. Or maybe `bin2hex($ssh->read())`.

Another possibility might be to do something like this:

```php
$ssh->setTimeout(1);
$ssh->read();
$ssh->write("command\n");
echo $ssh->read();
```

idk what the exact timeout would need to be.

**Comment by P4sca1** [comment]
> One thing you could do to figure out what the prompt is... do $ssh->setTimeout(3); echo $ssh->read();. Or maybe bin2hex($ssh->read()).

Both things output nothing.

> Another possibility might be to do something like this:
```
$ssh->setTimeout(1);
$ssh->read();
$ssh->write("command\n");
echo $ssh->read();
```
This does not work either, but I noticed that using the code snippet below, will give me the output I want, every 0.1 seconds:
```
$lastCheck = 0;
while (true) {
$time = microtime(true);
if ($lastCheck + 0.1 < $time) {
$ssh->setTimeout(0.1)
echo $ssh->read();
}
}
```

**Comment by terrafrost** [comment]
>> One thing you could do to figure out what the prompt is... do $ssh->setTimeout(3); echo $ssh->read();. Or maybe bin2hex($ssh->read()).
>
> Both things output nothing.

I have no idea what you're connecting to but the only way that would be the case (assuming you're not doing something funky) is if (1) there is no prompt or (2) it's taking the prompt more than 3 seconds to appear.

I mean, I suppose you could have vim in your .bashrc file or something. That'd certainly cause there not to be a prompt but I'd also call that funky.

Anyway, let's try this: get me your log files. You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and then `echo $ssh->getLog()` after the `$ssh->read()` or whatever.

**Comment by P4sca1** [comment]
Okay, weird. No the $ssh->read() returns something. Is this called the prompt?
```
Linux {fqdn} 4.5.2-mod-std-ipv6-64 #8 SMP Tue Apr 26 15:41:39 CEST 2016 x86_64 GNU/Linux server : 719643 ip : {ip} hostname : {fqdn} Last login: Tue Oct 10 20:55:01 2017 from {ip} {user}@{machine}:~$
```

**Comment by Sxderp** [comment]
That looks like a motd + prompt to me.
I think there's probably some newlines in there.

**Comment by terrafrost** [comment]
Closed due to inactivity.
