### ISSUE TITLE
SFTP - File Transfer Load

### ISSUE THREAD

**Issue by totomtornado** [phpseclib/phpseclib#1201]
Sorry ... wasn't sure how to title this.

This is more of a question than an issue.

I am using the library to make a sftp transfer.  Here is my setup....

I have a Raspberry Pi running php and using the library.
I have other machines that all have a network folder(will explain why that matters in a sec.).

I am worried about putting too much stress on my little raspberry pi so I am writing this question in hopes of better understanding how an sftp request with this library works.

I need to use a page run by the pi to call on phpseclib.  Next, I open up the sftp.  Then I want to copy some files from the shared folder on the remote computer to the desktop.  I am also copying a few other smaller files to make a folder for the user with all their goodies.

Both the shared folder(source) and the desktop(destination) are on the same computer.  I will be copying some video files so here is my concern.

Making the copy in this way... do the files have to transfer through the pi or does the pi make the request via sftp and then the files transfer locally?

I am worried that what would happen is that I would be taking files from essentially...

Remote Comp1 >>> Raspberry Pi >>> Back to Remote Comp1 

I don't want to do this.

Is this what is happening when I make an sftp request?

**Comment by terrafrost** [comment]
So you want to use phpseclib from the Raspberry Pi to facilitate the copying of a file from one location on a remote computer to another location on that same computer?

Do you have shell access? If so `$ssh->exec('cp /path/to/file.ext /home/user/Desktop')l` or some such should do the trick.

If you're using SFTP to do the transfer...  you'd have to download the file and then reupload it. That's just how SFTP works. You can't facilitate remote transfers with SFTP. With FTP there's [FXP](https://en.wikipedia.org/wiki/File_eXchange_Protocol) but SFTP has nothing comparable.

**Comment by totomtornado** [comment]
Thanks...

That answers it... sftp would do in fact what I do not want to do...

I should use exec instead in this case....thanks!

 the remote machine is a windows machine and the pi is running ubuntu.  Do
I need to edit the exec statement in anyway to accommodate for this fact?

While researching I saw all kinds of variations on this.  Some used the
native ssh2 library and some used “cmd COMMAND”...
Is calling commandline(cmd) like this necessary with phpseclib and an
ubuntu to windows setup?

Cheers

**Comment by terrafrost** [comment]
>  the remote machine is a windows machine and the pi is running ubuntu.  Do
> I need to edit the exec statement in anyway to accommodate for this fact?

You'd probably need to do `copy c:\path\to\file.ext c:\users\username\Desktop` then or some such.

> While researching I saw all kinds of variations on this.  Some used the
> native ssh2 library and some used “cmd COMMAND”...
> Is calling commandline(cmd) like this necessary with phpseclib and an
> ubuntu to windows setup?

You mean http://php.net/ssh2? I'd have to see an example to provide any insight into what that's all about but no - in phpseclib you shouldn't have to do that.

**Comment by totomtornado** [comment]
Thanks a ton for the insight!  You da bomb!

**Comment by totomtornado** [comment]
Hmmm... this should work... I just can't seem to get the right command.... the path is strange or not formatted correctly...

Here is what I am using:

`$SourceFilePath = "/\/\YOUR-PC/\work_video_files/\teacher_footage_plans/\Room_504/\Final_Videos/\Mystery_by_the_Lake_SP3/\Mystery_by_the_Lake_SP3-TeamNames.txt";
$DestinationFilePath = "C:\Users\W7UK\Desktop";

print_r('<pre>' . var_export($ssh->exec('copy '.$SourceFilePath.' '.$DestinationFilePath), true) . '</pre>');`

BUT I get this error:

> '/bin/sh: copy: command not found
'

Any thoughts on the format for this?

**Comment by totomtornado** [comment]
super hard to paste this code in here as it is....

**Comment by totomtornado** [comment]
Ok... I got this to work using robocopy ... I will post the finished example in a while.....

**Comment by terrafrost** [comment]
A normal Windows shell wouldn't respond with `/bin/sh: copy: command not found`. That's the kind of response I'd expect more on Windows. But who knows what you're using as your SSH server so maybe your SSH server is emulating bash or something idk. I guess to know that I'd need to know what you were using as your SSH server.

Either way it sounds like you got it tho :)

**Comment by totomtornado** [comment]
using openssh
 other commands do not really seem to work well either...
what do you recommend for an ssh server?

**Comment by totomtornado** [comment]
as an example... I can get the copy to work but I can not call a batch file... Again it says command not found.  Perhaps there is a more friendly ssh server I could be using because I do not want to run into these problems all the time.

**Comment by terrafrost** [comment]
`cmd COMMAND` might do the trick actually.

In a "normal" SSH environment it wouldn't be necessary but with OpenSSH on Windows it might be.

As for alternative SSH servers...  bitvise has a Windows one but idk that I've tried the SSH parts of it that much as opposed to just the SFTP parts. There's also Microsoft's port of OpenSSH: https://github.com/PowerShell/Win32-OpenSSH/wiki/Install-Win32-OpenSSH I've used it once but don't have a ton of experience with it.

**Comment by totomtornado** [comment]
This thread kind of took on a new topic.  It is now somewhat more about the proper ssh server software to use with phpseclib and how to interact with it but...

Commands not working...

I tried bitvise and another ssh server software.  They seemed to react strangely as well so I went back to openssh.  I have not tried the cmd idea above yet.

I am wondering if the strange behavior of commands not being recognized might be because of how I login to the ssh session via phpseclib.  I was just using password and username.  Could using an RSA key like the example listed in this link, change things in some way?  
 http://phpseclib.sourceforge.net/2.0.html

It feels like I am getting shutdown on functionality because of permissions.  I have the user setup as an admin on the windows machine so in my mind that would mean opening an ssh session using that user would let me to pretty much anything and any command I could in a native cmd window.  Is that thinking too ambitious?

It is also possible my filepaths are wrong because they are kind of funky.

**Comment by totomtornado** [comment]
When I say openssh... i believe i got my download here... https://www.openssh.com/

It is an exe .. is that different from the git project youlist for openssh?

**Comment by terrafrost** [comment]
So I went ahead and tried `$ssh->exec('copy file1.ext file2.ext');` on Microsoft's OpenSSH port and it worked just fine. I got "_1 file(s) copied_" as the response.

> Could using an RSA key like the example listed in this link, change things in some way?

Not with any SSH server I've ever heard of.

> I have the user setup as an admin on the windows machine so in my mind that would mean opening an ssh session using that user would let me to pretty much anything and any command I could in a native cmd window.

That would really depend on the SSH server and tbh 95% of the servers I SSH into are Linux servers. That said, in my testing of Microsoft's OpenSSH port it does seem to work as you describe.

> When I say openssh... i believe i got my download here... https://www.openssh.com/
>
> It is an exe .. is that different from the git project youlist for openssh?

I didn't see a Windows download at https://www.openssh.com/ when I checked just now, altho apparently the first result for the phrase [openssh server windows](https://www.google.com/search?q=openssh+server+windows) is talking about the Microsoft OpenSSH port.

Anyway, I hate to say it, but your problems are probably beyond the scope of phpseclib. My guess is that you'd have this same problem with any SSH client you tried. If so that would mean that this isn't a problem with phpseclib but rather with the SSH server itself. In that scenario I'd recommend posting on [superuser.com](http://superuser.com) or the support forum for the SSH server you're using or something.

**Comment by totomtornado** [comment]
Yes... i can not quite recall where I found the download for my current
“openssh” server which makes my claim confusing... I know.

I will try the link you recommend instead.  Perhaps I will have better
results.  I will post back after testing.  Also, I will try to figure out
where I got my exe from.  It drove me crazy trying to find it again.  ;)
