### ISSUE TITLE
PHP 7 Errors 

### ISSUE THREAD

**Issue by JudeRosario** [phpseclib/phpseclib#1205]
Hi a end user reports the following errors when using with PHP 7 

```
FILE: /home/CENSORED/public_html/blog/wp-content/plugins/keyy/vendor/phpseclib/phpseclib/phpseclib/File/X509.php
——————————————————————————————————————-
FOUND 4 ERRORS AFFECTING 4 LINES
——————————————————————————————————————-
4660 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
4685 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
4752 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
4824 | ERROR | Using a call-time pass-by-reference is deprecated since PHP 5.3 and prohibited since PHP 5.4
——————————————————————————————————————-
```

**Comment by JudeRosario** [comment]
This is when using with the 1.0 branch

**Comment by terrafrost** [comment]
Let's look at those line numbers. [Line 4660 in 1.0.8](https://github.com/phpseclib/phpseclib/blob/1.0.8/phpseclib/Net/SSH2.php#L4660) and line 4660 in the [most recent commit to the 1.0 branch](https://github.com/phpseclib/phpseclib/blob/ffcff461c4d5ea1686e7265b860bbb9b6a665487/phpseclib/Net/SSH2.php#L4660) is this:

        return $this->exit_status;

[Line 4660 in 1.0.7](https://github.com/phpseclib/phpseclib/blob/1.0.7/phpseclib/Net/SSH2.php#L4660) doesn't exist.

So it's not immediately obvious what line 4660 is supposed to be but even without knowing that I can tell you that this in all likelihood bogus. It seems likely you're using phpcs on phpseclib and you're running into the same issue #337 ran into. eg.

> call-time pass-by-reference is when you do `foo(&$a);` - not when you do `&foo($a);` What phpseclib is doing in the lines of code you mentioned is [returning by reference](http://www.php.net/manual/en/language.references.return.php)

phpseclib is unit tested on Travis CI on PHP versions going up to 7.0. A call-time pass-by-reference would cause the unit tests to fail and yet they're not failing.

The fact that phpseclib needs to use returning by reference and the fact that it works, without any error, be it E_NOTICE or E_DEPRECATED or anything, on versions of PHP up to 7.1, is demonstrated by #772

**Comment by JudeRosario** [comment]
Thanks for the detailed reply @terrafrost ! Appreciate it. I think he meant [this file on 1.0.7](https://github.com/phpseclib/phpseclib/blob/1.0.7/phpseclib/File/X509.php#L4660). 

Specifically this bit

`$rclist = &$this->_subArray($this->currentCert, 'tbsCertList/revokedCertificates')`

I am going to read through the other tickets you referenced and will also check where exactly the end users are getting this. Im inclined to think its a dashboard error on WordPress but will either get back or close this issue once I'm sure.

Thanks for the great work you do !

**Comment by DavidAnderson684** [comment]
@JudeRosario This is a user who's run a static analysis tool on the code-base. The text in your initial report isn't a dashboard notice; it's the output of the tool, run over the code base. These reports are almost always unhelpful when sent by end-users, because they don't understand the tools or their limitations, or how to interpret the results. Both phpseclib and Keyy are run through in-house CI that checks PHP version compatibility. So, almost all the time, you can ignore any such reports and just assure the user that all is well.

**Comment by JudeRosario** [comment]
Thanks @DavidAnderson684 @terrafrost I confirmed this is not a dashboard notice. I have limited experience with static analysis tools and did not recognize the output. Will keep your pointers in mind going forward. Closing this issue !
