### ISSUE TITLE
Net\SSH2.php user_error on login

### ISSUE THREAD

**Issue by MRolefes** [phpseclib/phpseclib#1207]
Hi,

We're currently using release 2.0.7 and are facing the problem that, while using Net\SSH2.php, there is no way we can catch errors on login failure because this generates a user_error.

I've seen this file has had RuntimeException's in the past (f300e825b0c5018415aed803f7e0d24757a35f58) but some merges on Branche 2.0 has been reverted and those has been undone and that has been reverted to the point where I don't know what it 'should' be.. hehe :).

I know on Master it has RuntimeException's, we tested this on a local machine and it worked as expected. Do these changes get released in 2.0.8? If so, do you have a release date?

Thank you,
Maarten

**Comment by terrafrost** [comment]
The 2.0 branch will never throw exceptions as that would be a BC break.

f300e825b0c5018415aed803f7e0d24757a35f58 was me accidentally merging the BC breaking master branch into the 2.0 branch.

If you want to use exceptions with 2.0 might I suggest using `set_error_handler` to throw exceptions when the errors happen? It's not ideal, which is why it was changed in the master branch, but it's the best that's gonna be achievable whilst maintaining BC.

**Comment by tomsommer** [comment]
At what point will phpseclib then switch to Exceptions?

**Comment by terrafrost** [comment]
The version of phpseclib that will switch to using Exceptions already has.

So right now there are three branches of phpseclib. 1.0, 2.0 and master. The master branch will eventually become 3.0 once the API becomes finalized.  More specifically, at that point, I'll do `get checkout -b 3.0 origin/master` and then I'll do `git push origin 3.0`. At that point changes done in the master branch but not in the 1.0, 2.0 or 3.0 branches will not be guaranteed to maintain BC and at some point changes to the master branch will result in a 4.0 release, etc.

Put another way, all the branches save for master seek to maintain BC with themselves.

**Comment by tomsommer** [comment]
What about these user_error() in master?

https://github.com/phpseclib/phpseclib/search?utf8=%E2%9C%93&q=user_error&type=

**Comment by terrafrost** [comment]
The commented out ones are pretty inconsequential as is the one in the unit test. This leaves three that need to be fixed. One in SFTP.php, two in SSH2.php.

**Comment by terrafrost** [comment]
The `user_error()` occurrences have been fixed with https://github.com/phpseclib/phpseclib/commit/56a644faa849040f32ebf3399282d682af690dcf
