### ISSUE TITLE
Fatal error: Allowed memory size of NUMBER bytes exhausted /usr/share/php/Crypt/Base.php

### ISSUE THREAD

**Issue by Defrand** [phpseclib/phpseclib#1208]
Hi,

I have some trouble in my server. Some times when I upload big crypted files ( up to 200 Mb ) I got this error:

PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 29729224 bytes) in /usr/share/php/Crypt/Base.php on line 1393

The Encryption that I use is:

Crypt_AES(CRYPT_AES_MODE_CBC)

How can I solve this problem?

**Comment by bantu** [comment]
Can you show some code? You are probably holding a lot of data in memory.

**Comment by Defrand** [comment]
I can show you in pseudo-code:

$data = Decrypt($encrypted_file);
file_put_contents($data, $file);

but I not clean the data variable, I only notice it now.

Can the problem be it?

I think that the problem is in first row of code.

**Comment by terrafrost** [comment]
> PHP Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 29729224 bytes) in /usr/share/php/Crypt/Base.php on line 1393

Looks like your memory_limit is 128M. Maybe try changing it to 1024M. Or, better yet, rewrite your app such that it loads the file in chunks. ie. enable continuous mode and then try to decrypt 1mb at a time, writing each successive 1mb block to a file with `fputs()`.

**Comment by Defrand** [comment]
This is a really good idea. I'll try.
