### ISSUE TITLE
Problem with verifying signature

### ISSUE THREAD

**Issue by Robofolk** [phpseclib/phpseclib#1209]
Hi,
I'm not sure if this the best place to ask my question, but since the support forum is closed, I think I have no other choices. Apologise in advance if I chose the wrong place to have my question.

I've got a PHP code that uses phpseclib RSA to create a signature, as listed below. I have no problem with verifying if in PHP as well. 

```
<?php
include('Crypt/RSA.php');

$package = "MyPassword";
$signature = rsa_hash_sign($package, file_get_contents("/usr/local/SSLKeys/private/server_signature.key")); // private key
var_dump(rsa_verify_sign(file_get_contents("/usr/local/SSLKeys/public/server_signature.crt"), $signature, $package)); // public key

function rsa_hash_sign($package, $privateKey) {
    $rsa = new Crypt_RSA();
    $rsa->setHash("sha256");
    $rsa->setSignatureMode(CRYPT_RSA_SIGNATURE_PKCS1);
    $rsa->loadKey($privateKey);
    $hash = hash('sha256', $package, true);
    $signature = $rsa->sign($hash);

    $hexData = bin2hex($signature);
    $base64 = base64_encode($hexData);
    return $base64;
}

// please ignore the following function. It is only used for testing if the above function works as expected or not.
function rsa_verify_sign($publicKey, $signature, $package) {
    $base64 = base64_decode($signature);
    $crypttext = pack("H*", $base64);

    $rsa = new Crypt_RSA();
    $rsa->setHash("sha256");
    $rsa->setSignatureMode(CRYPT_RSA_SIGNATURE_PKCS1);
    $rsa->loadKey($publicKey);
    $hashToCheck = hash('sha256', $package, true);
    $verify = $rsa->verify($hashToCheck, $crypttext);
    return $verify;
}
?>
```

However, I cannot verify a PHP signature in C#. In the code below the output of ```rsa_hash_sign()``` function above, has been allocated to ```phpSignedData`` in the following C# method. I tried to mimic all the phpseclib verification in C#, but the verification fails. Can you please advise whether phpseclib signature can be verified in C# or not, and if it's possible, please let me know of my mistake.

```
[Test]
public void rsa_sign_in_php_verify_in_csharp()
{
    // this is the output of the above PHP function rsa_hash_sign()
    string phpSignedData = "OWFkMmExNzkzZDgzYmZkNjliOGViYTlhZjFjMTYwNjI2OGYzNWI4OGExMTQ2ZTg5ZTY2YjBlYTBlNDcwZmVmZDFhOGU5ZDg3ODdmMjZiMzczZjhjZmZjZmYwNDliZjI5Y2JmMDg4ZGVhYjBmNjdiNTkxNTVkYzMyMjQyYmUzOGVmNTJmNTA4OWNmZWVhZDliYTVmYWU2ZTliZGMyZjQwMTM5NjU3ODI0NDQxZTUyMzZhOGJiMGNlZjg5YzNlZTkyMTYwYmIxMGY5MDYxOWU3OGUwN2I0NWEzMjE4MzlkYTM2YWUxZTI0MjNkMWUwOThmZmUyNjcxYTgwOTYxNmViZmY1NDUzNzQ3YWI2MGU4YjYwMTE1YmQ4MTAxZjM1MTFjN2IyYzcyMzZiMzFiNjRhZTc2NzczMDFhYjY5YTFmOGIzNjIyY2M2M2YxMDY1YWEzN2U5YzZiOTI1ZWExMWYxMmEwMGU5OTk5NzE3N2UwOWYwNzVjN2E5NmY4MWJmMDNkYWFmMTJlOTM3YjI2MDY0YTAwNWM1ZDE3ZWI5MDU4MWEwZGU3MzdmZjVhNzk0ZmQ1NzNjNTBlZTQ0NzIxZGE3ZGJmMjRjZGIzZTUxOWM4MmQyZDdlMDZiZGQzMDAxZjJlOTZlODkyOTdhODZlMmVlYWY4YjdjMTU0MGUwNDVlMmM=";

    byte[] phpSignatureBytes = DecodePhpOutput(phpSignedData);

    byte[] csharpHmac;
    using (var sha256 = System.Security.Cryptography.SHA256.Create())
    {
        byte[] data = System.Text.Encoding.UTF8.GetBytes("MyPassword");
        csharpHmac = sha256.ComputeHash(data);
    }

    bool verficationResult = VerifySignature(csharpHmac, phpSignatureBytes);

    Assert.That(verficationResult, Is.True);
}

public static byte[] DecodePhpOutput(string input)
{
    byte[] base64Bytes = Convert.FromBase64String(input);

    var base64String = string.Empty;
    foreach (byte x in base64Bytes)
    {
        base64String += Convert.ToChar(x);
    }

    var outputBytes = new List<byte>();
    for (int i = 0; i < urlDecoded.Length; i += 2)
    {
        string twoCharacters = urlDecoded.Substring(i, 2);
        outputBytes.Add(Convert.ToByte(twoCharacters, 16));
    }

    return outputBytes.ToArray();
}

private bool VerifySignature(byte[] hashOfDataToVerify, byte[] signature)
{
    RSAParameters m_serverSigningPublicKey = xxx; // For sake of brevity this line of code has truncated

    using (var rsa = new RSACryptoServiceProvider(2048))
    {
        rsa.ImportParameters(m_serverSigningPublicKey);

        var rsaDeformatter = new RSAPKCS1SignatureDeformatter(rsa);
        rsaDeformatter.SetHashAlgorithm("SHA256");

        return rsaDeformatter.VerifySignature(hashOfDataToVerify, signature);
    }
}
```

Thanks

**Comment by terrafrost** [comment]
First, I don't really know C#. On http://phpseclib.sourceforge.net/ I recommend people go to stackoverflow for support requests and this post is one of the reasons why. On SO there are people who know C# and the C# crypto API. And they're available at all hours of the day whereas I'm not.

In any event, it does strange that you're creating the hash outside of any `RSAPKCS1SignatureDeformatter` method calls. That said https://msdn.microsoft.com/en-us/library/system.security.cryptography.rsapkcs1signaturedeformatter(v=vs.110).aspx appears to (mostly) do the same thing. The biggest difference I see between what you're doing and what the example is doing is that you appear to be using an HMAC, which I think is a bit gimmicky. I'd just go with a standardized approach instead of trying to roll out your own.

Also, I don't know what `RSAPKCS1SignatureDeformatter` does internally but...  in PKCS1 you embed the OID of the hash algorithm into the message that's going to be subjected to modular exponentiation. https://tools.ietf.org/html/rfc3447#section-9.2 elaborates. In theory you'd want this to be the same as the hash that's actually used but I suppose one could make it different if one were so inclined. My guess is that `RSAPKCS1SignatureDeformatter` lets you do just that. I mean, it does have "PKCS1" in the name and that has to count for something.

Anyway, if that's the case, you're basically coming up with your own custom hashing scheme independent of what the OID would indicate. phpseclib determines the hashing algorithm from the OID and SHA256 with HMAC is not an option.

I'd recommend just not doing the HMAC.

Also...

```
        $htmlFriendly = htmlspecialchars_decode($signature);
        $base64 = base64_decode($htmlFriendly);
        $urldecode = urldecode($base64);
        $crypttext = pack("H*", $urldecode);
```

So the ciphertext is first converted to a hexidecimal notation (ie. only allowed digits are 0-F) and then urlencoded? Hex-encoded strings have no characters that would need to be URL encoded by definition. Then, after that it's being base64_encoded?

It's just a whole lot of indirection and unnecessary steps...

**Comment by Robofolk** [comment]
Hi,
The reason I used ```HMACSHA256``` is that this class provides a SHA256 hash function with the specified key data. With ```SHA256Managed``` and ```SHA256``` classes, you cannot have the key. However I've already tested that the output of ```HMACSHA256.ComputeHash ()``` (converted to a string) is exactly the same as PHP's ```hash_hmac()```. 
So what I do for research is to use ```hash()``` in PHP instead of  ```hash_hmac()```, although including the session key in the hash is very important to me.
BTW, Thanks I am going to ask this question on stackoverflow after my research.

**Comment by terrafrost** [comment]
> However I've already tested that the output of ```HMACSHA256.ComputeHash ()``` (converted to a string) is exactly the same as PHP's ```hash_hmac()```. 

That's not what I'm saying.

The PKCS1 encryption format has the OID embedded within it for the hash algorithm. The supported OIDs are as follows:

```
   1. For the six hash functions mentioned in Appendix B.1, the DER
      encoding T of the DigestInfo value is equal to the following:

      MD2:     (0x)30 20 30 0c 06 08 2a 86 48 86 f7 0d 02 02 05 00 04
                   10 || H.
      MD5:     (0x)30 20 30 0c 06 08 2a 86 48 86 f7 0d 02 05 05 00 04
                   10 || H.
      SHA-1:   (0x)30 21 30 09 06 05 2b 0e 03 02 1a 05 00 04 14 || H.
      SHA-256: (0x)30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00
                   04 20 || H.
      SHA-384: (0x)30 41 30 0d 06 09 60 86 48 01 65 03 04 02 02 05 00
                   04 30 || H.
      SHA-512: (0x)30 51 30 0d 06 09 60 86 48 01 65 03 04 02 03 05 00
                      04 40 || H.
```
That's the hex encoded OIDs but the thing is...  there are only a small number of hash algorithms that are accepted and none of them are HMACs. [BLAKE2](https://en.wikipedia.org/wiki/BLAKE_(hash_function)) is a newer hash algorithm that's generally regarded as being quite secure. But you can't use it with PKCS1 RSA encryption. Not if you want your ciphertext to be PKCS1 v2.2 compliant. If you don't care about PKCS1 v2.2 compliance then sure, do whatever you like, but be aware that your ciphertext may not decrypt with other tools.

**Comment by Robofolk** [comment]
Thanks. You're right. I don't know what's going on in ```RSAPKCS1SignatureDeformatter```. I used ```hash()``` in PHP and ```SHA256.ComputeHash()``` in C#, but no success. Although the .NET's own example and also in your list above SHA-256 hash must be supported.

**Comment by terrafrost** [comment]
> Although the .NET's own example and also in your list above SHA-256 hash must be supported.

SHA-256 hash is supported but not SHA-256 HMAC.

In your C# code you have `rsa_sign_in_php_verify_in_csharp`, which calls `CsharpHMAC`, which utilizes `HMACSHA256`:

```c#
using (var hmac = new HMACSHA256(sessionKey))
```

In the sample code `SHA256` is used:

```c#
using (SHA256 sha256 = SHA256.Create())
```

**Comment by Robofolk** [comment]
> So try using SHA256 - not HMACSHA256.

I did try that also, but as I mentioned above I had no success with it either. I didn't update the code on this ticket with my latest code, but I did try SHA256 only. So my php code line 13 now looks like:

```
$hash = hash('sha256', $package, true);
```

and in C# code my code is:

```
using (var sha256 = System.Security.Cryptography.SHA256.Create())
{
        byte[] data = System.Text.Encoding.UTF8.GetBytes("hmacPassword");
	csharpHmac = sha256.ComputeHash(data);
}
```

No luck though

**Comment by Robofolk** [comment]
I managed to solve the issue. 

> The PKCS1 encryption format has the OID embedded within it for the hash algorithm. The supported OIDs are as follows:
>   1. For the six hash functions mentioned in Appendix B.1, the DER
      encoding T of the DigestInfo value is equal to the following:
      MD2:     (0x)30 20 30 0c 06 08 2a 86 48 86 f7 0d 02 02 05 00 04
                   10 || H.
      MD5:     (0x)30 20 30 0c 06 08 2a 86 48 86 f7 0d 02 05 05 00 04
                   10 || H.
      SHA-1:   (0x)30 21 30 09 06 05 2b 0e 03 02 1a 05 00 04 14 || H.
      SHA-256: (0x)30 31 30 0d 06 09 60 86 48 01 65 03 04 02 01 05 00
                   04 20 || H.
      SHA-384: (0x)30 41 30 0d 06 09 60 86 48 01 65 03 04 02 02 05 00
                   04 30 || H.
      SHA-512: (0x)30 51 30 0d 06 09 60 86 48 01 65 03 04 02 03 05 00
                      04 40 || H.
That's the hex encoded OIDs but the thing is... there are only a small number of hash algorithms that are accepted and none of them are HMACs.

I know that you are the people who have developed phpseclib, and you know all the details about it. But by trial & error and not looking at the source code, I discovered that both phpseclib and .NET accept just anything to sign. It can be a hash, a simple string or even a HMAC.

So in both PHP and C# code, I switched back to HMAC as it's much more secure than ordinary hash as I can include my session-key to it. I had to do some strange things with it though. .NET gives me an array of 32 bytes for HMAC. This is the value that I need to use to verify the signed data against. **But apparently in phpseclib the HMAC which is used to sign, has 64 bytes!** Maybe you can explain and elaborate more on this. So in my C# code I first converted that array of 32 bytes to an array of 64 bytes (to be honest at this moment, I don't know if there is any way nicer to do this):

```
byte[] csharpHmac = GetDataHashing().HMAC(System.Text.Encoding.UTF8.GetBytes("hmacPassword"), System.Text.Encoding.UTF8.GetBytes("MyPassword"));

var hmacAsString = string.Empty;
foreach (byte @byte in csharpHmac)
{
    hmacAsString += @byte.ToString("x2");
}
byte[] urlEncodedBytes = System.Text.Encoding.UTF8.GetBytes(hmacAsString);
```

Then I made some changes to the verification code as well. The main difference is that I used the method ```VerifyData()``` instead of ```VerifySignature()```. It now looks like:
```
private bool VerifySignature(byte[] hashOfDataToVerify, byte[] signature)
{
    RSAParameters m_serverSigningPublicKey = xxx; // For sake of brevity this line of code has truncated

    using (var rsa = new RSACryptoServiceProvider())
    {
        rsa.ImportParameters(m_serverSigningPublicKey);
        // To verify the data using the signature, I should pass a new instance of SHA256CryptoServiceProvider to specify the use of SHA256 for hashing.
	return rsa.VerifyData(hashOfDataToVerify, new SHA256CryptoServiceProvider(), signature);
    }
}
```

**Comment by Robofolk** [comment]
I really appreciate if someone shed some lights on the mystery of _**64 bytes**_ as highlighted and explained in the above post.

**Comment by salmonila** [comment]
As I've said before I don't know C# and I don't know what the API you're
using is trying to do internally. My posts were an attempt to help you
achieve interoperability based on my best guess as to what the C# code
seemed to be doing.

But let's dispense with interoperability for the time being and let's just
consider the PHP code.

You're not verifying the signature of the message - you're verifying the
hmac of the message. I guess the hmac of the message could be considered to
be a message but you're not verifying the message directly.

As for the 64 bytes..  you're not creating the HMAC with phpseclib. You're
creating it with hash_hmac. That's a native PHP function and it's output is
hex encoded. If C# is outputting 32 bytes it's probably not hex encoded.
FWIW phpseclib can make it's own hmacs but that's not what you're using to
do so. In order for hash_hmac to output non hex encoded data you need to
pass a fourth parameter to it - true.

**Comment by Robofolk** [comment]
> In order for hash_hmac to output non hex encoded data you need to
pass a fourth parameter to it - true.

Thanks. I added the forth parameter and now it matches .NET's HMAC. :-)

Finally, I'd like to thank everybody who contributed on this post. Really helpful. I can now sign in phpseclib and verify it in .NET and vice versa.
