### ISSUE TITLE
SSH2 - auth + keyboard-interactive auth

### ISSUE THREAD

**Issue by theunreal** [phpseclib/phpseclib#1216]
I'm trying to authenticate to my device which requires user:pass authentication (which works) and keyboard-interactive auth after it.

1. Connect with user/pass // Works

```
$ssh = new \phpseclib\Net\SSH2('my-ip');

$result = $ssh->login('test', 'test123');
```

2. execute "en" (starts keyboard-interactive)

`echo $ssh->exec('en');`

3. Output: "Password:" --> I need to enter a password here. 

Trying to

`echo $ssh->exec('my-password'); // doesn't work, auth fails`

Any idea how I can interactively enter the password in this stage? it seems like exec not working for this one

**Comment by metaclassing** [comment]
For starters I highly recommend using an account in TACACS+ that automagically gets assigned priv 15 on all network devices so it doesn't need to use enable passwords. Those are somewhat antiquated for network device security.

Some devices like ASA's still refuse to give up that style of administration however in which case I have code that sends "enable\npassword" together to get around that issue:
https://github.com/metaclassing/PHP5-NetworkAutomation/blob/4ed4073634caba90fbdc9ec2e0bb1c4bbb1b3a72/bin/save-config.php#L87-L95

**Comment by theunreal** [comment]
@metaclassing Woah! so it's impossible to do the enable password with this library?

**Comment by metaclassing** [comment]
Its not "impossible" or even the the library's fault.

You are using an exec function that blocks the next PHP instruction from executing until a prompt or pattern get returned (or configured timeout) before continuing to the next PHP instruction.

The enable password line does not end. There is no \r\n received from the network device for a blocking pattern matcher to use indicating output has stopped. It is an interactive prompt you have to expect and know to just send the password to.

You CAN do it in two separate lines of code with $blah->write("enable"); and $blah->write("mySecretPassword"); but a $blah->read(); operation will not return if you put in between the two writes. Simply concatenating the enable\npassword into one exec call simplifies this network device created issue.

**Comment by metaclassing** [comment]
Also while we are on the topic of prompt pattern matching, I dont know how you are doing it currently but if you have a multivendor environment you will likely need to build an array of different REGEX to use depending on device types and operating systems running on them.

Examples of regex for IOS, NXOS, IOS-XR, IOS-XE, ASA, ArubaOS, etc.
https://github.com/metaclassing/PHP5-NetworkAutomation/blob/4ed4073634caba90fbdc9ec2e0bb1c4bbb1b3a72/include/command/command.class.php#L49-L85

**Comment by theunreal** [comment]
Thanks @metaclassing , currently I'm just trying to authenticate with the enable password. I tried to follow your suggestion as follows:
```
echo $ssh->write('en');
wait(5);
echo $ssh->write('lab');
echo $ssh->exec('dir');
```

Another try:
```
echo $ssh->exec('en');
sleep(5);
echo $ssh->exec('lab');
echo $ssh->exec('dir');
```

Both returned

`Notice: Unable to open channel in C:\xampp\htdocs\php-ssh\vendor\phpseclib\phpseclib\phpseclib\Net\SSH2.php on line 3653`

**Comment by metaclassing** [comment]
Starting from the beginning, can you authenticate and echo $ssh->exec("show version"); successfully? If that hangs or is incomplete then you are running into a more fundamental problem than enableing.

Are you doing terminal length 0, or no terminal pager, or term width 512, or whatever the correct commands are for your specific platform to prepare for an automated SSH session?

What is the prompt pattern you are matching inside $ssh to determine when command output has finished and should be returned?

Does the $ssh->exec("enable\nlab"); command work result in the prompt> changing to prompt#?

**Comment by terrafrost** [comment]
It's hard to comment without seeing the logs but based on what I've read...

```php
$ssh->write('en');
sleep(5);
$ssh->write('lab');
sleep(5);
$ssh->write("dir\n");
echo $ssh->read('[prompt]');
```

The thing is...  `$ssh->write()` sends commands on a specific SSH channel. `$ssh->exec()` sends commands on a different channel. If you're authenticating within a specific channel I'd expect that authorization to only be valid for that _specific_ channel and thus all subsequent commands would need to be done in that same channel.

**Comment by metaclassing** [comment]
If @theunreal is still checking back on this post, I extracted the network device ssh wrapper logic to stand on its own.

This example might be useful if you want to use it as-is, or write your own logic to use phpseclib to ssh into routers and switches: https://github.com/metaclassing/PHP7-SSHWrapper/

It's about as simple as I could boil down all the logic required to connect, detect prompt, send commands, etc. Should be copy/paste-able to run in most environments.

**Comment by theunreal** [comment]
> Starting from the beginning, can you authenticate and echo $ssh->exec("show version"); successfully? If that hangs or is incomplete then you are running into a more fundamental problem than enableing.

I just tried this, returns:

`Notice: Connection closed prematurely in C:\xampp\htdocs\php-ssh\vendor\phpseclib\phpseclib\phpseclib\Net\SSH2.php on line 3814`

@terrafrost - your example was close! I have a real output here!
I tried your example and also tried to add \n to illustarte "enter" but I get the same output with and without \n:

`DEVICE-NAME-196_231>en\nlab\ndir % Bad IP address or host name% Unknown command or computer name, or unable to find computer address Device-NAME-196_231>`

I get this error when i'm trying to run commands before enabling it with en -> Password: mypass, that this is what i'm trying to do with the commands above.

@metaclassing - looks nice, I will check it out.

**Comment by terrafrost** [comment]
Your output has `\n` but the PHP code I gave you didn't. Did you add them?

Anyway, I'd say the best thing would be to see which key stroke results in the server actually sending stuff over with PuTTY logging. You can get the Putty logs by enabling logging. To do so go PuTTY->Session->Logging and checking the "SSH packets" radio button. Post them on pastebin.com and then post the link here and I'll revise my example to behave more like they do.

**Comment by theunreal** [comment]
@terrafrost I had to replace `$ssh->write('lab\n');` with `$ssh->write("lab\n");` and it worked!

Finally, awesome!

Just one question: sometimes I run commands like copying files that take long (about 20 seconds). Is there any way to "wait" start writing to ssh only after the process has completed?

For example:

`$ssh->write("copy //some-path// another-path\n");
$ssh->write("ANOTHER COMMAND \n") // Run it only after the command above has completed and the file was copied`

**Comment by terrafrost** [comment]
You could do this:

```php
$ssh->write("copy //some-path// another-path\n");
$ssh->setTimeout(0); // disable timeout
$ssh->read('[prompt]');
$ssh->write("ANOTHER COMMAND \n") // Run it only after the command above has completed and the file was copied
```

**Comment by theunreal** [comment]
@terrafrost Your solution worked and the command is executed until the end of it, but the page is loading infinitely and I can't echo or return the output

**Comment by terrafrost** [comment]
Probably you're not matching the prompt exactly. There could be ANSI escape codes in there for example that would make the actual string that the server sends not match the string that you "see".

Two ways you could figure this out. Do `$ssh->setTimeout(3);` or whatever you have to do to see the prompt. You could also get the SSH logs. eg. do `define('NET_SSH2_LOGGING', 3);`. That's enable real time logging. You could then give me the last few packets that the SSH server sends.

**Comment by theunreal** [comment]
I don't know how many time the command will take, so setting a contant time is not a good idea (like setTimeout(3)

The last packets are:

```
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1211, network: 0.1202s)
00000000  00:00:00:02:00:00:00:01:21                       ........!

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.4934, network: 0.493s)
00000000  00:00:00:02:00:00:00:01:21                       ........!

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.2036, network: 0.2028s)
00000000  00:00:00:02:00:00:00:01:21                       ........!

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.4127, network: 0.4123s)
00000000  00:00:00:02:00:00:00:19:0d:0a:5b:4f:4b:20:2d:20  ..........[OK - 
00000010  33:38:33:36:38:30:33:36:20:62:79:74:65:73:5d:0d  38368036 bytes].
00000020  0a   
```

**Comment by theunreal** [comment]
@terrafrost when settimeout is 0, and the web page keep loading even after the command was done, the last packet is:

```
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.303, network: 0.3028s)
00000000  00:00:00:02:00:00:00:01:21                       ........!

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.3294, network: 0.3291s)
00000000  00:00:00:02:00:00:00:01:21                       ........!

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.316, network: 0.3153s)
00000000  00:00:00:02:00:00:00:01:21                       ........!

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.2799, network: 0.2793s)
00000000  00:00:00:02:00:00:00:19:0d:0a:5b:4f:4b:20:2d:20  ..........[OK - 
00000010  38:37:32:37:37:30:39:35:20:62:79:74:65:73:5d:0d  87277095 bytes].
00000020  0a      
```

**Comment by terrafrost** [comment]
So maybe you don't get a prompt as such. That last response that you're getting says "[OK - 87277095 bytes]" followed by a new line. In light of that I'd say do this:

```php
echo $ssh->read('#\[OK - \d+ bytes\]\n#', NET_SSH2_READ_REGEX);
```

Hopefully from this example you can figure out what to do for other commands. ie. see what the last message from the command is and figure out how to identify that last message. Use regular expressions to do so if necessary.
