### ISSUE TITLE
Getting Expected SSH_MSG_KEXINIT when attempting to download large file

### ISSUE THREAD

**Issue by andrefigueira** [phpseclib/phpseclib#1217]
Hello,

Please let me know if more information will be required, but so far this is all I can see, using v2.0.7

And seem to be getting `Expected SSH_MSG_KEXINIT` when downloading an 18GB file, the package on top of this is flysystem. but the exception is thrown by this package, does anyone have some steps to see what could  be causing this? it only seems to happen with these very large files after a while, then it exceptions.

Cheers!

**Comment by terrafrost** [comment]
Try the latest git version - I think https://github.com/phpseclib/phpseclib/commit/b50dde76f5683367e64e9f5e2936412d3168dad3 may fix this issue.

I need to do a release within the next few days to get that fix out there.

If that doesn't fix it for you lmk and I'll tell you how to get log files.

Thanks!

**Comment by andrefigueira** [comment]
Thanks @terrafrost will give it a go and report back thank you!

**Comment by andrefigueira** [comment]
It seems that the version referenced has breaking changes, so assuming the tag will be to 3.*.* 

The library i'm using which is flysystem is showing a missing class:

`PHP Fatal error:  Class 'phpseclib\Net\SFTP' not found in /var/www/console/vendor/league/flysystem-sftp/src/SftpAdapter.php on line 176
`

**Comment by terrafrost** [comment]
That commit is in the 1.0 and 2.0 and master branches. Anyway, just pull the latest version of the 2.0 branch.

Altho that said, even in the master branch, the namespace for the SFTP class is unchanged...  maybe you tried the latest version of the 1.0 branch and not the 2.0 branch? idk

**Comment by andrefigueira** [comment]
@terrafrost strange! I'll give it another go today!

**Comment by terrafrost** [comment]
I just made new releases of 1.0 and 2.0 (1.0.9 and 2.0.9, respectively). Try them out.

Thanks!

**Comment by andrefigueira** [comment]
@terrafrost so I haven't been able to verify yet if this has worked, i'm definitely getting farther down the download now, but it seems I'm getting a Segmentation fault now, but not sure it's traceable back here now, might be something in the flysystem library

**Comment by andrefigueira** [comment]
Just ran it with full verbose mode, can confirm, latest release fixes my problem, thanks for your help @terrafrost !
