### ISSUE TITLE
API changes in 2.0.8

### ISSUE THREAD

**Issue by nijel** [phpseclib/phpseclib#1218]
Our tests have just upgraded to phpseclib 2.0.8 and this lead to several breakages as this changes API in quite severe way. Can you please consider increasing major version when doing such changes? Honestly I think this should have been called 3.0.0...

Commits leading to problems in phpMyAdmin, but there are probably more API breakages in 2.0.8:

* c509909004345d8434a2c21983aa5c61f825fa4a - Crypt\Base is gone
* 4171262b9ee6f905eb2bfc4a942c5f44483efdf8 - using strings instead of constants
* 2a1177b256361220c5666faa17d7afef34f39998 - making private previously public attribute which didn't have accessor before

Adjusting to these changes is not a complex task, but this is certainly not expected from patchlevel version change especially as there is no easy way to the changes in backward compatible way.

Also see https://semver.org/

**Comment by Jelle-S** [comment]
We have similar issues in the code that we use to do our deploys. As stated, this should have been a major release, not a minor one.

**Comment by bantu** [comment]
This was not intentional. The tag is on the wrong branch.

**Comment by bantu** [comment]
I hope tagging 2.0.9 on the correct branch will address the issues.
Doing so is probably what I'd suggest. Any alternative suggestions are
welcome.

**Comment by terrafrost** [comment]
I just released 2.0.9. I'm sorry for the screw up :(

**Comment by bantu** [comment]
Michal, Jelle: Please let us know whether that fixed the issues you were
having. Thanks

**Comment by nijel** [comment]
Yes, 2.0.9 seems work work fine, thanks for fast fixing this.
