### ISSUE TITLE
PHP 5.x support in 2.0.8

### ISSUE THREAD

**Issue by nijel** [phpseclib/phpseclib#1219]
The readme says for 2.0 "Minimum PHP version: 5.3.3", however composer.json for 2.0.8 release speaks differently:

https://github.com/phpseclib/phpseclib/blob/0a58b73037b4cbcbd66bb9aaed910740eb8624e5/composer.json#L56

What is actually intended?

**Comment by bantu** [comment]
Please check again. You're probably looking at a master commit.

https://github.com/phpseclib/phpseclib/blob/2.0/composer.json#L54 says 5.3.3

**Comment by nijel** [comment]
I'm talking about 2.0.8 release, which apparently was not done from the 2.0 branch:

https://github.com/phpseclib/phpseclib/blob/2.0.8/composer.json#L56

**Comment by bantu** [comment]
Indeed. Something seem to have went wrong there.

**Comment by terrafrost** [comment]
I just did a 2.0.9 release to fix the issue. Shows 5.3.3 now:

https://github.com/phpseclib/phpseclib/blob/2.0.9/composer.json#L56
