### ISSUE TITLE
Willing to maintain WP plugin

### ISSUE THREAD

**Issue by DavidAnderson684** [phpseclib/phpseclib#1224]
Hi Jim,

I'm always grateful for your work on phpseclib. In the past, you noted that I maintain a number of WordPress plugins - https://profiles.wordpress.org/davidanderson#content-plugins - and asked if I'd be willing to maintain https://wordpress.org/plugins/ssh-sftp-updater-support/ also. I said I was too busy then, but I have more capacity now, and would be willing to take over the plugin. My motivation is that I have a number of other plugins with are monetised with premium versions, and we'd be glad to generate some good-will in the community by maintaining a free plugin (I already have several - see the above page). We would be likely to add a dismissable dashboard notice to point people to those plugins. (We do this tastefully and don't spam people - you can see examples in the above plugins; it makes no sense to antagonise your users; e.g. no plugin has a notice that appears on main dashboard pages more than once a year, if they click the obvious "Dismiss" link).

Please let me know if you're still interested.

David

**Comment by terrafrost** [comment]
I added you as a committer! Is that all I need to do?

**Comment by DavidAnderson684** [comment]
Hi,

Yes, thank you. I now have commit access, and it's working.

David

**Comment by terrafrost** [comment]
I just released 1.0.10. The most relevant fix for the Wordpress plugin is #1248. 

I can update the plugin tomorrow? Or you could do that?

Thanks!

**Comment by DavidAnderson684** [comment]
@terrafrost I can update it. I will seek to do so later today.
