### ISSUE TITLE
mcrypt no longer supported in PHP

### ISSUE THREAD

**Issue by antonydandrea** [phpseclib/phpseclib#1229]
Can we bring this library into the year 2018 by migrating away from mcrypt so that it can still be used in PHP 7.2. Mcrypt hasn't been supported for at least 8 years anyway so shouldn't be used.

**Comment by terrafrost** [comment]
Quoting #1134,

> phpseclib has used the error suppression operator on all mcrypt function calls since 1.0.4 / 2.0.4:
> 
> https://github.com/phpseclib/phpseclib/commit/640f10609fdb2aa825f8a42c6bee975879974e1c
> 
> Those versions were released on October 3, 2016. My recommendation: upgrade to the latest version of phpseclib from either the 1.0 or 2.0 branches.
> 
> Removing mcrypt is not going to happen because, deprecated tho it may be, it's still a heck of a lot faster than the pure-PHP implementation. The fact that it's being used on your system suggests that OpenSSL isn't available so mcrypt is gonna be the fastest way to do encryption in PHP.

phpseclib (all branches) are unit tested on PHP 7.2:

https://travis-ci.org/phpseclib/phpseclib

They all pass in spite of using mcrypt. idk if you've ever used Travis CI but an E_DEPRECATED notice will result in a failing unit test and yet the unit tests are all passing.

If you can actually convince me that phpseclib does not work on PHP 7.2 I'll pay you $100.

**Comment by terrafrost** [comment]
OpenSSL is used if it's available. mcrypt is used if it's available and OpenSSL isn't. The pure-PHP implementation (the slowest version) is an extreme last resort.

So if you have both installed OpenSSL should be used (unless you're doing something like Rijndael with a block size of 256, which isn't AES and is supported by mcrypt but not OpenSSL).

If you have just mcrypt installed and not OpenSSL then yah, mcrypt will be used, by default. It won't produce any errors, thanks to the use of error suppression, but it'll be used none-the-less. If you don't want it to be used, you can tell phpseclib to use the internal engine, despite it's being significantly slower. And that it's significantly slower shouldn't be of any great surprise as PHP is kinda a bloated interpreted language compared to C / C++
