### ISSUE TITLE
$sftp->get() is deleting remote file

### ISSUE THREAD

**Issue by thesequelgroup** [phpseclib/phpseclib#1230]
Installed via Composer: "phpseclib/phpseclib": "^2.0"
Running PHP 7.1.10

Here's my code:

<pre>
$sftp = new SFTP('testdomain.com');
	if (!$sftp->login('user', 'pass')) {
	    $logger->error('Could not login to remote server.');
	    die;
	}
$sftp->get('/test/document.csv', 'tempCSV.csv');
</pre>
The CSV downloads as expected but it's also deleting the remote file. I don't want this to happen. I've tracked it down to this line within **phpseclib\Net\SFTP**

Line 2146: **$this->_send_sftp_packet(NET_SFTP_OPEN, $packet);**

No idea what's going on. Any ideas?

**Comment by terrafrost** [comment]
My guess: it probably does that with any file you download with any SFTP client.

Google'ing the SSH server software you're using could yield some useful info. That can be done by doing `echo $ssh->getServerIdentification()`.

Doing `print_r($ssh->getErrors())` or `print_r($ssh->getSFTPErrors())` might provide some insight as well.

But that said, there's no way for an NET_SFTP_OPEN packet to tell the server to delete the file. Here are the options that are available to be passed to NET_SFTP_OPEN:

https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#page-12

None of those tell the server to delete the file. There's an option to truncate but not delete. And the only option `get()` uses is SSH_FXF_READ. If the server is deciding to delete the file it's deciding that all on it's own - phpseclib is not asking it to (based on the code you've posted) nor is there a way for it to do so.

**Comment by thesequelgroup** [comment]
Yea that's an odd behavior for sure. As a sanity check, I copied the file to local using WinSCP and the same behavior is reproduced. Definitively something on their end. No errors are reported using the commands you gave above, and the only server info returned from getServerIdentification() is "SSH-2.0-SFTP Server" which is not very useful.

I'll follow up with this client directly. I appreciate your quick response time @terrafrost 
Thank you!
