### ISSUE TITLE
Uploading not working over sftp

### ISSUE THREAD

**Issue by Royiestan** [phpseclib/phpseclib#1231]
I am trying to upload files using phpseclib sftp library but when i check the uploaded files it is empty and the following error is displayed during upload 
Notice: is not a valid file in C:\wamp\www\directory\Net\SFTP.php on line 2028

$sftp->put('htdocs/directory/'.time()."-".$_FILES['filenamebig']['name'],` $_FILES['filename']['tmp_name'], NET_SFTP_LOCAL_FILE);

**Comment by terrafrost** [comment]
First, are you using phpseclib 1.0? If you're using 2.0 it's not `NET_SFTP_LOCAL_FILE` that you should be using - it's `SFTP::SOURCE_LOCAL_FILE`.

Anyway, that said, the first key you're using for the `$_FILES` array is different. The first time you're getting the `name` key of $_FILES['filename**big**'] and the second time you're getting the `tmp_name` of $_FILES['filename'].

Look at those key names side by side:

filenamebig
filename

They're not the same. My guess: it'll work if you make them the same (whichever one is correct is dependent on code you've not posted)

**Comment by Royiestan** [comment]
thats true don't know how i missed it :p it worked on the local host but once i uploaded the files online it is now giving connection failed but it is working normally on localhost do you know what the problem can be

**Comment by terrafrost** [comment]
It could be that the prod (?) server is limited how fsockopen() can be used. ie. on local host you can connect to any host and on prod you can't connect to any.

The SSH logs might provide some insight (altho if it's the fsockopen issue I mentioned, they'd be empty). You can get them by doing `define('NET_SSH2_LOGGING', 2);` and `echo $ssh->getLog();` after the failed login attempt.

**Comment by Royiestan** [comment]
the get log is returning empty

**Comment by Royiestan** [comment]
RSA certificate configured for domain:443 does NOT include an ID which matches the server name this is the error on the ssl logs

**Comment by terrafrost** [comment]
In a post that you, I guess, deleted, it sounds like your server might be running FTPS - not SFTP.

Anyway, try doing this:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
$this->fsock = @fsockopen($this->host, $this->port, $errno, $errstr, $this->curTimeout == 0 ? 100000 : $this->curTimeout);
#
#-----[ REPLACE WITH ]----------------------------------
#
$this->fsock = fsockopen($this->host, $this->port, $errno, $errstr, $this->curTimeout == 0 ? 100000 : $this->curTimeout);
```

My guess is that you'll get an error about how it's unable to connect.
