### ISSUE TITLE
Null reply packet, expecting CONTINUE

### ISSUE THREAD

**Issue by simPod** [phpseclib/phpseclib#1232]
When using SSH connection, I see `Null reply packet, expecting CONTINUE` errors on devices I'm connecting to. Is there a way to find why and how to fix it?

I create `new SSH2($ip)` instance, `login($username, $pass)` to it, then I `setTimeout(20)` and execute command `$ssh->exec($command)`

Error examples I receive:
`tty1: Null reply packet, expecting CONTINUE`
`pts/8: Null reply packet, expecting CONTINUE`
`ssh: Null reply packet, expecting CONTINUE`

Thanks!

**Comment by terrafrost** [comment]
Two things that would help.

1. Knowing what the command is.
2. Seeing the SSH logs. You can get those by doing `define('NET_SSH2_LOGGING', 2);` at the top and then `echo $ssh->getLog();` after the `$ssh->exec();`.

**Comment by simPod** [comment]
I'm connecting to Arista devices, it's propably command `show vlans`. I'll try the logging tho. Thanks

**Comment by terrafrost** [comment]
In a post that you, I guess, deleted, it sounds like your server might be running FTPS - not SFTP.

Anyway, try doing this:

```php
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
$this->fsock = @fsockopen($this->host, $this->port, $errno, $errstr, $this->curTimeout == 0 ? 100000 : $this->curTimeout);
#
#-----[ REPLACE WITH ]----------------------------------
#
$this->fsock = fsockopen($this->host, $this->port, $errno, $errstr, $this->curTimeout == 0 ? 100000 : $this->curTimeout);
```

My guess is that you'll get an error about how it's unable to connect.

**Comment by terrafrost** [comment]
Err - my last post was meant for #1231 - not for this. For this one I'll want to see the log before making recommendations as to possible next steps.

Sorry about the confusion!

**Comment by simPod** [comment]
We have somehow managed to implement this lib and the problem is not happening.
