### ISSUE TITLE
phpseclib login error only on HEROKU

### ISSUE THREAD

**Issue by nihitx** [phpseclib/phpseclib#1240]
Hi, I am using heroku to send files through phpseclib to a SFTP server. 
I have pasted the code below, but the problem is that ONLY on Heroku I am facing login error and I am not sure why it works perfectly fine on my LOCAL computer. I tried to log information via stfp error loggers but they show empty array.

I have phpseclib on composer. I am loading it via autoloader.
Here is the code I am using. The version I am using is     "phpseclib/phpseclib": "~2.0",
```

 $sftp = new \phpseclib\Net\SFTP(getenv('INSTRUM_SERVER'));
        if (!$sftp->login(getenv('INSTRUM_USERNAME'), getenv('INSTRUM_PASSWORD'))) {
            exit('Login Failed');
        }
```

**Comment by terrafrost** [comment]
One possibility is that the method you're trying to use to get the log files isn't correct. Could you post how you're doing that, just for my own edification?

Assuming you are doing it correctly than it sounds like maybe something like `fsockopen` is failing. In phpseclib 2.0 fsockopen has it's errors suppressed. eg. it does `@fsockopen`. I'd remove the `@` and see if you get any errors from that.

Also, do the same thing for `@stream_select`.

**Comment by nihitx** [comment]
Hi, I Have been testing the errors like this.

var_dump($sftp->getSFTPErrors() );
var_dump($sftp->getLastSFTPError());

WHere can I find @fsockopen? I tried looking for it in the phpseclib file but unfortunately had no luck.

There is one @fsockopen in the codeigniter files which looks like this.

```
// Open the socket
		if ( ! $fp = @fsockopen($target['host'], 80))
```
I am not sure if that's the one.

**Comment by terrafrost** [comment]
It's in SSH2.php (SFTP.php extends SSH2.php)

**Comment by nihitx** [comment]
Hi Terrafrost, 

I figured out the error which was basically the SFTP client not supporting the IP address. Meaning the IP address of heroku was blocked by the server. 
I was wondering is there a way to manually make phpseclib have a static IP? If not please close this issue and thank you for the help and sorry for the trouble.

**Comment by terrafrost** [comment]
Does https://github.com/phpseclib/phpseclib/issues/742#issuecomment-122351289 let you do what you're needing?
