### ISSUE TITLE
How to set Login Timeout

### ISSUE THREAD

**Issue by quyeticb** [phpseclib/phpseclib#1251]
hello, need set login Timeout, setTimeout function not working with login method.

**Comment by terrafrost** [comment]
Works for me:

```php
$start = microtime(true);

$ssh = new SSH2('www.google.com', 1);
$ssh->setTimeout(2);
if (!$ssh->login('test', 'test')) {
	$elapsed = microtime(true) - $start;
	exit("unable to login\ntook $elapsed seconds\n");
}

$elapsed = microtime(true) - $start;
exit("login successful\ntook $elapsed seconds\n");
```

With the `$ssh->setTimeout(2);` it takes 2 seconds. Without it it takes 10 seconds (the default timeout).

This particular example demonstrates slowdowns in `fsockopen` but it's possible your slowdown is occurring elsewhere. Try doing `define('NET_SSH2_LOGGING', 3);` at the top of your PHP file and then posting the output.  If the slowdown isn't in the `fsockopen` part of the code that should reveal where it is.

Thanks!
