### ISSUE TITLE
Multiple random timeouts moving a large file (1.4 Gb)

### ISSUE THREAD

**Issue by HectorFGarcia** [phpseclib/phpseclib#1252]
I'm triying to move a very large **excel** (1.4 Gb) from a FTP to another server. All seems to be working fine but, when around a Gb is transfered, the script stops due to some random timeout. I'm saying "random" because, after running the script five times, I had five timeouts from different lines:

* From Net/SSH2.php:3956
* From Crypt/Base:1048
* From Net/SSH2.php:3366
* From Net/SSH2.php:3705
* From Crypt/Hash.php:334 

The script is extremely simple:

```
$sftp = new Net_SFTP($ftp_server);
if (!$sftp->login($ftp_user, $ftp_pass)) {
    echo json_encode('...');
}

$sftp->setTimeout(0);

if ($sftp->get($file, EXCEL_PATH . $file) != FALSE) {
    echo json_encode('...');
} else {
    echo json_encode('...');
}
```

What can I do? I tried to add the timeout setting it to 0 and 3600, but nothing changed.

P.S. I'm using phpseclib 1.0.10 and PHP 5.3.10

**Comment by terrafrost** [comment]
I'd be curious to know what the full error message was - not just the file name / line number.

Anyway, my guess, based on the info provided thus far: try putting `set_time_limit(0);` at the top of your PHP file.

**Comment by HectorFGarcia** [comment]
All timeouts are logged like this: 

[Tue Mar 13 10:39:28 2018] [warn] [client X.X.X.X] mod_fcgid: stderr: PHP Fatal error:  Maximum execution time of 60 seconds exceeded in SOMEPATH

I'll try the set_time_limit. Thanks.
