### ISSUE TITLE
Error 111. Connection refused

### ISSUE THREAD

**Issue by gromovod** [phpseclib/phpseclib#1253]
I'm trying to connect pt 2222
$port = 2222;
$ssh = new \phpseclib\Net\SSH2($host, $port);

I get an error: Cannot connect to IP:2222. Error 111. Connection refused  Net_SSH2->_connect() ( 1038 
On my local computer (Windows, OpenServer) the connection is established without error.
And on a hosting - an error.
Perhaps this is an error in the hosting settings?

**Comment by terrafrost** [comment]
What version of phpseclib are you usng? I tried looking at line 1038 on versions 2.0.10 through 2.0.0 and didn't see any line that could emit that error. eg. I saw this:

https://github.com/phpseclib/phpseclib/blob/2.0.0/phpseclib/Net/SSH2.php#L1038
https://github.com/phpseclib/phpseclib/blob/2.0.10/phpseclib/Net/SSH2.php#L1038

My guess would be that that's the line that has `fsockopen`. If that's the case then you should be able to reproduce the problem by doing `fsockopen($host, $post)` on the two machines. It should work locally but not on your host.

Anyway, it's possible it's an issue with your iptables configuration. Or maybe you're trying to connect to a machine on your local machine's LAN whereas the production machine is not on the same LAN.

SELinux can also cause issues. https://stackoverflow.com/a/13608942/569976 elaborates.

**Comment by gromovod** [comment]
I use now version 2.0.10
Now error in line 1122
"Cannot connect to 8_.__.___.___:2222. Error 111. Connection refused in phpseclib\Net\SSH2->_connect() (str 1122 in.. "
"My guess would be that that's the line that has fsockopen." - how to do it?
in my file like this?:
fsockopen($host, $post);
$ssh = new \phpseclib\Net\SSH2($host, $port);

**Comment by terrafrost** [comment]
> "SELinux can also cause issues" - I use on a hosting. I can not change the settings (setsebool -P httpd_can_network_connect 1)

I would suggest contacting your hosting provider then. Give them a script with just `fsockopen` and tell them that fsockopen can't connect and that you need it to.

If you give them a script with all of phpseclib they're gonna have to debug phpseclib to figure out what's up with the script and there's no need for that - we've already diagnosed the problem and it's not phpseclib. Plus, the more extra code you give them the more opportunities they have to misdiagnose the problem.

**Comment by elmarzouguidev** [comment]
I have the same error in 2023 !!

**Comment by terrafrost** [comment]
@elmarzouguidev :

My guess would be that that's the line that has `fsockopen`. If that's the case then you should be able to reproduce the problem by doing `fsockopen($host, $post)` on the two machines. It should work locally but not on your host.

Anyway, it's possible it's an issue with your iptables configuration. Or maybe you're trying to connect to a machine on your local machine's LAN whereas the production machine is not on the same LAN.

SELinux can also cause issues. https://stackoverflow.com/a/13608942/569976 elaborates.

**Comment by noveweb** [comment]
> I have the same error in 2023 !!

This error is caused by the target machine firewall. To solve this problem go to your server firewall where the code is running and add the target IP to allowed ip list. For exemple, im using cPanel WHM, then i go to ConfigServer Security & Firewall and add the target machine ip in Allow IP address field then click in QUICK ALLOW.

<img width="1130" alt="QUICKALLOW" src="https://github.com/phpseclib/phpseclib/assets/11202389/891f9c77-dae3-4588-ae4e-caa1d0007543">

**Comment by elmarzouguidev** [comment]
> > I have the same error in 2023 !!
> 
> This error is caused by your server firewall where the code is running. To solve this problem go to your server firewall where the code is running and add the target IP to allowed ip list. For exemple, im using cPanel WHM, then i go to ConfigServer Security & Firewall and add the target machine ip in Allow IP address field then click in QUICK ALLOW.
> 
> <img alt="QUICKALLOW" width="1130" src="https://private-user-images.githubusercontent.com/11202389/294772187-891f9c77-dae3-4588-ae4e-caa1d0007543.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ4MzE1NjAsIm5iZiI6MTcwNDgzMTI2MCwicGF0aCI6Ii8xMTIwMjM4OS8yOTQ3NzIxODctODkxZjljNzctZGFlMy00NTg4LWFlNGUtY2FhMWQwMDA3NTQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDIwMTQyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyMDAxZGIxNjUyMDU0MTE1MzBlMTZiMDkyMzkxOGZlNmJlN2IyMGQzMTE4YWJjZjZhMWY1ODE5YzY1ZTkxMjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZIEA0XQHOfOvqB0ZJT9wVifapVJ13zAoGlGXZTvtguc">

yes i gree the problem was from my shared hosting cpanel ...

**Comment by mlopezcoria** [comment]
> > I have the same error in 2023 !!
> 
> This error is caused by your server firewall where the code is running. To solve this problem go to your server firewall where the code is running and add the target IP to allowed ip list. For exemple, im using cPanel WHM, then i go to ConfigServer Security & Firewall and add the target machine ip in Allow IP address field then click in QUICK ALLOW.

This work for me. Thank you!!

**Comment by xamax-dev** [comment]
> > I have the same error in 2023 !!
> 
> This error is caused by your server firewall where the code is running. To solve this problem go to your server firewall where the code is running and add the target IP to allowed ip list. For exemple, im using cPanel WHM, then i go to ConfigServer Security & Firewall and add the target machine ip in Allow IP address field then click in QUICK ALLOW.

Worked for me with `phpseclib3 `on Almalinux, php8.2-fpm, in May 2025

**Thanks Noveweb**
