### ISSUE TITLE
encodeBER enumerated 

### ISSUE THREAD

**Issue by ErkErd** [phpseclib/phpseclib#1254]
my enumerated map 

    'requestorRole' => array('type' => FILE_ASN1_TYPE_ENUMERATED,
                                    'roleClient'=> 0,
                                    'roleParticipant' =>1
                                ),

on array
    
    'requestorRole' => 'roleClient'

Where is the mistake ? It gives me error (bitString function) because of roleClient is not ingeter but it is enumerated so it should't be integer right ? 

This is the full map and array:
map:

    $IdentityObject = array('type' =>FILE_ASN1_TYPE_SEQUENCE,
            'children'=> array(
                'identityIdentificationData' => array('type'=>FILE_ASN1_TYPE_SEQUENCE,
                    'children'=> array(
                        'version' => array('type' => FILE_ASN1_TYPE_IA5_STRING),
                        'staticData' =>array('type' => FILE_ASN1_TYPE_SEQUENCE,
                            'children'=> array(
                                'acceptedPolicyVersion' => array('type' =>FILE_ASN1_TYPE_IA5_STRING),
                                'cardHolderID' => array('type' =>FILE_ASN1_TYPE_INTEGER),
                                'deviceSerialNumber' => array('type' => FILE_ASN1_TYPE_SEQUENCE,
                                    'children'=> array(
                                        'deviceType' => array('type' =>FILE_ASN1_TYPE_INTEGER),
                                        'deviceUniqueID' => array('type' =>FILE_ASN1_TYPE_OCTET_STRING)
                                    ),
                                ),
                                'appLabel' => array('type' =>FILE_ASN1_TYPE_UTF8_STRING),
                                'requestorRole' => array('type' => FILE_ASN1_TYPE_ENUMERATED,
                                    'roleClient'=> 0,
                                    'roleParticipant' =>1
                                ),
                                'creationTime' => array('type' =>FILE_ASN1_TYPE_UTC_TIME)
                            )
                        )
                    )
                )
            )
        );

source:

    array 
    'identityIdentificationData' => 
    array 
      'version' => '2.0'
      'staticData' => 
      array
         'acceptedPolicyVersion' => '2'
         'cardHolderID' => 11111111111
         'deviceSerialNumber' => 
         array 
            'deviceType' => 3
            'deviceUniqueID' => '11111111'
         'appLabel' => 'examination' 
         'requestorRole' => 'roleClient' 
         'creationTime' => '180319141236Z'

**Comment by terrafrost** [comment]
Looks like you posted this on https://stackoverflow.com/q/49421661/569976 . Does that solve the problem you're having?

**Comment by ErkErd** [comment]
Yes that was solved my problem thx.
