### ISSUE TITLE
Crypt_Rijndael without padding is different from the original mcrypt

### ISSUE THREAD

**Issue by kuofp** [phpseclib/phpseclib#1258]
```php
$str = str_repeat('A', 1);
$key = str_repeat('A', 16);
$iv = str_repeat('A', 16);

$cipher = new \Crypt_Rijndael(CRYPT_RIJNDAEL_MODE_CBC);
$cipher->setKey($key);
$cipher->setIV($iv);
$cipher->disablePadding();

$r = mcrypt_encrypt(MCRYPT_RIJNDAEL_128, $key, $str, MCRYPT_MODE_CBC, $iv);
echo base64_encode($r) . "\n"; //GBUxEQzKDaU5dPJ0wNGqFQ==

$r = @$cipher->encrypt($str . str_repeat("\0", $cipher->block_size - (strlen($str) % $cipher->block_size)));
echo base64_encode($r) . "\n"; //GBUxEQzKDaU5dPJ0wNGqFQ==

$r = @$cipher->encrypt($str);
echo base64_encode($r) . "\n"; //Y/p3rrra5ni7zxDBvGNWMQ==

```

and I found that plaintext was padded with chr($pad)

```php
//Base.php line 1897
$pad = $this->block_size - ($length % $this->block_size);

return str_pad($text, $length + $pad, chr($pad));
```

phpseclib 1.0.10
PHP 7.0.27 with mcrypt and openssl

not sure if that is a bug
any idea?

**Comment by terrafrost** [comment]
It's the intended behavior for 1.0 and 2.0.

Some modes require the plaintext / ciphertext be a multiple of the block size. CTR does not but CBC does and you're using CBC in your example.

When padding is disabled but the plaintext is none-the-less _not_ a multiple of the block size phpseclib 1.0 / 2.0 will pad it with PKCS1 padding none-the-less. An error will be emitted with `user_error` but padding will basically be turned back on.

So phpseclib PKCS1 pads the plaintext whereas mcrypt null pads it.

Other ways phpseclib 1.0 / 2.0 deal with bad input...  if the key isn't long enough it's null padded and if the IV isn't null enough it's null padded. Both of these behaviors are consistent with mcrypt. If the key or IV aren't present at all they're assumed to be all null bytes.

In the master branch this behavior is different. The master branch is a lot less tolerant of user error. If the key or IV aren't long enough (or aren't specified at all) you get an Exception. If padding is disabled and the plaintext (or ciphertext) isn't long enough you get an Exception.

The master branch takes the philosophy that cryptographic primitives ought not be used unless you know what you're doing and if you're making mistakes like the above then it ought not make your life easier by silently working around them. The 1.0 / 2.0 philosophy (inspired by mcrypt) was "let's try to massage bad input as much as we can".

**Comment by kuofp** [comment]
Thanks for replying me in such detailed information.
However, it would be a pity that phpseclib is backward incompatible in this case.

May I suggest adding a feature to change the padding mode?
something like
```php
$cipher->enablePadding(PAD_MODE_NULL); // could use PAD_MODE_PKCS5 PAD_MODE_PKCS7
```

**Comment by terrafrost** [comment]
The master branch isn't meant to be backwards compatible with the 1.0 and 2.0 branches.

That said, I'll still be maintaining and supporting 2.0 once 3.0 is released. If you want to use 2.0 there's no reason to stop. Just look at the 1.0 branch. Even that branch is still getting releases..
