### ISSUE TITLE
X509 Question Adding UPN to SAN

### ISSUE THREAD

**Issue by metaclassing** [phpseclib/phpseclib#1263]
I have a (hopefully quick) usage question regarding 2.x x509 implementation.

When I read in a cert from AD there is a SAN from MS for user principal name (UPN):
```
[
  "extnId" => "id-ce-subjectAltName",
  "critical" => false,
  "extnValue" => [
    [
      "otherName" => [
        "type-id" => "1.3.6.1.4.1.311.20.2.3",
        "value" => [
          "utf8String" => "user.name@domain.com",
        ],
      ],
    ],
  ],
],
```

How would I go about setting this same structure in a new cert I generate and sign with phpseclib?

Can I do something similar to this:
```
$CSR->setExtension('id-ce-subjectAltName',
[
    'otherName' => [
        'type-id' => '1.3.6.1.4.1.311.20.2.3',
        'value' => [    
            'utf8String' => "user.name@domain.com",  
        ],    
    ]
]);
```
or do I need to add the OID to a list in file\x509.php or ASN1.php and write some kind of parser there? If there are changes required I can try my hand at implementing them and send a PR, not sure where to start.

**Comment by terrafrost** [comment]
Try this:

```php
$CSR->setExtension('id-ce-subjectAltName',
[[
    'otherName' => [
        'type-id' => '1.3.6.1.4.1.311.20.2.3',
        'value' => [    
            'utf8String' => "user.name@domain.com",  
        ],    
    ]
]]);
```

**Comment by metaclassing** [comment]
I believe it worked, thanks a bunch for the help!
