### ISSUE TITLE
SSH to localhost (Mac)

### ISSUE THREAD

**Issue by bmelon** [phpseclib/phpseclib#1265]
Hi,

I have managed to SSH using an RSA key to an external Linux server, but I wondered if it is possible to SSH into my localhost (Mac).

I've tried using `localhost`, `127.0.0.1` and my lan address (`192.168.1.111`). I've supplied my username, password and private key (`file_get_contents("/Users/matt/.ssh/id_rsa")`), but it always fails.

P.S. I have enabled remote login in Mac system preferences and confirmed that `ssh matt@192.168.1.111` in the terminal works correctly.

Thanks!

**Comment by terrafrost** [comment]
Can you connect with to localhost with the CLI ssh client? If not then the problem isn't exclusive to phpseclib and is probably a problem with how you have your account setup on your Mac. At which point this question would probably be better posted on superuser.com.

That said, a few thoughts.

- Is the public key corresponding to your private key in your `/Users/matt/.ssh/authorized_keys` file?
- Is the permission on the key correct?

Maybe one thing you could try to do is to do `tail /var/log/auth.log` from one window and then connect via SSH with an RSA key with the other.

**Comment by bmelon** [comment]
Connecting with CLI through terminal is no problem. I tried adding id_rsa.pub to authorized_keys and made sure to chmod 600 it, still no luck.

TBH, It's not really an issue as I only wanted to SSH to localhost for writing tests. I've just added a check in my code so that localhost doesn't add the key.
