### ISSUE TITLE
PHP Fatal error: Use of undefined constant NET_SSH2_DISCONNECT_BY_APPLICATION

### ISSUE THREAD

**Issue by pmatseykanets** [phpseclib/phpseclib#1267]
I'm getting this error in php 7.2

```
PHP Fatal error:  Uncaught ErrorException: Use of undefined constant NET_SSH2_DISCONNECT_BY_APPLICATION - assumed 'NET_SSH2_DISCONNECT_BY_APPLICATION' (this will throw an Error in a future version of PHP) in /Users/user/src/application/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3146
```

**Comment by terrafrost** [comment]
idk what version of phpseclib you're using but it's defined in both.

In 2.0.11 it's initially defined in the constructor:

https://github.com/phpseclib/phpseclib/blob/2.0.11/phpseclib/Net/SSH2.php#L966

So a bunch of arrays are defined and then `$this->_define_array()` is called. `_define_array` loops through these arrays and defines them there:

https://github.com/phpseclib/phpseclib/blob/2.0.11/phpseclib/Net/SSH2.php#L4073

1.0.11 works the same way:

https://github.com/phpseclib/phpseclib/blob/1.0.11/phpseclib/Net/SSH2.php#L1017

So if you're using the latest version of phpseclib than I don't see how that's possible. If, otoh, you're using a ten year old version, then sure, maybe it is possible that that error could occur. idk what all bugs have been fixed for the past ten years but it's possible that one of them is the exact issue you're reporting. It's not a recent release that fixes this tho, that much I know.

**Comment by pmatseykanets** [comment]
Thank you so much for a quick response.

It was version 2.0.10 required by another package. Updated to 2.0.11.
Hopefully it's going to fix it.

Thanks again.

**Comment by terrafrost** [comment]
None of the changes made between 2.0.10 and 2.0.11 should affect this but if it works it works I guess..
