### ISSUE TITLE
Will you delete _parseKey in newer versions?

### ISSUE THREAD

**Issue by z3nth10n** [phpseclib/phpseclib#1270]
I'm having problems with jose from "Spomky Labs":

https://github.com/Spomky-Labs/jose/issues/326

And I'm using your lib as a reference to know what it's failing in, and the problem is related to the conversion needed from `_parseKey` and `_convertPrivateKey` && `_convertPublicKey`.

So, I need to know if this feature will be deleted or implemented in another way. Because I searched the code on the current master branch and I didn't find the `_parseKey` method neither `_convertPrivateKey` && `_convertPublicKey`.

**Comment by terrafrost** [comment]
`_parseKey` is not in the master branch. The master branch uses a plugin based approach. I do not plan on removing it from either the 1.0 or 2.0 branches.
