### ISSUE TITLE
SSH-Ed25519

### ISSUE THREAD

**Issue by Esysteme** [phpseclib/phpseclib#1279]
Hello,

it is a chance to see an implementation for ssh-ed25519 in phpseclib ?

**Comment by terrafrost** [comment]
Yes. I actually posted a status update last night about the status of Ed25519 in phpseclib:

https://github.com/phpseclib/phpseclib/issues/1082#issuecomment-396122366

**Comment by Esysteme** [comment]
thx you ;)

**Comment by bantu** [comment]
Closing this as a duplicate of #1082 and #1309
