### ISSUE TITLE
TwoFish CBC: _unpad breaks the decryption

### ISSUE THREAD

**Issue by mnpenner** [phpseclib/phpseclib#1280]
I was trying to debug why my decryption was failing. I tracked it to this function: `\phpseclib\Crypt\Base::decrypt`

In particular, this block here is strange:

```php
$plaintext = @mdecrypt_generic($this->demcrypt, $ciphertext);

if (!$this->continuousBuffer) {
    @mcrypt_generic_init($this->demcrypt, $this->key, $this->decryptIV);
}

return $this->paddable ? $this->_unpad($plaintext) : $plaintext;
```

Firstly, not that it matters, but isn't the `mcrypt_generic_init` pointless? The ciphertext was already decrypted by this point.

Anyway, `\phpseclib\Crypt\Base::_unpad` has this:

```php
$length = ord($text[strlen($text) - 1]);

if (!$length || $length > $this->block_size) {
    return false;
}
```

`$length` is coming back 0 for me, which makes sense, because there's no padding needed. However, phpseclib interprets this as a failure for some reason and then gives me back `false` even though it had already successfully decrypted my ciphertext...?

For reference, my code is:

```
$two = new Twofish(Twofish::MODE_CBC);
$strongkey = md5($salt . $WeakKey);                       
$DescrambleData = $this->BlockDescramble($SecretData, $strongkey);
unset($SecretData);
$ivsz = 16;                                           
$iv = substr($DescrambleData, 0, $ivsz);                               
$WorkData = substr($DescrambleData, $ivsz);                                      
unset($DescrambleData);
$two->setIV($iv);
$two->setKey($strongkey);
$two->paddable = false; // <-- this is needed so that phpseclib doesn't break
$compressed_data = $two->decrypt($WorkData);
if($compressed_data === false) throw new \Exception("Could not decrypt data");
```

**Comment by terrafrost** [comment]
> Firstly, not that it matters, but isn't the `mcrypt_generic_init` pointless? The ciphertext was already decrypted by this point.

Looks like it's setting it up for the next decryption. That you're only doing one decryption is not something phpseclib has any way of knowing.

**Comment by terrafrost** [comment]
> `$length` is coming back 0 for me, which makes sense, because there's no padding needed. However, phpseclib interprets this as a failure for some reason and then gives me back `false` even though it had already successfully decrypted my ciphertext...?

phpseclib uses PKCS7 padding. Quoting [RFC2315](https://tools.ietf.org/html/rfc2315#page-22):

        2.   Some content-encryption algorithms assume the
             input length is a multiple of k octets, where k > 1, and
             let the application define a method for handling inputs
             whose lengths are not a multiple of k octets. For such
             algorithms, the method shall be to pad the input at the
             trailing end with k - (l mod k) octets all having value k -
             (l mod k), where l is the length of the input. In other
             words, the input is padded at the trailing end with one of
             the following strings:

                      01 -- if l mod k = k-1
                     02 02 -- if l mod k = k-2
                                 .
                                 .
                                 .
                   k k ... k k -- if l mod k = 0

             The padding can be removed unambiguously since all input is
             padded and no padding string is a suffix of another. This
             padding method is well-defined if and only if k < 256;
             methods for larger k are an open issue for further study.

https://en.wikipedia.org/wiki/Padding_(cryptography)#PKCS7 talks about it as well. Basically, in that padding scheme, _something_ is always removed. For that reason, 0 is an invalid value, because bytes are always supposed to be removed.

**Comment by terrafrost** [comment]
Anyway, what you need to do is `$two->disablePadding()`.

**Comment by terrafrost** [comment]
> `$two->paddable = false; // <-- this is needed so that phpseclib doesn't break`

That's what `$two->disablePadding()` does. The phpDoc comments for `var $paddable` say that it's private and in the matser branch that'll eventually become the 3.0 branch it is explicitly private so that wouldn't work anyway...

**Comment by mnpenner** [comment]
Didn't notice the `disablePadding()` method; PhpStorm didn't turn it up when I searched for usages.

Thank you for clarifying everything @terrafrost! I'll just use that method then :smile: Sorry for the troubles.
