### ISSUE TITLE
Different result in C# Rijndael?

### ISSUE THREAD

**Issue by InkedCurtis** [phpseclib/phpseclib#1281]
I'm using the following in C# (in hex) to create a string & then decode it in PHP

    RijndaelManaged rijndaelManaged = new RijndaelManaged();
    rijndaelManaged.KeySize = 256;
    rijndaelManaged.BlockSize = 128;
    rijndaelManaged.Mode = CipherMode.CBC;

    ICryptoTransform decryptor = rijndaelManaged.CreateDecryptor(rgbKey, Array4);

    count2 = fileStream.Read(buffer4, 0, count1); //6D-18-80-01-DD-B6-3E-5B-26-83-CE-30-C7-AC-57-79
    cryptoStream.Write(buffer4, 0, count2);

    ^^ this value is 31-3B-3B-31-3B-3B-40-FD-00-20-A9-A2-00-08-71-CA
    
However, I can't seem to get the same result in PHP?

    $rgbKey = "de299ceff91f2a216969a22e482a6c1616c6e64e552d46ffafb713f1743e32d1";
    $rgbIv = "ECCD26BE791BB360E2010F6378CD5631";

    $rijndael = new Rijndael();
    $rijndael->setKey($rgbKey);
    $rijndael->setIV($rgbIv);
    $rijndael->enableContinuousBuffer();
    $rijndael->setKeyLength(256);
    $rijndael->setBlockLength(128);

    echo bin2hex($rijndael->decrypt("6D188001DDB63E5B2683CE30C7AC5779")); 

    ^^ this value is c3d0ea2da27565c46fc7f1d2c0684baaf246

Although, when using the same key & IV, I can get the correct result here: http://aes.online-domain-tools.com/link/1300553gqcXhtYR9LB/ but cannot replicate it within phpseclib?

I've also found a way to do it using `openssl_decrypt` how can I replicate this using phpseclib?

    $result = openssl_decrypt{
        hex2bin($raw_binary_string),
        'AES-256-CBC',
        hex2bin($rgbKey),
        OPENSSL_RAW_DATA|OPENSSL_ZERO_PADDING,
        hex2bin($rgbIv)
    );

**Comment by terrafrost** [comment]
You know how you're using `hex2bin` with OpenSSL? You need to use it with phpseclib as well.

Here's your code, updated to use `hex2bin`:

```php
$rgbKey = "de299ceff91f2a216969a22e482a6c1616c6e64e552d46ffafb713f1743e32d1";
$rgbIv = "ECCD26BE791BB360E2010F6378CD5631";

$rijndael = new Rijndael('cbc');
$rijndael->setKey(hex2bin($rgbKey));
$rijndael->setIV(hex2bin($rgbIv));
$rijndael->enableContinuousBuffer();
$rijndael->setKeyLength(256);
$rijndael->setBlockLength(128);
$rijndael->disablePadding();

echo bin2hex($rijndael->decrypt(hex2bin("6D188001DDB63E5B2683CE30C7AC5779"))); 
```
Gives me the same result as your C# code.

**Comment by terrafrost** [comment]
Oh - I also had to add `$rijndael->disablePadding();`.

**Comment by InkedCurtis** [comment]
@terrafrost Thankyou!
