### ISSUE TITLE
SFTP..login() breaks on Mac OS 10.3.5 Server edition

### ISSUE THREAD

**Issue by bedmison** [phpseclib/phpseclib#1282]
On Mac OS X 10.3.5, using the Server version, running PHP 7.1.13, when I run this code (based on the sample code):

    <?php
    require __DIR__ . '/vendor/autoload.php';
    
    use phpseclib\Net\SFTP;
    
    $sftp = new SFTP('<dns for SFTP server>');
    error_log('This log statement will be captured in the log');

    if (!$sftp->login('user', 'pw')) {  //<--  code fails here
        exit('Login Failed');
    }else{
        error_log('Should be in the log on successful login, but never executes');
    }

    error_log('This log statement will not be captured in the log');
    echo $sftp->pwd();

    $sftp->chdir('test'); // open directory 'test'
    print_r($sftp->pwd()); // show that we're in the 'test' directory
    print_r($sftp->nlist()); // get the listing

    ?>

the code fails at the call to login(). Apache displays a 502 Proxy Error and this error is written to the apache error_log:

`[core:notice] [pid 46552] AH00052: child pid 49065 exit signal Illegal instruction (4)`

In the Mac Server version, Apache is running in a proxyed configuration. When I run this on a Mac without the Mac server version (but same major OS version 10.3.5), it executes as expected. 

I've looked at the code, but I'm not sure how to most effectively debug this or provide the info to help debug this is. Is there any kind of special configuration I have to do to make phpseclib work in a proxied environment? Any insight would be appreciated.

**Comment by terrafrost** [comment]
I would place `exit('this far');` at successive places in the code to figure out where it's occurring. Like maybe place one before Net/SSH2.php's `fsockopen` call to verify that it's getting at least that far. Then remove it and place it after `fsockopen` to see if the fsockopen is being successfully being performed, etc.

You can do it like a binary search too. Like try placing it in the middle of the constructor and then place it 1/4 of the way in the constructor or 3/4 of the way in the constructor depending on whether or not you see the "this far".

A quick Google search, however, suggests that there may not be much that I can do from a PHP perspective. It sounds like this might be an issue with PHP itself and that recompiling PHP might be the best bet:

https://github.com/phalcon/cphalcon/issues/2082

**Comment by bedmison** [comment]
I'll try to exit() strategy.

I saw that thread about phalcon, but discounted it. I'm running the same version of php, built with the same flags,  on the same base OS version, built on exact same Apple hardware. phpseclib works on one of the computers, and doesn't on the other. The only difference is the way Apache is configured.

**Comment by bantu** [comment]
Try the above code without cphalcon?
