### ISSUE TITLE
Connection closed prematurely error 

### ISSUE THREAD

**Issue by phodat** [phpseclib/phpseclib#1283]
Hello, I am trying to figure out why I keep getting this error. The library is working well for me on Cisco Routers but when I try to SSH into a ACME SBC it keeps disconnecting during any exec statements. The initial connection always comes back good, but as as soon as I try to send anything to the SBC. it drops immediately. Help!!

Using Library 2.0.11 on windows XAMPP platform PHP version 5.6
Error Msg:
Connection closed prematurely on 3217 in C:\xampp\htdocs\includes\phpseclib\Net\SSH2.php

I have tried commenting out the algorithms:
//     'arcfour256',
//     'arcfour128',
without any success thus far.

I added an extra if check after line 3217:

if (!is_resource($this->fsock) || feof($this->fsock)) {
     if (feof($this->fsock)){
          user_error('Connection closed prematurely Due to FEOF');
     }
     user_error('Connection closed prematurely');
     $this->bitmap = 0;
     return false;
}
and it confirms that I am getting feof early for some reason

Also, an addl test is that I put a 1 second pause between the connect and exec statements. In this case I catch eof immediately

function _send_binary_packet($data, $logged = null)
    {
        if (!is_resource($this->fsock) || feof($this->fsock)) {
            if (feof($this->fsock)) {
                user_error('Connection closed prematurely Due to FEOF');
            }
            user_error('Connection closed prematurely');
            $this->bitmap = 0;
            return false;
        }
....
}

I also attempted similar tests with write and read methods. If I insert a pause between write and read then I get premature disconnect and an error saying interactive shell cannot be made. No pause then i get blank back for the command sent.

Appreciate any help offered. Thanks in advance!

[ssh.log](https://github.com/phpseclib/phpseclib/files/2194442/ssh.log)

**Comment by phodat** [comment]
I added an extra if check after line 3217:
if (feof($this->fsock))
if (feof($this->fsock))
            {
                user_error('Connection closed prematurely Due to FEOF');
            }
and it confirms that I am  getting feof early for some reason

**Comment by terrafrost** [comment]
Looks like it's dying here:

```
-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s)
00000000  05:18:07:d2:00:00:00:04:65:78:65:63:01:00:00:00  ........exec....
00000010  15:73:68:6f:77:20:73:65:63:75:72:69:74:79:20:73  .show security s
00000020  75:6d:6d:61:72:79                                ummary
```

It's possible it only allows `exec` commands with a PTY, at which point, you could do `$ssh->enablePTY()`. It's also possible that the server only accepts interactive shells, at which point you'd need to do `$ssh->read('[prompt]');` and then `echo $ssh->read('[prompt]');`.

**Comment by phodat** [comment]
I had tried enabled PTY before but what I did not try was the initial read then writing and read again. that was the part that I was missing. Thanks!
