### ISSUE TITLE
Provide fallback for utf8_decode

### ISSUE THREAD

**Issue by DavidAnderson684** [phpseclib/phpseclib#1289]
If an end-user doesn't have php-xml installed, then the function `utf8_decode()` is not available. One user just encountered this with the ssh-sftp-updater-support WP plugin :  https://wordpress.org/support/topic/php-fatal-error-145/

The function is used by phpseclib only inside one file, `Net/SSH2.php`.

This function can apparently be re-implemented in around 20-30 lines of PHP; search for `utf8_decode` in: https://github.com/JamesHeinrich/getID3/blob/master/getid3/getid3.lib.php

Would it be worth including a fill-in for this method to help users in deployments where php-xml is not active?

**Comment by terrafrost** [comment]
What would you think if I just removed `utf8_decode` all together?

http://php.net/utf8-decode says it "_converts a string with ISO-8859-1 characters encoded with UTF-8 to single-byte ISO-8859-1_". The most common ISO-8859-1 characters are encoded the same in UTF-8 and ISO-8859-1. The ones that aren't - characters like `è` - aren't as commonly used. And if they are used...  maybe the person can either live with `?`'s appearing on the page or maybe they can set the page encoding to UTF-8 or the browser can auto-deduce that they're UTF-8 or whatever.

Besides, it doesn't sound like `utf8_decode` care of characters that aren't in ISO-8859-1. eg. `ɛ`. `utf8_decode` just decodes that to `?` (ie. `0x3f`).

**Comment by DavidAnderson684** [comment]
I haven't looked at the code closely, but, if you think it makes no difference then it would seem reasonable to throw in a `if (function_exists('utf8_decode'))` and, if it wasn't there, carry on anywhere. The result presumably can't be worse than a Fatal.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/bee6183bd743477598e9757031979100d6b7a1ce should resolve this.
