### ISSUE TITLE
how can i build publickey ,i have a modulus and exponent

### ISSUE THREAD

**Issue by qq690712575** [phpseclib/phpseclib#1290]
I get the modulus  and exponent。
$exponent = 'AQAB';
$modulus = '00cb43da4b6602c17404e2d8be987d4ccb822836d85fd4cc6029338ef5b28908a9c9e7a0832acf9e8e15dc99bb340bdcdf53740bb4e449243c9d3c1f71773afb883a80e91844685487a6b911803ee7f76adcdc1360a7ae95a373f4432e7e6e12a009a8e9771cf775f6dab1f39ebd03d26ccded12e054b1ab85c861bdbfca225cff';

how can i build publickey and encrypt data

**Comment by qq690712575** [comment]
Thank,but I use 2.0branch

- 发送自我的Sony Xperia™智能手机

---- terrafrost编写 ----


<?php
include('Crypt/RSA.php');
include('Math/BigInteger.php');

$exponent = 'AQAB';
$modulus = '00cb43da4b6602c17404e2d8be987d4ccb822836d85fd4cc6029338ef5b28908a9c9e7a0832acf9e8e15dc99bb340bdcdf53740bb4e449243c9d3c1f71773afb883a80e91844685487a6b911803ee7f76adcdc1360a7ae95a373f4432e7e6e12a009a8e9771cf775f6dab1f39ebd03d26ccded12e054b1ab85c861bdbfca225cff';

$rsa = new Crypt_RSA();
$rsa->loadKey([
        'e' => new Math_BigInteger(base64_decode($exponent), 256),
        'n' => new Math_BigInteger(base64_decode($modulus), 256)
]);

echo $rsa;

This code snippet uses the 1.0 branch to convert a modulus / exponent to a more recognizable public key format. If you want to encrypt (as opposed to just converting the key) just replace the echo $rsa with this:

echo base64_encode($rsa->encrypt('ddd'));

**Comment by qq690712575** [comment]
Thanks for your help.
I used openssl_public_encrypt($pwd, $encrypted, $rsa) to encrypt my data . $rsa is a cert resource?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: terrafrost <notifications@github.com>
发送时间: Sunday, August 19, 2018 9:22:37 PM
收件人: phpseclib/phpseclib
抄送: Jianle Chen; Author
主题: Re: [phpseclib/phpseclib] how can i build publickey ,i have a modulus and exponent (#1290)


It's pretty much the same thing - just swap out the include's with an include to the autoloader and use statements and then remove the Crypt_ / Net_ prefix from the object instantiations.

<?php
require __DIR__ . '/vendor/autoload.php';

use phpseclib\Crypt\RSA;
use phpseclib\Math\BigInteger;

$exponent = 'AQAB';
$modulus = '00cb43da4b6602c17404e2d8be987d4ccb822836d85fd4cc6029338ef5b28908a9c9e7a0832acf9e8e15dc99bb340bdcdf53740bb4e449243c9d3c1f71773afb883a80e91844685487a6b911803ee7f76adcdc1360a7ae95a373f4432e7e6e12a009a8e9771cf775f6dab1f39ebd03d26ccded12e054b1ab85c861bdbfca225cff';

$rsa = new RSA();
$rsa->loadKey([
        'e' => new BigInteger(base64_decode($exponent), 256),
        'n' => new BigInteger(base64_decode($modulus), 256)
]);

echo $rsa;

―

**Comment by terrafrost** [comment]
> $rsa is a cert resource?

No - it's an RSA object with a `__toString` magic method.

That said, you don't need to use OpenSSL to perform the encryption. phpseclib is perfectly capable of that. eg.:

```php
echo base64_encode($rsa->encrypt('ddd'));
```

If you really want to use `openssl_public_encrypt` instead of `$rsa->encrypt` you're free to do so. If memory serves, `$key` can be a string so you could trigger the `$rsa` `__toString` magic method by doing `"$rsa"`.

**Comment by qq690712575** [comment]
Thank you for helping me solve this problem and make the service website made by my school community better.

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: terrafrost <notifications@github.com>
发送时间: Monday, August 20, 2018 12:15:34 AM
收件人: phpseclib/phpseclib
抄送: Jianle Chen; Author
主题: Re: [phpseclib/phpseclib] how can i build publickey ,i have a modulus and exponent (#1290)


$rsa is a cert resource?

No - it's an RSA object with a __toString magic method.

That said, you don't need to use OpenSSL to perform the encryption. phpseclib is perfectly capable of that. eg.:

echo base64_encode($rsa->encrypt('ddd'));

If you really want to use openssl_public_encrypt instead of $rsa->encrypt you're free to do so. If memory serves, $key can be a string so you could trigger the $rsa __toString magic method by doing "$rsa".

―

**Comment by guihouchang** [comment]
> ```
> ```
> <?php
> include('Crypt/RSA.php');
> include('Math/BigInteger.php');
> 
> $exponent = 'AQAB';
> $modulus = '00cb43da4b6602c17404e2d8be987d4ccb822836d85fd4cc6029338ef5b28908a9c9e7a0832acf9e8e15dc99bb340bdcdf53740bb4e449243c9d3c1f71773afb883a80e91844685487a6b911803ee7f76adcdc1360a7ae95a373f4432e7e6e12a009a8e9771cf775f6dab1f39ebd03d26ccded12e054b1ab85c861bdbfca225cff';
> 
> $rsa = new Crypt_RSA();
> $rsa->loadKey([
> 	'e' => new Math_BigInteger(base64_decode($exponent), 256),
> 	'n' => new Math_BigInteger(base64_decode($modulus), 256)
> ]);
> 
> echo $rsa;
> ```
> 
> 
> This code snippet uses the 1.0 branch to convert a modulus / exponent to a more recognizable public key format. If you want to encrypt (as opposed to just converting the key) just replace the `echo $rsa` with this:
> ```
> echo base64_encode($rsa->encrypt('ddd'));
> ```
> ```

Hi, I get  RSA string leng is 384, not 256. This is my code, is anything wrong whith my code? plz help me, and thank you.

result(use PHP): 018E5DD303A756B77A9E04B4FAB440967EE862CB173877EE3C379A3149D6659A907F5DB647E62EFF3435D820DFA164F155C71D7ED99691CA16AF934F2C5109964DA4AF7803EA8404332DEB2F5C13B376C25ED9FC64D0B84E6D9CDF3A53CFD9D0A6DBE5BF5DA09B405B83CAAE818F882DCA31560C59D963BDADF36962BCEE74DC4D660295960D319AB18B8F986B1DC72BAC02BA0E70102CB7A036BB9A0A87375FC887367F09975F7A79FEB49617369F0BEBAC5978F32BA1E5E7EF539418A6664E

==== code ======
 public function testRSAAction()
    {
        $modulus = 'BB955F6C6185B341C1A42EBF1FF9971B273878DBDAB252A0F1C305EBB529E116D807E0108BE6EDD47FF8DC5B6720FFE7F413CBB4ACDFB4C6BE609A5D60F5ADB261690A77755E058D4D9C0EC4FC2F5EB623DEBC88896003FBD8AFC4C3990828C66062A6D6CE509A2B0F8E06C4E332673FB86D235164B62B6110C1F1E0625B20ED';
        $exponent = '10001';
        $rsa = new Crypt\RSA();
        $rsa->loadKey([
            'e' => new Math\BigInteger(base64_decode($exponent), 256),
            'n' => new Math\BigInteger(base64_decode($modulus), 256)
        ]);

        return strtoupper(bin2hex($rsa->encrypt('123')));
    }

**Comment by bantu** [comment]
Your input data are hex strings. Applying base64 decode seems wrong.

**Comment by florianpasquereau** [comment]
Hello, I have to reproduce the java code bellow in PHP
```
byte[] modulusB = Base64.getUrlDecoder().decode(modulusB64u);
BigInteger modulus = new BigInteger(1, modulusB);
System.out.println("modulus " + modulus);
```

this is what I did :
```
$n = new BigInteger(base64_decode(modulusB64u), -256);
dd($n->toString())
```

If I send  `AQAB` I have the correct result `65537` **exponent**
Now if I do the same with the **modulus**
```
tuvQMkcuXqle4bK6Rljf8JVwFWj905KJkofg83r-3tHZRwSXiCt9gJxtGfuL_TkKVgamP9eghixaViAltTQnim8drsPpTzDhLON9oM3xAAFinONy0Q58oNhChoPUGPSf37rGbSYPKo9Yi_U2vxoZ5SRcxaKjEYIugJ4DecOpuQgGt2ZDffzdbZDEFLDPaHU4EVxQ6s26QGf9KatVQYOAAuKxCnz6bBx27oIwshO6-4P8LNYIUlHQoqmHxHVqE9eUHw8LY2OJp0TRUGMc9AbECU4ssh1M46vRnhMJQOxXyGIrIl3RAJlQByQkmkldGCzozhL0tV7Q63GL9j20Zrr8CQ
```
I get a totally different result ...

Java return me 
```
23091655359828866917830467906030605973578647404311797556076741516568386519196729728123897221500774651790907042149716245691990902542989373053506456225151006465063711445101315612994930999471726138287013825911860270200501622452105990613206291489844219864194686779640928155414306861976880014077027593570653421893911887655780837301199479850921928627371487102278737296232708409879966961262066505766139293193167052601987989387185061039254115723027870288413864538961879040374388653059309295765435708865315005426661240077746819973280992148151882439048258343681282702430404044802404693992621584677630014408112459639580459203593
```

PHP return me 
```
-549873752086290143900180386462172626666155771339159397843694920000807568474589458651731313833933653280205082630960034052388061938995686167700354768763204719659890448368302784123356699459088442607195441730732771906202345667293430368030570915046442372524611197497330538625858599478248004029694705186607997131312095916631939301923988760858479639908748217412817918506817299449304156324293938188732357964438935197003183464052344882445336079353502760845587708305998131941453891738784535896470583655028612044341985655234202552746289183243686933919626870447846784617123092190079088798371826396376272391525140229587959
```

My Expected result is the java one. Any idea what I missed ?
Thank you

**Comment by terrafrost** [comment]
First, this would have been better as a new topic vs a reply to an existing one.

That said, PHP's `base64_decode` is doing MIME base64 whereas you're doing Base64URL with Java. You need to transform the base64 encoded data for PHP's `base64_decode` to give you the correct result. See https://www.php.net/manual/en/function.base64-decode.php#71583 for more info.
