### ISSUE TITLE
Attempted to call an undefined method named "setEngine" of class "phpseclib\Crypt\RC4"

### ISSUE THREAD

**Issue by adrienHoareau** [phpseclib/phpseclib#1294]
Hello,

In a sftp connexion, I want to use the internal crypto engine instead of the mcrypt engine.
So I do :
$client = new SFTP($myHost, $myPort);
$client->setCryptoEngine(1);// method in SSH2 class
$client->login($username, $password);

And then I got the error :
Attempted to call an undefined method named "setEngine" of class "phpseclib\Crypt\RC4"

I think it is because of this  : 
$this->encrypt->setEngine($this->crypto_engine); // in SSH2 class at line 1823

There is no method setEngine in the project, only _setEngine which is private, so I think It should be replace by : 
$this->encrypt->setPreferredEngine($this->crypto_engine);

I'm not confortable with git so I don't know how to do this change by myself. Can someone do the fix ?

**Comment by adrienHoareau** [comment]
By the way I would like to know if someone knows how to set the cipher to use when using the SFTP class ?

**Comment by terrafrost** [comment]
This should work better as of the latest commit.

> By the way I would like to know if someone knows how to set the cipher to use when using the SFTP class ?

There's not really a good way to do this atm. I do intend to significantly revamp the SSH2 API at some point but my priorities atm are on updating phpseclib's underlying cryptographic primitives.

**Comment by adrienHoareau** [comment]
thank you very much, it works great !
