### ISSUE TITLE
SSL certificate of phpseclib.org expired

### ISSUE THREAD

**Issue by PHPGangsta** [phpseclib/phpseclib#1299]
Some Google search results point to phpseclib.org

The certificate expired on October 1, 2018, 11:30:38 AM GMT+2. The current time is October 5, 2018, 4:19 PM.

https://phpseclib.org
https://api.phpseclib.org/master/Net_SSH2.html

**Comment by terrafrost** [comment]
@bantu maintains that website. Seems like a Let's Encrypt cert would be good.

**Comment by bantu** [comment]
Thanks for reporting. Should be fixed.
