### ISSUE TITLE
php seclibrary decryption error

### ISSUE THREAD

**Issue by esraanaem** [phpseclib/phpseclib#1304]
i am using php seclibrary RSA cipher for autjetication system, in registration the system encrypt the user password with the public key and saved in the data base along with the private key which i will need for decryption, in login using MYSAL query to get the encrypted password and the private key but i cannot decrypt it,here the decrypt code function dec_pass(){
              global $pas,$pp;

           $rsa = new Crypt_RSA();
            $privatekey=$pp;
                // $p= $rsa->getPrivateKey($pp);
                                     
              $rsa->loadKey($privatekey);

           $passes = $rsa->decrypt($pas);
         echo $passes;
        help me please

**Comment by terrafrost** [comment]
phpseclib uses OAEP padding by default. Maybe whatever is doing the encryption is using PKCS1 padding instead. You can do that by doing `$rsa->setEncryptionMode(CRYPT_RSA_ENCRYPTION_PKCS1)` before you perform the actual decryption.

**Comment by terrafrost** [comment]
Post the key. If the key is being used for sensitive data then create a new key using the same method to create the old key. Then post some ciphertext encrypted with it. Base64 encode it so that non-printable characters don't get lost.

Also, post how both the key and the ciphertext are being generated.

**Comment by esraanaem** [comment]
$rsa = new Crypt_RSA();
       extract($rsa->createKey());
    $username=$_POST['username'];
          $rsa->setEncryptionMode(CRYPT_RSA_ENCRYPTION_PKCS1);
 $rsa->setPrivateKeyFormat(CRYPT_RSA_PRIVATE_FORMAT_PKCS1);
 $rsa->setPublicKeyFormat(CRYPT_RSA_PUBLIC_FORMAT_PKCS1);
        $rsa->loadKey($publickey);
   $pass = $rsa->encrypt($password);
//echo $pass;
   $pp= $rsa->loadKey($privatekey);
 $query="insert into login (username,password,pp) values ('$username','$pass','$pp')";
       $result=mysql_query($query);

**Comment by terrafrost** [comment]
Given how you're using it I'd use PHP's built in password hashing functions:

http://php.net/manual/en/ref.password.php

That said, for `$pass`...  I'd base64 encode it if you're gonna store it to the DB. VARCHAR or TEXT are not sufficient - VARBINARY or BLOB are what should be used:

https://dev.mysql.com/doc/refman/8.0/en/binary-varbinary.html
https://dev.mysql.com/doc/refman/8.0/en/blob.html

**Comment by bantu** [comment]
@esraanaem great!
