### ISSUE TITLE
Hostkeys Error from SSH

### ISSUE THREAD

**Issue by dehrk** [phpseclib/phpseclib#1306]
Everything appears to be successful with the login, and the commands I run using the SSH2 class, but I'm still getting this error: `SSH_MSG_GLOBAL_REQUEST: hostkeys-00@openssh.comssh-rsa̃7Y: n:I#-6r1Z)j}Økf
                                                                                                           Ͷ
                                                                                                            (7]nx7ZvJUᇏڞ
                                                                                                                           u؊~lF5/袼}[^,N^0`

**Comment by dehrk** [comment]
[ssh_log.txt](https://github.com/phpseclib/phpseclib/files/2531513/ssh_log.txt)

**Comment by terrafrost** [comment]
Did you get that with `$ssh->getErrors()` or `$ssh->getLastError()`? If so then that's not really an error. A lot of the errors in that are more informational thing anything.

**Comment by dehrk** [comment]
Getting that from `getErrors()`. If I can't rely on that function, how should I be checking for errors?

**Comment by terrafrost** [comment]
`getErrors()` is like PHP's E_NOTICE.

Overall, I'd say that none of the errors that show up in that are going to be very severe. The more severe errors will result `user_error()` errors or full on PHP errors.

Consider a failed authentication attempt. There'll probably be an entry in `$ssh->getErrors()` but how severe is that? If you're using phpseclib to brute force an SSH password (nefarious tho that task may be) it's not really an error. It's kinda the expected outcome.

Maybe in a new version of phpseclib I might have different error levels but even that would be a bit subjective. "Exceptional" errors would still be optimally handled be exceptions being thrown (they're thrown in the master branch but not in the 1.0 / 2.0 branches).

**Comment by dehrk** [comment]
Awesome. Thanks for a the tips.
