### ISSUE TITLE
remote copy

### ISSUE THREAD

**Issue by nathanaelmartel** [phpseclib/phpseclib#1308]
Hi, I don't knw if it is a bug or a feature.

I use flysystem with  sftp adaptator and I just tried to copy a file using copy(). 

As it was very slow, I monitor the network and it's appear that the function download and then upload the file.

It is not possible to make a remote copy, I mean without downloading and uploading the file ?

**Comment by nathanaelmartel** [comment]
By remote copy, I mind that both files are on the same filesystem, on the same server.

**Comment by nathanaelmartel** [comment]
for people who have the same problem, I just did that for the moment 

```
$conn = ssh2_connect('example.com', 22);
ssh2_auth_password($conn, 'username', 'password');

$stream = \ssh2_exec($conn, 'cp source_file_path dest_file_path');
```

It is not as convenient as using the API but it's work…

**Comment by terrafrost** [comment]
There is no way to do what you are wanting using pure SFTP. The libssh2 approach you're using (1) isn't SFTP and (2) can be done with phpseclib:

```php
$sftp->exec('cp source_file_path dest_file_path');
```
