### ISSUE TITLE
Support for ed25519 and possibly ecdsa keys

### ISSUE THREAD

**Issue by AlexMax** [phpseclib/phpseclib#1309]
I am able to use RSA keypairs with this library just fine, but recent versions of OpenSSH support `ed25519` and `ecdsa` keys, which begin with:

`-----BEGIN OPENSSH PRIVATE KEY-----`

and

`-----BEGIN EC PRIVATE KEY-----`

respectively.

I have been able to use RSA keys with this library with no problem, but I have not been able to figure out how to get `ed25519` keys working, and I don't even know about `ecdsa`.

**Comment by terrafrost** [comment]
I have a branch that adds support for Ed25519 / ECDSA here:

https://github.com/terrafrost/phpseclib/tree/ecdsa

Keys of the format you describe are also supported, altho encrypted OpenSSH private keys are not, because OpenSSH has a custom bcrypt implementation and just as PHP is too slow for pure-PHP Argon2i implementation in [sodium_compat](https://github.com/paragonie/sodium_compat) PHP is too slow for a good pure-PHP bcrypt implementation.

The unit tests are still being worked on.

**Comment by demyxco** [comment]
Hello any news on this? I noticed master has the Crypt/ECDSA but it's not there in composer.

**Comment by terrafrost** [comment]
> I noticed master has the Crypt/ECDSA but it's not there in composer.

I'm not completely sure what you mean.

You could do `composer install phpseclib/phpseclib:dev-master` to install master altho, personally, I wouldn't recommend it, unless you're just wanting to test it out.

Right now I'm working on ECDH / Curve25519 / Curve448. After that I'll prob let the master sit for a few weeks and will then release 3.0.0.

**Comment by demyxco** [comment]
I don't think I'll use dev-master in production. I installed phpseclib via `composer require phpseclib/phpseclib:~2.0` and it doesn't have support for ed25519.

**Comment by terrafrost** [comment]
> I installed phpseclib via composer require phpseclib/phpseclib:~2.0 and it doesn't have support for ed25519.

That is correct. phpseclib/phpseclib:~2.0 will never have support for ed25519. The changes I've made to phpseclib to allow for elliptic curves and what not are BC breaking, hence their being in the master branch that'll eventually become the 3.0 branch.

**Comment by demyxco** [comment]
Thanks for the info, makes sense now. I'll be using RSA for the time being. Thank you again for the project!

**Comment by solaryssky** [comment]
Good day. Tell me, is there a version now that supports ed25519?

**Comment by solaryssky** [comment]
> > I installed phpseclib via composer require phpseclib/phpseclib:~2.0 and it doesn't have support for ed25519.
> 
> That is correct. phpseclib/phpseclib:~2.0 will never have support for ed25519. The changes I've made to phpseclib to allow for elliptic curves and what not are BC breaking, hence their being in the master branch that'll eventually become the 3.0 branch.

Good day. Tell me, is there a version now that supports ed25519?

**Comment by terrafrost** [comment]
> Good day. Tell me, is there a version now that supports ed25519?

No. They're supported in the master branch, which can be installed by doing `composer require phpseclib/phpseclib:dev-master`.

I'm currently working on updating the HMAC support and once that's done I plan on creating a new 3.0 branch from master. So all I can say is that a new release is on the horizon.

**Comment by solaryssky** [comment]
OK. I will wait for version 3.0 from you. Thank.

**Comment by duckchip** [comment]
What's the status of this ticket? Is it already part of 3.0? Thx!

**Comment by terrafrost** [comment]
> What's the status of this ticket? Is it already part of 3.0? Thx!

Yes. See https://phpseclib.com/docs/ec
