### ISSUE TITLE
README unclear about LTS for 2.0

### ISSUE THREAD

**Issue by appills** [phpseclib/phpseclib#1310]
The README states that 1.0 is an LTS release, but I see that 1.0 was merged into 2.0 2 days ago (11/3/2018)

Should new users of phpseclib be using the 2.0 branch? If so, this should be called out in the README.

![image](https://user-images.githubusercontent.com/20586284/48024235-b7d3d780-e105-11e8-927b-d0f7f633e51d.png)

**Comment by terrafrost** [comment]
I'd say both should be considered as LTS releases. And As for which one people should use...  either work. The 2.0 branch has a small handful of minor features that 1.0 doesn't have but for the most part they're identical. This won't be the case with the 3.0, however. 3.0 is going to have major features that aren't present in either 1.0 or 2.0.
