### ISSUE TITLE
validateDate errors

### ISSUE THREAD

**Issue by curunoir** [phpseclib/phpseclib#1318]
Hello,

I'm trying to use v2.0 to validate dates from x509 cert files. I instaled the package with _composer require phpseclib/phpseclib:~2.0_

```
$x509 = new X509();
$x509->loadX509(file_get_contents($cert_path, "r"));
return $x509->validateDate($date);
```
But I'm getting always getting this error either $date contains a valid datetime string or null :
DateTime::__construct() expects parameter 1 to be string, object given

The error is launched on the line 
`      case $date < new DateTime($notBefore, new DateTimeZone(@date_default_timezone_get())):`

It seems to be related to the dates within the certificate, which looks correct to me. When I dump the $notBefore var this is what I get 
```
DateTime @1542364364 {#3721 ▼
  date: 2018-11-16 10:32:44.0 +00:00
}
```
which is the correct start date of the certificate.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/476cb127b16e0759066b5e69c52f2aa42117bfbe should fix the issue. I added a unit test for this as well.

That said...  from your code:

```php
$x509->loadX509(file_get_contents($cert_path, "r"));
```
[file_get_contents](http://php.net/file-get-contents)' second parameter is a boolean. `$use_include_path`

**Comment by curunoir** [comment]
Thanks ²
