### ISSUE TITLE
SSH2->login('username', $agent) fails as of 2.0.12

### ISSUE THREAD

**Issue by kralos** [phpseclib/phpseclib#1319]
Since version `2.0.12` It's no longer possible to login with `Agent`

This was working in version `2.0.11`

Example implementation:

```php
<?php

declare(strict_types=1);

require __DIR__.'/vendor/autoload.php';

$agent = new phpseclib\System\SSH\Agent();
$ssh = new phpseclib\Net\SSH2('my.host.com');
$authenticated = $ssh->login('myuser', $agent);
var_dump($authenticated); // true in v2.0.11, false as of v2.0.12
```

```bash
kralos@maia:~/src/test$ php sftp-test.php 
bool(true)
kralos@maia:~/src/test$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating phpseclib/phpseclib (2.0.11 => 2.0.12):  Checking out 8814dc7841
Writing lock file
Generating autoload files
kralos@maia:~/src/test$ php sftp-test.php 
bool(false)
kralos@maia:~/src/test$ 
```

Environment:

| property               | version                         |
|-------------------|--------------------------------------|
| php               | 7.2.12 (cli)                         |
| local host        | debian 9.6 x64                       |
| target host       | debian 9.5 x64                       |
| target ssh server | OpenSSH Server 7.4p1-10+deb9u4 amd64 |

```
kralos@maia:~/src/test$ php -v
PHP 7.2.12 (cli) (built: Nov  9 2018 23:40:34) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.12, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.1, Copyright (c) 2002-2018, by Derick Rethans
kralos@maia:~/src/test$ 
```

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/8f2a0e6f0da1e4365077487cfff58a388a1194a5 should fix this.

The problem was introduced with https://github.com/phpseclib/phpseclib/commit/b57976ec5ffc556f31036f713d5079ad59feb5d7 , which added support for rsa-sha2-256 and rsa-sha2-512, as discussed in RFC8332. The problem was that the SSH Agent code wasn't updated to work with those new hashes.
