### ISSUE TITLE
$sftp->login('ubuntu', $agent) failed for me

### ISSUE THREAD

**Issue by srinivas2v** [phpseclib/phpseclib#1321]
Hi.

I got this error using phpseclib version: "2.0.12"

PHP code:

<pre>
require __DIR__ . '/vendor/autoload.php';

use phpseclib\Net\SFTP;
use phpseclib\System\SSH\Agent;

define('NET_SSH2_LOGGING', 2);

$agent = new Agent();
$sftp = new SFTP('3.33.33.333'); //my host ip address
$connected = $sftp->login('ubuntu', $agent); // my username with sftp agent
var_dump($connected);
print_r($sftp->getLastError());
print_r($sftp->getLastSFTPError());
print_r($sftp->getErrors());
</pre>
PHP Error:
<pre>
Notice: SSH_AUTH_SOCK not found in phpseclib/System/SSH/Agent.php on line 130
bool(false) Array ( )
</pre>
how can i fix this?

my PHP Version:
<pre>
srini@ubuntu:~$ php -v
PHP 5.6.36-1+ubuntu16.04.1+deb.sury.org+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
</pre>
And i am able to login through my ubuntu terminal using ssh-agent:
<pre>
srini@ubuntu:~$ sftp ubuntu@3.33.33.333
Connected to 3.33.33.333.
sftp> ls
MyInbox   
sftp>
</pre>
Thank you.
Srini

**Comment by bantu** [comment]
You need to provide the SSH_AUTH_SOCK variable (either in the SERVER
array or the ENV array), which contains the filesystem path to your
ssh agent socket.

**Comment by v5srinivas** [comment]
Thanku for @bantu,

My $_SERVER and $_ENV are not taking my SSH_AUTH_SOCK path

<pre>
srini@ubuntu:~$ echo $SSH_AUTH_SOCK
/run/user/1000/keyring/ssh
srini@ubuntu:~$
</pre>

How can i set my filesystem path to my ssh agent socket.

**Comment by bantu** [comment]
$_SERVER['SSH_AUTH_SOCK'] = '/run/user/1000/keyring/ssh';

should do it

@terrafrost Maybe agent should have a constructor taking a socket path.

**Comment by v5srinivas** [comment]
It was giving Permission denied.

<pre>
Warning: fsockopen(): unable to connect to unix:///run/user/1000/keyring/ssh:0 (Permission denied) in phpseclib/System/SSH/Agent.php on line 134

Notice: Unable to connect to ssh-agent (Error 13: Permission denied) in phpseclib/System/SSH/Agent.php on line 136
bool(false) Array ( )
</pre>

**Comment by terrafrost** [comment]
> $_SERVER['SSH_AUTH_SOCK'] = '/run/user/1000/keyring/ssh'; should do it @terrafrost Maybe agent should have a constructor taking a socket path.

I think that's a good idea. I'll try to do it this weekend.



> It was giving Permission denied.
> 
> Warning: fsockopen(): unable to connect to unix:///run/user/1000/keyring/ssh:0 (Permission denied) in phpseclib/System/SSH/Agent.php on line 134
> 
> Notice: Unable to connect to ssh-agent (Error 13: Permission denied) in phpseclib/System/SSH/Agent.php on line 136
> bool(false) Array ( )

I have no idea what's up with that. Maybe you could try `setsebool -P httpd_can_network_connect 1`? It's a setting on SELinux.

That said, if you are able to get passed that error you may still have issues with #1319. That issue is fixed in the latest git version but that fix is not in 2.0.12. A new release would need to be done.

**Comment by bantu** [comment]
The most likely scenario is that PHP is run via a webserver as www-data or something and user 1000 is a different user. That explains why the socket is not readable permission-wise but also why the environment variable is not defined.

**Comment by v5srinivas** [comment]
Thanku @terrafrost and @bantu for replies

Yes @bantu I am running php via apache webserver. i have [configured](https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/) ssh-agent as mentioned. I don't know why 'SSH_AUTH_SOCK' environment variable was setup. Is there any way or command to set $_SERVER['SSH_AUTH_SOCK'] using ssh-agent

**Comment by terrafrost** [comment]
> Maybe agent should have a constructor taking a socket path.

Done:

https://github.com/phpseclib/phpseclib/commit/fbef6f009fb869f1c78b3d7dfb95ef92eedf586a
