### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by PostCrafter** [phpseclib/phpseclib#1324]
We're currently running into some `Connection closed prematurely` issues, which we would be able to work around by reconnecting if `isConnected()` returns `false`. Unfortunately this doesn't work in the most recent version, but is fixed in ca695f5bdddfc5ef4f6ec68dc2f30bbbd77ea462 (396b9f1a0a233daf20645cc2fde444e652e3bd33 targets the same issue).

Usually we would just update the version directly in our `composer.json`, but since phpseclib is only included as a sub-dependency in our project this doesn't quite work.

Could you please create a new release including those fixes (it's already using `2.0.*`), so we can use the updated version without having to fork this package.

Much appreciated!

**Comment by terrafrost** [comment]
I'll try to do so this weekend.

Thanks!

**Comment by terrafrost** [comment]
I had hoped to do this this weekend but this weekend didn't exactly go according to plan :(

I'll try to do a new release sometime this coming week or next weekend.

I haven't forgotten!

**Comment by terrafrost** [comment]
A new release has been made! 1.0.13 and 2.0.13.

**Comment by PostCrafter** [comment]
Thanks a lot!
