### ISSUE TITLE
SFTP connection to host in same shared server

### ISSUE THREAD

**Issue by guirama** [phpseclib/phpseclib#1325]
Hi,

This particluar issue may not be an issue with phpseclb. But are you aware of such issue and are there any workarounds ?

Assume that I have an app using phpsecblib hosted in server A, connecting to host B1 in server B. In that case it worked fine. A is the development server. Then app is moved to host B0 in server B. So the app in B0 (in server B) tries to SFTP connect to B1 (in server B). In that case the connection is refused and following error is returned. As per the server admins of B, there is no restriction for B0 , in fact IP address in whitelisted . Same code is working with same FTP credentials when attempted from server A to connect to B1

`A PHP Error was encountered

Severity: User Notice

Message: Cannot connect to hostx.####.com:####. Error 111. Connection refused

Filename: Net/SSH2.php

Line Number: 1122

Backtrace:

File: /home/####/public_html/###/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php
Line: 1122
Function: user_error

File: /home/####/public_html/###/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php
Line: 2114
Function: _connect

File: /home/####/public_html/###/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php
Line: 404
Function: call_user_func_array

File: /home/####/public_html/###/application/controllers/Clients.php
Line: 971
Function: login

**Comment by terrafrost** [comment]
Based on the line numbers, it looks like you're using 2.0.11 - not 2.0.12 FWIW.

Anyway, I'd check to see that each host resolves to the same IP address. eg. `gethostbyname`.

Who knows...  maybe even if both hosts are mapped correctly on the DNS maybe there's some /etc/hosts setting that's affecting the mapping locally.
