### ISSUE TITLE
Number of elements can't be negative  - phpseclib/File/ANSI.php275

### ISSUE THREAD

**Issue by vudangnt** [phpseclib/phpseclib#1333]
$ansi = new ANSI();
   
$ssh->enablePTY();
        $ssh->exec('top');
        $ssh->setTimeout(5);
        $ansi->appendString($ssh->read());
        echo $ansi->getScreen();

show error 

ErrorException (E_WARNING)
array_fill(): Number of elements can't be negative
ErrorException 
…/vendor/phpseclib/phpseclib/phpseclib/File/ANSI.php275

![screen shot 2019-01-15 at 10 54 06 pm](https://user-images.githubusercontent.com/31053681/51192146-81da7d00-1918-11e9-99bf-387022b906ba.png)

**Comment by terrafrost** [comment]
If you could pass the output of `$ssh->read()` through `base64_encode` and then do `chunk_split` on it and then give me the result that'd be good.

Thanks!
