### ISSUE TITLE
PHP Fatal error:  Uncaught Use of undefined constant NET_SSH2_DISCONNECT_BY_APPLICATION

### ISSUE THREAD

**Issue by rami-dridi** [phpseclib/phpseclib#1337]
I use PHP 7.0.3  and phpseclib 2.014
I'm receiving this warning:
PHP Fatal error:  Uncaught Use of undefined constant NET_SSH2_DISCONNECT_BY_APPLICATION - assumed 'NET_SSH2_DISCONNECT_BY_APPLICATION'
thrown in phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3214

**Comment by terrafrost** [comment]
I'm not able to reproduce this in phpseclib 2.0.14:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use phpseclib\Net\SSH2;

$ssh = new SSH2('localhost');

echo defined('NET_SSH2_DISCONNECT_BY_APPLICATION') ? 'yes' : 'no';
```

That constant is defined in the SSH2 constructor:

https://github.com/phpseclib/phpseclib/blob/2.0.14/phpseclib/Net/SSH2.php#L994

Shortly after that line `_define_array` is called here:

https://github.com/phpseclib/phpseclib/blob/2.0.14/phpseclib/Net/SSH2.php#L1010

`_define_array` defines undefined values here:

https://github.com/phpseclib/phpseclib/blob/2.0.14/phpseclib/Net/SSH2.php#L4203

Keep in mind, I didn't test on PHP 7.0.3 - I tested on PHP 7.2.8.

Maybe post the code that reproduces this issue?

**Comment by electrolinux** [comment]
How to reproduce in a Laravel 11 application with phpseclib/phpseclib required:
- launch the tinker REPL: php artisan tinker
- open a new SSH2 connection
- quit the REPL with Ctrl+D

````
> ^D

   INFO  Ctrl+D.


   Error 

  Undefined constant "phpseclib3\Net\NET_SSH2_DISCONNECT_BY_APPLICATION"

  at vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3325
    3321▕      *
    3322▕      */
    3323▕     public function disconnect()
    3324▕     {
  ➜ 3325▕         $this->disconnect_helper(NET_SSH2_DISCONNECT_BY_APPLICATION);
    3326▕         if (isset($this->realtime_log_file) && is_resource($this->realtime_log_file)) {
    3327▕             fclose($this->realtime_log_file);
    3328▕         }
    3329▕         unset(self::$connections[$this->getResourceId()]);

      +1 vendor frames 

  2   [internal]:0
      phpseclib3\Net\SSH2::__destruct()

````

**Comment by terrafrost** [comment]
This seems like a Laravel bug to me? I'm able to reproduce the issue with this:

```
composer require terrafrost/namespace:dev-main
php artisan tinker
$a = new Terrafrost\Namespace\Demo;
(Ctrl + D)
```
There's only one PHP script in terrafrost/namespace - vendor/terrafrost/namespace/src/Demo.php:

```php
<?php
namespace Terrafrost\Namespace;

class Demo
{
    public function __construct()
    {
        define('ZZZ', 999);
    }

    public function __destruct()
    {
        echo ZZZ . "\n";
    }
}
```
Now consider doing this in `php artisan tinker`:

```
$a = new Terrafrost\Namespace\Demo;
defined('ZZZ') ? 't' : 'f';
```
This shows that ZZZ is being defined in the root namespace.

`print_r(get_defined_constants(true)['user']);` concurs. But if I then put `print_r(get_defined_constants(true)['user']);` into the `__destruct` method, before the `echo ZZZ . "\n";` then, all of a sudden, `ZZZ` no longer shows up.

I'll open up a bug report against Laravel Framework shortly.

**Comment by terrafrost** [comment]
Here's the bug report:

https://github.com/laravel/framework/issues/51816

**Comment by terrafrost** [comment]
Well Laravel closed the bug. I don't agree with their reasons and I am not going to do the heavy lifting for their issues. TLDR this is NOT a phpseclib problem so I am locking this conversation. No further discussion on this matter will be entertained. If you want to jump through Laravel's hoops feel free - I won't.
