### ISSUE TITLE
Connect to a SFTP server with a proxy settings 

### ISSUE THREAD

**Issue by AndreAntG** [phpseclib/phpseclib#1339]
Im trying to connect to a SFTP server via a proxy.
I have the following code but i need to pass the username and password of the proxy.
What i am missing?

      $proxyHost = '******';                             
      $proxyPort = '*****';

    $fsock = fsockopen($proxyHost, $proxyPort); 
    $address = '*****'; 
    $port = '*****';
    $request = "CONNECT $address:$port HTTP/1.0\r\nContent-Length: 0\r\n\r\n"; 

    if(fputs($fsock, $request) != strlen($request)) {
        exit("premature termination"); 
    }
    $response = fgets($fsock); 

    $sftp   = new SFTP($fsock);
     if (!$sftp->login('******', '******')) {
            exit('Bad credentials!' . $lb);
        }

**Comment by bantu** [comment]
Why the Content-Length header?
Missing something like Proxy-Authorization: Basic encoded-credentials ?
Via https://en.wikipedia.org/wiki/HTTP_tunnel

Maybe there is a library implementation that will construct you a
proxied socket you can put into phpseclib's SFTP class. Then you do
not have to construct it youself.

**Comment by AndreAntG** [comment]
I have take this part of code from this comment :
https://github.com/phpseclib/phpseclib/issues/1117#issuecomment-295662545

So i need to include this Proxy-Authorization in the header following the username and password?

@bantu

**Comment by bantu** [comment]
You need to determine how the proxy expects credentials to be passed and
then you have to submit the username/password using a mechanism that is
supported by the proxy.

**Comment by AndreAntG** [comment]
The proxy expects the host , port , user and password to connect. 
Can you help me? I still cant understand if my code is correct or no.

@bantu

**Comment by AndreAntG** [comment]
@terrafrost  Hi , can you help me with this topic?

**Comment by terrafrost** [comment]
@AndreAntG - maybe over the weekend. This isn't as simple as me just looking at log files. I have to setup an HTTP CONNECT proxy, look at the protocol to determine how to then actually connect to it, write the code that does that, potentially debug it, etc.

Understand that you're request is one of the more time consuming ones on my plate and that my free time is finite. I'm going to try to get to it but I'm not going to try to squeeze it into an already jam packed weekday schedule, especially when I'm not being paid to do so.

**Comment by terrafrost** [comment]
I got it working for me...

```php
<?php
include('Net/SSH2.php');

$fsock = fsockopen('127.0.0.1', 80, $errno, $errstr, 1);
if (!$fsock) {
    echo $errstr; exit;
}
fputs($fsock, "CONNECT website.com:22 HTTP/1.0\r\n\r\n");
while ($line = fgets($fsock, 1024)) {
    if ($line == "\r\n") {
        break;
    }
    //echo $line;
}

$ssh = new Net_SSH2($fsock);
$ssh->login('user', 'pass');
echo $ssh->exec('ls -latr');
```

Of course, that's without authenticating into the proxy itself. I'll try that out as time permits.

**Comment by terrafrost** [comment]
With authorization:

```php
<?php
include('Net/SSH2.php');

$fsock = fsockopen('127.0.0.1', 80, $errno, $errstr, 1);
if (!$fsock) {
    echo $errstr; exit;
}
fputs($fsock, "CONNECT website.com:22 HTTP/1.0\r\n");
fputs($fsock, "Proxy-Authorization: Basic " . base64_encode('user:pass') . "\r\n");
fputs($fsock, "\r\n");
while ($line = fgets($fsock, 1024)) {
    if ($line == "\r\n") {
        break;
    }
    //echo $line;
}

$ssh = new Net_SSH2($fsock);
$ssh->login('user', 'pass');
echo $ssh->exec('ls -latr');
```

If that doesn't work then run the script and tell me what the headers you get back are. Digest authentication is more of a PITA then Basic.

**Comment by AndreAntG** [comment]
Hi @terrafrost  thanks for the reply.
To connect to the server in question i need to generate a SSH-2 RSA Key with PuTTY.
I know can connect via WinSCP to the server in question but i specified the file key in question.

Do i need to pass the key in the password field on the login or need to do in other way?

**Comment by terrafrost** [comment]
From http://phpseclib.sourceforge.net/ssh/auth.html#rsakey:

```php
<?php
include('Net/SSH2.php');
include('Crypt/RSA.php');

$ssh = new Net_SSH2('www.domain.tld');
$key = new Crypt_RSA();
$key->loadKey(file_get_contents('privatekey'));
if (!$ssh->login('username', $key)) {
    exit('Login Failed');
}

echo $ssh->exec('pwd');
echo $ssh->exec('ls -la');
?>
```

**Comment by AndreAntG** [comment]
Thanks for the reply.
You really help me alot!!!!
I will test and give you a feedback
@terrafrost

**Comment by AndreAntG** [comment]
@terrafrost  I have tested this and work very good.
Thanks for the support!!!

**Comment by fedeisas** [comment]
@AndreAntG I'm facing the same issues. I need to connect to an SFTP server running on a non-standard port using key authentication. They have whitelisted one of my Elastic IPs. Which software are you running for the actual proxying? I'm at lost with the difference between SOCKS and HTTP proxies. Thanks a lot!

PS: sorry for posting on a closed issue :-(

**Comment by terrafrost** [comment]
I used mod_proxy and mod_proxy_connect for Apache. I updated one of the *.conf files in sites-available and added `ProxyRequests On` and `AllowCONNECT 80`.

For authentication I did this:

```
<Proxy *>
  AuthType Basic
  AuthName "Wrapper auth"
  AuthBasicProvider file
  AuthUserFile "/path/to/.htpasswd"
  Require valid-user
</Proxy>
```
