### ISSUE TITLE
sftp/ssh2 errors

### ISSUE THREAD

**Issue by epoplive** [phpseclib/phpseclib#134]
There seems to be some type of bug maintaining connections (I'm using the SFTP portion, but the errors are coming from the SSH2 class) downloading multiple files via SFTP class.  After grabbing a fresh copy of phpseclib I'm seeing these errors after a couple files download successfully:

PHP Notice:  fputs(): send of 36 bytes failed with errno=32 Broken pipe in /redacted/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2847

Notice: fputs(): send of 36 bytes failed with errno=32 Broken pipe in /redacted/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2847
updating file log...
Error downloading file!
PHP Notice:  Connection closed prematurely in /redacted/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2815

Notice: Connection closed prematurely in /redacted/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2815

Here's the version info on what I'm using:
commit bf6da217c19514506060d98797a53dc1a78c807e
Merge: 8c9e7a8 78f9fad
Author: terrafrost terrafrost@php.net
Date:   Mon Jul 22 23:53:45 2013 -0500

```
Merge branch 'master' of https://github.com/phpseclib/phpseclib
```

I replaced this version of phpseclib with a previous one, and everything is back to functioning as expected.  Here's the info on that version in case it helps:
commit b2262f731dbd2aee68bcbe95593d374b8aee76a5
Merge: 33e415c af3f275
Author: terrafrost terrafrost@php.net
Date:   Tue May 14 11:02:45 2013 -0500

```
Merge branch 'master' of https://github.com/phpseclib/phpseclib
```

**Comment by joelharkes** [comment]
Is this currently an issue? we are receiving the same errors? how is this best solved?

**Comment by joelharkes** [comment]
still getting a lot of the following errors. this means the connection has been reset?

```
RuntimeException: Only  of 176 bytes were sent
#0 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4291): phpseclib3\Net\SSH2->send_binary_packet()
#1 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3252): phpseclib3\Net\SSH2->send_channel_packet()
#2 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2370): phpseclib3\Net\SFTP->send_sftp_packet()
#3 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(167): phpseclib3\Net\SFTP->get()
#4 /var/www/html/vendor/league/flysystem/src/Filesystem.php(74): League\Flysystem\PhpseclibV3\SftpAdapter->read()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(258): League\Flysystem\Filesystem->read()
...
```

**Comment by terrafrost** [comment]
Can you post the SSH logs that you get right up until that error? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and then `echo $e->getLog()` in the catch block for the exception.
