### ISSUE TITLE
Slow when connecting

### ISSUE THREAD

**Issue by samfrjn11** [phpseclib/phpseclib#1342]
I have the following piece of code:

```
        $start_exec_time = microtime(true);
        $this->ssh = new Net_SSH2($ip);
        $login = $this->ssh->login($username, $password);

        $exec_time = (microtime(true) - $start_exec_time);
```

The result of $exec_time is a little over 12 seconds. This happens each time. Any reason why I'm having this behaviour?

Executing commands with `$ssh->exec('command')` or `$ssh->write('command\n')` works just fine, it's just the init process that's taking very long.

**Comment by bantu** [comment]
Install the GMP extension to speedup expensive crypto operations at SSH
startup.

**Comment by terrafrost** [comment]
In all likelihood bantu's assessment is correct.

None-the-less, it'd be interesting to see your SSH logs. You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top and then `echo $this->ssh->getLog();` after you login.

Seeing your `phpinfo()` could provide additional insight.

**Comment by samfrjn11** [comment]
Hi,

Result from getLog();

`
<-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  37:2e:35:0d:0a                                   7.5..

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:31:2e:30:0d:0a                             b_1.0..

-> NET_SSH2_MSG_KEXINIT (since last: 0.0299, network: 0.0001s)
00000000  34:83:3d:45:49:4f:ca:a3:1d:ca:ab:a7:a0:85:f3:44  4.=EIO.........D
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:29:72:73:61:2d:73:68:61:32:2d:32  56...)rsa-sha2-2
000000a0  35:36:2c:72:73:61:2d:73:68:61:32:2d:35:31:32:2c  56,rsa-sha2-512,
000000b0  73:73:68:2d:72:73:61:2c:73:73:68:2d:64:73:73:00  ssh-rsa,ssh-dss.
000000c0  00:00:e9:61:72:63:66:6f:75:72:32:35:36:2c:61:72  ...arcfour256,ar
000000d0  63:66:6f:75:72:31:32:38:2c:61:65:73:31:32:38:2d  cfour128,aes128-
000000e0  63:74:72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61  ctr,aes192-ctr,a
000000f0  65:73:32:35:36:2d:63:74:72:2c:74:77:6f:66:69:73  es256-ctr,twofis
00000100  68:31:32:38:2d:63:74:72:2c:74:77:6f:66:69:73:68  h128-ctr,twofish
00000110  31:39:32:2d:63:74:72:2c:74:77:6f:66:69:73:68:32  192-ctr,twofish2
00000120  35:36:2d:63:74:72:2c:61:65:73:31:32:38:2d:63:62  56-ctr,aes128-cb
00000130  63:2c:61:65:73:31:39:32:2d:63:62:63:2c:61:65:73  c,aes192-cbc,aes
00000140  32:35:36:2d:63:62:63:2c:74:77:6f:66:69:73:68:31  256-cbc,twofish1
00000150  32:38:2d:63:62:63:2c:74:77:6f:66:69:73:68:31:39  28-cbc,twofish19
00000160  32:2d:63:62:63:2c:74:77:6f:66:69:73:68:32:35:36  2-cbc,twofish256
00000170  2d:63:62:63:2c:74:77:6f:66:69:73:68:2d:63:62:63  -cbc,twofish-cbc
00000180  2c:62:6c:6f:77:66:69:73:68:2d:63:74:72:2c:62:6c  ,blowfish-ctr,bl
00000190  6f:77:66:69:73:68:2d:63:62:63:2c:33:64:65:73:2d  owfish-cbc,3des-
000001a0  63:74:72:2c:33:64:65:73:2d:63:62:63:00:00:00:e9  ctr,3des-cbc....
000001b0  61:72:63:66:6f:75:72:32:35:36:2c:61:72:63:66:6f  arcfour256,arcfo
000001c0  75:72:31:32:38:2c:61:65:73:31:32:38:2d:63:74:72  ur128,aes128-ctr
000001d0  2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73:32  ,aes192-ctr,aes2
000001e0  35:36:2d:63:74:72:2c:74:77:6f:66:69:73:68:31:32  56-ctr,twofish12
000001f0  38:2d:63:74:72:2c:74:77:6f:66:69:73:68:31:39:32  8-ctr,twofish192
00000200  2d:63:74:72:2c:74:77:6f:66:69:73:68:32:35:36:2d  -ctr,twofish256-
00000210  63:74:72:2c:61:65:73:31:32:38:2d:63:62:63:2c:61  ctr,aes128-cbc,a
00000220  65:73:31:39:32:2d:63:62:63:2c:61:65:73:32:35:36  es192-cbc,aes256
00000230  2d:63:62:63:2c:74:77:6f:66:69:73:68:31:32:38:2d  -cbc,twofish128-
00000240  63:62:63:2c:74:77:6f:66:69:73:68:31:39:32:2d:63  cbc,twofish192-c
00000250  62:63:2c:74:77:6f:66:69:73:68:32:35:36:2d:63:62  bc,twofish256-cb
00000260  63:2c:74:77:6f:66:69:73:68:2d:63:62:63:2c:62:6c  c,twofish-cbc,bl
00000270  6f:77:66:69:73:68:2d:63:74:72:2c:62:6c:6f:77:66  owfish-ctr,blowf
00000280  69:73:68:2d:63:62:63:2c:33:64:65:73:2d:63:74:72  ish-cbc,3des-ctr
00000290  2c:33:64:65:73:2d:63:62:63:00:00:00:39:68:6d:61  ,3des-cbc...9hma
000002a0  63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63:2d  c-sha2-256,hmac-
000002b0  73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68:61  sha1-96,hmac-sha
000002c0  31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68:6d  1,hmac-md5-96,hm
000002d0  61:63:2d:6d:64:35:00:00:00:39:68:6d:61:63:2d:73  ac-md5...9hmac-s
000002e0  68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61  ha2-256,hmac-sha
000002f0  31:2d:39:36:2c:68:6d:61:63:2d:73:68:61:31:2c:68  1-96,hmac-sha1,h
00000300  6d:61:63:2d:6d:64:35:2d:39:36:2c:68:6d:61:63:2d  mac-md5-96,hmac-
00000310  6d:64:35:00:00:00:04:6e:6f:6e:65:00:00:00:04:6e  md5....none....n
00000320  6f:6e:65:00:00:00:00:00:00:00:00:00:00:00:00:00  one.............

<- NET_SSH2_MSG_KEXINIT (since last: 0.0003, network: 0.0001s)
00000000  40:7d:86:ad:83:62:31:69:13:21:70:c2:34:66:21:f8  @}...b1i.!p.4f!.
00000010  00:00:01:02:63:75:72:76:65:32:35:35:31:39:2d:73  ....curve25519-s
00000020  68:61:32:35:36:2c:63:75:72:76:65:32:35:35:31:39  ha256,curve25519
00000030  2d:73:68:61:32:35:36:40:6c:69:62:73:73:68:2e:6f  -sha256@libssh.o
00000040  72:67:2c:65:63:64:68:2d:73:68:61:32:2d:6e:69:73  rg,ecdh-sha2-nis
00000050  74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32:2d  tp256,ecdh-sha2-
00000060  6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73:68  nistp384,ecdh-sh
00000070  61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66:66  a2-nistp521,diff
00000080  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000090  2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35:36  -exchange-sha256
000000a0  2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d  ,diffie-hellman-
000000b0  67:72:6f:75:70:31:36:2d:73:68:61:35:31:32:2c:64  group16-sha512,d
000000c0  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
000000d0  6f:75:70:31:38:2d:73:68:61:35:31:32:2c:64:69:66  oup18-sha512,dif
000000e0  66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75  fie-hellman-grou
000000f0  70:31:34:2d:73:68:61:32:35:36:2c:64:69:66:66:69  p14-sha256,diffi
00000100  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31  e-hellman-group1
00000110  34:2d:73:68:61:31:00:00:00:41:73:73:68:2d:72:73  4-sha1...Assh-rs
00000120  61:2c:72:73:61:2d:73:68:61:32:2d:35:31:32:2c:72  a,rsa-sha2-512,r
00000130  73:61:2d:73:68:61:32:2d:32:35:36:2c:65:63:64:73  sa-sha2-256,ecds
00000140  61:2d:73:68:61:32:2d:6e:69:73:74:70:32:35:36:2c  a-sha2-nistp256,
00000150  73:73:68:2d:65:64:32:35:35:31:39:00:00:00:6c:63  ssh-ed25519...lc
00000160  68:61:63:68:61:32:30:2d:70:6f:6c:79:31:33:30:35  hacha20-poly1305
00000170  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73  @openssh.com,aes
00000180  31:32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63  128-ctr,aes192-c
00000190  74:72:2c:61:65:73:32:35:36:2d:63:74:72:2c:61:65  tr,aes256-ctr,ae
000001a0  73:31:32:38:2d:67:63:6d:40:6f:70:65:6e:73:73:68  s128-gcm@openssh
000001b0  2e:63:6f:6d:2c:61:65:73:32:35:36:2d:67:63:6d:40  .com,aes256-gcm@
000001c0  6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:6c:63  openssh.com...lc
000001d0  68:61:63:68:61:32:30:2d:70:6f:6c:79:31:33:30:35  hacha20-poly1305
000001e0  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73  @openssh.com,aes
000001f0  31:32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63  128-ctr,aes192-c
00000200  74:72:2c:61:65:73:32:35:36:2d:63:74:72:2c:61:65  tr,aes256-ctr,ae
00000210  73:31:32:38:2d:67:63:6d:40:6f:70:65:6e:73:73:68  s128-gcm@openssh
00000220  2e:63:6f:6d:2c:61:65:73:32:35:36:2d:67:63:6d:40  .com,aes256-gcm@
00000230  6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:d5:75  openssh.com....u
00000240  6d:61:63:2d:36:34:2d:65:74:6d:40:6f:70:65:6e:73  mac-64-etm@opens
00000250  73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:2d  sh.com,umac-128-
00000260  65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  etm@openssh.com,
00000270  68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2d:65:74  hmac-sha2-256-et
00000280  6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d  m@openssh.com,hm
00000290  61:63:2d:73:68:61:32:2d:35:31:32:2d:65:74:6d:40  ac-sha2-512-etm@
000002a0  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63  openssh.com,hmac
000002b0  2d:73:68:61:31:2d:65:74:6d:40:6f:70:65:6e:73:73  -sha1-etm@openss
000002c0  68:2e:63:6f:6d:2c:75:6d:61:63:2d:36:34:40:6f:70  h.com,umac-64@op
000002d0  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31  enssh.com,umac-1
000002e0  32:38:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68  28@openssh.com,h
000002f0  6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61  mac-sha2-256,hma
00000300  63:2d:73:68:61:32:2d:35:31:32:2c:68:6d:61:63:2d  c-sha2-512,hmac-
00000310  73:68:61:31:00:00:00:d5:75:6d:61:63:2d:36:34:2d  sha1....umac-64-
00000320  65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  etm@openssh.com,
00000330  75:6d:61:63:2d:31:32:38:2d:65:74:6d:40:6f:70:65  umac-128-etm@ope
00000340  6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68  nssh.com,hmac-sh
00000350  61:32:2d:32:35:36:2d:65:74:6d:40:6f:70:65:6e:73  a2-256-etm@opens
00000360  73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32  sh.com,hmac-sha2
00000370  2d:35:31:32:2d:65:74:6d:40:6f:70:65:6e:73:73:68  -512-etm@openssh
00000380  2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:31:2d:65  .com,hmac-sha1-e
00000390  74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:75  tm@openssh.com,u
000003a0  6d:61:63:2d:36:34:40:6f:70:65:6e:73:73:68:2e:63  mac-64@openssh.c
000003b0  6f:6d:2c:75:6d:61:63:2d:31:32:38:40:6f:70:65:6e  om,umac-128@open
000003c0  73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61  ssh.com,hmac-sha
000003d0  32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61:32:2d  2-256,hmac-sha2-
000003e0  35:31:32:2c:68:6d:61:63:2d:73:68:61:31:00:00:00  512,hmac-sha1...
000003f0  15:6e:6f:6e:65:2c:7a:6c:69:62:40:6f:70:65:6e:73  .none,zlib@opens
00000400  73:68:2e:63:6f:6d:00:00:00:15:6e:6f:6e:65:2c:7a  sh.com....none,z
00000410  6c:69:62:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00  lib@openssh.com.
00000420  00:00:00:00:00:00:00:00:00:00:00:00              ............

-> NET_SSH2_MSG_KEXDH_INIT (since last: 5.3832, network: 0.0001s)
00000000  00:00:01:00:59:f9:1f:ee:6b:b5:25:26:b2:85:4d:ff  ....Y...k.%&..M.
00000010  a0:1e:84:52:0f:81:35:7c:86:d5:13:5b:93:9c:43:56  ...R..5|...[..CV
00000020  cc:0b:fe:05:14:24:ed:91:b8:07:5c:46:cf:c2:85:b5  .....$....\F....
00000030  6c:e8:e4:f3:ce:ff:14:5c:37:8e:48:dc:1b:0e:e5:71  l......\7.H....q
00000040  de:10:9d:4b:fb:28:90:1b:e2:40:9d:4d:d8:44:be:20  ...K.(...@.M.D. 
00000050  ad:0f:83:37:0a:33:bd:37:6d:9b:6b:f6:81:08:b3:dd  ...7.3.7m.k.....
00000060  c2:f6:9c:d6:68:b3:a7:35:58:80:44:74:e7:34:91:4e  ....h..5X.Dt.4.N
00000070  2e:61:0c:82:d0:d3:15:93:b8:aa:a0:31:b6:dc:bb:97  .a.........1....
00000080  b5:43:4e:50:e9:f5:9e:5e:f6:83:e4:9c:f2:d4:07:3a  .CNP...^.......:
00000090  ef:64:76:a8:b2:bb:c0:ad:f4:f2:14:69:29:97:88:18  .dv........i)...
000000a0  45:30:dc:05:2c:29:c6:37:98:e3:fc:43:67:fb:71:45  E0..,).7...Cg.qE
000000b0  4e:ac:74:e8:51:89:97:2b:20:ed:00:db:5d:62:73:a1  N.t.Q..+ ...]bs.
000000c0  c8:0c:c7:45:5c:47:46:30:20:ff:c9:af:58:3a:52:f0  ...E\GF0 ...X:R.
000000d0  2a:1b:8c:1b:5b:e0:28:89:fe:5d:e3:c1:bc:80:53:35  *...[.(..]....S5
000000e0  7f:75:e0:53:47:fa:64:26:07:4d:c5:4c:76:4e:2a:b8  .u.SG.d&.M.LvN*.
000000f0  30:11:9b:b1:03:c9:ba:da:fc:ec:3f:62:88:c2:e2:59  0.........?b...Y
00000100  b1:c8:13:b8                                      ....

<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.016, network: 0.0159s)
00000000  00:00:01:17:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000010  00:00:03:01:00:01:00:00:01:01:00:a3:3f:74:79:f1  ............?ty.
00000020  07:3e:8c:7c:fd:e7:e9:98:ba:8f:88:7a:16:36:3a:a8  .>.|.......z.6:.
00000030  77:42:d3:cc:f2:f4:e6:ac:6c:65:6e:bf:3d:35:13:9e  wB......len.=5..
00000040  cd:27:2f:48:3e:75:87:10:4f:59:ea:43:f0:bf:ef:b8  .'/H>u..OY.C....
00000050  06:07:8f:66:cf:14:a8:e1:d2:4c:97:e2:92:32:d2:88  ...f.....L...2..
00000060  fe:5f:67:63:0a:e1:d6:4f:09:b1:d6:3d:9b:62:7e:6e  ._gc...O...=.b~n
00000070  63:7a:00:ea:ee:a8:54:6b:51:69:fb:f2:ba:da:3f:5a  cz....TkQi....?Z
00000080  e7:6e:71:be:c6:1e:d5:36:0c:66:f7:8c:ec:a2:ee:8f  .nq....6.f......
00000090  16:ee:ac:5c:1b:f0:4f:ca:82:6f:bf:85:20:cf:82:cf  ...\..O..o.. ...
000000a0  35:4b:1d:21:b3:4f:16:9d:18:51:34:4a:3a:e1:98:95  5K.!.O...Q4J:...
000000b0  ab:a3:e3:88:c2:b6:b3:d3:6c:03:11:a8:50:3b:25:99  ........l...P;%.
000000c0  42:d5:8d:33:fe:6a:b7:75:cc:94:be:c1:1e:6b:b8:46  B..3.j.u.....k.F
000000d0  9d:ed:eb:40:a7:4e:88:04:9f:57:ba:f5:17:99:29:98  ...@.N...W....).
000000e0  28:51:05:7c:e1:6f:81:7c:6f:1f:f1:da:24:b0:78:53  (Q.|.o.|o...$.xS
000000f0  f2:48:b6:67:f1:1f:6f:64:2a:3d:c4:44:4e:ee:f0:4d  .H.g..od*=.DN..M
00000100  60:44:c8:8f:a6:c3:41:55:53:3e:e3:e3:38:3a:21:29  `D....AUS>..8:!)
00000110  b8:e7:52:97:ad:82:fa:29:8c:57:2f:00:00:01:01:00  ..R....).W/.....
00000120  da:35:a0:4b:13:ed:65:c2:39:e1:f3:df:95:d2:83:bf  .5.K..e.9.......
00000130  61:c1:a1:5b:03:6d:12:65:10:b3:5e:a7:95:1f:37:6b  a..[.m.e..^...7k
00000140  73:f7:67:cf:15:9e:f4:cf:a6:6f:15:c8:52:fc:40:a8  s.g......o..R.@.
00000150  18:6b:4c:32:16:b7:9c:ab:fd:07:aa:10:59:f9:16:fd  .kL2........Y...
00000160  5b:57:c3:ba:a8:3f:99:ff:39:a3:41:8d:3d:dc:20:46  [W...?..9.A.=. F
00000170  fd:0b:76:8e:52:2d:e9:ea:b0:bf:f4:d9:a9:29:a3:02  ..v.R-.......)..
00000180  56:16:c7:20:b7:8d:b5:92:7c:2c:92:1b:88:11:ba:43  V.. ....|,.....C
00000190  5f:3c:59:06:88:8b:a1:54:fc:43:36:82:f0:58:d4:d2  _.Y....T.C6..X..
000001a0  e7:26:3c:41:7e:53:13:5a:1f:01:3b:f1:1d:5e:32:fe  .&.A~S.Z..;..^2.
000001b0  2a:47:26:e2:d7:57:f3:1e:00:35:ca:da:17:f2:e6:9f  *G&..W...5......
000001c0  0f:24:2c:99:29:77:e1:89:a7:3f:82:6c:2d:e7:e7:6f  .$,.)w...?.l-..o
000001d0  06:24:eb:99:53:ce:34:cd:5e:fb:95:72:a4:4c:7b:40  .$..S.4.^..r.L{@
000001e0  47:28:d1:68:87:84:91:37:37:e7:d6:65:cd:3a:b2:b0  G(.h...77..e.:..
000001f0  fa:67:68:72:e5:58:59:d5:27:c7:1a:73:63:6e:17:4d  .ghr.XY.'..scn.M
00000200  8c:bd:3e:44:22:95:5b:21:06:1b:3b:65:cc:4f:39:de  ..>D".[!..;e.O9.
00000210  a4:6f:54:6a:07:df:16:3f:b8:be:d4:8c:2e:f4:50:a6  .oTj...?......P.
00000220  00:00:01:14:00:00:00:0c:72:73:61:2d:73:68:61:32  ........rsa-sha2
00000230  2d:32:35:36:00:00:01:00:9e:9e:1b:70:65:c7:86:8a  -256.......pe...
00000240  94:3b:0b:23:35:10:b2:c8:69:17:76:2a:81:02:01:1d  .;.#5...i.v*....
00000250  1a:b6:91:8f:e5:f7:00:26:72:a8:a2:27:d6:ac:35:d1  .......&r..'..5.
00000260  2f:e0:d2:96:61:19:85:cb:04:3b:67:1d:df:2a:d5:3e  /...a....;g..*.>
00000270  af:26:15:de:76:ad:c1:da:60:53:9e:d9:e0:ed:1b:40  .&..v...`S.....@
00000280  79:f1:31:03:b5:47:6d:28:e1:d0:37:e6:69:47:5d:04  y.1..Gm(..7.iG].
00000290  06:d1:bb:2f:20:18:f0:61:7f:2b:cc:88:a2:8a:fe:1a  .../ ..a.+......
000002a0  58:82:2b:af:ce:9a:9e:a9:7f:fc:63:db:92:7d:b5:d9  X.+.......c..}..
000002b0  66:ee:c9:8e:eb:e6:f1:6a:84:da:70:78:8e:e4:a9:07  f......j..px....
000002c0  e7:a9:42:38:ff:35:02:d7:ef:17:77:74:48:fd:2a:e1  ..B8.5....wtH.*.
000002d0  e8:aa:2f:fb:2f:5c:d0:b4:b6:6a:4a:c0:41:6f:14:ab  .././\...jJ.Ao..
000002e0  af:90:17:7b:55:7c:c8:95:5e:45:55:b2:f7:ff:fc:98  ...{U|..^EU.....
000002f0  0f:fd:31:47:0b:2d:fa:2f:e6:ec:9b:e4:c0:26:78:3f  ..1G.-./.....&x?
00000300  5c:87:29:a7:f2:f8:9f:df:44:3f:f7:dc:7e:be:ce:f7  \.).....D?..~...
00000310  fd:ff:bd:a8:d0:e7:5e:aa:d5:32:81:6a:b2:68:1b:92  ......^..2.j.h..
00000320  cc:8c:a6:d8:9b:4c:bd:c8:f0:0f:1a:24:56:77:06:74  .....L.....$Vw.t
00000330  c2:68:6a:95:eb:ba:0b:34                          .hj....4

-> NET_SSH2_MSG_NEWKEYS (since last: 6.9954, network: 0.0001s)
                                                 

<- NET_SSH2_MSG_NEWKEYS (since last: 0.0001, network: 0.0001s)
                                                 

-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.1081, network: 0.0001s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.0114, network: 0.0111s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0007, network: 0.0001s)
00000000  00:00:00:08:75:73:65:72:6e:61:6d:65:00:00:00:0e  ....username....
00000010  73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f:6e:00:00  ssh-connection..
00000020  00:08:70:61:73:73:77:6f:72:64:00:00:00:00:08:70  ..password.....p
00000030  61:73:73:77:6f:72:64                             assword

<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.0073, network: 0.0071s)
`

php info in attachment.

Thanks!
[phpinfo().pdf](https://github.com/phpseclib/phpseclib/files/2836403/phpinfo.pdf)

**Comment by samfrjn11** [comment]
I installed the GMP extension as suggested by @bantu 
My speed improved from 12.43s ish to 0.127 seconds. That's amazing!
