### ISSUE TITLE
How do I copy folder server to server with phpseclib?

### ISSUE THREAD

**Issue by ivink3aray** [phpseclib/phpseclib#1351]
i want to create backup data from server to another server using library phpseclib. this is recently script :

```
<?php
include "lib/Crypt/RSA.php";
include "lib/Crypt/Base.php";
include "lib/Crypt/RC4.php";
include "lib/Crypt/AES.php";
include "lib/Net/SFTP.php";
include "lib/Math/BigInteger.php";

set_include_path('lib/'); 

$sftp = new Net_SFTP('172.1.xxx.xx');
if (!$sftp->login('root', 'xxxx')) {
    exit('login failed');
}

$sftp->chdir('/opt/oss/server/var/fileint/fm');
$files = $sftp->nlist('.', true);
foreach ($files as $file) {
    if ($file == '.' || $file == '..') {
        continue;
    }
    $dir = './Alarm/' . dirname($file);
    if (!file_exists($dir)) {
        //mkdir($dir, 0777, true);
    }
    file_put_contents($dir . '/' . $file, $sftp->get($file));
}
```
but still error -> PHP WARNING : file_put_contents ( )

copy all files and folder

server 1

to

server 2

**Comment by terrafrost** [comment]
I think the feedback you're getting on stackoverflow is good:

https://stackoverflow.com/questions/55114045/how-do-i-copy-folder-server-to-server-with-phpseclib

Not much more I can add beyond what neubert did...

**Comment by ivink3aray** [comment]
i has been try it, but still error.

**Comment by bantu** [comment]
Consider using rsync, if it is an option. Cheers

**Comment by ivink3aray** [comment]
@bantu : can you suggest how to implementation using sync

**Comment by bantu** [comment]
@ivink3aray I am afraid you will at least have to try to look into it [rsync] yourself.

**Comment by terrafrost** [comment]
It looks like the OP got the answer he was looking for from SO. Closing.

**Comment by ivink3aray** [comment]
Thanks terrafrost for your support. case closed
