### ISSUE TITLE
ping not working as expected

### ISSUE THREAD

**Issue by chadbarbe** [phpseclib/phpseclib#1353]
Line 3310 of SSH2 is this:

```$result = call_user_func_array(array(&$this, 'parent::login'), $auth);```

But SSH2 doesn't have a parent so this call will not work. This method is only called by ping in an attempt to reestablish the connection but will fail.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/f111bf94b61550fc4685f1c17a5041102aa7410e should fix this.

Thanks!
