### ISSUE TITLE
 [UnexpectedValueException]   Overloading of string functions using mbstring.func_overload is not supported by phpseclib.

### ISSUE THREAD

**Issue by livevasiliy** [phpseclib/phpseclib#1355]
Hello everyone, I have problem with installing package Laravel/Passport. In time install php artisan (cli Laravel Framework) give me error next:

> Package operations: 15 installs, 0 updates, 0 removals
>  - Installing psr/http-message (1.0.1): Loading from cache
>  - Installing psr/http-factory (1.0.0): Loading from cache
>  - Installing zendframework/zend-diactoros (2.1.1): Loading from cache
>  - Installing symfony/psr-http-message-bridge (v1.2.0): Loading from cache
>  - Installing phpseclib/phpseclib (2.0.15): Loading from cache
>  - Installing defuse/php-encryption (v2.2.1): Loading from cache
>  - Installing lcobucci/jwt (3.2.5): Loading from cache
>  - Installing league/event (2.2.0): Loading from cache
>  - Installing league/oauth2-server (7.3.2): Loading from cache
>  - Installing ralouphie/getallheaders (2.0.5): Loading from cache
>  - Installing guzzlehttp/psr7 (1.5.2): Loading from cache
>  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
>  - Installing guzzlehttp/guzzle (6.3.3): Loading from cache
>  - Installing firebase/php-jwt (v5.0.0): Loading from cache
>  - Installing laravel/passport (v7.2.2): Loading from cache
> symfony/psr-http-message-bridge suggests installing nyholm/psr7 (For a super lightweight PSR-7/17 implementation)
>phpseclib/phpseclib suggests installing ext-libsodium (SSH2/SFTP can make use of some algorithms provided by the libsodium-php extension.)
phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
lcobucci/jwt suggests installing mdanter/ecc (Required to use Elliptic Curves based algorithms.)
Writing lock file
>Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
Script Illuminate\Foundation\ComposerScripts::postAutoloadDump handling the post-autoload-dump event terminated with an exception
>  **[UnexpectedValueException]
  Overloading of string functions using mbstring.func_overload is not supported by phpseclib.**

I have next work enthronement:
PHP ver 7.2.11-win32-VC15-x64bit[TS]
Apache 2.4.35-win64-VC15
MySQL 5.7.24-win64

Composer.json
`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/passport": "^7.2",
        "laravel/tinker": "^1.0",
        "menarasolutions/geographer": "^0.3.7",
        "menarasolutions/geographer-laravel": "^0.2.1",
        "menarasolutions/geographer-ru": "^0.2.2",
        "spatie/laravel-permission": "^2.36"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

**Comment by bantu** [comment]
I assume your question is "What do I need to do to make phpseclib work in my environment?". The answer is "Disable string function overloading." See http://php.net/manual/en/mbstring.overload.php

**Comment by livevasiliy** [comment]
> I assume your question is "What do I need to do to make phpseclib work in my environment?". The answer is "Disable string function overloading." See http://php.net/manual/en/mbstring.overload.php

 My config environment
![image](https://user-images.githubusercontent.com/15705591/54808753-97627f00-4c9a-11e9-904a-428be0d06c99.png)

**Comment by bantu** [comment]
What is your mechanism for changing func_overload to 0? I doubt this is the configuration at the time of package installation.

**Comment by livevasiliy** [comment]
> What is your mechanism for changing func_overload to 0? I doubt this is the configuration at the time of package installation.

Via httpd config my local server (Laragon)
`<Directory "C:/laragon/www/backend">
php_admin_value mbstring.func_overload 0
</Directory>`
With value 2 i give next error 
>Deprecated: The mbstring.func_overload directive is deprecated in Unknown on line 0
>Fatal error: Uncaught UnexpectedValueException: Overloading of string functions using >mbstring.func_overload is not supported by phpseclib. in >C:\laragon\www\backend\vendor\phpseclib\phpseclib\phpseclib\bootstrap.php:11 Stack trace: #0 >C:\laragon\www\backend\vendor\composer\autoload_real.php(66): require() #1 >C:\laragon\www\backend\vendor\composer\autoload_real.php(56): >composerRequire8e6a3ad506f1497cfdda158a306517aa('decc78cc4436b12...', 'C:\\laragon\\www\\...') >#2 C:\laragon\www\backend\vendor\autoload.php(7): >ComposerAutoloaderInit8e6a3ad506f1497cfdda158a306517aa::getLoader() #3 >C:\laragon\www\backend\public\index.php(24): require('C:\\laragon\\www\\...') #4 {main} thrown in ?>C:\laragon\www\backend\vendor\phpseclib\phpseclib\phpseclib\bootstrap.php on line 11

**Comment by bantu** [comment]
Guessing: httpd and CLI are NOT using the same configuration.
