### ISSUE TITLE
Need help SSH2 connection with Agent Forwarding

### ISSUE THREAD

**Issue by JorSanders** [phpseclib/phpseclib#1356]
Hello I am very lost trying to setup an SSH2 connection with agent forwarding enabled. I would really love some help. I cannot find any functional example in the documentation, Github history, the Unit Tests or anywhere else online. 
SSH2 with Agent Forwarding seems to be included in this library since this Pull Request. https://github.com/phpseclib/phpseclib/pull/518 . 
I do have the SSH2 connection working. But on the server I am reaching I want to perform a git clone over SSH through Php. For which I need Agent Forwarding enabled. Since the server doesn't have the credentials itself to git clone. 

This is my current code block.

```
	$socket = '/tmp/ssh-0xbLAWSpdb5v/agent.3067';
	$agent  = new Agent($socket);
	$ssh    = new SSH2($sshHost);
	$agent->startSSHForwarding($ssh);
	$ssh->agent = $agent;
	$key        = new RSA;
	$key->loadKey($privateKey);
	if (!$ssh->login($sshUsername, $key))
	{
		return false;
	}
	$clone = $ssh->exec('git clone ' . $gitUrl . $projectRoot);
```
Some important things to note:
- $socket is based of running `echo $SSH_AUTH_SOCK` in my terminal on a Ubuntu host.
- in the constructor of the Agent(). the line ```$this->fsock = fsockopen('unix://' . $address, 0, $errno, $errstr);``` returns false
- $errno = 2
- $errstr = "No such file or directory"
- if (!$ssh->login($sshUsername, $key)) results in true, indicating Ssh connection is successful
- $clone = "Cloning into 'gitrepo'...
buffer_get_ret: trying to get more bytes 1 than in buffer 0
buffer_get_char_ret: buffer_get_ret failed
buffer_get_char: buffer error
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists."

I have also tried to reverse engineer the Unit test for the Agent. under /tests/Functional/Net/SSH2AgentTest.php. but in the function TestAgentLogin() on the first line ```$ssh = new SSH2($this->getEnv('SSH_HOSTNAME'))``` there already gets an exception thrown which does get caught but the rest of the unit test isn't executed. I realize this could be due to my miss configured environment, but it is also dead end for me. 

Just to clarify through my terminal I do have managed to login to the server via SSH with Agent forwarding enabled. And managed to do a git clone over ssh. So I am sure the SSH key isn't the problem.

Again help would be greatly appreciated.

**Comment by bantu** [comment]
Which user runs your PHP script? Does that user have access to the Agent Socket? fsockopen() returning false might indicate this is not the case.

Note also that you're not logging in using the agent, but using the key directly. You might want to try logging in using the agent as a first step (assuming your setup does not consist of multiple independent keys). This will also set $ssh->agent correctly. See https://github.com/phpseclib/phpseclib/blob/2.0.15/phpseclib/Net/SSH2.php#L2553

**Comment by JorSanders** [comment]
My php user runs as the default 'www-data' which I am assuming doens't have permissions to open the Unix socket. I'm going to attempt allowing php the access the socket. Logging in using the Agent didn't work for me because of the socket not being loaded, but I am going to attempt that after I get the socket loaded in Php. 
Just for the info I am using a single SSH Key.
Much thanks for the fast reply. I will update the issue once i progress

**Comment by bantu** [comment]
Okay. Then you can use `$ssh->login($sshUsername, $agent)` to login and can drop the other three lines and will need to make sure PHP actually has access to the socket. Also see #1321

**Comment by JorSanders** [comment]
Thank you for the support. I have Agent Forwarding working now. I have let Php run with my user id then I could access the agent socket. Thanks for the quick help. For future reference this is the revised code. I realize running Php on my own user id isn't really production ready but that is some server management I will configure later.
```
	$socket = '/tmp/ssh-0xbLAWSpdb5v/agent.3067';
	$agent  = new Agent($socket);
	$ssh    = new SSH2($sshHost);
	$agent->startSSHForwarding($ssh);
	if (!$ssh->login($sshUsername, $agent))
	{
		return false;
	}
	$clone = $ssh->exec('git clone ' . $gitUrl . $projectRoot);
```

**Comment by JorSanders** [comment]
Sort of unrelated is it possible to to forward my Ssh key without using my local Ssh Agent but use the pure Php implementation of the SSH protocol? This would be preferable over the current solution but as for now using my Local Ssh Agent is already amazing

**Comment by bantu** [comment]
> is it possible to to forward my Ssh key without using my local Ssh Agent but use the pure Php implementation of the SSH protocol?

There is no SSH Agent implementation in phpseclib right now. Depending on your setup, it might make sense to generate another key which is owned by www-data and making it such that www-data has its own SSH Agent.

Also, for deploying code, there are other mechanisms that you might want to look into. E.g. deploy tokens.

**Comment by terrafrost** [comment]
> Sort of unrelated is it possible to to forward my Ssh key without using my local Ssh Agent but use the pure Php implementation of the SSH protocol? This would be preferable over the current solution but as for now using my Local Ssh Agent is already amazing

I'm not sure I completely understand what you're asking for. Can you elaborate?

**Comment by JorSanders** [comment]
I would like to forward my SSH Key to the server I am logging in to. Which I have managed using Agent forwarding. But I would like to not have to open an Agent socket for my Php user. Since it is possible to make an SSH connection to my server by just using the pure Php implementation and loading my key in via php. I hoped it would also be possible to make an SSH connection just using php and then forwarding the key my php is using to the server.

The scenario is like this we have a hosting provider we mainly use. But its a shared hosting where we don't have root access to. So it is impossible to expose an SSH-Agent socket to php. We would like to use this server to make ssh connections with key forwarding enabled. 

As for now I have setup our website on a different hosting where i am able to  expose an SSH-Agent socket to php.
