### ISSUE TITLE
Invalid comment for SSH2::READ_NEXT

### ISSUE THREAD

**Issue by jflambert** [phpseclib/phpseclib#1360]
Three READ modes are available for `SSH2::read()`

Unfortunately `READ_NEXT` has invalid documentation. It looks like a copy-paste from `READ_REGEX`

     * Returns when a string matching $expect exactly is found
     */
    const READ_SIMPLE = 1;
    /**
     * Returns when a string matching the regular expression $expect is found
     */
    const READ_REGEX = 2;
    /**
     * Returns when a string matching the regular expression $expect is found
     */
    const READ_NEXT = 3;

It seems to have nothing to do with a regular expression, in fact the `$expect` variable is completely ignored. I would appreciate actual documentation for this mode. Thanks!

        if ($mode == self::READ_NEXT) {
            return $this->get_channel_packet($channel);
        }

**Comment by terrafrost** [comment]
Good catch.

The mode was introduced in #1140 . I'll try to update the comment when I get home from work.

Thanks!

**Comment by terrafrost** [comment]
This is live:

https://github.com/phpseclib/phpseclib/commit/756b2474463c711777d16abeca81fa33047fac91

Thanks!
