### ISSUE TITLE
UUID OIDs and OIDs 2.40+ are not supported

### ISSUE THREAD

**Issue by danielmarschall** [phpseclib/phpseclib#1367]
I have looked at your implementation of Object Identifiers and found out that there are many issues.

(1) The [modulo-40 code](https://github.com/phpseclib/phpseclib/blob/master/phpseclib/File/ASN1.php#L462) is not correct, since it does not support the case of OID 2.40, 2.41, etc. Your modulo-40 code would encode 2.40 as 3.0.

(2) Since no BigInteger code is used, the max size of arcs is limited, and therefore UUID-OIDs (OIDs inside 2.25) are not supported.

You can find a implementation which solves all problems [here](https://misc.daniel-marschall.de/asn.1/oid-converter/php/). Testcases/checks of the DER encoding can be done [here](https://misc.daniel-marschall.de/asn.1/oid-converter/online.php).

**Comment by bantu** [comment]
@danielmarschall Thanks you for your report.

I did not have a change to look into your implementation and whether it could be integrated into phpseclib. In case we would like to, would you be willing to release your code under the MIT license? You are welcome to submit a pull request introducing tests reproducing the issues you're seeing and fixing them.

**Comment by danielmarschall** [comment]
I was actually changing a lot of my source codes from GPLv3 to Apache2. Would that fit better? I guess Apache2 and MIT are compatible with each other, so you could include my library in your project.

**Comment by terrafrost** [comment]
You appear to be correct. [ITU-T X.690, ISO/IEC 8825-1 § 8.19.5](https://www.itu.int/ITU-T/studygroups/com17/languages/X.690-0207.pdf#page=22) gives 2.100.3 as an example and shows the encoding to be 0x813403.

I'll look at your library and test cases and see what I can do, as time permits, to improve how it works in phpseclib. As for including you're library...  phpseclib doesn't have the gmp extension as a dependency and I don't intend to make it one. Also, to facilitate third party use, I'd recommend you make your package install-able via Composer / Packagist.

Anyway, thanks for the report and, like I said, I'll try to work on this as time permits.

Thanks!

**Comment by terrafrost** [comment]
Here's what I've done so far for decoding OIDs:

https://github.com/terrafrost/phpseclib/commit/8784f4bacb116f43b1d4ced75da513652008d0be

**Comment by terrafrost** [comment]
I've finished up the encoding step as well along with the unit test:

https://github.com/terrafrost/phpseclib/commit/e793461543d16a5d52f8805882bf6d45bf8c6cde

The next step is the merge this into the 2.0 and master branches. idk if I'll have a chance to do that this evening but we'll see!

**Comment by terrafrost** [comment]
The fix for this has been merged into all the branches now.

Thanks!
