### ISSUE TITLE
SFTP::login() Should handle error of additional output of shell init

### ISSUE THREAD

**Issue by greatmorro** [phpseclib/phpseclib#1371]
Hello,

I ran into this problem with SFTP:

 1. Put an echo in my .cshrc, e.g
`echo Hello`
 2. Call SFTP::login()
 3. It runs forever

Could you please look into this? A 'false' return could be fine in this case.

As in native sftp, it will error:
`Received message too long xxxx`

Thanks a lot,

**Comment by terrafrost** [comment]
I'm able to reproduce the problem. I'll work on a fix as time permits.

Thanks!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/8df35cc3683bf86c432acf1fd25d056c19cc8a63 should fix this.

Thanks!

**Comment by greatmorro** [comment]
Hello,

It works!

Thanks for your help,
