### ISSUE TITLE
Feature Request | phpseclib sftp->get() Download Progress

### ISSUE THREAD

**Issue by flipmode85** [phpseclib/phpseclib#1375]
Hello!

as mentioned here ->https://stackoverflow.com/questions/45897601/phpseclib-file-upload-with-progress/45930965?noredirect=1#comment99357581_45930965

it would be great to have a callback on $sftp->get() as its implemented on $sftp->put() e.g using to display the download progress. 

Thanks!

**Comment by terrafrost** [comment]
I'll try to take a look this weekend as time permits.

Thanks!

**Comment by flipmode85** [comment]
Thanks, really appreciate it!

**Comment by terrafrost** [comment]
idk what branch you're using so...  do any of these do what you want?:

https://github.com/terrafrost/phpseclib/tree/1.0-callback
https://github.com/terrafrost/phpseclib/tree/2.0-callback
https://github.com/terrafrost/phpseclib/tree/master-callback

An example:

```php
$sftp->get('test.ext', false, 0, -1, function($read) {
    echo "$read\n";
});
```

**Comment by terrafrost** [comment]
Does what I did look like it'll suit your needs? I'm not going to change it once it's merged.

Thanks!

**Comment by flipmode85** [comment]
Hey, 
sorry for my late reply - dealing with some illness!
Thank you so much - it's perfect!

**Comment by terrafrost** [comment]
This is now in phpseclib/phpseclib (as opposed to terrafrost/phpseclib):

https://github.com/phpseclib/phpseclib/commit/f8d8ad24fd19453ef56a778f8a9a67685d42a6d0
