### ISSUE TITLE
Missing Exception Folder

### ISSUE THREAD

**Issue by hpsam** [phpseclib/phpseclib#1386]
Hello,

In source code (2.0.21) the "Exception" folder exist and contains all exception classes.
But in release zip package, the folder is not present.

If you call \phpseclib\Crypt\RSA::setHash() with an invalid hash value, we get a PHP Fatal Error because "UnsupportedAlgorithmException" class does not exist.
Exception is thrown by "\phpseclib\Crypt\Hash::setHash()".

Before class declaration, the use list is good and contains "phpseclib\Exception\UnsupportedAlgorithmException".

**Comment by jim-wigginton-medigap** [comment]
> In source code (2.0.21) the "Exception" folder exist and contains all exception classes.

I'm not seeing an Exception folder here:

https://github.com/phpseclib/phpseclib/tree/2.0/phpseclib

I also did Ctrl + F to see if I could find "Exception" in https://github.com/phpseclib/phpseclib/blob/2.0.21/phpseclib/Crypt/Hash.php and was unable to do so.

The _master_ branch has an Exception folder but not the 2.0 branch. The _latest_ master version doesn't actually have the `setHash` method. You do `RSA::load('...')` and (assuming you don't get an exception) you get back either a RSA\PublicKey instance or an RSA\PrivateKey instance. Both of those are immutable and have a `withHash()` method but not a `setHash()` method.

**Comment by terrafrost** [comment]
> In source code (2.0.21) the "Exception" folder exist and contains all exception classes.

I'm not seeing an Exception folder here:

https://github.com/phpseclib/phpseclib/tree/2.0/phpseclib

I also did Ctrl + F to see if I could find "Exception" in https://github.com/phpseclib/phpseclib/blob/2.0.21/phpseclib/Crypt/Hash.php and was unable to do so.

The _master_ branch has an Exception folder but not the 2.0 branch. The _latest_ master version doesn't actually have the `setHash` method. You do `RSA::load('...')` and (assuming you don't get an exception) you get back either a RSA\PublicKey instance or an RSA\PrivateKey instance. Both of those are immutable and have a `withHash()` method but not a `setHash()` method.

**Comment by hpsam** [comment]
Ok I think that master branch is the source of 2.x., my mystake.
I take maintenance of a project that I don't initiated and the version used throw Exception and don't have the Exception folder. The project say that it's the 2.0.5 version.
With your information I check RSA.php code and compare 2.0.5 release with project code and they are not the same.
I think project is messed up. I'm going to integrate 2.0.21 and adapt all code to it, to be clean.
Thanks
