### ISSUE TITLE
X509.php - unhandled exception for inet_ntop function

### ISSUE THREAD

**Issue by kpawel-29** [phpseclib/phpseclib#1387]
Hello,
Im working on tag 2.0.21 and noticed problem with loading my client certificate. Function _decodeIP in file X509.php throws an exception while parsing this certificate. I suggest to catch this and return false or null then.

What You think?
My solution below: 
```
function _decodeIP($ip)
    {
        try {
            return inet_ntop(base64_decode($ip));
        } catch (\Exception $ex) {
            return false;
        }
    }
```

And certificate that causes problem:
```
MIIGcDCCBVigAwIBAgIQRUgJC4ec7yFWcqzT3mwbWzANBgkqhkiG9w0BAQwFADB1MQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1czEoMCYGA1UEAwwfRUUgQ2VydGlmaWNhdGlvbiBDZW50cmUgUm9vdCBDQTEYMBYGCSqGSIb3DQEJARYJcGtpQHNrLmVlMCAXDTE1MTIxNzEyMzg0M1oYDzIwMzAxMjE3MjM1OTU5WjBjMQswCQYDVQQGEwJFRTEiMCAGA1UECgwZQVMgU2VydGlmaXRzZWVyaW1pc2tlc2t1czEXMBUGA1UEYQwOTlRSRUUtMTA3NDcwMTMxFzAVBgNVBAMMDkVTVEVJRC1TSyAyMDE1MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0oH61NDxbdW9k8nLA1qGaL4B7vydod2Ewp/STBZB3wEtIJCLdkpEsS8pXfFiRqwDVsgGGbu+Q99trlb5LI7yi7rIkRov5NftBdSNPSU5rAhYPQhvZZQgOwRaHa5Ey+BaLJHmLqYQS9hQvQsCYyws+xVvNFUpK0pGD64iycqdMuBl/nWq3fLuZppwBh0VFltm4nhr/1S0R9TRJpqFUGbGr4OK/DwebQ5PjhdS40gCUNwmC7fPQ4vIH+x+TCk2aG+u3MoAz0IrpVWqiwzG/vxreuPPAkgXeFCeYf6fXLsGz4WivsZFbph2pMjELu6sltlBXfAG3fGv43t91VXicyzR/eT5dsB+zFsW1sHV+1ONPr+qzgDxCH2cmuqoZNfIIq+buob3eA8ee+XpJKJQr+1qGrmhggjvAhc7m6cU4x/QfxwRYhIVNhJf+sKVThkQhbJ9XxuKk3c18wymwL1mpDD0PIGJqlssMeiuJ4IzagFbgESGNDUd4icm0hQT8CmQeUm1GbWeBYseqPhMQX97QFBLXJLVy2SCyoAz7Bq1qA43++EcibN+yBc1nQs2Zoq8ck9MK0bCxDMeUkQUz6VeQGp69ImOQrsw46qTz0mtdQrMSbnkXCuLan5dPm284J9HmaqiYi6j6KLcZ2NkUnDQFesBVlMEm+fHa2iR6lnAFYZ06UECAwEAAaOCAgowggIGMB8GA1UdIwQYMBaAFBLyWj7qVhy/zQas8fElyalL1BSZMB0GA1UdDgQWBBSzq4i8mdVipIUqCM20HXI7g3JHUTAOBgNVHQ8BAf8EBAMCAQYwdwYDVR0gBHAwbjAIBgYEAI96AQIwCQYHBACL7EABAjAwBgkrBgEEAc4fAQEwIzAhBggrBgEFBQcCARYVaHR0cHM6Ly93d3cuc2suZWUvQ1BTMAsGCSsGAQQBzh8BAjALBgkrBgEEAc4fAQMwCwYJKwYBBAHOHwEEMBIGA1UdEwEB/wQIMAYBAf8CAQAwQQYDVR0eBDowOKE2MASCAiIiMAqHCAAAAAAAAAAAMCKHIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMCcGA1UdJQQgMB4GCCsGAQUFBwMJBggrBgEFBQcDAgYIKwYBBQUHAwQwfAYIKwYBBQUHAQEEcDBuMCAGCCsGAQUFBzABhhRodHRwOi8vb2NzcC5zay5lZS9DQTBKBggrBgEFBQcwAoY+aHR0cDovL3d3dy5zay5lZS9jZXJ0cy9FRV9DZXJ0aWZpY2F0aW9uX0NlbnRyZV9Sb290X0NBLmRlci5jcnQwPQYDVR0fBDYwNDAyoDCgLoYsaHR0cDovL3d3dy5zay5lZS9yZXBvc2l0b3J5L2NybHMvZWVjY3JjYS5jcmwwDQYJKoZIhvcNAQEMBQADggEBAHRWDGI3P00r2sOnlvLHKk9eE7X93eT+4e5TeaQsOpE5zQRUTtshxN8Bnx2ToQ9rgi18q+MwXm2f0mrGakYYG0bix7ZgDQvCMD/kuRYmwLGdfsTXwh8KuL6uSHF+U/ZTss6qG7mxCHG9YvebkN5Yj/rYRvZ9/uJ9rieByxw4wo7b19p22PXkAkXP5y3+qK/Oet98lqwI97kJhiS2zxFYRk+dXbazmoVHnozYKmsZaSUvoYNNH19tpS7BLdsgi9KpbvQLb5ywIMq9ut3+b2Xvzq8yzmHMFtLIJ6Afu1jJpqD82BUAFcvi5vhnP8M7b974R18WCOpgNQvXDI+2/8ZINeU=
```

**Comment by bantu** [comment]
What's the message of the exception?

**Comment by terrafrost** [comment]
Also, do you know what the specific Exception was? Like was it just a base Exception exception or was it an InvalidArgumentException or some such?

https://php.net/inet-ntop makes no mention of exceptions.

**Comment by gocom** [comment]
Reason could be a error-to-exception handler; `inet_ntop` can generate E_WARNINGs, but it doesn't throw exceptions.

**Comment by kpawel-29** [comment]
This is `ErrorException` with message `inet_ntop(): Invalid in_addr value`

**Comment by terrafrost** [comment]
Can you provide a copy of the X.509 cert that causes this error?

Thanks!

**Comment by terrafrost** [comment]
Never mind - I see that your original post provided it lol. I'll try to take a look later today or tomorrow as time permits.

Thanks!

**Comment by terrafrost** [comment]
So it looks like this is a legit bug.

So an IP address should be either 4 bytes (IPv4) or 16 bytes (IPv6). Your cert has 8 bytes and 32 bytes in the IP address fields, hence the error. BUT...  apparently in the id-ce-nameConstraints extension it's supposed to be the IP address followed by the subnet mask. Quoting [RFC5280](https://tools.ietf.org/html/rfc5280#page-42):

    The syntax of iPAddress MUST be as described in Section 4.2.1.6 with
    the following additions specifically for name constraints.  For IPv4
    addresses, the iPAddress field of GeneralName MUST contain eight (8)
    octets, encoded in the style of RFC 4632 (CIDR) to represent an
    address range [RFC4632].  For IPv6 addresses, the iPAddress field
    MUST contain 32 octets similarly encoded.  For example, a name
    constraint for "class C" subnet 192.0.2.0 is represented as the
    octets C0 00 02 00 FF FF FF 00, representing the CIDR notation
    192.0.2.0/24 (mask 255.255.255.0).

I didn't know this. phpseclib has a unit test for IP Addresses in the subject alt name extension but not for the name constraints one:

https://github.com/phpseclib/phpseclib/blob/2.0.21/tests/Unit/File/X509/X509Test.php#L229

I need to head off to work but I'll try to implement a fix in the next day or two.

Thanks!

**Comment by metaclassing** [comment]
Do you want to extend decodeIP to accept both formats and decide based on length?

```
function decodeIP($base64IP)
{
    $packed = base64_decode($base64IP);
    $length = strlen($packed);

    switch ($length) {
        // For IPv4 without subnet information
        case 4:
        // For IPv6 without subnet information
        case 16:
            $decoded = inet_ntop($packed);
            break;
        // For IPv4 with subnet bitmask information
        case 8:
        // For IPv6 with subnet bitmask information
        case 32:
            $half = $length / 2;
            $p1 = substr($packed, 0, $half);
            $p2 = substr($packed, $half, $half);
            $decoded = inet_ntop($p1) . ' ' . inet_ntop($p2);
            break;
        default:
            throw new \Exception('Trying to decode IP address information with invalid byte length '.$length);
    }

    return $decoded;
}
```
I gave it a quick and dirty test like this:
```
<?php


$tests = [
    'ipv4 1.2.3.4' => chr(1) . chr(2) . chr(3) . chr(4),
    'ipv6 1:2:3:4:5:6:7:8' => chr(0) . chr(1) . chr(0) . chr(2) . chr(0) . chr(3) . chr(0) . chr(4) . chr(0) . chr(5) . chr(0) . chr(6) . chr(0) . chr(7) . chr(0) . chr(8),
    'ipv4 1.2.3.4/24' => chr(1) . chr(2) . chr(3) . chr(4) .
                         chr(255) . chr(255) . chr(255) . chr(0),
    'ipv6 1:2:3:4:5:6:7:8/64' => chr(0) . chr(1) . chr(0) . chr(2) . chr(0) . chr(3) . chr(0) . chr(4) . chr(0) . chr(5) . chr(0) . chr(6) . chr(0) . chr(7) . chr(0) . chr(8) .
                                 chr(255) . chr(255) . chr(255) . chr(255) . chr(255) . chr(255) . chr(255) . chr(255) . chr(0) . chr(0) . chr(0) . chr(0) . chr(0) . chr(0) . chr(0) . chr(0),
];


foreach($tests as $name => $test) {
    echo 'Running test ' . $name . PHP_EOL;
    $decoded = runtest($test);
    echo '    TEST FINISHED: ' . $decoded . PHP_EOL;
}

function runtest($binaryIP)
{
    $b64 = base64_encode($binaryIP);
    return decodeIP($b64);
}
```
This is all probably slightly slower than the rest of the codebase, but its not like most people run decodeIP a thousand times a minute and it is relatively readable by people not super familiar with ipv4/v6 subnetting.

**Comment by terrafrost** [comment]
I've gone with a slightly different fix:

https://github.com/terrafrost/phpseclib/commit/19ad5d27daf5a54b862f01967b284f84bcd237e0

The RFC says that the netmask is "_specifically for name constraints_". In the fix I went with you'd still get the error if it was in the subject alt name extension as opposed to the name constraints extension.

I suppose technically, with my change, you'd still be able to create X.509 certs with an IP address / netmask in the subject alt name - it just wouldn't read them without producing an error.

I have the fix in the 1.0 and 2.0 branches on the terrafrost remote but the master branch is failing and it's not immediately obvious as to why.

I'll pursue this more this evening.

Thanks!

**Comment by metaclassing** [comment]
This might be a somewhat unrelated thing and admittedly I have not tested this extensively, but somewhere in the differences between the version im running and master inet_ntop was changed out in favor of long2ip which i think breaks IPv6 address information. I dont know if there are any specific tests around that but I will have to see if I can manage to craft a certificate to demonstrate what I suspect is happening.

**Comment by terrafrost** [comment]
The fix for this has been committed.

@metalclassing - I tried your cert with the latest 2.0 and got this:

                                           [1] => Array
                                                (
                                                    [base] => Array
                                                        (
                                                            [iPAddress] => Array
                                                                (
                                                                    [0] => 1.2.3.0
                                                                    [1] => 255.255.255.0
                                                                )

                                                        )

                                                    [minimum] => phpseclib\Math\BigInteger Object
                                                        (
                                                            [value] => 0x
                                                            [engine] => gmp
                                                        )

                                                )

                                            [2] => Array
                                                (
                                                    [base] => Array
                                                        (
                                                            [iPAddress] => Array
                                                                (
                                                                    [0] => 1:2:3:4:5:6:7:8
                                                                    [1] => ffff:ffff:ffff:ffff::
                                                                )

                                                        )

                                                    [minimum] => phpseclib\Math\BigInteger Object
                                                        (
                                                            [value] => 0x
                                                            [engine] => gmp
                                                        )

                                                )

                                        )

Seems like it's working to me? If there are further issues lmk and I'll endevour correct them!
