### ISSUE TITLE
ASN1 _decodeTime error

### ISSUE THREAD

**Issue by vladdnepr** [phpseclib/phpseclib#1388]
Hi.

Got error when parsing cert.
[test.php.zip](https://github.com/phpseclib/phpseclib/files/3441141/test.php.zip)

Got lot of errors:
`$ php test.php 
PHP Warning:  strpos() expects parameter 1 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1232
PHP Warning:  strlen() expects parameter 1 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1236
PHP Notice:  Undefined offset: -1 in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1236
PHP Warning:  strpos() expects parameter 1 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1240
PHP Warning:  DateTime::createFromFormat() expects parameter 2 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1246
PHP Warning:  strpos() expects parameter 1 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1232
PHP Warning:  strlen() expects parameter 1 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1236
PHP Notice:  Undefined offset: -1 in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1236
PHP Warning:  strpos() expects parameter 1 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php on line 1240
PHP Warning:  DateTime::createFromFormat() expects parameter 2 to be string, array given in vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php`

When lib try to parse `id-ce-privateKeyUsagePeriod`  _decodeTime function received not a string, function received array.

`array (
  0 => 
  array (
    'start' => 4,
    'headerlength' => 2,
    'type' => 24,
    'content' => 
    DateTime::__set_state(array(
       'date' => '2017-04-21 09:05:50.000000',
       'timezone_type' => 1,
       'timezone' => '+00:00',
    )),
    'length' => 17,
  ),
)`

I think its bug, but cant fix it. Can anybody help?

**Comment by vladdnepr** [comment]
Version 2.0.21

**Comment by terrafrost** [comment]
I'm able to reproduce the issue locally. I'll try to investigate in more depth this evening or tomorrow evening.

Thanks!

**Comment by terrafrost** [comment]
So the issue is with the id-ce-privateKeyUsagePeriod extension. The following script more succinctly reproduces the issue:

```php
<?php
$map = [
        'type'     => FILE_ASN1_TYPE_SEQUENCE,
        'children' => [
            'notBefore' => [
                                             'constant' => 0,
                                             'optional' => true,
                                             'implicit' => true,
                                             'type' => FILE_ASN1_TYPE_GENERALIZED_TIME],
            'notAfter'  => [
                                             'constant' => 1,
                                             'optional' => true,
                                             'implicit' => true,
                                             'type' => FILE_ASN1_TYPE_GENERALIZED_TIME]
        ]
    ];

$asn1 = new File_ASN1();
$a = pack('H*', '3026a011180f32303137303432313039303535305aa111180f32303138303432313230353935395a');
$a = $asn1->decodeBER($a);
$a = $asn1->asn1map($a[0], $map);
```
I'm still working on this but I wanted to post a status update!

**Comment by terrafrost** [comment]
So what I feel like is going on is that my library is expecting the datetime stuff in the id-ce-privateKeyUsagePeriod to be implicitly encoded whereas in this X.509 cert it is explicitly encoded. eg.

asn1parse is giving me this:

```
    0:d=0  hl=2 l=  38 cons: SEQUENCE
    2:d=1  hl=2 l=  17 cons: cont [ 0 ]
    4:d=2  hl=2 l=  15 prim: GENERALIZEDTIME   :20170421090550Z
   21:d=1  hl=2 l=  17 cons: cont [ 1 ]
   23:d=2  hl=2 l=  15 prim: GENERALIZEDTIME   :20180421205959Z
```

When what phpseclib is expecting is this:

```
    0:d=0  hl=2 l=  34 cons: SEQUENCE
    2:d=1  hl=2 l=  15 prim: cont [ 0 ]
   19:d=1  hl=2 l=  15 prim: cont [ 1 ]
```
So if, in the above definition ("map"), `'implicit' => true,` were changed to `'explicit' => true,` that, I think, would fix it. The problem is...  it's not clear to me what it _ought_ to be.

Windows doesn't seem to decode that extension for either format:

[![enter image description here][1]][1]

(the hex string is different but in both cases it's still a non-decoded hex string)

I guess the next step will be to try to decode the X.509 certs (one with implicit encoding, one with explicit encoding) with OpenSSL (vs Windows or phpseclib) and see if OpenSSL errors out on one of them.


  [1]: https://i.stack.imgur.com/G8hd7.png

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/511f55de3d1d504e4686f9d558a3c10709b413f8 should fix this!
