### ISSUE TITLE
PHP 7 Login Timeouts

### ISSUE THREAD

**Issue by riscphree** [phpseclib/phpseclib#1392]
Been googling this one to no avail. 
Running phpseclib on nginx, phpfpm 7.2. Tried both the 1.x release and 2.x release. My code was working great on phpfpm 5 but updated to 7 and now I'm getting timeout issues. 

I've tried setting timeouts in php.ini and using $ssh->setTimeout() and keep getting timeout errors. The code is just simple basic: 

```php
define('NET_SSH2_LOGGING', 3);
		$start = microtime(true);

set_include_path(get_include_path() . PATH_SEPARATOR . APPPATH . 'third_party/phpseclib');
		include(APPPATH . '/third_party/phpseclib/Net/SSH2.php');
		$ssh = new Net_SSH2('1.1.1.1');
		//$ssh->setTimeout(0);

		if (!$ssh->login('root', $password)) {
			$elapsed = microtime(true) - $start;
			exit("unable to login\ntook $elapsed seconds\n");
		}

		$elapsed = microtime(true) - $start;
exit("login successful\ntook $elapsed seconds\n");
```

Any suggestions on where to debug? On the server it's trying to connect to, I do not see any connection attempts. On the machine the code is on, I have allowed outgoing connections thru firewall with ufw.

**Comment by terrafrost** [comment]
Do this and then rerun the script:

```
#
#-----[ OPEN ]------------------------------------------
#
Net/SSH2.php
#
#-----[ FIND ]------------------------------------------
#
            $this->fsock = @fsockopen($this->host, $this->port, $errno, $errstr, $this->curTimeout == 0 ? 100000 : $this->curTimeout);
#
#-----[ REPLACE WITH ]----------------------------------
#
            $this->fsock = fsockopen($this->host, $this->port, $errno, $errstr, $this->curTimeout == 0 ? 100000 : $this->curTimeout);
```
(you're basically removing the [error suppression operator](https://www.php.net/manual/en/language.operators.errorcontrol.php))

Post whatever output you get with that here.

Thanks!

**Comment by riscphree** [comment]
This is what I get (IP redacted):

>  Severity: Warning
> 
> Message: fsockopen(): unable to connect to 1.1.1.1:22 (Connection timed out)
> 
> Filename: Net/SSH2.php
> 
> Line Number: 1171

**Comment by terrafrost** [comment]
Sounds like it's an issue with PHP. If `fsockopen('1.1.1.1', 22)` won't work then phpseclib won't work either.

Maybe it's an issue with selinux?:

https://stackoverflow.com/a/13608942/569976

**Comment by riscphree** [comment]
I'm on ubuntu and don't have selinux installed. 

`sestatus

Command 'sestatus' not found, but can be installed with:

apt install policycoreutils`

**Comment by terrafrost** [comment]
Can you connect to the IP address / port with `fsockopen`?

**Comment by riscphree** [comment]
Apparently not, I get timeouts with the following: 

> $fsock = fsockopen('1.1.1.1', 22, $errno, $errstr); 
> echo $errstr;

**Comment by terrafrost** [comment]
I would post on stackoverflow.com then or superuser.com and ask about why that doesn't work. Or maybe ask your server admin if it's not you. This isn't a phpseclib problem so much as it is a PHP problem (or rather, a PHP configuration problem).

**Comment by riscphree** [comment]
Sounds good, thanks for the help. Been racking my brain on this one and it was working on php5 but after going to php7 it stopped working. *shrug*
