### ISSUE TITLE
->get is inserting special characters into file name

### ISSUE THREAD

**Issue by Alexisgarci** [phpseclib/phpseclib#1393]
Hi guys,

when i download a file from the server, it comes with special characters. Anyone knows how to correct this? 
`if (!$return = $this->get($order, $InboundInno . $order, 'wb'))`....

File name before download - {sdsd}-{4326423}-SALES_BFC_NOTIFICATION -{egdsgs}
File name after download - {sdsd}-{4326423}-SALES_â€‹BFCâ€‹_NOTIFICATION -{egdsgs}
i've tried with and without the 'wb'.

**Comment by bantu** [comment]
What is $this? SFTP? SCP?
Which version of phpseclib?

**Comment by Alexisgarci** [comment]
version 2.0 $this = SFTP

**Comment by terrafrost** [comment]
You posted this on stackoverflow recently:

https://stackoverflow.com/q/57371986/569976

Quoting one of the responses,

> all phpseclib really does is just pass that parameter, without alteration, to `fopen()`: https://github.com/phpseclib/phpseclib/blob/2.0.21/phpseclib/Net/SFTP.php#L2188 Given that this seems more like a PHP issue idk. What happens if you do `$fp = fopen('Modules\*' . $order, 'wb'); fputs($fp, '...'); fclose($fp);`?

You responded with this:

> its the same, it inserts special characters into the file name. 

So, basically, this is an issue with `fopen` - not with phpseclib. I'd repost your question on stackoverflow and ask about why `fopen` isn't working. Don't mention phpseclib because, at this point, phpseclib would just be a distraction. The `fopen` experts aren't liable to be reading questions about phpseclib.

**Comment by bantu** [comment]
The filename is metadata stored on filesystem. As such I'd recommend investigating the local and remote filesystems. Guess: Different filesystems with different encodings.

**Comment by Alexisgarci** [comment]
> You posted this on stackoverflow recently:
> 
> https://stackoverflow.com/q/57371986/569976
> 
> Quoting one of the responses,
> 
> > all phpseclib really does is just pass that parameter, without alteration, to `fopen()`: https://github.com/phpseclib/phpseclib/blob/2.0.21/phpseclib/Net/SFTP.php#L2188 Given that this seems more like a PHP issue idk. What happens if you do `$fp = fopen('Modules\*' . $order, 'wb'); fputs($fp, '...'); fclose($fp);`?
> 
> You responded with this:
> 
> > its the same, it inserts special characters into the file name.
> 
> So, basically, this is an issue with `fopen` - not with phpseclib. I'd repost your question on stackoverflow and ask about why `fopen` isn't working. Don't mention phpseclib because, at this point, phpseclib would just be a distraction. The `fopen` experts aren't liable to be reading questions about phpseclib.

fopen is working fine. i create files, move them around in the server with no problem, i copy and delete them on the server with no problem. So fopen has nothing to do with it. This only happens on ->Get nothing else.  idk why you say its fopen since the file is ok on the server.

**Comment by Alexisgarci** [comment]
> The filename is metadata stored on filesystem. As such I'd recommend investigating the local and remote filesystems. Guess: Different filesystems with different encodings.

it was so obvious that i dindt even think of that, just added `<add key="AddDefaultCharset" value="utf8_general_ci"/>` to my server config and it worked. Some times feel so dumb with these mistakes... Anyway thanks for the help.

**Comment by bantu** [comment]
Cheers
