### ISSUE TITLE
Call to undefined method Strings::unpack()

### ISSUE THREAD

**Issue by actycrea** [phpseclib/phpseclib#1395]
Fatal error: Call to undefined method phpseclib\Common\Functions\Strings::unpack() in phpseclib/Net/SFTP.php on line 2755

The **Strings::unpack()** method does not exist. It is fixed by replacing the method with this other **Strings::unpackSSH2()**

**Comment by terrafrost** [comment]
Good catch!

https://github.com/phpseclib/phpseclib/commit/b89c488f4338d74f0fec05be29c0deae2dc50b97 should fix this!
