### ISSUE TITLE
Remote command - No such file or directory

### ISSUE THREAD

**Issue by solaryssky** [phpseclib/phpseclib#1401]
$ssh = new SSH2($host);
if (!$ssh->login($ssh_name, $ssh_pass)) {
    exit('Не могу авторизоваться по SSH!<br>');
}

$command_ssh_list = '/usr/bin/curl --disable-eprt -P - -sk "'.$ftp_type.'://'.$req_host.$req_path.'" --user "'.$req_user.':'.$req_pass.'" --connect-timeout 30 | /usr/bin/wc -l';

$list_file = $ssh->exec('"'.$command_ssh_list.'"');

Return error:

string(177) "bash: /usr/bin/curl --disable-eprt -P - -sk sftp://10.0.00.00:22/aкс/inc/rtc/ --user user:pass --connect-timeout 30 | /usr/bin/wc -l: No such file or directory "

If you execute the command directly on the host, it runs without errors like this:

/usr/bin/curl --disable-eprt -P - -sk sftp://10.0.00.00:22/aкс/inc/rtc/ --user user:pass --connect-timeout 30 | /usr/bin/wc -l

**Comment by bantu** [comment]
Conceptually, piping (the `|` symbol) is a shell construction. So you have to make sure you're actually using a shell.

**Comment by solaryssky** [comment]
If you plump without | - the error is the same . bash: /usr/bin/curl --disable-eprt -P - -sk sftp://10.0.00.00:22/aкс/inc/rtc/ --user user:pass --connect-timeout 30: No such file or directory

**Comment by solaryssky** [comment]
string(19) "/bin/bash -c 'curl'" string(53) "bash: /bin/bash -c 'curl': No such file or directory "

**Comment by solaryssky** [comment]
I don’t quite understand why it worked, but if I form a command in a variable just before the ssh connection, it works without errors

$ command_ssh_list = '/ bin / bash -c \' curl --disable-eprt -P - -sk \ ''. $ ftp_type. ': //'.$req_host.$req_path.' \ '--user \' '. $ req_user.': '. $ req_pass.' \ '--connect-timeout 10 \' | wc -l ';
$ list_file = $ ssh-> exec ($ command_ssh_list);

**Comment by terrafrost** [comment]
I'd say this is more of a curl question than it is a phpseclib question.

In looking at the curl manual...  idk why you're doing `--disable-eprt` - that seems only applicable to FTP servers.  I guess `-sk` means silent and insecure over SSL, both of which seems unnecessary for SFTP.

Anyway, my best guess is that you need a PTY for this to work. Normally when you SSH into a machine you have a PTY. You can enable this before you do the `exec()` by doing `$ssh->enablePTY()`.

That said, the most accurate simulation an SSH shell is to use the interactive read / write commands: http://phpseclib.sourceforge.net/ssh/examples.html#interactive

FWIW I did try to run a simplified version of your command (`curl sftp://127.0.0.1:22/ --user username:password --connect-timeout 30`) and got this error back:

> curl: (1) Protocol "sftp" not supported or disabled in libcurl

I tried to compile a new version of curl with sftp using the different instructions at https://askubuntu.com/questions/195545/how-to-enable-sftp-support-in-curl without success. Maybe this wouldn't be an issue on a newer version of Ubuntu but tbh atm I feel like this has already taken too much of my time.

Try the PTY or interactive read / write, if you're unsatisfied with your current approach, and lmk how it goes.

**Comment by solaryssky** [comment]
Hello! Yes, you're right; some of the keys are not needed for. Rather, it was my mistake - extra quotes $ list_file = $ ssh-> exec ('"'. $ Command_ssh_list. '"');
