### ISSUE TITLE
Reconnecting with ping fails because fsock is still open

### ISSUE THREAD

**Issue by dorrogeray** [phpseclib/phpseclib#1402]
Hello,

I have a long running import, which fetches a file from SFTP, and after processing it, tries to fetch another file.. This is where the `Connection closed prematurely` or `Connection closed by server` happens. I thought I could prevent this by adding `$this->sftp->ping()` before the fetch, but actually the ping itself fails, because in the _connect method the condition `if (!is_resource($this->fsock)) {` is evalued as false (`is_resource($this->fsock)` is true).. This happens because the disconnect method does not close the fsock if the bitmap was reset to 0 due to user error.. Which in this case, it was. Therefore the fsock remains a resource and following reconnect attempts fail.

```
    /**
     * Disconnect
     *
     * @param int $reason
     * @return bool
     * @access private
     */
    function _disconnect($reason)
    {
        // I think the disconnect should check if fsock is a resource, and if so, always close it.
        if ($this->bitmap & self::MASK_CONNECTED) {
            $data = pack('CNNa*Na*', NET_SSH2_MSG_DISCONNECT, $reason, 0, '', 0, '');
            $this->_send_binary_packet($data);
            $this->bitmap = 0;
            fclose($this->fsock);
            return false;
        }
    }
```

Let me know If I can provide any more information.

**Comment by terrafrost** [comment]
One thing you could try to do is to run a "ping" command in the background. eg.

```php
<?php
include('Net/SSH2.php');

$ssh = new Net_SSH2('127.0.0.1', 2222);
$ssh->login('vagrant', 'vagrant');

$ssh->write("ping 127.0.0.1\n");

sleep(15);
echo $ssh->exec('ls -latr');
```
So let's say the SSH server is setup to timeout after 2s (via `ClientAliveInterval` in sshd_config). The `sleep(15)` in the code snippet far exceeds that limit and yet the `$ssh->exec('ls -latr')` still produces output. That's because of the ping in the background.

**Comment by dorrogeray** [comment]
@terrafrost Thanks! I appreciate your quick response. :+1: What you suggest seems to be a workaround, rather than a solution. Also, this is issue is about the `phpseclib\Net\SFTP` class, so I am not sure if the ping would work. I have also noticed another issue. The `phpseclib\Net\SFTP` overrides the `login` method of  `phpseclib\Net\SSH2`, but it does not store the credentials in the `$this->auth` array, like it's parent class does. This can lead to a crash in `phpseclib\Net\SSH2::_reconnect()`, where the `$result` variable will be undefined if `$this->auth` contains an empty array. Should I open another ticket for this?

I am still trying to work out some other workaroud than using the ping. Ill update this when I reach some conclusions!

**Comment by terrafrost** [comment]
> What you suggest seems to be a workaround, rather than a solution

I mean, to an extent, it is, but keep in mind, PHP doesn't support stuff like Javascript's [setInterval](https://www.w3schools.com/jsref/met_win_setinterval.asp). I'm not gonna say it's not impossible to implement but it'd require a significant overhaul of SSH2.php. Which I do intend to do at some point but not any time soon, unless I'm paid a sizable amount of cash lol. I mean, I have a roadmap for phpseclib in my head and the SSH2.php revamp is a good ways out on that roadmap. I can bump it up in priority for some $$.

As for the `login` method being overwritten...  it is BUT it does call the parent method. From `SFTP::login()`:

```php
        $args = func_get_args();
        if (!call_user_func_array(array(&$this, '_login'), $args)) {
            return false;
        }
```

This is basically what `SSH2::login()` does:

```php
    function login($username)
    {
        $args = func_get_args();
        $this->auth[] = $args;
        return call_user_func_array(array(&$this, '_login'), $args);
    }
```

I mean, if you can create some code sample that actually demonstrates the problem in a reproducible manner then I'll take a look but my initial impression, based on your description, is that it's a non issue.

**Comment by dorrogeray** [comment]
There is no need for **setInterval** or anything similar. **I think it is ok that the sftp connection expires.. That's not what the problem is at all imho.**

The problem is, that the library does not properly support reconnecting for SFTP, even though it **almost** does. Now I have spent entire day debugging this, and here is what I found:

1] What you said about calling parent method is not quite true, it calls the parent method "_login" - note the underscore, but the `$this->auth` is actually set in the parent "login" method, without underscore. So thats one issue, with relatively easy fix.

2] When I tried to reconnect, I found another issue: In the method `phpseclib\Net\SFTP::login` following assignment is made `$this->use_request_id = true;`. The problem is, that before you can successfully try to login again, you have to set this property back to `$this->use_request_id = false;`, otherwise, in method `phpseclib\Net\SFTP::_get_sftp_packet`, this snippet:

```
if ($this->use_request_id) {
    extract(unpack('Npacket_id', $this->_string_shift($this->packet_buffer, 4))); // remove the request id
   $length-= 5; // account for the request id and the packet type
} else {
    $length-= 1; // account for the packet type
}
```

Will cause a problem - it will cull off the **version** sent from server to the client, which then of course completely breaks the rest of the parsing.

This is the first login:
```preformated
-> NET_SFTP_INIT (0.0001s)
00000000  00:00:00:03                                      ....

<- NET_SFTP_VERSION (0.2031s)
00000000  00:00:00:03:00:00:00:18:70:6f:73:69:78:2d:72:65  ........posix-re
00000010  6e:61:6d:65:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  name@openssh.com
00000020  00:00:00:01:31:00:00:00:13:73:74:61:74:76:66:73  ....1....statvfs
00000030  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:01  @openssh.com....
00000040  32:00:00:00:14:66:73:74:61:74:76:66:73:40:6f:70  2....fstatvfs@op
00000050  65:6e:73:73:68:2e:63:6f:6d:00:00:00:01:32:00:00  enssh.com....2..
00000060  00:14:68:61:72:64:6c:69:6e:6b:40:6f:70:65:6e:73  ..hardlink@opens
00000070  73:68:2e:63:6f:6d:00:00:00:01:31:00:00:00:11:66  sh.com....1....f
00000080  73:79:6e:63:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  sync@openssh.com
00000090  00:00:00:01:31  
```
Note the **00:00:00:03** in the NET_SFTP_VERSION response.

This is the second login, which should happen when reconnecting (see foreach in `phpseclib\Net\SSH2::_reconnect()`):
```preformated
-> NET_SFTP_INIT (0.0001s)
00000000  00:00:00:03                                      ....

<- NET_SFTP_VERSION (0.2041s)
00000000  00:00:00:18:70:6f:73:69:78:2d:72:65:6e:61:6d:65  ....posix-rename
00000010  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:01  @openssh.com....
00000020  31:00:00:00:13:73:74:61:74:76:66:73:40:6f:70:65  1....statvfs@ope
00000030  6e:73:73:68:2e:63:6f:6d:00:00:00:01:32:00:00:00  nssh.com....2...
00000040  14:66:73:74:61:74:76:66:73:40:6f:70:65:6e:73:73  .fstatvfs@openss
00000050  68:2e:63:6f:6d:00:00:00:01:32:00:00:00:14:68:61  h.com....2....ha
00000060  72:64:6c:69:6e:6b:40:6f:70:65:6e:73:73:68:2e:63  rdlink@openssh.c
00000070  6f:6d:00:00:00:01:31:00:00:00:11:66:73:79:6e:63  om....1....fsync
00000080  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:01  @openssh.com....
00000090  31                                               1

```
Note that the  **00:00:00:03** is now missing. This is because the `$this->use_request_id` was set to `true` during the second login request. Instead, it should have been reset to false right before the foreach with auth in `phpseclib\Net\SSH2::_reconnect()`

This was very hard to debug, because the issue is propagated into the logs, so I initially thought that the server is simply not sending the version byte back.. And its hard to verify, because its sftp and even if you sniff the packets, they are encryped.

When I have more time, I may be able to prepare some docker setup to demonstrate this issue. For now, this is what I am doing to be able to sucessfully reconnect:

1] I manually set the `$sftp->auth[] = ['user', 'pass'];` after login
2] 
```
try {
    echo "Trying to get another file" . PHP_EOL;
    $file = $sftp->get('file');
} catch (\Throwable $throwable) {
    if (strpos($throwable->getMessage(), 'Connection closed by server') !== false ||
        strpos($throwable->getMessage(), 'Connection closed prematurely') !== false
    ) {
        if (reconnect($sftp)) {
            echo 'Succesfully reconnected!' . PHP_EOL;
        } else {
            echo 'Failed to reconnect!' . PHP_EOL;
            die('this is the end');
        }

        try {
            echo "Trying to retrieve file one more time.." . PHP_EOL;
            $file = $sftp->get('sshd_config');
        } catch (\Throwable $throwable) {
            echo sprintf(
                "There was an error while retrieving file after reconnecting: \"%s\"\n",
                $throwable->getMessage()
            );

            throw $throwable;
        }
    } else {
        echo "Exception not recognized.." . PHP_EOL;
    }
}

/**
 * @param SFTP $sftp
 *
 * @return bool
 */
function reconnect(SFTP $sftp): bool
{
    // This is a workaround to reset the connection, since there seems to be a bug in the library,
    // with the ping not being able to reconnect properly, because the fsock is not closed properly
    // in the disconnect method, when the bitmap is set to 0
    if (is_resource($sftp->fsock)) {
        // close socket that did not get closed by the library
        fclose($sftp->fsock);
        // Prevent bad parsing of version
        $sftp->use_request_id = false;
        // reconnect, this will automatically call login
        if ($sftp->_reconnect()) {
            // Ping and be happy
            return $sftp->ping();
        };
    }

    return false;
}
```

Thanks for your time reading this! :+1: Hopefully, it will be usefull and it will help others avoid this pitfall.. If you fix these issue Ill buy you a beer or two. :-)

**Comment by bantu** [comment]
@dorrogeray Thanks a lot for your analysis. I agree that reconnect should be supported properly.

**Comment by terrafrost** [comment]
Good catches and good analysis. I apologize if I came off as being "thick".

I've made some progress on fixing the issues but I have to head off to work soon.

> If you fix these issues Ill buy you a beer or two. :-)

You could do a patreon donation! :D

**Comment by dorrogeray** [comment]
> You could do a patreon donation! :D

Will do once its fixed.. :D In the amount of a beer or two.. ;-)

**Comment by terrafrost** [comment]
I believe https://github.com/phpseclib/phpseclib/commit/fbf36728fdbba5f62e33e61e6ea00f754021cc4e should fix the issue for you!

**Comment by dorrogeray** [comment]
Looks like this should fix it indeed! I will test this properly during the weekend (too busy at work right now, deadlines looming :P).. And thanks for the quick fix!

**Comment by terrafrost** [comment]
I've gone ahead and made a new release (2.0.22) that includes this fix.

If there are issues with it I guess create a new ticket.

Thanks!

**Comment by BR0kEN-** [comment]
Now this ends up in `fclose() expects parameter 1 to be resource, boolean given` if a server is a wrong one.

```
fclose() expects parameter 1 to be resource, boolean given

/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4122
/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:3167
/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3157
/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3173
```

Example: `(new \phpseclib\Net\SFTP('my-server', 4000))->login('propeople', 'wrong-pass');`.

**Comment by terrafrost** [comment]
I'm gonna get a fix out for this this evening (after I get home from work) and will release a new version.

Thanks!

**Comment by dorrogeray** [comment]
Sorry I did not have time to test it yet - but I have sent a beer or two via paypal your way. Thanks for the fix!
