### ISSUE TITLE
Modulus and Exponent parsed wrong

### ISSUE THREAD

**Issue by andrew-svirin** [phpseclib/phpseclib#1413]
Hi,
Thanks for this library.

I have a problem with parsing public key by last version of phpseclib.

I parsing public key:

`
-----BEGIN RSA PUBLIC KEY-----
MIIBCgIDAQABAoIBAQCicNlQ2CUY4JYpapSBX+9IitH+6WOHNTzAcB3xG500Jvaz
MceTAFGTIB/KTDVONdbFfp5p2M5CT7cRIwdU3152/qoDOI8W+InTzmJzAWt3kt+6
En492uxRdjjU0HIgxXlz2GQuitoHNGae2NCgzfTxZKl5bcyF3d+txmnQ2HRPKS8R
ud0C5GpVYC6y0Bqu52Y1FE7N4IQTJip4V23rr9w7DCDiCwaFWgy0XFo1e3yVElQQ
GVcNmANNON8eNcQT2rYJVn/mJRtTgtg9J9DfbamUgSQL2uf3Z8TYC9rvjG2u8hOB
+AXP6p8+Ii2+jf7YFZExu+ne1G/6Er9k0GV2xyEj
-----END RSA PUBLIC KEY-----
`
by code
```php
      $publicKey = new RSA();
      $publicKey->setPublicKey($certificate->getPublicKey(), RSA::PUBLIC_FORMAT_PKCS1);
      $e0 = $publicKey->exponent->toHex(true);
      $m0 = $publicKey->modulus->toHex(true);
```

And got vice verse result, where exponent is huge value and modulus is short.

This tools shows correct result `https://8gwifi.org/PemParserFunctions.jsp`

Could you check the logic of parsing public key?

**Comment by terrafrost** [comment]
I contend that the key is malformed.

From [PKCS #1: RSA Cryptography Specifications Version 2.2 § A.1.1.  RSA Public Key Syntax](https://tools.ietf.org/html/rfc8017#appendix-A.1.1):

```
   An RSA public key should be represented with the ASN.1 type
   RSAPublicKey:

         RSAPublicKey ::= SEQUENCE {
             modulus           INTEGER,  -- n
             publicExponent    INTEGER   -- e
         }
```

Here's what `openssl asn1parse -in test.pem` gives me:

```
    0:d=0  hl=4 l= 266 cons: SEQUENCE
    4:d=1  hl=2 l=   3 prim: INTEGER           :010001
    9:d=1  hl=4 l= 257 prim: INTEGER           :A270D950D82518E096296A94815FEF488AD1FEE96387353CC0701DF11B9D3426F6B331C793005193201FCA4C354E35D6C57E9E69D8CE424FB711230754DF5E76FEAA03388F16F889D3CE6273016B7792DFBA127E3DDAEC517638D4D07220C57973D8642E8ADA0734669ED8D0A0CDF4F164A9796DCC85DDDFADC669D0D8744F292F11B9DD02E46A55602EB2D01AAEE76635144ECDE08413262A78576DEBAFDC3B0C20E20B06855A0CB45C5A357B7C9512541019570D98034D38DF1E35C413DAB609567FE6251B5382D83D27D0DF6DA99481240BDAE7F767C4D80BDAEF8C6DAEF21381F805CFEA9F3E222DBE8DFED8159131BBE9DED46FFA12BF64D06576C72123
```
http://phpseclib.sourceforge.net/x509/asn1parse.php concurs.

So the modulus - the first parameter of the key - is super small - and the exponent - the second parameter - is super large.

Like I said, it looks like a malformed key.

**Comment by terrafrost** [comment]
I tried it on https://8gwifi.org/PemParserFunctions.jsp as well. idk what value you selected from the drop down menu but when I selected "RSA" I got results consistent with my own:

```
Algo RSA
Format X.509
 ASN1 Dump
RSA Public Key [97:61:cb:75:57:2d:54:8a:62:ed:73:39:57:9f:09:ed:2c:2f:55:91]
            modulus: 10001
    public exponent: a270d950d82518e096296a94815fef488ad1fee96387353cc0701df11b9d3426f6b331c793005193201fca4c354e35d6c57e9e69d8ce424fb711230754df5e76feaa03388f16f889d3ce6273016b7792dfba127e3ddaec517638d4d07220c57973d8642e8ada0734669ed8d0a0cdf4f164a9796dcc85dddfadc669d0d8744f292f11b9dd02e46a55602eb2d01aaee76635144ecde08413262a78576debafdc3b0c20e20b06855a0cb45c5a357b7c9512541019570d98034d38df1e35c413dab609567fe6251b5382d83d27d0df6da99481240bdae7f767c4d80bdaef8c6daef21381f805cfea9f3e222dbe8dfed8159131bbe9ded46ffa12bf64d06576c72123
```

**Comment by andrew-svirin** [comment]
Your rights. Thanks a lot  for your reply.
