### ISSUE TITLE
$keyLength is undefined in SSH2.php

### ISSUE THREAD

**Issue by simPod** [phpseclib/phpseclib#1419]
https://github.com/phpseclib/phpseclib/blob/bd534c9271751da28f25b892315746b54dd394de/phpseclib/Net/SSH2.php#L1542

The variable `$keyLength` is not defined. I did not figure out what it might be unfortunately.

**Comment by NiklasBr** [comment]
Did it get lost here perhaps?

https://github.com/phpseclib/phpseclib/commit/1e7453b585e1092549ccc8ba45d7286ced908f21#diff-82a5983a6daace4acbcc65edf2dfb605L1576

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/f36b4686c97003dbea82e037975a597012ff73b2 should fix this - thanks!
