### ISSUE TITLE
Get error timeout on a test server

### ISSUE THREAD

**Issue by tonviet712** [phpseclib/phpseclib#1422]
My code working fine on local/test server

```
require 'phpseclib/Net/SFTP.php';

$sftp = new Net_SFTP('xxx.xxx.xx');
if (!$sftp->login('user', 'pass')) {
    exit('Login Failed');
}
```

But when run on another test server that return error:
**PHP Notice:  Cannot connect to xxx:22. Error 110. Connection timed out in dir/phpseclib/Net/SSH2.php on line 1187**

**Comment by terrafrost** [comment]
In all likelihood `fsockopen` isn't working for you. What happens if you try to do this?:

```php
<?php
$fsock = fsockopen('xxx.xxx.xx', 22);
var_dump($fsock);
?>
```

**Comment by tonviet712** [comment]
It returns **false**
```
$fp = fsockopen($host, $port, $errno, $errstr, 30);
var_dump($fp);
if (!$fp) {
    echo "$errstr ($errno)<br />\n";
} else {
    $out = "GET / HTTP/1.1\r\n";
    $out .= "Host: www.example.com\r\n";
    $out .= "Connection: Close\r\n\r\n";
    fwrite($fp, $out);
    while (!feof($fp)) {
        echo fgets($fp, 128);
    }
    fclose($fp);
}

**Comment by terrafrost** [comment]
There's not much that can be done on the phpseclib end then if even `fsockopen` is failing. Maybe check your iptables rules or something idk. If you're connecting via a hostname maybe make sure that it's connecting to the right IP address. Like maybe you have an entry in `/etc/hosts` that you had forgotten about or something.
