### ISSUE TITLE
RSA PSS doesn't support non power of 2 public keys

### ISSUE THREAD

**Issue by masterzen** [phpseclib/phpseclib#1423]
The RFC3447 doesn't mention that public keys modulus size should be a power of 2.
Though, the RSA PSS verification code only supports keys whose modulus has a size that is a power of 2.

I discovered this while trying to validate the JWS PS256 signature of a token that had been signed with a public key of 522 bits.

**Comment by terrafrost** [comment]
Your fix has been merged.

Thanks!
