### ISSUE TITLE
connection closed by server

### ISSUE THREAD

**Issue by malohtie** [phpseclib/phpseclib#1429]
Hi guys, i have this error that gonna make me crazy ,

the crazy part about this is sometimes my code work normal,  some throw to me this error telling me that is connection closed by server 

ps : i can log to my remote server normally without any issue
i'm using the last release v2

here is my log 

```
{
    "message": "Connection closed by server",
    "exception": "ErrorException",
    "file": "/var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php",
    "line": 1228,
    "trace": [
        {
            "function": "handleError",
            "class": "Illuminate\\Foundation\\Bootstrap\\HandleExceptions",
            "type": "->"
        },
        {
            "file": "/var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php",
            "line": 1228,
            "function": "user_error"
        },
        {
            "file": "/var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php",
            "line": 2101,
            "function": "_connect",
            "class": "phpseclib\\Net\\SSH2",
            "type": "->"
        },
        {
            "function": "_login",
            "class": "phpseclib\\Net\\SSH2",
            "type": "->"
        },
        {
            "file": "/var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php",
            "line": 414,
            "function": "call_user_func_array"
        },
        {
            "file": "/var/dms/app/Libraries/Ssh.php",
            "line": 59,
            "function": "login",
            "class": "phpseclib\\Net\\SFTP",
            "type": "->"
        },
        {
            "file": "/var/dms/app/Http/Controllers/user/PmtaController.php",
            "line": 61,
            "function": "connect",
            "class": "app\\Libraries\\Ssh",
            "type": "->"
        },
        ...
    ]
}
```
My code

```
$ssh = new Ssh($server->ip, $server->username, $server->password, $server->login_type, $server->port);
if (!$ssh->connect()) {
                    return response()->json(['status' => FALSE, 'data' => 'ERROR AUTH', 'id' => $request->id]);
}
$result = $ssh->exec("pmta pause queue {$vmta};");

```
ssh class
```
public function __construct($ip, $username, $password, $login_type, $port = 22, $id = null, $domain = null)
{
        $this->id = $id;
        $this->ip = $ip;
        $this->port = $port;
        $this->username = $username;
        $this->password = $password;
        $this->login_type = strtolower($login_type);
        $this->domain = $domain;
}
public function connect()
    {
        $key = null;
        $this->ssh = new SFTP($this->ip, $this->port);

        if($this->login_type == "password"){
            $key = $this->password;
        } else {
            $key = new RSA();
            $key->loadKey($this->password);
        }
        if($this->ssh->login($this->username, $key))
        {
           return true;
        }
        return false;
    }

    public function exec($command)
    {
        if($this->ssh->isConnected() && $this->ssh->isAuthenticated()) {
            return $this->ssh->exec($command);
        }
        return false;
    }
```

any suggestion please ?

**Comment by terrafrost** [comment]
Can you post the SSH logs? You can get them by doing `define('NET_SSH2_LOGGING', 2)` at the top and then `echo $this->ssh->getLog()` afterwards.

Based on the line numbers it looks like all it's doing is sending the identification strings but even that could yield some useful information.

**Comment by malohtie** [comment]
i did it as you telled me 

![image](https://user-images.githubusercontent.com/20033279/68625331-272e9500-04d9-11ea-863c-2c914d4f79b7.png)



string seem to be empty when the exception occurs hmmm ? 

`Connection closed by server------------------<pre></pre>*******************`

otherwise in successful call here's the log 

`<-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  35:2e:33:0d:0a                                   5.3..

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:32:2e:30:20:28:6f:70:65:6e:73:73:6c:2c:20  b_2.0 (openssl, 
00000020  62:63:6d:61:74:68:29:0d:0a                       bcmath)..

-> NET_SSH2_MSG_KEXINIT (since last: 0.3111, network: 0.0001s)
00000000  5e:74:ce:e1:a6:e0:c3:da:a8:46:02:9a:8a:7a:91:98  ^t.......F...z..
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64  an-group1-sha1,d
00000030  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
00000040  6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69  oup14-sha1,diffi
00000050  65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d  e-hellman-group-
00000060  65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69  exchange-sha1,di
00000070  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000080  75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32  up-exchange-sha2
00000090  35:36:00:00:00:29:72:73:61:2d:73:68:61:32:2d:32  56...)rsa-sha2-2
000000a0  35:36:2c:72:73:61:2d:73:68:61:32:2d:35:31:32:2c  56,rsa-sha2-512,
000000b0  73:73:68:2d:72:73:61:2c:73:73:68:2d:64:73:73:00  ssh-rsa,ssh-dss.
000000c0  00:00:d3:61:65:73:31:32:38:2d:63:74:72:2c:61:65  ...aes128-ctr,ae
000000d0  73:31:39:32:2d:63:74:72:2c:61:65:73:32:35:36:2d  s192-ctr,aes256-
000000e0  63:74:72:2c:74:77:6f:66:69:73:68:31:32:38:2d:63  ctr,twofish128-c
000000f0  74:72:2c:74:77:6f:66:69:73:68:31:39:32:2d:63:74  tr,twofish192-ct
00000100  72:2c:74:77:6f:66:69:73:68:32:35:36:2d:63:74:72  r,twofish256-ctr
00000110  2c:61:65:73:31:32:38:2d:63:62:63:2c:61:65:73:31  ,aes128-cbc,aes1
00000120  39:32:2d:63:62:63:2c:61:65:73:32:35:36:2d:63:62  92-cbc,aes256-cb
00000130  63:2c:74:77:6f:66:69:73:68:31:32:38:2d:63:62:63  c,twofish128-cbc
00000140  2c:74:77:6f:66:69:73:68:31:39:32:2d:63:62:63:2c  ,twofish192-cbc,
00000150  74:77:6f:66:69:73:68:32:35:36:2d:63:62:63:2c:74  twofish256-cbc,t
00000160  77:6f:66:69:73:68:2d:63:62:63:2c:62:6c:6f:77:66  wofish-cbc,blowf
00000170  69:73:68:2d:63:74:72:2c:62:6c:6f:77:66:69:73:68  ish-ctr,blowfish
00000180  2d:63:62:63:2c:33:64:65:73:2d:63:74:72:2c:33:64  -cbc,3des-ctr,3d
00000190  65:73:2d:63:62:63:00:00:00:d3:61:65:73:31:32:38  es-cbc....aes128
000001a0  2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74:72:2c  -ctr,aes192-ctr,
000001b0  61:65:73:32:35:36:2d:63:74:72:2c:74:77:6f:66:69  aes256-ctr,twofi
000001c0  73:68:31:32:38:2d:63:74:72:2c:74:77:6f:66:69:73  sh128-ctr,twofis
000001d0  68:31:39:32:2d:63:74:72:2c:74:77:6f:66:69:73:68  h192-ctr,twofish
000001e0  32:35:36:2d:63:74:72:2c:61:65:73:31:32:38:2d:63  256-ctr,aes128-c
000001f0  62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c:61:65  bc,aes192-cbc,ae
00000200  73:32:35:36:2d:63:62:63:2c:74:77:6f:66:69:73:68  s256-cbc,twofish
00000210  31:32:38:2d:63:62:63:2c:74:77:6f:66:69:73:68:31  128-cbc,twofish1
00000220  39:32:2d:63:62:63:2c:74:77:6f:66:69:73:68:32:35  92-cbc,twofish25
00000230  36:2d:63:62:63:2c:74:77:6f:66:69:73:68:2d:63:62  6-cbc,twofish-cb
00000240  63:2c:62:6c:6f:77:66:69:73:68:2d:63:74:72:2c:62  c,blowfish-ctr,b
00000250  6c:6f:77:66:69:73:68:2d:63:62:63:2c:33:64:65:73  lowfish-cbc,3des
00000260  2d:63:74:72:2c:33:64:65:73:2d:63:62:63:00:00:00  -ctr,3des-cbc...
00000270  39:68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68  9hmac-sha2-256,h
00000280  6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63  mac-sha1-96,hmac
00000290  2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39  -sha1,hmac-md5-9
000002a0  36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:39:68:6d  6,hmac-md5...9hm
000002b0  61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63  ac-sha2-256,hmac
000002c0  2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68  -sha1-96,hmac-sh
000002d0  61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68  a1,hmac-md5-96,h
000002e0  6d:61:63:2d:6d:64:35:00:00:00:04:6e:6f:6e:65:00  mac-md5....none.
000002f0  00:00:04:6e:6f:6e:65:00:00:00:00:00:00:00:00:00  ...none.........
00000300  00:00:00:00                                      ....

<- NET_SSH2_MSG_KEXINIT (since last: 0.1903, network: 0.1901s)
00000000  36:09:56:d1:56:c3:fe:a4:ec:19:b3:5e:1b:2d:50:c1  6.V.V......^.-P.
00000010  00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ...~diffie-hellm
00000020  61:6e:2d:67:72:6f:75:70:2d:65:78:63:68:61:6e:67  an-group-exchang
00000030  65:2d:73:68:61:32:35:36:2c:64:69:66:66:69:65:2d  e-sha256,diffie-
00000040  68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d:65:78  hellman-group-ex
00000050  63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69:66:66  change-sha1,diff
00000060  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000070  31:34:2d:73:68:61:31:2c:64:69:66:66:69:65:2d:68  14-sha1,diffie-h
00000080  65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:2d:73:68  ellman-group1-sh
00000090  61:31:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73  a1....ssh-rsa,ss
000000a0  68:2d:64:73:73:00:00:00:9d:61:65:73:31:32:38:2d  h-dss....aes128-
000000b0  63:74:72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61  ctr,aes192-ctr,a
000000c0  65:73:32:35:36:2d:63:74:72:2c:61:72:63:66:6f:75  es256-ctr,arcfou
000000d0  72:32:35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c  r256,arcfour128,
000000e0  61:65:73:31:32:38:2d:63:62:63:2c:33:64:65:73:2d  aes128-cbc,3des-
000000f0  63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63:62:63  cbc,blowfish-cbc
00000100  2c:63:61:73:74:31:32:38:2d:63:62:63:2c:61:65:73  ,cast128-cbc,aes
00000110  31:39:32:2d:63:62:63:2c:61:65:73:32:35:36:2d:63  192-cbc,aes256-c
00000120  62:63:2c:61:72:63:66:6f:75:72:2c:72:69:6a:6e:64  bc,arcfour,rijnd
00000130  61:65:6c:2d:63:62:63:40:6c:79:73:61:74:6f:72:2e  ael-cbc@lysator.
00000140  6c:69:75:2e:73:65:00:00:00:9d:61:65:73:31:32:38  liu.se....aes128
00000150  2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74:72:2c  -ctr,aes192-ctr,
00000160  61:65:73:32:35:36:2d:63:74:72:2c:61:72:63:66:6f  aes256-ctr,arcfo
00000170  75:72:32:35:36:2c:61:72:63:66:6f:75:72:31:32:38  ur256,arcfour128
00000180  2c:61:65:73:31:32:38:2d:63:62:63:2c:33:64:65:73  ,aes128-cbc,3des
00000190  2d:63:62:63:2c:62:6c:6f:77:66:69:73:68:2d:63:62  -cbc,blowfish-cb
000001a0  63:2c:63:61:73:74:31:32:38:2d:63:62:63:2c:61:65  c,cast128-cbc,ae
000001b0  73:31:39:32:2d:63:62:63:2c:61:65:73:32:35:36:2d  s192-cbc,aes256-
000001c0  63:62:63:2c:61:72:63:66:6f:75:72:2c:72:69:6a:6e  cbc,arcfour,rijn
000001d0  64:61:65:6c:2d:63:62:63:40:6c:79:73:61:74:6f:72  dael-cbc@lysator
000001e0  2e:6c:69:75:2e:73:65:00:00:00:85:68:6d:61:63:2d  .liu.se....hmac-
000001f0  6d:64:35:2c:68:6d:61:63:2d:73:68:61:31:2c:75:6d  md5,hmac-sha1,um
00000200  61:63:2d:36:34:40:6f:70:65:6e:73:73:68:2e:63:6f  ac-64@openssh.co
00000210  6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c  m,hmac-sha2-256,
00000220  68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2c:68:6d  hmac-sha2-512,hm
00000230  61:63:2d:72:69:70:65:6d:64:31:36:30:2c:68:6d:61  ac-ripemd160,hma
00000240  63:2d:72:69:70:65:6d:64:31:36:30:40:6f:70:65:6e  c-ripemd160@open
00000250  73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61  ssh.com,hmac-sha
00000260  31:2d:39:36:2c:68:6d:61:63:2d:6d:64:35:2d:39:36  1-96,hmac-md5-96
00000270  00:00:00:85:68:6d:61:63:2d:6d:64:35:2c:68:6d:61  ....hmac-md5,hma
00000280  63:2d:73:68:61:31:2c:75:6d:61:63:2d:36:34:40:6f  c-sha1,umac-64@o
00000290  70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d  penssh.com,hmac-
000002a0  73:68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68  sha2-256,hmac-sh
000002b0  61:32:2d:35:31:32:2c:68:6d:61:63:2d:72:69:70:65  a2-512,hmac-ripe
000002c0  6d:64:31:36:30:2c:68:6d:61:63:2d:72:69:70:65:6d  md160,hmac-ripem
000002d0  64:31:36:30:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  d160@openssh.com
000002e0  2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d  ,hmac-sha1-96,hm
000002f0  61:63:2d:6d:64:35:2d:39:36:00:00:00:15:6e:6f:6e  ac-md5-96....non
00000300  65:2c:7a:6c:69:62:40:6f:70:65:6e:73:73:68:2e:63  e,zlib@openssh.c
00000310  6f:6d:00:00:00:15:6e:6f:6e:65:2c:7a:6c:69:62:40  om....none,zlib@
00000320  6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:00:00  openssh.com.....
00000330  00:00:00:00:00:00:00:00                          ........

-> NET_SSH2_MSG_KEXDH_INIT (since last: 0.1073, network: 0.0001s)
00000000  00:00:00:80:0d:9d:c3:18:5e:46:e6:b1:d4:cc:3a:4f  ........^F....:O
00000010  e0:0f:bf:d6:36:94:bb:cc:76:49:e5:6b:c8:43:16:12  ....6...vI.k.C..
00000020  d5:42:56:79:eb:e6:15:4d:d5:22:7c:e9:81:57:5f:9b  .BVy...M."|..W_.
00000030  db:9a:2e:dc:eb:78:7f:98:70:d6:39:ad:5b:eb:f5:0f  .....x..p.9.[...
00000040  51:b3:c6:57:5f:34:1d:17:78:fc:64:df:75:35:9e:69  Q..W_4..x.d.u5.i
00000050  2a:59:5b:1c:95:66:bb:06:a1:e8:41:88:97:7b:2a:48  *Y[..f....A..{*H
00000060  0b:44:e2:6b:03:a6:01:c9:ef:0a:c4:62:d6:71:13:de  .D.k.......b.q..
00000070  cf:d1:be:71:7e:9a:41:60:0b:ec:65:bd:a1:b5:d4:af  ...q~.A`..e.....
00000080  5e:5f:fc:fa                                      ^_..

<- NET_SSH2_MSG_KEXDH_REPLY (since last: 0.2003, network: 0.2002s)
00000000  00:00:01:15:00:00:00:07:73:73:68:2d:72:73:61:00  ........ssh-rsa.
00000010  00:00:01:23:00:00:01:01:00:c9:1b:5a:2b:b0:43:27  ...#.......Z+.C'
00000020  02:fa:1d:c0:c5:e9:35:aa:2c:f9:6d:75:42:e1:6a:03  ......5.,.muB.j.
00000030  29:d6:04:59:3f:c6:7d:8d:1c:98:22:ea:ae:25:90:b4  )..Y?.}..."..%..
00000040  ac:6b:72:6a:59:eb:95:c5:e3:b7:a1:cb:e2:fd:f4:64  .krjY..........d
00000050  f3:07:09:a7:39:5d:80:4e:c6:f4:0d:08:3e:70:c9:9e  ....9].N....>p..
00000060  5e:5b:fe:8b:b0:b3:47:6d:4d:50:a3:cd:d5:1e:0a:6e  ^[....GmMP.....n
00000070  45:ee:b0:e3:32:25:64:9d:fe:3d:92:20:77:0e:93:57  E...2%d..=. w..W
00000080  bd:6a:f9:a4:e5:bf:94:4a:22:a8:f1:38:01:a7:62:38  .j.....J"..8..b8
00000090  72:6d:19:5f:9b:57:2c:ae:e4:e4:ca:58:b1:96:f2:7f  rm._.W,....X....
000000a0  15:99:b3:5f:14:69:4a:c9:d6:be:c8:5f:20:c3:c2:7b  ..._.iJ...._ ..{
000000b0  bb:89:30:45:2d:32:99:d9:ef:f0:13:70:0e:fc:85:d8  ..0E-2.....p....
000000c0  1e:ef:f9:f2:6f:d0:28:8e:3a:34:2f:47:d7:bd:24:cc  ....o.(.:4/G..$.
000000d0  e5:22:ce:15:89:56:e7:d7:cf:a3:22:a2:bf:5a:17:48  ."...V...."..Z.H
000000e0  82:16:33:59:76:cf:95:74:20:46:b5:5f:42:08:a3:f2  ..3Yv..t F._B...
000000f0  a9:b1:da:04:14:84:e1:09:44:ad:f7:c3:fa:d2:0e:04  ........D.......
00000100  d9:7a:ee:72:d4:29:da:40:d0:a0:5c:91:69:7d:03:3a  .z.r.).@..\.i}.:
00000110  9e:bc:ab:18:2d:36:88:bc:e5:00:00:00:80:70:b7:3e  ....-6.......p.>
00000120  28:e2:55:60:b7:e0:22:34:ce:e3:4b:0b:ee:d8:de:03  (.U`.."4..K.....
00000130  63:76:7a:a2:6d:f3:90:94:d6:cb:be:51:cf:35:68:fa  cvz.m......Q.5h.
00000140  6e:e2:ec:47:ad:dc:42:49:d7:d8:df:2b:6a:04:ea:be  n..G..BI...+j...
00000150  b1:26:f9:f8:4e:cf:a2:b5:05:1a:0d:1c:8b:ae:38:18  .&..N.........8.
00000160  d3:a2:bd:85:e3:0f:84:17:83:71:7a:17:15:53:92:b9  .........qz..S..
00000170  43:92:e6:df:d9:12:3c:f6:fe:2e:d7:20:ae:52:97:af  C.......... .R..
00000180  f2:41:a1:1a:6b:a2:14:9b:75:61:f5:6e:18:e9:56:7d  .A..k...ua.n..V}
00000190  fe:33:11:18:5a:59:96:09:dc:93:86:11:75:00:00:01  .3..ZY......u...
000001a0  0f:00:00:00:07:73:73:68:2d:72:73:61:00:00:01:00  .....ssh-rsa....
000001b0  06:3c:74:fb:89:42:e3:0e:14:7b:4d:95:98:1b:b4:62  ..t..B...{M....b
000001c0  ba:fb:05:ca:59:3a:36:8d:e9:2c:ca:bd:76:1d:b8:1d  ....Y:6..,..v...
000001d0  13:30:95:c6:41:d3:31:e5:a9:78:44:c2:86:d4:36:7f  .0..A.1..xD...6.
000001e0  cc:c9:51:e3:a9:9a:26:5e:f5:42:5b:26:6e:78:a5:4e  ..Q...&^.B[&nx.N
000001f0  8b:88:f5:86:80:07:6d:b2:71:c4:f1:fc:f0:a3:d9:96  ......m.q.......
00000200  a2:60:15:86:b2:43:e2:d4:f8:55:5d:90:a4:cb:97:c7  .`...C...U].....
00000210  e7:a3:a0:71:44:3a:27:d0:09:75:50:56:ab:f7:a5:86  ...qD:'..uPV....
00000220  47:4a:d8:13:49:25:8d:18:7d:ee:71:ec:eb:61:c0:6a  GJ..I%..}.q..a.j
00000230  f8:58:20:e3:bd:6f:5d:54:d8:9c:7c:af:0b:a8:76:9b  .X ..o]T..|...v.
00000240  c6:52:8d:03:1b:73:15:ea:dc:3c:7d:c7:7a:07:fa:c3  .R...s....}.z...
00000250  7b:a7:71:e3:a5:b1:b8:3b:38:ed:e0:aa:47:3a:26:7c  {.q....;8...G:&|
00000260  ce:31:93:cb:75:84:68:53:92:8c:2e:3b:09:fc:e0:72  .1..u.hS...;...r
00000270  5f:7a:1d:88:c1:de:cb:b0:87:a9:3c:1d:d5:d5:76:92  _z............v.
00000280  f6:d5:8c:3d:38:5e:2a:c9:d0:aa:01:92:23:20:5e:74  ...=8^*.....# ^t
00000290  0f:6b:0b:85:fb:04:a9:60:2a:cf:c6:06:3b:da:c7:61  .k.....`*...;..a
000002a0  10:8f:ee:77:fa:1e:26:eb:cc:41:29:81:7b:2b:75:05  ...w..&..A).{+u.

-> NET_SSH2_MSG_NEWKEYS (since last: 0.0238, network: 0.0002s)
                                                 

<- NET_SSH2_MSG_NEWKEYS (since last: 0.0003, network: 0.0001s)
                                                 

-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0021, network: 0s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.486, network: 0.4857s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0009, network: 0.0003s)
00000000  00:00:00:08:75:73:65:72:6e:61:6d:65:00:00:00:0e  ....username....
00000010  73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f:6e:00:00  ssh-connection..
00000020  00:08:70:61:73:73:77:6f:72:64:00:00:00:00:08:70  ..password.....p
00000030  61:73:73:77:6f:72:64                             assword

<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.3914, network: 0.3911s)
`

**Comment by terrafrost** [comment]
When you say "otherwise in successful call" do you mean that this an intermittent problem? ie. sometimes you're able to connect to the server and sometimes you're not? Or is the successful call on a completely different server all together?

Working under the assumption that you mean the latter then try doing `$ssh->sendIdentificationStringLast()` after you create the `$ssh` object but before you try to login.

phpseclib, by default, lets the server send first but maybe it'd work better for you / this server if it didn't do that

**Comment by malohtie** [comment]
yes as you said, it an intermittent problem in the same server, sometimes work normal and execute the command sometimes no throw the exception telling me that the connection is closed

**Comment by terrafrost** [comment]
Well hopefully `$ssh->sendIdentificationStringLast()` will fix the issue for you! Like I said, do that before you do `$ssh->login()`. If it doesn't fix the issue for you lmk!

**Comment by malohtie** [comment]
unfortunately this didn't fix my problem :/

**Comment by terrafrost** [comment]
Try to use this SSH2.php:

https://github.com/terrafrost/phpseclib/blob/malohtie/phpseclib/Net/SSH2.php

That SSH2.php will _not_ fix the problem but hopefully (once you post the output) it'll give me enough info to tell you, for sure, what's happening.

Thanks!

**Comment by malohtie** [comment]
hi again, thanks for your efforts and time ^^

![image](https://user-images.githubusercontent.com/20033279/69008110-ec988280-0946-11ea-844a-f126cb2e95b1.png)


here's when the result is good :

```
sending identification string first
.#data = SSH-2.0-OpenSSH_5.3

data2= U1NILTIuMC1PcGVuU1NIXzUuMw0K
```

![image](https://user-images.githubusercontent.com/20033279/69008123-10f45f00-0947-11ea-8a1a-65bb69fe5520.png)



and this one when the problem occure 

```
sending identification string first
.#data = 

data2= Cg==
```
![image](https://user-images.githubusercontent.com/20033279/69008151-66307080-0947-11ea-9dba-42619e8e7b1a.png)

**Comment by terrafrost** [comment]
I guess I dropped the ball on this altho, in my defense, at the time this exchange was taking place I was vacationing in Egypt (which is pretty far away from where I live in Texas).

Due to how old this is I don't see a lot of point in responding so imma close this.
