### ISSUE TITLE
PHP 7.4. combatibility

### ISSUE THREAD

**Issue by dpauli** [phpseclib/phpseclib#1449]
I found a little problem with a not working PHP 7.4 combatibility:
- `fread` returns a `false` on problem (not a `''` anymore), see:
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Crypt/Random.php#L100
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/System/SSH/Agent.php#L163
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/System/SSH/Agent.php#L171
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/System/SSH/Agent.php#L173
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/System/SSH/Agent.php#L176
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/System/SSH/Agent.php#L305
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/System/SSH/Agent.php#L307
-- https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/System/SSH/Agent/Identity.php#L193

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/c2be7e648060fc373381f16509c2c7aea8728a57 should fix this - thanks!
