### ISSUE TITLE
Modifying Random.php

### ISSUE THREAD

**Issue by JamalAkram89** [phpseclib/phpseclib#1451]
Hi Guys!
I am using this library with a php framework that doesn't allow native php session functions, hence causing a problem when phpseclib tries to generate random string. The code tries to set the seed by backing up current session, generating new session and then once the seed is set, it resets the old session. 

My question is, is it safe/ok if i comment out the part where is backs up old session and generates the new session. Will the seed generation still be safe enough.

Thanks & Regards
Jamal Akram

**Comment by terrafrost** [comment]
What version of phpseclib are you running? What version of PHP? Can you share with me your `phpinfo()`?

**Comment by JamalAkram89** [comment]
I am using phpseclib 2.0.23. 
PHP verision is 5.6.38.
Since I am using it with Oracle Service Cloud, we can't get Oracle to enable any features/modules/extensions that they have disabled.

PHPINFO():
![image](https://user-images.githubusercontent.com/60900590/74255945-a1c9a500-4cc0-11ea-8d44-4080ef49feac.png)

**Comment by NiklasBr** [comment]
@JamalAkram89 Are you using Composer to install this package, then maybe [this might be something ](https://stackoverflow.com/questions/28104574/strategy-to-override-a-class-in-a-library-installed-with-composer)for you?

It could potentially work, just copy the Random.php class to your own code directory, rename the namespace, use some other decent seed and override in composer.json.

Alternatively, create a patch with a different seed than the session, save the file and use [Composer Patches](/cweagans/composer-patches). Thinking about it that might be easier than my first suggestion. :)

**Comment by JamalAkram89** [comment]
@NiklasBr I am not using composer. I just copied the phpseclib files to my site and loaded them to my controller. See attached my modified random.php file which is currently working. Not sure if that would generate a decent seed or not.

[Random.zip](https://github.com/phpseclib/phpseclib/files/4188030/Random.zip)

**Comment by terrafrost** [comment]
Oh wow that's a restrictive system.

So I guess not even /dev/urandom is available to read.

The `$_SESSION` stuff is intended to maximize entropy. Depending on what you're doing you may have other acceptable sources of entropy. phpBB 2.0.x kinda persisted entropy using the DB:

https://github.com/phpbb/phpbb/blob/2.0.x/phpBB/includes/functions.php#L149

It's not immediately obvious what the differences are between your changes and the one that is included with phpseclib. Could you provide a diff? Maybe I can do a diff on my own later, as time permits.

**Comment by JamalAkram89** [comment]
Yep, you are right. urandom is also unavailable. 
I am using this library to sign SAML requests before sending out to IdP.  I was able successfully sign and verify the signature after my changes. The thing i am concerned is if my changes will compromise the security or not. Please see the difference below. 

My changes are on left. 
![image](https://user-images.githubusercontent.com/60900590/74856738-9ace1280-5310-11ea-9864-14e79f01c4a8.png)

**Comment by terrafrost** [comment]
> The thing i am concerned is if my changes will compromise the security or not.

Yes, but a more relevant question is: how much will the changes impact security - not whether it'll impact it at all. And as for how much...  that's harder to say, without a full system examination.

Certainly it'll be more predictable but how much more predictable? If `$_SERVER` had a key that had, as it's value, the first 128 bytes of /dev/urandom, it would be more secure then it'd otherwise but but, at the same time, I've never seen a PHP server that behaved that way. As such it seems, superficially, like it's safe to assume that yours doesn't behave that way, either, but yours is already behaving in unusual ways, so who knows...
