### ISSUE TITLE
Slow uploads on SFTP

### ISSUE THREAD

**Issue by MatisiekPL** [phpseclib/phpseclib#1455]
Hello.
I'm experiencing low upload speed, while download speed is very OK. 
I've installed mcrypt.
What should I do to increase the speed of uploads?
Thanks, Matt

**Comment by terrafrost** [comment]
What version of phpseclib are you using?

If you're using the new 2.0.24 that I released last night then there's this new change in that version:

https://github.com/phpseclib/phpseclib/commit/333e2e4c2bb1e50e698be57f601cb08260705654#commitcomment-36576462

I'm kinda wondering if that could be causing you issues. If it is then the following will revert you back to the last version (2.0.23):

```
composer require phpseclib/phpseclib:"~2.0, !=2.0.24"
```
lmk if that works for you and if so then I'll consider doing a new release that doesn't have that change in it.

Thanks!

**Comment by BBrunekreeft** [comment]
I experienced the exact same problem. Downgrading to 2.0.23 resolved the speed problems.

**Comment by BBrunekreeft** [comment]
I can confirm that there are no speed issues with version 2.0.25.
Thanks!

**Comment by terrafrost** [comment]
Thanks!

I want to make another commit in an attempt to speed uploads up tonight. Maybe y'all can test it out?

I tested it with a 1GB file and it was able to upload it to localhost in 17s whereas without any changes it took 30s.

With the #1425 -inspired changes I probably did a 100MB file when I was testing them. It seemed to hang when I uploaded a 1GB file with those changes last night.

Thanks!

**Comment by BBrunekreeft** [comment]
I'll be happy to test it out.

**Comment by terrafrost** [comment]
Try this:

1.0 branch: https://github.com/terrafrost/phpseclib/tree/1.0-speed-up-uploads
2.0 branch: https://github.com/terrafrost/phpseclib/tree/2.0-speed-up-uploads
3.0 branch: https://github.com/terrafrost/phpseclib/tree/3.0-speed-up-uploads
master branch: https://github.com/terrafrost/phpseclib/tree/master-speed-up-uploads

**Comment by terrafrost** [comment]
I've gone ahead and merged this. If there are further speed issues create another ticket.

Thanks!
