### ISSUE TITLE
Error loading a wrong certificate with PHP 7.4

### ISSUE THREAD

**Issue by jjanvier** [phpseclib/phpseclib#1456]
With PHP 7.4 and phpseclib 2.0.24, we encounter the following problem:

```
Trying to access array offset on value of type bool in  /srv/pim/vendor/phpseclib/phpseclib/phpseclib/File/ASN1.php line 534
```

This error comes from one of our test (`it_adds_a_violation_if_the_certificate_is_wrongly_formatted`) that triggers underneath this code:

```
    if (!$this->x509->loadX509('a string to represent a wrongly formatted certificate')) {
            $this->context
                ->buildViolation($constraint->invalidMessage)
                ->addViolation()
            ;

            return;
        }
```

The method `ASN1::asn1map` receives `false` as value for `$decoded`. Which then makes the method crash on line [534](https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/File/ASN1.php#L534). 
This comes from `X509::loadX509` where the method `decodeBER` returns `[0 => false]`. See [here](https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/File/X509.php#L1500).

Sadly, I can't propose a fix as I don't really get what's going on here.

**Comment by terrafrost** [comment]
Can you provide a copy of the certificate that's causing the issue? This will enable me to implement a fix and to then include a unit test for it.

Thanks!

**Comment by jjanvier** [comment]
The problem occurs when it's not a certificate that is provided, but a "random" string instead. For instance `a string to represent a wrongly formatted certificate` like in my example.

I'd rather have a real "business" exception thrown than this PHP error. Or maybe there is way to validate that a string is a certificate before calling `this->x509->loadX509($certificate)`?

**Comment by terrafrost** [comment]
As an update to this...  I'm able to reproduce the issue. I'll try to have a fix in place this weekend.

Thanks!

**Comment by jjanvier** [comment]
Thank you very much @terrafrost !

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/fc0832ae99b13ce34ceb45f1125927a5d632288c should fix this.

The commit immediately before that one has a unit test for this.

Thanks!

**Comment by jjanvier** [comment]
Thank you very much!

**Comment by jjanvier** [comment]
Hello @terrafrost 

Will this bug fix be available with the next 2.0.26? And if yes, do you have an ETA for it?

**Comment by terrafrost** [comment]
> Will this bug fix be available with the next 2.0.26?

Yes.

> And if yes, do you have an ETA for it?

I'll try to do it this week.

Thanks!

**Comment by jjanvier** [comment]
Perfect, thank you very much :1st_place_medal:

**Comment by terrafrost** [comment]
> Perfect, thank you very much 🥇

2.0.26 has been released - thanks!
