### ISSUE TITLE
Secure Connection Failed

### ISSUE THREAD

**Issue by RobDelafontaine** [phpseclib/phpseclib#1458]
Hello,

I'm sorry to bother you. I have an issue, which in all probability is due to some oversight or error on my side. Anyhow, this is the problem.
I'm running some php code in a vhost on my local apache server. I'm trying to connect to a remote server, get a file, and copy it back to my local server.
For the moment, I'm doing this:

```
$ssh = new Net_SSH2('ssh.remote_server.com', 22);
$key = new Crypt_RSA();
$key->loadKey(file_get_contents('../id_rsa'));
if (!$ssh->login('username', $key)) {
exit('Login Failed');} 
```

But the connection fails.
When I forward to port 22, I get a Firefox error page saying "Secure Connection Failed, An error occurred during a connection to vhost.localhost.
When I forward from a random port 3011 to 22, I get a php error saying "Notice: Cannot connect to ssh.remoteserver.com:3011. Error 60. Operation timed out in /phpseclib/Net/SSH2.php on line 1187 - Login Failed".

In the terminal, I tested ssh -v connections to both the remote server and vhost.localhost. No problems there.
I checked if port22 is truely open, and it is.

However, on vhost.localhost I'm using an ssl certificate, signed by my own CA. Could that be the problem ?  I have imported the CA in Firefox, and this works well in standard use, meaning Firefox accepts the local certificates and gives me https access to localhost.

Any suggestions ? All help appreciated.

**Comment by RobDelafontaine** [comment]
Well, after studying this for most of the day, I think it boils down to one question, how can I make phpseclib trust my self-signed CA cert ?

**Comment by terrafrost** [comment]
> When I forward to port 22, I get a Firefox error page saying "Secure Connection Failed, An error occurred during a connection to vhost.localhost.

A Google search for that error doesn't reveal a ton of info. It's not a phpseclib error. Maybe post a screen shot of the error so I can put some more context to it?

> When I forward from a random port 3011 to 22, I get a php error saying "Notice: Cannot connect to ssh.remoteserver.com:3011. Error 60. Operation timed out in /phpseclib/Net/SSH2.php on line 1187 - Login Failed".

Sounds like that's the expected behavior?

> However, on vhost.localhost I'm using an ssl certificate, signed by my own CA. Could that be the problem ? I have imported the CA in Firefox, and this works well in standard use, meaning Firefox accepts the local certificates and gives me https access to localhost.

I have a self-signed cert as well that I'm using as a CA. Generated it with phpseclib actually lol. But no - if that was causing problems that wouldn't cause problems with _just_ connecting to an SSH server with PHP - that'd cause problems with any and all PHP calls.

> how can I make phpseclib trust my self-signed CA cert ?

If you're trying to connect to an SSH server with PHP then a browser-initiated PHP page load isn't going to care if you're using a self-signed CA cert or not...

**Comment by RobDelafontaine** [comment]
Thanks for replying. Added a screenshot of the error-page. 
![SecureConnectionFailed](https://user-images.githubusercontent.com/59472576/75755742-8554e180-5d2f-11ea-945a-9ff3878ec7ba.jpeg)

When I do this...
```
$ssh = new Net_SSH2('ssh.remote_server.com', 22);
$key = new Crypt_RSA();
$key->loadKey(file_get_contents('../id_rsa'));
print_r($key);
```
...I get a series of arrays with data, which means at least the key gets read in. 

This `echo $ssh->getLog();` doesn't help me, because the error-page is served before it gets to the log.

**Comment by RobDelafontaine** [comment]
Sorry for being stubborn. I tried to run my phpseclib code from the terminal. This gave me the following error:

> Illegal instruction: 4

Which makes me think something is wrong with apache. Checking error logs for the virtual host gave me this: 

> [core:notice] [pid 84] AH00052: child pid 1033 exit signal Illegal instruction (4)

I'm on High Sierra, openssl version is 1.0.2k.

**Comment by terrafrost** [comment]
Sorry for not responding sooner - I've been at a conference for the past few days and trying to squeeze work stuff in my free time.

Anyway, did you figure this out?

```php
if ($handle = opendir('ftp://username:password@remote_server.com/some-dir', $ctx)) {
```
That's FTPS - not SFTP FWIW. Not that connecting to an FTPS server should crash phpseclib.

> Sorry for being stubborn. I tried to run my phpseclib code from the terminal. This gave me the following error: ... Which makes me think something is wrong with apache. Checking error logs for the virtual host gave me this:

Running it from the terminal wouldn't invoke Apache. Altho Google'ing your error I see https://stackoverflow.com/a/14285922/569976 . I feel like the issue might be with your PHP binaries..

**Comment by RobDelafontaine** [comment]
> Sorry for not responding sooner - I've been at a conference for the past few days and trying to squeeze work stuff in my free time.

No problem whatsoever. I do understand this is not an issue with phpseclib, but rather some misconfiguration on my side. And I can’t expect you to debug each and every apache install. That’s why I closed the issue.

> Anyway, did you figure this out?

Not yet, but it’s only a matter of time.

Bye now,
Rob
