### ISSUE TITLE
Add ctime

### ISSUE THREAD

**Issue by anotherdevs** [phpseclib/phpseclib#1464]
Hi

Is it possible to add ctime?

From what I can tell: https://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-7.1 the ctime is supported by the protocol.

**Comment by terrafrost** [comment]
phpseclib implements [SFTPv3](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-5) - ctime wasn't added until [SFTPv4](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-03#section-5.1).

The IETF Draft you cited discusses SFTPv6.

I want to add support for SFTPv4-6 at some point but it hasn't been a particularly high priority.

**Comment by anotherdevs** [comment]
Hi @terrafrost 

Understandable. Thank you for considering it.

Should we keep this open as to track SFTPv6 implementation?

**Comment by terrafrost** [comment]
> Should we keep this open as to track SFTPv6 implementation?

It's already on my radar but atm the priority is fairly low (it's been on my radar for years lol)

A ticket to keep track of it is fine by me but imho it should be a new ticket as the description for this one doesn't immediately scream out to me "SFTPv6!" lol.
