### ISSUE TITLE
Parallel connections?

### ISSUE THREAD

**Issue by mikerow** [phpseclib/phpseclib#1470]
Is there (or is planned) a way to make multiple calls in parallel?

For example, can I connect via SSH and send/receive to multiple hosts at the same time? Avoiding to wait to end the communication with one node to call the next one?

**Comment by terrafrost** [comment]
Right now you have two possibilities.

1. Use `$ssh->exec()` with `nohup`.
2. Use `$ssh->read()` / `$ssh->write()`. eg.
   ```php
   $ssh->setTimeout(5);
   $ssh->read('prompt]');
   $ssh->write("ping 127.0.0.1\n");

   $start = microtime(true);
   echo $ssh->read();
   $elapsed = microtime(true) - $start;
   echo "took $elapsed seconds\n";

   $start = microtime(true);
   echo $ssh->read();
   $elapsed = microtime(true) - $start;
   echo "took $elapsed seconds\n";
   ```
   As can be seen by running that last command the output of ping picks up from where it left off with the second `$ssh->read()` call.

Beyond that...  I've had a few thoughts as elaborated at https://github.com/phpseclib/phpseclib/issues/479#issuecomment-61917716 and https://github.com/phpseclib/phpseclib/issues/1071#issuecomment-391596953 for example. I've also thought about doing https://www.php.net/curl-multi-exec or making use of coroutines / promises but none of that is currently supported however.

**Comment by mikerow** [comment]
Thank you for your answer, I appreciate.
