### ISSUE TITLE
Uninitialized string offset when _realpath is empty in Net\SFTP.php

### ISSUE THREAD

**Issue by mnewnham** [phpseclib/phpseclib#1474]
phpseclib version 2.0.27
program NET\SFTP.php
function _realpath

### Issue
if empty value is passed to _realpath as the value of $path, the following error is generated:

````
uninitialized string offset: 0, line 722
````
### Solution
Change line 722 from
````php
if ($path[0] != '/') {
````
to
````php
if ($path && $path[0] != '/') {
````

**Comment by terrafrost** [comment]
With your proposed changes `$sftp->realpath('')` would return `/`. It's not immediately obvious what it _ought_ to return but my gut says that it'd be better if it returned the same thing that `$sftp->realpath('.')` returned? This could be faciliated by doing `if (!strlen($path) || $path[0] != '/') {` or `if (!$path || $path[0] != '/') {`.

Do you have any strong opinion on `/` or `$sftp->realpath('.')` ?

**Comment by mnewnham** [comment]
I have no real opinion on this as I simply don't know enough on the subject. The fix was the one I applied to make the problem go away and to not change any paths in my own use case

**Comment by terrafrost** [comment]
https://www.php.net/realpath treats `''` and `'.'` the same way so I went ahead and went with that route:

https://github.com/phpseclib/phpseclib/commit/a07f5bc6a27519df2d227f7b2ba6c5ec6813f280
