### ISSUE TITLE
Use dynamic object

### ISSUE THREAD

**Issue by luafa** [phpseclib/phpseclib#1482]
I try to use $ssh connection anywhere;
but I got this
```
PHP Warning:  Use of undefined constant NET_SSH2_MSG_CHANNEL_OPEN - assumed 'NET_SSH2_MSG_CHANNEL_OPEN' (this will throw an Error in a future version of PHP) in /home/team/public_html/tab/Net/SSH2.php on line 2744
PHP Notice:  Connection closed prematurely in /home/team/public_html/tab/Net/SSH2.php on line 3951
PHP Warning:  Use of undefined constant NET_SSH2_DISCONNECT_BY_APPLICATION - assumed 'NET_SSH2_DISCONNECT_BY_APPLICATION' (this will throw an Error in a future version of PHP) in /home/team/public_html/tab/Net/SSH2.php on line 3203
```
and I used this code!
```
file_put_contents("sessions", serialize($ssh));
$ssh = unserialize(file_get_contents("sessions"));
```
PHP version 7.2
Phpseclib 1.0.18

there is no way to use $ssh anywhere I liked?

**Comment by terrafrost** [comment]
That's not a use case I've ever really considered.

To make that work I'd have to use [__sleep() / __wakeup()](https://www.php.net/manual/en/language.oop5.magic.php#object.sleep) or [Serializable](https://www.php.net/manual/en/class.serializable.php).

fsockopen would need to be called, again.

Some things might not work as expected. Interactive sessions would need to be restarted, for example. eg. if you did `$ssh->write("vim\n");` you'd need to redo that yourself. I mean, I guess phpseclib could retain a log of commands and replay them BUT...  what if vim wasn't installed the first time around and _was_ installed the second time around? At that point the behavior would be different..

Anyway, I'll see what I can whip up, if it's not too much effort!
