### ISSUE TITLE
SFTP Connection unable to connect as of 2.0.26

### ISSUE THREAD

**Issue by aditkosel** [phpseclib/phpseclib#1488]
We discovered, that one client was no longer able to connect to an sftp server.
Originally the client did not specify a timeout, then it waits forever, with a timeout it does terminate but not successfully connect.
Both scenarios did work with 2.0.25

I tried to create a log file, but unfortunately it does not provide any details on this issue.
I assume, that this is related to the fix for this issue: https://github.com/phpseclib/phpseclib/issues/1454

**Comment by terrafrost** [comment]
> I tried to create a log file, but unfortunately it does not provide any details on this issue.

I'd probably be a better judge of that then you lol. Could you post the logs?

If you could also post the 2.0.25 logs that'd be cool.

Thanks!

**Comment by aditkosel** [comment]
All the logs said lastly was that a connection was closed, but there is nothing documenting that it is hanging in a wating loop.
It looks like that:

<- NET_SSH2_MSG_USERAUTH_SUCCESS (since last: 0.0267, network: 0.0266s)
                                                 

-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0002, network: 0s)
00000000  00:00:00:07:73:65:73:73:69:6f:6e:00:00:01:00:7f  ....session.....
00000010  ff:ff:ff:00:00:40:00                             .....@.

<- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0242, network: 0s)
00000000  00:00:01:00:00:00:00:00:00:01:00:00:00:00:80:00  ................

-> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s)
00000000  00:00:00:00:00:00:00:09:73:75:62:73:79:73:74:65  ........subsyste
00000010  6d:01:00:00:00:04:73:66:74:70                    m.....sftp

<- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0242, network: 0s)
00000000  00:00:01:00                                      ....

-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0002, network: 0s)
00000000  00:00:00:00:00:00:00:09:00:00:00:05:01:00:00:00  ................
00000010  03                                               .

<- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.0243, network: 0.0001s)
00000000  00:00:01:00:00:00:00:00                          ........

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0665, network: 0.0665s)
00000000  00:00:01:00:00:00:00:09:00:00:00:05:02:00:00:00  ................
00000010  03                                               .

-> NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0001, network: 0s)
00000000  00:00:00:00:00:00:00:0e:00:00:00:0a:10:00:00:00  ................
00000010  01:00:00:00:01:2e                                ......

<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0247, network: 0.0001s)
00000000  00:00:01:00:00:00:00:1b:00:00:00:17:68:00:00:00  ............h...
00000010  01:00:00:00:01:00:00:00:01:2f:00:00:00:01:2f:00  ........./..../.
00000020  00:00:00                                         ...

-> NET_SSH2_MSG_DISCONNECT (since last: 0.0003, network: 0s)
00000000  00:00:00:0b:00:00:00:00:00:00:00:00              ............

What might be important here is that it did not happen on all connection attempts, so some connections have been made, but later in the process some fail.

**Comment by terrafrost** [comment]
So it's sending a SSH_FXP_REALPATH packet, trying to get the fully qualified path for ., and then it's getting a SSH_FXP_NAME packet back saying that the fully qualified path is /.

Can you post the sequence of commands that you're issuing that causes it to behave this way?

Also, can you post the 2.0.25 logs, since you said it worked with them and so that I might see what 2.0.25 is doing that 2.0.26 isn't?

Thanks!

**Comment by aditkosel** [comment]
What it was trying to do is logging in.
What might be relevant here is that the context of this operation is in a way that users trigger multiple steps, where each is logging in, doing some things (in this scenario, each was downloading a file if it exists), and logging out again.
The issue was not happening on every login attempt, maybe never on the first attempt, currently not sure about that.
However here is a log file where it was working:
[ssh2_2.0.25.log](https://github.com/phpseclib/phpseclib/files/4901708/ssh2_2.0.25.log)
I redacted the content of the files transferred in this.

**Comment by aditkosel** [comment]
I received a log file from the customers server, which might help you track down the response from the other side.
[redacted_sftp.log](https://github.com/phpseclib/phpseclib/files/4912259/redacted_sftp.log)

**Comment by terrafrost** [comment]
Are the logs from the customer server with 2.0.25 or 2.0.26?

Anyway, I have a few ideas on how to diagnose this further (not how to fix it), but, per your hypothesis, what happens if you undo this change?:

https://github.com/phpseclib/phpseclib/commit/95d189ca72040ab4972886c616e881b739b180e5

Does it work then?

If so then (1) my guess would be that that server can't be logged into with PuTTY (since that change made phpseclib's behavior more consistent with PuTTY's) or WinSCP (since that uses PuTTY) and (2) what's the server signature? If I know that I can make phpseclib behave differently for SSH-2.0-coreftp or whatever the server signature is.

Thanks!

**Comment by aditkosel** [comment]
I assume, that this log contains some of both, you might want to match timestamps from both ends to see what happens.
I also tested with the requested change and it worked.
How might I get the signature?

**Comment by terrafrost** [comment]
> How might I get the signature?

`echo $ssh->getServerIdentification();` should do it!

**Comment by aditkosel** [comment]
The server's signature is "SSH-2.0-CoreFTP-0.3.3".

Thanks for your help!

**Comment by terrafrost** [comment]
Try https://github.com/phpseclib/phpseclib/commit/c7d7b36018e13d034a74f2416ce1dcd247bda3ec
