### ISSUE TITLE
base 16 two's complement negative incorrect

### ISSUE THREAD

**Issue by unstoppablecarl** [phpseclib/phpseclib#1489]
I just came across this case:

```
$hex = 'f6';
$num = new BigInteger($hex, -16);
$num->is_negative // false
$num->toString() // '-10'
$num->value // -10
```
Seems like `$num->is_negative` should be true? or am I missing something about two's complement hex?

Is this a better way to check if the number is negative? `$num->toString()[0] === '-';`

**Comment by terrafrost** [comment]
`$num->is_negative` should be seen as a private variable. Indeed, in 3.0, it is a private variable:

https://github.com/phpseclib/phpseclib/blob/e2fa9f3925a0686d56403a47ec8ef7e95f956098/phpseclib/Math/BigInteger/Engines/Engine.php#L45

For the GMP / BCMath engines `$num->is_negative` isn't even used:

https://github.com/phpseclib/phpseclib/blob/d1ca58cf33cb21046d702ae3a7b14fdacd9f3260/phpseclib/Math/BigInteger.php#L419-L430

In the 3.0 branch it's kinda used for passing data between the parent object and the child one but then it's reset.

Anyway, I'd say that the best way to see if it's negative is to do `$num->compare(new BigInteger()) < 0`. ie. `$num < 0`.

Your method works, too, but, depending on the engine being used, the conversion from the internal representation to decimal could result in unneeded CPU cycles being utilized.

**Comment by unstoppablecarl** [comment]
@terrafrost if I am only using the BigInteger class should I be using 3.0 branch?

**Comment by terrafrost** [comment]
Up to you!

Any of them should work! Altho since I haven't actually tagged a 3.0.0 version, yet, the 3.0 branch could make it harder for end users to install a library you're writing (if that's what you're developing), depending on their minimum-stability settings in composer.json.
