### ISSUE TITLE
Cannot connect with Password protected RSA private key

### ISSUE THREAD

**Issue by rafaeldsousa** [phpseclib/phpseclib#1490]
I'm trying to connect to a remote SFTP server using a private RSA (_PRIVATE_FORMAT_OPENSSH_) key, which is password protected but the connection is never stablished. Debugging it, it seems that the connection isn't ever attempted as the key modulus isn't loaded.
This happens for both 2.0.25 version and 2.0.27

```php
/**
     * Attempts to connect to server
     *
     * @return void
     */
    public function connect(): void
    {
        if (!$this->canExecute()) {
            $private_key = file_get_contents($this->ssh_auth_key);
            $key = new RSA();
            $key->setPassword($this->ssh_auth_pwd);
            $key->loadKey($private_key);

            //Remote server's ip address or hostname
            $this->connection = new SFTP($this->ssh_host);

            if (!$this->connection->login($this->ssh_auth_user, $key)) {
                SFTPErrorHandler::logError($this->connection, SFTPErrorHandler::AUTHERROR);
            }
        }
    }
```
Debugging it step by step I get to `_parseKey()` line [1484](https://github.com/phpseclib/phpseclib/blob/c18159618ed7cd7ff721ac1a8fec7860a475d2f0/phpseclib/Crypt/RSA.php#L1484) (_in this case `$options` is equals to **_aes256-ctr bcrypt_**_) on RSA.php file, which check the key options and in this case the key has an encryption, not meeting the criteria for this check. 

After that, and going through a few more checks, I get to `_privatekey_login()` line [2548](https://github.com/phpseclib/phpseclib/blob/c18159618ed7cd7ff721ac1a8fec7860a475d2f0/phpseclib/Net/SSH2.php#L2548) on SSH2.php, which tries to get the publicKey for the private key I'm using, that goes [back to RSA.php](https://github.com/phpseclib/phpseclib/blob/c18159618ed7cd7ff721ac1a8fec7860a475d2f0/phpseclib/Crypt/RSA.php#L1856) which checks if we have ```$this->modules``` loaded and nothing has been loaded, returning false and login process failing prematurely.

If I try login in with a private key that isn't pwd protect the process works just fine.

Could anyone help me bring some light to this, I'm pretty much stuck at this point and don't know what to search for to try and workaround/resolve this issue.

I'm running OpenSSL 1.1.1 on Mac High Sierra

**Comment by terrafrost** [comment]
Encrypted OpenSSH private keys are, sadly, not supported. Based on my experiments, to date, it seems that PHP is just waaay too slow to do the bcrypt-inspired password derivation.

The following comment (from the 3.0 branch) elaborates:

https://github.com/phpseclib/phpseclib/blob/dc6ccb2ad512fad67cc16655c414bbd8da6a3ab1/phpseclib/Crypt/Common/Formats/Keys/OpenSSH.php#L95-L120

Maybe PHP8's JIT will make it more feasible idk.

**Comment by rafaeldsousa** [comment]
Hi @terrafrost that makes total sense. I kept trying my private OpenSSH key and kinda panicked for a moment. But with a suggestion from a work mate I've generate a key using PEM and that worked as expected.
Hopefully PHP8 will get this sorted for this to work there. 

Thanks a lot for your reply.

**Comment by terrafrost** [comment]
Encrypted OpenSSH private keys are now supported as of this commit:

https://github.com/phpseclib/phpseclib/commit/0c8994bbadffd45cd979a1354258b14ec68a025d
