### ISSUE TITLE
Download preserving original creation, modification and access dates

### ISSUE THREAD

**Issue by jomiquel** [phpseclib/phpseclib#1496]
When using the sftp client with the -p parameter, when downloading files they retain the original creation, modification and access dates. Is there a way to achieve the same with that library? I can not find it.

**Comment by terrafrost** [comment]
There is not currently a way to do this. But what if I add two methods, like so?:

- `$sftp->enableDatePreservation()`
- `$sftp->disableDatePreservation()`

**Comment by jomiquel** [comment]
This sounds so nice. Thanks.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/ea653e1b012a71d6a194452421bb9cdef2cab827 should do the trick!
