### ISSUE TITLE
Function mcrypt_list_algorithms() is deprecated

### ISSUE THREAD

**Issue by mark-ambrazhevich-spiral** [phpseclib/phpseclib#1500]
I have the following error "Function mcrypt_list_algorithms() is deprecated".
Environment: docker alpine, php7.2, mcript installed.

I've tried ` $sftp->setCryptoEngine(Base::ENGINE_INTERNAL);` but still at some point it checks every engine and fails with error.

"version": "2.0.28"

**Comment by terrafrost** [comment]
mcrypt is utilized for speed purposes:

https://github.com/phpseclib/phpseclib/issues/1028#issuecomment-242739527

It is weird, tho, that it's trying to call it even tho you're setting the crypto engine to be `Base::ENGINE_INTERNAL`.

What's the line number you're getting the error on?

Thanks!

**Comment by mark-ambrazhevich-spiral** [comment]
I saw that topic, put didn't find the solution there.
This is the stack track
```
·    [0] = string(112) #0 /var/www/stat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4626): phpseclib\Crypt\Base->isValidEngine(2)
·    [1] = string(128) #1 /var/www/stat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1354): phpseclib\Net\SSH2->getSupportedEncryptionAlgorithms()
·    [2] = string(109) #2 /var/www/stat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(1288): phpseclib\Net\SSH2->_key_exchange()
·    [3] = string(104) #3 /var/www/stat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2150): phpseclib\Net\SSH2->_connect()
·    [4] = string(109) #4 /var/www/stat/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(2128): phpseclib\Net\SSH2->_login('username')
·    [5] = string(75) #5 [internal function]: phpseclib\Net\SSH2->login('username', 'pass')
```

**Comment by terrafrost** [comment]
The `mcrypt_list_algorithms` call in `isValidEngine()` has the [error suppression operator](https://www.php.net/manual/en/language.operators.errorcontrol.php) before it so idk how errors are showing up.

Anyway, https://github.com/phpseclib/phpseclib/commit/40b4f1d557d2d466987bf6fc573ea205ecaa35d9 should make it so that `mcrypt_list_algorithms` isn't called when `$sftp->setCryptoEngine(Base::ENGINE_INTERNAL);` is set.

**Comment by ogbofjnr** [comment]
Cool, thank you, waiting for release.
