### ISSUE TITLE
Add stubs for phpseclib

### ISSUE THREAD

**Issue by kesselb** [phpseclib/phpseclib#1505]
Hey!

PHPStorm (and static analysis tools like psalm) are unable to resolve constants like NET_SFTP_HANDLE used by phpseclib because they are defined at runtime: https://github.com/phpseclib/phpseclib/search?q=define_array&unscoped_q=define_array

I sent a patch with stubs to https://github.com/JetBrains/phpstorm-stubs/pull/868 (those stubs are used by phpstrom) but they are not accepting stubs for non php extensions for now :disappointed: 

Is this something we could add here (as code or wiki page)?

**Comment by terrafrost** [comment]
I'll try to take a look at this in the next few days, as time permits.

Thanks!

**Comment by terrafrost** [comment]
I tried to create [phpstorm-phpseclib.zip](https://github.com/phpseclib/phpseclib/files/5057348/phpstorm-phpseclib.zip) based on *Creating External Libraries* instructions at https://blog.jetbrains.com/phpstorm/2018/03/how-to-provide-stubs-for-phpstorm/ . I then tried to add that to PhpStorm using the *Using custom stubs* directions and...  it's not working for me. I get the following error:

> Error
> 
> Fail to load plugin descriptor from file phpstorm-phpseclib.zip

I would say: if you want a plugin create a new repo and if it works for me in PHPStorm I can create a repo in the phpseclib project / team / whatever for the PHPStorm plugin to live. Or if it should be a directory / file within this repo (as opposed to a whole new repo) I guess create a PR that adds a new directory.

**Comment by kesselb** [comment]
Thanks @terrafrost for having a look :+1: 

> I tried to create phpstorm-phpseclib.zip based on Creating External Libraries instructions at https://blog.jetbrains.com/phpstorm/2018/03/how-to-provide-stubs-for-phpstorm/ . I then tried to add that to PhpStorm using the Using custom stubs directions and... it's not working for me. I get the following error:

Made it work :tada: 

1. Create phpseclib.jar file.

```
zip -r phpseclib.jar *
  adding: library/ (stored 0%)
  adding: library/library.php (deflated 20%)
  adding: library/phpseclib/ (stored 0%)
  adding: library/phpseclib/sftp.php (deflated 76%)
  adding: library/phpseclib/ssh2.php (deflated 75%)
  adding: META-INF/ (stored 0%)
  adding: META-INF/plugin.xml (deflated 45%)
```

2. Install plugin from disk 

![image](https://user-images.githubusercontent.com/3902676/89917046-a2ec7800-dbf8-11ea-8d30-6fe40dd4317f.png)

3. Restart PHPStorm


![image](https://user-images.githubusercontent.com/3902676/89917198-ce6f6280-dbf8-11ea-86b9-b88d0e0c0cf8.png)

**Comment by terrafrost** [comment]
So is it auto predicting the constants like you were wanting?

If so then I'll create a repo for this in the next few days!

Not really sure if there's a marketplace for PHPStorm plugins or not where I could add it too idk lol

**Comment by kesselb** [comment]
> So is it auto predicting the constants like you were wanting?

Yes. Works like a charm. 

> If so then I'll create a repo for this in the next few days!

Cool. I'm not sure if we need a PHPStorm plugin. I guess it does not hurt but my use case was psalm where the stub files are enough. We could also start with a wiki page. 

> Not really sure if there's a marketplace for PHPStorm plugins or not where I could add it too idk lol

Yep. There is a store.
