### ISSUE TITLE
API Documentation (generated by Sami)   has been 404

### ISSUE THREAD

**Issue by zs1211** [phpseclib/phpseclib#1506]

**Comment by frasche** [comment]
Use https://api.phpseclib.org/ 
and select the version

**Comment by zs1211** [comment]
> Use https://api.phpseclib.org/
> and select the version

ok . Thanks! I have complete my works.

**Comment by zs1211** [comment]
> Use https://api.phpseclib.org/
> and select the version
 

At the time ，I did not find the "select version" button in the first time,

**Comment by williamdes** [comment]
https://github.com/phpseclib/phpseclib/issues/1365#issuecomment-675320397

**Comment by zs1211** [comment]
> [#1365 (comment)](https://github.com/phpseclib/phpseclib/issues/1365#issuecomment-675320397)
Thanks very much.
