### ISSUE TITLE
SFTP:get() inifinite loop

### ISSUE THREAD

**Issue by biozshock** [phpseclib/phpseclib#1508]
Hello.

Recently after upgrade to php7.4 i have noticed that the SFTP is sometimes stuck on huge amount of files in the infinite loop. I didn't notice any pattern on when and how it fails.
After some digging i found that the issue is in SSH:_get_binary_packet here https://github.com/phpseclib/phpseclib/blob/2.0.27/phpseclib/Net/SSH2.php#L3363

I added some other debug lines, so the stack trace may be one or two lines off.

The stack trace
 at vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3367
 phpseclib\Net\SSH2->_get_binary_packet() at vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3724
 phpseclib\Net\SSH2->_get_channel_packet() at vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:3060
 phpseclib\Net\SFTP->_get_sftp_packet() at vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2252
 phpseclib\Net\SFTP->get() at vendor/league/flysystem-sftp/src/SftpAdapter.php:478
 League\Flysystem\Sftp\SftpAdapter->readStream() at vendor/league/flysystem/src/Filesystem.php:196

The issue is that the socket have less bytes than you expect in the packet length. Dug it by prepending into this code into while loop:

```php
$meta = stream_get_meta_data($this->fsock);

if (isset($meta['unread_bytes']) && $meta['unread_bytes'] == 0) {
    throw new \Exception();
}
```

In addition to that - if i enable the logging into file (which BTW does not work :) ) the issue does not appear. 
Finally got a 4000'ish lines from console with LOG_REALTIME, but not sure that should be public.

Local: Ubuntu 18.04, php7.4.8
Remote SFTP: SSH-2.0-OpenSSH_7.9p1 Debian-10

**Comment by terrafrost** [comment]
> is sometimes stuck on huge amount of files in the infinite loop

So the problem isn't that you're uploading a single huge file but rather that you're uploading a huge amount of individual distinct files?

> Finally got a 4000'ish lines from console with LOG_REALTIME, but not sure that should be public.

Yah - that'd be helpful. You can email them to terrafrost@php.net.

Thanks!

**Comment by biozshock** [comment]
The script uploads all kinds of files - jpegs, zips, mp4 etc. So the size and amount varies from time to time.
Saved log files were sent.

If you want to have any other help - just write me here or by email. Checking on free time though.

**Comment by terrafrost** [comment]
Things start to get a little weird in your log file here:

```
<- NET_SSH2_MSG_CHANNEL_DATA ON BAD (since last: 0.0575, network: 0.0003s)
00000000  00:00:01:00:00:00:40:00:30:f5                    ......@.0.



<-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  37:2e:39:70:31:20:44:65:62:69:61:6e:2d:31:30:0d  7.9p1 Debian-10.
00000020  0a                                               .
```
The whole `NET_SSH2_MSG_CHANNEL_DATA ON BAD` is...  weird. "ON BAD" doesn't even appear as a string in phpseclib. Is that, per chance, an edit you manually made to the file?

Decoding the packet it looks like that's a continuation of the previous SSH_FXP_DATA packet. Here's the first line of that packet:

```
<- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0019, network: 0.0015s)
00000000  00:00:01:00:00:00:40:00:00:00:80:09:67:00:00:00  ......@.....g...
```
00:00:01:00 - recipient channel
00:00:40:00 - data length
00:00:80:09 - SFTP packet length
67 - SFTP packet type (SSH_FXP_DATA)

So the first takeaway from this is that the SFTP packet length exceeds the data length. So it makes sense that the packet following that one (ie. the `NET_SSH2_MSG_CHANNEL_DATA ON BAD` packet) would be a continuation of the previous packet.

If you are manually editing the file could you give me the unedited file?

But then after that there's another issue. The fact that redoing the [protocol version exchange](https://tools.ietf.org/html/rfc4253#section-4.2) makes it seem like the connection timed out (eg. maybe something like a `sleep(1000)` was done on the server hosting the PHP code and phpseclib is trying to reconnect.

**Comment by terrafrost** [comment]
I guess one thing that might help too is you give me SFTP access? If you're willing to do so you can email terrafrost@php.net the connection info.

Thanks!

**Comment by biozshock** [comment]
`NET_SSH2_MSG_CHANNEL_DATA ON BAD` is the record that actually fails inside the while loop. Sorry, forgot to mention that..

**Comment by salmonila** [comment]
Where are the files that you're trying to download? I tried this and didn't
have any issues:

$sftp = new SFTP('push-30.cdn77.com');
$sftp->login('user_mr1kafco', 'rtqSVT9Q7zpc60zRj5Fq');

$files = $sftp->nlist('/www');
foreach ($files as $file) {
    if ($file == '.' || $file == '..') {
        continue;
    }
    $data = $sftp->get('/www/' . $file);
    echo strlen($data) . "\n";
}

echo "all done!";


Thanks!

**Comment by biozshock** [comment]
Looks like the problem is on the server side. The SSH server was cutting the connection (limit on the simultaneous connections) and the job was poorly done, thus cutting the connection in the middle of the transaction.

Sorry for bothering, and thank you for the awesome library!
