### ISSUE TITLE
Add Curve25519 support

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#151]

**Comment by bantu** [comment]
Also see https://github.com/lt/PHP-Curve25519/issues/3#issuecomment-72666184

**Comment by marclaporte** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  marc@laporte.name
    Domain marclaporte.com has exceeded the max emails per hour (303/300 (101%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o4.sgmail.github.com ([192.254.112.99]:33380)
	by uskm12.fastbighost.net with esmtps (TLSv1.2:DHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.84)
	(envelope-from <bounces+848413-0bd8-marc=marclaporte.com@sgmail.github.com>)
	id 1YKrah-002Mz5-1v
	for marc@marclaporte.com; Mon, 09 Feb 2015 18:53:43 +0200
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed; d=github.com; 
	h=from:reply-to:to:in-reply-to:references:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=wH/+z7nrrRTouaKO6mWha6y9ixw=; b=akuCMnHrqhLjnL8V
	1cTifJlMfr93MpAeKKRgRdiz4rCXMwUrk2Vs/z1fgYPCHIzzFAG9itkxaytCnP+C
	HoFlj/0GqUbSw69yD9OxJl6mbs2HWHI+yJai5bG///xob+NZlDiRdDlGph9L+0AO
	Vw6r6wRVay1MLhGRodNCGQ9HaUY=
Received: by filter0292p1mdw1.sendgrid.net with SMTP id filter0292p1mdw1.19968.54D8E60D25
        2015-02-09 16:53:34.46305461 +0000 UTC
Received: from github-smtp2a-ext-cp1-prd.iad.github.net (github-smtp2a-ext-cp1-prd.iad.github.net [192.30.253.16])
	by ismtpd-002 (SG) with ESMTP id 14b6f42a846.a04.16c7a2
	for <marc@marclaporte.com>; Mon, 09 Feb 2015 16:53:34 +0000 (UTC)
Date: Mon, 09 Feb 2015 08:53:34 -0800
