### ISSUE TITLE
Function mcrypt_list_algorithms() is deprecated

### ISSUE THREAD

**Issue by daveime68** [phpseclib/phpseclib#1512]
Trying to establish an SFTP connection with username and password to a remote server using phpseclib v2.

Worked fine on older server running php 5.4.

This server has PHP 7.1.4, and modules mcrypt and openssl are both loaded and show in phpinfo();

But still getting this deprecated warning even though the function isValidEngine($engine) in Crypt/Base.php has the deprecation suppression 

@mcrypt_list_algorithms

How can I force the engine used to the INTERNAL one, even though I know it's going to be slower?

$sftp = new SFTP('mydomain.com');
$connection = @$sftp->login('myusername','mypassword'); // this is where the error is thrown.

How do I specify the engine before establishing the connection, and ensure it's not silently going to change?

**Comment by terrafrost** [comment]
I almost wonder if you're using a [custom error handler](https://stackoverflow.com/a/53957701/569976) that's making this more an issue than it really is.

Anyway, altho I think wantonly taking a speed increase, to avoid these errors, is a bad idea...

In lieu of that you could do `$sftp->setCryptoEngine(Base::ENGINE_INTERNAL)]` before you try to login but this'll work better with the latest git version:

https://github.com/phpseclib/phpseclib/commit/40b4f1d557d2d466987bf6fc573ea205ecaa35d9

**Comment by terrafrost** [comment]
Actually, could you give me SSH access to a server that demonstrates the issue?

I've been getting these tickets for years and idk wtf is up with them. Outside of my custom error handler guess I haven't the foggiest clue why the error suppression operator isn't working and having access to a server that demonstrates the problem could provide some insights!

**Comment by daveime68** [comment]
Unfortunately it's one of my clients servers, so can't give access to anyone.

I tried your $sftp->setCryptoEngine(Base::ENGINE_INTERNAL) suggestion, and if I print_r on the $sftp object, I can see that the [crypto_engine] property is indeed set to 1.

However, still ran into the mcrypt_list_algorithms error, seems like the isValidEngine function is still called regardless to check which engines are potentially available, 

I commented out the MCRYPT portion entirely and just returned true; which prevented the error - but the $connection object is still empty after calling $connection = $sftp->login('myusername','mypassword');

And both the $sftp->getErrors() and $sftp->getSFTPErrors() calls return empty arrays.

I've done ini_set('display_errors', 1); ini_set('display_startup_errors', 1); error_reporting(E_ALL);

I even tried implementing my own custom error handler to see if I could catch anything - it never triggers. I tried wrapping the login function inside a try/catch block, it never throws an exception. The error_log for the domain I'm testing on is also empty.

I dunno, seems like something is failing internally in the library without throwing any error that can be caught or logged.

I'd downgrade to PHP 5.4 if I could, but it's a GoDaddy shared host with only PHP 7 available.

Thanks for your help anyway.

**Comment by terrafrost** [comment]
> However, still ran into the mcrypt_list_algorithms error, seems like the isValidEngine function is still called regardless to check which engines are potentially available,

Was https://github.com/phpseclib/phpseclib/commit/40b4f1d557d2d466987bf6fc573ea205ecaa35d9 in your code?

> And both the $sftp->getErrors() and $sftp->getSFTPErrors() calls return empty arrays.

It's not an SFTP or SSH2 error. It's an deprecation error with the mcrypt_ methods.

> I dunno, seems like something is failing internally in the library without throwing any error that can be caught or logged.

Having a deprecated notice appear doesn't sound like a failure, to me, as I'd use the term. The code still runs, even with those deprecated warnings, does it not? If so then I wouldn't call it a failure. The only question is _why_ they're appearing, even despite the use of the error suppression operator. That operator _should_ suppress errors but it isn't and I have no idea as to why.

**Comment by george-zakharov** [comment]
I'm getting the same error on PHP 7.4.13:
`LEVEL: 8192 (E_DEPRECATED)
FILE:
/vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/SymmetricKey.php
LINE: 2194
TEXT:
Function mcrypt_list_algorithms() is deprecated
`
According to https://www.php.net/manual/en/function.mcrypt-list-algorithms.php:
_This function has been DEPRECATED as of PHP 7.1.0 and REMOVED as of PHP 7.2.0. Relying on this function is highly discouraged._
So I guess, it would be better to replace it.

**Comment by terrafrost** [comment]
@george-zakharov - phpseclib uses (in order): OpenSSL, mcrypt, the pure-PHP engine. If mcrypt is being used it's because OpenSSL isn't available for it to use whereas mcrypt is, so it's using it.  Using mcrypt over the pure-PHP engine is preferred because, even despite being deprecated, it is still _significantly_ faster than the pure-PHP engine. https://github.com/phpseclib/phpseclib/issues/1028#issuecomment-242739527 elaborates.

Error suppression (eg. `@mcrypt_list_algorithms()`)is also used on all the mcrypt functions. If you're getting that error then that means error suppression isn't working for you. I've never been able to figure out why that is but I'm also not going to remove mcrypt because of it, especially in light of the huuuuuge speedups mcrypt provides.

**Comment by george-zakharov** [comment]
> @george-zakharov - phpseclib uses (in order): OpenSSL, mcrypt, the pure-PHP engine. If mcrypt is being used it's because OpenSSL isn't available for it to use whereas mcrypt is, so it's using it. Using mcrypt over the pure-PHP engine is preferred because, even despite being deprecated, it is still _significantly_ faster than the pure-PHP engine. [#1028 (comment)](https://github.com/phpseclib/phpseclib/issues/1028#issuecomment-242739527) elaborates.
> 
> Error suppression (eg. `@mcrypt_list_algorithms()`)is also used on all the mcrypt functions. If you're getting that error then that means error suppression isn't working for you. I've never been able to figure out why that is but I'm also not going to remove mcrypt because of it, especially in light of the huuuuuge speedups mcrypt provides.

Thank you for your fast answering.
I see.
The problem is I do have openssl module enabled, but my system ignores `@`-symbol for bugfix checking.
Anyway, I've got your point of view :)

**Comment by george-zakharov** [comment]
@terrafrost Also it seems that in 7.0, escaping a function with @ does NOT suppress the deprecation warnings.

**Comment by terrafrost** [comment]
> The problem is I do have openssl module enabled

Well it also depends on the encryption algorithm being used. Rijndael with a 256-bit block size is not supported by OpenSSL but it is supported by mcrypt, for example.

>@terrafrost Also it seems that in 7.0, escaping a function with @ does NOT suppress the deprecation warnings.

Seems like it is to me.

Compare the output of https://3v4l.org/qpEeB with https://3v4l.org/7G9Tr . The former shows a deprecation warning for `is_real` on PHP 7.4 while the latter does _not_ show a deprecation warning for `@is_real` on PHP 7.4.

**Comment by terrafrost** [comment]
@george-zakharov - do you, per chance, have a custom error handler?

**Comment by george-zakharov** [comment]
> @george-zakharov - do you, per chance, have a custom error handler?

Yes. I will try to fix it there.
