### ISSUE TITLE
Separate STDERR with "read" doesn't work

### ISSUE THREAD

**Issue by darkelfe14728** [phpseclib/phpseclib#1516]
Hello,

According to [documentation](http://phpseclib.sourceforge.net/ssh/2.0/examples.html), functions "enableQuitMode()" and "getStdError()" works with "read".
In my case, it doesn't : work very well with "exec", but "read" always merge them.

Simple example :
```php
use phpseclib\Crypt\RSA;  
use phpseclib\Net\SSH2;`

require_once __DIR __ . '/vendor/autoload.php';

$key = new RSA();
$key->loadKey(file_get_contents('XXX'));

$ssh = new SSH2('fr13.fidit.com', 22);
$ssh->login('XXX', $key);

$ssh->enableQuietMode();

$ssh->read('/XXX@[a-z0-9_-]+[^%]+[%$]/', SSH2::READ_REGEX);

$ssh->write('ech' . "\n");
echo 'STDOUT : ' . $ssh->read('/XXX@[a-z0-9_-]+[^%]+[%$]/', SSH2::READ_REGEX) . "\n";
echo 'STDERR : ' . $ssh->getStdError() . "\n";

//echo 'STDOUT : ' . $ssh->exec('ech') . "\n";
//echo 'STDERR : ' . var_dump('STDERR', $ssh->getStdError()) . "\n";

$ssh->disconnect();
```

Did I do something wrong ?

**Comment by terrafrost** [comment]
That is strange behavior but PuTTY appears to be behaving in the same way (not using a separate stderr when a TTY is in use, as it would be when `$ssh->read()` is used). I asked about it on stackoverflow here:

https://stackoverflow.com/q/63656823/569976

So I guess we'll see what we see.

As for the documentation...  it says the following:

> By default $ssh->exec() returns both stdout and stderr. To suppress stderr you can call $ssh->enableQuietMode(). To re-enable it call $ssh->disableQuietMode().

It doesn't explicitly say it won't work with a TTY (eg. `$ssh->read()`) but it also doesn't say that will. I can update it to say, explicitly, that those methods don't work with `$ssh->read()` but I'll hold off for a few days to give people a chance to answer the stackoverflow question!

**Comment by darkelfe14728** [comment]
According to post answer, the problem is the remote console, who merge STDOUT and STDERR before transmitting to SSH tunnel. Some aside search indicate the problem can be "solved" by using a specific xterm which don't merge if accessed through SSH on server side.

The conclusion is : it's not a bug relative to phpseclib itself. I think documentation must be updated to say that.
Issue closed
