### ISSUE TITLE
SFTP list updates

### ISSUE THREAD

**Issue by kardianos** [phpseclib/phpseclib#1517]
Hello. When a client attempted to use phpseclib with the Go sftp server library `github.com/pkg/sftp`. What we found is a slight incompatibility. I think the issue is on phpseclib side. After applying the following patch to 2.0.28 release, it seemed to work.

The core issue is that the current code may send many requests for a DIR list, rather then listening for multiple packets after a single READDIR request.

```patch
diff --git a/phpseclib/Net/SFTP.php b/phpseclib/Net/SFTP.php
index 7c821377..3d7c1a4e 100644
--- a/phpseclib/Net/SFTP.php
+++ b/phpseclib/Net/SFTP.php
@@ -941,16 +941,19 @@ class SFTP extends SSH2
 
         $this->_update_stat_cache($dir, array());
 
+        // http://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-8.2.2
+        // why multiple SSH_FXP_READDIR packets would be sent when the response to a single one can span arbitrarily many
+        // SSH_MSG_CHANNEL_DATA messages is not known to me.
+        if (!$this->_send_sftp_packet(NET_SFTP_READDIR, pack('Na*', strlen($handle), $handle))) {
+            return false;
+        }
+
         $contents = array();
         while (true) {
-            // http://tools.ietf.org/html/draft-ietf-secsh-filexfer-13#section-8.2.2
-            // why multiple SSH_FXP_READDIR packets would be sent when the response to a single one can span arbitrarily many
-            // SSH_MSG_CHANNEL_DATA messages is not known to me.
-            if (!$this->_send_sftp_packet(NET_SFTP_READDIR, pack('Na*', strlen($handle), $handle))) {
-                return false;
-            }
-
             $response = $this->_get_sftp_packet();
+            if(!$response) {
+                break;
+            }
             switch ($this->packet_type) {
                 case NET_SFTP_NAME:
                     if (strlen($response) < 4) {
```

**Comment by terrafrost** [comment]
I think it's more likely that https://github.com/pkg/sftp has a buggy implementation.

Quoting [SSH File Transfer Protocol § 6.7 Scanning Directories](https://tools.ietf.org/html/draft-ietf-secsh-filexfer-02#section-6.7),

> The client should call SSH_FXP_READDIR repeatedly until it has found the
>   file it is looking for or until the server responds with a
>   SSH_FXP_STATUS message indicating an error (normally SSH_FX_EOF if
>   there are no more files in the directory).

In all likelihood you'd be unable to list large directories with a client like WinSCP either.

I suppose I could try to reproduce the problem, myself, and then submit a bug report, but idk. I'll mull on it. Maybe you, yourself, could submit a bug report to them, instead?

If https://github.com/pkg/sftp had a larger user base I might be willing to code in an exception specific for it (much like [PuTTY's Bugs panel](https://winscp.net/eng/docs/ui_login_bugs) but based on the watcher / star / fork counts it doesn't seem that big idk lol

**Comment by kardianos** [comment]
@terrafrost You are correct. Not an issue with pkg/sftp, it was a problem with my own code.

I'm sorry for the noise. Thank you for taking time to respond.
