### ISSUE TITLE
SFTP: Unable to authenticate

### ISSUE THREAD

**Issue by ooobii** [phpseclib/phpseclib#1518]
Good morning!! I'm trying to write a PHP script to automatically download a file from an SFTP server via cron job, and I'm having issues authenticating with the SFTP server.

I've tested my credentials on different GUI-based FTP clients (Transmit, FileZilla) with authentication success, but no matter what I try, I can't seem to get phpseclib to successfully authenticate.

Here's the code `index.php` (Executed by PHP 7.3.11 on MacOS Catalina 10.15.6):

```php
<?php
require __DIR__.'/vendor/autoload.php';
use Symfony\Component\Dotenv\Dotenv;
$dotenv = new Dotenv();
$dotenv->load(__DIR__.'/.env');

$args = array(
    'usr'=>$_ENV['SFTP_USER'],
    'pwd'=>$_ENV['SFTP_PASS'],
    'host'=>$_ENV['SFTP_HOST'],
    'port'=>$_ENV['SFTP_PORT'],
    'certpath'=>$_ENV['CRYPT_PRIVATEKEY_PATH'],
    'certpwd'=>$_ENV['CRYPT_PRIVATEKEY_PASS']
);

use phpseclib\Net\SFTP;
use phpseclib\Crypt\RSA;
define('NET_SFTP_LOGGING', SFTP::LOG_COMPLEX);

echo "Begin connection to '".$args['usr']."@".$args['host'].":".$args['port']."'... \n";

// disabled RSA key attempts to help debug connection issues. Issues persist regardless of auth method.
// echo 'Prepare RSA encryption authentication...';
// $privKey = new RSA();
// $privKeyStr = file_get_contents($args['certpath']);
// if(!$privKey->loadkey($privKeyStr)) {
//     echo "ERROR!";
//     exit();
// }
// echo "OK!\n";

echo 'Logging in and shanking hands...';
$sftp = new SFTP($args['host'], $args['port']);
if(!$sftp->login($args['usr'], $args['pwd'])) {
    echo "ERROR!\n\n";
    print_r($sftp->getSFTPErrors());
    echo "\n\n";
} else {
    echo "OK!\n";
    echo "Is Connected: ".$sftp->isConnected()."\n";
    echo "Is Authenticated: ".$sftp->isAuthenticated()."\n\n";

    try {
        echo $sftp->get("/testfile.text");
    } catch (\Throwable $th) {
        echo $th;
    }
}
echo "End of file \n";
```

This script outputs the following:
```
mwendel@Matthew-Wendels-MacBook-Pro php-sftp % php index.php
Begin connection to '[user redacted]@[host redacted]:22'...
Logging in and shanking hands...ERROR!

Array
(
)


End of file
```

I have confirmed that the .env settings are being loaded, and the `$args` object is populated with the same user/pass values from my tests using GUI clients. I'd love to learn more information about what is causing this failure, but it seems as though the built-in logging does not log authentication challenges? Any help or advice would be greatly appreciated! :smile:

**Comment by ooobii** [comment]
Mysteriously, it's working, but i'm not sure what changed.

**Comment by terrafrost** [comment]
Well, normally, I'd suggest sharing the logs with me, either via email or through a link here, or whatever you're comfortable with, but if it's working it's working lol.

One possibility is that maybe the machines you were using the GUI SFTP clients on were different machines than you were using phpseclib on? I ask because sometimes different machines can route differently, have different firewall settings, etc.

**Comment by ooobii** [comment]
Actually, after further investigation, it was a configuration problem with our server and how the user was allowed to authenticate... how embarrassing :sweat_smile: 

Later after posting this, I had found an API doc for phpseclib, and discovered the `isConnected()` and `isAuthenticated()` functions. After seeing them print connected = 1 and authenticated = 0, It turned me to investigate my user's permissions, and *voila!*

In the future, what do you suggest for logging errors? I'm rather new to PHP (coming from .NET and strong-typed languages has proven a challenge, but I love it so far!), and if something like this were to come up in the future, diagnosing myself it would be extremely helpful. I had used the `define('NET_SFTP_LOGGING', SFTP::LOG_COMPLEX);` statement, but didn't know where to look for it's output.

**Comment by terrafrost** [comment]
tbh idk that `define('NET_SFTP_LOGGING', SFTP::LOG_COMPLEX);` is really gonna be useful for anyone but me lol. For me it's _super_ useful. Way more than the verbose logs OpenSSH gives you.

There's `$ssh->getErrors()` and `$ssh->getLastError()` (and `$sftp->getSFTPErrors()`, etc, for SFTP specific errors) but they're only gonna show errors if the SSH / SFTP server reports on them.

It's an area I need to improve upon!
