### ISSUE TITLE
how to generate ECDSA CSR

### ISSUE THREAD

**Issue by afatsoum** [phpseclib/phpseclib#1519]
Since ECDSA is now supported in master branch. Can I get a sample code for loading an ECDSA key and generating a ECDSA CSR from it?

I couldn't find any examples of this anywhere.

If possible I specifically want to be able to specify a commonName and Organization attribute for the subject DN.

Thanks

**Comment by terrafrost** [comment]
I'd suggest using the 3.0 branch - not the master branch.

Anyway...

```php
use phpseclib3\File\X509;
use phpseclib3\Crypt\PublicKeyLoader;

$privKey = $key = PublicKeyLoader::load(file_get_contents('/path/to/key.pem'), $password = false);
$pubKey = $privKey->getPublicKey();

$x509 = new X509();
$x509->setPrivateKey($privKey);
$x509->setDNProp('id-at-organizationName', 'phpseclib demo cert');

$csr = $x509->signCSR();

echo $x509->saveCSR($csr);
```

**Comment by afatsoum** [comment]
@terrafrost I tried to use the 3.0 branch by downloading the files manually but i get the following error

`Fatal error: Uncaught Error: Class 'phpseclib3\Crypt\Common\AsymmetricKey' not found in C:\xampp\htdocs\test\vendor\phpseclib\Crypt\EC.php:58 Stack trace: #0 C:\xampp\htdocs\test\ecc.php(6): include() #1 {main} thrown in C:\xampp\htdocs\test\vendor\phpseclib\Crypt\EC.php on line 58`

I am trying to load the library files like so

```
include('/phpseclib/File/X509.php');
include('/phpseclib/Crypt/PublicKeyLoader.php');
include('/phpseclib/Crypt/EC.php');
include('/phpseclib/Crypt/Common/AsymmetricKey.php');

use phpseclib3\File\X509;
use phpseclib3\Crypt\PublicKeyLoader;
```
I think I am not loading the library properly but not sure how I am supposed to do it.. i tried to download phpseclib 3.0 with composer to get the autoload files but that doesnt work either as it complains 3.0 version doesnt exist.

```
C:\>composer require phpseclib/phpseclib ^3.0

  [InvalidArgumentException]
  Could not find package phpseclib/phpseclib in a version matching 3.0
```

Can you please advise how I am supposed to load the 3.0 branch library properly?

**Comment by afatsoum** [comment]
I solved my problem by installing with composer with the following command using the **dev-master** branch

`composer require phpseclib/phpseclib:dev-master`

**Comment by terrafrost** [comment]
`composer require phpseclib/phpseclib:3.0.x-dev` for 3.0.

The reason I recommend _not_ using master is because master will never have a stable API. Let's say I've started work on 4.0. I'll do the initial work in the master branch. At some point, once I'm committed to the API I'll create the 4.0 branch from master.

So, sure, master works, for now, but will it next year? idk and I will make no guarantees or promises that it will.
