### ISSUE TITLE
Undefined $length in _get_sftp_packet

### ISSUE THREAD

**Issue by ndobromirov** [phpseclib/phpseclib#1526]
There is an uninitialized `$length` variable used in the method in arithmetic context. 
I've found this by accident in `2.0.29` and it seems incorrect.
Close this if it's deemed correct.

https://github.com/phpseclib/phpseclib/blob/497856a8d997f640b4a516062f84228a772a48a8/phpseclib/Net/SFTP.php#L3071

**Comment by terrafrost** [comment]
Check out the line immediately preceding that line:

https://github.com/phpseclib/phpseclib/blob/497856a8d997f640b4a516062f84228a772a48a8/phpseclib/Net/SFTP.php#L3070
