### ISSUE TITLE
PHP 7.x

### ISSUE THREAD

**Issue by faca5** [phpseclib/phpseclib#1532]
Hello.

Is "phpseclib3" 100% compatible with PHP 7.x?

Example:
Crypt/RSA.php has in comment only "PHP version 5".

Thank you.

**Comment by terrafrost** [comment]
Yes. It's unit tested on all PHP 7.x versions. Same thing with phpseclib 1.0 and 2.0:

phpseclib 1.0 on TravisCI:

https://travis-ci.org/github/terrafrost/phpseclib/builds/726476362

phpseclib 2.0 on TravisCI:

https://travis-ci.org/github/terrafrost/phpseclib/builds/726476380

phpseclib 3.0 on TravisCI:

https://travis-ci.org/github/terrafrost/phpseclib/builds/728563431

The comments should probably be updated but it is a very low priority as changing them does not fix an actual bug, etc.

**Comment by faca5** [comment]
Thank you!

In mid time we have already tested on PHP 7.3 and it works.
