### ISSUE TITLE
Connection closed by server

### ISSUE THREAD

**Issue by elieobeid7** [phpseclib/phpseclib#1534]
`Connection closed by server ---- file: /var/www/html/crons/phpseclib/Net/SSH2.php ---- line: 1246`

Say on average we upload 20 videos daily, 5 of them will have that issue. I tried increasing the timeout in `SSH2.php` from 10 to 500, didn't help.

Is there anything we can do to solve this? Tweak some settings on the storage server?

**Comment by terrafrost** [comment]
How big are the files that it's failing on?

Can you get me the SSH logs? You can get them by doing `define('NET_SSH2_LOGGING', 2);` at the top of the file and `echo $ssh->getLog();` after the error occurs.

Thanks!

**Comment by elieobeid7** [comment]
@terrafrost I don't know, 400mb+

how to know when the error occurs in order to echo it? it's a cron job,

Are you suggesting that I add those in SSH2.php or is there a try-catch I can add in my script to detect that specific error?

**Comment by terrafrost** [comment]
So one thing you could do is to add a [custom error handler](https://www.php.net/manual/en/function.set-error-handler.php).

Example:

```
set_error_handler(function($errno, $errstr, $errfile) {
    throw new \Exception('whatever');
}, E_USER_NOTICE);
```
At that point you could catch the exception and then echo out the logs.

If you have other code pieces that aren't phpseclib that issue E_USER_NOTICE errors it might be helpful to the error handler to take `$errfile` into consideration. eg. only throw an exception if the file is in the phpseclib path.

**Comment by itsnotvalid** [comment]
As previously discussed in https://github.com/phpseclib/phpseclib/issues/1207, version 3.0 may change the errors to `\Exception`. Would you mind pointing out plans for 3.0 to be released?

Thanks.

**Comment by terrafrost** [comment]
3.0.0 has been tagged and released!
