### ISSUE TITLE
Cannot delete empty folders, due to missing . and .. entries

### ISSUE THREAD

**Issue by ssswang** [phpseclib/phpseclib#1537]
https://github.com/phpseclib/phpseclib/blob/92eb7b670f7198c41607f9074245afb896e0890a/phpseclib/Net/SFTP.php#L2320

Empty folders on this ftp server don't have . and .. entries. Permissions to read and delete are allowed.

**Comment by terrafrost** [comment]
Not really sure what to do about this one.

On one hand I feel that removing that line could be a BC break. What if, in _most_ cases, a lack of the `.` and `..` entries mean that read and delete permissions are _not_ allowed? In that case removing this line would require third party programs that had previously been hitting that line of code to have to rewrite their code to adapt to the new code.

On the other hand, if it's not a feature anyone uses then changing it isn't a huge issue.

Alternatively, I suppose I could add a new method to enable / disable that behavior on demand. By default it could be enabled, to preserve backwards compatibility, but you could turn it off to get the behavior you desire.

Something else I could do is just make the change and if I get bug reports about the change then I could revert that commit and release a new version of phpseclib that same day.

I could also make this change only in the 3.0 and master branches.

idk. I'll think on it some. Do you have any thoughts?
