### ISSUE TITLE
How to answer popup lists in with phpseclib? 

### ISSUE THREAD

**Issue by VahanDrnoyan** [phpseclib/phpseclib#1538]
Hello!

I tried to get an answer from the web but didn't find it.

So in ubuntu, there are popup lists like the screenshot attached, how to answer with one of the answers from phpseclib?

Thank you!
![Screenshot (1)](https://user-images.githubusercontent.com/23120503/95236998-b4c55280-0818-11eb-82f4-19c2d97f815e.png)

**Comment by terrafrost** [comment]
I'm not able to test this. I tried running `sudo apt-get install mysql-apt-config` in [Laravel Homestead](https://app.vagrantup.com/laravel/boxes/homestead) and it wasn't able to find the package.

That said, my guess is that what you'd need to do is something like this:

```php
$ssh->write("mysql-apt-config\n");
$ssh->sleep(3);
$ssh->write("\x1B5B42"); // send the down arrow
$ssh->write("\n"); // send the enter key
```
The `$ssh->sleep(3)` could probably be eliminated if I knew what to look for with a `$ssh->read()`. One thing you could give me that'd help with that is a base64 encoded version of the string returned by `$ssh->read()` after the `$ssh->write("mysql-apt-config\n");` By default you should get the `$ssh->read()` output after 10s.

**Comment by VahanDrnoyan** [comment]
Thank you for answer @terrafrost 

I have managed it by setting noninteractive mode for dpkg, Like this

` $input = "sudo DEBIAN_FRONTEND=noninteractive dpkg -i mysql-apt-config_0.8.12-1_all.deb";
        $output = $ssh->exec($input);`

And seeded the database with ready-made answers, like this

`$input = "debconf-set-selections <<< 'mysql-apt-config mysql-apt-config/tools-component string mysql-tools'";
        $output = $ssh->exec($input);`

Thank you again:)
