### ISSUE TITLE
Unsupported declare 'strict_types' in /vendor/sabre/event/lib/coroutine.php

### ISSUE THREAD

**Issue by pinmike** [phpseclib/phpseclib#1539]
The docs for this package says it works with PHP5 however when I install it with composer, it adds a dependency for sabre which results in a failure with the error

`Unsupported declare 'strict_types' in /vendor/sabre/event/lib/coroutine.php`

Then everything I can find online says Sabre requires PHP7? Is there a way to get this package to work with PHP5?

**Comment by terrafrost** [comment]
When I do a search for sabre PHP I get https://github.com/sabre-io/dav but that doesn't seem to have the directory structure that your error describes so I can't read it.

That said, this worked fine for me without issue:

```php
<?php
declare(strict_types=1);

error_reporting(E_ALL);

require __DIR__ . '/vendor/autoload.php';

use phpseclib\Crypt\RSA;
use phpseclib\Net\SFTP;

$rsa = new RSA();
$rsa->loadKey('...');

$ssh = new SFTP('website.com');
$ssh->login('root', $rsa);
print_r($ssh->nlist());
```
What does your phpinfo say?
