### ISSUE TITLE
PHP 8.0 warnings when using SSH2 and PublicKeyLoader after switch from 2.0.29 to 3.0.0

### ISSUE THREAD

**Issue by szaqal83** [phpseclib/phpseclib#1551]
Connecting over SSH2 with public key results several:

`Warning: Trying to access array offset on value of type null in /home/websites/.../phpseclib/phpseclib/phpseclib/Crypt/Common/Formats/Keys/PKCS8.php on line 488`

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/99e8d7b822fe8d27de5406fb048e36553235b178 should fix this
