### ISSUE TITLE
Stream class fails

### ISSUE THREAD

**Issue by meteguerlek** [phpseclib/phpseclib#1552]
$fsock ist private property
https://github.com/phpseclib/phpseclib/blob/5fcb2d4e34252c258de9eaaba87384d0765da3c1/phpseclib/Net/SSH2.php#L181

Stream class cant use the property
https://github.com/phpseclib/phpseclib/blob/5fcb2d4e34252c258de9eaaba87384d0765da3c1/phpseclib/Net/SFTP/Stream.php#L472

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/20852adf78c2954a8827c71274f0c187be929b0c should fix this. I added a unit test for this, as well, but that's in another commit.

Thanks!
