### ISSUE TITLE
Undefined method size

### ISSUE THREAD

**Issue by meteguerlek** [phpseclib/phpseclib#1553]
Size method not exists. filesize method should be used here.

https://github.com/phpseclib/phpseclib/blob/5fcb2d4e34252c258de9eaaba87384d0765da3c1/phpseclib/Net/SFTP.php#L1881

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/08478feee7577af1eeace51a191068623e33f0e3 should fix this. There's a unit test for this, as well, but that's in another commit.

Thanks!
