### ISSUE TITLE
Error when downloading file: Expected NET_SFTP_DATA or NET_SFTP_STATUS.

### ISSUE THREAD

**Issue by AdamGaskins** [phpseclib/phpseclib#1555]
```
Fatal error: Uncaught UnexpectedValueException: Expected NET_SFTP_DATA or NET_SFTP_STATUS. Got packet type:  in .../ftphosting-error/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2207
Stack trace:
#0 .../ftphosting-error/index.php(12): phpseclib3\Net\SFTP->get('...', '...')
#1 {main}
  thrown in .../ftphosting-error/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2207
```

Here is the full code. My only dependency is `phpseclib 3.0.1`:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use phpseclib3\Net\SFTP;

$sftp = new SFTP('...', 22);
$sftp->login('username', 'password');
$list = $sftp->nlist($dir = 'Directory/');
$sftp->get($dir . '/' . $list[0], $list[0]);
```

Here is the SFTP log: https://gist.github.com/AdamGaskins/7a0f0f48a98cddce8b9a08128576461a
And the SSH2 log: https://gist.github.com/AdamGaskins/5f0e8597b0c9e6f932b0d6759b4719d9

I wonder if the issue is at least partially similar to [this one](https://github.com/phpseclib/phpseclib/issues/1480)? I unfortunately don't know much about SFTP. Having this issue with https://www.ftphosting.net/ as the hosting provider.

**Comment by terrafrost** [comment]
Nothing looks off in the logs but if this is the same issue as #1480 then, in looking at that ticket, it looks like nothing looked wrong in those logs either (hence my providing debug code to the original poster to use).

I created an accounting on https://www.ftphosting.net/ and tried to first upload and then download a short file from the server and was able to do so without issue. Since I'm evidently not able to reproduce the issue would you be able to provide me with your login info so that I might try to reproduce the issue with your setup?

Alternatively, I could give you my credentials and maybe you could try to reproduce it on my instance?

My email address is terrafrost@php.net.

Thanks!

**Comment by AdamGaskins** [comment]
Hey, I appreciate the response and the active support! Love this library.

The day after I created the issue, ftphosting.net stopped erroring, I guess they changed something on their end. I was waiting around to see if it would come back, but it seems to be working fine now... I've had similar issues with them in the past too. Closing this issue for now :)

**Comment by haridarshan** [comment]
@terrafrost 

I'm getting this same issue when trying to download large media files (~4-7GB) from our client's SFTP Server. Some of the files are getting downloaded successfully but for some, getting this error/exception

I'm using _**phpseclib - 3.0.8**_

```php
UnexpectedValueException Object
(
    [message:protected] => Expected NET_SFTP_DATA or NET_SFTP_STATUS. Got packet type: 
    [string:Exception:private] => 
    [code:protected] => 0
    [file:protected] => /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php
    [line:protected] => 2219
    [trace:Exception:private] => ...<truncated>...
```

On debugging, SSH Error logs shows nothing but SFTP error logs shows 

```php
[sftp_errors:phpseclib3\Net\SFTP:private] => Array
  (
      [0] => : The file is EOF
      [1] => : The file is EOF
      [2] => : The file is EOF
      [3] => : The file is EOF
  )
```

Sample code from the script

```php
define('NET_SSH2_LOGGING', SSH2::LOG_COMPLEX);

try {
    $sftp = new SFTP($sftpServerHost, $sftpServerPort, $sftpTimeout);
    $sftp->sendKEXINITLast();
    $sftp->setTimeout(0);
    $sftp->setKeepAlive(5);
    $sftp->enableDatePreservation();

    $isLoggedIn = $sftp->login($user, $password);

    try {
        $status = $sftp->get(
            '/mediaarchive/profile5/feature/BM_11146_hd_h264_p005.ts.gpg',
            '/11146/BM_11146_hd_h264_p005.ts.gpg'
        );

        echo $status;
    } catch (Throwable $exception) {
        print_r($sftp->getErrors());
        print_r($sftp->getSFTPErrors());
        print_r($exception->getMessage());
    }
} catch (Throwable $exception) {
    print_r($exception);
}
```

Attached entire stack trace
[nohup.txt](https://github.com/phpseclib/phpseclib/files/6429697/nohup.txt)
