### ISSUE TITLE
Help - how to load RSA public base64 key and encrypt in v3 - a Java example attached?

### ISSUE THREAD

**Issue by RyanDaDeng** [phpseclib/phpseclib#1557]
Hello author,

I have a task that i have to encrypt message by using a public RSA key. The given example is like below (written in java), I have tried a lot method to do the same thing but still no luck. The provided RSA key is something like this:

````
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCHgH6rGreRZDC/fQ0oCBFamxXmR0/P3Z4ZaH112fIB4LqCD9g1mCCHNf9aISukD6vPBy7k/EgFevuUYeFpPSXveCVDUF+dkj//o5qpSI54s7p70PzzVKHDWp6KD9mYVuIRH8yMvGwiXEhx0DGLUD1mE0Nc6cwWdc8iAWjHSz3FuQIDAQAB
````

The demo code reads above Key and generate a PublicKey object and then encrypt things into base64 format.

````java


usage:

AsymmetricCryptography ac = new AsymmetricCryptography();
PublicKey publicKey = ac.getPublickey(RSA_PUBLIC_KEY);
String encryptedMessage = ac.encrypt(message, publicKey); 


// main code

public PublicKey getPublickey(String base64) throws Exception {
    byte[] keyBytes = java.util.Base64.getDecoder().decode(base64);
    X509EncodedKeySpec spec = new X509EncodedKeySpec(keyBytes);
    KeyFactory kf = KeyFactory.getInstance("RSA");
    return kf.generatePublic(spec);
}


public String encrypt(String msg, PublicKey key) throws NoSuchAlgorithmException, NoSuchPaddingException, UnsupportedEncodingException, IllegalBlockSizeException, BadPaddingException, InvalidKeyException {
    this.cipher.init(Cipher.ENCRYPT_MODE, key);
    return Base64.encodeBase64String(cipher.doFinal(msg.getBytes("UTF-8")));
}
````

I have tried many new methods, but still no luck, been on this for almost 5 hours...

Thanks in advance

**Comment by RyanDaDeng** [comment]
I was trying to convert the below code by using phpseclib 3, basically, the value I have is a base64 format (not sure if it PKCS8 ? sorry I'm not sure)


````java
public PublicKey getPublickey(String base64) throws Exception {
    byte[] keyBytes = java.util.Base64.getDecoder().decode(base64);
    X509EncodedKeySpec spec = new X509EncodedKeySpec(keyBytes);
    KeyFactory kf = KeyFactory.getInstance("RSA");
    return kf.generatePublic(spec);
}

````

**Comment by RyanDaDeng** [comment]
I found lower version of phpsecli has the following solution:

````php
function encrypt($key,$payload){
    $rsa = new RSA();
    $rsa->loadKey($key); // public key

    $rsa->setEncryptionMode(2);   //  change encryption mode to be PKCSPADDING 
    $ciphertext = $rsa->encrypt($payload);

    return base64_encode($ciphertext);
}

````


The v3 doesn't allow me to set up ` $rsa->setEncryptionMode(2); ` any ideas?

**Comment by RyanDaDeng** [comment]
...well, i tried a lot methods, v2,v3..... i can get encyrpted message, however if I sent it to 3rd party service, its not passed...

v2:

````php

       $rsa = new RSA();
        $rsa->setEncryptionMode(RSA::ENCRYPTION_PKCS1);
        $rsa->loadKey($key);
        $encyptedmessage = base64_encode(rsa->encrypt($message));
````
not work.

well...

**Comment by terrafrost** [comment]
```
this.cipher.init(Cipher.ENCRYPT_MODE, key);
```
What is `this.cipher` an instance of?

Normally you'd set the `cipher` variable to `Cipher.getInstance("RSA/ECB/PKCS1Padding")` or `RSA/ECB/OAEPWithSHA-256AndMGF1Padding` or something.

This also depends on the crypto service provider you're using. org.bouncycastle.jce.provider.BouncyCastleProvider assumes the MGFHash and the Hash are using the same algorithm whereas com.sun.crypto.provider.SunJCE has the MGFHash hard-coded as sha1.

I realize you closed this ticket but if you're still having issues I'd need to know how `cipher` is being initialized (should be in the code snippet you have) and what crypto service provider you're using (which you can get by doing `cipher.getProvider()`)

**Comment by RyanDaDeng** [comment]
@terrafrost i just found out the third party document has missed some important logic, all good now. its not the package issue. thanks for the prompt reply!
