### ISSUE TITLE
Documentation type mismatch

### ISSUE THREAD

**Issue by kylekatarnls** [phpseclib/phpseclib#1558]
Hello,

Can you please explain:
https://phpseclib.com/docs/rsa#raw-rsa-public-keys

Example show an n+e array as parameter, but the method actually requires `string`:
https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/PublicKeyLoader.php#L36

So can you show how to proceed for an n+e array?

**Comment by terrafrost** [comment]
When the documentation and the phpDoc comments don't match, _always_ assume the documentation is more accurate.

I've spent the past 11 or so months working on phpseclib.com. I most definitely was _not_ doing it full time but, in-so-far as phpseclib work is concerned, that's been my main focus. The phpDoc commentary, otoh, has not gotten anywhere near that same level of attention.

Anyway, yes, arrays are supported for the Raw type:

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA/Formats/Keys/Raw.php#L49

Technically, _any_ data type is supported as long as a plugin for it exists.

I'll add it to my to do list to update the phpDoc comment.

> So can you show how to proceed for an n+e array?

Yes. It's in the documentation link you provided lol.

**Comment by kylekatarnls** [comment]
Thanks for clarifying which one is the source of truth. In this case maybe you can explain why passing such an array produces the error:
```
TypeError: strpos(): Argument #1 ($haystack) must be of type string, array given

vendor/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/PKCS1.php:64
vendor/phpseclib/phpseclib/phpseclib/Crypt/Common/AsymmetricKey.php:162
vendor/phpseclib/phpseclib/phpseclib/Crypt/PublicKeyLoader.php:42
src/AccessToken/Verify.php:235
src/AccessToken/Verify.php:105
tests/Google/AccessToken/VerifyTest.php:41
```

phpseclib 3.0.1
PHP 8.0.0

Code that call `load()` is:
https://github.com/googleapis/google-api-php-client/pull/2019/files#diff-dbcd1e59f54ffa0425222f56eca976fc29e17bc33c82c559e29703ad397a1d41R235

I'm still inspecting my code but sounds like a legit n+e array passed triggers this type error.

Thanks for your help.

**Comment by kylekatarnls** [comment]
@terrafrost I wrote a unit test using the example of the documentation here:
https://github.com/phpseclib/phpseclib/pull/1559

This is the failure that makes me believe that the documentation might eventually not be accurate.

I know it's a lot of work, it would be nice if unit tests or some other checker might run code examples provided in the doc against current PHP stable version so we can safely rely on them.
