### ISSUE TITLE
Interrupted system call on sftp file_exists

### ISSUE THREAD

**Issue by malohtie** [phpseclib/phpseclib#1560]
Hi after upgrading to v3 i'm started getting this error on file_exists method
it happen 7 out of 10 times

process executed every minute with cron job to check if file exists and download them 

`  return $this->sftp->file_exists($file);`

```
ErrorException: stream_select(): unable to select [4]: Interrupted system call (max_fd=18) in /var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3199


Stack trace:
--
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#1 /var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3199): stream_select()
#2 /var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3691): phpseclib3\Net\SSH2->get_binary_packet()
#3 /var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2948): phpseclib3\Net\SSH2->get_channel_packet()
#4 /var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(1315): phpseclib3\Net\SFTP->get_sftp_packet()
#5 /var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(1203): phpseclib3\Net\SFTP->stat_helper()
#6 /var/dms/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2391): phpseclib3\Net\SFTP->stat()
#7 /var/dms/app/Libraries/Ssh.php(111): phpseclib3\Net\SFTP->file_exists()
#8 /var/dms/app/Jobs/BounceLogJob.php(57): App\Libraries\Ssh->fileExists()

```

thanks

**Comment by malohtie** [comment]
i removed the keepalive method and my jobs still failling 

```
$this->sftp = new SFTP($this->server->ip, $this->server->port);
//$this->sftp->setKeepAlive(10);
$this->sftp->setTimeout(0);
$password = null;
if (strtolower($this->server->login_type) == 'password') {
	$password = $this->server->password;
} else {
	$password = PublicKeyLoader::load($this->server->password);
}
if ($this->sftp->login($this->server->username, $password)) {
	$this->osVersion();
	if($this->fileExists("/var/mini/storage/bnc.log")) {
		$ssh->exec("mv /var/mini/storage/bnc.log /var/mini/storage/bnc.old");
		$name = sprintf('%s_bnc_%s', uniqid(), now()->timestamp);
		$fullpath = 'tmp/'.$name;
		return  $ssh->download('/var/mini/storage/bnc.old', Storage::path($fullpath));
	}
}
return false;
```

is it something related to this ? 
#https://github.com/PHPMailer/PHPMailer/issues/1227
#https://github.com/PHPMailer/PHPMailer/pull/2074
#https://github.com/symfony/symfony/pull/6540

**Comment by malohtie** [comment]
i temporary rolled back to v 2.0.18 until i figure out what going to those queue jobs

**Comment by terrafrost** [comment]
I think https://github.com/phpseclib/phpseclib/commit/7a9418e4e02a3da7950b6b85c30e694d68daf995 should fix this. In the 2.0 branch (2.0.18 is over a year old btw) this wasn't an issue because the error suppression operator was being used on `stream_select`. Mainly to suppress "Warning: Invalid CRT parameters detected" errors on Windows but it would have had the side effect of suppressing other errors as well, like this one.

In testing 3.0 I wasn't able to encounter that "Warning: Invalid CRT parameters detected" error. Thinking that was because I had upped the PHP version requirements from 4.4.x to 5.6.1 I thought that the need for the error suppression operator had been eliminated. Maybe not!

LMK if this change fixes your issue.

Thanks!

**Comment by malohtie** [comment]
it seem everything okay after the suppression of the error no exception raised

the only thing remain is to release the patch so we can use it in production ^^

Many thanks

**Comment by malohtie** [comment]
i'm wondering if this solution will work for php 8 as Error Suppression operator @ does not silent fatal errors
im on 7.4 so it fine for me for now

**Comment by terrafrost** [comment]
> i'm wondering if this solution will work for php 8 as Error Suppression operator @ does not silent fatal errors
im on 7.4 so it fine for me for now

Can you test it out and lmk? I don't have access to a server that reproduces the issue (unless you give me access to yours lol; you can email the credentials to terrafrost@php.net if you're down!) so I'm unable to do much myself.

Thanks!

**Comment by malohtie** [comment]
> it seem everything okay after the suppression of the error no exception raised
> 
> the only thing remain is to release the patch so we can use it in production ^^
> 
> Many thanks

as i said it working great now it been 3 hours no exception raised using master branch everything fine, 
we dont have php 8 installed on our production server sorry it was just a thought

Thanks

**Comment by terrafrost** [comment]
3.0.2, which contains this fix, has been released!

If the fix doesn't work on PHP8 I'll prob get a bug report at some point. If it throws an exception I can catch that specific exception and all should be well.

Thanks!
