### ISSUE TITLE
Can not see DES

### ISSUE THREAD

**Issue by laynier** [phpseclib/phpseclib#1563]
The errorGET / - Uncaught Error: Class 'phpseclib3\Crypt\DES' not found in /route/user/Descargas/3des/phpseclib/phpseclib/Crypt/TripleDES.php:47

What means? is it possible that the composer or autoloader aren't working_? how can a class not see its parent_? TripleDES extends from DES and can not see it. Why_?
Hope you help me... Thanks

**Comment by terrafrost** [comment]
It works fine for me:

```php
<?php
require __DIR__ . '/vendor/autoload.php';

use phpseclib3\Crypt\TripleDES;

$cipher = new TripleDES('ecb');
$cipher->setPassword('zzz');

echo bin2hex($cipher->encrypt('test'));
```
How did you install phpseclib?

**Comment by laynier** [comment]
1- Made a clone of the repo.
2-composer install
3-created a view to interact with the library.
Update: Finally fixed by correcting my configuration of autoload. So, error was in MY environment, but example like you provide me now would be very useful.
