### ISSUE TITLE
random_compat error installing with composer in PHP 7

### ISSUE THREAD

**Issue by adamjimenez** [phpseclib/phpseclib#1571]
I get an error when I try to install with composer:

```
# composer require phpseclib/phpseclib
Installation request for paragonie/random_compat (locked at v9.99.99) -> satisfiable by paragonie/random_compat[v9.99.99].
```

I think the composer requirements need to be [tweaked](https://github.com/paragonie/random_compat#version-99999).

**Comment by terrafrost** [comment]
I'm not able to reproduce this. I'm running PHP 7.4.3 and Composer 2.0.8 and did `composer require phpseclib/phpseclib` in a new directory and got this:

```
./composer.json has been created
Running composer update phpseclib/phpseclib
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking paragonie/constant_time_encoding (v2.4.0)
  - Locking paragonie/random_compat (v2.0.19)
  - Locking phpseclib/phpseclib (3.0.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing paragonie/random_compat (v2.0.19): Extracting archive
  - Installing paragonie/constant_time_encoding (v2.4.0): Extracting archive
  - Installing phpseclib/phpseclib (3.0.2): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
```
I mean, I can change it, but outside of you, I'm not aware of anyone else having this issue and I'm a little reluctant to require random_compat 9.99.99 when it 2.0.19 seems to be working fine for everyone else...

What version of PHP are you running? What version of Composer? Maybe you can post the full Composer output?

Thanks!

**Comment by adamjimenez** [comment]
Thanks for looking into this. I'm using PHP 7.2.24
This issue seems to have resolved itself after upgrading other packages. Closing.

**Comment by terrafrost** [comment]
Should be working better after #1585
