### ISSUE TITLE
Does phpseclib allows to generate X509 v3?

### ISSUE THREAD

**Issue by andrew-svirin** [phpseclib/phpseclib#1576]
For custom purpose I need to generate Certificate X509 v3. Does phpseclib can do it?

**Comment by terrafrost** [comment]
Yes. It's kinda cumbersome but yes:

http://phpseclib.sourceforge.net/x509/guide.html

Also, v3 certs are the only type of X509 cert phpseclib supports. You can't do v2 or v1 X.509 certs with phpseclib.
