### ISSUE TITLE
Self signed Certificate X509

### ISSUE THREAD

**Issue by andrew-svirin** [phpseclib/phpseclib#1577]
Please advice me about this certificate generation:

```
        $subject = $this->generateSubject(...);
        $issuer = $this->generateIssuer(...);

        $x509 = new x509;
        $x509->setStartDate(...);
        $x509->setEndDate(...);
        $x509->setSerialNumber(...);

        // Signing Subject for append extensions below.
        $signedSubject = $x509->sign($issuer, $subject);
        $x509->loadX509($signedSubject);

        foreach ($extensions as $extension) {
            $x509->setExtension(...);
        }

        // Signing again with extensions.
        $signedX509 = $x509->sign($issuer, $x509);
        $x509->loadX509($signedX509);
```

Am i correctly signing certificate twice? Is it correct way?

**Comment by terrafrost** [comment]
$subject = $this->generateSubject(...);
        $issuer = $this->generateIssuer(...);

        $x509 = new x509;
        $x509->setStartDate(...);
        $x509->setEndDate(...);
        $x509->setSerialNumber(...);

        // Signing Subject for append extensions below.
        $signedSubject = $x509->sign($issuer, $subject);
        $x509->loadX509($signedSubject);

        foreach ($extensions as $extension) {
            $x509->setExtension(...);
        }

        // Signing again with extensions.
        $signedX509 = $x509->sign($issuer, $x509);
        $x509->loadX509($signedX509);


```
        // Signing Subject for append extensions below.
        $signedSubject = $x509->sign($issuer, $subject);
        $x509->loadX509($signedSubject);
```
You might need to do this instead:

```
        // Signing Subject for append extensions below.
        $signedSubject = $x509->saveX509($x509->sign($issuer, $subject));
        $x509->loadX509($signedSubject);
```
If I'm right you'd need to do another `$x509->saveX509(...)` call after the second `$x509->sign(...)` call as well.

**Comment by andrew-svirin** [comment]
Thanks!
