### ISSUE TITLE
Variable '$value' is introduced as a method parameter and overridden

### ISSUE THREAD

**Issue by applibs** [phpseclib/phpseclib#1589]
```
foreach ($extensions as $key => $value) {
    if ($value['extnId'] == $id) {
        if (!$replace) {
            return false;
        }

        $extensions[$key] = $newext;
        return true;
    }
}
```

**Comment by terrafrost** [comment]
If you're referring to `private function setExtensionHelper($id, $value, $critical = false, $replace = true, $path = null)` in 3.0 then it's not an issue. The line right before `foreach ($extensions as $key => $value) {` is as follows:

```
$newext = ['extnId'  => $id, 'critical' => $critical, 'extnValue' => $value];
```
ie. the `$value` method parameter is used to build `$newext`, at which point, it's no longer needed and is available for reuse, which is what's being done.
