### ISSUE TITLE
Undefined class 'Engine'

### ISSUE THREAD

**Issue by applibs** [phpseclib/phpseclib#1592]
```
/**
 * Bitwise Split
 *
 * Splits BigInteger's into chunks of $split bits
 *
 * @param int $split
 * @return \phpseclib3\Math\BigInteger\Engine[]
 */
public function bitwise_split($split)
```

should be: `@return \phpseclib3\Math\BigInteger\Engines\Engine[]`

**Comment by terrafrost** [comment]
Yup, you're right. It's not an issue I would have lost sleep over (I don't really lose sleep over DocBlock issues lol) but since it's been pointed out I'll endeavor to fix it!

If you wanted to submit a PR to fix it I'd merge it in but I can make the code change myself too!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/bdb6c08c3507c3aeb47a1bc5a198ee9bdb3618f7 should fix this - thanks!
