### ISSUE TITLE
Undefined class 'ECDSA' 

### ISSUE THREAD

**Issue by applibs** [phpseclib/phpseclib#1593]
`use phpseclib3\Crypt\ECDSA;`

and

`if ($key instanceof ECDSA)`

**Comment by terrafrost** [comment]
That's in ./System/SSH/Agent/Identity.php. Should be `$key instanceof EC` - not `$key instanceof ECDSA`. Nice catch!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/1795b5df6a172952cfc4d67177646709152c9367 should fix this - thanks!
