### ISSUE TITLE
Performance issues when signing with EC

### ISSUE THREAD

**Issue by vizvayu** [phpseclib/phpseclib#1601]
I'm having some performance issues when using elliptic curves for signing. I don't know if this is supposed to be like this (a feature by design), if it's a bug or if I'm doing something wrong. I did a quick comparison against the openssl functions in PHP and these are the results (in seconds):

```
Sign openssl: 0.00019192695617676
Sign phpseclib: 0.78625392913818
Verify openssl (1): 0.00012803077697754
Verify phpseclib (1): 0.015505075454712
```

This is the test code I'm using (the keys are truncated to make it shorter/more readable):

```
$data = 'asd123';
$key = '-----BEGIN EC PRIVATE KEY-----
...
-----END EC PRIVATE KEY-----';
$keyP = '-----BEGIN PUBLIC KEY-----
...
-----END PUBLIC KEY-----';
$hash = 'sha256';

$ts = microtime(true);
openssl_sign($data, $sign1, $key, $hash);
$te = microtime(true) - $ts;
echo "Sign openssl: $te\n";

$ts = microtime(true);
$keyObject = phpseclib3\Crypt\EC::load($key)->withHash($hash);
$sign2 = $keyObject->sign($data);
$te = microtime(true) - $ts;
echo "Sign phpseclib: $te\n";

$ts = microtime(true);
$ret = openssl_verify($data, $sign1, $keyP, $hash);
$te = microtime(true) - $ts;
echo "Verify openssl (".(int)$ret."): $te\n";

$ts = microtime(true);
$keyObject = phpseclib3\Crypt\EC::load($keyP)->withHash($hash);
$ret = $keyObject->verify($data, $sign2);
$te = microtime(true) - $ts;
echo "Verify phpseclib (".(int)$ret."): $te\n";

```
This is in a Xeon 6140 single-core VM (in case that helps).
The key was created using a secp256r1 curve.
Any suggestion is appreciated.
Thanks!

**Comment by terrafrost** [comment]
The speed ultimately depends on the engine you're using. Here's what I got with your script with GMP:

```
Sign openssl: 0.00072312355041504
Sign phpseclib: 0.057081937789917
Verify openssl (1): 0.00027298927307129
Verify phpseclib (1): 0.064456939697266
```
If you don't have GMP installed than PHP64 with OpenSSL will be used. Here's what I get with that:

```
Sign openssl: 0.00057792663574219
Sign phpseclib: 0.1438090801239
Verify openssl (1): 0.00038814544677734
Verify phpseclib (1): 0.14177513122559
```
This is on my Intel i7-1065G7 and with PHP 7.4.

I think a lot of this, unfortunately, is just PHP overhead. Here's the same test with the `$ts = microtime(true)` line _after_ the key is loaded instead of before (with PHP64):

```
Sign openssl: 0.00042891502380371
Sign phpseclib: 0.06527304649353
Verify openssl (1): 0.00082993507385254
Verify phpseclib (1): 0.048412084579468
```
The times are much better. Indeed, if OpenSSL is available, `Crypt/EC/PrivateKey.php::sign` actually uses `openssl_sign`:

```
            // altho PHP's OpenSSL bindings only supported EC key creation in PHP 7.1 they've long
            // supported signing / verification
            // we use specified curves to avoid issues with OpenSSL possibly not supporting a given named curve;
            // doing this may mean some curve-specific optimizations can't be used but idk if OpenSSL even
            // has curve-specific optimizations
            $result = openssl_sign($message, $signature, $this->toString('PKCS8', ['namedCurve' => false]), $this->hash->getHash());
```
I can use xdebug profiling, at some point, to see if there are any optimizations I can squeeze out but I'm not gonna hold my breath on my being able to do anything that'd make a significant impact. Maybe PHP 8.0 with JIT would speed thus up more?

Unrelated, to make an even more concise example you could do this:

```php
$key = EC::createKey('secp256r1');
$keyP = $key->getPublicKey();
$keyP = (string) $key->getPublicKey();
$key = (string) $key;
```

**Comment by vizvayu** [comment]
Yes, I think you're right. Most of the time is spent loading the key:
![phpseclib ec profile](https://user-images.githubusercontent.com/1631074/107035938-a1f76600-6797-11eb-97e5-661d8031e0b8.png)
I don't know the internals, but maybe because there's a double conversion of the key when loaded? I mean, PEM to binary and then to text again to pass it to openssl_sign(). Just guessing, I don't know.
I do have GMP installed, and libsodium as well. It may be slower in my case because it's a single core VM.
I hope it'll be faster with PHP8, but for now I think I'll just keep using openssl directly for signing and verifying because the difference in performance is just too big.

Unrelated question: Is it possible to encrypt a key like with RSA but using elliptic curves? I'm doing some tests with JWE and I'd like to try ECDH-ES. I'm already doing it with RSA (RSA1_5 and RSA-OAEP), but I was wondering if it's possible to do the same with EC using phpseclib.

Thank you very much for your time!

**Comment by terrafrost** [comment]
> I don't know the internals, but maybe because there's a double conversion of the key when loaded? I mean, PEM to binary and then to text again to pass it to openssl_sign(). Just guessing, I don't know.

Yah. Even if I cache'd PKCS1/8 formatted keys I'd still want to parse them as that enables them to be validated. You also couldn't convert keys unless the individual key components were broken down.

For 1x signature that up front validation makes things slower but if you're gonna be signing a bunch of stuff the time lost in the parsing of the key becomes increasingly irrelevant.

> Unrelated question: Is it possible to encrypt a key like with RSA but using elliptic curves? I'm doing some tests with JWE and I'd like to try ECDH-ES. I'm already doing it with RSA (RSA1_5 and RSA-OAEP), but I was wondering if it's possible to do the same with EC using phpseclib.
>
> EDIT: I think I can do this using DH->computeSecret() (please correct me if I'm wrong). I was looking inside the EC class, that's why I didn't found anything related to what I needed.

You can use ECDH to do crypto but it's def less direct than RSA. Like using that route you'd also have to select a symmetric key algorithm. I mean, I guess for sufficiently short plaintext's you could just XOR the shared secret against the plaintext. If you're encrypting you use the other persons public key and you use your own private key.

**Comment by vizvayu** [comment]
Yes, the idea is to encrypt only a key to use then with symmetric encryption for the payload... that's with RSA. With EC-DH apparently I can use the shared secret as a key for the symmetric encryption.

And in my case I'll be signing just one thing at a time. Hopefully with PHP8 things will be much faster.
Thanks again for your help.
