### ISSUE TITLE
phpseclib3: X509 provides no way to access $currentCert

### ISSUE THREAD

**Issue by tomsommer** [phpseclib/phpseclib#1602]
$currentCert is now private, there is no way to get the current cert, or the current cert in each ->getChain()

```
foreach ( $x509->getChain() as $chain ) {
$x509->saveX509($chain);
}
```

no longer works. The phpseclib2_compat also does not work with this

**Comment by terrafrost** [comment]
I'll try to play around with this either tomorrow or this weekend!

**Comment by terrafrost** [comment]
So I totally forgot about this lol - hopefully I'll be able to play around with this this evening - thanks!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/052cb7d762779ae34fdf3c99c5ab10d00350fc3e should now fix this!

I apologize for the delay!

I'll try to do a release in the next few days!

**Comment by terrafrost** [comment]
This is live in the new 3.0.5 release.

Thanks!
