### ISSUE TITLE
Importing EC X and Y coordinates into a key resource

### ISSUE THREAD

**Issue by vizvayu** [phpseclib/phpseclib#1607]
Is it possible to import some EC X and Y coordinates into phpseclib, or at least somehow get a public key PEM string from them?

Thanks!

**Comment by terrafrost** [comment]
I think this should work:

```php
$curve = new \phpseclib3\Crypt\EC\Curves\secp256k1;
$coords = [
    $curve->convertInteger(new BigInteger(...)),
    $curve->convertInteger(new BigInteger(...))
];
\phpseclib3\Crypt\EC\Formats\Keys\PKCS8::savePublicKey($curve, $coords);
```
I suppose if there was enough demand for this I could add a Raw plugin for EC keys, much like how RSA has one.

**Comment by vizvayu** [comment]
Excellent! I'll give it a try.
Thanks again!
