### ISSUE TITLE
phpseclib v.2.0 - RSA

### ISSUE THREAD

**Issue by bonilla9229** [phpseclib/phpseclib#1610]
this is to ask you a question about the use of the library,

We are generating an RSA encryption and everything seems to be working excellent, it generates the encrypted key, using a public key, we use two methods, both the XML method and the use of a PEM file, but our problem is that this encrypted key must be sent to a API in .NET, which tells us that the key is wrong,

We did a test of generating an encrypted key in .NET and it was accepted.

our query ... it is possible that despite the fact that PHP generates an encrypted key for us, this is not the same as its generation in .NET, They believe that .NET its decryption is waiting for some variable that it does not include in the library.

```
<?php

	require __DIR__ . '/vendor/autoload.php';

	use phpseclib\Crypt\RSA;

	$rsa = new RSA();
	
    $public = "<RSAKeyValue>\r\n" . "  <Modulus>" . b64url2b64('4VWXgXXXXXXXXXXXXXXXXXXXXXXXXXXXXX+E=') 
													. "</Modulus>\r\n" . "  <Exponent>" . b64url2b64('AQAB') . "</Exponent>\r\n" . 
			   "</RSAKeyValue>";

			

    $rsa->loadKey($public, RSA::PUBLIC_FORMAT_XML);
		
	$rsa->setEncryptionMode(RSA::ENCRYPTION_PKCS1);

	$ciphertext = base64_encode($rsa->encrypt('8945'));

    echo $ciphertext; exit;

	
    function b64url2b64($base64url) {
        // "Shouldn't" be necessary, but why not
        $padding = strlen($base64url) % 4;
        if ($padding > 0) {
        $base64url .= str_repeat("=", 4 - $padding);
        }
        return strtr($base64url, '-_', '+/');
    }
?>
```

**Comment by terrafrost** [comment]
Can you post the .NET code? Is it C#?

Also, just for good measure, could you post the key that .NET isn't able to decrypt?

Thanks!
