### ISSUE TITLE
Decryption Error

### ISSUE THREAD

**Issue by konco** [phpseclib/phpseclib#1613]
`use phpseclib3\Crypt\RSA;`

i'm using Laravel.

`$crypted = base64_decode($txPaymentTokenId);
$token = file_get_contents(storage_path('eMoneyMetfone.pri'));
$rsa = PublicKeyLoader::load($token);
$rsa->withPadding(RSA::ENCRYPTION_PKCS1);
$decrypted = $rsa->decrypt($crypted);
dd($decrypted);`

**Comment by terrafrost** [comment]
```php
$rsa->withPadding(RSA::ENCRYPTION_PKCS1);
```

That should be this:

```php
$rsa = $rsa->withPadding(RSA::ENCRYPTION_PKCS1);
```
In phpseclib v3 keys are immutable. That's why it was changed from `setPadding()` to `withPadding()`.
