### ISSUE TITLE
is_writable() does not work on directories

### ISSUE THREAD

**Issue by lightray22** [phpseclib/phpseclib#1616]
PHP's is_writeable() doc specifies... "Returns true if the filename exists and is writable. The filename argument may be a directory name allowing you to check if a directory is writable."

Giving a directory to phpseclib always returns false.  Looks like it's because the implementation checks by opening up a handle to what it assumes is a file.  is_readable() likely has the same issue.  For what it's worth this doesn't seem to work in the FTP extension either, but by PHP's description it seems like it should.

**Comment by terrafrost** [comment]
Short of actually trying to upload a test file to a directory, it's not immediately clear how this could even work. See https://stackoverflow.com/q/54985650/569976

**Comment by lightray22** [comment]
Maybe it can't.  I'm not sure how PHP's version works.  Uploading a test file is how I'm working around it.

Regardless, since PHP claims that it does/should work, maybe a note in the documentation would suffice.

**Comment by terrafrost** [comment]
> Maybe it can't. I'm not sure how PHP's version works. Uploading a test file is how I'm working around it.

In-so-far as the local filesystem is concerned you probably have more system calls available to you then SFTP provides for. So one possibility is that you _can't_ do, through SFTP, what PHP does for the local filesystem.

> Regardless, since PHP claims that it does/should work, maybe a note in the documentation would suffice.

It is mentioned in the documentation:

https://phpseclib.com/docs/sftp#file-attributes

> `is_readable()` and `is_writeable()` only work on files. They work by actually opening up a file for reading or writing and then closing the file immediately thereafter. The same technique does not work for directories.

**Comment by lightray22** [comment]
Oops, missed that.  Weirdly it seems like is_readable() does work on the directory I'm trying it on.
