### ISSUE TITLE
stream wrapper does not work on PHP 7.4.15 or 8.0.2

### ISSUE THREAD

**Issue by lightray22** [phpseclib/phpseclib#1617]
I'm actually not sure if this should be considered a PHP bug, or a phpseclib bug.

The phpseclib stream wrapper uses the magic __call function to do logging, but in the PHP versions I've tested, __call is never actually called in the stream wrapper in most cases (possibly never), meaning the stream wrapper does not work at all.  I started by debugging mkdir - I never saw the call get to _mkdir() or to __call(), but when I added the actual mkdir() function to Stream.php, it worked.  

By replacing "private function _" with "public function ", and fixing a few conflicting method signatures I was able to get the stream wrapper working.  I'm not sure if this is the direction you would want to go for fixing this, since it breaks the intended logging.

**Comment by terrafrost** [comment]
I tried it out and it worked just fine for me on PHP 8.0.2.

For good measure I took the sample stream wrapper at https://www.php.net/manual/en/stream.streamwrapper.example-1.php and modified all the method names to be prepended with `_`'s, like how phpseclib does it. I then added the same `__call()` method that phpseclib has and it worked without issue on all the PHP versions 3v4l.org tests against:

https://3v4l.org/QBBel

I mean, I don't have a problem removing the `__call`, especially if it's breaking things in a duplicatable way, but I'm not able to duplicate it...

**Comment by lightray22** [comment]
Interesting. I'll have to do some more digging...

**Comment by lightray22** [comment]
Update - it seems like at least some of the stream wrapper is working for me.  I tried reading/writing a file with the original stream wrapper and it worked fine.  But mkdir (what I started with) still does not work.  The mkdir() call on my end is returning false, and when I add `echo "phpseclib call $name\n";` to the beginning of __call(), all I see is `phpseclib call url_stat` twice.  If I add a _mkdir() to the PHP demo website you linked it does appear to work.  So not sure yet what the issue is...

**Comment by lightray22** [comment]
Okay now I'm getting somewhere... while _mkdir is never called in Stream.php, the base mkdir() in SFTP.php *is* getting called.

**Comment by terrafrost** [comment]
Ooh interesting. That makes sense about mkdir.

Try this:

https://github.com/phpseclib/phpseclib/commit/eeabad1ed3cdf91302cd01ec3a4bcf6059e77ffa

**Comment by lightray22** [comment]
Works!  Looking at the code I would guess rmdir/rename were also broken, both work now.   I also tried fread/fwrite/fseek/ftruncate/unlink/touch, all work fine.  Glad the fix was that simple - thanks!
