### ISSUE TITLE
writing beyond the end of a file does not work

### ISSUE THREAD

**Issue by lightray22** [phpseclib/phpseclib#1618]
When using the stream wrapper to write bytes to a file... trying to write beyond the end of a file does not work.  I can work around this with a check for the file size and truncate() call, but this probably should work.  It works for local storage, even if the starting offset is also beyond the end of the file.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/d20e842a5e9bb7c6873dbf3e5c5f296eb636c127 should fix this.

Thanks!

**Comment by lightray22** [comment]
I can confirm this now works correctly on master. Thanks!
