### ISSUE TITLE
Decryption error

### ISSUE THREAD

**Issue by konco** [phpseclib/phpseclib#1619]
Question:
1. why the result after encrypt not same as they want?
2. when i try to encrypt  the plaintext like this: "test data", and decrypt again, the result always Decryption error.

this is the RSA Crypto:
![image](https://user-images.githubusercontent.com/4013641/108702391-c4c99e80-753b-11eb-95b4-ef0eea299167.png)

```$encrypted= "D3/Ax591Mn8OHzQk7+ZBeL3t1KZXm1MROH45V/X3vTjNx9Mgix1QTg76a1Hp3TiZ/zQ/4GadzQoD9kuKZcbV1JX2d9WpSB6NJ1IcpfnMKu1HnrRvbuvujM9I1jjkb5bjXYQ2wtzNed0JX+CrOIQuz5He7UCktMHy7ToU52xnzAZlghjSFm9rEjEKei5BLhEilVWvy/4i3vTDX+5cna/a1A6YttBYGbe1JrQBmN/680OM/cTsoE1A/xwVJLuRFjjuDiPhzE9PaNYxJWqibV/+Gn0000aIBKHpS2WK0qBWqw0LPl4isvuRcQB8LD+D0cohnVSrMDvissHc3HCJvaCB6g==";```

plaintext after decrypt : b4a70c781a790199e40e20dcefcddf0e27d09e2e8c21b71f12e99f0ef804adc44a8e76732e4835b88171757ae5efeed8

```
private function decrypt_data_new($encrypted)
    {
        $crypted = base64_decode($encrypted);
        $token = file_get_contents(storage_path('test.pri'));
        $rsa = PublicKeyLoader::load($token)->withPadding(RSA::ENCRYPTION_PKCS1);
        $decrypted = $rsa->decrypt($crypted);

        return $decrypted;
    }
```
```
private function encrypt_data_new($plaintext)
    {
        $plaintext = "2478e27af578e11a6af86a8320562124240f5c972e8039cd9c564e53d643bb31|".$plaintext;
        $token = file_get_contents(storage_path('test.pub'));
        $rsa = PublicKeyLoader::load($token)->withPadding(RSA::ENCRYPTION_PKCS1);
        $ciphertext = $rsa->encrypt($plaintext);
        $encrypt = base64_encode($ciphertext);
        return $encrypt;
    }
```

**Comment by terrafrost** [comment]
The public key does not appear to correspond to the private key. In particular, the modulo is different.

```php
$private = PublicKeyLoader::load(file_get_contents('test.pri'));
$public = PublicKeyLoader::load(file_get_contents('test.pub'));

echo crc32($private->getPublicKey()->toString('Raw')['n']->toString()) . "\n";
echo crc32($public->toString('Raw')['n']->toString());
```

**Comment by konco** [comment]
but when i try like this, go response error: Call to undefined method phpseclib3\Crypt\RSA\PublicKey::decrypt()

```php
$priv_key = file_get_contents(storage_path('test.pri'));
$private = PublicKeyLoader::load($priv_key)->withPadding(RSA::ENCRYPTION_PKCS1);
$plaintext = $private->getPublicKey()->withPadding(RSA::ENCRYPTION_PKCS1)->decrypt($crypted);
dd($plaintext);
```

**Comment by konco** [comment]
i have a java code, but i never using java, so i do't understand ussing this code.
i always use PHP, so thats why i use phpseclib.
maybe u can help to convert this to PHP code using this library.

```java
public static String encryptRSA(String plainData, StringpublicKeyFilePath) 
{
	try {
		FileInputStream fis = new FileInputStream(publicKeyFilePath);
		byte[] byteKeyFromFile = new byte[fis.available()];
		fis.read(byteKeyFromFile);
		fis.close();
		X509EncodedKeySpec keySpec = new
		X509EncodedKeySpec(byteKeyFromFile);
		KeyFactory factory = KeyFactory.getInstance("RSA");
		PublicKey pubKey = factory.generatePublic(keySpec);

		Cipher c = Cipher.getInstance("RSA/ECB/PKCS1Padding");
		c.init(Cipher.ENCRYPT_MODE, pubKey);
		byte encryptedByte[] = c.doFinal(plainData.getBytes());
		String encrypted = Base64.encodeBase64String(encryptedByte);
		return encrypted;
	} catch (Exception ex) {
		logger.error(ex);
	}
	return null;
}
```

**Comment by terrafrost** [comment]
```php
$plaintext = $private->getPublicKey()->withPadding(RSA::ENCRYPTION_PKCS1)->decrypt($crypted);
```
Usually, with RSA, you encrypt with the public key and decrypt with the private key. You're trying to do the opposite - you're trying to decrypt with the public key, which phpseclib v3 doesn't support. Are you sure that that's really what you're wanting to do?

**Comment by terrafrost** [comment]
Is the PHP code you posted your attempt to port the Java code? Because if so the Java code is performing encryption whereas you're trying to perform decryption with the PHP code. The Java code is also doing `base64_encode` whereas the PHP code that you've posted isn't.
