### ISSUE TITLE
Call to a member function verify() on boolean

### ISSUE THREAD

**Issue by konco** [phpseclib/phpseclib#1620]
how to fix this, cause got response: Call to a member function verify() on boolean
```php
$data = 'test';
$x509 = new X509();
$privatekey = file_get_contents(storage_path('eMoneyMetfone.pri'));
$rsa = PublicKeyLoader::load($privatekey);
$signed = $rsa->sign($data);

$publickey = file_get_contents(storage_path('eMoneyMetfone.pub'));
$x509->loadX509($publickey);
$rsa = $x509->getPublicKey();
return $rsa->verify($data, $signed) ? 'verified' : 'unverified';
```

**Comment by terrafrost** [comment]
Post the contents of eMoneyMetfone.pub.

If it were truly an X.509 cert it should work. eg.:

```php
$x509 = new X509;
$x509->loadX509('-----BEGIN CERTIFICATE-----
MIIDITCCAoqgAwIBAgIQT52W2WawmStUwpV8tBV9TTANBgkqhkiG9w0BAQUFADBM
MQswCQYDVQQGEwJaQTElMCMGA1UEChMcVGhhd3RlIENvbnN1bHRpbmcgKFB0eSkg
THRkLjEWMBQGA1UEAxMNVGhhd3RlIFNHQyBDQTAeFw0xMTEwMjYwMDAwMDBaFw0x
MzA5MzAyMzU5NTlaMGgxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpDYWxpZm9ybmlh
MRYwFAYDVQQHFA1Nb3VudGFpbiBWaWV3MRMwEQYDVQQKFApHb29nbGUgSW5jMRcw
FQYDVQQDFA53d3cuZ29vZ2xlLmNvbTCBnzANBgkqhkiG9w0BAQEFAAOBjQAwgYkC
gYEA3rcmQ6aZhc04pxUJuc8PycNVjIjujI0oJyRLKl6g2Bb6YRhLz21ggNM1QDJy
wI8S2OVOj7my9tkVXlqGMaO6hqpryNlxjMzNJxMenUJdOPanrO/6YvMYgdQkRn8B
d3zGKokUmbuYOR2oGfs5AER9G5RqeC1prcB6LPrQ2iASmNMCAwEAAaOB5zCB5DAM
BgNVHRMBAf8EAjAAMDYGA1UdHwQvMC0wK6ApoCeGJWh0dHA6Ly9jcmwudGhhd3Rl
LmNvbS9UaGF3dGVTR0NDQS5jcmwwKAYDVR0lBCEwHwYIKwYBBQUHAwEGCCsGAQUF
BwMCBglghkgBhvhCBAEwcgYIKwYBBQUHAQEEZjBkMCIGCCsGAQUFBzABhhZodHRw
Oi8vb2NzcC50aGF3dGUuY29tMD4GCCsGAQUFBzAChjJodHRwOi8vd3d3LnRoYXd0
ZS5jb20vcmVwb3NpdG9yeS9UaGF3dGVfU0dDX0NBLmNydDANBgkqhkiG9w0BAQUF
AAOBgQAhrNWuyjSJWsKrUtKyNGadeqvu5nzVfsJcKLt0AMkQH0IT/GmKHiSgAgDp
ulvKGQSy068Bsn5fFNum21K5mvMSf3yinDtvmX3qUA12IxL/92ZzKbeVCq3Yi7Le
IOkKcGQRCMha8X2e7GmlpdWC1ycenlbN0nbVeSv3JUMcafC4+Q==
-----END CERTIFICATE-----');
$rsa = $x509->getPublicKey();
echo $rsa;
```
That works. `getPublicKey()` returns an object that's castable to a string via the `__toString` magic method.

You might have better luck if you did this instead:

```php
$publickey = file_get_contents(storage_path('eMoneyMetfone.pub'));
$rsa = PublicKeyLoader::load($publickey);
return $rsa->verify($data, $signed) ? 'verified' : 'unverified';
```
Even if eMoneyMetfone.pub were an X.509 cert (which I'm not convinced that it is; you'll need to provide it's contents for me to know for sure) that should still work. ie. when an X.509 cert is passed to it the public key will be extracted from the X.509 cert.

**Comment by konco** [comment]
so the case like this.
my partner provide me a public key and private key.
they said:
- Use RSA private key (provided) to decrypt
- Use RSA public key (provided) to encrypt
[pub_priv_key.zip](https://github.com/phpseclib/phpseclib/files/6034414/pub_priv_key.zip)


- Algorithm: RSA
- Public Format: X.509
- Private Format: PKCS#8
- Key size: 2048
- Padding: RSA/ECB/PKCS1Padding

Example:
token: 
`
NR4hkrQZGMJJl32wtAgo20oq5V6/AI+ejh4ysvx2ur12L2RLCZTy+0dwqn1fjkZNc7KY5Q/8p84rUni0jRY//NEJ7y2548YRxb0vcWJMyYRR12+G8XPqNOQ2fSuWoapjS5cw43H8bI4UFgBcKq+5JgUcEe8st/aXOfUIQeIrb8/GOePpLtroIKtm2fpu/PwIU6b7TGVJ80kefcDO//KWye0HwgaZT48Af1yFy53YvSVHfWZTE7J6d0aDHJ0IHyw5WwgajFdOxwwEqe7ATy+Qs/JjeaQWEuqXhsJjlo9jdanXcXMx7gXqxnG84rtoTWmKiwYRB6AIQLkSwZJ3mFD4EA==
`
when i try to decrypt the token and i provide them, the value after decrypt is correct.
```php
private function decrypt_data_new($encrypted)
{
    $crypted = base64_decode($encrypted);
    $priv_key= file_get_contents(storage_path('test.pri'));
    $rsa = PublicKeyLoader::load($priv_key)->withPadding(RSA::ENCRYPTION_PKCS1);
    $decrypted = $rsa->decrypt($crypted);

    return $decrypted;
}
```
the result after Decrypt: 2aec70a2274338c0014c488f35a4b395cbedd198cee3c377aac85aca8ee9e64e0b8526b13c8a5b15b60db5182bdf7bcc

now, i want to encrypt this string.
`
$textToEncrypt = "2478e27af578e11a6af86a8320562124240f5c972e8039cd9c564e53d643bb31|2aec70a2274338c0014c488f35a4b395cbedd198cee3c377aac85aca8ee9e64e0b8526b13c8a5b15b60db5182bdf7bcc";
`
some case need to encrypt the token after decrypt combined with their secret key.
when i post the result after encrypt to their endpoint, always return false.
```php
private function encrypt_data_new($textToEncrypt )
{
    $pub_key= file_get_contents(storage_path('test.pub'));
    $rsa = PublicKeyLoader::load($pub_key)->withPadding(RSA::ENCRYPTION_PKCS1);
    $ciphertext = $rsa->encrypt($textToEncrypt);
    $encrypt = base64_encode($ciphertext);
    return $encrypt;
}
```
because they said public key use Format: X.509.
so thats why i try using this function, but got error : `Call to a member function withPadding() on boolean`
```php
private function encrypt_using_X509($textToEncrypt )
{
    $publickey = file_get_contents(storage_path('eMoneyMetfone.pub'));
    $x509 = new X509();
    $x509->loadX509($publickey);
    $rsa = $x509->getPublicKey()->withPadding(RSA::ENCRYPTION_PKCS1);
    $ciphertext = $rsa->encrypt($textToEncrypt );
    $ciphertext = base64_encode($ciphertext);
    return $ciphertext;
}
```
i'm confused to encrypt this.

**Comment by terrafrost** [comment]
> because they said public key use Format: X.509.

It's definitely _not_ an X.509 cert. It's in a format that phpseclib calls PKCS8. Java calls it X509EncodedKeySpec. RFC5280 (which discusses X509 v3) calls it SubjectPublicKeyInfo.

> when i post the result after encrypt to their endpoint, always return false.

I can't tell you why you can't decrypt with their endpoint. idk what the source code for their endpoint looks like and idk what they're using for a private key. All I can say is that the public and private keys you posted do not correspond to one another:

https://github.com/phpseclib/phpseclib/issues/1619#issuecomment-783439009

If the private key they're using in their endpoint is the same one that's in the zip file then it'll never decrypt (the modulo doesn't match).

Maybe you could ask if they could provide the source code and key for their endpoint.

For that matter, maybe you could provide the full documentation for their endpoint. You posted a screenshot of it at https://github.com/phpseclib/phpseclib/issues/1619#issue-813411735 but maybe there are clues elsewhere in the document as to what's going on / what they're doing.

**Comment by konco** [comment]
this is the full documentation
[API_EMONEY_PAYMENT_v1.1.1.pdf](https://github.com/phpseclib/phpseclib/files/6037509/API_EMONEY_PAYMENT_v1.1.1.pdf)

You can go to page 12 for the flow I use.
maybe u can help me for this issue.

**Comment by terrafrost** [comment]
I'm not able to go through that document in any great detail atm but in giving it a very cursory glance I wonder if the character encoding matters.

Consider the string "abc". In ISO-8859-1 that's encoded as three bytes. In UTF-16, however, it's encoded as six bytes. eg. "a\0b\0c\0".

**Comment by terrafrost** [comment]
Sorry for the delay.

Anyway, I'd try this:

```php
private function encrypt_using_X509($textToEncrypt )
{
    $publickey = file_get_contents(storage_path('test.pub'));
    $rsa = PublicKeyLoader::load($publickey)->withPadding(RSA::ENCRYPTION_PKCS1);
    $ciphertext = $rsa->encrypt($textToEncrypt );
    $ciphertext = base64_encode($ciphertext);
    return $ciphertext;
}
```
If that doesn't work then the next thing I'd try is to see if I could get the Java code working. If it doesn't work with their own demo code then, at that point, I'd shoot them a support email, asking for further assistance. How familiar are you with Java?

I just figure that doing it in the language that they document would be optimal since (1) that's prob the language they're most familiar with and (2) that'll minimize the odds of them being able to out of hand dismiss the problem as being a problem with your code

**Comment by konco** [comment]
@terrafrost thanks for you help.
i already ask them.
I really appreciate your help.
