### ISSUE TITLE
Set terminal type to xterm

### ISSUE THREAD

**Issue by powerpbx** [phpseclib/phpseclib#1625]
I have some php code that currently uses `ssh2_shell()` combined with an [xterm.js](https://github.com/xtermjs/xterm.js/) front end to create an SSH client as a web page.  I am trying to convert it over to use phpseclib.   It mostly works but the cursor doesn't always display properly,  such as when I run `top`.  Is there any way to make the output compatible with `xterm` like you can do with the [ssh2_shell()](https://www.php.net/manual/en/function.ssh2-shell.php) `term_type` setting?

Looking through the code I found these two references to vt100

 https://github.com/phpseclib/phpseclib/blob/e2328a9477a83f6e5fd8b3c51cda12472e0d3d03/phpseclib/Net/SSH2.php#L2640-L2654

https://github.com/phpseclib/phpseclib/blob/e2328a9477a83f6e5fd8b3c51cda12472e0d3d03/phpseclib/Net/SSH2.php#L2767-L2779

Changing `vt100` to `xterm` seems to solve my problem although I have not extensively tested it.  Would it make sense to make this a configurable option at runtime?  Something like `$ssh->setTerminalType('xterm');`

**Comment by powerpbx** [comment]
Update:

I kind of have it working with the following code. It's really laggy though with a big delay between key presses.  So I am not quite there yet.  Also the terminal cursor is not showing quite right when running something like top.  I think that comes down to the terminal emulation because I see the same thing when using `ssh2_shell()` and changing terminal emulation there to vt100.


```
public function onMessage(ConnectionInterface $from, $msg) {
        $data = json_decode($msg, true);
        if (!isset($data)) {
            return;
        }
        switch (key($data)) {
            case 'data':
                $this->shell[$from->resourceId]->write($data['data']['data']);
                //usleep(800);
                $this->shell[$from->resourceId]->setTimeout(0.5);
                while ($line = $this->shell[$from->resourceId]->read()) {
                    $from->send(mb_convert_encoding($line, "UTF-8"));
                }
                break;
            case 'auth':
                if ($this->connectSSH2($data['auth']['server'], $data['auth']['port'], $data['auth']['user'], $data['auth']['password'], $from)) {
                    $from->send(mb_convert_encoding("Connected....", "UTF-8"));
                    $this->shell[$from->resourceId]->setTimeout(0.5);
                    while ($line = $this->shell[$from->resourceId]->read()) {
                        $from->send(mb_convert_encoding($line, "UTF-8"));
                    }
                } else {
                    $from->send(mb_convert_encoding("Error, can not connect to the server. Check the credentials", "UTF-8"));
                    $from->close();
                }
                break;
            default:
                if ($this->conectado[$from->resourceId]) {
                    while ($line = $this->shell[$from->resourceId]->read()) {
                        $from->send(mb_convert_encoding($line, "UTF-8"));
                    }
                }
                break;
        }
    }
```

**Comment by powerpbx** [comment]
Looking through the code I found these two references to vt100

 https://github.com/phpseclib/phpseclib/blob/e2328a9477a83f6e5fd8b3c51cda12472e0d3d03/phpseclib/Net/SSH2.php#L2648

**Comment by terrafrost** [comment]
Yah - I can do that. vt100 is definitely going to be the default terminal, however, because the terminal emulator that phpseclib has is a vt100 one - not an xterm one:

https://phpseclib.com/docs/commands#ansi-escape-codes

**Comment by terrafrost** [comment]
I added a `setTerminal()` method!:

https://github.com/phpseclib/phpseclib/commit/624f514e889b93ba881381048ce810266c658ad2
