### ISSUE TITLE
Notice: Undefined variable: sftp

### ISSUE THREAD

**Issue by ognik777** [phpseclib/phpseclib#1634]
Hi - I'm a newbie to PHP, using phpseclib to do housekeeping on remote backup dirs/files.  php7.4  centos 7.9

I googled my error - "Notice: Undefined variable: sftp" found a reply suggesting it was a bug, fixed in a later version.  As far as I can tell, I am using phpseclib3, I have this line in my code:
```
   set_include_path(get_include_path() . PATH_SEPARATOR . 'phpseclib3');
   print(get_include_path());
```
which outputs:     .:/opt/cpanel/ea-php74/root/usr/share/pear:phpseclib3

My code logs in OK, and lists the directories successfully - so I can be sure am using net/sftp 

Then I call the following function, to recursively delete a dir:
```
    function rmdir_r($dir) {   // Expects 2 dirs within dir-to-delete, each with files
        $flag = true;
        if ($sftp->chdir($dir)) {
            $objects = $sftp->nlist();  
            foreach ($objects as $object) { 
                if ($object = "." || $object = "..") {
                    myPrint ("ignoring " . $object);
                } 
                elseif ($sftp->delete($object)) {    //phpseclib has a delete (recursive)
                    myPrint ($object . " deleted ");
                }
                else {
                    myPrint ($object . " *** FAILED to delete *** ");
                    $flag = false;
                }
            }
        } 
        else {
            myPrint ("FAILED to enter " . $dir);
            $flag = false;
        }
        $sftp->chdir('..'); // up 1 dir to exit, back to main dir 
        if ($sftp->delete($dir)) {
            myPrint ($dir . " deleted ");          
        } else {
            myPrint ($object . " deleted ");
            $flag = false;
        }
        return $flag;
    }
```

The error ref's this line - if ($sftp->chdir($dir)) {

I have no idea how to fix this?

**Comment by terrafrost** [comment]
I'm surprised your code even works. `set_include_path(get_include_path() . PATH_SEPARATOR . 'phpseclib3');` is what you need to do to get 1.0 to work. With 3.0 you need to use a Composer generated autoloader. eg. you'd need to do `require __DIR__ . '/vendor/autoload.php';` at the top.

But since you say it does work...  I note that `$sftp` isn't defined in your `rmdir_r` method. Maybe you need to declare it a global in the method? eg. `global $sftp;` at the top? Or maybe it's a class variable, at which point you might need to do `$sftp = $this->sftp;` at the top?

**Comment by ognik777** [comment]
Thanks, you've hit the nail on the head, it appears liquid web have installed the wrong version, I changed my code to start:
````
    require __DIR__ . '/vendor/autoload.php'; 

    $sftp = new \phpseclib3\Net\SFTP($sftphost);

    if (!$sftp->login($sftpuser ,$sftppass)) {
        myPrint ("Login failed");
        exit;}
    else {
        myPrint ("Login succeeded");
    }
````
It failed with:
- Warning: require(/root/vendor/autoload.php): failed to open stream: No such file or directory in /root/tmp.php on line 77

 - Fatal error: require(): Failed opening required '/root/vendor/autoload.php' (include_path='.:/opt/cpanel/ea-php74/root/usr/share/pear') in /root/tmp.php on line 77  (which is require __DIR__ . '/vendor/autoload.php'; )


Note: I have googled for the below but don't know enough to decipher what I found, so would appreciate being treated like an idiot here :-)
1. Given I am unix-challanged and cannot rely on LW to install the right version, please advise how I can upgrade (or uninstall & install) the latest version?  Also, what is the command  to check the version of phpseclib?
2. Please confirm I have the right code in the require, apologies if I took it too literally.

Thanks again

**Comment by terrafrost** [comment]
So phpseclib3 needs to be installed with composer. Normally you'd do this on the CLI by doing `composer init` and then `composer require phpseclib/phpseclib:~3.0`. If you don't have access to the CLI, however, then what you could do is you could, on your local machine, in an empty directory, run those commands. Those command will create a vendor/ directory in that empty directory and then you could upload that vendor directory.

This technique should open up the whole Composer / Packagist ecosystem to you.

See https://getcomposer.org/ for more info about Composer!

**Comment by terrafrost** [comment]
Like phpseclib3 has a few dependencies that Composer will auto download for you so trying to duplicate this without Composer would kinda be a PITA!

**Comment by ognik777** [comment]
Making progress :-)
for security I created a new account - runphp01 and did the composer thing (with a little trial and error) - the composer.json file has ````"phpseclib/phpseclib": "~3.0"````   so I think we're good, so far.

I also made sftp a global variable, which also worked - thanks again.

One qeustion please -  I built my function rmdir_r because I don't know if sftp->delete  works when the dir has files AND dirs within it?

**Comment by terrafrost** [comment]
> I don't know if sftp->delete works when the dir has files AND dirs within it?

Yah - it'll do that by default. If you wanted it to just delete files and not directories recursively you'd need to do `$sftp->delete($path, false)`.
