### ISSUE TITLE
When having multiple open connections at the same time causes Invalid HMAC exception

### ISSUE THREAD

**Issue by sakarikl** [phpseclib/phpseclib#1636]
Following fails with: Invalid HMAC in vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3365

```PHP
$aSftp = new SFTP('HOST A');
$aSftp->setTimeout(25);

if (!$aSftp->login('username', 'password')) {
    throw new \Exception("Unable to establish SFTP connection a");
}

$bSftp = new SFTP('HOST B');
$bSftp->setTimeout(25);
$secret = RSA::load(file_get_contents('/path/to/key'), 'password');

if (!$bSftp->login('username', $secret)) {
    throw new \Exception("Unable to establish SFTP connection b");
}

var_dump($aSftp->stat('existing/file.txt'));

```

But if I switch connections other way around it works

```PHP
$bSftp = new SFTP('HOST B');
$bSftp->setTimeout(25);
$secret = RSA::load(file_get_contents('/path/to/key'), 'password');

if (!$bSftp->login('username', $secret)) {
    throw new \Exception("Unable to establish SFTP connection b");
}

$aSftp = new SFTP('HOST A');
$aSftp->setTimeout(25);

if (!$aSftp->login('username', 'password')) {
    throw new \Exception("Unable to establish SFTP connection a");
}

var_dump($aSftp->stat('existing/file.txt'));

```

**Comment by sakarikl** [comment]
HOST A offers only following key exchange methods: diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1,diffie-hellman-group14-sha1

if relevant.

**Comment by sakarikl** [comment]
As a workaround I now have only one connection alive at any given moment.

**Comment by terrafrost** [comment]
I think you sent me an email about this? If so I responded. If not then could you post the SSH logs?

Thanks!

**Comment by sakarikl** [comment]
@terrafrost I sent you an email that contains SSH logs.

**Comment by terrafrost** [comment]
Just responded to your email. Quoting my response:

> I think what's going on is that you're creating a zip file after you create the directory. The creation of the zip file is taking 6.5s in the case of ssh1.txt and 7.3s in the case of log.txt from your first email. During that time the connection is being closed. Probably feof() is returning false or maybe fputs() is returning false (which would indicate that the connection is being closed).
> 
> In ssh2.txt, which doesn't show the problem, 0.05s passes between the directories creation and the file upload.
> 
> Try creating the zip file _before_ you connect to the SSH server and see if that helps.
> 
> Because PHP doesn't have very good async support it can't send keep-alive packets while the zip file is being created.

**Comment by sakarikl** [comment]
Actually no. I have no zip file creations at all. And I sent you only one email. Did you maybe respond to wrong ticket? (Haven't received any mail)

**Comment by terrafrost** [comment]
I'm able to reproduce the problem.

Doing `$bSftp->setPreferredAlgorithms(['client_to_server' => ['crypt' => ['aes128-ctr']], 'server_to_client' => ['crypt' => ['aes128-ctr']]]);` in the second example, after `$bSftp = new SFTP('HOST B')` does the trick in the first example. Obviously that ought not be necessary but I'm still looking into this.

Thanks!

**Comment by terrafrost** [comment]
Also, sorry about the miscommunication! And you're right - I did reply to the wrong ticket lol

**Comment by terrafrost** [comment]
I've figured out what's going on. The problem is with `$cipher_name_openssl_ecb`. It's declared static, which isn't a problem for most ciphers, but it is a problem for AES since AES supports multiple key sizes. ie. the ECB mode name for OpenSSL changes depending on the key size.

The solution is to make it so that that variable isn't static. I need to head into work now but I'll try to do this after work.

Thanks!

**Comment by terrafrost** [comment]
I think https://github.com/phpseclib/phpseclib/commit/03e9060cbbfe719e56bb6687df3d4ea10595ddd4 should fix this.

Thanks!
