### ISSUE TITLE
loadPlugins in Crypt/Common/AsymmetricKey extra check on filename

### ISSUE THREAD

**Issue by rotweiller92** [phpseclib/phpseclib#1637]
Issue came up because when copying project it created ._FILENAME.php backup files.

Not strictly an issue but it can be useful an extra check up on filename like strpos or a pattern match, like:
```
$name = $file->getBasename('.php');
if (strpos($name,'.')===0) {
    continue;
}```

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/b7eaee4977b02f610ac01d0b2d4f733f3b82e8d1 should do this.

Thanks!
