### ISSUE TITLE
Generating pub+priv key

### ISSUE THREAD

**Issue by iamtunde** [phpseclib/phpseclib#1645]
I know this is not an issue, just can't find enough resources on how to integrate this library with Laravel.

What is the best way to generate public and private keys. I have installed phpseclib via composer like so;

```
"require:"{
      "...."
      "phpseclib/phpseclib": "~3.0",
      "..."
}
```

and in my controller file I have this.
```
use phpseclib3\Crypt\RSA;

class SSHService {

    public function generate($name) {
        $rsa = new RSA();

        $keys = $rsa->createKey(4096);
        
        $this->store($keys, $name);
    }
}
```

But this line `$rsa = new RSA();` throws this error `Undefined type 'phpseclib3\Crypt\RSA'.`

Perhaps I'm doing something wrongly, kindly point me in the right direction.

**Comment by terrafrost** [comment]
With phpseclib v3 you create keysbydoingthis:

```
$private = RSA::createKey();
$public = $private->getPublicKey();
```
That said, the error you're getting is kinda weird. If the `use`  wasn't there or was incorrect you'd get `Fatal error: Uncaught Error: Class "RSA" not found`.

Just a shot in the dark but did you do `composer update` after you added phpseclib to composer.json?

**Comment by iamtunde** [comment]
Sorry for the late reply.

Oh yes, I did ran `composer update` and installed the dependencies required.

**Comment by iamtunde** [comment]
Thank you for your response, I've been able to generate public and private keys. however, I don't how to set public key format to open SSH, like in the example [http://phpseclib.sourceforge.net/rsa/examples.html](http://phpseclib.sourceforge.net/rsa/examples.html) using this library.

**Comment by terrafrost** [comment]
When you first visit phpseclib.sourceforge.net and go to one of the examples a popup appears asking which version of phpseclib you have:

[![enter image description here][1]][1]

If you select 3.0 you'll be redirected to https://phpseclib.com/

If you had already been using phpseclib.sourceforge.net for 2.0 then you'll have to update your bookmarks. https://phpseclib.com/ is where the 3.0 documentation now lives.

  [1]: https://i.stack.imgur.com/1kdqK.jpg

**Comment by iamtunde** [comment]
Thank you @terrafrost for your swift response, I've been able to generate keys and connect to the server.
