### ISSUE TITLE
Hanging on PHP Exec

### ISSUE THREAD

**Issue by MikeFairbrother** [phpseclib/phpseclib#1655]
I am running a few commands with $ssh->exec so they run directly on the server with the intention of it not taking up PHP resources and causing the page to hang. I wanted to run the command in exec and let the page continue as normal.

I've got a few commands, such as deleting the contents of a folder within the /root/ of the linux server and then using tar to extract a .tar file in to a directory.

It work's perfectly fine but the PHP page times out (even though the command(s) run on the server until they've finished...as the exec command has been sent.

The commands are separated with ; in exec and they end with & so they run in the background.

How can I get the PHP page to stop hanging though?

Once it's sent the command within $ssh->exec('<here>'); I want it to move on. The tar is so large it takes about 45 minutes to full extract.

Thanks in advance

**Comment by terrafrost** [comment]
Doing [nohup](https://en.wikipedia.org/wiki/Nohup) before the commands might help.

Ultimately, what you do is prob going to have to be a Linux solution. If you were to do something like open the SSH channel to run the command, run it and then close the channel without waiting for the response then the server would, unless you did something like nohup, probably just kill the command, prematurely.

**Comment by MikeFairbrother** [comment]
I wrapped the whole command in ( ) - this resolved it by grouping the commands and then the final & runs the whole group in the background.
