### ISSUE TITLE
PHP Notice: Trying to access array offset on value of type bool (Version 2 + PHP 7.4)

### ISSUE THREAD

**Issue by dmytroklyman** [phpseclib/phpseclib#1656]
Using of version 2 (in my case 2.0.31) with PHP 7.4 can produce the following notices: 

PHP Notice: Trying to access array offset on value of type bool in .../phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3516

```
$payload = $this->_get_binary_packet(); // Can return bool
...
switch (ord($payload[0])) {
...
```

Till 7.4 code like `false[0]` returns null, but starting from version 7.4 it produces notices.

**Comment by terrafrost** [comment]
Nice find! Altho I've elected to go with a different fix:

https://github.com/phpseclib/phpseclib/commit/915d1d8ca96b4f7dfe973a20f256fd31fb335ea3

Thanks for reporting the issue!
