### ISSUE TITLE
Problems with loading .PEM data if there are any comments/text before the -----BEGIN CERTIFICATE----- marker

### ISSUE THREAD

**Issue by krestenk** [phpseclib/phpseclib#1659]
This issue showed up at updates from 2.0.30 to 2.0.31 (or 3.0.8) because we happend to have a Root certificate we loaded which had the subject and issuer in the header. 

I suspect from the changes that it is the fix for this issue: https://github.com/phpseclib/phpseclib/issues/1568 which caused this. 

From my testing it is any text which is not whitespace before the marker which triggers this, the actual certificate does not appear to matter.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/0a2dc24489f9a05efb1094502429b6de416545b8 should fix this.

Thanks!
