### ISSUE TITLE
Error: Class "Crypt_RSA" not found

### ISSUE THREAD

**Issue by W1DJM** [phpseclib/phpseclib#1662]
Installed the latest version of phpseclib (3.0) using composer (php composer.phar require phpseclib/phpseclib:~3.0) and put it below a directory that is already in the PHP include path (/var/Classes). The simple test below fails on the 5th line when trying to create an instance of Crypt_RSA.

```
<?php
require 'vendor/autoload.php';
$modulus  = 'somevalue';
$exponent = 'ZZZZ';
$rsa      = new Crypt_RSA();
$modulus  = new Math_BigInteger(base64_decode($modulus), 256);
$exponent = new Math_BigInteger(base64_decode($exponent), 256);
$rsa->loadKey(['n' => $modulus, 'e' => $exponent]);
echo $rsa;
```
The complete error message is:

_Fatal error: Uncaught Error: Class "Crypt_RSA" not found in test.php:5_

Using PHP 8.0.6 from the command line.

**Comment by terrafrost** [comment]
You're trying to use the 1.0 API with phpseclib 3.0.

Here's your 1.0 API code rewritten with the 2.0 API:

```php
<?php
require 'vendor/autoload.php';
use phpseclib\Crypt\RSA;
$modulus  = 'somevalue';
$exponent = 'ZZZZ';
$rsa      = new RSA();
$modulus  = new Math_BigInteger(base64_decode($modulus), 256);
$exponent = new Math_BigInteger(base64_decode($exponent), 256);
$rsa->loadKey(['n' => $modulus, 'e' => $exponent]);
echo $rsa;
```
See http://phpseclib.sourceforge.net/2.0.html for more info.

Here's your code rewritten with the 3.0 API:

```php
<?php
require 'vendor/autoload.php';
use phpseclib3\Crypt\PublicKeyLoader;
$modulus  = 'somevalue';
$exponent = 'ZZZZ';
$modulus  = new Math_BigInteger(base64_decode($modulus), 256);
$exponent = new Math_BigInteger(base64_decode($exponent), 256);
$rsa = PublicKeyLoader::load([
    'n' => $modulus,
    'e' => $exponent
]);
echo $rsa;
```
More info: https://phpseclib.com/docs/rsa#raw-rsa-public-keys

**Comment by terrafrost** [comment]
I updated my examples to reflect the new class name for BigInteger.

**Comment by W1DJM** [comment]
Holy smokes! Thank you, thank you, thank you. I couldn't pull that detail out of the resources. Appreciate the very quick response!

**Comment by W1DJM** [comment]
Pardon one more interrupt if I may, how do I use the results of that code to encrypt a string using SHA-256 RSA?

**Comment by terrafrost** [comment]
Sorry for the delay.

By default phpseclib uses OAEP padding, which has two types of hashes - the regular hash and the MGF hash. OAEP is less commonly used than PKCS1 but it's also more secure.

Assuming you're using the more common PKCS1 thing then you'd do `$rsa->withPadding(RSA::ENCRYPTION_PKCS1)->encrypt($plaintext);`. PKCS1 encryption does not utilize a hash.

If you want to do OAEP encryption then you can do:

`$rsa->withHash('sha256')->withMGFHash('sha256')->encrypt('...');`

More info: https://phpseclib.com/docs/rsa#encryption--decryption

**Comment by W1DJM** [comment]
Please don't apologize, I very much appreciate the response. That seemed to work but it says my message is too long at only 29 characters. I will apologize again for bothering you and taking up your time. I understand that the documentation and examples for 3.0 are still being worked on and suspect I would not have to be asking questions if that section were complete.

**Comment by terrafrost** [comment]
The length depends on the mode, as elaborated at https://phpseclib.com/docs/rsa#encryption--decryption

So for `RSA::ENCRYPTION_OAEP` the max length of the plain text is `($key->getLength() - 2 * $key->getHash()->getLength() - 16) >> 3`.

For `RSA::ENCRYPTION_PKCS1` the max length of the plain text is `($key->getLength() - 88) >> 3`.

Are you trying to implement to some spec or something?

**Comment by W1DJM** [comment]
Thanks again and yes, I am trying to encrypt the URL string that is sent to PayPoint, now FISERV, to initiate a payment without exposing the dollar amount or other information including the return URL.

I have the Exponent, Modulus, and a URL encoded string that needs to be sent. Thanks to your earlier assistance I can generate the public key. But I'm having one heck of a time getting it encrypted since the URL encoded string that needs to be encrypted and sent will be 350 characters or more (it is variable depending on the person name, address and e-mail address).

Thank you again for your patience and assistance.

This is a quote from the PayPoint/FISERV documentation on what they are expecting encryption wise:

> Encryption Option

> PayPoint supports accepting query string data that is encrypted. This is achieved by encrypting the query string using SHA-256 RSA key to be provided by PayPoint Support Team and sending this with the new field “en=” When PayPoint receives the query string that begins with “en=”, the string will be decrypted using SHA-256 RSA Key and process the data.

> Here’s an example of an encoded query string, which is received by PayPoint in clear text:

> https://uat.thepayplace.com/epayconsumerweb/train/training1/trainapp/default.aspx?returnurl= http%3A%2F%2Fwww.yourmerchantwebsite.com&amount=120.00&custom= 12345%2Ctomtestp%2C120.00

> Below is an example of the query string above sent to Consumer Payments using encryption.

> https://uat.thepayplace.com/epayconsumerweb/train/training1/trainapp/default.aspx?en=150717 121608|345dd16d6fbe22c22909bba274b17ea08e76ac2e5cce863f0ec0d25d4b2c054b514c99ddd 337a4cc9da3b8b52697e6007ac1629f612b42c8b643c642c0d3dd99d5ce6926fd8bcb540fb9cbbf65 90b5f6e9d54bb5dc80f15a9749052edf73c37d5c5da341232e1c91a4dac9654648bc85d00a53af18 8c6c5374f84ceec57442e9
> Because PayPoint can identify whether the query string is encrypted or not, there is no coordinated migration process needed to switch to an encrypted query string.

**Comment by terrafrost** [comment]
I see the documentation at https://www.bidnet.com/bneattachments?/516696165.pdf . That documentation is most useless lol.

They say "_ encrypting the query string using SHA-256 RSA key_". idk what that even means lol. OAEP is the only encryption mode that takes a hash as a parameter but that one has two different hash algorithms as discussed above.

If they could provide sample code in _any_ language then it'd be easy enough to infer what they mean. But like even with Java...  so with Java you pass a string description of the "mode" to `Cipher.getInstance`. eg. maybe you'd do `RSA/ECB/PKCS1Padding` or maybe you'd do `RSA/ECB/OAEPWithMD5AndMGF1Padding`. But which "mode" would you do in Java for "SHA-256 RSA"? idk!

I'd maybe ask them if they can provide some sample code. We can build a PHP solution off of that. As is there's not enough information with which to work from and their documentation is just god awful!

**Comment by W1DJM** [comment]
Useless is a generous description. I won't go into how difficult it was to get to the point where I could get things to work using plain URLs.

That said I did manage to get them to send me a ZIP file with examples that are written in a C variant but they didn't hep me I'm afraid. My C skills have been rusting for over 40 years. I will include the ZIP file and perhaps you will be able to interpret it.

Thanks again for your assistance.

[Encryption_Sample.zip](https://github.com/phpseclib/phpseclib/files/6569576/Encryption_Sample.zip)

**Comment by terrafrost** [comment]
Looking at their code I think what you'd need to do is this:

```
use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Math\BigInteger;

$exponent = "AQAB";
$modulus = "wx121rWeZMwb8NXpdA3VC57e6+MpTcxR9TP5UYUjtjA66yk0xQatpm9iO2krCAqLZKNtgkbdwdMdaNkBxITIQDCwxvzp8pkmKV5QLl0IoOiaFcsU1S9F6ey92uC2C5+9uo2q/sJmoFVIFeYdhOuhFBISmlOdZgwvCtRL2c2zcaipJ2B+HN/U3sJyrHllPdT7IJ1n9JaN4Y30h6sCKoptkosgTodiPAOa7NGQYwYpbdbWBnl7C7z8rz+Y4vFh/zsYBHhvnODaRXtMLkQ5NMd7Q/emLCTge7RReQviC2XTBbXuYnljsaUf4txZgX1QwKJl2xcstc5gnA6Cjxq5VnBeYr6nQZcXsRJu32qi70+srGJia+s2C4lnPtW3c1vF1uxy83yqZl7JCimwhq4DmU+qNWQ+Mt4kPQbFT35eBTvBorH/Wk+qM+o3cdUjAWh9akBsCJYaqSHLiGL3/pkX/uWw+ueXf9k0spiEKHt0Z1RHpoNuqyrN7rgNnu2EaQfpbuSCZeemIuLrByjivdPuK87r9ZwOND1w2B47WEPP+qZY/vrbmK2dGiGALV8MTRWCG3WMEPCBs5DQzmqP+wlFMTpBuj3lSNLpS9jWja7f4JBhoZ6fxdnnmji6D1FEWJYZgUfT9b7uHFrp9mQK85DV5DFAREWI/owgGQYHhsPChe0DhGk=";

$key = [
    'n' => new BigInteger(base64_decode($modulus), 256),
    'e' => new BigInteger(base64_decode($exponent), 256)
];
$key = PublicKeyLoader::load($key);
$key = $key->withPadding(RSA::ENCRYPTION_PKCS1);
echo base64_encode($key->encrypt('test'));
```
The key is 4096 bits, which gives a max supported length of 501 bytes.

Here's a simplified / more standalone version of their (C#) code:

```
using System;
using System.Security.Cryptography;
using System.Text;

class Test
{
    static void Main()
    {
        var exponent = "AQAB";
	var modulus = "wx121rWeZMwb8NXpdA3VC57e6+MpTcxR9TP5UYUjtjA66yk0xQatpm9iO2krCAqLZKNtgkbdwdMdaNkBxITIQDCwxvzp8pkmKV5QLl0IoOiaFcsU1S9F6ey92uC2C5+9uo2q/sJmoFVIFeYdhOuhFBISmlOdZgwvCtRL2c2zcaipJ2B+HN/U3sJyrHllPdT7IJ1n9JaN4Y30h6sCKoptkosgTodiPAOa7NGQYwYpbdbWBnl7C7z8rz+Y4vFh/zsYBHhvnODaRXtMLkQ5NMd7Q/emLCTge7RReQviC2XTBbXuYnljsaUf4txZgX1QwKJl2xcstc5gnA6Cjxq5VnBeYr6nQZcXsRJu32qi70+srGJia+s2C4lnPtW3c1vF1uxy83yqZl7JCimwhq4DmU+qNWQ+Mt4kPQbFT35eBTvBorH/Wk+qM+o3cdUjAWh9akBsCJYaqSHLiGL3/pkX/uWw+ueXf9k0spiEKHt0Z1RHpoNuqyrN7rgNnu2EaQfpbuSCZeemIuLrByjivdPuK87r9ZwOND1w2B47WEPP+qZY/vrbmK2dGiGALV8MTRWCG3WMEPCBs5DQzmqP+wlFMTpBuj3lSNLpS9jWja7f4JBhoZ6fxdnnmji6D1FEWJYZgUfT9b7uHFrp9mQK85DV5DFAREWI/owgGQYHhsPChe0DhGk=";
	var padding = false;
	var data = "test";

        RSAParameters keyInfo = new RSAParameters() {
            Exponent = Convert.FromBase64String(exponent),
            Modulus = Convert.FromBase64String(modulus)
        };
	var rsaPub = new RSACryptoServiceProvider();

	rsaPub.ImportParameters(keyInfo);
	var ciphertextBytes = rsaPub.Encrypt(Encoding.ASCII.GetBytes(data), padding);

        Console.WriteLine(BitConverter.ToString(ciphertextBytes).Replace("-", ""));
    }
}
```
Their documentation says SHA-256 RSA but since they're doing PKCS1 no hash is actually used.

In their example, their query_str variable is only 98 bytes long.

Also, based on the comments in their Support_Classes.cs you might think OAEP was being used but that does not appear to be the case. From their code:

```
	public class EncryptionRSA {
		public static string Encrypt(string data, string keyid, string exponent, string modulus, bool padding = false) {
			byte[] bytes = null;
			RSAParameters keyInfo = new RSAParameters() { Exponent = Convert.FromBase64String(exponent), Modulus = Convert.FromBase64String(modulus) };
			using (RSACryptoServiceProvider rsa = new RSACryptoServiceProvider()) {
				//Import the RSA Key information. This only needs to include the public key information.
				rsa.ImportParameters(keyInfo);
				//Encrypt the passed byte array and specify OAEP padding.  OAEP padding is only available on Microsoft Windows XP or later.
				bytes = rsa.Encrypt(Encoding.ASCII.GetBytes(data), padding);
			}
			return $"{keyid}|{bytes.ToHexString()}";
		}
	}
```
OAEP is only used if padding is set to true but in the method definition it default to false if it's not otherwise provided.

In Program.cs, when they call it, it doesn't have that padding parameter set so the default of false is used:

```
data = EncryptionRSA.Encrypt(query_str, _rsa_keyid, _rsa_exponent, _rsa_modulus);
```
LMK if that works for you. Failing that what you could, I suppose, do, is compile their code (you can compile it on Linux) and try it out for yourself.

**Comment by W1DJM** [comment]
I hope you have someplace I can buy you a virtual coffee or something :) The first block of code you provided seems like it will do the job however this line, 

`$key = $key->withPadding(RSA::ENCRYPTION_PKCS1); `

is throwing an error: 

**Fatal error: Uncaught Error: Class "RSA" not found**

**Comment by terrafrost** [comment]
> I hope you have someplace I can buy you a virtual coffee or something :)

You can make a PayPal donation!:

https://www.paypal.me/phpseclib

> *Fatal error: Uncaught Error: Class "RSA" not found*

You'd need to do `use phpseclib3\Crypt\RSA` at the top

**Comment by W1DJM** [comment]
You can't see me jumping up and down but I am! Even though the encrypted data doesn't appear to be getting handled correctly on the receiving end I am at least getting to the page I expect. Just in case they come back and say I should be using the private key instead of the public key, what needs to be changed in the first suggestion you sent above which seems to be doing fine for using the public key?

**Comment by terrafrost** [comment]
> Even though the encrypted data doesn't appear to be getting handled correctly on the receiving end I am at least getting to the page I expect.

Are you getting any sort of error message?

I guess what you could try to do is to take the simplified C# code that I posted, swap out it's modulus with your modulus, update the data as appropriate, and then compile / run it. To install it on Ubuntu you'd need to follow these directions: https://www.mono-project.com/download/stable/#download-lin After that you'd compile it by doing `csc test.cs && mono test.exe`.

If that works - or doesn't work - that'd be useful information, either way.

> Just in case they come back and say I should be using the private key instead of the public key, what needs to be changed in the first suggestion you sent above which seems to be doing fine for using the public key?

phpseclib v3 doesn't actually let you encrypt stuff with the private key - just the public key. In theory the public key is, just that, public, so anyone could have it. For encryption that's not an issue because it the intended recipient is the only one who can decrypt (since they're the only one who would have the private key). If you encrypted with your private key then anyone with your public key (which is generally assumed in theoretical models to be everyone) could decrypt it so it wouldn't be very secret. Now, for signature creation / verification, this is a useful property, but not so much for encryption / decryption.

**Comment by W1DJM** [comment]
Thanks once again for responding. There is no error message shown. The other side simply isn't seeing the values that have been encrypted and sent to them. I am putting this in their lap until/unless they can can prove to me that something is wrong with how the encryption is being done. I've gotten the sense that this is an area that they haven't dealt with much yet but I'm hopeful we'll be to the bottom of things soon.
