### ISSUE TITLE
v3 cannot set OpenSSL options

### ISSUE THREAD

**Issue by maxsky** [phpseclib/phpseclib#1663]
in v2 could set options such as:

```php
$aes = new AES($mode);

$aes->openssl_options = OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING;
```

but v3 removed `openssl_options` member variable, so I dont know how to set OpenSSL options.

**Comment by terrafrost** [comment]
Why are you trying to set them?

In phpseclib v2 I had that mainly as a way to toggle between PHP 5.3 support and 5.4+ support:

https://github.com/phpseclib/phpseclib/blob/613643413912cd418906ca428cc9922a4cb89871/phpseclib/Crypt/Base.php#L1640-L1646

Knowing the use case might motivate me to add the variable back or give me some idea as to what alternatives might exist that'd still satisfy your use case.

**Comment by maxsky** [comment]
In the WeChat official account, I need receive and decrypt message from WeChat, and reply with encrypt message to WeChat. If I cant set openssl_options, I can only use OpenSSL method like this:

```php
$encrypted = openssl_encrypt($text, 'AES-256-CBC', $this->aesKey, OPENSSL_ZERO_PADDING, $iv);
$decrypted = openssl_decrypt($encrypted, 'AES-256-CBC', $this->aesKey, OPENSSL_ZERO_PADDING, $iv);
```

I tried using `disablePadding()` in phpseclib v3, but whether encrypt or decrypt will error.

theres document and SampleCode in this page: https://developers.weixin.qq.com/doc/offiaccount/en/Message_Management/Message_encryption_and_decryption_instructions.html

**Comment by terrafrost** [comment]
I'm curious what the phpseclib v2 code that you were using is that was able to successfully interoperate with this.

Looking at their PHP SampleCode here's what I'm seeing:

```php
	/**
	 * 对明文进行加密
	 * @param string $text 需要加密的明文
	 * @return string 加密后的密文
	 */
	public function encrypt($text, $appid)
	{

		try {
			//获得16位随机字符串，填充到明文之前
			$random = $this->getRandomStr();
			$text = $random . pack("N", strlen($text)) . $text . $appid;
			// 网络字节序
			$size = mcrypt_get_block_size(MCRYPT_RIJNDAEL_128, MCRYPT_MODE_CBC);
			$module = mcrypt_module_open(MCRYPT_RIJNDAEL_128, '', MCRYPT_MODE_CBC, '');
			$iv = substr($this->key, 0, 16);
			//使用自定义的填充方式对明文进行补位填充
			$pkc_encoder = new PKCS7Encoder;
			$text = $pkc_encoder->encode($text);
			mcrypt_generic_init($module, $this->key, $iv);
			//加密
			$encrypted = mcrypt_generic($module, $text);
			mcrypt_generic_deinit($module);
			mcrypt_module_close($module);

			//print(base64_encode($encrypted));
			//使用BASE64对加密后的字符串进行编码
			return array(ErrorCode::$OK, base64_encode($encrypted));
		} catch (Exception $e) {
			//print $e;
			return array(ErrorCode::$EncryptAESError, null);
		}
	}
```
PKCS7Encoder::encode is defined thusly:

```php
	public static $block_size = 32;

	/**
	 * 对需要加密的明文进行填充补位
	 * @param $text 需要进行填充补位操作的明文
	 * @return 补齐明文字符串
	 */
	function encode($text)
	{
		$block_size = PKCS7Encoder::$block_size;
		$text_length = strlen($text);
		//计算需要填充的位数
		$amount_to_pad = PKCS7Encoder::$block_size - ($text_length % PKCS7Encoder::$block_size);
		if ($amount_to_pad == 0) {
			$amount_to_pad = PKCS7Encoder::block_size;
		}
		//获得补位所用的字符
		$pad_chr = chr($amount_to_pad);
		$tmp = "";
		for ($index = 0; $index < $amount_to_pad; $index++) {
			$tmp .= $pad_chr;
		}
		return $text . $tmp;
	}
```
One problem I'm seeing, right off the bat, is that MCRYPT_RIJNDAEL_128 doesn't have a block size of 32 - it has a block size of 16. And yet their PKCS7Encoder class treats it like it's a block size of 32.

Their _key_ is 32 bytes (base64_decode the key in demo.php after appending an = to it) but their _block size_ is 16.

So in the phpseclib I would disable padding and then write your own custom padding method. You could repurpose their PKCS7Encoder class or you could do this (untested):

```php
function customPad($str)
{
    $length = strlen($text);

    $pad = 32 - ($length % 32);
    return str_pad($str, $length + $pad, chr($pad));
}
```

**Comment by maxsky** [comment]
now I used this for encrypt

```php
public function encrypt(string $text) {
    // get random string
    $random = ex_str_rand();

    $text = $random . pack('N', strlen($text)) . $text . $this->appId;

    // use custom fill method for fill-in with plaintext
    $text = $this->encode($text);

    $iv = substr($this->aesKey, 0, 16);

    // encrypt
    $encrypted = openssl_encrypt($text, 'AES-256-CBC', $this->aesKey, OPENSSL_ZERO_PADDING, $iv);

    return $encrypted ?: -40006;
}
```

or use v2:

```php
$aes = new AES(AES::MODE_CBC);

$aes->setKey($this->aesKey);
$aes->setKeyLength(256);
$aes->setIV($iv);
$aes->disablePadding();

$aes->openssl_options = OPENSSL_ZERO_PADDING;

// encrypt
$encrypted = $aes->encrypt($text);
```

**Comment by terrafrost** [comment]
You should be able to achieve the same result thusly:

```php
$aes = new AES(AES::MODE_CBC);

$aes->setKey($this->aesKey);
$aes->setIV($iv);
$aes->disablePadding();

// encrypt
$encrypted = base64_encode($aes->encrypt($text));
```
`$aes->setKeyLength(256)` is only needed if you're using a key that's 24 bytes or less. Like it'll NULL-pad keys that are > 24 bytes to 32 bytes if the key length isn't explicitly defined. It'll NULL-pad keys between 16 and 24 bytes to 24 bytes and keys less than 16 bytes to 16 bytes.

At least that's how phpseclib 2.0 works. phpseclib 3.0 won't accept keys that aren't either 16, 24 or 32 bytes long and `$aes->setKeyLength(256)` doesn't change that behavior.

**Comment by terrafrost** [comment]
Like the only difference between what you're doing and what phpseclib is doing is that phpseclib isn't using OPENSSL_RAW_DATA as an option. Without that openssl_encrypt() returns base64 encoded data.
