### ISSUE TITLE
TypeError: decbin(): Argument #1 ($num) must be of type int, float given on armhf architecture

### ISSUE THREAD

**Issue by utkarsh2102** [phpseclib/phpseclib#1666]
Hey,

The following lines of code doesn't work on `armhf` architecture with PHP 8:

https://github.com/phpseclib/phpseclib/blob/333d2f9ffd35d1daaf339019fd28a95552454c8c/phpseclib/Math/BigInteger.php#L661-L666

However, the following patch fixes that:
```
--- a/phpseclib/Math/BigInteger.php
+++ b/phpseclib/Math/BigInteger.php
@@ -659,10 +659,10 @@
         $hex = $this->toHex($twos_compliment);
         $bits = '';
         for ($i = strlen($hex) - 8, $start = strlen($hex) & 7; $i >= $start; $i-=8) {
-            $bits = str_pad(decbin(hexdec(substr($hex, $i, 8))), 32, '0', STR_PAD_LEFT) . $bits;
+            $bits = str_pad(decbin((int) hexdec(substr($hex, $i, 8))), 32, '0', STR_PAD_LEFT) . $bits;
         }
         if ($start) { // hexdec('') == 0
-            $bits = str_pad(decbin(hexdec(substr($hex, 0, $start))), 8, '0', STR_PAD_LEFT) . $bits;
+            $bits = str_pad(decbin((int) hexdec(substr($hex, 0, $start))), 8, '0', STR_PAD_LEFT) . $bits;
         }
         $result = $this->precision > 0 ? substr($bits, -$this->precision) : ltrim($bits, '0');
 

```

Let me know if you're interested, I could create a PR for this. Thanks!

**Comment by terrafrost** [comment]
The patch and the code snippet you linked to aren't the same. More specifically, the patch doesn't reflect the changes that were introduced with https://github.com/phpseclib/phpseclib/commit/b2b867f032949fab435370061a2a00dc31b22d9a#diff-dcbaddf33b7e8788a9b70a3945d971af58bb44ccf0da3fb1bac326b895ecddd6

I'm thinking that if you upgrade to the latest version 2.x or 3.x version of phpseclib (both of the latest versions of each branch should have that patch in them) that the issue that you're trying to fix with that patch should be fixed?

**Comment by utkarsh2102** [comment]
Perfect, okay. That makes sense!
