### ISSUE TITLE
Cannot login to Amazon linux 2 machine

### ISSUE THREAD

**Issue by ulshamim** [phpseclib/phpseclib#1667]
I have tried the below code but cannot log in to the Amazon Linux machine whereas I can log in to the ubuntu machine. 

```
use phpseclib3\Net\SSH2;
use phpseclib3\Crypt\PublicKeyLoader;
$ssh = new SSH2($instanceIp);
            $key = PublicKeyLoader::load('abcd.pem');
            if (!$ssh->login('ec2-user', $key)) {
                return redirect()->back()->with('customError', 'Cannot login to remote machine.');
            } else {
```

I have already tried to log in using ssh command from the terminal which is working but using PHP code it is not working.

**Comment by terrafrost** [comment]
Can you post the SSH logs?

You can get them by doing `define('NET_SSH2_LOGGING', true)` at the top and then `echo $ssh->getLog()` before the `'Cannot login to remote machine.'` error.

**Comment by ulshamim** [comment]
Thanks for the reply. Here is the log

```
array (
  0 => '<-',
  1 => '->',
  2 => '-> NET_SSH2_MSG_KEXINIT (since last: 0.4301, network: 0.0001s)',
  3 => '<- NET_SSH2_MSG_KEXINIT (since last: 0.0686, network: 0.0685s)',
  4 => '-> NET_SSH2_MSG_KEX_ECDH_INIT (since last: 0.0026, network: 0s)',
  5 => '<- NET_SSH2_MSG_KEX_ECDH_REPLY (since last: 0.9964, network: 0.9963s)',
  6 => '-> NET_SSH2_MSG_NEWKEYS (since last: 0.0009, network: 0.0001s)',
  7 => '<- NET_SSH2_MSG_NEWKEYS (since last: 0.0001, network: 0s)',
  8 => '-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0007, network: 0s)',
  9 => '<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 1.0516, network: 1.0515s)',
  10 => '-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0003, network: 0.0001s)',
  11 => '<- NET_SSH2_MSG_USERAUTH_FAILURE (since last: 0.5912, network: 0.5911s)',
  12 => '-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0128, network: 0.0002s)',
  13 => '<- NET_SSH2_MSG_USERAUTH_FAILURE (since last: 0.9446, network: 0.9445s)',
)
```

**Comment by terrafrost** [comment]
I should have had you do `define('NET_SSH2_LOGGING', 2)`, sorry.

Anyway, based on what you did post I'm wondering if the key simply isn't supported.

What happens if you `echo $key;` after `$key = PublicKeyLoader::load('abcd.pem');`?

Like maybe the key is password protected and you're just not supplying it with a password?

Could you give me the first line of the key file? Should be something like `------ BEGIN PRIVATE KEY ------` or some such.

**Comment by ulshamim** [comment]
Hi 

Hers is the log

<-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  37:2e:34:0d:0a                                   7.4..

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:33:2e:30:20:28:6c:69:62:73:6f:64:69:75:6d  b_3.0 (libsodium
00000020  2c:20:6f:70:65:6e:73:73:6c:2c:20:67:6d:70:29:0d  , openssl, gmp).
00000030  0a                                               .

-> NET_SSH2_MSG_KEXINIT (since last: 0.6113, network: 0.0001s)
00000000  76:e8:d7:66:db:30:da:42:b0:2c:1d:c4:95:91:58:c0  v..f.0.B.,....X.
00000010  00:00:01:7c:63:75:72:76:65:32:35:35:31:39:2d:73  ...|curve25519-s
00000020  68:61:32:35:36:2c:63:75:72:76:65:32:35:35:31:39  ha256,curve25519
00000030  2d:73:68:61:32:35:36:40:6c:69:62:73:73:68:2e:6f  -sha256@libssh.o
00000040  72:67:2c:65:63:64:68:2d:73:68:61:32:2d:6e:69:73  rg,ecdh-sha2-nis
00000050  74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32:2d  tp256,ecdh-sha2-
00000060  6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73:68  nistp384,ecdh-sh
00000070  61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66:66  a2-nistp521,diff
00000080  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000090  2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35:36  -exchange-sha256
000000a0  2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d  ,diffie-hellman-
000000b0  67:72:6f:75:70:2d:65:78:63:68:61:6e:67:65:2d:73  group-exchange-s
000000c0  68:61:31:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ha1,diffie-hellm
000000d0  61:6e:2d:67:72:6f:75:70:31:34:2d:73:68:61:32:35  an-group14-sha25
000000e0  36:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e  6,diffie-hellman
000000f0  2d:67:72:6f:75:70:31:34:2d:73:68:61:31:2c:64:69  -group14-sha1,di
00000100  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000110  75:70:31:35:2d:73:68:61:35:31:32:2c:64:69:66:66  up15-sha512,diff
00000120  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000130  31:36:2d:73:68:61:35:31:32:2c:64:69:66:66:69:65  16-sha512,diffie
00000140  2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:37  -hellman-group17
00000150  2d:73:68:61:35:31:32:2c:64:69:66:66:69:65:2d:68  -sha512,diffie-h
00000160  65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:38:2d:73  ellman-group18-s
00000170  68:61:35:31:32:2c:64:69:66:66:69:65:2d:68:65:6c  ha512,diffie-hel
00000180  6c:6d:61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31  lman-group1-sha1
00000190  00:00:00:71:73:73:68:2d:65:64:32:35:35:31:39:2c  ...qssh-ed25519,
000001a0  65:63:64:73:61:2d:73:68:61:32:2d:6e:69:73:74:70  ecdsa-sha2-nistp
000001b0  32:35:36:2c:65:63:64:73:61:2d:73:68:61:32:2d:6e  256,ecdsa-sha2-n
000001c0  69:73:74:70:33:38:34:2c:65:63:64:73:61:2d:73:68  istp384,ecdsa-sh
000001d0  61:32:2d:6e:69:73:74:70:35:32:31:2c:72:73:61:2d  a2-nistp521,rsa-
000001e0  73:68:61:32:2d:32:35:36:2c:72:73:61:2d:73:68:61  sha2-256,rsa-sha
000001f0  32:2d:35:31:32:2c:73:73:68:2d:72:73:61:2c:73:73  2-512,ssh-rsa,ss
00000200  68:2d:64:73:73:00:00:01:01:61:65:73:32:35:36:2d  h-dss....aes256-
00000210  67:63:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  gcm@openssh.com,
00000220  61:65:73:31:32:38:2d:67:63:6d:40:6f:70:65:6e:73  aes128-gcm@opens
00000230  73:68:2e:63:6f:6d:2c:61:65:73:31:32:38:2d:63:74  sh.com,aes128-ct
00000240  72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73  r,aes192-ctr,aes
00000250  32:35:36:2d:63:74:72:2c:61:65:73:31:32:38:2d:63  256-ctr,aes128-c
00000260  62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c:61:65  bc,aes192-cbc,ae
00000270  73:32:35:36:2d:63:62:63:2c:62:6c:6f:77:66:69:73  s256-cbc,blowfis
00000280  68:2d:63:74:72:2c:62:6c:6f:77:66:69:73:68:2d:63  h-ctr,blowfish-c
00000290  62:63:2c:33:64:65:73:2d:63:74:72:2c:33:64:65:73  bc,3des-ctr,3des
000002a0  2d:63:62:63:2c:74:77:6f:66:69:73:68:31:32:38:2d  -cbc,twofish128-
000002b0  63:74:72:2c:74:77:6f:66:69:73:68:31:39:32:2d:63  ctr,twofish192-c
000002c0  74:72:2c:74:77:6f:66:69:73:68:32:35:36:2d:63:74  tr,twofish256-ct
000002d0  72:2c:74:77:6f:66:69:73:68:31:32:38:2d:63:62:63  r,twofish128-cbc
000002e0  2c:74:77:6f:66:69:73:68:31:39:32:2d:63:62:63:2c  ,twofish192-cbc,
000002f0  74:77:6f:66:69:73:68:32:35:36:2d:63:62:63:2c:74  twofish256-cbc,t
00000300  77:6f:66:69:73:68:2d:63:62:63:00:00:01:01:61:65  wofish-cbc....ae
00000310  73:32:35:36:2d:67:63:6d:40:6f:70:65:6e:73:73:68  s256-gcm@openssh
00000320  2e:63:6f:6d:2c:61:65:73:31:32:38:2d:67:63:6d:40  .com,aes128-gcm@
00000330  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73:31  openssh.com,aes1
00000340  32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74  28-ctr,aes192-ct
00000350  72:2c:61:65:73:32:35:36:2d:63:74:72:2c:61:65:73  r,aes256-ctr,aes
00000360  31:32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63  128-cbc,aes192-c
00000370  62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c:62:6c  bc,aes256-cbc,bl
00000380  6f:77:66:69:73:68:2d:63:74:72:2c:62:6c:6f:77:66  owfish-ctr,blowf
00000390  69:73:68:2d:63:62:63:2c:33:64:65:73:2d:63:74:72  ish-cbc,3des-ctr
000003a0  2c:33:64:65:73:2d:63:62:63:2c:74:77:6f:66:69:73  ,3des-cbc,twofis
000003b0  68:31:32:38:2d:63:74:72:2c:74:77:6f:66:69:73:68  h128-ctr,twofish
000003c0  31:39:32:2d:63:74:72:2c:74:77:6f:66:69:73:68:32  192-ctr,twofish2
000003d0  35:36:2d:63:74:72:2c:74:77:6f:66:69:73:68:31:32  56-ctr,twofish12
000003e0  38:2d:63:62:63:2c:74:77:6f:66:69:73:68:31:39:32  8-cbc,twofish192
000003f0  2d:63:62:63:2c:74:77:6f:66:69:73:68:32:35:36:2d  -cbc,twofish256-
00000400  63:62:63:2c:74:77:6f:66:69:73:68:2d:63:62:63:00  cbc,twofish-cbc.
00000410  00:00:f7:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  ...hmac-sha2-256
00000420  2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  -etm@openssh.com
00000430  2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2d:65  ,hmac-sha2-512-e
00000440  74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:75  tm@openssh.com,u
00000450  6d:61:63:2d:36:34:2d:65:74:6d:40:6f:70:65:6e:73  mac-64-etm@opens
00000460  73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:2d  sh.com,umac-128-
00000470  65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  etm@openssh.com,
00000480  68:6d:61:63:2d:73:68:61:31:2d:65:74:6d:40:6f:70  hmac-sha1-etm@op
00000490  65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73  enssh.com,hmac-s
000004a0  68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61  ha2-256,hmac-sha
000004b0  32:2d:35:31:32:2c:75:6d:61:63:2d:36:34:40:6f:70  2-512,umac-64@op
000004c0  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31  enssh.com,umac-1
000004d0  32:38:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68  28@openssh.com,h
000004e0  6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63  mac-sha1-96,hmac
000004f0  2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39  -sha1,hmac-md5-9
00000500  36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:f7:68:6d  6,hmac-md5....hm
00000510  61:63:2d:73:68:61:32:2d:32:35:36:2d:65:74:6d:40  ac-sha2-256-etm@
00000520  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63  openssh.com,hmac
00000530  2d:73:68:61:32:2d:35:31:32:2d:65:74:6d:40:6f:70  -sha2-512-etm@op
00000540  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:36  enssh.com,umac-6
00000550  34:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f  4-etm@openssh.co
00000560  6d:2c:75:6d:61:63:2d:31:32:38:2d:65:74:6d:40:6f  m,umac-128-etm@o
00000570  70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d  penssh.com,hmac-
00000580  73:68:61:31:2d:65:74:6d:40:6f:70:65:6e:73:73:68  sha1-etm@openssh
00000590  2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32  .com,hmac-sha2-2
000005a0  35:36:2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32  56,hmac-sha2-512
000005b0  2c:75:6d:61:63:2d:36:34:40:6f:70:65:6e:73:73:68  ,umac-64@openssh
000005c0  2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:40:6f:70  .com,umac-128@op
000005d0  65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73  enssh.com,hmac-s
000005e0  68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68:61:31  ha1-96,hmac-sha1
000005f0  2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68:6d:61  ,hmac-md5-96,hma
00000600  63:2d:6d:64:35:00:00:00:04:6e:6f:6e:65:00:00:00  c-md5....none...
00000610  04:6e:6f:6e:65:00:00:00:00:00:00:00:00:00:00:00  .none...........
00000620  00:00                                            ..

<- NET_SSH2_MSG_KEXINIT (since last: 0.6018, network: 0.6016s)
00000000  71:1c:6c:2c:f1:b7:bb:cd:df:de:71:fb:c5:17:65:4f  q.l,......q...eO
00000010  00:00:01:40:63:75:72:76:65:32:35:35:31:39:2d:73  ...@curve25519-s
00000020  68:61:32:35:36:2c:63:75:72:76:65:32:35:35:31:39  ha256,curve25519
00000030  2d:73:68:61:32:35:36:40:6c:69:62:73:73:68:2e:6f  -sha256@libssh.o
00000040  72:67:2c:65:63:64:68:2d:73:68:61:32:2d:6e:69:73  rg,ecdh-sha2-nis
00000050  74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32:2d  tp256,ecdh-sha2-
00000060  6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73:68  nistp384,ecdh-sh
00000070  61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66:66  a2-nistp521,diff
00000080  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000090  2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35:36  -exchange-sha256
000000a0  2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d  ,diffie-hellman-
000000b0  67:72:6f:75:70:31:36:2d:73:68:61:35:31:32:2c:64  group16-sha512,d
000000c0  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
000000d0  6f:75:70:31:38:2d:73:68:61:35:31:32:2c:64:69:66  oup18-sha512,dif
000000e0  66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75  fie-hellman-grou
000000f0  70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c  p-exchange-sha1,
00000100  64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67  diffie-hellman-g
00000110  72:6f:75:70:31:34:2d:73:68:61:32:35:36:2c:64:69  roup14-sha256,di
00000120  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000130  75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69:65  up14-sha1,diffie
00000140  2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:2d  -hellman-group1-
00000150  73:68:61:31:00:00:00:41:73:73:68:2d:72:73:61:2c  sha1...Assh-rsa,
00000160  72:73:61:2d:73:68:61:32:2d:35:31:32:2c:72:73:61  rsa-sha2-512,rsa
00000170  2d:73:68:61:32:2d:32:35:36:2c:65:63:64:73:61:2d  -sha2-256,ecdsa-
00000180  73:68:61:32:2d:6e:69:73:74:70:32:35:36:2c:73:73  sha2-nistp256,ss
00000190  68:2d:65:64:32:35:35:31:39:00:00:00:af:63:68:61  h-ed25519....cha
000001a0  63:68:61:32:30:2d:70:6f:6c:79:31:33:30:35:40:6f  cha20-poly1305@o
000001b0  70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73:31:32  penssh.com,aes12
000001c0  38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74:72  8-ctr,aes192-ctr
000001d0  2c:61:65:73:32:35:36:2d:63:74:72:2c:61:65:73:31  ,aes256-ctr,aes1
000001e0  32:38:2d:67:63:6d:40:6f:70:65:6e:73:73:68:2e:63  28-gcm@openssh.c
000001f0  6f:6d:2c:61:65:73:32:35:36:2d:67:63:6d:40:6f:70  om,aes256-gcm@op
00000200  65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73:31:32:38  enssh.com,aes128
00000210  2d:63:62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c  -cbc,aes192-cbc,
00000220  61:65:73:32:35:36:2d:63:62:63:2c:62:6c:6f:77:66  aes256-cbc,blowf
00000230  69:73:68:2d:63:62:63:2c:63:61:73:74:31:32:38:2d  ish-cbc,cast128-
00000240  63:62:63:2c:33:64:65:73:2d:63:62:63:00:00:00:af  cbc,3des-cbc....
00000250  63:68:61:63:68:61:32:30:2d:70:6f:6c:79:31:33:30  chacha20-poly130
00000260  35:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65  5@openssh.com,ae
00000270  73:31:32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d  s128-ctr,aes192-
00000280  63:74:72:2c:61:65:73:32:35:36:2d:63:74:72:2c:61  ctr,aes256-ctr,a
00000290  65:73:31:32:38:2d:67:63:6d:40:6f:70:65:6e:73:73  es128-gcm@openss
000002a0  68:2e:63:6f:6d:2c:61:65:73:32:35:36:2d:67:63:6d  h.com,aes256-gcm
000002b0  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73  @openssh.com,aes
000002c0  31:32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63  128-cbc,aes192-c
000002d0  62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c:62:6c  bc,aes256-cbc,bl
000002e0  6f:77:66:69:73:68:2d:63:62:63:2c:63:61:73:74:31  owfish-cbc,cast1
000002f0  32:38:2d:63:62:63:2c:33:64:65:73:2d:63:62:63:00  28-cbc,3des-cbc.
00000300  00:00:d5:75:6d:61:63:2d:36:34:2d:65:74:6d:40:6f  ...umac-64-etm@o
00000310  70:65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d  penssh.com,umac-
00000320  31:32:38:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e  128-etm@openssh.
00000330  63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32:35  com,hmac-sha2-25
00000340  36:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f  6-etm@openssh.co
00000350  6d:2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2d  m,hmac-sha2-512-
00000360  65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  etm@openssh.com,
00000370  68:6d:61:63:2d:73:68:61:31:2d:65:74:6d:40:6f:70  hmac-sha1-etm@op
00000380  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:36  enssh.com,umac-6
00000390  34:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:75:6d  4@openssh.com,um
000003a0  61:63:2d:31:32:38:40:6f:70:65:6e:73:73:68:2e:63  ac-128@openssh.c
000003b0  6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  om,hmac-sha2-256
000003c0  2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2c:68  ,hmac-sha2-512,h
000003d0  6d:61:63:2d:73:68:61:31:00:00:00:d5:75:6d:61:63  mac-sha1....umac
000003e0  2d:36:34:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e  -64-etm@openssh.
000003f0  63:6f:6d:2c:75:6d:61:63:2d:31:32:38:2d:65:74:6d  com,umac-128-etm
00000400  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61  @openssh.com,hma
00000410  63:2d:73:68:61:32:2d:32:35:36:2d:65:74:6d:40:6f  c-sha2-256-etm@o
00000420  70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d  penssh.com,hmac-
00000430  73:68:61:32:2d:35:31:32:2d:65:74:6d:40:6f:70:65  sha2-512-etm@ope
00000440  6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68  nssh.com,hmac-sh
00000450  61:31:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63  a1-etm@openssh.c
00000460  6f:6d:2c:75:6d:61:63:2d:36:34:40:6f:70:65:6e:73  om,umac-64@opens
00000470  73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:40  sh.com,umac-128@
00000480  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63  openssh.com,hmac
00000490  2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73  -sha2-256,hmac-s
000004a0  68:61:32:2d:35:31:32:2c:68:6d:61:63:2d:73:68:61  ha2-512,hmac-sha
000004b0  31:00:00:00:15:6e:6f:6e:65:2c:7a:6c:69:62:40:6f  1....none,zlib@o
000004c0  70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:15:6e:6f  penssh.com....no
000004d0  6e:65:2c:7a:6c:69:62:40:6f:70:65:6e:73:73:68:2e  ne,zlib@openssh.
000004e0  63:6f:6d:00:00:00:00:00:00:00:00:00:00:00:00:00  com.............

-> NET_SSH2_MSG_KEX_ECDH_INIT (since last: 0.0027, network: 0.0001s)
00000000  00:00:00:20:62:e1:be:5a:f0:99:e8:7b:65:55:64:23  ... b..Z...{eUd#
00000010  e9:85:83:0d:85:dc:97:50:42:e7:91:48:90:68:46:29  .......PB..H.hF)
00000020  17:22:91:5f                                      ."._

<- NET_SSH2_MSG_KEX_ECDH_REPLY (since last: 0.3227, network: 0.3226s)
00000000  00:00:00:33:00:00:00:0b:73:73:68:2d:65:64:32:35  ...3....ssh-ed25
00000010  35:31:39:00:00:00:20:b7:b2:f2:e1:36:02:f9:b9:be  519... ....6....
00000020  cc:a8:8d:3a:68:cb:b0:f0:81:0b:ba:ca:39:86:0e:4b  ...:h.......9..K
00000030  db:8a:0a:de:f2:ee:08:00:00:00:20:9d:ef:8d:50:ba  .......... ...P.
00000040  fa:e8:1d:5d:3f:f3:c6:b3:00:b1:7e:38:85:8d:f9:7a  ...]?.....~8...z
00000050  58:5a:94:8d:a3:1b:7b:14:e1:f2:4c:00:00:00:53:00  XZ....{...L...S.
00000060  00:00:0b:73:73:68:2d:65:64:32:35:35:31:39:00:00  ...ssh-ed25519..
00000070  00:40:30:b2:00:d7:4a:83:06:86:c4:e3:b6:a6:02:23  .@0...J........#
00000080  e1:60:5c:6e:8a:9c:3b:e5:a5:26:bc:c4:f9:ba:44:7f  .`\n..;..&....D.
00000090  ce:c4:fe:50:34:91:af:2e:6e:0a:a4:82:a9:56:14:e7  ...P4...n....V..
000000a0  5e:77:9a:f6:72:44:ed:eb:37:3f:88:f7:b9:08:57:8b  ^w..rD..7?....W.
000000b0  7d:01                                            }.

-> NET_SSH2_MSG_NEWKEYS (since last: 0.0009, network: 0.0001s)
                                                 

<- NET_SSH2_MSG_NEWKEYS (since last: 0.0001, network: 0s)
                                                 

-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0007, network: 0s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 1.1055, network: 1.1054s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0003, network: 0.0001s)
00000000  00:00:00:08:65:63:32:2d:75:73:65:72:00:00:00:0e  ....ec2-user....
00000010  73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f:6e:00:00  ssh-connection..
00000020  00:04:6e:6f:6e:65                                ..none

<- NET_SSH2_MSG_USERAUTH_FAILURE (since last: 0.4087, network: 0.4086s)
00000000  00:00:00:26:70:75:62:6c:69:63:6b:65:79:2c:67:73  ...&publickey,gs
00000010  73:61:70:69:2d:6b:65:79:65:78:2c:67:73:73:61:70  sapi-keyex,gssap
00000020  69:2d:77:69:74:68:2d:6d:69:63:00                 i-with-mic.

-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0051, network: 0.0001s)
00000000  00:00:00:08:65:63:32:2d:75:73:65:72:00:00:00:0e  ....ec2-user....
00000010  73:73:68:2d:63:6f:6e:6e:65:63:74:69:6f:6e:00:00  ssh-connection..
00000020  00:09:70:75:62:6c:69:63:6b:65:79:00:00:00:00:0c  ..publickey.....
00000030  72:73:61:2d:73:68:61:32:2d:32:35:36:00:00:01:17  rsa-sha2-256....
00000040  00:00:00:07:73:73:68:2d:72:73:61:00:00:00:03:01  ....ssh-rsa.....
00000050  00:01:00:00:01:01:00:80:c5:3f:c0:9b:99:e0:13:cf  .........?......
00000060  8e:a0:44:9d:cd:2b:87:98:71:01:b3:64:3b:79:56:b2  ..D..+..q..d;yV.
00000070  8b:bb:ac:19:6a:11:42:bd:e0:28:14:cc:8f:b4:f9:54  ....j.B..(.....T
00000080  25:34:b8:fb:e3:97:70:58:35:18:75:3e:22:93:46:49  %4....pX5.u>".FI
00000090  15:46:ea:4d:c6:8f:d7:ac:ac:ce:34:71:50:be:85:95  .F.M......4qP...
000000a0  c3:fa:cd:37:b8:2d:e2:38:51:cc:d5:f3:a6:c7:2c:f6  ...7.-.8Q.....,.
000000b0  44:77:55:22:8c:ae:25:4d:b4:af:ea:01:1e:69:8a:d2  DwU"..%M.....i..
000000c0  1e:6e:a9:ef:94:39:ee:78:88:b4:3b:86:bd:f9:b9:88  .n...9.x..;.....
000000d0  b2:7c:20:90:5d:94:08:17:4c:c7:8a:1a:c5:ca:86:c4  .| .]...L.......
000000e0  f8:55:5d:69:e0:0e:22:19:f5:41:7f:fe:d6:f3:26:54  .U]i.."..A....&T
000000f0  39:e8:25:c9:e7:ed:08:6a:21:81:3d:14:47:5a:e5:64  9.%....j!.=.GZ.d
00000100  b8:21:79:74:cb:32:c1:0a:dc:72:84:8a:e2:e3:67:d7  .!yt.2...r....g.
00000110  c9:82:d1:b7:96:20:9d:f0:f5:e1:68:dc:86:11:4e:d6  ..... ....h...N.
00000120  11:c1:53:d1:61:7b:e3:36:71:46:41:5f:27:78:fc:a2  ..S.a{.6qFA_'x..
00000130  88:b4:72:ca:01:73:63:96:7b:c7:eb:6c:08:5f:fd:da  ..r..sc.{..l._..
00000140  5d:5f:99:66:af:b8:06:3e:70:6c:0f:01:ab:d8:b5:b2  ]_.f...>pl......
00000150  f2:90:b1:86:89:07:01                             .......

<- NET_SSH2_MSG_USERAUTH_FAILURE (since last: 0.4045, network: 0.4044s)
00000000  00:00:00:26:70:75:62:6c:69:63:6b:65:79:2c:67:73  ...&publickey,gs
00000010  73:61:70:69:2d:6b:65:79:65:78:2c:67:73:73:61:70  sapi-keyex,gssap
00000020  69:2d:77:69:74:68:2d:6d:69:63:00                 i-with-mic.


_What happens if you echo $key; after $key = PublicKeyLoader::load('abcd.pem');?_

A: This returns the content of the pem file. 

_Could you give me the first line of the key file? Should be something like ------ BEGIN PRIVATE KEY ------ or some such._

A: -----BEGIN PRIVATE KEY----- MIIEvAIBADANBgkqhkiG9w0BAQEFAASCBK...................so on.

**Comment by terrafrost** [comment]
So the way publickey auth in SSH2 works is that it sends two requests. In the first request the client sends to the server the public key of the signature format (rsa-sha2-256). If the server responds with SSH_MSG_USERAUTH_PK_OK then the client sends a second request that contains a signature of the session identifier (as created by the private key).

In this case it's failing on the first of those two requests. So one of two possibilities exist:

1. The server doesn't have a public key corresponding to the one that it was sent for the user in question
2. The server doesn't support rsa-sha2-256 even tho it says it does

My money is on #1.

> I have already tried to log in using ssh command from the terminal which is working but using PHP code it is not working.

Are you _sure_ you're using the same key for both? If you're extra sure you are then it'd be interesting to see know what PuTTY does. PuTTY records the full SSH logs whereas OpenSSH doesn't, hence my wanting to know what PuTTY doe. You can enable logging in PuTTY by going to putty.exe, selecting the Logging category and checking "SSH packets". Then go back to the Session category, type in a session name (say phpseclib) under "Saved Sessions" and hit the Save button.

I suppose you could try to see #2 too by doing `$ssh->setPreferredAlgorithms(['hostkey' => ['ssh-rsa']]);`.
