### ISSUE TITLE
bug: SFTP session stays open in V3

### ISSUE THREAD

**Issue by DRoet** [phpseclib/phpseclib#1672]
I've noticed that v3 no longer closes the session inside my long-running process. the __destruct method (inside the SSH2 class) is no longer being triggered somehow, so the object never gets cleaned up. I noticed that my memory consumption also slowly increases every cycle.

minimal reproduction: (for both v2/v3):

```php
<?php

use phpseclib3\Net\SFTP;  //use phpseclib\Net\SFTP; for v2

require_once('../vendor/autoload.php');

while (true) {
   $sftp = new SFTP('hostname');
   $login = $sftp->login('username', 'password');
   echo $login;
   sleep(1);
   // in v2 the SSH2 __destruct method closes the session here when the cycle is done
}

```

**Comment by DRoet** [comment]
Manually calling ```unset($sftp)``` also doesn't work to clean up the object/connections.

**Comment by terrafrost** [comment]
It's because of this (in SSH2.php):

```php
self::$connections[$this->getResourceId()] = $this;
```
Here's the commit that added that:

https://github.com/phpseclib/phpseclib/commit/70dd67c4d9ada5d00e15ed8e717af46f8d9692f7

https://3v4l.org/HNABA demonstrates the issue. Note how the calling of the destructor is not interleaved with the calling of the constructor. It is with https://3v4l.org/McaXV but not with https://3v4l.org/HNABA . [WeakReferences](https://www.php.net/manual/en/class.weakreference.php) would fix this: https://3v4l.org/mO1FG but they weren't added until PHP 7.4 and phpseclib 3.0 works on PHP 5.6+.

I'll need to think on this some.

**Comment by terrafrost** [comment]
What version of PHP are you using? Maybe I could do this:

```php
self::$instances[$this->instanceID] = class_exists('WeakReference') ? WeakReference::create($this) : $this;
```
phpseclib 4.0 will require a newer version of PHP than 5.6. Not sure what version yet. Maybe 7.4 will be the minimum version! But  have no ETA on 4.0. It's years away lol

**Comment by DRoet** [comment]
I'm currently on version 7.4.20, thanks for looking into this!

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/418035c404833187f7474c71e0ba06c167b0bcf0 should fix this for people running PHP 7.4+.

Thanks!

**Comment by DRoet** [comment]
Thanks, looking forward to the next release 👍

**Comment by DRoet** [comment]
@terrafrost The connection issue seems to be resolved, however unless I am mistaken the memory still seems to creep up slowly every cycle using the latest `v3.0.x-dev` version when used inside a long-running process. Could there be something else that is staying in memory? I am not an expert in PHP memory debugging so I am not really sure how to pinpoint this issue.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/05539a72befc2e50f8b0437b69dee64b46b97aa8 should help out with this too.

That said, you might see what looks like a memory leak unless you do `gc_collect_cycles()` as well. See https://stackoverflow.com/q/68330517/569976 for a nice demonstration.

phpseclib 3.0 uses anonymous functions like that whereas phpseclib 1.0 / 2.0 do not.

**Comment by DRoet** [comment]
Good news! Your latest patch seems to resolve the issues I was having, haven't seen any significant memory increases in the last few hours. Thank you so much for looking into this!
