### ISSUE TITLE
Use of undefined constant NET_SSH2_CHANNEL_KEEP_ALIVE

### ISSUE THREAD

**Issue by walid-vbout** [phpseclib/phpseclib#1674]
https://github.com/phpseclib/phpseclib/blob/d789306e5ca3233b6ee8f31a0d3c3d73f63e3c5b/phpseclib/Net/SSH2.php#L3095

Is this correct or should be `self::CHANNEL_KEEP_ALIVE`?

**Comment by terrafrost** [comment]
Good catch! It's been fixed!:

https://github.com/phpseclib/phpseclib/commit/9b1f8a260accd9f6305abdd2ca61688840b5e8be
