### ISSUE TITLE
V3 public key algo different when signing a cert from loadcsr

### ISSUE THREAD

**Issue by gvandenbosch** [phpseclib/phpseclib#1675]
Hello,

When I am trying to sign a certificate which comes from `loadCSR` function  it always comes with the following public key algorithm:

```
Public Key Algorithm: rsassaPss
                RSA-PSS Public-Key: (4096 bit)
```

When instead of loading the CSR I create my own `X509` object, the public key algorithm is correct:

```
Public Key Algorithm: rsaEncryption
                RSA Public-Key: (4096 bit)
```

The public key algorithm from the loadCSR function should also be `rsaEncryption`.

I have created a test script which I have attached that demonstrates the difference.

[Pkitest.php.zip](https://github.com/phpseclib/phpseclib/files/6698664/Pkitest.php.zip)

In the test script the private key is generated the same way:

```
/* generate key */
$privateKey = RSA::createKey(4096);
$privateKey = $privateKey->withPadding(RSA::SIGNATURE_PKCS1);
$privateKey = $privateKey->withHash('sha256');
```

However the Public Key Algorithm still comes out as `rsassaPss` for the function that uses `loadCSR`

The only difference I see is that I use `setPublicKey` in the function without CSR, however in my real world application for the function with CSR I am unable to use that as the CSR will be uploaded from third party without private keys.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/f0736a8828f720824e3d6828f80631cea5bba4aa should fix this.

Thanks!

**Comment by gvandenbosch** [comment]
Confirmed fix
