### ISSUE TITLE
Serializable interface deprecated in PHP 8.1

### ISSUE THREAD

**Issue by W1DJM** [phpseclib/phpseclib#1680]
Using PHP 8.1.0alpha 3 the following errors get thrown when using BigInteger:

> [15-Jul-2021 12:45:34 America/New_York] PHP Deprecated:  The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in D:\var\Classes\vendor\phpseclib\phpseclib\phpseclib\Math\BigInteger.php on line 42
> [15-Jul-2021 12:45:34 America/New_York] PHP Deprecated:  The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in D:\var\Classes\vendor\phpseclib\phpseclib\phpseclib\Math\BigInteger\Engines\GMP.php on line 28
> [15-Jul-2021 12:45:34 America/New_York] PHP Deprecated:  The Serializable interface is deprecated. Implement __serialize() and __unserialize() instead (or in addition, if support for old PHP versions is necessary) in D:\var\Classes\vendor\phpseclib\phpseclib\phpseclib\Math\BigInteger\Engines\PHP64.php on line 29

The code that is generating the errors is:

```
$key = [
	'e' => new BigInteger(base64_decode($exponent), 256),
	'n' => new BigInteger(base64_decode($modulus), 256)
];
```

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/5e290492d15e64b4ba570b632d33d908f6bff6c5 should fix this.

Thanks!
