### ISSUE TITLE
SFTP get method downloads file but also deletes the file on SFTP server

### ISSUE THREAD

**Issue by awais300** [phpseclib/phpseclib#1681]
I am trying to download/copy a file to local using the get method described here: https://phpseclib.com/docs/sftp

```
// copies filename.remote to filename.local from the SFTP server
$sftp->get('filename.remote', 'filename.local');
```

It does download the file but also deletes the same file on the SFTP server. How can I keep the file on SFTP server?

**Comment by terrafrost** [comment]
Could you create a small file on the server and then try to download it with phpseclib?

If you could then post the full SFTP logs that'd be helpful. You can get them by doing `define('NET_SFTP_LOGGING', 2)` at the top and then `echo $sftp->getSFTPLogs()` after the `$sftp->get()`.

Also, get me the server identification string. eg. `echo $sftp->getServerIdentification();`.

My best guess is that you're connecting to a custom SFTP server that is designed to delete files upon download. In that scenario (1) the problem should be reproducible with any SFTP client and (2) there's nothing phpseclib can do to stop that.

**Comment by awais300** [comment]
@terrafrost You were right, The SFTP server is designed to delete files upon download.
