### ISSUE TITLE
Getting "1" output from SSH

### ISSUE THREAD

**Issue by ESPHayden** [phpseclib/phpseclib#1682]
I have this code block here:

```php
foreach ($execCommands as $cmd) {
    if ($failed == true) break;
    $ssh->setTimeout(0);
    $ssh->enablePTY();

    (new DeploymentLog([
        'deployment_id' => $this->deployment->id,
        'content' => "[@] $path $ docker-compose exec server " . $cmd,
        'timestamp' => Carbon::now()
    ]))->save();

    $out = $ssh->exec("cd '$path' && $dockerComposePath exec server $cmd");

    (new DeploymentLog([
        'deployment_id' => $this->deployment->id,
        'content' => $out,
        'timestamp' => Carbon::now()
    ]))->save();

    $ssh->disablePTY();
    $ssh->setTimeout(10);

    if ($ssh->getExitStatus() != 0) {
        $exitCode = $ssh->getExitStatus();
        $failed = true;
        break;
    }
}
```

And it seems to work fine until this code executes (authentication and such is handled above that block).

For some reason, I'm only seeing `1` out of the command when I run this code (see the `content` attribute of that `DeploymentLog` model creation), or in some cases `0`. I can't figure out if it's just something I'm doing wrong or what. I've verified that the commands I'm running with `exec` are correct by dumping the same string to check they're valid.

But it's worth noting that this happens ~40% of the time, as most of the time when this happens it goes off without a hitch.

If someone could give me a hand with this, it would be very much appreciated :)

**Comment by terrafrost** [comment]
`$ssh->exec()` return true or false when you're using a PTY. If you want the actual output of `$ssh->exec()` (whilst using a PTY) you'd need to use `$ssh->read()`.

This is because the PTY lets you send data to the server, as well, which could affect the output. See https://phpseclib.com/docs/commands#exec-with-and-without-a-pty-vs-interactive-shells for a few examples.

**Comment by ESPHayden** [comment]
@terrafrost Ah, thanks for this -- I'll give this a try soon (later today or tomorrow, depending on when I have time). :)

**Comment by ESPHayden** [comment]
That worked, thanks! :)
