### ISSUE TITLE
Unable to connect with the public key you've provided.

### ISSUE THREAD

**Issue by Asadeli** [phpseclib/phpseclib#1687]
![image](https://user-images.githubusercontent.com/46839255/128596890-658aa96b-21c8-4b80-9d28-07aa652a2c33.png)

**Comment by terrafrost** [comment]
Sorry for not responding sooner - I've been super busy this past week.

Anyway, are you still having this problem?

idk what that screenshot is from.

What version of phpseclib are you using? Are you sure you're using phpseclib?

Sample code would be much more helpful than a screenshot.
