### ISSUE TITLE
BouncyCastle implementation

### ISSUE THREAD

**Issue by akalongman** [phpseclib/phpseclib#1688]
Is it possible to create EC key with [BouncyCastle](http://www.bouncycastle.org/) implementation and encrypt/decrypt data? Something similar to this Java code:

```java
KeyPairGenerator generator = KeyPairGenerator.getInstance("EC", new BouncyCastleProvider());
generator.initialize(ECNamedCurveTable.getParameterSpec("brainpoolP256r1"));
KeyPair keyPair = generator.generateKeyPair();
```

Now I create EC like this:

```php
$key = EC::createKey('brainpoolP256r1');
$publicKey = $key->getPublicKey();
```

**Comment by terrafrost** [comment]
Yah should work just fine. phpseclib supports brainpoolP256r1.

If you encounter any issues lmk

**Comment by akalongman** [comment]
@terrafrost I have a problem with the calculation of the secret for my private and received public key. I am getting error: "The string representation of the points is not of an appropriate length".
On the Java this works perfectly.
Imho something is wrong with the calculation of EC Point for `brainpoolP256r1` here https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/EC/PrivateKey.php#L59

**Comment by terrafrost** [comment]
So what, exactly, is the issue?

Are you:

1. Creating the key in BouncyCastle and unable to load it in phpseclib?
2. Creating the key in phpseclib and unable to load it in phpseclib?
3. Creating the key in phpseclib and unable to upload it in BouncyCastle?

I was able to create a key in BouncyCastle and load it in phpseclib without issue:

```java
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import org.bouncycastle.jce.ECNamedCurveTable;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import java.security.PrivateKey;
import java.io.FileOutputStream;

public class ECTest
{
    public static void main(String[] args) throws Exception
    {
        KeyPairGenerator generator = KeyPairGenerator.getInstance("EC", new BouncyCastleProvider());
        generator.initialize(ECNamedCurveTable.getParameterSpec("brainpoolP256r1"));
        KeyPair keyPair = generator.generateKeyPair();
        PrivateKey privateKey = keyPair.getPrivate();
        FileOutputStream out = new FileOutputStream("private.key");
        out.write(privateKey.getEncoded());
        out.close();
    }
}
```
If you're having issues with that then might I suggest that the issue might be with how you're saving it.

I also tried to create a key in phpseclib and load it with phpseclib without issue:

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use phpseclib3\Crypt\PublicKeyLoader;
use phpseclib3\Crypt\EC;

$private = EC::createKey('brainpoolP256r1');

$key = PublicKeyLoader::load("$private");

echo $key->getLoadedFormat() . "\n";
echo $key->getCurve();
```
I have not tried to create a key in phpseclib and load it in BouncyCastle. I can try but idk that I want to expend much more effort without having a better understanding of the problem you're having.

**Comment by akalongman** [comment]
The issue is computing shared secret when communicating with API written on Java. 

Scenario:

I am generating private key via openssh: 
```bash
openssl ecparam -name brainpoolP256r1 -genkey -noout -out private.ec.pem
```

And send to API public key via code:

```php
/** @var \phpseclib3\Crypt\EC\PrivateKey $private */
$private = PublicKeyLoader::load(file_get_contents('private.ec.pem'));

/** @var \phpseclib3\Crypt\EC\PublicKey $public */
$public = $private->getPublicKey();
XML::setNamespace(null);
$xml = $public->toString('XML');

// send XML with the public key to the API for key exchange
```

After I am receiving their public key and encrypted data from the API and I have to calculate secret to decrypt the data.

```php
$receivedPublic = 'base64 encoded string from XML'; // Tried base54_decode() as well
$result = DH::computeSecret($private, $receivedPublic);
```

And I am getting the error: "The string representation of the points is not of an appropriate length"

What I am doing wrong?

**Comment by terrafrost** [comment]
```php
/** @var \phpseclib3\Crypt\EC\PrivateKey $private */
$private = PublicKeyLoader::load(file_get_contents('private.ec.pem'));

/** @var \phpseclib3\Crypt\EC\PublicKey $public */
$public = $private->getPublicKey();
XML::setNamespace(null);
$xml = $public->toString('XML');

// send XML with the public key to the API for key exchange
```
For XML based keys there are two formats to consider:

https://www.w3.org/TR/xmldsig-core/#sec-ECKeyValue
https://www.w3.org/TR/xmldsig-core/#sec-RFC4050Compat

I forget which one it uses by default 

> After I am receiving their public key and encrypted data from the API and I have to calculate secret to decrypt the data.

Can you post the code you're using to decrypt the data?

Also, maybe looking at the API docs might help. Can you share them with me?

**Comment by akalongman** [comment]
@terrafrost sorry for the late answer. I'll share more data on what I want to achieve and also, Java code examples. Maybe it helps more
