### ISSUE TITLE
Any web interfaces for phpseclib SFTP?

### ISSUE THREAD

**Issue by sdwru** [phpseclib/phpseclib#1694]
I just need basic front end functionality.  I already have phpseclib SFTP running on my webserver backend.  I am finding that just trying to do the most basic things in SFTP requires lots of front end work on the web UI in order to present it in a typical file manager way.  Is there anything that already exists that I could perhaps modify? I just need the basics.  Browse directories, view file contents, download files.

Something like tinyfilemanager would be nice if it supported SFTP.  Still overkill for what I need so I could trim that down quite a bit.  I look through the code and it still looks like a very heavy lift to try modify that for SFTP.

https://github.com/prasathmani/tinyfilemanager

**Comment by terrafrost** [comment]
There's owncloud I guess. There may be libraries that use league/flysystem-sftp as well.
