### ISSUE TITLE
loadPrivateKey does not work with array parameters

### ISSUE THREAD

**Issue by allan-simon** [phpseclib/phpseclib#1711]
I'm using 3.0.11

when I do

```
      return PublicKeyLoader::loadPrivateKey([
              'e' => new Math_BigInteger($packet->key['e'], 256), 
              'n' => new Math_BigInteger($packet->key['n'], 256),
              'd' => new Math_BigInteger($packet->key['d'], 256),
              'p' => new Math_BigInteger($packet->key['p'], 256),
              'q' => new Math_BigInteger($packet->key['q'], 256),
              'u' => new Math_BigInteger($packet->key['u'], 256),
          ])                                
              ->withPadding(CRYPT_RSA_SIGNATURE_PKCS1)
              ->withHash('sha256');     
```

it fails, telling me 
```
The key that was loaded was not a private key in  vendor/phpseclib/phpseclib/phpseclib/Crypt/PublicKeyLoader.php:79
```

the issue seems to be that the `loadPrivateKey` does not support receiving parameters as Array

because on the other side , if do 

```
      return PublicKeyLoader::loadPublicKey([
              'e' => new Math_BigInteger($packet->key['e'], 256), 
              'n' => new Math_BigInteger($packet->key['n'], 256),
              'd' => new Math_BigInteger($packet->key['d'], 256),
              'p' => new Math_BigInteger($packet->key['p'], 256),
              'q' => new Math_BigInteger($packet->key['q'], 256),
              'u' => new Math_BigInteger($packet->key['u'], 256),
          ])
              ->asPrivateKey()                                
              ->withPadding(CRYPT_RSA_SIGNATURE_PKCS1)
              ->withHash('sha256');   
```
it works fine

**Comment by terrafrost** [comment]
That's correct - arrays are only supported for public keys. If you pass a private key array to `loadPublicKey` the private key parameters will be ignored.

I can make it so that arrays can be used for private keys as well but can I ask what the use case is? I feel like some third party API's specify the modulus and exponent as distinct fields for some APIs, hence why it's a little useful. I don't have any specific examples of this however.

**Comment by allan-simon** [comment]
@terrafrost 
I'm trying to port  openpgp-php to  phpseclib3  and I faced the issue while porting these specific lines 

https://github.com/singpolyma/openpgp-php/blob/master/lib/openpgp_crypt_rsa.php#L241-L268

it seems that before for private keys they were first loading it as public key,  and then setted additional properties , but these are now all protected/private parameters ,  so I thought the code above would be equivalent for private keys 

I want to add that outside of generic knowledge of RSA, i have no deep knowledge , so don't hesitate to tell me if what i'm doing is wrong/does not make sense.

**Comment by terrafrost** [comment]
I'll try to do this in the next few days.

Ideally, I think it'd be cool if phpseclib, itself, had built in support for OpenPGP keys. Failing that you could write your own plugin:

https://phpseclib.com/docs/publickeys#custom-key-formats

(phpseclib v1/2 don't support plugins but v3 does)

As a plugin it's something I could ultimately incorporate into phpseclib.

**Comment by allan-simon** [comment]
thanks for your quick reply

for the plugin, once I've upgraded openpgp-php it's the next thing I could do :)

**Comment by terrafrost** [comment]
This is now supported as of https://github.com/phpseclib/phpseclib/commit/84295e2fc276d0f98983d31bf58584e435fcc73a

**Comment by allan-simon** [comment]
thanks I'm going to try that right now !

**Comment by allan-simon** [comment]
awesome it works great,  is it possible to tag a version ?

**Comment by terrafrost** [comment]
> is it possible to tag a version ?

Maybe in 1-2 weeks. I want to give people a chance to test out / chime in on #1712 before I do a release. That was a fairly broad change to how elliptic curves work.

I don't actually expect to get any feedback on it but I don't want to rush out a big change like that without at least giving people a reasonable amount of time to give feedback should be they so inclined.

**Comment by allan-simon** [comment]
fair enough :)

**Comment by terrafrost** [comment]
I'm gonna try to do a release this evening!

**Comment by allan-simon** [comment]
great !

**Comment by terrafrost** [comment]
3.0.12 has been released!
