### ISSUE TITLE
DangerousPhp inside phpseclib when checking with YARA

### ISSUE THREAD

**Issue by mujuonly** [phpseclib/phpseclib#1713]
When doing malware scanner inside the app using YARA,

yara -r ./php.yar -s /myapp

it's showing the validation error from phpseclib

DangerousPhp /myapp/phpseclib/Net/SSH2.php
0x1140c:$system: system
0x1083a:$: call_user_func
0x1671f:$: call_user_func
0x154:$: EXEC

The scanner tool used is https://github.com/nbs-system/php-malware-finder/

**Comment by terrafrost** [comment]
Looks like you got a fairly detailed answer at https://stackoverflow.com/a/70028637/569976
