### ISSUE TITLE
[question]  in RSA.php both  privateExponent and publicExponent are set to $e 

### ISSUE THREAD

**Issue by allan-simon** [phpseclib/phpseclib#1714]
see https://github.com/phpseclib/phpseclib/blob/7e38313802b62606cf27ddf573a7c47e88b5d33f/phpseclib/Crypt/RSA.php#L431-L433

```php
        $privatekey->publicExponent = $e;
        $privatekey->exponent = $d;
        $privatekey->privateExponent = $e;
```

while the comment above state : 

```php
        //     publicExponent    INTEGER,  -- e
        //     privateExponent   INTEGER,  -- d
```

also in the same vein 

```php
        //     exponent1         INTEGER,  -- d mod (p-1)
        //     exponent2         INTEGER,  -- d mod (q-1)
```

but we have 

```php
        foreach ($primes as $i => $prime) {
            $temp = $prime->subtract(self::$one);
            $exponents[$i] = $e->modInverse($temp); // shouldn't it be $d  ? 
        }
```

I'm not deeply knowledgeable in RSA so i'm maybe missing something ?

**Comment by terrafrost** [comment]
Good catch!

I was trying to see if there was any way I could write a unit test to test for this but it looks like there isn't.

When private keys are saved `$this->exponent` is utilized - not `$this->privateExponent`. Since it doesn't appear to be used I've just gone ahead and full on removed it:

https://github.com/phpseclib/phpseclib/commit/a85c2f0d6e173a471192cc207dccfc092b058268

**Comment by allan-simon** [comment]
ok thanks it answers my first question , as for   dp and dq  that are used using  `e` is there any reason ?

**Comment by terrafrost** [comment]
In re-reading your question I get what you're asking. I'll respond iab. Maybe in a few days. I got some other stuff to do atm

**Comment by terrafrost** [comment]
To answer your question...  `d mod (p-1)` is the same thing as `e**-1 mod (p - 1)`. https://crypto.stackexchange.com/a/96294/4520 elaborates.

**Comment by allan-simon** [comment]
thanks a lot , it's clearer now.
