### ISSUE TITLE
phpseclib 3, can withSaltLength be set to auto ( auto-detected when verifying ) ?

### ISSUE THREAD

**Issue by Fiqih57** [phpseclib/phpseclib#1728]
I'm using phpseclib 3, I'm using RSA::SIGNATURE_PSS
The following methods can be used to configure this method:
- withHash (defaults to sha256)
- with MGFHash (defaults to sha256)
- withSaltLength (defaults to hash length in bytes)

I want to ask, can withSaltLength be set to auto ( auto-detected when verifying ) ? 

not using the default withSaltLength set ( the length of the salt is the same as the length of the hash used in the signature )

**Comment by terrafrost** [comment]
You'd have to brute force the salt length then. From [PKCS #1: RSA Cryptography Specifications Version 2.2 § EMSA-PSS § Verification Operation](https://datatracker.ietf.org/doc/html/rfc8017#section-9.1.2):

```
      11.  Let salt be the last sLen octets of DB.

      12.  Let

              M' = (0x)00 00 00 00 00 00 00 00 || mHash || salt ;

           M' is an octet string of length 8 + hLen + sLen with eight
           initial zero octets.

      13.  Let H' = Hash(M'), an octet string of length hLen.
```
To translate that to phpseclib, you could do this:

```
#
#-----[ OPEN ]------------------------------------------
#
phpseclib/Crypt/RSA/PrivateKey.php
#
#-----[ FIND ]------------------------------------------
#
        $temp = $emLen - $this->hLen - $sLen - 2;
        if (substr($db, 0, $temp) != str_repeat(chr(0), $temp) || ord($db[$temp]) != 1) {
            return false;
        }
        $salt = substr($db, $temp + 1); // should be $sLen long
        $m2 = "\0\0\0\0\0\0\0\0" . $mHash . $salt;
        $h2 = $this->hash->hash($m2);
        return hash_equals($h, $h2);
#
#-----[ REPLACE WITH ]----------------------------------
#
        for ($sLen = 0; $sLen < strlen($db); $sLen++) {
            $temp = $emLen - $this->hLen - $sLen - 2;
            if (substr($db, 0, $temp) != str_repeat(chr(0), $temp) || ord($db[$temp]) != 1) {
                continue;
            }
            $salt = $sLen ? substr($db, -$sLen) : '';
            $m2 = "\0\0\0\0\0\0\0\0" . $mHash . $salt;
            $h2 = $this->hash->hash($m2);
            if (hash_equals($h, $h2)) {
                return true;
            }
        }
        return false;
```
I'm not a huge fan of doing this kind of brute forcing however. Is there precedent for it? Are there other libraries that do this?

**Comment by terrafrost** [comment]
The file to modify is phpseclib/Crypt/RSA/PublicKey.php - not phpseclib/Crypt/RSA/PrivateKey.php. Sorry about that!

**Comment by Fiqih57** [comment]
sip, it works, thanks
