### ISSUE TITLE
Integer class has fault

### ISSUE THREAD

**Issue by WouterVeen** [phpseclib/phpseclib#1731]
I have updated the lib from 3.0.9 to 3.0.10 because of a constant error. But now I get this 
`Undefined offset: 0 in /vendor/phpseclib/phpseclib/phpseclib/Math/PrimeField/Integer.php on line 74` 

also see the given image.

![image](https://user-images.githubusercontent.com/3602494/148734714-74799d7f-5c72-46d1-becb-64f806cc232f.png)

Thanks in advanced!

Greetings Wouter

**Comment by terrafrost** [comment]
Can you post the output of  the following?:

- `phpinfo()`
- `print_r($ssh->getAlgorithmsNegotiated())`?
- `print_r(BigInteger::getEngine())`

I tried to duplicate the problem myself without success:

```php
require __DIR__ . '/vendor/autoload.php';

use phpseclib3\Crypt\Hash;
use phpseclib3\Math\BigInteger;

BigInteger::setEngine('GMP');
//BigInteger::setEngine('BCMath');
//BigInteger::setEngine('PHP64');
//BigInteger::setEngine('PHP32');

$hash = new Hash('umac-32');
$hash->setKey(str_repeat('x', 16));
$hash->setNonce('zzzz');
echo bin2hex($hash->hash('abcdefghijklmnopqrstwxyz'));
```
I tried it with each of those engines and was unable to duplicate the issue

**Comment by WouterVeen** [comment]
@terrafrost thank you for your quick reply. I will try your code to test the environment. If no success I will post the info you asked for.
