### ISSUE TITLE
unable to read key error in PublicKeyLoader - phpseclib v3.0.12

### ISSUE THREAD

**Issue by raghuveer** [phpseclib/phpseclib#1733]
- I am using phpseclib v3.0.12 using composer.
- PHP code is being run on a CPanel control panel managed CentOS server where RSA 2048 bit SSH keys with passphrase are generated and keys are saved in the following paths.
- private key (/home/cccv3/.ssh/id_rsa), public key (/home/cccv3/.ssh/id_rsa.pub)
- public key is copied to target server over putty client and while I am able to connect over ssh on putty, I get error loading the private key irrespective of private key's absolute path or relative path when I try using key based authentication (https://phpseclib.com/docs/auth#public-key),

```
PHP Fatal error:  Uncaught phpseclib3\Exception\NoKeyLoadedException: Unable to read key in /home/cccv3/public_html/vendor/phpseclib/phpseclib/phpseclib/Crypt/PublicKeyLoader.php:64
Stack trace:
#0 /home/cccv3/public_html/test-ssh-sftp2.php(23): phpseclib3\Crypt\PublicKeyLoader::load(false, 'gIoNocxIp08y')
#1 {main}
  thrown in /home/cccv3/public_html/vendor/phpseclib/phpseclib/phpseclib/Crypt/PublicKeyLoader.php on line 64
```

```php
include 'vendor/autoload.php';
//$key = \phpseclib3\Crypt\PublicKeyLoader::load('/home/cccv3/.ssh/id_rsa', 'gIoNocxIp08y');
//$key = \phpseclib3\Crypt\PublicKeyLoader::load('.ssh/id_rsa', 'gIoNocxIp08y');
$key = \phpseclib3\Crypt\PublicKeyLoader::load('../.ssh/id_rsa', 'gIoNocxIp08y');

$ssh = new \phpseclib3\Net\SSH2('167.71.83.55');
echo "getserveridentification: " . $ssh->getServerIdentification() . "<br>";
print_r($ssh->getServerAlgorithms());
print_r($ssh->getAlgorithmsNegotiated());

if (!$ssh->login('root', $key)) {
	exit('Login Failed');
}

echo $ssh->read('root@root:~$');
$ssh->write("ls -la\n");
echo $ssh->read('root@root:~$');
```

```
getserveridentification: SSH-2.0-OpenSSH_8.0

Array ( [kex] => Array ( [0] => curve25519-sha256 [1] => curve25519-sha256@libssh.org [2] => ecdh-sha2-nistp256 [3] => ecdh-sha2-nistp384 [4] => ecdh-sha2-nistp521 [5] => diffie-hellman-group-exchange-sha256 [6] => diffie-hellman-group14-sha256 [7] => diffie-hellman-group16-sha512 [8] => diffie-hellman-group18-sha512 [9] => diffie-hellman-group-exchange-sha1 [10] => diffie-hellman-group14-sha1 ) [hostkey] => Array ( [0] => rsa-sha2-512 [1] => rsa-sha2-256 [2] => ssh-rsa [3] => ecdsa-sha2-nistp256 [4] => ssh-ed25519 ) [client_to_server] => Array ( [crypt] => Array ( [0] => aes256-gcm@openssh.com [1] => chacha20-poly1305@openssh.com [2] => aes256-ctr [3] => aes256-cbc [4] => aes128-gcm@openssh.com [5] => aes128-ctr [6] => aes128-cbc ) [mac] => Array ( [0] => hmac-sha2-256-etm@openssh.com [1] => hmac-sha1-etm@openssh.com [2] => umac-128-etm@openssh.com [3] => hmac-sha2-512-etm@openssh.com [4] => hmac-sha2-256 [5] => hmac-sha1 [6] => umac-128@openssh.com [7] => hmac-sha2-512 ) [comp] => Array ( [0] => none [1] => zlib@openssh.com ) [lang] => Array ( [0] => ) ) [server_to_client] => Array ( [crypt] => Array ( [0] => aes256-gcm@openssh.com [1] => chacha20-poly1305@openssh.com [2] => aes256-ctr [3] => aes256-cbc [4] => aes128-gcm@openssh.com [5] => aes128-ctr [6] => aes128-cbc ) [mac] => Array ( [0] => hmac-sha2-256-etm@openssh.com [1] => hmac-sha1-etm@openssh.com [2] => umac-128-etm@openssh.com [3] => hmac-sha2-512-etm@openssh.com [4] => hmac-sha2-256 [5] => hmac-sha1 [6] => umac-128@openssh.com [7] => hmac-sha2-512 ) [comp] => Array ( [0] => none [1] => zlib@openssh.com ) [lang] => Array ( [0] => ) ) )

Array ( [kex] => curve25519-sha256 [hostkey] => ssh-ed25519 [client_to_server] => Array ( [crypt] => aes256-gcm@openssh.com [mac] => hmac-sha2-256-etm@openssh.com [comp] => none ) [server_to_client] => Array ( [crypt] => aes256-gcm@openssh.com [mac] => hmac-sha2-256-etm@openssh.com [comp] => none ) )
```

**Comment by terrafrost** [comment]
Encrypted OpenSSH private keys are not supported for technical reasons:

https://github.com/phpseclib/phpseclib/blob/13b5ad9593072f1b2eca9047af722025e4590849/phpseclib/Crypt/Common/Formats/Keys/OpenSSH.php#L95-L120

**Comment by raghuveer** [comment]
@terrafrost thanks for the info

While I am checking if file is not being read due to chmod issues, I see that it is fine in that front,

id_rsa: 0600
id_rsa.pub: 0644
.ssh folder: 0700

you are right, I did notice the private key is encrypted with the following header,

-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,0142FBDB17703DC6576C4A30982EBF96

Do you suggest to generate SSH keys using openssl command and in .pem format or how?

will key based authentication w.r.t. SSH work if keys are generated using a different approach?

do appreciate your help with references/code samples

Thank you

**Comment by terrafrost** [comment]
```
-----BEGIN RSA PRIVATE KEY-----
Proc-Type: 4,ENCRYPTED
DEK-Info: AES-128-CBC,0142FBDB17703DC6576C4A30982EBF96
```
That's not an OpenSSH formatted key. An encrypted OpenSSH key starts off with `-----BEGIN OPENSSH PRIVATE KEY-----`. Apologies for assuming that it was.

Private keys of the format you posted _are_ supported.

If you can generate a private key that'll duplicate the issue - or are willing to share that private key with me - could you do so so that I might be able to reproduce the key? You can email it to terrafrost@php.net if you want!

**Comment by raghuveer** [comment]
@terrafrost email sent with this github issue #1733 in the subject line

I wish to use phpseclib in SSH & SFTP based functionality that will have target servers using RHEL, CentOS, HP-UX, AIX, Solaris etc... 

thank you

**Comment by terrafrost** [comment]
Got it - I'll take a look later today!

**Comment by raghuveer** [comment]
@terrafrost  please also confirm if SSH-keygen can be used to generate SSH authentication keypairs irrespective of operating system it is generated upon (like CentOS/Ubuntu/RHEL etc...)?

**Comment by terrafrost** [comment]
> please also confirm if SSH-keygen can be used to generate SSH authentication keypairs irrespective of operating system it is generated upon (like CentOS/Ubuntu/RHEL etc...)? or do I need to be mindful in terms of if OpenSSH related bcrypt encryption is used or not by observing the key header before trying with phpseclib library?

It depends more on the version of OpenSSH being used. Looking at the changelog's it looks like it was OpenSSH 7.8 that [introduced the change](https://www.openssh.com/txt/release-7.8):

```
 * ssh-keygen(1): write OpenSSH format private keys by default
   instead of using OpenSSL's PEM format. The OpenSSH format,
   supported in OpenSSH releases since 2014 and described in the
   PROTOCOL.key file in the source distribution, offers substantially
   better protection against offline password guessing and supports
   key comments in private keys. If necessary, it is possible to write
   old PEM-style keys by adding "-m PEM" to ssh-keygen's arguments
   when generating or updating a key.
```

**Comment by raghuveer** [comment]
@terrafrost thanks for the info, so will try that PEM option too sooner, meanwhile, the understanding about why previously generated RSA authentication keypair w.r.t. SSH did not work helps to get comprehensive view on where it is going wrong for me, will wait for your observations in this respect

**Comment by raghuveer** [comment]
@terrafrost , thank you for the confirmation that the private key is working for you, when you copied and pasted the private key file content (i.e., content of id_rsa) in the method that takes private key input.

This means, my php code is not able to read the private key.

I had tried the same way and it worked for me now. I will check by trying different file permissions and will try sharing the update, meanwhile, please suggest if you have any other recommendations other than

id_rsa: 0600
id_rsa.pub: 0644
.ssh folder: 0700

in security perspective?

Thank you

**Comment by terrafrost** [comment]
It's possible that PHP is running as a different user (say www-data) than the user that owns the key. This would be a problem because OpenSSH won't use the key if the permissions are too open.

A few ideas:

- You could make the web server run with the same account you login as (probably not a good idea)
- You could make the key hard-coded in PHP (how often does it change, anyway?)
- You could password protect the key and put the new key in the same path as your code
- Maybe setting up an ssh-agent would help. See https://phpseclib.com/docs/auth#ssh-agent for more info

**Comment by raghuveer** [comment]
@terrafrost , the user that own the key and the user running the php script is same, cccv3 in this scenario, the php script is running on a CPanel control panel managed server and SSH key creation is done over web interface.

Actually I started testing phpseclib over this server after I have this same private key not readable problem on a manually managed server (tested on Ubuntu server & centos server earlier) where I am not sure what the problem is and to confirm all this I tried on the server I did, before raising this support request yesterday.

While I avoid hardcoding any security key, that includes JWT secret, probably using environment variable might be a simple alternative, that too to store passphrase and kind of...

Will ssh-agent approach help with this situation? While I am trying everything in php to minimize dependencies, I need to try Ansible for specific purpose as last alternative.

please share your thoughts and thanks a lot for your prompt response :)

**Comment by terrafrost** [comment]
It's possible it's PHP, itself, that's preventing you from opening the file. Like maybe you have some sort of [open_basedir](https://www.php.net/manual/en/ini.core.php#ini.open-basedir) restriction in place.

That said, at this point, this question seems more like a general PHP question vs a phpseclib question and altho I'm prob the best person in the world to provide phpseclib support I'm prob not the best person in the world for providing general PHP support. Maybe post on https://stackoverflow.com/ asking "why is it that when I do `echo file_get_contents('../.ssh/id_rsa');` that nothing is output? the permissions are correct" or something.

Like at this point the fact that phpseclib is involved is immaterial.

**Comment by raghuveer** [comment]
@terrafrost You got it right. This server has virtual hosting setup and open_basedir restrictions are the cause for this situation. I will check about the scope of open_basedir restrictions in the manually managed servers (centos & ubuntu), that I mentioned about in one of the comments earlier.

open_basedir restrictions are good to have and this is the first situation I have a requirement to override that, let's see how that goes.

Thanks a lot, I will do my code while working on ways to increase the scope of open_basedir or kind of.

**Comment by raghuveer** [comment]
@terrafrost 

I have an update, "it worked".

While I tried using file_get_contents in one of the manually managed server setup on ubuntu/centos, I somehow replaced that code with private key path directly, as posted in the sample code in this github issue, when keys are created and code was later uploaded on this cpanel control panel managed centos server.

replaced:
`$key = \phpseclib3\Crypt\PublicKeyLoader::load('/home/cccv3/.ssh/id_rsa', 'gIoNocxIp08y');
`

with:
`
$key = \phpseclib3\Crypt\PublicKeyLoader::load(file_get_contents('/home/cccv3/.ssh/id_rsa'), 'gIoNocxIp08y');`

while commenting the key reading line of code inwhich I had copied private key content directly.

key takeaways:

- When deploying code on manually managed servers (when server management control panel is not used), I need to check for open_basedir restrictions and deploy code inside "/home/username/public_html" kind of paths instead of other places like "/usr/share/nginx/html"

thank you

**Comment by sdwru** [comment]
So is there no chance of phpseclib ever supporting ed25519 SSH key passphrases?

**Comment by terrafrost** [comment]
So one interesting thing about encrypted OpenSSH keys is that node.js can do them super fast:

https://gist.githubusercontent.com/haythemhammami/83e60a81d6066b5652bc57876947c7a3/raw/b4da272983a63687b8931aa6a5cf83524fb677ce/crawlerByTimos_node_modules_bcrypt-pbkdf_index.js

So what I've been mulling over is to just port that instead of trying to come up with a brand new green field implementation. If even that doesn't yield an acceptably fast OpenSSH encrypted key I should at least be able to share a small code samples showing Javascript's speed vs PHP's speed. Like right now the best I can do is share one big program vs another big program and that's not as convincing a demonstration as a small 3 line code snippet would be.

I mean, just considering the history of Javascript vs PHP it isn't all that surprising that Javascript would be loads faster. Javascript has big money behind it. The PHP Foundation has an annual budget of $600k per https://opencollective.com/phpfoundation#category-BUDGET . Google's V8 engine probably has whole teams of devs working on it, of which prob 25% of the devs make [$500k+ a year](https://www.levels.fyi/company/Google/salaries/Software-Engineer/L6/).  PHP can't compete with that.

**Comment by raghuveer** [comment]
@terrafrost agree with you in terms of practical situation with development of PHP these days, especially after Zend company is taken over by another and PHP development these days is being organized to happen through a foundation. While this donot have that money power, I am sure we will be able to manage together the better possible, even though having direct corporate support and contribution will expedite the process.

Coming to the request to use ED25519 with Key phrases, while you will try to port the nodejs based script into PHP, I would request you to please also consider any PHP extension/openssh portable or whatever other that will serve the purpose. Those who want that feature will install that extra dependencies on their server where they use PHPseclib library.

Please indicate, if this is in the priority list or other

Thank you

**Comment by terrafrost** [comment]
> Note: In the organization I work in, I am yet to get Libsodium whitelisted, but still, I am making this request so that, those who want this being discussed feature, will install the extra dependencies (if required), on their server where they use PHPseclib library.

Unfortunately, I'm not aware of any dependencies that'd help.

I already use every trick under the sun to maximize speed and expand support if possible. Like encrypted PuTTY v3 keys use Argon2i. phpseclib doesn't implement Argon2i but lidsodium does and if libsodium is installed then phpseclib will all of a sudden be able to load PuTTY v3 keys.

> Please indicate, if this is in the priority list or other

So keeping in mind that I do have a day job and what not...  my plan is to finish up decompression support for  https://github.com/terrafrost/zlib_compat and then to move onto the JS port. I can't give you an ETA for when all that might be.

**Comment by raghuveer** [comment]
@terrafrost I serve in a financial institution. 

While Libsodium was rejected once, I hope to make a request after completion of current project that uses PHPSeclib for whitelisting again though. Currently focus is to integrate PHPSeclib to serve the required functionality.

We understand the practical limitations. Hope to see this functionality implemented soon as per your priorities

Thank you

**Comment by terrafrost** [comment]
Encrypted OpenSSH private keys are now supported as of this commit:

https://github.com/phpseclib/phpseclib/commit/0c8994bbadffd45cd979a1354258b14ec68a025d

> P.S. You are one of the PHP core developers?

No lol. I have a php.net email address because I created a PEAR package but PEAR is pretty much dead these days.

**Comment by Ip-address-nathanael** [comment]
@raghuveer https://lnkr.fun/1125c44
