### ISSUE TITLE
Tag 2.0.34 and newer is not compatible with PHP 5.3

### ISSUE THREAD

**Issue by Paullik74** [phpseclib/phpseclib#1734]
https://github.com/phpseclib/phpseclib/blob/2.0.34/phpseclib/Net/SSH2.php#L4132

Version 2 should be compatible with PHP 5.3.3 like readme said, but from tag 2.0.34 it is not because of this line above.

```
$this->compress_context = deflate_init(ZLIB_ENCODING_RAW, ['window' => 15]);
```

PHP 5 does not support array syntax `[]`.

**Comment by terrafrost** [comment]
Good catch! See https://github.com/phpseclib/phpseclib/commit/dac83d206ef64b46996ab1b2f268c8c972e24f9c
