### ISSUE TITLE
DES/CBC/NoPadding  with key RC2

### ISSUE THREAD

**Issue by jealvin** [phpseclib/phpseclib#1739]
if its possible to write phpseclib from kotlin code like this

import android.util.Base64
import javax.crypto.Cipher
import javax.crypto.spec.IvParameterSpec
import javax.crypto.spec.SecretKeySpec

private fun decrypt(code:String) {
        val iv = byteArrayOf(1, 3, 5, 7, 9, 11, 13, 15)
        val key = byteArrayOf(101, 103, 105, 107, 109, 111, 113, 115)
        val skeySpec = SecretKeySpec(key, "RC2")
        val ivSpec = IvParameterSpec(iv)
        val cipher: Cipher = Cipher.getInstance("DES/CBC/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, skeySpec, ivSpec)
        val cipherText: ByteArray = Base64.decode(code, Base64.DEFAULT)
        var decrypted = String(cipher.doFinal(cipherText), charset = Charsets.UTF_8)
        println(decrypted)
    }

**Comment by terrafrost** [comment]
This should do the trick:
```
use phpseclib3\Crypt\DES;

$cipher = new DES('cbc');
$cipher->setKey(str_repeat('a', 16));
$cipher->setIV(str_repeat('b', 16));
$cipher->disablePadding();

echo bin2hex($cipher->encrypt('test'));
```

**Comment by terrafrost** [comment]
The above code is for phpseclib 3. If you're using phpseclib 2 then this is the code you'd want to use:

```php
use phpseclib\Crypt\DES;

$cipher = new DES(); // could use DES::MODE_CBC
$cipher->setKey($key);
$cipher->setIV($key);
$cipher->disablePadding();

echo bin2hex($cipher->encrypt('test'));
```

**Comment by jealvin** [comment]
> The above code is for phpseclib 3. If you're using phpseclib 2 then this is the code you'd want to use:
> 
> ```
> use phpseclib\Crypt\DES;
> 
> $cipher = new DES(); // could use DES::MODE_CBC
> $cipher->setKey($key);
> $cipher->setIV($key);
> $cipher->disablePadding();
> 
> echo bin2hex($cipher->encrypt('test'));
> ```

thx it works
