### ISSUE TITLE
Endless loop when no auth_methods_to_continue 

### ISSUE THREAD

**Issue by yarkm13** [phpseclib/phpseclib#1753]
https://github.com/phpseclib/phpseclib/blob/cc65aa3b0e9efd982688f921028cbdb158c2905e/phpseclib/Net/SSH2.php#L2288

It seems that SFTP servers returns available auth methods string with null char at the end

`"\x00\x00\x00\x12publickey,password\x00"`

it works fine but SFTP server can be cofigured to show no available auth methods to unknown users. In this case string will looks like

`"\x00\x00\x00\x00\x00"`

and auth_methods_to_continue array will contain the only element with empty string

```
array:1 [
  0 => ""
]
```

So in this loop

```
                foreach ($this->auth_methods_to_continue as $method) {
                    switch ($method) {
```

no appropriate case for empty sring and `$args` will never loose that element and outer `while` will never ends

I don't have lot of experience with such protocols to be sure in my suggestion, but i believe that 

```
        return $this->_filter(rtrim($payload, "\0"), $skip_channel_filter);
```

in `_get_binary_packet()` will work perfectly.

Also it's possible to just filter empty methods before `while` like 

```
$this->auth_methods_to_continue = array_filter($this->auth_methods_to_continue)
```

so `!$this->auth_methods_to_continue` will evaluate to false and clear `$args` but it's rather workaround instead of fix.

To reproduce such condition setup SFTP like following

```
PubKeyAuthentication no
PasswordAuthentication no

Match User sftp_user

PubKeyAuthentication yes
PasswordAuthentication yes
```

`/etc/ssh/sshd_config`

and try to establish public key auth connection with any username except sftp_user

tested on
Ubuntu 18.04.6 LTS
Debian 11.1
hetzner storage-box sevice (version unknown)

Also you can try it here (hetzner storage-box)

```
host: u279209.your-storagebox.de
port: 23
username: any random except u279209
```

_please do not generate excess trafic here, setup your own environment for testing_

**Comment by terrafrost** [comment]
I was able to reproduce this with phpseclib 3.0.12 but not with phpseclib 3.0.13. Most likely https://github.com/phpseclib/phpseclib/commit/a74707e08052a54430ec525c7d0c03916518989b fixed the issue. #1744 also reported on this issue.
