### ISSUE TITLE
find OS name on remote server over SSH/SFTP using phpseclib v3.0.12

### ISSUE THREAD

**Issue by raghuveer** [phpseclib/phpseclib#1755]
Hi,

Anyway to identify OS on the remote server using phpseclib?

I tried based on 
`$sftp->getServerIdentification();`

it gives OpenSSH version etc..., but not the OS name, any method to accurately identify the OS like with 
`PHP_OS`

but over SFTP?

Thank you

**Comment by terrafrost** [comment]
No way to do that with SFTP. You could do it with SSH2 using any of the techniques described at https://www.cyberciti.biz/faq/find-linux-distribution-name-version-number/ but not with pure SFTP.

**Comment by raghuveer** [comment]
Thank you @terrafrost , so I will connect over SSH, get info, disconnect by doing `$ssh->exec('exit')`, then try connecting with SFTP, to run target server OS related logic, as much possible.
