### ISSUE TITLE
PHP 8 - deprecated conversion in Net/SSH2.php (phpseclib 1.0)

### ISSUE THREAD

**Issue by DavidAnderson684** [phpseclib/phpseclib#1762]
I have an end user reporting these two deprecation notices to us, using phpseclib 1.0.20 (I don't have much other context):

```
* PHP event: code E_DEPRECATED: Implicit conversion from float 972354.8889160156 to int loses precision (line 1338,vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php)
* PHP event: code E_DEPRECATED: Implicit conversion from float 905452.9666900635 to int loses precision (line 3525,vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php)
```

Looking at those lines, the error reporting is suppressed by `@`, however, the comment immediately preceding indicates that this isn't because of the above conversion, it's because "on windows this returns a "Warning: Invalid CRT parameters detected" error". Before PHP 8, the @ would have caused the deprecation warning to not be passed to our error handler (see: https://www.php.net/manual/en/function.set-error-handler.php). But now we are getting it.

I'm guessing it's the `$usec` parameter that needs explicit casting to an `int`.

**Comment by terrafrost** [comment]
Does https://github.com/phpseclib/phpseclib/commit/ba4414c2f3788b64de17e922d0496f6913c05898 fix the issue?

**Comment by DavidAnderson684** [comment]
I don't have access to the user's server, but it surely will - there are no other parameters on that line that could be floats.
