### ISSUE TITLE
Fail to Run on Linux

### ISSUE THREAD

**Issue by gerardgilliland** [phpseclib/phpseclib#1767]
phpseclib Support,

https://phpseclib.com/docs/install

Without Composer
create a new directory
In this new directory create a new file
composer.json - and prepopulate it with the following:
{
    "require": {
        "phpseclib/phpseclib": "~3.0"
    }
}

Then, in your shell, type the following in:

composer install

Once you do that the new directory will then have the following structure:

composer.json
composer.lock
vendor/

Include these files in your application and do this at the top of your file and you'll be golden:

require __DIR__ . '/vendor/autoload.php';

your Next button brings up 404 File not found
I think I am more rust than golden.

.......................

Attempting the above on Linux server ...

puTTY into Linux server:
    $host = "home208845805.1and1-data.host";
    $user = "u45596567-Nvidia";
    $folder "Nvidia";

(uiserver):u45596567:~/Nvidia$ ls
composer.json
(uiserver):u45596567:~/Nvidia$ composer install
-bash: composer: command not found

trying other ...
(uiserver):u45596567:~/Nvidia$ /usr/bin/php7.4-cli composer install
Could not open input file: composer
(uiserver):u45596567:~/Nvidia$ /usr/bin/php7.4 composer install
Status: 404 Not Found
Content-type: text/html; charset=UTF-8
No input file specified.

trying other ...
(uiserver):u45596567:~$ wget https://raw.githubusercontent.com/composer/getcomposer.org/master/web/installer
(uiserver):u45596567:~$ mv installer composer-setup.php
(uiserver):u45596567:~$ /usr/bin/php7.4 composer-setup.php
Composer (version 2.2.6) successfully installed to: /homepages/36/d208845805/htdocs/composer.phar
Use it: php composer.phar
(uiserver):u45596567:~/Nvidia$ mv composer.phar composer
(uiserver):u45596567:~/Nvidia$ rm composer-setup.php
(uiserver):u45596567:~/Nvidia$ ls
composer  composer.json

one more time ...
(uiserver):u45596567:~/Nvidia$ /usr/bin/php7.4-cli composer install
No composer.lock file present. Updating dependencies to latest instead of installing from lock file. 
See https://getcomposer.org/install for more information.
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking paragonie/constant_time_encoding (v2.5.0)
  - Locking paragonie/random_compat (v9.99.100)
  - Locking phpseclib/phpseclib (3.0.13)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Downloading paragonie/random_compat (v9.99.100)
  - Downloading paragonie/constant_time_encoding (v2.5.0)
  - Downloading phpseclib/phpseclib (3.0.13)
  - Installing paragonie/random_compat (v9.99.100): Extracting archive
  - Installing paragonie/constant_time_encoding (v2.5.0): Extracting archive
  - Installing phpseclib/phpseclib (3.0.13): Extracting archive
3 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
1 package you are using is looking for funding.
Use the `composer fund` command to find out more!
(uiserver):u45596567:~/Nvidia$
(uiserver):u45596567:~/Nvidia$ ls
composer  composer.json  composer.lock  vendor
YEA !!

running GetSpecieRef.php from 
https://www.modelsw.com/Nvidia/GetSpecieRef.php?Id=0&FileName=C:/Android/unknown/Song/American_Crow_2aCTr.wav

Fatal error: require(): 
Failed opening required '/homepages/36/d208845805/htdocs/Nvidia/vendor/composer/
../phpseclib/phpseclib/phpseclib/bootstrap.php' (include_path='.:/usr/lib/php7.4')
 in /homepages/36/d208845805/htdocs/Nvidia/vendor/composer/autoload_real.php on line 78

Link to GetSpecieRef.php (The password is changed - I can send it to you.)
https://github.com/gerardgilliland/BirdingViaMic/blob/master/GetSpecieRef.php

Thank you and Peace,
Gerard
gerardg@modelsw.com

**Comment by terrafrost** [comment]
First, congrats on figuring out how to install composer, altho I probably would have just followed the instructions at https://getcomposer.org/download/ . 

Anyway, my guess is that you don't have the right permissions on the vendor directory. You ran Composer on the CLI and that most likely created the vendor directory and the contents therein with the owner being the same as the user running the command.

On modelsw.com in the Nvidia directory what are the perms on GetSpecieRef.php? Who is the owner? I'd do recursive chown's and chmod's on the vendor directory to make it match.

Ultimately, tho, this is a Composer issue and I'd post further questions about Composer on https://github.com/composer/composer/issues . I'm just one guy - there are probably a lot more people providing Composer support then there are phpseclib support.

Like you had to wait 20h to get an answer. Maybe you would have only had to have waited 10m to get an answer on https://github.com/composer/composer/issues .

**Comment by terrafrost** [comment]
I can log into the server and get it working for you if you want to email
me the SSH2 credentials. My email is ***@***.***

**Comment by gerardgilliland** [comment]
terrafrost,

TF: I can log into the server and get it working for you if you want to email
me the SSH2 credentials. My email is ***@***.*** <mailto:***@***.***> 
GG: GREAT !!!

I can’t send the SSH2 credentials to ***@***.*** <mailto:***@***.***> 

I believe security is getting in the way of the real world.

I suspect we will need to start a new conversation outside of github.

Please send your email to ***@***.*** ***@***.***> 

You can see my email in CC: line below.

In the meantime, I am heading out to my Server to get the credentials.

Thank you and Peace,

Gerard

**Comment by terrafrost** [comment]
I'm seeing a lot of ***@***.***'s lol. If ***@***.*** doesn't work
try ***@***.***

**Comment by gerardgilliland** [comment]
To lots of *** --  aka terrafrost,

I am trying to get my act together

And send you information that is clear and not filled with my overkill junk

Please stand by …

Thank you,

Gerard 

My email address is

With a space between each character

g e r a r d g @ m o d e l s w . c o m
