### ISSUE TITLE
[bug] PHP Warning:  Undefined array key "OpenSSL" phpseclib/phpseclib/phpseclib/Crypt/RSA.php on line 938

### ISSUE THREAD

**Issue by aaronpk** [phpseclib/phpseclib#1771]
I have a fresh install of phpseclib 3 on PHP 8.1, and I get this error when running the `getEngine()` method in the RSA class.

```
Undefined array key "OpenSSL" phpseclib/phpseclib/phpseclib/Crypt/RSA.php on line 938
```

To reproduce the error:

```php
<?php
require('vendor/autoload.php');
use phpseclib3\Crypt\RSA;
$rsa = RSA::loadPrivateKey(file_get_contents('private.pem'));
$rsa->getEngine();
```

The line it's failing on is:

```php
return self::$engines['OpenSSL'] && self::$defaultExponent == 65537 ? 'OpenSSL' : 'PHP'
```

I'm guessing this should be an `isset()` check instead? Let me know if I'm doing something else wrong though.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/301aad47644f0ac8b622fc627e8a00d2b8a4be19 should fix this.

Thanks!
