### ISSUE TITLE
Bad packet length reported by OpenSSH when executing long (characters) commands

### ISSUE THREAD

**Issue by mewejo** [phpseclib/phpseclib#1777]
Hi,

Version `3.0.13`

We're experiencing the following error from the client (PHP) side:

```
PHP Notice:  fputs(): Send of 228044 bytes failed with errno=104 Connection reset by peer in /var/www/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 4247
```
This is running a long (in char length) command. The command is putting an nginx config file into a server by a redirection command `>` to the file.

We were hoping an upgrade to the latest phpseclib version would solve it (from v2) but it hasn't unfortunately. Today I did some more digging and found this on the server side:

```
Bad packet length 336624.
```

An option is to change how these files are sent to the server, but it would be preferable to fix this issue if possible. It only happens on exceptionally large files/streams of text, and I appreciate it's not the best way to do it (inherited tech debt).

Another issue I found suggested adding a timeout, which is in place but that didn't fix it either.

The version of OpenSSH: `OpenSSH_8.2p1 Ubuntu-4ubuntu0.4, OpenSSL 1.1.1f  31 Mar 2020`

Any help or pointers appreciated, and thanks for your work :-)

**Comment by terrafrost** [comment]
I'm guessing you're using the `exec()` function? If so then this is prob the issue (a stacktrace would confirm):

```php
        // although, in theory, the size of SSH_MSG_CHANNEL_REQUEST could exceed the maximum packet size established by
        // SSH_MSG_CHANNEL_OPEN_CONFIRMATION, RFC4254#section-5.1 states that the "maximum packet size" refers to the
        // "maximum size of an individual data packet". ie. SSH_MSG_CHANNEL_DATA.  RFC4254#section-5.2 corroborates.
        $packet = Strings::packSSH2(
            'CNsCs',
            NET_SSH2_MSG_CHANNEL_REQUEST,
            $this->server_channels[self::CHANNEL_EXEC],
            'exec',
            1,
            $command
        );
        $this->send_binary_packet($packet);
```
Per the comments I'm not sure there's a whole lot that can be done.

For good measure I tried to do a super long command with OpenSSH's CLI client. I first created the command thusly:

```
<?php
file_put_contents('test.sh', 'ssh localhost "echo ' . str_repeat('C', 1024 * 1024) . ' > test.txt"');
```
I then gave test.sh execute permissions and then ran it and got this error:

```
./test.sh: line 1: /usr/bin/ssh: Argument list too long
```
So I feel like this is prob just a fundamental SSH limitation. At least when using `$ssh->exec()` or something comparable. You may have better luck if you run the commands in an interactive shell with a PTY. eg. `$ssh->read('[prompt]'); $ssh->write('big command'); $ssh->read('[prompt]');`

**Comment by mewejo** [comment]
Thanks @terrafrost - I've tried that and had other issues with it breaking out of a here doc. I'll close this for now as the problem would be solved by a pty, just needs more changes this side!

Thanks for the quick reply and help :-)
