### ISSUE TITLE
phpseclib x509

### ISSUE THREAD

**Issue by supriyashukla** [phpseclib/phpseclib#1780]
i am facing   -  Fatal error: Uncaught Error: Class "ASN1" not found in E:\xampp\htdocs\phpseclib\phpseclib3\File\X509.php:336 Stack trace: #0 E:\xampp\htdocs\phpseclib\index.php(12): X509->__construct() #1 {main} thrown in E:\xampp\htdocs\phpseclib\phpseclib3\File\X509.php on line 336

**Comment by supriyashukla** [comment]
> i am facing - Fatal error: Uncaught Error: Class "ASN1" not found in E:\xampp\htdocs\phpseclib\phpseclib3\File\X509.php:336 Stack trace: #0 E:\xampp\htdocs\phpseclib\index.php(12): X509->__construct() #1 {main} thrown in E:\xampp\htdocs\phpseclib\phpseclib3\File\X509.php on line 336

**Comment by terrafrost** [comment]
Can you post your code?

Off hand I'm guessing that you're not using an autoloader.

**Comment by supriyashukla** [comment]
How to use autoloader

**Comment by supriyashukla** [comment]
Yes.where i have to post code

**Comment by supriyashukla** [comment]
`
[phpseclib.zip](https://github.com/phpseclib/phpseclib/files/8512284/phpseclib.zip)
`
