### ISSUE TITLE
Can openssl.cnf file be deleted from the vendor folder ?

### ISSUE THREAD

**Issue by williamdes** [phpseclib/phpseclib#1781]
Can openssl.cnf file be deleted from the vendor folder ?

Why: to remove any useless file from servers around the world.
See (for actual files we delete): https://github.com/phpmyadmin/phpmyadmin/blob/QA_5_1/scripts/create-release.sh#L143-L147

https://github.com/phpseclib/phpseclib/blob/master/phpseclib/openssl.cnf

**Comment by hc-jworman** [comment]
It is used in "phpseclib/Crypt/RSA.php", so I would just leave it.

Anyways, this seems like a nightmare to maintain for little gain :octocat:

**Comment by williamdes** [comment]
> It is used in "phpseclib/Crypt/RSA.php", so I would just leave it.
> 
> Anyways, this seems like a nightmare to maintain for little gain :octocat:

Thank you !
Since we delete the RSA class we can remove this file too
See: https://github.com/phpmyadmin/phpmyadmin/blob/ea6a70037c8443c4405bba2242a1fd56a0948da4/scripts/create-release.sh#L215-L220
