### ISSUE TITLE
How can I get the size of a directory in bytes with SFTP/SCP 

### ISSUE THREAD

**Issue by insinfo** [phpseclib/phpseclib#1782]
How can I get the size of a directory in bytes with SFTP/SCP to calculate copy progress

**Comment by terrafrost** [comment]
Doing `$sftp->filesize('/home');` returns 4096 for me. This is also what typing in `stat /home` outputs as the size of the directory. https://askubuntu.com/q/186813/180177 talks about why Linux works this way.

If you want to see the size of all the files within the directory and you want to do so recursively...  per https://unix.stackexchange.com/a/67808/54354 you could do `du -s /home`. You could do this with phpseclib with `$sftp->exec()`.

If you wanted to do this with pure SFTP (eg. you're connecting to a jail shelled host) I guess you could do `$sftp->rawlist('/home', true)` and then parse the resultant array and add up all the size keys, provided the type key was `NET_SFTP_TYPE_REGULAR`. As discussed above, the file size for directories doesn't mean much. I guess symlinks would be another consideration, along with sockets, etc.

I don't think there's an easy way in SFTP to get the size of a _directory_. WinSCP doesn't do it.

phpseclib gets the size of files using [SSH_FXP_STAT](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.8). [SSH_FXP_READDIR](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.7) will return file attribute info as well (that packet is used when you are listing the contents of a directory).

**Comment by insinfo** [comment]
I implemented code for this in dart a while ago for SCP, but I thought phpseclib would have a ready-made method for this?

```dart
 ///return total size in bytes of Directory
  int getSizeOfDirectory(
      Pointer<ssh_session_struct> session, String remoteDirectoryPath,
      {bool isThrowException = true}) {

    var cmdToGetTotaSize =
        "find $remoteDirectoryPath -type f -print0 | xargs -0 stat --format=%s | awk '{s+=\$1} END {print s}'";
    String? cmdRes;
    try {
      cmdRes = execCommandSync(session, cmdToGetTotaSize);
      if (cmdRes.trim().isEmpty) {
        //check is symbolic link    
        cmdRes = execCommandSync(session, 'file $remoteDirectoryPath');
     //is it a symbolic link?
        if (cmdRes.contains('symbolic')) {
        // get the real path of the symbolic link
          var cmdRe =
              execCommandSync(session, 'readlink -f $remoteDirectoryPath');
          if (cmdRe.trim().isNotEmpty) {
            cmdRes = execCommandSync(session,
                "find ${cmdRe.replaceAll(RegExp(r'\n'), '')} -type f -print0 | xargs -0 stat --format=%s | awk '{s+=\$1} END {print s}'");
          }
        }
      }
      //for old debian like debian  6
      //old debian bug 1.57903e+10
      if (cmdRes.contains('e+')) {
        cmdRes = execCommandSync(session,
            'find $remoteDirectoryPath -type f -print0 | xargs -0 stat --format=%s |  paste -sd+ - | bc -l');
      } else if (int.tryParse(cmdRes) == null) {
     
        cmdRes = execCommandSync(session,
            'find $remoteDirectoryPath -type f -print0 | du -scb -L --apparent-size --files0-from=- | tail -n 1');
        return int.parse(cmdRes.split(' ').first.trim());
      }

      return int.parse(cmdRes);
    } catch (e) {
      print(
          'getSizeOfDirectory: $e \r\n cmdToGetTotaSize: $cmdToGetTotaSize \r\n cmdRes: $cmdRes');
      if (isThrowException) {
        throw LibsshGetFileSizeException(
            'Unable to get the size of a directory in bytes, \r\n cmd: $cmdToGetTotaSize cmdResult: $cmdRes');
      }
    }
    return 0;
  }
```
code from [libssh_binding](https://github.com/insinfo/libssh_binding/blob/master/lib/src/extensions/scp_extension.dart)

**Comment by terrafrost** [comment]
That's executing commands on the system, something which phpseclib doesn't do. I mean, Net/SCP.php does it but (1) _only_ calls the SCP executable and the commands you're calling _strictly_ SCP  and (2) phpseclib 3.0 dropped SCP support as think SFTP is the overall superior protocol. And in the context of SFTP this doesn't make a lot of sense because SFTP is an SSH subsystem. SFTP works even on jail shelled systems. Like some servers will let you SFTP whilst not letting you run commands on the CLI.

The way I see it, this is kinda like http://www.soucy.org/project/cisco/ uses phpseclib to connect to and manage Cisco routers. It issues it's own commands that presumably only work on Cisco routers. imho stuff like that has no business in phpseclib-core.

If you want to use phpseclib in a new library to implement the functionality you're looking for feel free but imho it does not belong in phpseclib-core.

**Comment by insinfo** [comment]
perhaps a more compatible option with pure SFTP would be to implement a fear in phpseclib that scans directories using $sftp->rawlist('/home', true) and SSH_FXP_STAT. SSH_FXP_READDIR to count the size of all files, this would be a convenience feature for the phpseclib user

**Comment by terrafrost** [comment]
See https://github.com/phpseclib/phpseclib/commit/b8f8f0b7dba76bece84786f504f9a04b31d75235
