### ISSUE TITLE
A non-numeric value encountered in SFTP.php

### ISSUE THREAD

**Issue by Ivalys** [phpseclib/phpseclib#1787]
Hi,

I used to get this error while trying to push a file through SFTP : A non-numeric value encountered in phpseclib/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php at line 2265.

I'm pretty sure it came from a constant (NET_SFTP_LOCAL_FILE) I was using in phpseclib 2.0, as this error occurs since I upgraded the library.

`if(!$sftp->put(xxxx, yyyy, NET_SFTP_LOCAL_FILE)) {`

Does this constant changed ? If yes, can you confirm it changed to SOURCE_LOCAL_FILE ?

**Comment by terrafrost** [comment]
You need to be doing `SFTP::SOURCE_LOCAL_FILE` now instead of `NET_SFTP_LOCAL_FILE`

**Comment by Ivalys** [comment]
Thanx @terrafrost, it solved the incident !
