### ISSUE TITLE
LengthException when MaxAuthTries is 1 and authentication fails

### ISSUE THREAD

**Issue by NickstaDB** [phpseclib/phpseclib#1790]
A LengthException is thrown with the message `At least one byte needs to be present for successful C / b decodes` when authentication fails against a server that is configured with the following:

```
MaxAuthTries 1
```

With this configuration, when an authentication failure occurs, OpenSSH responds with a `NET_SSH2_MSG_DISCONNECT` packet, rather than the `NET_SSH2_MSG_USERAUTH_FAILURE` packet that phpseclib expects. This leads to the above exception when the following line attempts to unpack data that isn't available:

https://github.com/phpseclib/phpseclib/blob/bff58b0d5b7900d6cfffe79d6186ece8fc874242/phpseclib/Net/SSH2.php#L2351

A simple `false` check immediately prior to the above line of code seems to be enough to resolve the issue. E.g.

```php
    $response = $this->get_binary_packet();
    if($response === false) {
        return false;
    }
```

The call to `get_binary_packet()` seems to handle the disconnect, down to setting `$this->bitmap` to `0`, which in-turn causes any subsequent calls to `login_helper()` to return immediately (i.e. from https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SSH2.php#L2224), causing `sublogin()` and `login()` to return false.

**Comment by terrafrost** [comment]
Good idea. I'll try to make the change this evening.

Thanks!

**Comment by terrafrost** [comment]
This has been done:

https://github.com/phpseclib/phpseclib/commit/a965060d815b138795774d5b4d949421950ec716

Thanks for the feedback!
