### ISSUE TITLE
Getting exception on FTP call: Expected NET_SFTP_NAME or NET_SFTP_STATUS. Got packet type: 

### ISSUE THREAD

**Issue by BobDankert** [phpseclib/phpseclib#1796]
We are getting random exceptions during various SFTP calls. The exception is always the same, as noted in the title: `Expected NET_SFTP_NAME or NET_SFTP_STATUS. Got packet type: `. We have a scheduled process that connects to FTP, lists files, downloads a file, then deletes the file - this runs each weekday at 11am. About 1-2x per week we get this exception, and it is thrown on various commands that are executed: sometimes it's `->nlist()`, sometimes `->delete()`, could be other commands (though there aren't many others) that I didn't pay attention to as well.

Logging `->getErrors()` is blank and `->getSFTPErrors()` is also blank.

I do have the output from `->getLog()` which I can share - not sure if there is anything sensitive in there that needs to be removed before sharing?

The SFTP code looks like this:

```
try {
  $sftp = new SFTP($sftpUrl);
  if (!$sftp->login($sftpUser, $sftpPassword)) {
    throw new \Exception('SFTP Login failed');
  }

  $files = $sftp->nlist();

  // process $files above, assign file to download as $file
  if ($sftp->get($file, $localEncryptedImportFile) === false) {
    throw new \Exception('Unable to download the file from the SFTP');
  }

  $sftp->disconnect();

  // Disconnect from SFTP while performing other tasks

  // After other tasks, we reconnect and do more stuff on SFTP
  $sftp = new SFTP($sftpUrl);
  if (!$sftp->login($sftpUser, $sftpPassword)) {
    throw new \Exception('SFTP Login failed');
  }

  if (!$sftp->delete($file)) {
    throw new \Exception('Unable to delete the file from the SFTP');
  }

  $sftp->disconnect();
}
catch (\Exception $exception) {
  $this->saveDebug('Exception: FTP Errors', json_encode($sftp->getErrors()));
  $this->saveDebug('Exception: SFTP Errors', json_encode($sftp->getSFTPErrors()));
  $this->saveDebug('Exception: SSH Log', json_encode($sftp->getLog()));
  $this->saveDebug('Exception: SFTP Log', json_encode($sftp->getSFTPLog()));
  $this->saveDebug('Exception: Exception Message', json_encode($exception->getMessage()));
}
```

**Comment by terrafrost** [comment]
Got it! I'll try to take a look later today or tomorrow.

Thanks!

**Comment by BobDankert** [comment]
Per @terrafrost recommendation, I am adding `$sftp->disablePathCanonicalization()` to my code before login to see if that fixes this issue. The FTP Server is WS_FTP which is apparently a problematic FTP server. I will update if this resolves the error for us!

**Comment by BobDankert** [comment]
Finally got it working thanks to the help of @terrafrost ! We needed to add `$sftp->disablePathCanonicalization()` prior to the login, and then change the call to nlist() to include a directory, calling: `$sftp->nlist('.')`. We also needed to add `./` to our `$sftp->get()` calls and the `$sftp->delete()` calls as a prefix to the filename.
