### ISSUE TITLE
Undefined constant "phpseclib3\Net\NET_SSH2_DISCONNECT_BY_APPLICATION"

### ISSUE THREAD

**Issue by pacoorozco** [phpseclib/phpseclib#1797]
Hi,
I'm using this library inside Laravel, when I create a `SFTP` object I got this error:

```
Undefined constant "phpseclib3\Net\NET_SSH2_DISCONNECT_BY_APPLICATION" {"exception":"[object] (Error(code: 0): Undefined constant \"phpseclib3\\Net\\NET_SSH2_DISCONNECT_BY_APPLICATION\" at /var/www/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3271)
```
I've read the closed issues and I've seen #1337 but It doesn't point to any bug.

My code is this one... a Job constructor:

```
namespace App\Jobs;

use App\Models\Host;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use phpseclib3\Net\SFTP;

class UpdateServer implements ShouldQueue
{
    use Dispatchable;
    use InteractsWithQueue;
    use Queueable;
    use SerializesModels;

    protected Host $host;
    protected SFTP $sftp;

    public function __construct(Host $host)
    {
        $this->host = $host;

        $this->sftp = new SFTP($host->hostname);
    }
}
```
Using

- PHP 8.0
- Laravel 9
- phpseclib 3.0.14

**Comment by terrafrost** [comment]
In #1337 I explained why that error doesn't make any sense to me. Re-reviewing the code leaves me with the same conclusions. I don't understand how that's an issue and I am unable to reproduce it.

Like consider this code:

```php
<?php
namespace Demo\Demo;

define('ZZZ', 'hello, world');

echo \Demo\Demo\ZZZ . "\n";
```
Defining a constant in a namespace doesn't mean that that constant is "attached" to that namespace.

In phpseclib it's done in a class but even defining it in the context of a class doesn't let me reproduce the error:

```php
<?php
namespace Demo\Demo;

class A {
    function __construct() {
        define('ZZZ', 'hello, world');
    }
}

new A;

echo ZZZ . "\n";
echo \Demo\Demo\ZZZ . "\n";
```

**Comment by terrafrost** [comment]
One thing you could try...  in SSH2.php there's this:

```php
                if (!defined($value)) {
                    define($value, $key);
```
Maybe try replacing that with this:

```php
                if (!defined("\\phpseclib3\\Net\\$value)) {
                    define("\\phpseclib3\\Net\\$value", $key);
```
I mean, I feel like that'll probably break even more stuff but...  couldn't hurt to try.

If you give me SFTP access to a server with all the code in place to reproduce this issue I can give it a gander, altho even with that, the fact that it's in App\Jobs with ImplementsQueue kinda makes it a PITA to diagnose. I'd have to change QUEUE_DRIVER in config/queue.php to sync if it wasn't already, to more easily test it. Ideally it'd be reproducable with a php artisan command

**Comment by pacoorozco** [comment]
Hi @terrafrost 

Thanks for your quick reply. I agree with you that defining a constant, even in a class, would have to work. Before opening this issue I reviewed it a lot. I couldn't understand why it was not working.

You can get the code in [GitHub (branch issue-305)](https://github.com/pacoorozco/ssham/tree/issue-305), there is a docker-compose that will generate all the necessary environment to run it and reproduce the error. 

Once you have followed the README to setup everything, just run this command:

```
docker-compose exec app php artisan ssham:send
```

and review the log file `storage/logs/laravel-2022-MM-DD.log` to see the error.

**Comment by pacoorozco** [comment]
While I was repeating the process to write the instructions above I have seen that something has changed... Now the error is not related to `phpseclib`... 🤷🏼 

Let me test it again and I will probably close this ticket...

**Comment by pacoorozco** [comment]
Confirmed! I don't know how but the error is over 🤷🏼 

Sorry to bother you!

**Comment by terrafrost** [comment]
I just tried to check out the code and followed your directions to reproduce the error but like you said it's now working.

Ugh. I'd like to know what was up with it. Like if I need to do this under certain conditions:

```php
                if (!defined("\\phpseclib3\\Net\\$value)) {
                    define("\\phpseclib3\\Net\\$value", $key);
```
It'd be nice to have those conditions mapped out but even if that would be a fix idk what the conditions I'd need to check for are.

But like you said, it's working now, so meh.

Looks like an interesting project, incidentally!
