### ISSUE TITLE
Undefined variable $elapsed

### ISSUE THREAD

**Issue by malohtie** [phpseclib/phpseclib#1802]
it seem that $elapsed is not reached when you throw an excpetion in this line https://github.com/phpseclib/phpseclib/blob/2f0b7af658cbea265cbb4a791d6c29a6613f98ef/phpseclib/Net/SSH2.php#L3450 in some scenario

i'm using phpseclib 3.0.14 

```
{
    "class": "ErrorException",
    "message": "Undefined variable $elapsed",
    "code": 0,
    "file": "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3450",
    "trace": [
        "/var/aa/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php:255",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3450",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:3966",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4394",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:3283",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:608",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:637",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:532",
        "/var/aa/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php:2649",
}
```

**Comment by jack-worman** [comment]
My PHPStorm inspection showed ~60 "possible undefined variables". Which means there are logic paths the runtime could take to lead to that variable being undefined. I'll probably try to address those after the PHP 7.0 upgrade PR goes through

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/62677de0bfe4bbc5f21fe3bbabe3501c13a7d86f should fix the issue identified in this post.

Thanks!
