### ISSUE TITLE
Reply to run command

### ISSUE THREAD

**Issue by Softyr** [phpseclib/phpseclib#1803]
Hello,

I am running a command but how can I reply to it?

I want to write "1" as answer

```
<?php
include('Net/SSH2.php');

$ssh = new Net_SSH2('XXX');
if (!$ssh->login('root', 'XXX')) {
    exit('Login Failed');
}

echo "<pre>";
echo $ssh->exec('./discord-mass-dm-GO');
```

![image](https://user-images.githubusercontent.com/61640731/174103235-81322313-b908-46c3-a66c-8a212e472053.png)

**Comment by terrafrost** [comment]
You'd need to either use `$ssh->read()` / $ssh->write()` or else you'd need to enable a PTY by doing `$ssh->enablePTY()`.

The following URLs provide some examples:

https://phpseclib.com/docs/commands#exec-with-and-without-a-pty-vs-interactive-shells
https://phpseclib.com/docs/commands#read-with-regular-expressions-sudo

Apologies for the delayed response!
