### ISSUE TITLE
Static call to non-static method (results in an error starting from PHP 8.0)

### ISSUE THREAD

**Issue by vadym-ovechkin** [phpseclib/phpseclib#1805]
Hello, during preparation for migration of my project to PHP 8.1 I ran a static analyzer which have detected one problem in the package.

It complains about this line: https://github.com/phpseclib/phpseclib/blob/545b43cd700c986b0b11caa0fdf8b0d0ac18f6c6/phpseclib/File/X509.php#L2643

The `dnsName` method is not static but called as a static one. This results in an error starting from PHP 8.0 (see https://www.php.net/manual/en/migration80.incompatible.php)

I guess this helper method can simply be marked as static, and this will solve the problem

**Comment by jack-worman** [comment]
Would you provide a PR?

**Comment by jack-worman** [comment]
Closed by #1806
