### ISSUE TITLE
SubjectInfoAccessSyntax var is not defined

### ISSUE THREAD

**Issue by come-nc** [phpseclib/phpseclib#1808]
Hello,

In 2.0, `SubjectInfoAccessSyntax` property of `phpseclib\File\X509` is not declared.

(Spotted by running a dev build of PHP 8.2 which now warns about such things)

**Comment by terrafrost** [comment]
Looks like it's defined to me?:

https://github.com/phpseclib/phpseclib/blob/5a3e622c4deff961fd66cf3af0ba497f73383e9f/phpseclib/File/X509.php#L966-L971

(it's defined in the constructor along with pretty much every other property)

Can you post the full error message you're getting? Maybe some sample code that demonstrates the problem on PHP 8.2?

**Comment by jack-worman** [comment]
I believe the problem is that `$this->SubjectInfoAccessSyntax` is defined dynamically. It does not have a property declaration: `public $SubjectInfoAccessSyntax;`

**Comment by come-nc** [comment]
Thank you :heart:

**Comment by come-nc** [comment]
@terrafrost Hello, would it be possible to have a 2.0 release with this fix?

**Comment by terrafrost** [comment]
I'm gonna do a release within the next few days!

**Comment by terrafrost** [comment]
2.0.38 has been released.

Thanks!
