### ISSUE TITLE
PHP Fatal error:  Uncaught RuntimeException: Unable to open channel in /var/www/oneopamin.com/phpseclib/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4075

### ISSUE THREAD

**Issue by pep28** [phpseclib/phpseclib#1811]
Im trying to use phpseclib to connect to a cisco device, but i have some issues:
![Capture git](https://user-images.githubusercontent.com/95448408/176682953-dfd6e13e-143e-47f5-8bb8-7249ad1b6cd5.PNG)

[code.txt](https://github.com/phpseclib/phpseclib/files/9020361/code.txt)

here is the code i'm using to connect

**Comment by terrafrost** [comment]
Can you post your SSH logs? You're already doing `define('NET_SSH2_LOGGING', 2)` but and you have a `echo $ssh->getLog()` in your code, I see, but the `echo $ssh->getLog()` isn't in a try / catch block so it's never being ran. eg. do this:

```php
try {
    $ssh->write("ping 127.0.0.1\n");

    echo $ssh->exec('sleep 3600s; ls -latr');
} catch (\Exception $e) {
    echo $ssh->getLog();
    exit;
}
```

**Comment by terrafrost** [comment]
I see you're using a Cisco router. This is actually a limitation of Cisco devices. They only let you run one command per SSH session. https://stackoverflow.com/a/59661870/569976 talks about this in more depth.
