### ISSUE TITLE
SSH2 login : SSH_MSG_USERAUTH_FAILURE 

### ISSUE THREAD

**Issue by RAFFENNEvalentin** [phpseclib/phpseclib#1812]
Hi,

First of all thanks for your interesting contribution.
I tried several ways to connect to my server. However, succeed in connecting with my usual admin user by this way :

define('NET_SSH2_LOGGING', SSH2::LOG_COMPLEX);
$key = PublicKeyLoader::loadPrivateKey(file_get_contents('my_key'),"blablabla");

try{
    $sftp = new SSH2("146.59.243.11",22);

    /* if (!$sftp->login('usertest', $key)) {
        throw new \Exception('Login failed');
    } */
    if (!$sftp->login("usertest", $key)) {
        echo $sftp->getLastError();
        //echo $sftp->getLog();
        throw new Exception('Not Connected');
    }
}catch(Exception $e){
    $msg= $e->getMessage();
    echo $e;
}

However, i came across this message SSH_MSG_USERAUTH_FAILURE when i tried to connect with another user which called usertest. But i do not understand because there is no issue when tried with my shell (ssh ....) and with filezilla

I have tried several formats for the private key (openssl, ppk, pem) and each works with filezilla and  the shell

To be more precise, i check my ssh/auth.log and i have this :

- pam_unix(smtp:auth): check pass; user unknown
- pam_unix(smtp:auth): authentication failure; logname= uid=0 euid=0 tty= ruser= rhost=
- DEBUG: auth_pam: pam_authenticate failed: Authentication failure : auth failure: [user=hr] [service=smtp] [realm=] [mech=pam] [reason=PAM auth error]
- Invalid user admin from XXX.XX.XXX.XX port XXXXX
- Connection closed by invalid user admin XXX.XX.XXX.XX port XXXXX [preauth]

Thanks for your response ! 
💯

**Comment by RAFFENNEvalentin** [comment]
for sure 👍 
<-
00000000  53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f  SSH-2.0-OpenSSH_
00000010  38:2e:34:70:31:20:44:65:62:69:61:6e:2d:35:0d:0a  8.4p1 Debian-5..

->
00000000  53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69  SSH-2.0-phpsecli
00000010  62:5f:33:2e:30:20:28:6f:70:65:6e:73:73:6c:2c:20  b_3.0 (openssl, 
00000020  62:63:6d:61:74:68:29:0d:0a                       bcmath)..

-> NET_SSH2_MSG_KEXINIT (since last: 0.2501, network: 0.0001s)
00000000  c9:32:a5:92:be:0a:22:c5:34:43:4e:06:04:a4:bb:db  .2....".4CN.....
00000010  00:00:01:7c:63:75:72:76:65:32:35:35:31:39:2d:73  ...|curve25519-s
00000020  68:61:32:35:36:2c:63:75:72:76:65:32:35:35:31:39  ha256,curve25519
00000030  2d:73:68:61:32:35:36:40:6c:69:62:73:73:68:2e:6f  -sha256@libssh.o
00000040  72:67:2c:65:63:64:68:2d:73:68:61:32:2d:6e:69:73  rg,ecdh-sha2-nis
00000050  74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32:2d  tp256,ecdh-sha2-
00000060  6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73:68  nistp384,ecdh-sh
00000070  61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66:66  a2-nistp521,diff
00000080  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000090  2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35:36  -exchange-sha256
000000a0  2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d  ,diffie-hellman-
000000b0  67:72:6f:75:70:2d:65:78:63:68:61:6e:67:65:2d:73  group-exchange-s
000000c0  68:61:31:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d  ha1,diffie-hellm
000000d0  61:6e:2d:67:72:6f:75:70:31:34:2d:73:68:61:32:35  an-group14-sha25
000000e0  36:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e  6,diffie-hellman
000000f0  2d:67:72:6f:75:70:31:34:2d:73:68:61:31:2c:64:69  -group14-sha1,di
00000100  66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f  ffie-hellman-gro
00000110  75:70:31:35:2d:73:68:61:35:31:32:2c:64:69:66:66  up15-sha512,diff
00000120  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000130  31:36:2d:73:68:61:35:31:32:2c:64:69:66:66:69:65  16-sha512,diffie
00000140  2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:37  -hellman-group17
00000150  2d:73:68:61:35:31:32:2c:64:69:66:66:69:65:2d:68  -sha512,diffie-h
00000160  65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:31:38:2d:73  ellman-group18-s
00000170  68:61:35:31:32:2c:64:69:66:66:69:65:2d:68:65:6c  ha512,diffie-hel
00000180  6c:6d:61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31  lman-group1-sha1
00000190  00:00:00:71:73:73:68:2d:65:64:32:35:35:31:39:2c  ...qssh-ed25519,
000001a0  65:63:64:73:61:2d:73:68:61:32:2d:6e:69:73:74:70  ecdsa-sha2-nistp
000001b0  32:35:36:2c:65:63:64:73:61:2d:73:68:61:32:2d:6e  256,ecdsa-sha2-n
000001c0  69:73:74:70:33:38:34:2c:65:63:64:73:61:2d:73:68  istp384,ecdsa-sh
000001d0  61:32:2d:6e:69:73:74:70:35:32:31:2c:72:73:61:2d  a2-nistp521,rsa-
000001e0  73:68:61:32:2d:32:35:36:2c:72:73:61:2d:73:68:61  sha2-256,rsa-sha
000001f0  32:2d:35:31:32:2c:73:73:68:2d:72:73:61:2c:73:73  2-512,ssh-rsa,ss
00000200  68:2d:64:73:73:00:00:01:01:61:65:73:31:32:38:2d  h-dss....aes128-
00000210  67:63:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  gcm@openssh.com,
00000220  61:65:73:32:35:36:2d:67:63:6d:40:6f:70:65:6e:73  aes256-gcm@opens
00000230  73:68:2e:63:6f:6d:2c:61:65:73:31:32:38:2d:63:74  sh.com,aes128-ct
00000240  72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73  r,aes192-ctr,aes
00000250  32:35:36:2d:63:74:72:2c:61:65:73:31:32:38:2d:63  256-ctr,aes128-c
00000260  62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c:61:65  bc,aes192-cbc,ae
00000270  73:32:35:36:2d:63:62:63:2c:62:6c:6f:77:66:69:73  s256-cbc,blowfis
00000280  68:2d:63:74:72:2c:62:6c:6f:77:66:69:73:68:2d:63  h-ctr,blowfish-c
00000290  62:63:2c:33:64:65:73:2d:63:74:72:2c:33:64:65:73  bc,3des-ctr,3des
000002a0  2d:63:62:63:2c:74:77:6f:66:69:73:68:31:32:38:2d  -cbc,twofish128-
000002b0  63:74:72:2c:74:77:6f:66:69:73:68:31:39:32:2d:63  ctr,twofish192-c
000002c0  74:72:2c:74:77:6f:66:69:73:68:32:35:36:2d:63:74  tr,twofish256-ct
000002d0  72:2c:74:77:6f:66:69:73:68:31:32:38:2d:63:62:63  r,twofish128-cbc
000002e0  2c:74:77:6f:66:69:73:68:31:39:32:2d:63:62:63:2c  ,twofish192-cbc,
000002f0  74:77:6f:66:69:73:68:32:35:36:2d:63:62:63:2c:74  twofish256-cbc,t
00000300  77:6f:66:69:73:68:2d:63:62:63:00:00:01:01:61:65  wofish-cbc....ae
00000310  73:31:32:38:2d:67:63:6d:40:6f:70:65:6e:73:73:68  s128-gcm@openssh
00000320  2e:63:6f:6d:2c:61:65:73:32:35:36:2d:67:63:6d:40  .com,aes256-gcm@
00000330  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73:31  openssh.com,aes1
00000340  32:38:2d:63:74:72:2c:61:65:73:31:39:32:2d:63:74  28-ctr,aes192-ct
00000350  72:2c:61:65:73:32:35:36:2d:63:74:72:2c:61:65:73  r,aes256-ctr,aes
00000360  31:32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63  128-cbc,aes192-c
00000370  62:63:2c:61:65:73:32:35:36:2d:63:62:63:2c:62:6c  bc,aes256-cbc,bl
00000380  6f:77:66:69:73:68:2d:63:74:72:2c:62:6c:6f:77:66  owfish-ctr,blowf
00000390  69:73:68:2d:63:62:63:2c:33:64:65:73:2d:63:74:72  ish-cbc,3des-ctr
000003a0  2c:33:64:65:73:2d:63:62:63:2c:74:77:6f:66:69:73  ,3des-cbc,twofis
000003b0  68:31:32:38:2d:63:74:72:2c:74:77:6f:66:69:73:68  h128-ctr,twofish
000003c0  31:39:32:2d:63:74:72:2c:74:77:6f:66:69:73:68:32  192-ctr,twofish2
000003d0  35:36:2d:63:74:72:2c:74:77:6f:66:69:73:68:31:32  56-ctr,twofish12
000003e0  38:2d:63:62:63:2c:74:77:6f:66:69:73:68:31:39:32  8-cbc,twofish192
000003f0  2d:63:62:63:2c:74:77:6f:66:69:73:68:32:35:36:2d  -cbc,twofish256-
00000400  63:62:63:2c:74:77:6f:66:69:73:68:2d:63:62:63:00  cbc,twofish-cbc.
00000410  00:00:f7:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  ...hmac-sha2-256
00000420  2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  -etm@openssh.com
00000430  2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2d:65  ,hmac-sha2-512-e
00000440  74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:75  tm@openssh.com,u
00000450  6d:61:63:2d:36:34:2d:65:74:6d:40:6f:70:65:6e:73  mac-64-etm@opens
00000460  73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:2d  sh.com,umac-128-
00000470  65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  etm@openssh.com,
00000480  68:6d:61:63:2d:73:68:61:31:2d:65:74:6d:40:6f:70  hmac-sha1-etm@op
00000490  65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73  enssh.com,hmac-s
000004a0  68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68:61  ha2-256,hmac-sha
000004b0  32:2d:35:31:32:2c:75:6d:61:63:2d:36:34:40:6f:70  2-512,umac-64@op
000004c0  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31  enssh.com,umac-1
000004d0  32:38:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68  28@openssh.com,h
000004e0  6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63  mac-sha1-96,hmac
000004f0  2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39  -sha1,hmac-md5-9
00000500  36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:f7:68:6d  6,hmac-md5....hm
00000510  61:63:2d:73:68:61:32:2d:32:35:36:2d:65:74:6d:40  ac-sha2-256-etm@
00000520  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63  openssh.com,hmac
00000530  2d:73:68:61:32:2d:35:31:32:2d:65:74:6d:40:6f:70  -sha2-512-etm@op
00000540  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:36  enssh.com,umac-6
00000550  34:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f  4-etm@openssh.co
00000560  6d:2c:75:6d:61:63:2d:31:32:38:2d:65:74:6d:40:6f  m,umac-128-etm@o
00000570  70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d  penssh.com,hmac-
00000580  73:68:61:31:2d:65:74:6d:40:6f:70:65:6e:73:73:68  sha1-etm@openssh
00000590  2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32  .com,hmac-sha2-2
000005a0  35:36:2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32  56,hmac-sha2-512
000005b0  2c:75:6d:61:63:2d:36:34:40:6f:70:65:6e:73:73:68  ,umac-64@openssh
000005c0  2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:40:6f:70  .com,umac-128@op
000005d0  65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73  enssh.com,hmac-s
000005e0  68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68:61:31  ha1-96,hmac-sha1
000005f0  2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68:6d:61  ,hmac-md5-96,hma
00000600  63:2d:6d:64:35:00:00:00:1a:6e:6f:6e:65:2c:7a:6c  c-md5....none,zl
00000610  69:62:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:7a  ib@openssh.com,z
00000620  6c:69:62:00:00:00:1a:6e:6f:6e:65:2c:7a:6c:69:62  lib....none,zlib
00000630  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:7a:6c:69  @openssh.com,zli
00000640  62:00:00:00:00:00:00:00:00:00:00:00:00:00        b.............

<- NET_SSH2_MSG_KEXINIT (since last: 0.0002, network: 0.0001s)
00000000  97:15:4a:b2:58:00:07:1c:02:aa:7e:37:ac:5a:76:05  ..J.X.....~7.Zv.
00000010  00:00:00:e6:63:75:72:76:65:32:35:35:31:39:2d:73  ....curve25519-s
00000020  68:61:32:35:36:2c:63:75:72:76:65:32:35:35:31:39  ha256,curve25519
00000030  2d:73:68:61:32:35:36:40:6c:69:62:73:73:68:2e:6f  -sha256@libssh.o
00000040  72:67:2c:65:63:64:68:2d:73:68:61:32:2d:6e:69:73  rg,ecdh-sha2-nis
00000050  74:70:32:35:36:2c:65:63:64:68:2d:73:68:61:32:2d  tp256,ecdh-sha2-
00000060  6e:69:73:74:70:33:38:34:2c:65:63:64:68:2d:73:68  nistp384,ecdh-sh
00000070  61:32:2d:6e:69:73:74:70:35:32:31:2c:64:69:66:66  a2-nistp521,diff
00000080  69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70  ie-hellman-group
00000090  2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32:35:36  -exchange-sha256
000000a0  2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d  ,diffie-hellman-
000000b0  67:72:6f:75:70:31:36:2d:73:68:61:35:31:32:2c:64  group16-sha512,d
000000c0  69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72  iffie-hellman-gr
000000d0  6f:75:70:31:38:2d:73:68:61:35:31:32:2c:64:69:66  oup18-sha512,dif
000000e0  66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75  fie-hellman-grou
000000f0  70:31:34:2d:73:68:61:32:35:36:00:00:00:41:72:73  p14-sha256...Ars
00000100  61:2d:73:68:61:32:2d:35:31:32:2c:72:73:61:2d:73  a-sha2-512,rsa-s
00000110  68:61:32:2d:32:35:36:2c:73:73:68:2d:72:73:61:2c  ha2-256,ssh-rsa,
00000120  65:63:64:73:61:2d:73:68:61:32:2d:6e:69:73:74:70  ecdsa-sha2-nistp
00000130  32:35:36:2c:73:73:68:2d:65:64:32:35:35:31:39:00  256,ssh-ed25519.
00000140  00:00:6c:63:68:61:63:68:61:32:30:2d:70:6f:6c:79  ..lchacha20-poly
00000150  31:33:30:35:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  1305@openssh.com
00000160  2c:61:65:73:31:32:38:2d:63:74:72:2c:61:65:73:31  ,aes128-ctr,aes1
00000170  39:32:2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74  92-ctr,aes256-ct
00000180  72:2c:61:65:73:31:32:38:2d:67:63:6d:40:6f:70:65  r,aes128-gcm@ope
00000190  6e:73:73:68:2e:63:6f:6d:2c:61:65:73:32:35:36:2d  nssh.com,aes256-
000001a0  67:63:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00  gcm@openssh.com.
000001b0  00:00:6c:63:68:61:63:68:61:32:30:2d:70:6f:6c:79  ..lchacha20-poly
000001c0  31:33:30:35:40:6f:70:65:6e:73:73:68:2e:63:6f:6d  1305@openssh.com
000001d0  2c:61:65:73:31:32:38:2d:63:74:72:2c:61:65:73:31  ,aes128-ctr,aes1
000001e0  39:32:2d:63:74:72:2c:61:65:73:32:35:36:2d:63:74  92-ctr,aes256-ct
000001f0  72:2c:61:65:73:31:32:38:2d:67:63:6d:40:6f:70:65  r,aes128-gcm@ope
00000200  6e:73:73:68:2e:63:6f:6d:2c:61:65:73:32:35:36:2d  nssh.com,aes256-
00000210  67:63:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:00  gcm@openssh.com.
00000220  00:00:d5:75:6d:61:63:2d:36:34:2d:65:74:6d:40:6f  ...umac-64-etm@o
00000230  70:65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d  penssh.com,umac-
00000240  31:32:38:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e  128-etm@openssh.
00000250  63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32:35  com,hmac-sha2-25
00000260  36:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f  6-etm@openssh.co
00000270  6d:2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2d  m,hmac-sha2-512-
00000280  65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c  etm@openssh.com,
00000290  68:6d:61:63:2d:73:68:61:31:2d:65:74:6d:40:6f:70  hmac-sha1-etm@op
000002a0  65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:36  enssh.com,umac-6
000002b0  34:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:75:6d  4@openssh.com,um
000002c0  61:63:2d:31:32:38:40:6f:70:65:6e:73:73:68:2e:63  ac-128@openssh.c
000002d0  6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32:35:36  om,hmac-sha2-256
000002e0  2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32:2c:68  ,hmac-sha2-512,h
000002f0  6d:61:63:2d:73:68:61:31:00:00:00:d5:75:6d:61:63  mac-sha1....umac
00000300  2d:36:34:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e  -64-etm@openssh.
00000310  63:6f:6d:2c:75:6d:61:63:2d:31:32:38:2d:65:74:6d  com,umac-128-etm
00000320  40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61  @openssh.com,hma
00000330  63:2d:73:68:61:32:2d:32:35:36:2d:65:74:6d:40:6f  c-sha2-256-etm@o
00000340  70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d  penssh.com,hmac-
00000350  73:68:61:32:2d:35:31:32:2d:65:74:6d:40:6f:70:65  sha2-512-etm@ope
00000360  6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68  nssh.com,hmac-sh
00000370  61:31:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63  a1-etm@openssh.c
00000380  6f:6d:2c:75:6d:61:63:2d:36:34:40:6f:70:65:6e:73  om,umac-64@opens
00000390  73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:40  sh.com,umac-128@
000003a0  6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63  openssh.com,hmac
000003b0  2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73  -sha2-256,hmac-s
000003c0  68:61:32:2d:35:31:32:2c:68:6d:61:63:2d:73:68:61  ha2-512,hmac-sha
000003d0  31:00:00:00:15:6e:6f:6e:65:2c:7a:6c:69:62:40:6f  1....none,zlib@o
000003e0  70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:15:6e:6f  penssh.com....no
000003f0  6e:65:2c:7a:6c:69:62:40:6f:70:65:6e:73:73:68:2e  ne,zlib@openssh.
00000400  63:6f:6d:00:00:00:00:00:00:00:00:00:00:00:00:00  com.............

-> NET_SSH2_MSG_KEX_ECDH_INIT (since last: 1.1623, network: 0.0002s)
00000000  00:00:00:20:b3:bc:a3:bd:ac:43:81:05:72:1f:87:38  ... .....C..r..8
00000010  fd:53:79:bd:ec:d5:a3:7a:20:87:2c:c3:aa:4b:05:fa  .Sy....z .,..K..
00000020  3f:3a:14:6a                                      ?:.j

<- NET_SSH2_MSG_KEX_ECDH_REPLY (since last: 0.0561, network: 0.0561s)
00000000  00:00:00:33:00:00:00:0b:73:73:68:2d:65:64:32:35  ...3....ssh-ed25
00000010  35:31:39:00:00:00:20:30:e2:80:e0:31:d7:e7:e0:f9  519... 0...1....
00000020  fa:f1:a2:56:45:36:4c:05:1e:9b:ba:50:62:a2:05:b8  ...VE6L....Pb...
00000030  87:30:e8:bb:20:d9:2d:00:00:00:20:49:22:b7:ea:85  .0.. .-... I"...
00000040  71:63:f0:78:8c:7b:ff:ec:61:36:5e:08:ce:5e:3a:6c  qc.x.{..a6^..^:l
00000050  96:40:ad:c4:3f:93:7b:2c:37:4e:7e:00:00:00:53:00  .@..?.{,7N~...S.
00000060  00:00:0b:73:73:68:2d:65:64:32:35:35:31:39:00:00  ...ssh-ed25519..
00000070  00:40:b7:30:62:f1:7a:19:11:f2:e2:38:87:34:f0:6f  .@.0b.z....8.4.o
00000080  e5:58:d6:ed:ad:10:b4:48:65:69:b5:f0:8a:5c:e5:02  .X.....Hei...\..
00000090  82:f1:20:d9:0b:a8:b2:c2:59:b2:ac:6d:69:40:72:90  .. .....Y..mi@r.
000000a0  10:32:6d:c5:c3:53:9b:e7:ce:81:18:86:ae:6f:f2:84  .2m..S.......o..
000000b0  79:0b                                            y.

-> NET_SSH2_MSG_NEWKEYS (since last: 1.3577, network: 0.0001s)
                                                 

<- NET_SSH2_MSG_NEWKEYS (since last: 0.0013, network: 0.0013s)
                                                 

-> NET_SSH2_MSG_SERVICE_REQUEST (since last: 0.0005, network: 0s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

<- NET_SSH2_MSG_SERVICE_ACCEPT (since last: 0.0945, network: 0.0943s)
00000000  00:00:00:0c:73:73:68:2d:75:73:65:72:61:75:74:68  ....ssh-userauth

-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0149, network: 0.0001s)
00000000  00:00:00:07:74:65:73:74:62:62:6c:00:00:00:0e:73  ....testbbl....s
00000010  73:68:2d:63:6f:6e:6e:65:63:74:69:6f:6e:00:00:00  sh-connection...
00000020  04:6e:6f:6e:65                                   .none

<- NET_SSH2_MSG_USERAUTH_FAILURE (since last: 0.0794, network: 0.0792s)
00000000  00:00:00:09:70:75:62:6c:69:63:6b:65:79:00        ....publickey.

-> NET_SSH2_MSG_USERAUTH_REQUEST (since last: 0.0335, network: 0.0001s)
00000000  00:00:00:07:74:65:73:74:62:62:6c:00:00:00:0e:73  ....testbbl....s
00000010  73:68:2d:63:6f:6e:6e:65:63:74:69:6f:6e:00:00:00  sh-connection...
00000020  09:70:75:62:6c:69:63:6b:65:79:00:00:00:00:0c:72  .publickey.....r
00000030  73:61:2d:73:68:61:32:2d:32:35:36:00:00:01:97:00  sa-sha2-256.....
00000040  00:00:07:73:73:68:2d:72:73:61:00:00:00:03:01:00  ...ssh-rsa......
00000050  01:00:00:01:81:00:cc:b2:69:43:e6:3f:5c:ee:18:62  ........iC.?\..b
00000060  ec:b6:63:fd:86:90:b7:0f:37:bc:c0:0f:8f:a0:14:45  ..c.....7......E
00000070  e4:18:9d:eb:39:8e:6e:3b:dd:68:63:ec:9f:0c:05:9f  ....9.n;.hc.....
00000080  68:73:c5:d6:dd:03:9a:c2:db:e3:30:ca:23:d0:81:99  hs........0.#...
00000090  11:f5:8b:2a:51:7e:71:e8:e5:dd:73:5d:b4:43:78:73  ...*Q~q...s].Cxs
000000a0  f3:26:2d:a5:55:b5:3e:f8:5e:02:83:19:9c:ff:f3:a3  .&-.U.>.^.......
000000b0  43:42:3c:7f:40:31:49:96:d3:40:84:c5:42:bd:de:db  CB..@1I..@..B...
000000c0  ef:cd:bc:f0:bb:bf:5b:b6:4d:7e:4a:1d:dd:b9:b2:2a  ......[.M~J....*
000000d0  60:f6:57:e8:96:9e:56:36:b7:90:d3:47:45:7a:87:37  `.W...V6...GEz.7
000000e0  1d:2b:be:64:52:9e:bf:d0:64:30:83:2b:41:a3:ca:2d  .+.dR...d0.+A..-
000000f0  ed:3e:7e:1b:79:59:5e:d2:e5:b9:60:c9:61:3c:2a:ed  .>~.yY^...`.a.*.
00000100  cf:aa:38:d4:02:e2:64:11:81:4c:0a:0b:45:8c:10:c7  ..8...d..L..E...
00000110  7e:44:2f:c1:2e:ba:dc:f4:9e:7d:00:2a:51:59:ad:ea  ~D/......}.*QY..
00000120  c7:26:b3:d0:8c:56:81:1a:46:ed:7b:2f:01:a5:e0:29  .&...V..F.{/...)
00000130  9f:1f:6e:5f:fa:96:b7:8e:4e:44:ca:05:6a:18:e9:27  ..n_....ND..j..'
00000140  3a:e2:af:5a:ea:7f:80:c6:5f:9b:e1:55:fb:69:f4:c6  :..Z...._..U.i..
00000150  a4:9e:c5:55:be:c4:f0:98:a6:af:ce:73:d1:00:12:bb  ...U.......s....
00000160  3a:47:ef:f8:5d:52:fb:47:8d:94:cf:25:44:89:43:af  :G..]R.G...%D.C.
00000170  42:ec:b5:b8:de:c4:7a:63:67:f3:2f:7b:29:97:6d:87  B.....zcg./{).m.
00000180  fe:4e:ac:3c:22:24:0e:c0:2e:71:96:bf:cb:8d:9f:18  .N.."$...q......
00000190  e4:84:4b:a1:aa:2d:c3:32:b5:7d:d5:5e:29:ae:53:e2  ..K..-.2.}.^).S.
000001a0  43:c7:36:c3:63:81:a5:b9:fd:20:5d:fe:ab:2c:02:43  C.6.c.... ]..,.C
000001b0  14:5e:0b:76:ce:9c:20:ec:ad:8f:e5:34:3d:33:7f:bf  .^.v.. ....4=3..
000001c0  ce:5c:10:bf:6c:ba:41:e7:fe:e3:2c:c8:a8:c9:8e:c1  .\..l.A...,.....
000001d0  64:3c:fa:75:10:e9                                d..u..

<- NET_SSH2_MSG_USERAUTH_FAILURE (since last: 0.0662, network: 0.0661s)
00000000  00:00:00:09:70:75:62:6c:69:63:6b:65:79:00        ....publickey.

**Comment by terrafrost** [comment]
So the way public key authentication in SSH works is that the SSH client first sends a SSH_MSG_USERAUTH_REQUEST packet that contains the public key "_to avoid unnecessary processing and user interaction_" and the public key algorithm. If the key isn't in the ~/.ssh/authorized_keys file (for OpenSSH at least) or the public key algorithm isn't supported the server responds with SSH_MSG_USERAUTH_FAILURE, which is exactly what's happening here.

Normally the public key and the public key algorithm are the same but for RSA there's a chance they won't be. The server says that it supports rsa-sha2-256 for server authentication and normally that's supposed to extend to public key auth as well but in this case (possibly due to some sshd_config setting I'm unfamiliar with) maybe it doesn't.

Anyway, try `$ssh->setPreferredAlgorithms(['hostkey' => ['ssh-rsa']]);`.

If that works for you I'll make it so that if public key authentication with rsa-sha2-256 fails it'll fall back to ssh-rsa.

Thanks!

**Comment by RAFFENNEvalentin** [comment]
your explaination is very clear. I've tried and it works. Thanks a lot.
Just on thing, you might precise somewhere that the ~/.ssh/authorized_keys correspond to the home directory you give to your user and not like the protocol ssh do i. e. at the home/usr/.ssh/authorized_keys.
For linux machine you can see the path in etc/passwd file.

Thank you very much
