### ISSUE TITLE
Question on how to verify certificate chain

### ISSUE THREAD

**Issue by YT-SUN97** [phpseclib/phpseclib#1816]
Hi, I am glad to use the library for development, and here is my question. 
I need a function to verify certificate chain, which is described in [RFC 5280 sec 6](https://datatracker.ietf.org/doc/html/rfc5280#section-6). The `Openssl` command-line tool has a similar function like this:
```sh
openssl verify -verbose -CAfile <path to ca cert> <path to entity cert>
```
The echo would be "ok" / error notes.

My question is, does `phpseclib` has a similar function to the above?
I found a function `$x509>getChain()` in `phpseclib`, which could return a chain from root to leaf of the current certificate. Does it have the logic to verify the certificate chain?  Or is this only to build **a (possible exist) chain** in a certificate store?

I am happy to have any kindly reply and discussion. Many thanks.

**Comment by YT-SUN97** [comment]
Here is an example code for understanding.

```php
// load cert
$x509 = new X509();
$ca = $x509->loadCA(file_get_contents($ca_cert_path));
$ee = $x509->loadX509(file_get_contents($entity_cert_path));

// chain
if (count($x509->getChain()) == 2) {
	echo "ok";
} else {
	echo "err";
}
```
(I am sure that the CA cert is trusted)
Does the above code block has the validating effect? Can I regard the chain as a verified cert chain that could be trusted?

**Comment by terrafrost** [comment]
`$x509->getChain()` only looks in the CA-loaded certs for certs to complete the chain.

So if there are no intermediate certs between your cert and the CA-loaded certs then `$x509->getChain()` will return the full chain. If there are intermediate certs you'd need to call `$x509->validateSignature()` first. `$x509->validateSignature()` will download the intermediate certs (assuming `X509::disableURLFetch()` hasn't been called) and will verify the signature of those intermediate certs. If the signature passes than those intermediate certs are, themselves, added to the list of CA certs. Then, by the time you do call `$x509->getChain()`, all the certs in that chain have already had their signature validated.

**Comment by YT-SUN97** [comment]
Thx very much for your reply.

So could I understand that the `$x509->getchain()` will verify a chain by validating (not limited to) subject-issuer name and signature if the cert chain's length is equal to 2?

**Comment by terrafrost** [comment]
Validation actually is, by default, limited to subject-issuer name and the signature. If you wanted to validate the date you'd have to loop through the array returned by `$x509->getChain()` and do `$x509->validateDate()` on each element within that array. If the CA cert is trusted and the chain length is 2 then doing `$x509->validateDate()` on the non-CA cert should be sufficient.

**Comment by YT-SUN97** [comment]
Thanks very much for your kindly reply! I think I know the answer, and it's a good time to close the issue.

Regards.
