### ISSUE TITLE
Validate certificate signature problem

### ISSUE THREAD

**Issue by vbalazs90** [phpseclib/phpseclib#1829]
Hi,

PHP version: 7.4
phpseclib version: 3.0

My example code:
`$x509 = new X509();`
`$x509->loadX509($certData);`
`//before validation I load all CA from OS's CA directory with $x509->loadCA() method.`
`$isValid = $x509->validateSignature();`

I have a valid cert with intermediate cert and the validateSignature method return with false. I discovered an error with in the **`X509::fetchURL()`** method. My intermediate cert URL like this: http://host.name/index.cgi?ca=trusta and the fetchURL method is cut query params off hte link. The problem is the parse_url method, andwhat You use it:
`fputs($fsock, "GET $parts[path] HTTP/1.0\r\n");` is not enough to handle all parts of given url string.

I think you should use a ClientInterface with default Client and setter method. This is working well, and sufficiently flexible.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/3d05201d40bc2b8d6153c317818dd8d174ba96c4 should fix this.

> I think you should use a ClientInterface with default Client and setter method. This is working well, and sufficiently flexible.

Feel free to put in a PR and it can be considered on its merits.

It'll need to target the master branch. BC breaking changes to the 1.0 / 2.0 / 3.0 branches will not be considered.
