### ISSUE TITLE
Connection closed prematurely

### ISSUE THREAD

**Issue by ikudosi** [phpseclib/phpseclib#1830]
PHP: 8.1
PHPSECLIB: 3.0.14

I am using league/flysystem-sftp-v3 within Laravel and under the hood it uses this library. In regards to application usage, I am heavily doing SFTP transfers via queued jobs. I thought upgrading to latest phpseclib would resolve this issue as it's been going on for quite sometime, but it seems like it's still happening on my end. Below is the trace stack. So far, the only thing that's been saving my butt has been to ensure the job retries enough to make the transfer go through, but I would prefer not to rely on the retry mechanism. Any else have the same issue?

`phpseclib3\Exception\ConnectionClosedException: Connection closed prematurely in /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:4170 Stack trace: #0 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3753): phpseclib3\Net\SSH2->send_binary_packet() #1 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #2 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #3 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #4 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #5 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #6 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #7 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #8 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3755): phpseclib3\Net\SSH2->get_binary_packet() #9 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3633): phpseclib3\Net\SSH2->filter() #10 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(3966): phpseclib3\Net\SSH2->get_binary_packet() #11 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(3356): phpseclib3\Net\SSH2->get_channel_packet() #12 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(1497): phpseclib3\Net\SFTP->get_sftp_packet() #13 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(1387): phpseclib3\Net\SFTP->stat_helper() #14 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2945): phpseclib3\Net\SFTP->stat() #15 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2900): phpseclib3\Net\SFTP->get_xstat_cache_prop() #16 /var/www/html/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2675): phpseclib3\Net\SFTP->get_stat_cache_prop() #17 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(128): phpseclib3\Net\SFTP->is_dir() #18 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(120): League\Flysystem\PhpseclibV3\SftpAdapter->makeDirectory() #19 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(97): League\Flysystem\PhpseclibV3\SftpAdapter->ensureParentDirectoryExists() #20 /var/www/html/vendor/league/flysystem-sftp-v3/SftpAdapter.php(144): League\Flysystem\PhpseclibV3\SftpAdapter->upload() #21 /var/www/html/vendor/league/flysystem/src/Filesystem.php(56): League\Flysystem\PhpseclibV3\SftpAdapter->write() #22 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php(357): League\Flysystem\Filesystem->write() #23 /var/www/html/app/Jobs/StoreContentToDisk.php(37): Illuminate\Filesystem\FilesystemAdapter->put() #24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\StoreContentToDisk->handle() #25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #27 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call() #29 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call() #30 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() #31 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #32 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then() #33 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\Bus\Dispatcher->dispatchNow() #34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bus/Dispatchable.php(57): Illuminate\Bus\Dispatcher->dispatchSync() #35 /var/www/html/app/LTB/OrderIntegration/OrderApiHandler.php(86): App\Jobs\StoreContentToDisk::dispatchSync() #36 /var/www/html/app/Services/Dropship/Dropship.php(443): App\LTB\OrderIntegration\OrderApiHandler->sendViaSFTP() #37 /var/www/html/app/Jobs/SendDropshipOrderToAx.php(71): App\Services\Dropship\Dropship->sendOrderToAx() #38 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): App\Jobs\SendDropshipOrderToAx->handle() #39 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #40 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #41 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #42 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call() #43 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call() #44 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}() #45 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #46 /var/www/html/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then() #47 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(123): Illuminate\Bus\Dispatcher->dispatchNow() #48 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}() #49 /var/www/html/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}() #50 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(125): Illuminate\Pipeline\Pipeline->then() #51 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(69): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware() #52 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call() #53 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(429): Illuminate\Queue\Jobs\Job->fire() #54 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(379): Illuminate\Queue\Worker->process() #55 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(173): Illuminate\Queue\Worker->runJob() #56 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(150): Illuminate\Queue\Worker->daemon() #57 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(134): Illuminate\Queue\Console\WorkCommand->runWorker() #58 /var/www/html/vendor/laravel/horizon/src/Console/WorkCommand.php(51): Illuminate\Queue\Console\WorkCommand->handle() #59 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle() #60 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}() #61 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure() #62 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod() #63 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(651): Illuminate\Container\BoundMethod::call()...`

**Comment by terrafrost** [comment]
What would help are the SSH2 and SFTP logs. You can get them by doing `define('NET_SSH2_LOGGING', 2);` and `define('NET_SFTP_LOGGING', 2);` at the top and `$disk->getDriver()->getAdapter()->getLogs()` and `$disk->getDriver()->getAdapter()->getSFTPLogs()` after the error.

The logs will cap out at 1mb, unless that default is changed. Hopefully that'd be enough for me to get some idea as to what's going on.

Thanks!

**Comment by ikudosi** [comment]
@terrafrost looking at the docs, I don't see a getLogs() - only a getLogs(); Can you confirm? Also, would a simple log suffice or need the complex?

**Comment by terrafrost** [comment]
Yah - it's `getLog()` and `getSFTPLog()` - sorry about that!

And yah - complex logs would be ideal.

Thanks!

**Comment by ikudosi** [comment]
So far the SFTP logs are blank, however below are some SSH2 logs that were captured during these types of events. Hopefully these help!

[ssh2_logs.txt](https://github.com/phpseclib/phpseclib/files/9389744/ssh2_logs.txt)

**Comment by terrafrost** [comment]
I apologize for not looking at this sooner - I've been trying to do other phpseclib dev work (in addition to my other day to day responsibilities).

Anyway, what version of phpseclib are you using? I tried it with 3.0.14. What security policy on the AWS side of things are you using? I used TransferSecurityPolicy-2020-06. I could probably [deduce it from your ciphersuite](https://docs.aws.amazon.com/transfer/latest/userguide/security-policies.html) but it'd just be easier if you told me lol.

That said, it looks like I was able to get farther than you, from the logs. Like here's what I got when I tried to connect:

```
-> NET_SFTP_INIT (0.0002s)
00000000  00:00:00:03                                      ....

<- NET_SFTP_VERSION (1.5403s)
00000000  00:00:00:03                                      ....

-> NET_SFTP_REALPATH (0.0002s)
00000000  00:00:00:01:2e                                   .....

<- NET_SFTP_NAME (0.0685s)
00000000  00:00:00:01:00:00:00:01:2f:00:00:00:00:00:00:00  ......../.......
00000010  00                                               .

-> NET_SFTP_OPENDIR (0.0002s)
00000000  00:00:00:01:2f                                   ..../

<- NET_SFTP_HANDLE (0.0613s)
00000000  00:00:00:01:30                                   ....0

-> NET_SFTP_READDIR (0.0001s)
00000000  00:00:00:01:30                                   ....0

<- NET_SFTP_STATUS (0.0745s)
00000000  00:00:00:03:00:00:00:1d:55:6e:61:62:6c:65:20:74  ........Unable t
00000010  6f:20:41:73:73:75:6d:65:52:6f:6c:65:20:66:6f:72  o AssumeRole for
00000020  20:75:73:65:72:00:00:00:08:55:53:2d:41:53:43:49   user....US-ASCI
00000030  49                                               I
```
Based on what you posted, you're not even getting to the point where you can begin the SFTP initialization. Like you're getting disconnected immediately after the authentication has successfully completed (ie. before any channels have been opened [SFTP operates on an SSH2 channel]).

Can you connect to the server with any other SFTP client? If not then I'd recommend following up with AWS tech support - not me. My own issue is an AWS issue that's reproducible with other SFTP clients, meaning it's not a phpseclib issue.

**Comment by ikudosi** [comment]
Thank you for your response! I will bring this up to our dev-ops since they are doing the authentication to the transfer family via lambda function. This issue doesn't occur every time - about one every hour or two which is the weird part. 

I'll go ahead and close this ticket. Best of luck!
