### ISSUE TITLE
`phpseclib3\Net\SSH2::keyboard_interactive_process()`: Argument #1 must be of type array, string given

### ISSUE THREAD

**Issue by simPod** [phpseclib/phpseclib#1836]
With v3.0.15 I'm getting new error:

> phpseclib3\Net\SSH2::keyboard_interactive_process(): Argument #1 must be of type array, string given, called in /home/www/flop/10708/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2396

<img width="2056" alt="image" src="https://user-images.githubusercontent.com/327717/188304679-5c8279c4-5d20-404b-80d0-65dfe420da3e.png">

**Comment by frankdejonge** [comment]
I encountered this as well, it was caught by the Flysystem test suite. I was able to reproduce this by supplying an invalid password:

```php
$sftp = new SFTP($validHost, $validPort, 10);
var_dump($sftp->login($validUser, $notValidPassword));
```

In 3.0.14 the result is `false`, in 3.0.15 the result is an uncaught type-error.

**Comment by LordSimal** [comment]
Can also confirm that this error appears for login data which are not correct.

**Comment by terrafrost** [comment]
I've fixed this with https://github.com/phpseclib/phpseclib/commit/59e34b1cd3d8c9ccf3b036c6f4464ffe0d3bf338 and made a new release (3.0.16).

Apologies!

I'll look into adding a unit test as time permits. I flew into London from Texas last night and will be flying out to Spain to do mountain climbing tomorrow.

**Comment by frankdejonge** [comment]
Thanks for the speedy resolving @terrafrost 👍👌
