### ISSUE TITLE
PHP 8.1 implicit conversion deprecation error

### ISSUE THREAD

**Issue by jeremy3681** [phpseclib/phpseclib#1840]
[From PHP 8.1, a deprecation notice is emitted when a float value is coerced to an int value ](https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string) 
This causes phpseclib to emit the following "Deprecated: Implicit conversion from float 4294967295 to int loses precision SFTP.php line 450"

This appears to be fixed in the dev-main branch, but 3.0 and 2.0 should be made compatible with php 8.1

**Comment by terrafrost** [comment]
I'll try to update this in the next few days as time permits. I'm vacationing in Spain atm (I'm from Texas).

That said, two things.

1. This should still be an issue in dev-master. See https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Net/SFTP/Attribute.php#L35

2. Efforts have been made to fix this issue in the latest 2.0 and 3.0 releases as noted in the changelog:

    https://github.com/phpseclib/phpseclib/releases/tag/2.0.38
    https://github.com/phpseclib/phpseclib/releases/tag/3.0.15

    (look at the last entry, specifically: "_fix deprecated implicit float to int on 32-bit PHP 8.1_")

    Here's the commit that that entry is referring to:

    https://github.com/phpseclib/phpseclib/commit/1168ba4d275a436253daeeb2b5e073bc8bafc4d5

    I did not test SFTP uploading / downloading on 32-bit PHP versions, however, hence the SFTP.php line 450 error. Ideally, this is something that would be tested with GitHub Actions with continuous integration but, in-so-far as I know, you can't tell GitHub Actions (or Travis CI for that matter) the number of bits the test system should have. You can tell it what PHP version, what OS, etc, but you can't tell it the number of bytes. Now, PHP 5.6 on GitHub Actions does seem to be the 32-bit version but I guess for whatever reason, I guess the SFTP test didn't run / doesn't run on that one.

**Comment by jeremy3681** [comment]
I put up a pull request for a fix to the issue. 
However I'm not sure of the process should I put up a PR for each branch? (1.0, 2.0, 3.0 and master)
