### ISSUE TITLE
delete of non-existent folder returns true when it used to return false

### ISSUE THREAD

**Issue by phil-davis** [phpseclib/phpseclib#1847]
This commit changed the behavior:
https://github.com/phpseclib/phpseclib/commit/1dfd1b9cd4cc0f8566ee12a18f8abb9657eebb18

That was "a good thing" for issue #1791 when the folder exists but there is difficulty getting the folder contents.

I noticed the behavior change in unit tests: https://github.com/owncloud/core/pull/40323#issuecomment-1254719428

The test does:
```
	public function testDirectories($directory) {
		$this->assertFalse($this->instance->file_exists('/' . $directory));

		$this->assertTrue($this->instance->mkdir('/' . $directory));

		$this->assertTrue($this->instance->file_exists('/' . $directory));
		$this->assertTrue($this->instance->is_dir('/' . $directory));
		$this->assertFalse($this->instance->is_file('/' . $directory));
		$this->assertEquals('dir', $this->instance->filetype('/' . $directory));
		$this->assertEquals(0, $this->instance->filesize('/' . $directory));
		$this->assertTrue($this->instance->isReadable('/' . $directory));
		$this->assertTrue($this->instance->isUpdatable('/' . $directory));

		$dh = $this->instance->opendir('/');
		$content = [];
		while ($file = \readdir($dh)) {
			if ($file != '.' and $file != '..') {
				$content[] = $file;
			}
		}
		$this->assertEquals([$directory], $content);

		$this->assertFalse($this->instance->mkdir('/' . $directory)); //can't create existing folders
		$this->assertTrue($this->instance->rmdir('/' . $directory));

		$this->wait();
		$this->assertFalse($this->instance->file_exists('/' . $directory));

		$this->assertFalse($this->instance->rmdir('/' . $directory)); //can't remove non existing folders

		$dh = $this->instance->opendir('/');
		$content = [];
		while ($file = \readdir($dh)) {
			if ($file != '.' and $file != '..') {
				$content[] = $file;
			}
		}
		$this->assertEquals([], $content);
	}
```

and the existing test fails at:
```
		$this->assertFalse($this->instance->rmdir('/' . $directory)); //can't remove non existing folders
```

The `rmdir` in that class does:
```
			$result = $this->getConnection()->delete($this->absPath($path), true);
```
and returns the result.

With the fix in phpseclib 3.0.15 I now get back `true` for an attempt to delete a folder that does not even exist.

I suppose this is not so bad - after the call, the folder is gone (because it never even existed), and so the call was a success (the caller presumably hopes that the folder is gone if the call returns `true`, and that is indeed the case.

What to do? Accept that this new/different behavior is actually quite reasonable, and get on with life? Or adjust `_delete_recursive` so that it will understand the case when the folder path does not exist at all?

**Comment by terrafrost** [comment]
I squashed all the commits for #1848 into a single commit and then cherry-picked that to the 1.0 branch and merged that into 2.0 / 3.0 / master.

Here's the commit:

https://github.com/phpseclib/phpseclib/commit/24845ccbcc3039a292bfd1ad3d52dd5d8dc6b304

Thanks!
