### ISSUE TITLE
Release phpseclib 3.0.17

### ISSUE THREAD

**Issue by phil-davis** [phpseclib/phpseclib#1854]
Among other things, https://github.com/phpseclib/phpseclib/commit/24845ccbcc3039a292bfd1ad3d52dd5d8dc6b304 corrects a behavior change in 3.0.15/16

I did various forking and composer stuff to test this in owncloud core CI https://github.com/owncloud/core/pull/40432 and the tests there all pass again now. So the behavior is back to the way it was in 3.0.14 - good.

What is the schedule for releasing 3.0.17 ?

**Comment by terrafrost** [comment]
Apologies for the delay. 3.0.17 has been released:

https://github.com/phpseclib/phpseclib/releases/tag/3.0.17

Thanks!
