### ISSUE TITLE
Strings::packSSH2 , 'InvalidArgumentException' with message 'An integer was expected.'

### ISSUE THREAD

**Issue by WesSylvain** [phpseclib/phpseclib#1859]
Hi,

I encounter a problem when obtaining the listDir('.')
We have an error but we don't understand. 
Do you have an idea ?

Thank you

**Error :** 
exception 'InvalidArgumentException' with message 'An integer was expected.' in  vendor/phpseclib/phpseclib/phpseclib/Common/Functions/Strings.php:173
Stack trace:
#0  vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php(4128): phpseclib3\Common\Functions\Strings::packSSH2('CNs', 94, NULL, '')
#1  vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2889): phpseclib3\Net\SSH2->send_channel_packet(256, '\x00\x00\x00\x06\x10\x00\x00\x00\x01.')
#2  vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(682): phpseclib3\Net\SFTP->send_sftp_packet(16, '\x00\x00\x00\x01.')
#3  vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2670): phpseclib3\Net\SFTP->realpath('.')
#4  vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2638): phpseclib3\Net\SFTP->get_xstat_cache_prop('.', 'type', 'stat')
#5  vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php(2416): phpseclib3\Net\SFTP->get_stat_cache_prop('.', 'type')
#6 class.SFTPOasis.php(731): phpseclib3\Net\SFTP->is_dir('.')

**Comment by terrafrost** [comment]
```
exception 'InvalidArgumentException' with message 'An integer was expected.' in vendor/phpseclib/phpseclib/phpseclib/Common/Functions/Strings.php:173
```
Strings.php::173 threw that exception from phpseclib 3.0.0 to 3.0.10. The latest version of phpseclib 3.0 is 3.0.17. I'd try upgrading first and, if you still have the issue, then post back here, and we'll proceed from there.

Thanks!
