### ISSUE TITLE
How to mimic the MySQL AES_ENCRYPT() function with the phpseclib library version 3

### ISSUE THREAD

**Issue by julian-sawicki-skrepr** [phpseclib/phpseclib#1861]
In old versions for example `1.0.16` you could do this to mimic the MySQL `AES_ENCRYPT()` function: 

```
function aes_encrypt($val, $ky) {
    $aes = new Crypt_AES();
    $aes->setKey($ky);
    return $aes->encrypt($val);
}    
```
    
In new versions like `3.0.14` you can't do it anymore, because version 3 is way more picky. In older versions of phpseclib any key length was allowed. In version 3 the key length must have a specific length.  Thus the question is: 

How to mimic the MySQL AES_ENCRYPT() function with the phpseclib library version 3?

Interesting links: 

https://www.php.net/manual/en/ref.mcrypt.php#62850

https://dev.mysql.com/doc/refman/8.0/en/encryption-functions.html#function_aes-encrypt

**Comment by terrafrost** [comment]
> In new versions like `3.0.14` you can't do it anymore, because version 3 is way more picky. In older versions of phpseclib any key length was allowed. In version 3 the key length must have a specific length.

You can always null pad the key yourself. eg.

```php
str_pad(substr($key, 0, 16), 16, "\0");
```
That's what https://github.com/phpseclib/phpseclib2_compat does

**Comment by julian-sawicki-skrepr** [comment]
This is not enough to make it work. I tried it like this: 

```
$ky = str_pad($ky, 32, "\x00");
```

When you invoke `$aes->encrypt($val)` the phpseclib library internally calls `openssl_encrypt()`. Like this: 

```
case self::MODE_ECB:
                    return openssl_encrypt($plaintext, $this->cipher_name_openssl, $this->key, OPENSSL_RAW_DATA | OPENSSL_ZERO_PADDING);
```

The problem I face is the value of the property `cipher_name_openssl`. 
In the old version the value will be `aes-128-cbc`.
In the new version the value will be `aes-256-ecb`.

**Comment by julian-sawicki-skrepr** [comment]
I fixed it by creating a wrapper for the `AES` class. Please see below: 

```
namespace App\Security;

use phpseclib3\Crypt\AES;
use phpseclib3\Crypt\Common\SymmetricKey;

class CustomAES extends AES
{
    public function setKey($key)
    {
        if ($key === '') {
            throw new \LengthException('Key of size ' . strlen($key) . ' not supported by this algorithm.');
        }

        $key = str_pad($key, 16, "\x00");
        SymmetricKey::setKey($key);
    }
} 
```
