### ISSUE TITLE
In V2, infinite loop in SCP::get() when receive() returns package with length = 0

### ISSUE THREAD

**Issue by ppaulis** [phpseclib/phpseclib#1862]
Hi!

I'm downloading on a series of Servers files using the SCP class of the v2 of phpseclib. That works great on all but one machine. My guess is that the machine has an unidentified problem somewhere.

However, the reason for me writing this issue is, that the `while ($size < $info['size']) {` here:
https://github.com/phpseclib/phpseclib/blob/2.0/phpseclib/Net/SCP.php#L248
becomes an infinite loop when the receive on Line 249 returns permanently `false` (and that's currently happening here).

Shouldn't this loop be terminanted as soon as `_receive()` returns a first `false`?
If that should be the case, I can try to provide a PR fixing this behaviour.

**From SCP.php (line 248):**
```
while ($size < $info['size']) {      <============================== size in my test case is 4007
    $data = $this->_receive();     <============================== returns always false
    // SCP usually seems to split stuff out into 16k chunks
    $size+= strlen($data);           <============================== $size remains always lower than 4007 => infinite loop

    if ($local_file === false) {
        $content.= $data;
    } else {
        fputs($fp, $data);
    }
}
```

The consequence of this could be a gigantic error log in just a few minutes, because it's spamming Notices at an incredibly fast rate.

Thanks and best regards,
Pascal

**Comment by ppaulis** [comment]
Created a PR to show a potential fix:
https://github.com/phpseclib/phpseclib/pull/1863

**Comment by terrafrost** [comment]
I commented on your PR. I'm in Disneyland Paris atm for https://live.symfony.com/2022-paris-con/schedule so I'm a bit distracted.

**Comment by ppaulis** [comment]
PR updated. Thanks for the update and hf at the Symfony con :-)
