### ISSUE TITLE
SSH agent support under Windows

### ISSUE THREAD

**Issue by cfehse** [phpseclib/phpseclib#1866]
Hi,

currently the class `phpseclib3\System\SSH\Agent` only supports the communication with the SSH agent via UNIX Domain Sockets.  Under Windows this mechanism is not supported and SSH agent implementations like putty (pageant) or OpenSSH for Windows use named pipes to communicate with SSH clients.  

Perhaps the constructor of the class could be extended to open the communication resource using a `fopen()` class in case the `unix` stream transport is not supported. This would allow to open an address like  `\\.\pipe\<pipename>` under Windows to communicate with the SSH agent.

Something like this:

       ` if (in_array( 'unix', stream_get_transports(), true )) {
            $this->fsock = fsockopen( 'unix://' . $address, 0, $errno, $errstr );
            if (!$this->fsock) {
                throw new RuntimeException( "Unable to connect to ssh-agent ($errno: $errstr)" );
            }
        } else {
            $this->fsock = fopen( $address, 'r+b' );
            if (!$this->fsock) {
                throw new RuntimeException( "Unable to connect to ssh-agent ($address)" );
            }
        } `

Thank you.

**Comment by terrafrost** [comment]
The code changes you proposed look good but I'd like to be able to test this and mention it in the documentation.

Pursuant to that...  can you tell me how to get the pipe name?

Thanks!

**Comment by terrafrost** [comment]
I figured out how to get pipe name with pageant. You lunch pageant from the CLI by doing `./openssl --openssh-config pageant.conf`.

In-so-far as your code is concerned...  `in_array( 'unix', stream_get_transports(), true )`...  phpseclib does `in_array` several times through out its codebase and in none of those calls is the third parameter set so, for consistency, I think it ought to be removed from the final code that makes it into the codebase as well. If we want to add the third parameter to _all_ `in_array` function calls then that can be done as a separate PR.

Some validation should prob be done on the file name as well. Like obviously `C:\path\to\my.ini`, if it even existed at all, isn't a named pipe, so doing some sort of regex check to make sure the `$address` that the constructor is passed is valid is prob prudent.

In the Agent.php constructor there's this:

```
        if (!$address) {
            switch (true) {
                case isset($_SERVER['SSH_AUTH_SOCK']):
                    $address = $_SERVER['SSH_AUTH_SOCK'];
                    break;
                case isset($_ENV['SSH_AUTH_SOCK']):
                    $address = $_ENV['SSH_AUTH_SOCK'];
                    break;
                default:
                    user_error('SSH_AUTH_SOCK not found');
                    return false;
            }
        }
```
If the named pipe name doesn't exist in Windows as an environmental variable then this prob ought to be behind the if statement as well.

Also, when I created a named pipe I notice that it always had the same UUID. It kinda makes me wonder if, to make things easier with phpseclib, there wasn't some registry value we could check or some such that we could set as the default pipe name if none was provided.

Thanks!

**Comment by terrafrost** [comment]
In-so-far as validation goes, https://git.tartarus.org/?p=simon/putty.git;a=blob_plain;f=windows/named-pipe-client.c;hb=HEAD does this:

```
assert(strncmp(pipename, "\\\\.\\pipe\\", 9) == 0);
assert(strchr(pipename + 9, '\\') == NULL);
```
So adding some similar validation to that would prob be prudent.

As for the UUID-like string...  it doesn't match the sids that `wmic useraccount get name,sid` returns. https://git.tartarus.org/?p=simon/putty.git;a=blob_plain;f=windows/utils/agent_named_pipe_name.c;hb=HEAD seems to define it's structure. So it's the username and then `capi_obfuscate_string("Pageant")`.  `capi_obfuscate_string()` is defined in https://git.tartarus.org/?p=simon/putty.git;a=blob_plain;f=windows/utils/cryptoapi.c;hb=HEAD . It's not completely clear to me what that function does, atm. I had thought maybe it'd produce the same output on diff systems as `sha1('Pageant')` does but alas that does not appear to be the case.

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/218c7e5207725676e0202a11ce928820c0a237ad should do this now.

Thanks

**Comment by cfehse** [comment]
This works perfectly for putty (pageant) and the agent support in "OpenSSH for Windows" which uses a named pipe as well.

Thank you very much!

**Comment by terrafrost** [comment]
Great to hear!
