### ISSUE TITLE
It take too long time to get list of files using nlist.

### ISSUE THREAD

**Issue by Happyandhappy** [phpseclib/phpseclib#1867]
Here is the code snippet.

       $sftp = new SFTP(SFTP_HOST, SFTP_PORT);
        $sftp->login(SFTP_USER, SFTP_PASS);
        $files = $sftp->nlist();
        foreach($files as $file) {
            echo $file . "<br>";
        }

I took a little long time and I couldn't determine it completed or not.
I checked the ftp folder and there were 130000 files, maybe it's impossible to get the list of files at once.
Please let me know if there is an option for pagination in nlist or rawlist functions. Or any method to avoid too long time.
Or please let me know if there is limitation in nlist and rawlist functions.

Thank  you.
Regards.

**Comment by terrafrost** [comment]
Ideally the way phpseclib would work is that it'd support multiple channels. You do an nlist and it does it on it's own dedicated channel and then returns a lazy object that implements ArrayAccess and Iterable and what not. That said, that's more of a phpseclib 4.0 thing and isn't a solution that's liable to see the light of day in an official release in years.

The pagination is an interesting idea. I'll look into it as time permits. I've been on vacay and just got back last night and have a big backlog of other stuff to look at now meh :| So I'll look into this as soon as I can but idk when that'll be. Hopefully within a week

**Comment by terrafrost** [comment]
So upon further consideration, pagination won't work.

The SFTP protocol doesn't let you choose an offset in directories whereas it does in files. So if you wanted to do something like `LIMIT 100000, 100` you'd still have to pull in the first 100,000 entries to get the 100 you're interested in.

Sure, I suppose that'd be faster than returning a big giant array but it's still pretty suboptimal in the grand scheme of things.

More specifically, in the SFTPv3 specs, you have [SSH_FXP_READ](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.4), which has handle (which SSH_FXP_OPEN returned), offset and len as parameters. The comparable command for directories, [SSH_FXP_READDIR](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#page-16), does not have that - it has handle (which SSH_FXP_OPENDIR returned) and that's it. Not even SFTPv6 has [changed this behavior](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-13#section-8.2.2).

**Comment by Happyandhappy** [comment]
Thank you so much!
