### ISSUE TITLE
Use of undefined constant NET_SSH2_MSG_DISCONNECT

### ISSUE THREAD

**Issue by adrienHoareau** [phpseclib/phpseclib#1901]
Hi, I am getting this error `Use of undefined constant NET_SSH2_MSG_DISCONNECT` (using v3)
in my stack trace the error is thrown here : 
`/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php in phpseclib3\Net\SSH2::disconnect_helper at line 4155`
do you know what should be the value of NET_SSH2_MSG_DISCONNECT (and also NET_SSH2_DISCONNECT_BY_APPLICATION) so that I can define it in my project ?

**Comment by adrienHoareau** [comment]
Thank you for your quick reply.
I will have a deeper look at the project I am working on so that I can give you a code that reproduces the problem.

**Comment by adrienHoareau** [comment]
I found what was the problem.
One object was holding a reference to phpseclib SFTP class.
This object was serialized then unserialized.
Unserializing an object don't call its constructor but when the object is not used anymore the garbage collector calls the __destruct methods.
phpseclib SFTP class inherits from SSH2 and SSH2 does have a __destruct method which calls SSH2::disconnect()

So my solution was to remove the reference to the SFTP class before serializing my object.

**Comment by terrafrost** [comment]
Interesting.

Thanks for the update!
