### ISSUE TITLE
Fortify on Demand Recommendation - Weak Encryption: Inadequate RSA Padding

### ISSUE THREAD

**Issue by George-Ashworth** [phpseclib/phpseclib#1918]
### **Summary**
The method powmodhelper() in OpenSSL.php performs public key RSA encryption without OAEP padding, which makes the encryption weak.Public key RSA encryption is performed without using OAEP padding, which makes the encryption weak.

### **Explanation**
In practice, encryption with an RSA public key is usually combined with a padding scheme. A padding scheme can prevent attacks on RSA that only work when the encryption is performed without padding.

**Example 1**: The following code performs encryption using an RSA public key without using a padding scheme:
```
function encrypt($input, $key) {
$output='';
openssl_public_encrypt($input, $output, $key, OPENSSL_NO_PADDING);
return $output;
}
```

### **Recommendation**
To use RSA securely, you must use OAEP (Optimal Asymmetric Encryption Padding) when performing encryption.

**Example 2**: The following code performs encryption with an RSA public key using OAEP padding:
```
function encrypt($input, $key){
$output='';
openssl_public_encrypt($input, $output, $key, OPENSSL_PKCS1_OAEP_PADDING);
return $output;
}
```

### **References**
Wikipedia, http://en.wikipedia.org/wiki/RSA
OPENSSL Documentation, http://www.openssl.org/docs/crypto/RSA_public_encrypt.html
PKCS #1 v2.1: RSA Cryptography Standard
CWE ID 780, Standards Mapping - Common Weakness Enumeration
CCI-002450, Standards Mapping - DISA Control Correlation Identifier Version 2
MP, Standards Mapping - FIPS200
Insufficient Data Protection, Standards Mapping - General Data Protection Regulation
SC-13 Cryptographic Protection (P1), Standards Mapping - NIST Special Publication 800-53 Revision 4
SC-13 Cryptographic Protection, Standards Mapping - NIST Special Publication 800-53 Revision 5
2.6.3 Look-up Secret Verifier Requirements (L2 L3), 2.9.3 Cryptographic Software and Devices Verifier Requirements (L2 L3), 6.2.1 Algorithms (L1 L2 L3), 6.2.2 Algorithms (L2 L3), 8.3.7 Sensitive Private Data (L2 L3), 9.1.2 Communications Security Requirements (L1 L2 L3), 9.1.3 Communications Security Requirements (L1 L2 L3), Standards Mapping - OWASP Application Security Verification Standard 4.0
M6 Broken Cryptography, Standards Mapping - OWASP Mobile Top 10 Risks 2014
A8 Insecure Storage, Standards Mapping - OWASP Top 10 2004
A8 Insecure Cryptographic Storage, Standards Mapping - OWASP Top 10 2007
A7 Insecure Cryptographic Storage, Standards Mapping - OWASP Top 10 2010
A6 Sensitive Data Exposure, Standards Mapping - OWASP Top 10 2013
A3 Sensitive Data Exposure, Standards Mapping - OWASP Top 10 2017
A02 Cryptographic Failures, Standards Mapping - OWASP Top 10 2021
Requirement 6.5.8, Standards Mapping - Payment Card Industry Data Security Standard Version 1.1
Requirement 6.3.1.3, Requirement 6.5.8, Standards Mapping - Payment Card Industry Data Security Standard Version 1.2
Requirement 6.5.3, Standards Mapping - Payment Card Industry Data Security Standard Version 2.0
Requirement 6.5.3, Standards Mapping - Payment Card Industry Data Security Standard Version 3.0
Requirement 6.5.3, Standards Mapping - Payment Card Industry Data Security Standard Version 3.1
Requirement 6.5.3, Standards Mapping - Payment Card Industry Data Security Standard Version 3.2
Requirement 6.5.3, Standards Mapping - Payment Card Industry Data Security Standard Version 3.2.1
Control Objective 7.1 - Use of Cryptography, Control Objective 7.4 - Use of Cryptography, Standards Mapping - Payment Card Industry Software Security Framework 1.0
Control Objective 7.1 - Use of Cryptography, Control Objective 7.4 - Use of Cryptography, Control Objective B.2.3 - Terminal Software Design, Standards Mapping - Payment Card Industry Software Security Framework 1.1
APP3150.1 CAT II, Standards Mapping - Security Technical Implementation Guide Version 3.1
APP3150.1 CAT II, Standards Mapping - Security Technical Implementation Guide Version 3.10
APP3150.1 CAT II, Standards Mapping - Security Technical Implementation Guide Version 3.4
APP3150.1 CAT II, Standards Mapping - Security Technical Implementation Guide Version 3.5
APP3150.1 CAT II, Standards Mapping - Security Technical Implementation Guide Version 3.6
APP3150.1 CAT II, Standards Mapping - Security Technical Implementation Guide Version 3.7
APP3150.1 CAT II, Standards Mapping - Security Technical Implementation Guide Version 3.9
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.1
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.10
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.11
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.2
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.3
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.4
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.5
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.6
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.7
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.8
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 4.9
APSC-DV-002010 CAT II, APSC-DV-002040 CAT II, Standards Mapping - Security Technical Implementation Guide Version 5.1

**Comment by terrafrost** [comment]
powmodhelper() is used in the BCMath and PHP32/64 BigInteger engines for the powMod() and modPow() methods. Unpadded RSA and modular exponentiation are the same thing so if you make powmodhelper() employ OAEP padding then you break powMod() and modPow() in BigInteger.

Sure, I suppose the `openssl_public_encrypt` function call could be removed, all together, to avoid confusion, but then you'd be depriving yourself of the speed boosts that OpenSSL provides.

Like modular exponentiation is a fairly slow operation to begin with. Doing it via unpadded RSA with OpenSSL makes it a lot faster for any engine other than the GMP engine.

Furthermore, RSA encryption isn't the only reason you'd want to use modular exponentiation: it's used for primality testing. It's used in PrimeField.php (which in turn is used by elliptic curves) for it's pow() operation.

If we stop using unpadded RSA then all engines, save for the GMP engine, will be made significantly slower.

If you want to use RSA with phpseclib you should do so via RSA.php - not BigInteger.php. If you are using BigInteger.php's powMod() to do RSA encryption then that's on you.

Like what's next? Are you going to submit a bug report because `gmp_powm` doesn't do OAEP RSA?
