### ISSUE TITLE
SFTP: put() - how should RESUME and RESUME_START works?

### ISSUE THREAD

**Issue by forrest79** [phpseclib/phpseclib#1921]
Hi,
first, thanks for a super useful library :-) We're using SFTP functionality and I have a question about how putting a file with `RESUME` mode (or `RESUME_START`) should work. I read a doc for the `put()` method and I thought, that mode `SOURCE_LOCAL_FILE | RESUME` would resume my upload when the previous upload failed. For example. I'm uploading a 300MB video file, and the transfer is interrupted after 100MB, so I will use `RESUME` mode with the same local file and the remaining 200MB will be appended to the remote file.

But in reality, the whole 300MB of the local file is appended to the 100MB remote file (so on the remote, there is the 400MB file). This is the situation I'm expecting for the `SOURCE_LOCAL_FILE | RESUME_START` mode. Also the constant `RESUME_START` is not used in the whole file which is a little bit strange for me :-)

I was looking for the historical commits and this is the one [cf101b5d8c834d8e385e14245b108188a6b1833b](https://github.com/phpseclib/phpseclib/commit/6688f650f1aa53e7fb946932a19ead8037ade958) removing code I'm expecting here for the functionality I was trying describe.

Am I missing something or there is really a bug in the `RESUME` operations? I'm able to simulate the `RESUME` operation manually like this:

```php
if ($resume) {
    $offset = $sftp->stat($toPath)['size'] ?? FALSE;
    if ($offset === FALSE) {
        throw new \Exception('Unable to resume upload');
    }
} else {
    $offset = -1;
}

$sftp->put($toPath, $fromPath, Net\SFTP::SOURCE_LOCAL_FILE, $offset, $offset);
```

We can live with this.

**Comment by terrafrost** [comment]
RESUME would set `$start` to the length of the uploaded file but it didn't set `$local_start`. So RESUME works great if you're uploading a string (well, sorta; even now it doesn't skip the first `$start` bytes if you're uploading a string, but then again, neither does `$local_start` work on strings, either).

Anyway, I've changed this behavior:

https://github.com/phpseclib/phpseclib/commit/df3dab7d3f3a53fe6fa9f0c0b23effdda8f2f9c3

Well, I didn't change how it works for strings but I changed how it works for local files.

**Comment by terrafrost** [comment]
RESUME_START should be working better now, as well, with this commit:

https://github.com/phpseclib/phpseclib/commit/de09e8e8176e4a18ae7fc8711b0f1b85dfeb93e4

Thanks!

**Comment by terrafrost** [comment]
I believe the underlying issues have been addressed so imma close this!

**Comment by forrest79** [comment]
Hi, sorry for the delay, and thanks for the changes, everything works great!
