### ISSUE TITLE
Unexpected behavior from SSH2::ping

### ISSUE THREAD

**Issue by kevinreniers** [phpseclib/phpseclib#1923]
Hello, we're running into an issue that we think originates from a bug in phpseclib. Please see my [consistent reproducer project](https://github.com/kevinreniers/phpseclib-iss1923).

- We've tested against proftpd versions 1.3.6e and 1.3.7f.
- We've tested against phpseclib versions 3.0.19 and 3.0.20.
- We use [flysystem-sftp-v3](https://github.com/thephpleague/flysystem-sftp-v3) as an abstraction.

## Context

We have long-running processes spread across different servers. Each of these will consume work instructions from a RabbitMQ queue, process them, generate some data and push the results to a remote SFTP server. Work may be created on-demand, and is also created in batch-processing on set intervals.

In the reproducer project, configuration settings have been configured lower than reality to more easily trigger the issue. In reality, the client-side timeout value is set to 30s and the server-side TimeoutIdle is set to 360s.

## Expected Behavior

- I expected `SSH2::isConnected` to give the real connection status. This is also [what flysystem-sftp-v3 tries to rely upon](https://github.com/thephpleague/flysystem-sftp-v3/blob/3.x/SimpleConnectivityChecker.php) by default via its [SftpConnectionProvider](https://github.com/thephpleague/flysystem-sftp-v3/blob/3.x/SftpConnectionProvider.php#L59).
- Because it doesn't work as we expect, I've patched League's `SimpleConnectivityChecker` to ping the connection first. I expected `SSH2::ping` to reconnect transparently.

## Actual Behavior

In the reproducer project, there are two consuming services `app` and `patched-app`. The former is the default behavior of league/flysystem-sftp-v3. The latter is our patched version. League will [setup a new connection](https://github.com/thephpleague/flysystem-sftp-v3/blob/3.x/SftpConnectionProvider.php#L55-L57) when there isn't one already.

Our code will consume X number of messages from the queue and swallow errors. As such, every time the issue occurs at least one message fails completely.

- In the `app` service, writing to the socket that has entered CLOSE_WAIT on the client-side and has already entered FIN_WAIT2 or been discarded on the server side throws "Connection closed prematurely". This happens because League tries to reuse the already created connection because SSH2::isConnected returns true at this point.
- In the `patched-app` service, writing to the socket using the same setup as `app`, trying to consume one or more messages causes these errors:

```
phpseclib-proftpd-patched-app-1  | string(127) "Unable to write file at location: 56efebebebb1284f1ca6f8904c5a6da07f2eda48dd45709f25276e5b9c1ca6b2. Connection closed by server"
phpseclib-proftpd-patched-app-1  | string(128) "Unable to write file at location: 997ff6d9d68469792f4dea1235a0bc578ba6123527b1186794c236d00aa131d8. No data received from server"
phpseclib-proftpd-patched-app-1  | string(128) "Unable to write file at location: bd79d78cce4e6628da32a1d8a1a7e31ef1673dea2754b946f475c176be48a0bf. No data received from server"
phpseclib-proftpd-patched-app-1  | string(128) "Unable to write file at location: 2ddb8aca942d32dc8527a06599bf800c4262e7b4c459ad7c446c360a9cc294d3. No data received from server"
phpseclib-proftpd-patched-app-1  | string(128) "Unable to write file at location: baa25ff3bc42b5846ce035ccd7bbed09a269fd24dfd505d0436ba11ffef92c41. No data received from server"
```

At the TCP level you can see phpseclib creating new connections, and you can also see the connections being created at the proftpd side, however it seems that they cannot be used at all to transfer data over them.

![image](https://github.com/phpseclib/phpseclib/assets/22906111/32ee6573-5ebb-4277-affb-962119d2182a)
(after the first message is consumed, successfully)

![image](https://github.com/phpseclib/phpseclib/assets/22906111/6cfc476c-351d-4dc0-8774-02d261ae8ff2)
(server closes connection, enters FIN_WAIT, client-side enters CLOSE_WAIT)

![image](https://github.com/phpseclib/phpseclib/assets/22906111/5f82b687-c87d-46a8-bfad-15e703c4c779)
(trying to consume multiple new messages after that)

**Comment by terrafrost** [comment]
If you (or rather, flysystem) just want to see what the status of the socket connection is then one would prob be better off doing something like this:

```php
$fsock = fsockopen('domain.tld', 22);
$sftp = new SFTP($fsock);
print_r(stream_get_meta_data($fsock));
```
`SSH2::isConnected` is more analogous "can packets still be sent?". Like if `SSH2::get_binary_packet` didn't return as many bytes as are needed to decrypt some encrypted data then `SSH2::isConnected` would return false even though _technically_ the TCP/IP connection may still be open.

As for `SSH2::ping`...  it's not completely clear how you're thinking tit should work. The way it works now (or at least should) is that  it tries to open up a channel and then closes it up right after. But wait, you need to be authenticated to open a channel so if you're not authenticated and the credentials you logged in with haven't been saved it'll return false. BUT if you are authenticated and your credentials are cached it should try to connect again and then return a true or false based on the success of the login attempt. The only time you should ever be in this situation where you're not authenticated but the credentials are cached is if you've already been logged one once before but then got disconnected for whatever reason.

**Comment by kevinreniers** [comment]
Hi, thanks for the response.

>SSH2::isConnected is more analogous "can packets still be sent?". Like if SSH2::get_binary_packet didn't return as many bytes as are needed to decrypt some encrypted data then SSH2::isConnected would return false even though technically the TCP/IP connection may still be open.

Sure, that's fair enough. That's not very intuitive behavior though, so it might be worth changing or renaming on your end for a future (major) release.

>As for SSH2::ping... it's not completely clear how you're thinking tit should work. The way it works now (or at least should) is that it tries to open up a channel and then closes it up right after. [...]

I expected that `ping` would transparently reconnect to the server. Briefly [looking at the code](https://github.com/phpseclib/phpseclib/blob/3.0/phpseclib/Net/SSH2.php#L3349-L3373) seems to suggest that it does at least.

My interpretation was that if any errors is thrown from `SSH2::openChannel`, including unable to because the underlying TCP/IP connection is dead, a full reconnect is triggered.

>not authenticated and the credentials you logged in with haven't been saved it'll return false

All our connections are authenticated. I couldn't find any code in `SSH2` that would clear the `auth` property after a login, so the credentials should always be available in-memory, right?

**Comment by kevinreniers** [comment]
I think I can quite easily patch this on my end by changing the ConnectivityChecker to this:

```diff
--- /dev/null
+++ ../SimpleConnectivityChecker.php
@@ -10,6 +10,6 @@
 {
     public function isConnected(SFTP $connection): bool
     {
-        return $connection->isConnected();
+        return $connection->isConnected() && is_resource($connection->fsock) && !feof($connection->fsock);
     }
 }
```

This seems to have consistently resolved the issue on my end.

**Comment by terrafrost** [comment]
Closing since the PR to address this has been merged.
