### ISSUE TITLE
PHPStan issue for login with RSA key

### ISSUE THREAD

**Issue by LordSimal** [phpseclib/phpseclib#1924]
* phpseclib version 3.0.20
* phpstan 1.10.22
* PHP 8.2.7

The following code
```
$ssh = new \phpseclib3\Net\SSH2('somehost.com');
$key = \phpseclib3\Crypt\RSA::load(file_get_contents('/path/to/id_rsa'));
if (!$ssh->login('root', $key)) {
    return 'Login failed';
}
```

causes the following stan issue on level 6

```
 Parameter #2 ...$args of method phpseclib3\Net\SSH2::login() expects array<array>|phpseclib3\Crypt\Common\PrivateKey|phpseclib3\System\SSH\Agent|string|null,  
         phpseclib3\Crypt\Common\AsymmetricKey given.    
```

**Comment by terrafrost** [comment]
Does https://github.com/terrafrost/phpseclib/commit/fc4d9dd4804cd77d4d341d649951482cb176ee4f fix the issue for you?

I'd test it out myself but I'm about to head out.

Technically phpseclib3\Crypt\Common\PrivateKey is an instance of phpseclib3\Crypt\Common\AsymmetricKey. When you load an RSA private key you get an instance of phpseclib3\Crypt\RSA back that implements phpseclib3\Crypt\Common\PrivateKey. phpseclib3\Crypt\RSA, in turn, extends phpseclib3\Crypt\Common\AsymmetricKey

**Comment by LordSimal** [comment]
sorry for my late response.
indeed this change does fix my problem!

**Comment by terrafrost** [comment]
This has been merged:

https://github.com/phpseclib/phpseclib/commit/fc4d9dd4804cd77d4d341d649951482cb176ee4f

Thanks!
