### ISSUE TITLE
phpseclib synology composer

### ISSUE THREAD

**Issue by devildant** [phpseclib/phpseclib#1925]
Hello, I host my project on a nas synology, and I use an old version 3 which does not use compose, I would like to update it, but installing composer on a synology is a hassle, with each update it will be necessary to reinstall everything, and I would like to avoid installing on the nas because I had problems in the past.
I saw on this link a possible solution: https://phpseclib.com/docs/install

so can I do the procedure on another machine and just import the vender file on my syno without needing to compose?

best regards

**Comment by terrafrost** [comment]
Yup - what you described should work!

**Comment by devildant** [comment]
thx for help other people with synology with docker :
A) build and install
1) create directory on web shared directory (exemple: create test directory)
2) inside this directory create file with name composer.json
3) add this inside this file
```
{
	"config": {
		"platform": {
			"php": "7.4.33",
			"ext-something": "1"
		}
	},
    "require": {
        "phpseclib/phpseclib": "~3.0"
    }
}
```
4) open putty and connect you to your nas with admin, and root for have right to run docker command
5) goto your directory (created in step 1)  (exemple: cd /volume1/web/test)
6) run command bellow for build with composer
```
docker run --rm -v $(pwd):/app composer/composer:latest install
```
B) usage
1) move the directory (generate by command docker in step 6, inside working directory) with name vendor where you want to store the phpseclib lib
2) php script exemple
```
require_once(dirname(__FILE__).'/lib/phpseclib/autoload.php');
use phpseclib3\Net\SSH2;

$ssh = new SSH2("127.0.0.1");
if (!$ssh->login("XXXXXLOGIN", "XXXXXPASSWORD")) {
	echo "error";
	exit('Login Failed');
}
echo $ssh->exec('pwd');
unset($ssh)
```

**Comment by terrafrost** [comment]
Thanks for the comment! Hopefully it helps someone!
