### ISSUE TITLE
Implicit conversion from float 2147483648 to int loses precision

### ISSUE THREAD

**Issue by come-nc** [phpseclib/phpseclib#1931]
I get this deprecation warning on PHP 8.3 beta builds when using phpseclib on 32bits:
```
Implicit conversion from float 2147483648 to int loses precision
#0 phpseclib/phpseclib/phpseclib/File/ASN1.php(1444): PHPUnit\Util\ErrorHandler->__invoke(8192, 'Implicit conver...', '/__w/server/ser...', 1444)
#1 phpseclib/phpseclib/phpseclib/File/X509.php(2956): phpseclib\File\ASN1->convert('core', 12)
```

I think `($c & 0x80000000)` is converting `0x80000000` to int because `$c` is an int and it does not fit in a 32bit int, not sure.

This is with version 2.0.40, but I see the same line in current code so I think it will trigger the same error.

**Comment by terrafrost** [comment]
Apologies for the delay - I've been particularly busy at work.

Does the following fix this for you?:

https://github.com/terrafrost/phpseclib/commit/0f895640771c091a05cf88c8726619d0ad4c7665

**Comment by come-nc** [comment]
> Apologies for the delay - I've been particularly busy at work.
> 
> Does the following fix this for you?:
> 
> [terrafrost@0f89564](https://github.com/terrafrost/phpseclib/commit/0f895640771c091a05cf88c8726619d0ad4c7665)

Hello, is there a new release planned including this fix?

**Comment by terrafrost** [comment]
I'll try to do a release this week!

**Comment by terrafrost** [comment]
2.0.45 and 3.0.22 have been released.

Thanks!
