### ISSUE TITLE
SSH exec() breaks on certain commands

### ISSUE THREAD

**Issue by procodix** [phpseclib/phpseclib#1936]
I was using this component to remotely control a server with docker installed on it. When exec()'ing the docker pull [image] command, the function broke somehow, not throwing an error. 

Docker pull does some weird things on the terminal to display progress bars, while downloading images. This works by emitting escape sequences. Maybe one of theses causes exec() to fail completely. Other commands with just plain output work fine.

Switched to PHP ssh2 pecl library and the problem does not appear. So it must happen somewhere in the guts of this library/function. 

Ceterum censeo Composer esse delendam

**Comment by terrafrost** [comment]
How do you know it broke somehow if it didn't return an error? I tried it just now and get this as the output:

```php
debug3: Copy environment: XDG_SESSION_ID=c3
debug3: Copy environment: XDG_RUNTIME_DIR=/run/user/1000
debug3: Copy environment: DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
debug3: Copy environment: XDG_SESSION_TYPE=tty
debug3: Copy environment: XDG_SESSION_CLASS=user
debug3: Copy environment: MOTD_SHOWN=pam
debug3: Copy environment: PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
debug3: Copy environment: LANG=C.UTF-8
Environment:
  USER=terrafrost
  LOGNAME=terrafrost
  HOME=/home/terrafrost
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  SHELL=/bin/bash
  XDG_SESSION_ID=c3
  XDG_RUNTIME_DIR=/run/user/1000
  DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus
  XDG_SESSION_TYPE=tty
  XDG_SESSION_CLASS=user
  MOTD_SHOWN=pam
  LANG=C.UTF-8
  SSH_CLIENT=::1 49112 2222
  SSH_CONNECTION=::1 49112 ::1 2222
Using default tag: latest
latest: Pulling from phpseclib/php5.6
5e6ec7f28fb7: Pulling fs layer
cf165947b5b7: Pulling fs layer
7bd37682846d: Pulling fs layer
99daf8e838e1: Pulling fs layer
2c54247ac480: Pulling fs layer
f3b1c2142f71: Pulling fs layer
02b89997b012: Pulling fs layer
723ecf6515b9: Pulling fs layer
337dea8774dc: Pulling fs layer
890b4e8b358a: Pulling fs layer
f3b1c2142f71: Waiting
02b89997b012: Waiting
723ecf6515b9: Waiting
337dea8774dc: Waiting
890b4e8b358a: Waiting
99daf8e838e1: Waiting
2c54247ac480: Waiting
cf165947b5b7: Verifying Checksum
cf165947b5b7: Download complete
99daf8e838e1: Download complete
2c54247ac480: Verifying Checksum
2c54247ac480: Download complete
f3b1c2142f71: Verifying Checksum
f3b1c2142f71: Download complete
5e6ec7f28fb7: Verifying Checksum
5e6ec7f28fb7: Download complete
723ecf6515b9: Download complete
5e6ec7f28fb7: Pull complete
cf165947b5b7: Pull complete
7bd37682846d: Verifying Checksum
7bd37682846d: Download complete
337dea8774dc: Verifying Checksum
337dea8774dc: Download complete
02b89997b012: Download complete
890b4e8b358a: Download complete
7bd37682846d: Pull complete
99daf8e838e1: Pull complete
2c54247ac480: Pull complete
f3b1c2142f71: Pull complete
02b89997b012: Pull complete
723ecf6515b9: Pull complete
337dea8774dc: Pull complete
890b4e8b358a: Pull complete
Digest: sha256:e906c992f3480133d37bddbfc1ece90061dd319329de74c8345659bc4a66f704
Status: Downloaded newer image for phpseclib/php5.6:latest
docker.io/phpseclib/php5.6:latest
```
> Docker pull does some weird things on the terminal to display progress bars, while downloading images. This works by emitting escape sequences.

You'd probably need a PTY for that. eg.

```php
$ssh->enablePTY();
if ($ssh->exec('docker pull "phpseclib/php5.6"')) {
	echo $ssh->read();
} else {
	echo "error running command";
}
```
An interactive shell would work too:

```php
$ssh->write("docker pull \"phpseclib/php5.6\"\n");
$ssh->read('[prompt]');
```
You could use a callback with read(), as well, to output stuff real time.

**Comment by procodix** [comment]
it broke, because the output was not complete and the docker image not pulled. However there was not error message neither from SSH nor from docker. The output stopped somewhere in the downloading process. I did not use PTY nor Shell, just plain command.

Maybe some output buffering overflow? with php_ssh2 a PTY or Shell is not necessary.

**Comment by terrafrost** [comment]
> Maybe some output buffering overflow? with php_ssh2 a PTY or Shell is not necessary.

You are mistaken there. `ssh2_exec()` uses a PTY whether or not you explicitly specify one. Quoting https://www.php.net/manual/en/function.ssh2-exec.php#87783 : 

> The "pty" parameter is not documented.
>
> You should pass a pty emulation name ("vt102", "ansi", etc...) if you want to emulate a pty, or NULL if you don't.
>
> Passing false will convert false to a string, and will allocate a "" terminal.

A good example of this is `top`. If a PTY wasn't being used it'd return instantly with the output of `TERM environment variable not set` but it doesn't. It stalls. With phpseclib you can set a timeout: http://phpseclib.com/docs/commands#top With libssh2 it doesn't appear that you can. Normally with streams I'd do `stream_select` but, based on the comments and my own testing, that doesn't work with libssh2.

**Comment by terrafrost** [comment]
So with SSH you can optionally send a "pty-req" SSH_MSG_CHANNEL_REQUEST:

https://datatracker.ietf.org/doc/html/rfc4254#section-6.2

You can then follow that up with an "exec" SSH_MSG_CHANNEL_REQUEST:

https://datatracker.ietf.org/doc/html/rfc4254#section-6.5

phpseclib  only does the former if you enable a PTY. libssh2's ssh2_exec does the former all the time and there appears to be no way to disable that behavior. The "_TERM environment variable value (e.g., vt100)_" is set to whatever you pass to `ssh2_exec` via the optional `$pty` parameter. If that parameter isn't set it defaults to the empty string.

**Comment by terrafrost** [comment]
phpseclib, in contrast, doesn't let you set the TERM environment variable at all. It only does vt100 and that's it. If you request a PTY it'll do so with vt100 but if you don't a PTY won't be used at all.

I may make it so that you can set the TERM variable at some point but I am _never_ going to make it so that a PTY will be requested whether or not you explicitly asked it to create one as doing so would break some commands. libssh2's API - or at least the PHP bindings to it - just aren't very good, sorry to say.

**Comment by procodix** [comment]
thanks for the hints. ->enablePTY() and then after ->exec() a ->read() to return the output did it for me.
