### ISSUE TITLE
$sftp->get('remotefile', 'localfile') deleting the remote file

### ISSUE THREAD

**Issue by abhayadev7** [phpseclib/phpseclib#1939]
I tried to download a file from remote server using the $sftp->get() method. The file was copied but at the same time the remote file get deleted.

**Comment by terrafrost** [comment]
Most likely downloading the file with _any_ SFTP client will result in the file being deleted.

The way phpseclib does downloads is it sends an [SSH_FXP_OPEN](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.3) packet. The only flag set for this packet is SSH_FXF_READ. ie. it's kinda like doing `$fp - fopen('filename.ext', 'r')` in PHP.

The server responds with an SSH_FXP_HANDLE packet and then phpseclib sends a bunch of [SSH_FXP_READ](https://datatracker.ietf.org/doc/html/draft-ietf-secsh-filexfer-02#section-6.4) packets, in rapid succession. It sends up to 32x at a time before reading the responses (SSH_FXP_DATA). This is equivalent to doing `fread($fp, 1024)` in parallel.

Finally phpseclib sends an SSH_FXP_CLOSE packet. ie. `fclose($fp)`.

`$sftp->get()` does _not_ delete files. If the _server_ is deleting files there's nothing phpseclib can do about that.

What does `$sftp->getServerIdentification()` tell you? Like what software is serving up SFTP? Maybe this behavior is discussed in their documentation.

Maybe the server is informing you of its intentions to delete files once downloaded? If that's the case then I'd suggest adding `define('NET_SFTP_LOGGING', SFTP::LOG_COMPLEX);` to the top of that file and then doing `$sftp->getSFTPLog()` after the download is complete. Best to test this on a small file, however.

**Comment by abhayadev7** [comment]
I get this SSH-2.0-SFTP Server as a response to $sftp->getServerIdentification()

**Comment by terrafrost** [comment]
So I gather from https://serverfault.com/q/1080187/166832 that "SSH-2.0-SFTP Server" may be ProFTPD but it's hard to say for sure.

None-the-less, I looked at the documentation for ProFTPD...  I guess there's an SFTP module for it but it's not immediately clear to me how one would make it delete files on download.

I'd contact the administrator of the of the SFTP site and ask them about it!

**Comment by abhayadev7** [comment]
We have contacted the FTP server administrator, and they confirm that the are hiding the file once it retrieved by any client. 

So there is no issue from this library

Thanks for the response. Closing this as it not an issue
