### ISSUE TITLE
I have some doubts about a long running command with long output.

### ISSUE THREAD

**Issue by frizquierdo** [phpseclib/phpseclib#1948]
I have been reading some issues regarding the execution of long-running commands, as well as other posts on the internet about it and the truth is that I cannot find a consensus, perhaps due to my lack of knowledge on the matter. I will give an example of the execution of a command with a "long" output and the way I solved it but I don't think it is very appropriate. Note that I run these types of tasks from a separate worker:

Example command "`squidguard -c /etc/squidguard/squidGuard.conf -C all -d`" (-d param force stdout output), it's an example of course there are anothers command with much more extensive execution and large output but I think it would be the same treatment.

   ```
 /**
     * Build SquidGuard database blacklist from SquidGuard config file
     *
     * @param string $squidGuardConfFile Main SquidGuard config file
     * @param null|int|false $timeout Execution timeout
     * @return string
     * @throws Exception
     */
    public function executeSquidGuardBuildBlackList(string $squidGuardConfFile, null|int|false $timeout): string {
        try {

            $cmd = sprintf("squidGuard -c %s -C all -d", $squidGuardConfFile);
            $cmd = $this->_sanitizeArg($cmd); // ensure exec only one command per call

            $output = "";
            $this->_connect(); // start ssh server connection
            if (is_int($timeout) || false === $timeout) {
                $this->sshConnection->setTimeout($timeout);
            }

            $this->sshConnection->exec($cmd, function ($str) use ($output) {
                $output .= $str;
                if (str_contains($str, "ERROR") || str_contains($str, "FATAL")) {
                    throw new Exception($output);
                }
            });
        } catch (Exception $exc) {
            throw $exc;
        } finally {
            if ($this->sshConnection->isConnected()) {
                $this->sshConnection->disconnect();
            }
        }

        return $output;
    }
```

For this cases the key was set timeout to 0.

In case of error, the way to detect them was compare partial output inside callback function with words that may appear during failed execution of this specific command, and interrup execution throwing an exception with the stored $output at the moment of error.
 
Is there another, more optimal way to get the full output of a long-running command and another way to try errors execution?

**Comment by terrafrost** [comment]
in-so-far as errors go...  by default phpseclib lumps stderr and stdout together, unless you do `$ssh->disableQuietMode()`, but it doesn't sound like you're doing that. if it'd be helpful i could make it so that stderr and stdout can be split out into separate streams as well but that's not something phpseclib currently supports.

in-so-far as more optimal ways to run long running commands...  well the anonymous function approach you're using can be a good one depending on the context. something else that might help you tho - `$ssh->setKeepAlive(5);`. you can replace the 5 with whatever number you see fit. the 5, in this case, represents 5 seconds. but the general idea is...  if the command you're running just doesn't send you output for a long time the SSH server may wind up closing the connection due to inactivity. eg  the connection might timeout. so setKeepAlive() sends an SSH_MSG_IGNORE packet every 5s or whatever when there's no data being received.

how much of a help that'll be to you ultimately depends on how your server is setup and what command(s) you're running. but in lieu of knowing stuff, it's worth a shot!

**Comment by frizquierdo** [comment]
> in-so-far as errors go... by default phpseclib lumps stderr and stdout together, unless you do `$ssh->disableQuietMode()`, but it doesn't sound like you're doing that. if it'd be helpful i could make it so that stderr and stdout can be split out into separate streams as well but that's not something phpseclib currently supports.
> 
> in-so-far as more optimal ways to run long running commands... well the anonymous function approach you're using can be a good one depending on the context. something else that might help you tho - `$ssh->setKeepAlive(5);`. you can replace the 5 with whatever number you see fit. the 5, in this case, represents 5 seconds. but the general idea is... if the command you're running just doesn't send you output for a long time the SSH server may wind up closing the connection due to inactivity. eg the connection might timeout. so setKeepAlive() sends an SSH_MSG_IGNORE packet every 5s or whatever when there's no data being received.
> 
> how much of a help that'll be to you ultimately depends on how your server is setup and what command(s) you're running. but in lieu of knowing stuff, it's worth a shot!

@terrafrost thank you for yours tips.
Initially I used the approach of isolating stderr with `$ssh->disableQuietMode() `but without using a callback, and this confused me a bit because all the time the task was executed correctly (maybe this is not the best example of long running command) but the output remained in sterr and the user was always notified as an error . I'll try entering $ssh->setKeepAlive(x); and evaluate, I never had this option in mind. I'm thinking about multitail command with mercure hub updates from callback function, where long periods of inactivity on the output can occur and the ssh connection can be lost. 

I think separating stderr and stdout is convenient, less complications in error handling.

**Comment by terrafrost** [comment]
> I think separating stderr and stdout is convenient, less complications in error handling.

I'll try to work on that. idk if I'll be able to get to it this coming week as this coming week is fairly busy for me but maybe the week after!

**Comment by frizquierdo** [comment]
> > I think separating stderr and stdout is convenient, less complications in error handling.
> 
> I'll try to work on that. idk if I'll be able to get to it this coming week as this coming week is fairly busy for me but maybe the week after!

@terrafrost thank you!!!!!!!!

**Comment by terrafrost** [comment]
So it looks like there already is a way to get stderr without needing to do `$ssh->disableQuietMode()`. Quoting http://phpseclib.com/docs/commands#one-off-commands :

> By default `$ssh->exec()` returns both stdout and stderr. To suppress stderr you can call `$ssh->enableQuietMode()`. To re-enable it call `$ssh->disableQuietMode()`.
> 
> To get stderr separately from stdout you'll need to call `$ssh->enableQuietMode()` and then call `$ssh->getStdError()`. These functions do _not_ work with `$ssh->read()` (ie. when a PTY is enabled) for reasons described [here](https://superuser.com/a/1581769/172193).
> 
> To get the exit status you can call `$ssh->getExitStatus()`.
> 
> To see whether or not "quiet mode" is enabled do `$ssh->isQuietModeEnabled()`.
