### ISSUE TITLE
v3.0.23: Fatal error: Uncaught Error: Cannot access property phpseclib3\Net\SFTP::$disconnect_reasons

### ISSUE THREAD

**Issue by MarkLittlewood** [phpseclib/phpseclib#1952]
I have submitted a pull request
phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3731

static::$disconnect_reasons  changed to self::$disconnect_reasons fixes the error

**Comment by terrafrost** [comment]
Closing because of #1953
