### ISSUE TITLE
Add IEEE P1363  signature format for EC keys

### ISSUE THREAD

**Issue by allan-simon** [phpseclib/phpseclib#1956]
most tools using ECDSA keys will return the signature using the IEEE P1363 format and not  ASN1 

see https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/sign#ecdsa

I'm not familliar enough to propose a PR but  i locally get it working by doing 
```php
// this is of course an example private key :)
$key = PublicKeyLoader::load('{"alg":"ES256","crv":"P-256","d":"KRiXxoIFHmBQJdoCsqB8Bc9_f2Z-QCdRgoydMKdoL04","ext":true,"key_ops":["sign"],"kty":"EC","x":"FKwqyGd4i2NAl8RUXCCBRCAIbcpeGyfyXwgA_AWHb8Y","y":"njxhw5O6zGVkBlcPDKYj0E-6VO1giHTUkJWBhgKNqd8"}')
          $key = $key
              ->withHash('sha256')
              ->withSignatureFormat('Raw')
          ;
          $rawSignature = $key->sign($input);
          $r =  $rawSignature['r']->toHex();
          $s =  $rawSignature['s']->toHex();
          $signature =pack(
                 'H*', 
                 $r . $s
          );
```

**Comment by terrafrost** [comment]
I'll work on this later this week! Got a late night meeting today and another one Thursday night and then longhornphp.com on Friday and Saturday!

**Comment by terrafrost** [comment]
How does the following look?:

https://github.com/terrafrost/phpseclib/tree/IEEE
https://github.com/terrafrost/phpseclib/commit/30bc7fc30c243c3a5c6eba4959dd76abf205f619

**Comment by allan-simon** [comment]
@terrafrost  looks great ! Is there anyway I can help you test it ?

**Comment by terrafrost** [comment]
See https://github.com/phpseclib/phpseclib/commit/0086be8af1e5c9aef896d1355fd4b7ccd7fcdcdf

I added a unit test to test it.

Thanks!

**Comment by allan-simon** [comment]
awesome ! thanks a lot, can't wait for a release :angel:

**Comment by terrafrost** [comment]
A new release with this code change has been released!:

https://github.com/phpseclib/phpseclib/releases/tag/3.0.34

Thanks!
