### ISSUE TITLE
Some ciphers make key and  will throw error

### ISSUE THREAD

**Issue by deatil** [phpseclib/phpseclib#1958]
These are 
pbeWithMD2AndRC2-CBC, 
pbeWithMD5AndRC2-CBC,
pbeWithSHA1AndRC2-CBC
ciphers will throw error. this is making rsa pkcs8 privatekey with pass.

**Comment by deatil** [comment]
the error is https://github.com/phpseclib/phpseclib/blob/3.0.33/phpseclib/Crypt/Common/SymmetricKey.php#L1031

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/c21db263b0b65116532684e6e3674dd2b9ceac18 should fix this.

Thanks!

**Comment by deatil** [comment]
> [c21db26](https://github.com/phpseclib/phpseclib/commit/c21db263b0b65116532684e6e3674dd2b9ceac18) should fix this.
> 
> Thanks!

now,it is workong ok. 
Some, the desCBC look and have error. other dont decrypt its key.

**Comment by terrafrost** [comment]
desCBC works just fine for me.

I used `openssl pkcs8 -in smallrsa.pem -topk8 -v1 PBE-MD5-DES -out enckey.pem` to create the key and was then able to load it with phpseclib without issue.

Can you provide a sample key that phpseclib is unable to load?

**Comment by deatil** [comment]
@terrafrost hi, the error is what phpseclib lib make a pkcs8-pbes2 key with desCBC, and other lib load the key and it will throw error.
It is what other lib can not decrypt the phpseclib making key.

**Comment by terrafrost** [comment]
It worked fine for me.

Here's the phpseclib code I used to create a key:

...
use phpseclib3\Crypt\EC;
use phpseclib3\Crypt\RSA\Formats\Keys\PKCS8;

PKCS8::setEncryptionAlgorithm('pbeWithMD5AndDES-CBC');

$key = EC::createKey('secp256k1');

echo $key->withPassword('demo');
```

I then removed the password with `openssl pkcs8 -topk8 -nocrypt -in enc.key -out test.key` and that worked without issue after I entered in demo as the password, when prompted. As a final verification I did `openssl ec -in test.key -text -noout` on the unencrypted key that pkcs8 and that worked, as well.

Can you post the code that isn't working and post how you're testing the key?

**Comment by terrafrost** [comment]
It worked fine for me.

Here's the phpseclib code I used to create a key:

```
use phpseclib3\Crypt\EC;
use phpseclib3\Crypt\RSA\Formats\Keys\PKCS8;

PKCS8::setEncryptionAlgorithm('pbeWithMD5AndDES-CBC');

$key = EC::createKey('secp256k1');

echo $key->withPassword('demo');
```

I then removed the password with `openssl pkcs8 -topk8 -nocrypt -in enc.key -out test.key` and that worked without issue after I entered in demo as the password, when prompted. As a final verification I did `openssl ec -in test.key -text -noout` on the unencrypted key that pkcs8 and that worked, as well.

Can you post the code that isn't working and post how you're testing the key?

**Comment by deatil** [comment]
make key:
~~~php
$private = CryptRSA::createKey(1024);
$private = $private->withPassword("123");
$prikey = $private->toString('PKCS8', [
    'encryptionAlgorithm' => 'id-PBES2',
    'encryptionScheme' => 'desCBC',
]);
~~~

check key:
~~~php
$pri = openssl_pkey_get_private($prikey, "123");
if ($pri == false) {
    die("key error");
}

$opensslConfigPath = __DIR__ . "/openssl.cnf";

$config = [
    "private_key_type" => OPENSSL_KEYTYPE_RSA, 
    "config"           => $opensslConfigPath,
];
openssl_pkey_export($pri, $newPiv, null, $config);
~~~

echo "key error"

**Comment by deatil** [comment]
i find error.

file line: [L221](https://github.com/phpseclib/phpseclib/blob/3.0.33/phpseclib/Crypt/Common/Formats/Keys/PKCS8.php#L221)

need change `$cipher = new TripleDES('cbc');` to `$cipher = new DES('cbc');` and it will work ok.

**Comment by terrafrost** [comment]
Nice find! https://github.com/phpseclib/phpseclib/commit/9bfd1362598d2990a8cd9e671d1691563ccc64d9 should fix that.

Thanks!

**Comment by deatil** [comment]
> Nice find! [9bfd136](https://github.com/phpseclib/phpseclib/commit/9bfd1362598d2990a8cd9e671d1691563ccc64d9) should fix that.
> 
> Thanks!

good
