### ISSUE TITLE
PKCS1 v1.5 / OAEP

### ISSUE THREAD

**Issue by Himan15** [phpseclib/phpseclib#1963]
Hi.
Can you help me to understand how encrypt data by public key with such algorithm?

Thank you/

**Comment by terrafrost** [comment]
As http://phpseclib.com/docs/rsa#encryption--decryption explains, you can encrypt data with OAEP thusly:

```php
$ciphertext = $public->encrypt($plaintext);
```
You can encrypt data with PKCS1 thusly:

```php
$public = $public->withPadding(RSA::ENCRYPTION_PKCS1);
$ciphertext = $public->encrypt($plaintext);
```

Note that if you're trying to decrypt phpseclib generated ciphertext's created with OAEP with another program you'll need to make sure that phpseclib is using the same parameters that the other program is using. Those parameters can be set with `withHash()`, `withMGFHash()` and `withLabel()`. phpseclib defaults to `sha256` for the first two and the empty string (`''`) for the label.

**Comment by Himan15** [comment]
Thank you.
