### ISSUE TITLE
Undefined variable $name in function addFileFormat 

### ISSUE THREAD

**Issue by altec-icex** [phpseclib/phpseclib#1971]
see class Crypt/Common/AsymmetricKey

**Comment by altec-icex** [comment]
self::$invisiblePlugins[static::ALGORITHM][] = strtolower($shortname);

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/4bdfec9c230d694ac8d6a41e6b992b29d4610103 should fix this.

Thanks!
