### ISSUE TITLE
Notice: Trying to access array offset on value of type bool in /src/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2132

### ISSUE THREAD

**Issue by Saltibarsciai** [phpseclib/phpseclib#1975]
in this code snippet function stat() can return false instead of array and cause notice on php 7.4

```
elseif ($mode & (self::RESUME | self::RESUME_START)) {
            // if NET_SFTP_OPEN_APPEND worked as it should _size() wouldn't need to be called
            $size = $this->stat($remote_file)['size'];
            $offset = $size !== false ? $size : 0;
        } 
```

**Comment by terrafrost** [comment]
https://github.com/phpseclib/phpseclib/commit/978a5d9dc0dbe1b45e90ba5b9cd4196fdd7c5aea and https://github.com/phpseclib/phpseclib/commit/6b34da463cba176825c7d834bd013a7540bd703c should fix this.

Sorry for not responding earlier - I was vacationing in Iceland and Norway (I'm from Texas so they're not exactly close).
