### ISSUE TITLE
Add setPaddable func at the SymmetricKey class?

### ISSUE THREAD

**Issue by deatil** [phpseclib/phpseclib#1987]
some date what need encrypt do not use padding, and when the encrypted data is decrypting and it is error for unpadding. so we need add func for set paddable？

the func is:
~~~php
// \phpseclib3\Crypt\Common\SymmetricKey add func and set no pad
    public function setPaddable($paddable)
    {
        $this->paddable = $paddable;
    }
~~~

**Comment by terrafrost** [comment]
Seems like `enablePadding()` and `disablePadding()` in `\phpseclib3\Crypt\Common\SymmetricKey` essentially do the same thing?

**Comment by deatil** [comment]
> Seems like `enablePadding()` and `disablePadding()` in `\phpseclib3\Crypt\Common\SymmetricKey` essentially do the same thing?

great. before i do not find.☺
