### ISSUE TITLE
Website broken

### ISSUE THREAD

**Issue by Phillip85** [phpseclib/phpseclib#1989]
https://phpseclib.com/ is broken right now,
its not possible to read the documentation.

![image](https://github.com/phpseclib/phpseclib/assets/22318939/1623143f-e064-4dab-b384-c60ada77d135)

**Comment by terrafrost** [comment]
I just reran the most recent job on the phpseclib.github.io repo, without making any changes, and it seems to have worked without issue and I can now access the site. Weird but, like I said, it seems to be working now.
