### ISSUE TITLE
2.0.47 is a breaking change | `AES::setKey` interface changed

### ISSUE THREAD

**Issue by susnux** [phpseclib/phpseclib#1990]
Since 2.0.47 the interface of `AES::setKey` changed in a breaking way.
Previously it was extending `Base` but now the `AES::setKey` was removed so that it inherits from `Base::setKey` which is marked as `@internal`.

So this now causes a psalm issue:
> InternalMethod: The method phpseclib\Crypt\Base::setKey is internal to phpseclib but called from ...

**Comment by terrafrost** [comment]
Apologies for not getting to this sooner - I had eclipse stuff and then was trying to finish up stuff at work so that I can go on a big trip starting tomorrow.

Anyway, https://github.com/phpseclib/phpseclib/commit/cd4d0ba47c5bd5e1f2b90728e73eeb7f1fbd158e should fix this.

Thanks!
