### ISSUE TITLE
Load ASN.1 private key to generate an RSA signature

### ISSUE THREAD

**Issue by PlanetIrata** [phpseclib/phpseclib#1994]
Hi, 

I'm using phpseclib 1.0.23 because I can't achieve to make version 3 work without using composer to install it, I want a zip file

I'd like to load a private key saved in a ASN.1 binary file but it doesn't work. Here is my code so far...

```php
$priv_key = file_get_contents('./my.rsa.private.key.txt');
$asn1 = new File_ASN1();
$decoded = $asn1->decodeBER(base64_encode($priv_key));
print_r($decoded);   // <-- THIS OUTPUT SEEMS OK : Array ( [0] => Array ( [type] => 1 [constant] => 13 [content] => EGA.....Om9jx [length] => 75 ) )
$rsa->loadKey($decoded[0]);  // <-- DON'T WORK RETURN FALSE
```

Any help ?

**Comment by terrafrost** [comment]
You can make phpseclib 3.0 work "without" Composer using the instructions at https://phpseclib.com/docs/install#without-composer .

That said, for 1.0...  why can't you just do this?:

```
$rsa = new Crypt_RSA();
$rsa->loadKey($priv_key);
```
If you're gonna go the `$asn1->decodeBER(base64_encode($priv_key));` route then you'd also need to call `asn1map` as well and doing so is a fair amount more complicated in the 1.0 branch.;

**Comment by PlanetIrata** [comment]
Hi @terrafrost 

I tried this at first attempt:

```
$rsa = new Crypt_RSA();
$priv_key = file_get_contents('./my.rsa.private.key.txt');
$rsa->loadKey($priv_key);  // <-- return false
```

But `loadKey` returns `false` and RSA sign doesn't do anything after that... 

Will try with phpseclib 3.0 ...

**Comment by terrafrost** [comment]
```php
$rsa = new Crypt_RSA();
$priv_key = file_get_contents('./my.rsa.private.key.txt');
$rsa->loadKey($priv_key);  // <-- return false
```
Would be helpful to see the key - or at least a key that reproduces the problem. As is I can only speculate as to why that doesn't work.

```php
$rsa = $key->asPrivateKey();
echo $key->sign("toto");   // <-- Fatal error: Maximum execution time of 30 seconds exceeded
```
You'd need to do `$rsa->sign("toto")` vs `$key->sign("toto")`, as public key objects don't implement the `sign()` method.

That said, when I did it with `$rsa->sign("toto")` took me 0.164s to run it and that was with the PHP64 engine. Like the GMP engine is waaaaaay faster but 0.164s is still plenty fast. This was on PHP 8.3

So if `echo $key->sign("toto");` _wasn't_ a typo then it's not clear why you're not getting this error:

```
Fatal error: Uncaught Error: Call to undefined method phpseclib3\Crypt\RSA\PublicKey::sign() in \path\to\whatever.php
```

If `echo $key->sign("toto");` _was_ a typo then I'd need to see your php.ini to have at least recommendations as to how to speed it up. But even with that, tbh, even PHP 5.6 / 32-bit mode should still be plenty fast. xdebug could slow thing down but idk how by much off hand.

**Comment by terrafrost** [comment]
Apologies for the delay - I've been traveling / vacationing.

Anyway, I was able to reproduce the issue and https://github.com/phpseclib/phpseclib/commit/2689c727e7a99841e1d3f13e3a5a5fe62853e803 fixed it for me. Does it fix it for you?

**Comment by PlanetIrata** [comment]
> Apologies for the delay - I've been traveling / vacationing.
> 
> Anyway, I was able to reproduce the issue and [2689c72](https://github.com/phpseclib/phpseclib/commit/2689c727e7a99841e1d3f13e3a5a5fe62853e803) fixed it for me. Does it fix it for you?

@terrafrost Yes it fixes the timeout, thanks !
