### ISSUE TITLE
How to make SSH2 to behave like ssh

### ISSUE THREAD

**Issue by dan-m-joh** [phpseclib/phpseclib#2005]
Hello terrafrost,

First of all, thanks for a great project. This is not a bug-report per se but rather a usage question.

I am trying to connect to a Brocade-SAN-Switch and execute some commands. Most commands works as expected, but there is (at least) one that "behaves" different when executed in a ssh-session compared to through phpseclib/SSH2.

Here a example.
Using a "normal" ssh-client:
```
$ ssh myswitch
myswitch:FID128:user> fabricname --show
Fabric Name: "Fabric-A"
myswitch:FID128:user> setcontext 2
myswitch-2:FID2:user> fabricname --show
Fabric Name: "Fabric-E"

```
And here an example using phpseclib:
```
#!/usr/bin/php
<?php

require_once 'vendor/autoload.php';

use phpseclib3\Net\SSH2;

$ssh = new SSH2('myswitch');
$ssh->login('user', 'password');

$ssh->enablePTY();
$ssh->exec('fabricname --show');
$ssh->setTimeout(5);
$txt = $ssh->read();
echo $txt;

$ssh->exec('setcontext 2');
$ssh->setTimeout(5);
$txt = $ssh->read();
echo $txt;

$ssh->exec('fabricname --show');
$ssh->setTimeout(5);
$txt = $ssh->read();
echo $txt;
```

Which produces the following output:
```
Fabric Name: "Fabric-A"
rbash: setcontext: command not found
Fabric Name: "Fabric-A"
```
Note the "command not found".
Do you have any idea what I am doing wrong and how to "fix" it?

Regards,
Dan

**Comment by terrafrost** [comment]
Hard to say for sure but I suspect you might have better luck if you did something like this:

```
$ssh->read('myswitch:FID128:user>');
$ssh->write("fabricname --show\n");
echo $ssh->read('myswitch:FID128:user>');
$ssh->write("setcontext 2\n");
echo $ssh->read('myswitch:FID128:user>');
$ssh->write("fabricname --show\n");
echo $ssh->read('myswitch:FID128:user>');
```
So like don't do `$ssh->exec()` with a PTY at all - just go into an interactive shell directly with `read()`.

**Comment by dan-m-joh** [comment]
Great, thanks for the feedback.
With read/write/read it works as expected.

Thanks and keep up the good work.
Regards,

Dan
