### ISSUE TITLE
signing JWT's with SSH Agents

### ISSUE THREAD

**Issue by terrafrost** [phpseclib/phpseclib#2022]
This is split off from https://github.com/phpseclib/phpseclib/issues/1735#issuecomment-2232904187.

@WarriorXK - I'm curious how you're envisioning this would work.

So with ssh-agent it just tries to login with every key in the agent. When it succeeds you move on.

So if you have multiple keys in your ssh-agent then how would you know which one to use? You could do something like this I guess:

```
$agent = new \phpseclib3\System\SSH\Agent();
$identities = $agent->requestIdentities();
foreach ($identities as $identity) {
    if ($identity->getPublicKey()->toString() != 'whatever') break;
    if ($identity->getPublicKey()->getFingerprint() != 'whatever') break;
}
```
(i put two if statements there because either of them can be used; not sure why you'd want to use both in conjunction with one another)

Anyway, assuming you have a satisfactory answer to that then I guess the next thing would be...  so you found the specific key you're wanting to use. So I guess a JWT consists of three base64 encoded parts separated by a dot (.):

- The first part is the header and, when base64-decoded, looks like `{"typ":"JWT","alg":"ES256"}`.
- The second part contains the claims and, when base64-decode, looks like this:

      {"iat":1722234232,"nbf":1722234232,"exp":1722234832,"iss":"https://api.my-awesome-app.io","aud":"https://client-app.io"}
- The third part contains the signature, base64-encoded.

So assuming you got the first and second parts down pat (eg. `$jwt[0]` and `$jwt[1]`) then what you could do is you could is something like this:

```php
$identity = $identity->withHash('sha256'); // idk if this is necessary
$sig = $identity->sign($jwt[0] . '.' . $jwt[1]); // $jwt[0] and $jwt[1] should retain their base64 encoding
$sig = \phpseclib3\File\ASN1::decodeBER($sig);
$sig = \phpseclib3\File\ASN1::asn1map($sig[0], \phpseclib3\File\ASN1\Maps\EcdsaSigValue::MAP);
$sig = $sig['r']->toBytes() . $sig['s']->toBytes();
$jwt[2] = sodium_bin2base64($sig, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
```
That's only for ES256 however. And all that could be greatly simplified if I created a new signature plugin so that you could do this:

```php
$identity = $identity->withHash('sha256'); // idk if this is necessary
$identity = $identity->withSignatureFormat('JWS');
$jwt[2] = $identity->sign($jwt[0] . '.' . $jwt[1]);
```

Anyway, does that sound to be pretty close what you're looking for? Also, if you're looking for support for a specific algorithm lmk

**Comment by terrafrost** [comment]
Also, sorry for the delayed response - I was in Japan when you made your request and got back early last week and was then trying to play catch up at work.

**Comment by WarriorXK** [comment]
Hi @terrafrost, no worries about the delayed response, I am in no hurry :).

To give a bit of background, we use this to authenticate against an API from CLI context where normally we use OIDC. But since logging in through OIDC in a commandline (and opening a browser) does work quite as smooth we came up with the idea of using SSH keys for authentication since we already deploy those everywhere.

We are currently using the following piece of code to sign the JWT using the local agent:
```php
exec('ssh-keygen -Y sign -n ' . escapeshellarg($namespace) . ' -f ' . escapeshellarg(stream_get_meta_data($pubKeyFile)['uri']) . ' < ' . stream_get_meta_data($srcFile)['uri']);
```

This requires us to specify with public key we want to use (written to a temp file `$pubKeyFile`), the ssh-keygen command will use the ssh-agent to find the matching available private key (Including from PKCS11 devices such as YubiKeys). 
Currently we use our own implementation code to determine which key to use based on the comment of the public key, if this would be implemented in PHPSecLib I don't think it should be the responsibility of the library to figure out which key to use. But I think specifying the public key as object or the fingerprint as argument to the sign function would be a preferred approach.

We use the following to verify the signature and validity on the server side:
```php

$sshPublicKeys = []; // Read from /home/$jwtSubject/.ssh/authorized keys or LDAP

$mappedSSHPublicKeys = [];
foreach ($sshPublicKeys as $sshPublicKey) {

    $publicKey = PublicKeyLoader::load($sshPublicKey);
    $mappedSSHPublicKeys['SHA256:' . $publicKey->getFingerprint('sha256')] = $publicKey;

}

...

exec('/usr/bin/ssh-keygen -Y check-novalidate -n ' . escapeshellarg($namespace) . ' -s ' . escapeshellarg($tmpSignatureFilePath) . ' < ' . escapeshellarg($tmpBodyFilePath) . ' 2>&1', $output, $resultCode);
if ($resultCode !== 0) {
   return JWTValidationCode::InvalidSignature;
}

$outputLine = reset($output);
preg_match('/ +(?<fingerprint>[^\s]+)$/', $outputLine, $matches);
$usedKeyFingerprint = $matches['fingerprint'];

$logger?->log(LogLevel::DEBUG, 'Signature is valid and signed with key ' . $usedKeyFingerprint);
if (!isset($mappedSSHPublicKeys[$usedKeyFingerprint])) {
    return JWTValidationCode::UnknownKey;
}
```

So what we are looking for is not a JWT implementation perse, but more something that would be able to create a signature using the SSH agent and be able to verify the signature using a list of public SSH keys. I get the feeling that the second part is already possible using PHPSecLib, I am just unsure how. The challenging one is the first part, communicating with an ssh-agent.

We already have this working, but it would be amazing if we could remove all dependencies on executing commands as it would limit the ease of deployment and is prone to break.

**Comment by terrafrost** [comment]
> Currently we use our own implementation code to determine which key to use based on the comment of the public key, if this would be implemented in PHPSecLib I don't think it should be the responsibility of the library to figure out which key to use. But I think specifying the public key as object or the fingerprint as argument to the sign function would be a preferred approach.

I can implement a `findIdentityByPublicKey(PublicKey $key)` method in System/SSH/Agent.php and perhaps a `findIdentityByFingerprint(string $fingerprint)`.

> So what we are looking for is not a JWT implementation perse, but more something that would be able to create a signature using the SSH agent and be able to verify the signature using a list of public SSH keys. I get the feeling that the second part is already possible using PHPSecLib, I am just unsure how. The challenging one is the first part, communicating with an ssh-agent.

The former - creating signatures - should be possible using the code I posted:

```php
$identity = $identity->withHash('sha256'); // idk if this is necessary
$sig = $identity->sign($jwt[0] . '.' . $jwt[1]); // $jwt[0] and $jwt[1] should retain their base64 encoding
$sig = \phpseclib3\File\ASN1::decodeBER($sig);
$sig = \phpseclib3\File\ASN1::asn1map($sig[0], \phpseclib3\File\ASN1\Maps\EcdsaSigValue::MAP);
$sig = $sig['r']->toBytes() . $sig['s']->toBytes();
$jwt[2] = sodium_bin2base64($sig, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
```
That's for ES256 but I can simplify that with some code changes.

I haven't tested it for any of the RSA algorithms but I imagine this would work for RS256:

```php
$identity = $identity->withPadding(RSA::SIGNATURE_PKCS1)->withHash('sha256');
$sig = $identity->sign($jwt[0] . '.' . $jwt[1]); // $jwt[0] and $jwt[1] should retain their base64 encoding
$jwt[2] = sodium_bin2base64($sig, SODIUM_BASE64_VARIANT_URLSAFE_NO_PADDING);
```
For verifying you should just be able to do something like this (untested):

```php
$jwt = explode('.', $jwt);
echo $public->verify($jwt[0] . '.' . $jwt[1], $jwt[2]) ? 'good' : 'bad';
```
Obviously you'd need to set the padding / hash as appropriate, depending on the algorithm being used.

**Comment by terrafrost** [comment]
> The only issue that remains for me is that the comment field key is not available to us even though its already being retrieved from the agent (Agent.php line 179). We need it to determine which key to use since YubiKeys expose 2 different keys. Is it possible to add this to the identity or the public key object somehow?

See https://github.com/phpseclib/phpseclib/commit/10075ea57e8afbbebef3a6a0f85d84f783fc36a4

Also, https://phpseclib.com/docs/jwt shows how to use PrivateKey objects (or Identity objects) to create various different JWT signatures:

**Comment by terrafrost** [comment]
> Also, https://phpseclib.com/docs/jwt shows how to use PrivateKey objects (or Identity objects) to create various different JWT signatures:

Some of those examples will work better on the next release of phpseclib due to these two commits:

https://github.com/phpseclib/phpseclib/commit/2276cf51c0bbda0d8c849d084e961afe26026618
https://github.com/phpseclib/phpseclib/commit/45b98d8cb39230019612ddcca3abbdc574152834

**Comment by WarriorXK** [comment]
Great! Thank you so much for your assistance. Just a final question, do you follow a generic release schedule so we know when to expect these commits to be available as a tagged release?

**Comment by terrafrost** [comment]
I can try to do a release this weekend!

**Comment by terrafrost** [comment]
3.0.40 has been released!

**Comment by WarriorXK** [comment]
Great, thank you so much for your time!
