### ISSUE TITLE
[Feature request][SFTP] Support openssh posix-rename extension

### ISSUE THREAD

**Issue by SamMousa** [phpseclib/phpseclib#2024]
First of all: I'm willing to make a PR for this.

Currently in SFTPv3 a rename fails when the target file already exists. While more recent versions of the protocol support atomic renames with automatic file overwrite, these are not widely adopted.

OpenSSH supports a protocol extension `posix-rename@openssh.com`. Currently this cannot be used from within this library for several reasons:

1. The supported extensions for the connection are not accessible from outside the SFTP class. This means consuming code would not know if it can use a `posix_rename()` even if it existed.
2. There is no `posix_rename()` or any way to send custom SFTP commands.

Given that there are not that many widely adopted SFTP server implementations I'd like to add the following to the SFTP class:

```php
    class SFTP {
      public function openssh_posix_rename($oldname, $newname): bool {
          if (!$this->precheck()) {
              return false;
          }
          if (!isset($this->extensions['posix-rename@openssh.com']) || $this->extensions['posix-rename@openssh.com'] !== '1') {
              throw new \RuntimeException("Extension 'posix-rename@openssh.com' is not supported by the server");
          }
  
          $oldname = $this->realpath($oldname);
          $newname = $this->realpath($newname);
          if ($oldname === false || $newname === false) {
              return false;
          }
  
          $packet = Strings::packSSH2('sss', 'posix-rename@openssh.com', $oldname, $newname);
          $this->send_sftp_packet(NET_SFTP_EXTENDED, $packet);
  
          $response = $this->get_sftp_packet();
          if ($this->packet_type != NET_SFTP_STATUS) {
              throw new \UnexpectedValueException('Expected NET_SFTP_STATUS. '
                  . 'Got packet type: ' . $this->packet_type);
          }
  
          // if $status isn't SSH_FX_OK it's probably SSH_FX_NO_SUCH_FILE or SSH_FX_PERMISSION_DENIED
          list($status) = Strings::unpackSSH2('N', $response);
          if ($status != NET_SFTP_STATUS_OK) {
              $this->logError($response, $status);
              return false;
          }
  
          // don't move the stat cache entry over since this operation could very well change the
          // atime and mtime attributes
          //$this->update_stat_cache($newname, $this->query_stat_cache($oldname));
          $this->remove_from_stat_cache($oldname);
          $this->remove_from_stat_cache($newname);
  
          return true;
      }
    }

```

This code has been tested to work. 

I realize that from a purity perspective it's not great to add implementation specific code to a generic protocol implementation; but given the stability of SFTP protocol in practice I feel this is OK.

There are cleaner alternatives but they are more work and will not be easier to maintain; we could implement some kind of extension system for the SFTP class. Essentially opening it up to extensions.

```php
interface SFTPExtensionApi {
    public function getSFTP(): SFTP;
    public function send_sftp_packet($type, $packet);
    public function get_sftp_packet();
    public function get_packet_type();
    public function remove_from_stat_cache($path);
    public function logError($response, $status);
}

class SFTP {

    public function registerExtension(string $name, $class) {
    
    }

    public function getExtension(string $extension = 'posix-rename@openssh.com') {
 
   }
}


```
While possibly theoretically cleaner it has a  big downside: It essentially opens up the SFTP class' internals making those part of the (or a) public API. 

I can implement this in a PR.

**Comment by terrafrost** [comment]
So what I'm thinking is this:

What if a magic method, `__get`, is added. Then, depending on the capabilities of the server and the extension plugins available to phpseclib, methods like `statvfs`, `hardlink`, `fsync`, `lsetstat`, `copy_data`, etc, would be "created" (ie. no need to have the `openssh_` prefix).

Some OpenSSH sftp extensions wouldn't work like that. `limits@openssh.com` obviously shouldn't work like that. That's more something that should be built into SFTP.php directly. `expand-path@openssh.com` would prob be best integrated into `realpath` and `users-groups-by-id@openssh.com` would prob be best done to modify how `chown` and `chgrp` currently work. Like right now those require an int be passed to them for SFTPv3 and a string for SFTPv4+. With `users-groups-by-id@openssh.com` we could make `chown` and `chgrp` accept strings for SFTPv3 as well.

Thanks!

**Comment by terrafrost** [comment]
So the only 2-3 things different under my proposal vs your proposal is that `__get` be added, that `openssh_posix_rename` not be an explicit function (that way people could write their own extension plugins for phpseclib if they wanted to) and that the `openssh_` prefix for the function name be dropped.

Otherwise I like the idea!

**Comment by SamMousa** [comment]
My preferred solution is to not implement an extensions API at all, it feels like a bit of overkill.
Furthermore the extensions API will effectively make most of the inner workings part of the public API. Which can cause trouble down the road.

The list of extensions (found one here: https://www.greenend.org.uk/rjk/sftp/sftpversions.html) is so small that it could be less effort to just implement them in the core when requested vs allowing "3rd party extensions" to the SFTP class.

The ones that should be easy to implement:

- [ ] posix-rename
- [ ] statvfs (operates on file path)
- [ ] fstatvfs (operates on file handle, not sure how this works in phpseclib)
- [ ] hardlink
- [ ] md5-hash
- [ ] copy-file
- [ ] symlink-order 


Let me know if that would be a workable solution; I think it would be better then setting up a full dynamic extension system.

**Comment by SamMousa** [comment]
@terrafrost please have a look at #2029. It is not what you preferred but I hope you can see the benefits of this simplicity.

**Comment by terrafrost** [comment]
So https://www.greenend.org.uk/rjk/sftp/sftpversions.html is a little out of date. In-so-far as OpenSSH supported extensions go https://github.com/openssh/openssh-portable/blob/master/PROTOCOL is much more up-to-date.

sftpversions.html, for example, makes no mention of `lsetstat`, `fsync`, `limits`, `expand-path` or `users-groups-by-id` whereas PROTOCOL does.

That said, I suppose it's a bit moot if one can't find an SFTP server that implements an arbitrary extension. For example, connecting to a random SSH-2.0-OpenSSH_8.2p1 Ubuntu-4ubuntu0.11 server and listing their extensions only returns these:

```
Array
(
    [posix-rename@openssh.com] => 1
    [statvfs@openssh.com] => 2
    [fstatvfs@openssh.com] => 2
    [hardlink@openssh.com] => 1
    [fsync@openssh.com] => 1
    [lsetstat@openssh.com] => 1
)
```
Newer OpenSSH versions probably offer more extension support but the unit tests should take that into consideration. Presumably the image that GitHub Actions for older versions of PHP are going to be using older versions of OpenSSH that don't offer as many extensions as newer versions.

Also, `md5-hash` is going to be hard to implement. sftpversions.html says "_Described in draft-ietf-secsh-filexfer-09 s9.1.1 but not later versions (use check-file-handle and check-file-name instead). Computes the MD5 hash of a byte range of an open file_". In reviewing the [various secsh-filexer drafts](https://en.wikipedia.org/wiki/SSH_File_Transfer_Protocol#History_and_development)...  it's in drafts 05 - 09, inclusive. SFTP v5 was only ever discussed in draft 05 and SFTP v6 was discussed in drafts 06 - 13, inclusive. So whereas it seems likely that an SFTPv5 implementation would provide support for it it seems like it's a bit of a toss up as to whether or not an SFTPv6 implementation would provide support for it. Like the first 3x drafts discussing SFTPv6 mention it but the latter 4x drafts discussing SFTPv6 do not.

**Comment by terrafrost** [comment]
e2488749ae40657b51800a5a7eebf2f74d82045d adds `getSupportedExtensions()` to SFTP.php to make it easier to see what extensions are supported.

Additional (albeit obscure) extensions that, in theory, phpseclib _could_ support can be found here:

https://bitvise.com/files/specs/sftp-bitvise-extensions.txt

**Comment by SamMousa** [comment]
I don't really care about implementing all extensions, my point was more that there are so few of them widely used that setting up an extension system is overkill.
If people request them in the future they can be implemented in this library.

**Comment by terrafrost** [comment]
Closing as the PR that added this feature has been merged.
