### ISSUE TITLE
`BCMath::bitwise_or` calls `bitwiseXorHelper` internally

### ISSUE THREAD

**Issue by Bilge** [phpseclib/phpseclib#2025]
This looks like an obvious bug. Is it not?

https://github.com/phpseclib/phpseclib/blob/9983f00675cfbda067f7948e7c27c898003446ce/phpseclib/Math/BigInteger/Engines/BCMath.php#L306-L309

**Comment by terrafrost** [comment]
Good catch! I updated the unit test to catch this with https://github.com/phpseclib/phpseclib/commit/67f87dd1e276ef4a82842a54f9a3a47edc01c915 and then implemented the fix in https://github.com/phpseclib/phpseclib/commit/67f87dd1e276ef4a82842a54f9a3a47edc01c915 .

Thanks!
