### ISSUE TITLE
Deprecation after new release

### ISSUE THREAD

**Issue by buismaarten** [phpseclib/phpseclib#2026]
After the new 3.0.40 release I'm getting the following deprecation message:

**Deprecated:** Creation of dynamic property phpseclib3\Net\SFTP::$is_timeout is deprecated in /[redacted]/vendor/phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 3272

**Comment by terrafrost** [comment]
Good catch! 3.0.41 has been released.

Thanks!
