### ISSUE TITLE
Doubt about support for password protected private OpenSSH keys

### ISSUE THREAD

**Issue by maxnyby** [phpseclib/phpseclib#2044]
According to https://phpseclib.com/docs/publickeys#openssh phpseclib does not support encrypted OpenSSH keys.  
But it would seem that commit 826d8d6670855e885d34595843e9fe0fb875b02b (version [3.0.15](https://github.com/phpseclib/phpseclib/releases/tag/3.0.15)) has made that possible.  
Is this just the documentation that hasn't been updated, or are there still issues around encryption on OpenSSH keys?

**Comment by terrafrost** [comment]
The documentation was (apparently only partially) updated back in November 2022:

https://github.com/phpseclib/phpseclib.github.io/commit/919cacf92e1b268bcaed524fe64f8e3f4445730f#diff-1da2a3b039556597dfa795bc77598789d7368f8e7049454f16f4d2433002934cL91

I guess I just missed a spot. That oversight has been remedied:

https://github.com/phpseclib/phpseclib.github.io/commit/93391fda317380a80ec17e110689415b5c15ef5a

Thanks!
