### ISSUE TITLE
[documentation] add the php IPv6 tips about square brackets

### ISSUE THREAD

**Issue by Cyrille37** [phpseclib/phpseclib#2058]
Hi

Thanks a lot for this package, it works fine :-)

Could you please add in the SSH documentation page [connect](https://phpseclib.com/docs/connect) the tips for IPv6 from php fsockopen documentation : "**When specifying a numerical IPv6 address (e.g. fe80::1), you must enclose the IP in square brackets.**". It'll make people happier :smile_cat: 

Thanks & cheers

ref: #869

**Comment by terrafrost** [comment]
Done. See https://github.com/phpseclib/phpseclib.github.io/commit/d5c6c6602961e69f1a2ff050d24ce3398b51b3a2

**Comment by Cyrille37** [comment]
Thanks & cheers
