### ISSUE TITLE
Replacing user_error with Exception?

### ISSUE THREAD

**Issue by slowbro** [phpseclib/phpseclib#29]
I'd put in a pull request, but I'm not sure if this is something this project desires. user_error is un-catchable, so using phpseclib in a framework like Yii is pretty tough should there be any errors (Yii will throw up a big error page).

I went ahead and forked this repo and made the necessary changes at [slowbro/phpseclib](https://github.com/slowbro/phpseclib) - but I have a feeling these changes will cause a lot of headache for anyone upgrading.

What are your guys' thoughts on this? Do you desire Exceptions to be part of phpseclib? I'd love to help this project out in any way possible- I've been using it for years now and it's been a _huge_ help!

-Katelyn

**Comment by bkosborne** [comment]
Hmm I wonder what happened to this commit? The 1.0.2 and 2.0.2 are not using the code to optionally throw exceptions, they still use `user_error`

**Comment by terrafrost** [comment]
I undid it:

https://github.com/phpseclib/phpseclib/commit/e71fc979133c16110d827bbf5316db97648bc463

**Comment by terrafrost** [comment]
The master branch does throw exceptions but that one is not BC with the 1.0 or 2.0 branches and the API is currently unstable (ie. it's subject to BC breaking changes).
