### ISSUE TITLE
Notice: No compatible server to client encryption algorithms found in

### ISSUE THREAD

**Issue by Segfaultd** [phpseclib/phpseclib#340]
Hey,

Since my update from PHP 5.2 to PHP 5.4, I've this error : 

Notice: No compatible server to client encryption algorithms found in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\nodejs\includes\classes\net\Net\SSH2.php on line 1235

Why ? And how to fix ?

**Comment by mromero91** [comment]
Change 

phpseclib_resolve_include_path(file) to set_include_path(file)

in file ssh2.php
