### ISSUE TITLE
[error] [php] unpack(): Type C: not enough input, need 1, have 0 

### ISSUE THREAD

**Issue by hanski07** [phpseclib/phpseclib#400]
This error gets thrown every once in awhile. It happens when the server tries to put a file ( <1mb) on an FTP site hosted by maytech. I updated to the latest stable version of phpseclib, but it threw the error this morning. I'm positive it's on Maytech's end, but I'd like a way to either retry a few times, or be able to send an alert that the file did not upload.

Here are a couple entires from my logs.
~~~
2014/03/27 05:00:47 [error] [php] unpack(): Type C: not enough input, need 1, have 0 (.../Net/SSH2.php:1225)

2014/06/20 05:00:37 [error] [php] unpack(): Type C: not enough input, need 1, have 0 (/...Net/SSH2.php:1721)
Stack trace:
#0 unknown(0): Net_SFTP->login()

2014/07/02 03:00:34 [error] [php] unpack(): Type C: not enough input, need 1, have 0 (.../Net/SSH2.php:1842)
~~~

Note the line differences.  The last one occurred with version 0.3.6. 

I think it would be nice if phpseclib threw an exception of some sort rather than keeling over. I'll probably wrap the _login_helper function in a try catch, and define some custom error handler that will throw the exception there, but I wanted to see if this is a known issue with a known solution (my Googling produced no results) before I went and did something like that.

Thanks!

**Comment by hanski07** [comment]
Well, we're approaching 7 months, and this error has not been thrown again. I think I'll close the issue as this doesn't seem like a common problem elsewhere, and my application has been running smoothly for ~7 months.

**Comment by phackwer** [comment]
We just had this error this week here at work.

**Comment by phackwer** [comment]
We are using the latest version (2.0.4) on Ubuntu 14.04 with PHP 7.0.8. I'm very inclined to believe that we have a problem with the SSL lib on that distro (I've had something like this when I tried to compile PHP 7 on Ubuntu 14.04 on November 2015, which forced me to install an updated version manually),

Could that be the reason?
