### ISSUE TITLE
Add AES Galois/Counter Mode (GCM)

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#47]

**Comment by piotrgolasz** [comment]
Ok, so according to https://wiki.php.net/rfc/openssl_aead GMC doesn't work with PHP.

PHP Bugs says: https://bugs.php.net/bug.php?id=67304

Last comment in aforementioned thread points to: https://github.com/Spomky-Labs/jose/blob/master/src/Util/GCM.php

**Comment by Spomky** [comment]
Hi, 

I confirm you this implementation works fine. I tested it with some tests vectors from the RFC7520.

**Comment by discotroy** [comment]
Apologies for the necro-post, but did this feature request ever go anywhere?  Did anyone look into the potential for adding GCM support?

**Comment by Spomky** [comment]
Hi, 

I decided to create a dedicated library. 
You will find it at https://github.com/Spomky-Labs/php-aes-gcm
