### ISSUE TITLE
Bug reporting.

### ISSUE THREAD

**Issue by RoelDeveloper** [phpseclib/phpseclib#485]
Hello,

I want to report some bugs.
Lets start with Net_SSH2
The following code makes php exits, it doesnt give any warnings, it just exist;

$sftp = new Net_SSH2("server.samp-xportal.com");
$sftp->login("random", "random");

The next code works;

$sftp = new Net_SSH2("http://server.samp-xportal.com/");
$sftp->login("random", "random");

Reason? please tell me
Second bug;

$sftp = new Net_SFTP("server.samp-xportal.com");
$sftp->login("test", "test");

Also makes php exit, without warning...
The follow code works;

$sftp = new Net_SFTP("123");
$sftp->login("test", "test");

I have no idea, but please tell me why this is...

**Comment by bantu** [comment]
@RoelDeveloper Are you still having issues?
