### ISSUE TITLE
undefined offset in _trim function

### ISSUE THREAD

**Issue by joshua-paddle** [phpseclib/phpseclib#497]
I'm getting the error "Undefined offset: 33" in phpseclib/phpseclib/phpseclib/Math/BigInteger.php, line 3586, which I see is the _trim function, which is being called via modInverse, which comes from Net_SSH2->login. So, I can't login, muchless do anything else, making this unusable.

I also get an undefined offset error from line 2705 when I use a different key, and occasionally from line 937. You clearly have some problems with your array handling!

**Comment by ahait** [comment]
Yes I had the same problem. It helped installing the bcmath plugin/module for php.

**Comment by terrafrost** [comment]
@ahait - it would be most helpful if you actually posted the error message (which would include the line number) and the version of phpseclib you're using...
