### ISSUE TITLE
Implement SSH2 Agent Forwarding

### ISSUE THREAD

**Issue by Anahkiasen** [phpseclib/phpseclib#505]
Is there a way to make agent forwarding work with phpseclib?

When I run `ssh -T git@github.com` on my server I correctly get `Hi Anahkiasen! You've successfully authenticated, but GitHub does not provide shell access.`.

However the following:

``` php
$connection = new Net_SFTP('foobar.eu', 22);
$agent      = new System_SSH_Agent;

$connection->login('user', $agent);
$connection->exec('ssh -T git@github.com');
```

Will return `Permission denied (publickey).`

**Comment by bantu** [comment]
@terrafrost This has been implemented a long time ago, right?

**Comment by terrafrost** [comment]
Yup!:

https://github.com/phpseclib/phpseclib/blob/1.0/phpseclib/System/SSH/Agent.php
