### ISSUE TITLE
Moving to proper release management / Releasing the php5 branch

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#514]
* We should define a feature set for the php5 branch (e.g. PSR4 autoloading and removing all the old PHP4 stuff or whatnot) and then just release it.

* Releasing it involves assigning a version number. I think semantic versioning should be followed. I am fine with starting at 1.0.0, then what currently is master can stay as 0.x.y. The alternative is to make master 1.0.0 and release php5 as 2.0.0.

* We should define how long the released version will be supported with bugfixes etc. pp.

* New developments should happen in different branches, etc. pp. The php5 branch has to go.

**Comment by bantu** [comment]
I would like to release now as is.

> Is there a reason we need to rush it out the door asap?

People want to start using the features we have now. See e.g. https://github.com/phpseclib/phpseclib/issues/243#issuecomment-70236357

Can we release 1.0 and 2.0 now and 1.1 and 2.1 with OpenSSL (without breaking BC)?

**Comment by virgofx** [comment]
The exceptions weren't resolved; however, those could be incorporated slowly as each location where user_error's() were being generated would need to be evaluated.  +1 for releasing versions and also setting the default to the current PHP branch so development can move faster.

**Comment by terrafrost** [comment]
I didn't see this until just now.

Anyway,

> People want to start using the features we have now. See e.g. #243 (comment)

Fair enough, but then people have been wanting a namespace'd php5 version for years. I don't see why such people can't wait a few more weeks / months.

> Can we release 1.0 and 2.0 now and 1.1 and 2.1 with OpenSSL (without breaking BC)?

Well then what about exceptions? Do we do a 3.0 release for that? I don't feel Exceptions are big enough impact to justify a major release.

You kinda already touched on how phpBB hasn't following semantic versioning with its releases to date however phpBB is hardly the only example. Another big example...  OpenSSL. [url=https://www.openssl.org/support/faq.html#MISC8]OpenSSL versioning[/url] takes the form x.y.za. x is arbitrary and thus far there have only ever been two x's. 0 and 1. y signifies a major release and BC is not guaranteed. BC is guaranteed when just z changes and letter releases (eg. a) only contain bug fixes.

Among other things, if the most significant digits are only reserved for arbitrary massive changes then when they change people will pay more attention, it stands to reason.

Like let's say you were a loyal vBulletin user for years and then you saw that phpBB released 3.1 after having been on 3.0 for years. At that point you might be thinking "last time I used phpBB I didn't like it - but maybe I'll like 3.1 better - maybe I should give it another chance!"

When changing the most significant digits of the version is only done rarely then when it is done it may get people to give it a second chance. Certainly there are other things that can motivate people to give software second chances, as well, but no need toss one of those avenues out the window.

If you're too trigger happy to change the most significant digit, in contrast, some people might just stop paying attention to that version number all together. I know I do.

I mean I remember I used to get excited to check out the latest versions of Netscape. "Netscape 4.0 is coming out? That's so exciting! I have to check it out!". vs now with Firefox, where it's more like "Firefox 35 is coming out? Who cares. I'm desensitized."

If I were to do a release now I'd probably do 0.3.10 for the php4 version and 2.0 for the php5 version. OpenSSL support would bring the php4 version to 1.0 and the php5 version to 2.1.

**Comment by terrafrost** [comment]
> If I were to do a release now I'd probably do 0.3.10 for the php4 version and 2.0 for the php5 version. OpenSSL support would bring the php4 version to 1.0 and the php5 version to 2.1.

How does that sound for versioning? It seems consistent to the OpenSSL versioning approach, which itself seems semi-semantic as is.

**Comment by bantu** [comment]
@terrafrost That sounds good to me. I assume we can rename the branches then: 0.3, 2.0, master

**Comment by terrafrost** [comment]
Yah. I'll try to release them this weekend, assuming other stuff doesn't come up.

**Comment by bantu** [comment]
Actually, in which branch are we developing 1.0 then?

**Comment by terrafrost** [comment]
I figured 1.0 would be in what's currently master. php5 would be 2.0. Or we could have the 2.0 branch be develop.

1.0 is still aiming for 99% BC with 0.x. 2.0...  not so much. With the 2.x series all 2.0.x releases will need to be BC with one another as will all 2.1.x releases etc but 2.0.x and 2.1.x in theory should not be BC.

Although that said, with a release scheme like that I guess in a few years we'd prob have multiple branches. idk how those should be organized. Maybe dev-1.0 could be where 0.3.9 is, dev-2.0 could be where 2.0 is, dev-2.1 could be where 2.1 is, etc?

**Comment by terrafrost** [comment]
So how does my proposal sound for the branch names?

**Comment by bantu** [comment]
@terrafrost When I said "1.0 2.0 master" I was talking about branch names. So let's drop the "dev-" prefix from your suggestion and we have an agreement. ;-)

1.0 - currently master; contains 0.3.x releases until OpenSSL support, then contains 1.0.x releases.
2.0 - branched off from current php5 on release of 2.0.0
master - currently php5, the branch where new features are supposed to be added.

So the next steps would be renaming master to 1.0 and php to master. Then releasing 2.0.0 and branching off the 2.0 branch.

The version number branches make it easy to see which branches are supposed to merged into which other branches. E.g. 1.0 -> 2.0 -> 2.1 -> 3.0 -> master

**Comment by cnelissen** [comment]
+1 for Bantu's last comment. I think that is a perfect plan.

**Comment by terrafrost** [comment]
Well 0.3.10 has been released as has 2.0.0. As for updating the branches...  I guess I'm not good enough at git to know how to do that :(

Locally, I did `git branch -b 1.0` while in master and then deleted master, locally. I did `git branch -b 2.0` and `git branch -b master` while in the php5 branch as well. I then tried to delete master on my origin (terrafrost/phpseclib), figuring I'd re-create it from the php5 branch but now I'm getting the following error:

```
$ git push origin :master
remote: error: refusing to delete the current branch: refs/heads/master
To https://github.com/terrafrost/phpseclib.git
 ! [remote rejected] master (deletion of the current branch prohibited)
error: failed to push some refs to 'https://github.com/terrafrost/phpseclib.git'
```

When I do `git status` in 1.0 I get this:

```
$ git status
On branch 1.0
Your branch is up-to-date with 'origin/master'.
```

I figured I'd push 1.0 and then change my local 1.0 branch to track the 1.0 branch on production but that didn't work:

```
$ git push origin --set-upstream 1.0
Branch 1.0 set up to track remote branch master from origin.
Everything up-to-date
```

And in any event, I'm not sure that's such a good idea on my part. If I delete master what does that do for everyone who has master currently checked out? What happens when they try to do a `git pull`?

**Comment by bantu** [comment]
git checkout master
git branch -m 1.0
git checkout php5
git branch -m master
git branch 2.0
git push origin master 1.0 2.0 :php5

**Comment by bantu** [comment]
I would have done the branch renaming first before the release. The API generation config needs work after changing branches.

**Comment by terrafrost** [comment]
> I would have done the branch renaming first before the release. The API generation config needs work after changing branches.

Oh. Should I delete the tags?

Can you do the branches? I just got to work and probably won't be able to do any work with them until maybe 9-10h. I mean, I can post on github.com but I'm not gonna do commits from my work desktop..

**Comment by bantu** [comment]
> Oh. Should I delete the tags?

You did not push tags to phpseclib repository yet. So this should be fine. So we only have to worry about people who already downloaded the 0.3.10 packages. I'd say let's just keep that release and that tag.

> Can you do the branches?

Yes.

**Comment by terrafrost** [comment]
I updated the README.md file in master to say 0.3.10 (did so via github.com) altho now that I think about it I probably should have done it in the 1.0 branch and had it merged all the way up. Meh.

**Comment by bantu** [comment]
> I updated the README.md file in master to say 0.3.10 (did so via github.com) altho now that I think about it I probably should have done it in the 1.0 branch and had it merged all the way up. Meh.

I would actually like to move direct download links onto the wiki and include checksums.

Please push the 0.3.10 tag corresponding to the packages you published. Don't push the 2.0.0 tag, though. Delete that instead.

Can we establish that the preferred method to install 2.0 is via composer. We do not provide PEAR packages at all, right?

**Comment by terrafrost** [comment]
> Please push the 0.3.10 tag corresponding to the packages you published. Don't push the 2.0.0 tag, though. Delete that instead.

I'll do that later today.

> Can we establish that the preferred method to install 2.0 is via composer? We do not provide PEAR packages at all, right?

That's actually kinda what I was thinking lol

**Comment by tomzx** [comment]
Sorry to barge in, is there an ETA on the 2.0 tag? Dependencing on `dev-master` isn't nice :cry:

**Comment by GrahamCampbell** [comment]
> Is there an ETA on the 2.0 tag? Dependencing on dev-master isn't nice :cry:.

Why would you need to do that? Use a proper version constraint.

**Comment by tomzx** [comment]
@GrahamCampbell What is the proper version constraint to use for the 2.x branch?

**Comment by GrahamCampbell** [comment]
`2.0.*@dev` or `~2.0@dev` would do the job.

**Comment by tomzx** [comment]
Sorry, I guess I wasn't clear. I was asking when there would be a **stable** tag.

**Comment by GrahamCampbell** [comment]
Yeh. I was just responding to you saying you had to use `dev-master`, when you don't. That was all. :)

**Comment by bantu** [comment]
Closing this in favour of #756
