### ISSUE TITLE
2.x Beta Tag/Release Management

### ISSUE THREAD

**Issue by virgofx** [phpseclib/phpseclib#545]
Now that it seems a lot of changes are getting pushed through in the php5 branch in smaller batches, I wanted to include an issue to ensure tag/release management gets done properly at the conclusion of the namespacing/exceptions/2.0 roadmap, which is critical for including phpseclib in other libraries.

Required Changes:

1. Rename the current master branch name from **master** to "1.x-stable".  (Or something similar --- "1.0", "legacy", "php4")  (This is inline with common best practice). 
1. Rename the **php5** branch to **master**.
1. Set the default branch to be the newly renamed **master** branch.
1. Update the composer.json branch aliases accordingly.
    * "dev-master": "2.0-dev"
    * "dev-legacy": "1.0-dev"  (Or update the legacy part to match the updated branch name in step 1 above)
1. Update the readme.md to include information about the current two branches.  Specifically, a 1.x branch that is stable, PEAR formatting, PHP4 and the **current** 2.x branch that supports PHP5, autoloading, etc.
1. Lastly, tag the releases on the the master branch starting with an initial 2.0 tag/release. This is important to allow for other PHP projects to include a composer level "STABLE" of the project.

**Comment by bantu** [comment]
I agree with https://github.com/phpseclib/phpseclib/issues/243#issuecomment-70236357 we should release soon. As is, if necessary.

**Comment by ArjandeV** [comment]
@GrahamCampbell I get this error if I include either dev-php5 or ~2.0@dev in a package:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for elfet/deployer dev-master -> satisfiable by elfet/deployer[dev-master].
    - elfet/deployer dev-master requires phpseclib/phpseclib ~2.0-dev -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by bantu** [comment]
Closing this in favour of #514
