### ISSUE TITLE
Class Properties/Methods Not Consistent

### ISSUE THREAD

**Issue by cnelissen** [phpseclib/phpseclib#600]
Since there is no PSR standard with regards to the case style of class properties, I figured it is something we should come to an agreement on and then address.

Currently we are using a mix of case styles in different classes, some being camelCased and some being snake_cased, and even in File/X509 some being StudlyCased.

PSR-1:4.2 states:

"This guide intentionally avoids any recommendation regarding the use of $StudlyCaps, $camelCase, or $under_score property names.

Whatever naming convention is used SHOULD be applied consistently within a reasonable scope. That scope may be vendor-level, package-level, class-level, or method-level."

Let's just pick one and then make them all the same.

Also, we have methods that are snake_cased that should not be, (SSH2::_generate_identifier for instance). PSR-1:4.3 states:

"Method names MUST be declared in camelCase()."

**Comment by terrafrost** [comment]
Variable names are one thing. Changing public methods, however, is another matter entirely, as that breaks BC. And _generate_identifier, despite not being public, still affects BC, since it's intended to be used classes extended Net_SSH2 per #214.

Anyway, maybe come up with a list of what's not camelCase and further discussion can be had.

Do keep in mind that any BC breaking changes would be 2.0 / php5 only.

**Comment by cnelissen** [comment]
> Anyway, maybe come up with a list of what's not camelCase and further discussion can be had.

I think specifics are irrelevant... My intention for this issue was to decide what the standard convention for class properties *should* be for phpseclib. Once an agreement has been made, then we can come up with a list of what needs to change, and what the affects would be, since that largely depends on which way things go.

As for class methods, there really isn't any discussion to be had, if we are going to move to PSR-1/2 as a coding standard (and we definitely should) then all methods need to be camel cased.

> Do keep in mind that any BC breaking changes would be 2.0 / php5 only

Yes, and I agree. The move to PSR-1/2 is only for 2.0, as has been stated elsewhere.
