### ISSUE TITLE
loadCsr returns false on most files tested since 0.3.8

### ISSUE THREAD

**Issue by Fuitad** [phpseclib/phpseclib#602]
Heya,

While trying to understand why my app was no longer able to read 90% of the CSR thrown it's way after upgrading from 0.3.7 to 0.3.9, I was able to nail it down to this specific commit: e258e001fae139432af071ca4d7f4e42717eaeba (ASN1: rewrite _decode_der)

I am really not good enough when it comes to ASN1 to debug it much further and most of the CSR files I tried cannot be shared publicly :(. Is there anything more I can do to help understand where the problem is?

Here's my version of PHP, if that's any help: PHP 5.4.27 (cli) (built: Apr 23 2014 11:11:19)

**Comment by Fuitad** [comment]
I just upgraded my PHP installation (PHP 5.6.4 (cli) (built: Jan  7 2015 14:26:17)) and I'm getting the same result. Both 0.3.8 and 0.3.9 refuse to parse pretty much all of my CSR.

For what's worth, I'm running OSX Yosemite.

I hope this info helps.

**Comment by terrafrost** [comment]
Can you post a CSR that doesn't decode?

I can throw a few test CSR's at it myself, as well, but one that you've confirmed to have the issue vs me trying to brute force until I find one that doesn't work would make my life easier!

**Comment by Fuitad** [comment]
Hey there! :) I emailed you two CSR for you to test. I used the email displayed on your github profile. I hope that's OK.

**Comment by terrafrost** [comment]
Try replacing your ASN1.php with this:

https://raw.githubusercontent.com/phpseclib/phpseclib/84325d415eb35f2ebedc0893bc2ca46a7a19ac63/phpseclib/File/ASN1.php

#606 elaborates as to what was going on. The CSR in the unit test is based off of the ones you sent me but the keys have been replaced as has the subject DN.
