### ISSUE TITLE
Add diffie-hellman-group-exchange-sha256 key exchange algorithm

### ISSUE THREAD

**Issue by GregOriol** [phpseclib/phpseclib#609]
It seems that some server configurations are now upgraded to use only diffie-hellman-group-exchange-sha256 or some more advanced key exchange algorithms than the diffie-hellman-group1-sha1 or diffie-hellman-group14-sha1 currently supported by phpseclib.
Would it be possible to add diffie-hellman-group-exchange-sha256 ?

**Comment by terrafrost** [comment]
I can look into that.

Although that said I would say that servers that do not provide `diffie-hellman-group1-sha1` or `diffie-hellman-group14-sha1` are not in compliant. From [RFC4253](https://tools.ietf.org/html/rfc4253#section-6.5):

```
   Two REQUIRED key exchange methods have been defined:

      diffie-hellman-group1-sha1 REQUIRED
      diffie-hellman-group14-sha1 REQUIRED
```

**Comment by bantu** [comment]
Maybe there is an RFC deprecating those. I however doubt that. I rather expect distributions to disable insecure primitives because IETF processes are rather slow (too slow). The same probably applies to arcfour.

**Comment by GregOriol** [comment]
Sadly today I had to use a server maintained by an "admin" who disabled them... and so I couldn't make my script based on phpseclib to work with this server. I guess things are moving a little bit faster now that we have more of those "cyber attacks" things in the news, and some articles like this one: https://stribika.github.io/2015/01/04/secure-secure-shell.html

**Comment by terrafrost** [comment]
> Maybe there is an RFC deprecating those.

I'm not aware of any. If you scroll to the top you'll see "Updated by: 6668" but RFC6668 doesn't address diffie hellman key exchange. Just the hash algorithms. The errata doesn't mention deprecating diffie hellman either.

Whether or not it should be deprecated is another matter.

Anyway, like I said, I'll look into adding support for this.

Thanks!

**Comment by bantu** [comment]
RFC4419 is relevant here. No deprecation as far as I can see. https://tools.ietf.org/html/rfc4419

**Comment by GregOriol** [comment]
Hello,

@terrafrost : do you have any news on this implementation?

See you

**Comment by bantu** [comment]
@GregOriol Please test #714
