### ISSUE TITLE
Add curve25519-sha256@libssh.org key exchange algorithm

### ISSUE THREAD

**Issue by GregOriol** [phpseclib/phpseclib#610]
It seems that some server configurations are now upgraded to use only curve25519-sha256@libssh.org or some more advanced key exchange algorithms than the diffie-hellman-group1-sha1 or diffie-hellman-group14-sha1 currently supported by phpseclib.
Would it be possible to add curve25519-sha256@libssh.org ?

**Comment by bantu** [comment]
Also see #151

**Comment by bantu** [comment]
@terrafrost Here is a work in progress, but the SSH2 tests are not working correctly permanently yet. https://github.com/bantu/phpseclib/compare/phpseclib:php5...bantu:ssh-curve25519 Not I'll have time to look into it again any time soon.

**Comment by GregOriol** [comment]
Hi,

Any news on this?

Best regards,

**Comment by bantu** [comment]
#755 added support for this via libsodium.

**Comment by GregOriol** [comment]
Thanks! I'll try that!
