### ISSUE TITLE
SFTP upload File beyond 1.5kb upload hang.

### ISSUE THREAD

**Issue by markuz1787** [phpseclib/phpseclib#613]
Hello, I have a simple script that upload a file into server but everytime I upload a file beyond 1.5kb the script becomes hang or script loading forever. File size lower than 1.5kb is working. Im using the latest version 0.3.9.  My setup is Centos 6.5 server source and the destination server is Windows Server with freeFTPd SFTP server. Already tried other older version still not working.

Heres my script:
include('Net/SFTP.php');
define('NET_SFTP_LOGGING', NET_SFTP_LOG_REALTIME); 
$sftp = new Net_SFTP($host, 9222);
if ($sftp->login($username, $password)){
	echo 'Connection Success<br>';
	if($sftp->put('filename.csv', 'filename.csv', NET_SFTP_LOCAL_FILE))
	{
		echo 'File Transfer Success<br>';
	}
	else
	{
		echo 'File Transfer Failed<br>';
	}
}
else
{
	echo 'Connection Failed';
}

print_r($sftp->nlist());
echo $sftp->getSFTPLog();

Heres the logs:
-> NET_SFTP_INIT (0.0002s)
00000000  00:00:00:03                                      ....

<- NET_SFTP_VERSION (0.077s)
00000000  00:00:00:03                                      ....

-> NET_SFTP_REALPATH (0.0002s)
00000000  00:00:00:01:2e                                   .....

<- NET_SFTP_NAME (0.0769s)
00000000  00:00:00:01:00:00:00:01:2f:00:00:00:01:2f:00:00  ......../..../..
00000010  00:00                                            ..

Connection Success

-> NET_SFTP_OPEN (0.0003s)
00000000  00:00:00:19:2f:4a:42:39:39:39:39:5f:32:30:31:35  ..../JB9999_2015
00000010  30:31:32:38:5f:31:34:30:33:2e:63:73:76:00:00:00  0128_1403.csv...
00000020  1a:00:00:00:00                                   .....

<- NET_SFTP_HANDLE (0.0789s)
00000000  00:00:00:12:77:6f:64:53:66:74:70:46:69:6c:65:48  ....wodSftpFileH
00000010  61:6e:64:6c:65:30                                andle0

-> NET_SFTP_WRITE (0.0032s)
00000000  00:00:00:12:77:6f:64:53:66:74:70:46:69:6c:65:48  ....wodSftpFileH
00000010  61:6e:64:6c:65:30:00:00:00:00:00:00:00:00:00:00  andle0..........
00000020  08:16:32:30:31:35:30:31:32:38:31:34:30:33:33:31  ..20150128140331
00000030  2c:31:30:30:30:31:37:30:30:30:30:30:30:30:30:31  ,100017000000001
00000040  30:2c:30:30:30:30:30:30:30:36:30:30:31:30:34:30  0,00000006001040
00000050  33:2c:30:30:30:34:33:35:35:35:2c:31:31:31:39:2e  3,00043555,1119.
00000060  33:2c:32:37:32:37:2e:35:37:2c:30:30:30:30:32:36  3,2727.57,000026
00000070  0a:32:30:31:35:30:31:32:38:31:34:30:33:33:31:2c  .20150128140331,
00000080  31:30:30:30:31:30:32:30:31:35:34:31:30:34:36:39  1000102015410469
00000090  2c:35:30:30:30:31:36:2c:30:30:30:30:30:30:30:30  ,500016,00000000
000000a0  30:30:30:39:39:39:39:2c:32:30:31:35:30:30:30:30  0009999,20150000
000000b0  31:36:2c:34:39:2e:30:30:2c:32:39:2e:30:32:0a:32  16,49.00,29.02.2
000000c0  30:31:35:30:31:32:38:31:34:30:33:33:31:2c:31:30  0150128140331,10
000000d0  30:30:31:30:32:30:32:31:30:35:33:33:36:30:2c:35  00102021053360,5
000000e0  30:30:30:31:35:2c:30:30:30:30:30:30:30:30:30:30  00015,0000000000
000000f0  30:39:39:39:39:2c:32:30:31:35:30:30:30:30:31:35  09999,2015000015
00000100  2c:30:2e:30:30:2c:30:30:0a:32:30:31:35:30:31:32  ,0.00,00.2015012
00000110  38:31:34:30:33:33:31:2c:31:30:30:30:31:30:32:30  8140331,10001020
00000120  32:31:37:38:33:30:34:30:2c:35:30:30:30:31:37:2c  21783040,500017,
00000130  30:30:30:30:30:30:30:30:30:30:30:39:39:39:39:2c  000000000009999,
00000140  32:30:31:35:30:30:30:30:31:37:2c:30:2e:30:30:2c  2015000017,0.00,
00000150  30:30:0a:32:30:31:35:30:31:32:38:31:34:30:33:33  00.2015012814033
00000160  31:2c:31:30:30:30:31:30:32:30:32:34:38:33:38:39  1,10001020248389
00000170  33:32:2c:35:30:30:30:31:38:2c:30:30:30:30:30:30  32,500018,000000
00000180  30:30:30:30:30:39:39:39:39:2c:32:30:31:35:30:30  000009999,201500
00000190  30:30:31:38:2c:31:39:38:2e:30:30:2c:31:38:32:2e  0018,198.00,182.
000001a0  30:34:0a:32:30:31:35:30:31:32:38:31:34:30:33:33  04.2015012814033
000001b0  31:2c:31:30:30:30:31:30:32:30:32:32:31:32:34:32  1,10001020221242
000001c0  30:32:2c:35:30:30:30:31:39:2c:30:30:30:30:30:30  02,500019,000000
000001d0  30:30:30:30:30:39:39:39:39:2c:32:30:31:35:30:30  000009999,201500
000001e0  30:30:31:39:2c:33:36:2e:30:30:2c:32:31:39:2e:32  0019,36.00,219.2
000001f0  38:0a:32:30:31:35:30:31:32:38:31:34:30:33:33:31  8.20150128140331
00000200  2c:31:30:30:30:31:30:32:30:32:35:35:38:36:37:39  ,100010202558679
00000210  35:2c:35:30:30:30:32:30:2c:30:30:30:30:30:30:30  5,500020,0000000
00000220  30:30:30:30:39:39:39:39:2c:32:30:31:35:30:30:30  00009999,2015000
00000230  30:32:30:2c:31:31:33:2e:38:31:2c:34:32:36:2e:39  020,113.81,426.9
00000240  31:0a:32:30:31:35:30:31:32:38:31:34:30:33:33:31  1.20150128140331
00000250  2c:31:30:30:30:31:30:32:30:32:34:32:33:39:37:37  ,100010202423977
00000260  36:2c:35:30:30:30:32:31:2c:30:30:30:30:30:30:30  6,500021,0000000
00000270  30:30:30:30:39:39:39:39:2c:32:30:31:35:30:30:30  00009999,2015000
00000280  30:32:31:2c:30:2e:30:30:2c:30:30:0a:32:30:31:35  021,0.00,00.2015
00000290  30:31:32:38:31:34:30:33:33:31:2c:31:30:30:30:31  0128140331,10001
000002a0  30:32:30:32:31:36:36:35:33:34:36:2c:35:30:30:30  02021665346,5000
000002b0  32:32:2c:30:30:30:30:30:30:30:30:30:30:30:39:39  22,0000000000099
000002c0  39:39:2c:32:30:31:35:30:30:30:30:32:32:2c:30:2e  99,2015000022,0.
000002d0  30:30:2c:31:35:2e:30:30:0a:32:30:31:35:30:31:32  00,15.00.2015012
000002e0  38:31:34:30:33:33:31:2c:31:30:30:30:31:30:33:30  8140331,10001030
000002f0  30:35:38:38:31:37:35:30:2c:35:30:30:30:32:33:2c  05881750,500023,
00000300  30:30:30:30:30:30:30:30:30:30:30:39:39:39:39:2c  000000000009999,
00000310  32:30:31:35:30:30:30:30:32:33:2c:32:32:31:2e:39  2015000023,221.9
00000320  30:2c:35:2e:35:36:0a:32:30:31:35:30:31:32:38:31  0,5.56.201501281
00000330  34:30:33:33:31:2c:31:30:30:30:31:30:32:30:32:34  40331,1000102024
00000340  36:30:34:30:39:34:2c:35:30:30:30:32:34:2c:30:30  604094,500024,00
00000350  30:30:30:30:30:30:30:30:30:39:39:39:39:2c:32:30  0000000009999,20
00000360  31:35:30:30:30:30:32:34:2c:37:35:2e:30:30:2c:31  15000024,75.00,1
00000370  38:35:2e:35:30:0a:32:30:31:35:30:31:32:38:31:34  85.50.2015012814
00000380  30:33:33:31:2c:31:30:30:30:31:30:32:30:32:30:37  0331,10001020207
00000390  38:37:34:35:35:2c:35:30:30:30:32:35:2c:30:30:30  87455,500025,000
000003a0  30:30:30:30:30:30:30:30:39:39:39:39:2c:32:30:31  000000009999,201
000003b0  35:30:30:30:30:32:35:2c:31:32:39:2e:30:30:2c:31  5000025,129.00,1
000003c0  39:2e:34:32:0a:32:30:31:35:30:31:32:38:31:34:30  9.42.20150128140
000003d0  33:33:31:2c:31:30:30:30:31:30:33:30:30:35:35:34  331,100010300554
000003e0  35:37:33:36:2c:35:30:30:30:32:36:2c:30:30:30:30  5736,500026,0000
000003f0  30:30:30:30:30:30:30:39:39:39:39:2c:32:30:31:35  00000009999,2015
00000400  30:30:30:30:32:36:2c:30:2e:30:30:2c:30:30:0a:32  000026,0.00,00.2
00000410  30:31:35:30:31:32:38:31:34:30:33:33:31:2c:31:30  0150128140331,10
00000420  30:30:31:30:33:30:30:35:35:34:35:37:32:38:2c:35  00103005545728,5
00000430  30:30:30:32:37:2c:30:30:30:30:30:30:30:30:30:30  00027,0000000000
00000440  30:39:39:39:39:2c:32:30:31:35:30:30:30:30:32:37  09999,2015000027
00000450  2c:30:2e:30:30:2c:30:30:0a:32:30:31:35:30:31:32  ,0.00,00.2015012
00000460  38:31:34:30:33:33:31:2c:31:30:30:30:31:30:32:30  8140331,10001020
00000470  32:33:38:34:38:32:39:36:2c:35:30:30:30:32:38:2c  23848296,500028,
00000480  30:30:30:30:30:30:30:30:30:30:30:39:39:39:39:2c  000000000009999,
00000490  32:30:31:35:30:30:30:30:32:38:2c:34:36:2e:30:30  2015000028,46.00
000004a0  2c:36:33:2e:30:38:0a:32:30:31:35:30:31:32:38:31  ,63.08.201501281
000004b0  34:30:33:33:31:2c:31:30:30:30:31:30:32:30:32:33  40331,1000102023
000004c0  38:36:30:32:33:34:2c:35:30:30:30:32:39:2c:30:30  860234,500029,00
000004d0  30:30:30:30:30:30:30:30:30:39:39:39:39:2c:32:30  0000000009999,20
000004e0  31:35:30:30:30:30:32:39:2c:30:2e:30:30:2c:30:30  15000029,0.00,00
000004f0  0a:32:30:31:35:30:31:32:38:31:34:30:33:33:31:2c  .20150128140331,
00000500  31:30:30:30:31:30:32:30:32:33:38:36:36:37:37:37  1000102023866777
00000510  2c:35:30:30:30:33:30:2c:30:30:30:30:30:30:30:30  ,500030,00000000
00000520  30:30:30:39:39:39:39:2c:32:30:31:35:30:30:30:30  0009999,20150000
00000530  33:30:2c:38:30:2e:30:30:2c:32:30:2e:34:30:0a:32  30,80.00,20.40.2
00000540  30:31:35:30:31:32:38:31:34:30:33:33:31:2c:31:30  0150128140331,10
00000550  30:30:31:30:32:30:32:35:35:34:37:37:32:32:2c:35  00102025547722,5
00000560  30:30:30:33:31:2c:30:30:30:30:30:30:30:30:30:30  00031,0000000000
00000570  30:39:39:39:39:2c:32:30:31:35:30:30:30:30:33:31  09999,2015000031
00000580  2c:30:2e:30:30:2c:30:30:0a:32:30:31:35:30:31:32  ,0.00,00.2015012
00000590  38:31:34:30:33:33:31:2c:31:30:30:30:31:30:33:30  8140331,10001030
000005a0  30:34:34:34:37:30:32:35:2c:35:30:30:30:33:32:2c  04447025,500032,
000005b0  30:30:30:30:30:30:30:30:30:30:30:39:39:39:39:2c  000000000009999,
000005c0  32:30:31:35:30:30:30:30:33:32:2c:30:2e:30:30:2c  2015000032,0.00,
000005d0  30:30:0a:32:30:31:35:30:31:32:38:31:34:30:33:33  00.2015012814033
000005e0  31:2c:31:30:30:30:31:30:32:30:32:35:32:32:30:37  1,10001020252207
000005f0  38:33:2c:35:30:30:30:33:33:2c:30:30:30:30:30:30  83,500033,000000
00000600  30:30:30:30:30:39:39:39:39:2c:32:30:31:35:30:30  000009999,201500
00000610  30:30:33:33:2c:31:30:35:2e:30:30:2c:36:38:33:2e  0033,105.00,683.
00000620  35:30:0a:32:30:31:35:30:31:32:38:31:34:30:33:33  50.2015012814033
00000630  31:2c:31:30:30:30:31:30:32:30:32:31:37:32:35:32  1,10001020217252
00000640  38:30:2c:35:30:30:30:33:34:2c:30:30:30:30:30:30  80,500034,000000
00000650  30:30:30:30:30:39:39:39:39:2c:32:30:31:35:30:30  000009999,201500
00000660  30:30:33:34:2c:30:2e:30:30:2c:30:30:0a:32:30:31  0034,0.00,00.201
00000670  35:30:31:32:38:31:34:30:33:33:31:2c:31:30:30:30  50128140331,1000
00000680  31:30:32:30:32:30:33:36:37:33:31:36:2c:35:30:30  102020367316,500
00000690  30:33:35:2c:30:30:30:30:30:30:30:30:30:30:30:39  035,000000000009
000006a0  39:39:39:2c:32:30:31:35:30:30:30:30:33:35:2c:30  999,2015000035,0
000006b0  2e:30:30:2c:30:30:0a:32:30:31:35:30:31:32:38:31  .00,00.201501281
000006c0  34:30:33:33:31:2c:31:30:30:30:31:30:32:30:32:33  40331,1000102023
000006d0  39:37:36:35:30:31:2c:35:30:30:30:33:36:2c:30:30  976501,500036,00
000006e0  30:30:30:30:30:30:30:30:30:39:39:39:39:2c:32:30  0000000009999,20
000006f0  31:35:30:30:30:30:33:36:2c:37:2e:34:33:2c:32:2e  15000036,7.43,2.
00000700  39:35:0a:32:30:31:35:30:31:32:38:31:34:30:33:33  95.2015012814033
00000710  31:2c:31:30:30:30:31:30:32:30:32:31:34:36:39:37  1,10001020214697
00000720  37:32:2c:35:30:30:30:33:37:2c:30:30:30:30:30:30  72,500037,000000
00000730  30:30:30:30:30:39:39:39:39:2c:32:30:31:35:30:30  000009999,201500
00000740  30:30:33:37:2c:31:2e:30:30:2c:30:2e:39:38:0a:32  0037,1.00,0.98.2
00000750  30:31:35:30:31:32:38:31:34:30:33:33:31:2c:31:30  0150128140331,10
00000760  30:30:31:30:34:30:30:30:32:33:37:30:36:33:2c:35  00104000237063,5
00000770  30:30:30:33:38:2c:30:30:30:30:30:30:30:30:30:30  00038,0000000000
00000780  30:39:39:39:39:2c:32:30:31:35:30:30:30:30:33:38  09999,2015000038
00000790  2c:33:38:2e:32:39:2c:34:2e:37:38:0a:32:30:31:35  ,38.29,4.78.2015
000007a0  30:31:32:38:31:34:30:33:33:31:2c:31:30:30:30:31  0128140331,10001
000007b0  30:33:30:30:30:30:31:38:34:38:31:2c:35:30:30:30  03000018481,5000
000007c0  33:39:2c:30:30:30:30:30:30:30:30:30:30:30:39:39  39,0000000000099
000007d0  39:39:2c:32:30:31:35:30:30:30:30:33:39:2c:33:2e  99,2015000039,3.
000007e0  37:32:2c:37:39:34:2e:34:38:0a:32:30:31:35:30:31  72,794.48.201501
000007f0  32:38:31:34:30:33:33:31:2c:31:30:30:30:31:30:32  28140331,1000102
00000800  30:32:38:30:37:30:30:34:35:2c:35:30:30:30:34:30  028070045,500040
00000810  2c:30:30:30:30:30:30:30:30:30:30:30:39:39:39:39  ,000000000009999
00000820  2c:32:30:31:35:30:30:30:30:34:30:2c:31:35:2e:31  ,2015000040,15.1
00000830  35:2c:37:34:2e:36:37:0a                          5,74.67.

-> NET_SFTP_CLOSE (0s)
00000000  00:00:00:12:77:6f:64:53:66:74:70:46:69:6c:65:48  ....wodSftpFileH
00000010  61:6e:64:6c:65:30                                andle0

Thanks in Advance
Mark

**Comment by terrafrost** [comment]
Two things.

1. There's nothing wrong in the SFTP logs. The file is being uploaded successfully and then the file handle is being closed. The SSH2 logs would be more useful in this particular case. eg. `define('NET_SFTP_LOGGING', NET_SFTP_LOG_REALTIME)`.

2. You might have better luck with the latest Git version:

https://github.com/phpseclib/phpseclib/archive/master.zip

In particular, https://github.com/phpseclib/phpseclib/issues/502 may fix the issue.
