### ISSUE TITLE
Possible issue with AES

### ISSUE THREAD

**Issue by guiramadasa** [phpseclib/phpseclib#614]
I m not sure whether this issue is exactly with the phpseclib. It may be some issue with encoding differences etc. But I think its better to be checked by you.

What I do is creating some xml file, encrypting it using AES with phpseclib and saved as a text file. Then saved file later read, content decrypted by phpseclib.

Recently I noted read content of saved encrypted files are truncated. Always ending with particular character, more content is visible when file is opened with editor. With editor also if I copy paste, it doesnt copy beyond that character. That location I have marked in red in the attached image.

I have also attached file with raw contents, file with encrypted content.

Following is the code I ve used.

include('phpseclib0.3.5/Crypt/AES.php');
$cipher = new Crypt_AES(CRYPT_AES_MODE_ECB);
$cipher->setKey('hkekdoafmcjbmlpngopiiljn');

$value = $cipher->encrypt($value);

$fp = file_put_contents("/home/*************/".$uniqueid."_$cookieName.ext",$value);

For reading same file later I use file_get_contents()

If you have any idea why this could be happened, I do really appreciate if you could please do suggestions to overcome this issue. 

Thanks and Best Regards

Indunil

Original text,

<c><u>290</u><ldt>01-30-2015 06:56:20</ldt><ip>112.135.44.165</ip><e><rs><t>All</t><a id="99"><r>220</r><r>219</r><r>217</r><r>218</r><r>222</r><r>216</r><r>221</r></a><a id="79"><r>119</r><r>117</r><r>116</r><r>118</r><r>115</r></a><a id="110"><r>246</r><r>250</r><r>243</r><r>248</r><r>247</r><r>253</r><r>249</r><r>255</r><r>252</r><r>254</r><r>251</r><r>245</r><r>244</r></a><a id="75"><r>111</r><r>121</r><r>110</r></a><a id="109"><r>238</r><r>239</r><r>242</r><r>240</r><r>241</r></a></rs></e></c>

same above with htmlentities,

&lt;c&gt;&lt;u&gt;290&lt;/u&gt;&lt;ldt&gt;01-30-2015 06:56:20&lt;/ldt&gt;&lt;ip&gt;112.135.44.165&lt;/ip&gt;&lt;e&gt;&lt;rs&gt;&lt;t&gt;All&lt;/t&gt;&lt;a id=&quot;99&quot;&gt;&lt;r&gt;220&lt;/r&gt;&lt;r&gt;219&lt;/r&gt;&lt;r&gt;217&lt;/r&gt;&lt;r&gt;218&lt;/r&gt;&lt;r&gt;222&lt;/r&gt;&lt;r&gt;216&lt;/r&gt;&lt;r&gt;221&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;79&quot;&gt;&lt;r&gt;119&lt;/r&gt;&lt;r&gt;117&lt;/r&gt;&lt;r&gt;116&lt;/r&gt;&lt;r&gt;118&lt;/r&gt;&lt;r&gt;115&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;110&quot;&gt;&lt;r&gt;246&lt;/r&gt;&lt;r&gt;250&lt;/r&gt;&lt;r&gt;243&lt;/r&gt;&lt;r&gt;248&lt;/r&gt;&lt;r&gt;247&lt;/r&gt;&lt;r&gt;253&lt;/r&gt;&lt;r&gt;249&lt;/r&gt;&lt;r&gt;255&lt;/r&gt;&lt;r&gt;252&lt;/r&gt;&lt;r&gt;254&lt;/r&gt;&lt;r&gt;251&lt;/r&gt;&lt;r&gt;245&lt;/r&gt;&lt;r&gt;244&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;75&quot;&gt;&lt;r&gt;111&lt;/r&gt;&lt;r&gt;121&lt;/r&gt;&lt;r&gt;110&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;109&quot;&gt;&lt;r&gt;238&lt;/r&gt;&lt;r&gt;239&lt;/r&gt;&lt;r&gt;242&lt;/r&gt;&lt;r&gt;240&lt;/r&gt;&lt;r&gt;241&lt;/r&gt;&lt;/a&gt;&lt;/rs&gt;&lt;/e&gt;&lt;/c&gt;

After encryption

³† (More content is there (see image) but not getting copied to clipboard, similarly not read beyond that by file_get_contents)

![encrypted](https://cloud.githubusercontent.com/assets/9052857/5975772/323e468c-a8ab-11e4-9e67-aa21a4ab0019.jpg)

**Comment by bantu** [comment]
Please try the latest version of phpseclib and then the master branch.

**Comment by guiramadasa** [comment]
sure. Will do so and update this thread.

Thanks a lot for the prompt reply

**Comment by terrafrost** [comment]
```php
<?php
include('Crypt/AES.php');

$cipher = new Crypt_AES(CRYPT_AES_MODE_ECB);
$cipher->setKey('hkekdoafmcjbmlpngopiiljn');

$value = '<c><u>290</u><ldt>01-30-2015 06:56:20</ldt><ip>112.135.44.165</ip><e><rs><t>All</t><a id="99"><r>220</r><r>219</r><r>217</r><r>218</r><r>222</r><r>216</r><r>221</r></a><a id="79"><r>119</r><r>117</r><r>116</r><r>118</r><r>115</r></a><a id="110"><r>246</r><r>250</r><r>243</r><r>248</r><r>247</r><r>253</r><r>249</r><r>255</r><r>252</r><r>254</r><r>251</r><r>245</r><r>244</r></a><a id="75"><r>111</r><r>121</r><r>110</r></a><a id="109"><r>238</r><r>239</r><r>242</r><r>240</r><r>241</r></a></rs></e></c>';

echo '$value before encryption: ' . strlen($value) . "\r\n";

$value = $cipher->encrypt($value);

echo '$value after encryption: ' . strlen($value) . "\r\n";

file_put_contents('test.ext',$value);

echo 'file_get_contents: ' . strlen(file_get_contents('test.ext')) . "\r\n";
```

Here's what I get as the output:

$value before encryption: 503
$value after encryption: 512
file_get_contents: 512

You say "read content of saved encrypted files are truncated". How do you know they're being truncated?

> Always ending with particular character, more content is visible when file is opened with editor. With editor also if I copy paste, it doesnt copy beyond that character.

Are you using a text editor? If so then that's half the problem. Text editors are generally not good at editing binary data and behave unpredictably when you try.

If I opened a *.exe with Windows Notepad and saved it again do you think I'd get a *.exe that'd be runnable? I doubt it.

**Comment by terrafrost** [comment]
With HTML entities:

```php
<?php
include('Crypt/AES.php');

$cipher = new Crypt_AES(CRYPT_AES_MODE_ECB);
$cipher->setKey('hkekdoafmcjbmlpngopiiljn');

$value = '&lt;c&gt;&lt;u&gt;290&lt;/u&gt;&lt;ldt&gt;01-30-2015 06:56:20&lt;/ldt&gt;&lt;ip&gt;112.135.44.165&lt;/ip&gt;&lt;e&gt;&lt;rs&gt;&lt;t&gt;All&lt;/t&gt;&lt;a id=&quot;99&quot;&gt;&lt;r&gt;220&lt;/r&gt;&lt;r&gt;219&lt;/r&gt;&lt;r&gt;217&lt;/r&gt;&lt;r&gt;218&lt;/r&gt;&lt;r&gt;222&lt;/r&gt;&lt;r&gt;216&lt;/r&gt;&lt;r&gt;221&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;79&quot;&gt;&lt;r&gt;119&lt;/r&gt;&lt;r&gt;117&lt;/r&gt;&lt;r&gt;116&lt;/r&gt;&lt;r&gt;118&lt;/r&gt;&lt;r&gt;115&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;110&quot;&gt;&lt;r&gt;246&lt;/r&gt;&lt;r&gt;250&lt;/r&gt;&lt;r&gt;243&lt;/r&gt;&lt;r&gt;248&lt;/r&gt;&lt;r&gt;247&lt;/r&gt;&lt;r&gt;253&lt;/r&gt;&lt;r&gt;249&lt;/r&gt;&lt;r&gt;255&lt;/r&gt;&lt;r&gt;252&lt;/r&gt;&lt;r&gt;254&lt;/r&gt;&lt;r&gt;251&lt;/r&gt;&lt;r&gt;245&lt;/r&gt;&lt;r&gt;244&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;75&quot;&gt;&lt;r&gt;111&lt;/r&gt;&lt;r&gt;121&lt;/r&gt;&lt;r&gt;110&lt;/r&gt;&lt;/a&gt;&lt;a id=&quot;109&quot;&gt;&lt;r&gt;238&lt;/r&gt;&lt;r&gt;239&lt;/r&gt;&lt;r&gt;242&lt;/r&gt;&lt;r&gt;240&lt;/r&gt;&lt;r&gt;241&lt;/r&gt;&lt;/a&gt;&lt;/rs&gt;&lt;/e&gt;&lt;/c&gt;';

echo '$value before encryption: ' . strlen($value) . "\r\n";

$value = $cipher->encrypt($value);

echo '$value after encryption: ' . strlen($value) . "\r\n";

file_put_contents('test.ext',$value);

echo 'file_get_contents: ' . strlen(file_get_contents('test.ext')) . "\r\n";
```

My output:

$value before encryption: 1093
$value after encryption: 1104
file_get_contents: 1104

As before there's no truncation. Instead there's padding (which is to be expected). What do you get when you run this script?
