### ISSUE TITLE
Require 2.0.*@dev -> no matching package found

### ISSUE THREAD

**Issue by elfet** [phpseclib/phpseclib#615]
My project requires PhpSecLib:
```
"require": {
    "phpseclib/phpseclib": "2.0.*@dev"
}
```
When is clone project and run `composer install` every think is OK. But then i try to require my project in another project `composer require deployer/deployer:~3.0@dev` i got next error:
```
deployer/deployer v3.0.0-beta.1 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
```
What to do with this?

**Comment by GrahamCampbell** [comment]
Clear your composer cache.

**Comment by elfet** [comment]
Do next commands:
```
composer clear-cache
composer require deployer/deployer:~3.0@dev
```
Got error:
```
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - deployer/deployer v3.0.0-beta.2 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - deployer/deployer v3.0.0-beta.1 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - deployer/deployer v3.0.0-beta requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - Installation request for deployer/deployer ~3.0@dev -> satisfiable by deployer/deployer[v3.0.0-beta, v3.0.0-beta.1, v3.0.0-beta.2].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.
```

**Comment by bantu** [comment]
I do not know the cause of this, but belive this will go away when the 2.0 branch is created and aliases removed.

**Comment by GrahamCampbell** [comment]
I've seen this before actually. It's actually caused by an issue on packagist that was fixed on monday. You need need to make sure all non-existant branches are deleted from packagist, and then hit force update,

**Comment by bantu** [comment]
https://packagist.org/packages/phpseclib/phpseclib looks good to me as is.

**Comment by GrahamCampbell** [comment]
@bantu You still need to force update. Something's wrong internally. I had the same issue before. I contacted packagist and they fixed it.

**Comment by bantu** [comment]
@GrahamCampbell Okay. Forced update.

**Comment by bantu** [comment]
There is a real 2.0 branch now.

**Comment by elfet** [comment]
Got error, still:
```
 Problem 1
    - deployer/deployer v3.0.0-beta.2 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - deployer/deployer v3.0.0-beta.1 requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - deployer/deployer v3.0.0-beta requires phpseclib/phpseclib 2.0.*@dev -> no matching package found.
    - Installation request for deployer/deployer ~3.0@dev -> satisfiable by deployer/deployer[v3.0.0-beta, v3.0.0-beta.1, v3.0.0-beta.2].
```

**Comment by GrahamCampbell** [comment]
This looks like your minimum stability is wrong.

**Comment by elfet** [comment]
I'm requiring  phpseclib with @dev modifier: `2.0.*@dev`.

**Comment by GrahamCampbell** [comment]
Is that a requirement of deployer, and you're requiring deployer? If so, I don't think composer still respects the dev flags.

**Comment by bantu** [comment]
Try `2.0.x-dev@dev` ?

**Comment by bantu** [comment]
I guess deployer should have used that. But anyway, there will be a 2.0.0 soon.

**Comment by GrahamCampbell** [comment]
`2.0.x-dev@dev`. No. That would be totally wrong, lol.

**Comment by GrahamCampbell** [comment]
@bantu Just to prove this is not a bug, and does actually work fine:

https://travis-ci.org/GrahamTests/phpseclib-proof/builds/49863078.

See how the composer install for each version of php is working fine with https://github.com/GrahamTests/phpseclib-proof/blob/master/composer.json.

**Comment by GrahamCampbell** [comment]
```
$ travis_retry composer install --no-interaction --prefer-source
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing phpseclib/phpseclib (2.0.x-dev becb952)
    Cloning becb9524ff7fd1526797ba7f0b123db47b5f5418

Writing lock file
Generating autoload files
```

**Comment by elfet** [comment]
Please release soon!
