### ISSUE TITLE
Fatal error: Class 'phpseclib\Net\SSH2' not found in

### ISSUE THREAD

**Issue by danielepr** [phpseclib/phpseclib#622]
I have downloaded your package and saved into my zf2 project inside "vendor/phpseclib". So my structure is:
vendor/phpseclib/phpseclib/...
so we have vendor/phpseclib/phpseclib/crypt, vendor/phpseclib/phpseclib/File, etc.
then i installe composer but i think it did not work (windows 8.1, xampp, php 5.5).
so i edited autoload_namespaces in vendor folder:

<?php

// autoload_namespaces.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'Zend\\' => $vendorDir . '/zendframework/zendframework/library/',
    'ZendTest\\' => $vendorDir . '/zendframework/zendframework/tests/',
    'phpseclib\\' => $vendorDir .  '/phpseclib/',
);

then autoload_classmap.php:

<?php

// autoload_classmap.php generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array (
	'phpseclib\\' => $vendorDir . '/phpseclib/',
);

In my Application module I edited Module.php

    public function getAutoloaderConfig()
    {
        return array(
			'Zend\Loader\ClassMapAutoloader' => array(
				__DIR__ . '/../../vendor/composer/autoload_classmap.php',
			),         
            'Zend\Loader\StandardAutoloader' => array(
                'namespaces' => array(
                    __NAMESPACE__ => __DIR__ . '/src/' . __NAMESPACE__,
                ),
            ),
        );
    }
    
Then I was sure that in init_autoloader.php of my project I have:

// Composer autoloading
if (file_exists('vendor/autoload.php')) {
    $loader = include 'vendor/autoload.php';
}

Then i tried to call Net_SSH2 from other controllers, doing so:

use phpseclib\Net;
use phpseclib\Net\SSH2;

		$ssh = new \phpseclib\Net\SSH2('192.168.2.10');	
		if (!$ssh->login('pi', 'raspberry')) {
			echo 'Login Failed';
			exit;
		}
		echo "I am in";

But I get a fatal error : Class 'phpseclib\Net\SSH2' not found in

Thanks for your support

Daniele Protti

**Comment by bantu** [comment]
I'd say this problem is outside of the scope of this problem. I would suggest you read up on how to correctly use composer together with zf2.

**Comment by terrafrost** [comment]
I think http://stackoverflow.com/a/28465739/569976 answers your question?

**Comment by bantu** [comment]
I am closing this because you also posted on another platform.
