### ISSUE TITLE
PHP Fatal error: Cannot access self:: when no class scope is active

### ISSUE THREAD

**Issue by sapzxc** [phpseclib/phpseclib#632]
In composer requires:

```
"require": {
        "php": ">=5.3.3"
    },
```

But I have OSX:
PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies

And have errors in some situations:

*PHP Fatal error:  Cannot access self:: when no class scope is active in /dev/vendor/phpseclib/phpseclib/phpseclib/Crypt/Base.php(1958) : runtime-created function on line 16*

Use case:
```
		$ssh = new \phpseclib\Net\SSH2($ip, $port, 3);
		if(!$ssh->login($user,$pass))
		{
			return $ssh;
		}
		$res = $ssh->exec('uname -a');

		$ssh->disconnect();
```

Errors happens in random situations.

**Comment by sapzxc** [comment]
I found same issue:
http://stackoverflow.com/questions/8243873/how-can-i-access-class-constants-using-self-inside-an-anonymous-function-def

And then made search by Crypt folder and found only one "self::" place used in string (DES.php):
```
$init_encrypt = '$ke = $self->keys[self::ENCRYPT];';
$init_decrypt = '$kd = $self->keys[self::DECRYPT];';
```

Now changed to 
```
$init_encrypt = '$ke = $self->keys[$self::ENCRYPT];';
$init_decrypt = '$kd = $self->keys[$self::DECRYPT];';
```

Now testing, but looks like this fixed.

**Comment by bantu** [comment]
"$self::" doesn't sounds correct, though. Constants are supposed to be accessed statically. I am not sure whether non-static access works properly in all PHP versions. So, besides passing $self, which is an instance, we might just want to also pass $class which is the class name of $self. Then we can do $class::ENCRYPT.

**Comment by sapzxc** [comment]
"$init_encription" used in "_createInlineCryptFunction"

and there we see

return create_function('$_action, **&$self**, $_text', $init_crypt . 'if ($_action == "encrypt") { ' . $encrypt . ' } else { ' . $decrypt . ' }');

About access to class constants:
http://php.net/manual/en/language.oop5.constants.php

> As of PHP 5.3.0, it's possible to reference the class using a variable. The variable's value can not be a keyword (e.g. self, parent and static).

So var $self proper name for fix bug.

**Comment by bantu** [comment]
@sapzxc Indeed. Good point. This might affect the 1.0 branch too, however.

**Comment by terrafrost** [comment]
It's not an issue in 1.0 because 1.0 uses `define` to do constants:

https://github.com/phpseclib/phpseclib/blob/0efae5a91e90e6027b95874e5242f5ea8eaa5754/phpseclib/Crypt/DES.php#L1411

2.0 does uses class-specific const's.

Anyway, reproducing the issue is a bit tricky but I managed to do it with this:

```php
<?php
include('autoloader.php'); 

$loader = new \Composer\Autoload\ClassLoader(); 
$loader->addPsr4('phpseclib\\', __DIR__ . '\\phpseclib'); 
$loader->register();

use \phpseclib\Crypt\DES; 

$plaintext = ''; 
for ($i = 0; $i < 1024*1024; $i++) { 
    $plaintext.= chr(mt_rand(0, 255)); 
} 

$start = microtime(true); 

define('CRYPT_DES_MODE', DES::ENGINE_INTERNAL); 
$des = new DES();
$funcs = &$des->_getLambdaFunctions();
$funcs = range(0, 10);
$des->setKey('abcdefghijklmnop'); 
$des->encrypt($plaintext); 

$elapsed = microtime(true) - $start; 
echo "Elapsed time: $elapsed";
```

The reason the range(0, 10) thing is necessary is because of this (from DES.php):

```php
        // Generation of a uniqe hash for our generated code
        switch (true) {
            case $gen_hi_opt_code:
                // For hi-optimized code, we create for each combination of
                // $mode, $des_rounds and $this->key its own encrypt/decrypt function.
                $code_hash = md5(str_pad("DES, $des_rounds, {$this->mode}, ", 32, "\0") . $this->key);
                break;
            default:
                // After max 10 hi-optimized functions, we create generic
                // (still very fast.. but not ultra) functions for each $mode/$des_rounds
                // Currently 2 * 5 generic functions will be then max. possible.
                $code_hash = "DES, $des_rounds, {$this->mode}";
        }
```

I'll submit a PR for this shortly.

**Comment by kravco** [comment]
This issue has been fixed two years ago, but bad merge introduced it again
