### ISSUE TITLE
PHPSeclib demanding large memory chunk while running a command? 

### ISSUE THREAD

**Issue by AbhinavBansal** [phpseclib/phpseclib#635]
Hi,

On successful ssh to a machine, i get an error when I run a command through PHP Script:
SHARED MEMORY: cannot get  67108864 bytes: No space left on device.
The same command runs fine when executed via manual ssh

Why would PHPSecLib need 64MB (67108864) of space? 
Where does this value come from? Can it be reduced?

**Comment by terrafrost** [comment]
Sorry about not responding to this earlier - I guess I just missed it.

Anyway, what command are you trying to run?

Certainly there are some commands that could cause phpseclib to run out of memory. eg. `dd if=/dev/zero of=file_1GB bs=1024 count=1000; cat file_1GB`.
