### ISSUE TITLE
"Premature end of script headers" while executing get() with Net_SFTP

### ISSUE THREAD

**Issue by jackthesmack** [phpseclib/phpseclib#646]
**Version:** phpseclib 0.3.10

**Description:** I am getting this error when I try downloading a file, sometimes. When I watch the directory, I can see the file downloading. If the file is small, it completes successfully. But if it's larger than a few MBs, the script ends and this is the only error that appears. Here is a snippet of my code:

	echo "<p>Connecting via SFTP</p>";
	$conn_id = new Net_SFTP($ftp_server ,2222);
	$conn_id->setTimeout(60*60);

	if (!$conn_id->login($ftp_user_name, $ftp_user_pass))
		exit('Login Failed');
	else if($testing)
		echo "<p>Connected to ".$conn_id->getServerIdentification()." </p>";
	// try to download $server_file and save to $local_file
	if($testing) echo "<p>Downloading $server_file</p>";
	$conn_id->get($server_file, $local_file);
	if($testing) echo "<p>Downloaded $server_file</p>";

This the resulting text displayed on screen:

>Connecting via SFTP
>
>Connected to SSH-2.0-CrushFTPSSHD
>
>Downloading logs/dataport/dl/SAVED_EXPORT_ZXQ4WRZ7VV.xml

Then the page stops loading. This file I downloaded, for example, reached 9MB before the script terminated.

**Comment by terrafrost** [comment]
Does http://stackoverflow.com/a/4336957/569976 fix the issue for you?
