### ISSUE TITLE
loadCsr returns false when processing CSR generated using Win2k12R2 IIS Manager

### ISSUE THREAD

**Issue by Fuitad** [phpseclib/phpseclib#651]
This could be related to #602. I've hit another problem where X509 is unable to parse CSR files that were created using Win2k12R2 IIS Manager "Create Certificate Request" feature.

I emailed a few examples to @terrafrost.

**Comment by terrafrost** [comment]
Got the email - thanks! I'll try to take a look this weekend or next as time permits (I have some other stuff I need to do this weekend so idk for sure that I can do it this weekend but I'll try!)

**Comment by terrafrost** [comment]
Sorry for the delay - I had intended to look at this this weekend but wound up having to work through the whole weekend meh :(

Anyway, here's the fix:

```
#
#-----[ OPEN ]------------------------------------------
#
File/ASN1.php
#
#-----[ FIND ]------------------------------------------
#
                return $i < $n? null: $map;
#
#-----[ REPLACE WITH ]----------------------------------
#
                return $map;
```

More info:

http://stackoverflow.com/a/28665775/569976

It's something I'm tentatively thinking I'll address when I start refactoring the X.509 parsing routines.

Thanks!

**Comment by Fuitad** [comment]
Sorry for taking so long to get back. It's working with that change.
