### ISSUE TITLE
Saop Exception / SSL operation failed after $rsa->sign() in PHP 5.6.7

### ISSUE THREAD

**Issue by nforced** [phpseclib/phpseclib#654]
I use SoapClient in this manner:

```
$contextOptions = array(
            'ssl' => array(
                'verify_peer'   => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
            ),
            'http' => array(
                'timeout' => 5 //seconds
            )
 );

 //create stream context
$stream_context = stream_context_create($contextOptions);

//create client instance (over HTTPS)
$client = new SoapClient(WSDL_LOCATION, array(
            'cache_wsdl'  => WSDL_CACHE_NONE,
            'exceptions' => 1,
            'trace' => 1,
            'stream_context' => $stream_context,
            'soap_version'=> SOAP_1_2,
            'connection_timeout' => 5 //seconds
));//SoapClient

//got no errors
$x = $client->methodX($args);

//require phpseclib
require_once('phpseclib/Crypt/RSA.php');

$rsa = new Crypt_RSA();
$rsa->loadKey(AUTH_PRIVATE_KEY_PKCS1); //as string
$rsa->setPrivateKeyFormat(CRYPT_RSA_PRIVATE_FORMAT_PKCS1);
$rsa->setSignatureMode(CRYPT_RSA_SIGNATURE_PKCS1);
$rsa->setHash('md5');
$rsa->setMGFHash('md5');

//sign
$signature =  $rsa->sign($DataToSign);

//errors start here
$z = $client->methodZ($args);
```

Now after upgrade to PHP 5.6.7 I get this sort of errors:
```
PHP Warning:  SoapClient::__doRequest(): SSL operation failed with code 1. OpenSSL Error messages:
error:0906D06C:PEM routines:PEM_read_bio:no start line
error:0906D06C:PEM routines:PEM_read_bio:no start line
error:0906D06C:PEM routines:PEM_read_bio:no start line
error:0906D06C:PEM routines:PEM_read_bio:no start line
soap exception: Message: Error Fetching http headers
```
the same code was working just fine on PHP 5.6.6 and works fine on 5.6.7 if I don't $rsa->sign() prior the $client->methodZ() call.

I found a workaround for now which is basically to create a new instance of SoapClient after $rsa->sign() which maybe somehow affects my existing SoapClient instance.

I also looked at PHP 5.6.7 release notes here http://php.net/ChangeLog-5.php#5.6.7 and saw many OpenSSL bugs fixed (11) in this release so I guess something has been changed and caused this behaviour.

**Comment by terrafrost** [comment]
I am unable to reproduce this on PHP 5.6.7 on Windows 7. My code:

```php
<?php
$contextOptions = array(
    'ssl' => array(
        'verify_peer'   => false,
        'verify_peer_name' => false,
        'allow_self_signed' => true
    ),
    'http' => array(
        'timeout' => 5 //seconds
    )
);
    
//create stream context
$stream_context = stream_context_create($contextOptions);
    
//create client instance (over HTTPS)
$client = new SoapClient('https://fxtop.com/dev/service.wsdl', array(
    'cache_wsdl'  => WSDL_CACHE_NONE,
    'exceptions' => 1,
    'trace' => 1,
    'stream_context' => $stream_context,
    'soap_version'=> SOAP_1_1,
    'connection_timeout' => 5 //seconds
));//SoapClient

require_once('phpseclib/Crypt/RSA.php');

$rsa = new Crypt_RSA();
$rsa->loadKey(AUTH_PRIVATE_KEY_PKCS1); //as string
$rsa->setPrivateKeyFormat(CRYPT_RSA_PRIVATE_FORMAT_PKCS1);
$rsa->setSignatureMode(CRYPT_RSA_SIGNATURE_PKCS1);
$rsa->setHash('md5');
$rsa->setMGFHash('md5');

//sign
$signature =  $rsa->sign($DataToSign);

$args = array('Lang' => 'US', 'Isocode' => 'USD');
$z = $client->DescCurrency($args);
var_dump($z);
```
Just finding a free SOAP SSL service was a bit of a PITA but, regardless, given my inability to reproduce this issue if you want further diagnostics you'll need to give me SSH access or something to a box that can reproduce this problem. Or give me an Ansible playbook that can reproduce this issue or something.

**Comment by jonxiest** [comment]
I'm not using phpseclib and I'm getting exactly the same kind of error with PHP SoapClient after i upgraded from php version 5.6.6 -> 5.6.7.

I'm using the SoapClient instance as singleton, so I guess I'm also gonna try creating a new instance for every request, and try if it works.

**Comment by nforced** [comment]
Right, it turns out that it has to do with "timeout" and "connection_timeout" but I haven't got the time to investigate further. This can help explain some of the aspects http://stackoverflow.com/questions/4824799/soapfault-exception-http-error-fetching-http-headers

**Comment by jonxiest** [comment]
Setting the 'keep_alive' => false, in SoapClient constructor params, seemed to fix the errors for me.

**Comment by electric** [comment]
Just wanted to say that thanks to this thread I solved an issue that had been plaguing me for 4 days straight. 'keep_alive' => false was the fix for me also, as I was getting the "error:0906D06C:PEM routines:PEM_read_bio:no start line" error.

Cheers.
