### ISSUE TITLE
Upgrade guide?

### ISSUE THREAD

**Issue by a432511** [phpseclib/phpseclib#665]
Hello,

I see some namespace and class name changes in the latest revision on master. Can you provide an upgrade guide? I am currently setting the include path to the folder where I have stored the library and then including RSA.php. After pulling the latest revision (and changing the constructors from Crypt_RSA() to RSA()), it appears that the namespaces are causing problems.

The first issue I ran into was that even though RSA.php was included, using the constructor directly did not work. It requires the full namespace. After resolving that, it throws an error that BigInteger.php could not be found on line 513 of RSA.php.

I'm sure its just a matter of configuration, but there doesn't appear to be a guide to get the latest version up and running properly.

Thanks!

**Comment by terrafrost** [comment]
You need to use a PSR-4 style auto loader. eg.

```
<?php
// https://raw.githubusercontent.com/composer/composer/master/src/Composer/Autoload/ClassLoader.php

include('autoloader.php');

$loader = new \Composer\Autoload\ClassLoader();
$loader->addPsr4('phpseclib\\', __DIR__.'/phpseclib');
$loader->register();

use \phpseclib\Crypt\RSA;

$rsa = new RSA();
```

Beyond that there isn't really a whole heck of a lot to it. If you want to use constants they're now (mostly) like `RSA::ENCRYPTION_OAEP` etc.

**Comment by a432511** [comment]
I'll give it a shot. Thank you!
