### ISSUE TITLE
SHA512 OAEP - Very Intermittant Hash Incorrect

### ISSUE THREAD

**Issue by a432511** [phpseclib/phpseclib#666]
I was reluctant to file this issue because it has been so hard to reproduce, but I have run out of possible explanations. 

I am using phpseclib to perform RSA OAEP encryption using SHA512 as the MGF and Hash. This encryption is performed using an xml public key which is stored in a database (varchar) on a server. The key is 4096bit. 

```php
$rsaCrypt = new Crypt_RSA();
$rsaCrypt->setHash('sha512');
$rsaCrypt->setMGFHash('sha512');
$rsaCrypt->setEncryptionMode(CRYPT_RSA_ENCRYPTION_OAEP);
// Load the public key into that class
$rsaCrypt->loadkey("XML PUB KEY GOES HERE", CRYPT_RSA_PUBLIC_FORMAT_XML);
return $rsaCrypt->encrypt(DATA);
```

This works 95% (if not more) of the time. However, after a random amount of time that the public key is in existence, it simply stops working - as in, the above code produces a cipher (no errors during encryption) with an invalid hash. How do I know this? I debugged and recorded the resulting cipher on two different client devices (iOS and Windows) and watched the decryption error out on both citing an invalid hash.

I went so far as to write a standalone utility to test the cipher bytes and private key as a test. Still no luck. BouncyCastle's library returns a "data hash wrong" error and the iOS error is similar. 

So, as you can see, my process of elimination has lead me to suspect the phpseclib library is producing the incorrect hash. I am running phpseclib 0835389b5a2590efcbb5af0c00a5617f440aa9a3 and it was occurring as far back as 3 months before that commit.

The very very confusing part is why does that public key just stop working after a given period of time? It seems once the first failure occurs, every subsequent attempt to encrypt using the same public key produces a bad cipher....

Thanks in advance.

**Comment by terrafrost** [comment]
First, you do have some redundancies in your code. eg.

```php
$rsaCrypt->setEncryptionMode(CRYPT_RSA_ENCRYPTION_OAEP);
```
That's the default encryption mode as is so there's no need to explicitely specify it. Also,

```php
$rsaCrypt->loadkey("XML PUB KEY GOES HERE", CRYPT_RSA_PUBLIC_FORMAT_XML);
```
phpseclib doesn't need that CRYPT_RSA_PUBLIC_FORMAT_XML part to load XML keys.

In any event, I took your code and ran it in a for loop 1,000 times for a 4092-bit and didn't have any issues:

```php
include('Crypt/RSA.php');
include('Math/BigInteger.php');

//define('MATH_BIGINTEGER_MODE', MATH_BIGINTEGER_MODE_BCMATH);
//define('MATH_BIGINTEGER_OPENSSL_ENABLED', false);

for ($i = 0; $i < 1000; $i++) {
    $rsaCrypt = new Crypt_RSA();
    $rsaCrypt->setHash('sha512');
    $rsaCrypt->setMGFHash('sha512');
    $rsaCrypt->setEncryptionMode(CRYPT_RSA_ENCRYPTION_OAEP);
    // Load the public key into that class

    $rsaCrypt->loadkey('<RSAKeyValue>
  <Modulus>w3GYJ3MaMMPjsBTsg9imhrNO3WtL3kkwHuokza6fdI3zxJkzfzqe+49q/3u8HWyrzNWY1
Ox73/Hu36VcCBEFetA2wm6acLqL1tcptrAuub8M7XL/u7Reqn9wv6HQ37dEeRRPwd6dSb9JPXpVAmqgq
AOa19KSwffI1JnKgvsbeT4O6SiHpkFWsVmp8TOUkaGZWWM4+dCQlwflHnJFBOu8va2WkhAwg6JxbBdha
dPteA7B+z2ahhrl1w8VdGi+FPIDM1lxFwK54BR7ddYfNB2iWF+337YUBYcL5K3GDOSajsLWWkNuXrIJa
ScbwryGg2IwjyvVEUHdpdqApOU5v9l7DWBVQFNnLBVQ8teUC2gf/z3Yhs+gF7HvCn+1CTcO/uh7nuc0U
M4m11+BQ8gBKmvXizwNzpMmlteqL7DpjgvturuPt5eE2eesL8ADjlJcbgffnUto7Y2BgaDlCgdVYS5Yr
Uf6rBJcRWapdJmisLKo9zy1t58TQ/7DZdpcjKC38D2tT1jzZZlrPduGuGbZbjLLbvxYWoNHcJor6H33L
xYu8rD8PAX7cQc+6tgTkcBrUd2ACJo1C8P1REnDm7c0UO4Cs1h6AEsPjKxoR1m3Ktu1VH29jYEic/iiv
dsewLPBbkv1XsQcmQMv02vf/7d412Ukx9yngIzBFBIrahiv1KpqfTU=</Modulus>
  <Exponent>AQAB</Exponent>
</RSAKeyValue>', CRYPT_RSA_PUBLIC_FORMAT_XML);
    $ciphertext = $rsaCrypt->encrypt('zzz');

    $rsaCrypt->loadkey('<RSAKeyValue>
  <Modulus>w3GYJ3MaMMPjsBTsg9imhrNO3WtL3kkwHuokza6fdI3zxJkzfzqe+49q/3u8HWyrzNWY1
Ox73/Hu36VcCBEFetA2wm6acLqL1tcptrAuub8M7XL/u7Reqn9wv6HQ37dEeRRPwd6dSb9JPXpVAmqgq
AOa19KSwffI1JnKgvsbeT4O6SiHpkFWsVmp8TOUkaGZWWM4+dCQlwflHnJFBOu8va2WkhAwg6JxbBdha
dPteA7B+z2ahhrl1w8VdGi+FPIDM1lxFwK54BR7ddYfNB2iWF+337YUBYcL5K3GDOSajsLWWkNuXrIJa
ScbwryGg2IwjyvVEUHdpdqApOU5v9l7DWBVQFNnLBVQ8teUC2gf/z3Yhs+gF7HvCn+1CTcO/uh7nuc0U
M4m11+BQ8gBKmvXizwNzpMmlteqL7DpjgvturuPt5eE2eesL8ADjlJcbgffnUto7Y2BgaDlCgdVYS5Yr
Uf6rBJcRWapdJmisLKo9zy1t58TQ/7DZdpcjKC38D2tT1jzZZlrPduGuGbZbjLLbvxYWoNHcJor6H33L
xYu8rD8PAX7cQc+6tgTkcBrUd2ACJo1C8P1REnDm7c0UO4Cs1h6AEsPjKxoR1m3Ktu1VH29jYEic/iiv
dsewLPBbkv1XsQcmQMv02vf/7d412Ukx9yngIzBFBIrahiv1KpqfTU=</Modulus>
  <Exponent>AQAB</Exponent>
  <P>9il3BtsAomII/xBu3qpAbcUoAmjGiWzDiy+vO6Uojaa3ogRtMOhmbJ8G8DjDWyt0fVTl3CzcSma
eFkpQu71h2/GmTE0/Pmy2n/wPVZ143bSj/v+IIZUmY8N1Y1AxOZljGinatAKBQ5LoW7xtDikSZL7NZeS
t4SuAMufOLCtZP9NDCy8McQCQMHQC7Bi4elVjw1IhuYmGtCD3iQ1BYgWX2Eb7tV5mzvgTneAa9wx7frU
m0xHHUTp8CULpbk/GgSAEGj/i/EJSge//kN0S31lW+hFbxWfI55hAWmvArzn1LESvOONSe360NqY6JCw
aLjDg6Z/a2UXaOzb+bOaaNz+nwQ==</P>
  <Q>y0E4aL8p5o/pQK11avBc1I9Gfoas9+lw35/+uSozS+eotoI9jLntSa4HY6PO46OJcoF8slFy2l4
VjFeYlEZ71B5bPGz/bOb1MGOBjeGGtioHfnLC+cs6+5UozKE0xKDvKpOzzteVGuDrKdPwhSDoH/YofuU
8ohA/BbACyFvsCyT77R/cy8C/TZCQgwZY25uHkJy1N/DRP4s/qPr0oexfzGHdKwITNJ7yPQhfZ9IPhzz
PwMlcDj1OKpFRmqoLjUrexrBnLwn5gKjyhgj2TYPiTpxn3ANH2Mpna4sXmLalaiC0+JHSvC+wsZNRKEu
9VdQAiGpOO/nlL+VIganmBFdSdQ==</Q>
  <DP>C3mNWd11nxwwzSsH8AtBq5xILCyULK3MQ726Tm55gHjoEH5iVKhQtfmHykTrHmHdMUZ23JeewT
0dW26lasr+N9GA7gefzholPTnzwQrxKmyURHvG7cHVI0tmOnXvhX7X9s1Cq6d+PRcpC7Wx47oYaGfYjU
pmrJtpg3X4z2hJ5cbEVk4gJ1heYFPYGwdf+hvm5aD7f3mgtN7gixv6E0ateGB+tUqsQjOgPnjG6QNE8n
ghUi9++hNe2tOqrAC+ASDr8AlQXG//Bp2YbTlQ+uZgPpH2lDItVFZtkYl6VvC9tA2TmXRHUQhsACwpg6
wmoEaZBWr1ObGe5am/nHX3dGHcQQ==</DP>
  <DQ>JkSSTU5ooitIPFAsQkUdBTwwhpPurwJ5qPDjsZMbc1gbcLlWw08iOPQWGhF2W2+n6jIs+xnQqQ
J7xh+b75bRq59HiDnxYVyen0ys0Ly8c0G4hXsv8H3uDf4IX3aei8LNJNQIT5JRVW0xeX+Y0kfezF25RC
L+5nhulTCNZZHBAFwnPn74QDh7DCyCuNiSFE7VGEoY6H5jtzYNd1BAjNgHNWDblkRev1KJwyn3ZIGtQM
YXS3Hd7iRmuicAGUGYyTJmfTwrQTT8j9e/SbMYRIHnMuvJtie7+DorfJkEiVEiFbgwungiGCJWfyiAaD
jSXf17WDPDpREosHrXyunlD74tHQ==</DQ>
  <InverseQ>v8qZA4ZwNDGccNFdZdLrvtuktHYl3d6jDuQFTm5Nnn6dwEbI8uWimlQC8TlgxCZzSJQu
yIhQMCUhZoZlcDydvE342/HDUAsmjp3LYxuwABRn5p33PnK5x1a0S0R/HPDO4zzMQ17azEvJNYV5M89O
EAu5LvDduCGgmBkaREsMYYi9RPNoiIseHOM2R5t4d2QwfMhW0HJUG3RI6Xt47wqXHDTN6xRM+3Uian3+
oQj39YV5CJHgobEwdC8kdklVU15vLvzgIsELmid6rjZC/e9LYo9QY6dKQMohxPePklpsYwnSODm12oGT
iTUxeTqq6YpcUcHLyqHPGEmaH58CvZSUKg==</InverseQ>
  <D>oAuOgIeWI+bVteR8hb9NJrMA2vq5Rw8B098DQldEBmsT+qNF82Lqu6+G/C20LxhFW1hybbI2An4
YkZXU1lox9Y85uGBgIf3w836AjzSZHswfZvasCma6ur3fc12sMPbfoJMMeQK2JKT68dgScwckBlHlY+T
w/tvM3qQNnNLKfa9fAHmLE48f0d1N99G4UMVXUUaaap/rN3JkolkKwevVRDI5QeT2BWVpog1HXSUJqi3
TlcytlDHEkyar+Aap2XcRPeR5YlF+Ksw7CZTNOp0ly16esRhmLtyW1a2jp/0vv8Y3R/U+FVePs0cuSXq
eYEpw310Sfq5ENkPG4sE/WCZcx3hcN0gEIcd0KIUt/hzVNxaC5nDR37JYBb9YzjFi8UEQ8BBgjMOr8DE
IKtmv+dmuzh5iqBbsQsJxf/QloPWsnbGD5G8aZKK3DVuZG7jEpWVjPJ/f3si87bAfsFPScOjHgtoVGvb
gsWj0mbJZCy5+V07Kd9n3pMounDqOYuyvcd2MfhvVtm0fTq3OHD2so8zLN9MajH5ByHTXzjUTPW08+Iv
wYRlzW+Hng/H5bo0YfeAYXBRNXaukwOvjeXVTO4AXzsOExtodxv8HZJdxsDaAi08ZXcPQZfSzLiIm6wI
XILbmb1fWvlEg7YHrNhxF1kPhHouhyvV2t/6Ru8cLntWeaQE=</D>
</RSAKeyValue>');
    $rsaCrypt->decrypt($ciphertext);
}

echo 'all done!';
```
Given my inability to reproduce it it's hard to say anything. Maybe you can post your phpinfo()? This test was conducted under GMP. BCMath and internal could, in theory, produce different results (altho the unit tests make me think that's unlikely), as could, potentially, the presence of OpenSSL. There's also Crypt_Hash to consider, too, but the phpinfo() will provide me insight into all of that.

Also, it'd be helpful if you could post the key that's causing the problems.

**Comment by a432511** [comment]
Thank you for running your tests. I appreciate it. 

The interesting thing is that once a key stops working (even though the public key has not changed), it never works again. So it seems incredibly unlikely that the issue is actually in phpseclib because if it were, the issue would present itself randomly with a given key, rather than all of a sudden and in perpetuity. 

Also, this issue is not exclusive to a single public key. Many public keys have exhibited the issue.

What I am beginning to think is that I may have some sort of corruption of the private key on the client side.

Some of the phpinfo:

Openssl: 1.0.1f 1/6/2014
BCMath support: enabled
bcmath.scale: 0, 0
PHP: php-fpm

I will keep digging as well. 

Cheers,

Adam

**Comment by bantu** [comment]
@a432511 Hey Adam, any updates?
