### ISSUE TITLE
Getting Error ANSI on line 434

### ISSUE THREAD

**Issue by cybermailer** [phpseclib/phpseclib#667]
Notice: ] unsupported in /www/htdocs/***/***/includes/phpseclib/File/ANSI.php on line 434

I can see the stream from the server but i'm getting an ERROR.

I'm using this script:
       set_include_path(get_include_path() . PATH_SEPARATOR . '../../includes/phpseclib');
	include('Net/SSH2.php');
	include('File/ANSI.php');

	//Connection data
	$host = "";
	$username = "";
	$password = "";
	
	$ssh = new Net_SSH2($host);
	
	//Check Connection successfull
	if (!$ssh->login($username, $password)) {
		exit('Login Failed');
	}

	$ansi = new File_ANSI();

        $ssh->write("ls\n");
	$ssh->setTimeout(2);
	
	$ansi->appendString($ssh->read());
        echo $ansi->getScreen();

**Comment by terrafrost** [comment]
Instead of passing the output of `$ssh->read()` through `$ansi->appendString()` can you post the base64 encoded output of `$ssh->read()`? ie. `base64_encode`.

Thanks!

**Comment by cybermailer** [comment]
the problem occurs if i want the output ie. when i want the output of htop. It dont occurs with the output of top.

Problems with htop (same script htop as program to be streamed instead of top):

Notice: (B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: )0[ unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [?7h unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs/includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [69D unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [56D unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [35D unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [35D unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [2B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

Notice: [1B unsupported in /www/htdocs//includes/phpseclib/File/ANSI.php on line 434

and many more ...



THE OUPUT OF base64_encode:

HOW to use base64 ???

Original:

//GET HTOP
	$ssh->enablePTY();
	$ssh->exec('htop; ');
	$ssh->setTimeout(2);
	$ansi->appendString($ssh->read());
	echo $ansi->getHistory();

**Comment by terrafrost** [comment]
http://pastebin.com/3NfBcF3B is a marginal improvement but to really make this handle htop I'm gonna need to spend a good amount of time fundamentally changing the way it works.

**Comment by terrafrost** [comment]
Sorry for the delay. Anyway, I just made a commit to my clone of this repo that should give you much more accurate ANSI decoding:

https://github.com/terrafrost/phpseclib/commit/cc0420b36b3b03de7dd75f44ef263adaf49b0e06

I need to add a unit test and change elements of it for the 2.0 / php5 branch but in the mean time you can use that version on the 1.0 / 0.3.10 / php4 branch.

Thanks!

**Comment by terrafrost** [comment]
Fixed by #689
