### ISSUE TITLE
PHP Warning:  unpack(): Type N: not enough input, need 4, have 1

### ISSUE THREAD

**Issue by tburschka** [phpseclib/phpseclib#669]
I have following problem in my [project](https://github.com/tburschka/connect)

	PHP Warning:  unpack(): Type N: not enough input, need 4, have 1 in phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2826
	PHP Stack trace:
	PHP   1. {main}() /home/torsten/Projekte/connect/connect.phar:0
	PHP   2. require() /home/torsten/Projekte/connect/connect.phar:10
	PHP   3. Symfony\Component\Console\Application->run() phar:///home/torsten/Projekte/connect/connect.phar/src/bootstrap.php:17
	PHP   4. Symfony\Component\Console\Application->doRun() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
	PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
	PHP   6. Symfony\Component\Console\Command\Command->run() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
	PHP   7. Connect\Command\SshCommand->execute() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
	PHP   8. Net_SSH2->exec() phar:///home/torsten/Projekte/connect/connect.phar/src/Connect/Command/SshCommand.php:35
	PHP   9. Net_SSH2->_get_channel_packet() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2300
	PHP  10. Net_SSH2->_get_binary_packet() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2974
	PHP  11. Net_SSH2->_filter() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2771
	PHP  12. unpack() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2826
	PHP Warning:  extract() expects parameter 1 to be array, boolean given in phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2826
	PHP Stack trace:
	PHP   1. {main}() /home/torsten/Projekte/connect/connect.phar:0
	PHP   2. require() /home/torsten/Projekte/connect/connect.phar:10
	PHP   3. Symfony\Component\Console\Application->run() phar:///home/torsten/Projekte/connect/connect.phar/src/bootstrap.php:17
	PHP   4. Symfony\Component\Console\Application->doRun() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
	PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
	PHP   6. Symfony\Component\Console\Command\Command->run() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
	PHP   7. Connect\Command\SshCommand->execute() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
	PHP   8. Net_SSH2->exec() phar:///home/torsten/Projekte/connect/connect.phar/src/Connect/Command/SshCommand.php:35
	PHP   9. Net_SSH2->_get_channel_packet() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2300
	PHP  10. Net_SSH2->_get_binary_packet() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2974
	PHP  11. Net_SSH2->_filter() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2771
	PHP  12. extract() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2826
	PHP Notice:  Undefined variable: length in phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 2827
	PHP Stack trace:
	PHP   1. {main}() /home/torsten/Projekte/connect/connect.phar:0
	PHP   2. require() /home/torsten/Projekte/connect/connect.phar:10
	PHP   3. Symfony\Component\Console\Application->run() phar:///home/torsten/Projekte/connect/connect.phar/src/bootstrap.php:17
	PHP   4. Symfony\Component\Console\Application->doRun() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:126
	PHP   5. Symfony\Component\Console\Application->doRunCommand() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:195
	PHP   6. Symfony\Component\Console\Command\Command->run() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Application.php:874
	PHP   7. Connect\Command\SshCommand->execute() phar:///home/torsten/Projekte/connect/connect.phar/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
	PHP   8. Net_SSH2->exec() phar:///home/torsten/Projekte/connect/connect.phar/src/Connect/Command/SshCommand.php:35
	PHP   9. Net_SSH2->_get_channel_packet() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2300
	PHP  10. Net_SSH2->_get_binary_packet() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2974
	PHP  11. Net_SSH2->_filter() phar:///home/torsten/Projekte/connect/connect.phar/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php:2771

OS: Arch Linux
Server + Client: OpenSSH_6.8p1, OpenSSL 1.0.2a 19 Mar 2015

**Comment by terrafrost** [comment]
Does this branch fix the issue?:

https://github.com/terrafrost/phpseclib/tree/ssh2-global-request

The commit: https://github.com/terrafrost/phpseclib/commit/b59d821bbe8ad4f976ecf8f8c98b72d64327b9b8

Thanks!

**Comment by tburschka** [comment]
sry, didn't solve the issue.

**Comment by terrafrost** [comment]
Post your SSH2.php file then. Or rather post a pastebin.org link to it.

I made my change based on the fact that line 2826 in v0.3.10 deals with parsing SSH_MSG_GLOBAL_REQUEST packets:

https://github.com/phpseclib/phpseclib/blob/0.3.10/phpseclib/Net/SSH2.php#L2826

But then I don't even know that you're using v0.3.10. In-so-far as I know, you could be using the 2.0 branch, an older version of the 1.0 branch, or you could be using some version you downloaded straight from github.

Something else that could provide some insight...  post SSH logs. eg. do `define('NET_SSH2_LOGGING', NET_SSH2_LOG_COMPLEX);` after you include Net/SSH2.php (assuming you're using the 1.0 branch) and then later do this:

```php
echo $ssh->getLog();
```

Another possibility. Maybe the error message you're getting looks the same but the line numbers are different. ie. in that scenario the fix I proposed *did* fix the issue you were having and now you're having another issue. So if you could also repost the error message that you're getting that'd be helpful too.

**Comment by tburschka** [comment]
Sry, you're right, i had to show my downloaded dependencies from composer:

    phpseclib/phpseclib        0.3.10             PHP Secure Communications Library - Pure-PHP implementations of RSA, AES, SSH2, SFTP, X.509 etc.
    symfony/console            v2.6.6             Symfony Console Component

I've modified my phpseclib/phpseclib with the files from your ssh2-gobal-request branch, but i post the file here: http://pastebin.com/KHknQMxd
Also, here is the log: http://pastebin.com/QcWaawsp
and here the same warning message: http://pastebin.com/R7Zt9C7U
Please, feel free to ask for more logs (e.g. server log)

**Comment by terrafrost** [comment]
Thanks! I'm about to head out for a little bit but I'll try to take a look when I get back.

**Comment by terrafrost** [comment]
I made another update to that branch if you want to try it out. Diff:

https://github.com/terrafrost/phpseclib/commit/684d6eed0e2fc3045c9169685ce135a14474abef

**Comment by tburschka** [comment]
yep, that one worked!

**Comment by equizno345** [comment]
I was having a odd issue with "unpack(): Type N: not enough input, ..." and terrafrost@684d6ee fixed it. Thank you!
