### ISSUE TITLE
Please tag releases for Composer/Packagist

### ISSUE THREAD

**Issue by iammattcoleman** [phpseclib/phpseclib#688]
I'd like to be able to remove development dependencies from my project, and phpseclib is the last thing that forces me to set 'minimum-stability' to 'dev'. Can you tag releases for the 2.0 and 1.0 branches, please?

**Comment by GrahamCampbell** [comment]
Why? That doesn't make sense. They're not stable yet.

**Comment by GrahamCampbell** [comment]
You need to use dev stability. The prefer stable thing can be useful in composer if that helps. :)

**Comment by GrahamCampbell** [comment]
Example: https://github.com/StyleCI/StyleCI/blob/master/composer.json#L80.

**Comment by iammattcoleman** [comment]
While the entire library may not be stable, many pieces of it are. I have a proposal: rather than waiting until it's "done" or "ready" as a whole, tag it in its current state and create a to-do/errata document that enumerates what is not yet production-ready.

To speed up stabilization of the individual components, phpseclib could be restructured as a metapackage that pulls in separate packages for BigIntegers, RSA, SSH2, SFTP, X.509, and symmetric key encryption.

**Comment by iammattcoleman** [comment]
Also, thanks for the tip about the 'prefer-stable' setting! I had no idea it existed. :+1:

**Comment by iammattcoleman** [comment]
I just noticed that my "proposal" is already on the roadmap.
