### ISSUE TITLE
RSA::loadKey returning false on CentOS, but works correct on Mac

### ISSUE THREAD

**Issue by jeffrey-stickle** [phpseclib/phpseclib#694]
I am running stable version 0.3.10 and attempting to load a RSA public key I generated using the createKey function. This code works perfectly correctly when run locally on my Mac and spits back out the key I entered:

    CONST PUBLIC_KEY = '-----BEGIN PUBLIC KEY-----
    MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYwTO/CJJQ8vbwTRQRWmOS0Pbz
    tFCks4RhmPxYANSQV5V9Qy+QSupewn2WAb7zV04r4RqtwxB7stDMbK+uPY+GYR5M
    moQuT0YStJ6TXJjiF8i1Y+DBGLnTXOD36y93V8DpuFWMxMYtROskE+Mx1W70+VTZ
    EM6k+jvIfzRJoVDqswIDAQAB
    -----END PUBLIC KEY-----';

    $rsa = new \Crypt_RSA();
    $rsa->loadKey(self::PUBLIC_KEY);
    echo $rsa->getPublicKey();

However when I push it to an AWS instance running CentOS, the loadKey call returns false. I'm not seeing any other error notifications to tell me what went wrong. Is there some dependency that could be different in the two OS versions?

**Comment by jeffrey-stickle** [comment]
After doing some additional debugging, it looks like the discrepancy starts in `_parseKey` at line 1143
    if ($this->_decodeLength($key) != strlen($key)) {
        return false;
    }

**Comment by bantu** [comment]
What is the output of `var_dump(ini_get('mbstring.func_overload'));` ?

**Comment by terrafrost** [comment]
I think you posted this on stackoverflow as well lol:

http://stackoverflow.com/a/30489896/569976

Anyway, what version of phpseclib do you have installed locally on your mac vs on the CentOS AWS instance?

I just tried it on my local copy (latest Git version) and it worked just fine:

```php
<?php
include('Crypt/RSA.php');

$key = '-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDYwTO/CJJQ8vbwTRQRWmOS0Pbz
tFCks4RhmPxYANSQV5V9Qy+QSupewn2WAb7zV04r4RqtwxB7stDMbK+uPY+GYR5M
moQuT0YStJ6TXJjiF8i1Y+DBGLnTXOD36y93V8DpuFWMxMYtROskE+Mx1W70+VTZ
EM6k+jvIfzRJoVDqswIDAQAB
-----END PUBLIC KEY-----';

$rsa = new Crypt_RSA();
$rsa->loadKey($key);
echo $rsa->getPublicKey();
```

**Comment by jeffrey-stickle** [comment]
You're right I did post on stackoverflow then figured I'd come right to the source since it looked like you've been great with support and I've been struggling with this for a couple days now.

I am installing using composer and was previously running 0.3.10. I now switched it to use dev-master but am seeing the same result.

I think @bantu is on to something, when I output `var_dump(ini_get('mbstring.func_overload'));` locally I get 0 and on the server I get 7. Does having `mbstring.func_overload` enabled break the key parsing? I am only using RSA to encrypt an AES symmetric key, so I can probably temporarily disable `mbstring.func_overload` if necessary.

**Comment by terrafrost** [comment]
Yah - `mbstring.func_overload` would definitely cause problems. phpseclib works with binary data a lot. It assumes that `strlen($str)` returns the number of bytes in `$str` instead of the number of "gylphs", etc.

Maybe I should add a check for this in phpseclib and have it throw an exception or some such when mbstring function overloading is enabled..

**Comment by jeffrey-stickle** [comment]
Ahh that makes sense. I'll have to look into some way of temporarily disabling that while performing the encryption. Thanks so much for the clarification!
