### ISSUE TITLE
Unable to call loadCSR when pkcs-9-at-challengePassword is present

### ISSUE THREAD

**Issue by Fuitad** [phpseclib/phpseclib#696]
Trying to do $x509->loadCSR($csr) on a particular file returns false. Upon further inspection (openssl req -text -noout < csr), here's what I see that is usually not in the files I receive:

    Attributes:
            unstructuredName         :changeit
            challengePassword        :changeit

I debugged it a bit and the problem seems to be related to line 2870 of X509.php

    $csr = $asn1->asn1map($decoded[0], $this->CertificationRequest);

Any idea how I can work around that?

**Comment by terrafrost** [comment]
Can you post a copy of the CSR? Or at least a similarly formatted one?

**Comment by Fuitad** [comment]
Sent it to you privately.

**Comment by Fuitad** [comment]
I was able to get loadCSR to load by commenting out line 664 of ASN1.php

    } elseif (!isset($child['optional'])) {
      //return null; // Syntax error.
    }

and by modifying line 669 of the same file

    // Fail mapping if all input items have not been consumed.
    return $map; //$i < $n? null: $map;

I have no idea if I'm breaking more things in the process tho since I really don't fully understand what's going :P. But hopefully, this will help you debug. Thanks!

**Comment by terrafrost** [comment]
https://github.com/terrafrost/phpseclib/commit/d3a5398fe4a84ab3dd6f36e2bdee7c6ab1534f05

I believe that commit should fix the issue for you. I'll submit a pull request tomorrow - need to add a unit test too.

**Comment by Fuitad** [comment]
appears to be working, thanks! :)
