### ISSUE TITLE
Download file via SFTP - file is empty (0 bytes)

### ISSUE THREAD

**Issue by clarkk** [phpseclib/phpseclib#697]
What am I doing wrong here?

I need to download a file via SFTP.. Login is successful, the file is created, but it is empty (0 bytes)

```
require_once 'Net/SFTP.php';
$sftp = new Net_SFTP($host);
if (!$sftp->login('root', 'password')) {
	exit('Login Failed');
}
$sftp->get('remote_file.txt', 'destination_file.txt');
```

**Comment by terrafrost** [comment]
Could be an issue with you not having permissions. I'd check the error logs. eg.

```php
var_dump($sftp->getSFTPErrors());
```

Failing that maybe enable packet logging by doing `define('NET_SFTP_LOGGING', NET_SFTP_LOG_COMPLEX)` before you declare `Net_SFTP` but after the `require_once` and post the results.

We may need to look at the SSH layer too but let's look at the SFTP layer first.

**Comment by clarkk** [comment]
Please remove this issue.. Found out that the server was out of free storage :)

**Comment by clarkk** [comment]
Found out that the server was out of free storage.. :)
