### ISSUE TITLE
where have all the openssl changes gone from the 2.0 / master branch?

### ISSUE THREAD

**Issue by terrafrost** [phpseclib/phpseclib#703]
Here's the changelog for Crypt/RC4.php:

https://github.com/phpseclib/phpseclib/commits/2.0/phpseclib/Crypt/RC4.php

Crypt/RC4.php, as of the Dec 30, 2014 commit, had "isValidEngine" implemented.

https://github.com/phpseclib/phpseclib/blob/e3487c8adb4b3c79f10028f7dc174f81ce924427/phpseclib/Crypt/RC4.php

In the very next commit (from Jan 5, 2015) it's missing:

https://github.com/phpseclib/phpseclib/blob/71c2d4395695c4b2f12d968a5432ba83231e07a3/phpseclib/Crypt/RC4.php

The diff between those two versions does not show the "isValidEngine" method being removed but clearly it has been:

https://github.com/phpseclib/phpseclib/commit/71c2d4395695c4b2f12d968a5432ba83231e07a3#diff-268ec080c4caed62d72448f741d29e2f

So what's going on? I can re-add the changes but who's to say that they won't magically disappear again?

**Comment by terrafrost** [comment]
I think I've found the commit that removed these changes: 8fae19a02470463ddb8ac29cfd644a9918a8ae30

Here's a copy of Crypt/RC4.php from the commit before (Jan 1, 2015):

https://github.com/phpseclib/phpseclib/blob/4766973e6104ec7c32983a3718951125801c20ca/phpseclib/Crypt/RC4.php

Here's a copy of Crypt/RC4.php from the commit in question (Jan 3, 2015):

https://github.com/phpseclib/phpseclib/blob/8fae19a02470463ddb8ac29cfd644a9918a8ae30/phpseclib/Crypt/RC4.php

The diff doesn't show any changes being made to Crypt/RC4.php and yet Crypt/RC4.php is different before and after the commit.

Does anyone have any ideas as to what's going on here?

**Comment by bantu** [comment]
git checkout 2.0
git log phpseclib/Crypt/RC4.php

Top three:
d75f703c0ae93dbd99dab5c259c98f47759c87af
ebcb3130b728420569028936a89f93cfb03a50f7
71c2d4395695c4b2f12d968a5432ba83231e07a3

The first one does not seem relevant. 71c2d4395695c4b2f12d968a5432ba83231e07a3 does not seem to have caused this either. It looks more like an incorrect conflict resolution in ebcb3130b728420569028936a89f93cfb03a50f7, which basically means RC4 never had isValidEngine in the 2.0 branch. Indeed this commit added isValidEngine for some classes, but not RC4. See https://github.com/phpseclib/phpseclib/commit/ebcb3130b728420569028936a89f93cfb03a50f7#diff-268ec080c4caed62d72448f741d29e2f

**Comment by terrafrost** [comment]
That makes sense - thanks!
