### ISSUE TITLE
Certificates are not quite generated to RFC, apparently.

### ISSUE THREAD

**Issue by jonathanvaughn** [phpseclib/phpseclib#705]
We've run into this : https://bugzilla.mozilla.org/show_bug.cgi?id=1166216#c7

Loading pages with certificates generated with phpseclib are giving SEC_ERROR_BAD_DER from Firefox/etc products using mozpkix for certificate handling.

Specifically that there's not a NULL after rsaEncryption (288), before the bit string (289):
```
  262:d=4  hl=2 l=  18 cons: SEQUENCE
  264:d=5  hl=2 l=   3 prim: OBJECT            :commonName
  269:d=5  hl=2 l=  11 prim: PRINTABLESTRING   :example.com
  282:d=2  hl=4 l= 288 cons: SEQUENCE
  286:d=3  hl=2 l=  11 cons: SEQUENCE
  288:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  299:d=3  hl=4 l= 271 prim: BIT STRING
```

These certificates work everywhere else, but apparently mozpkix has decided to be sticklers for perfection and reject the certificates. If I get time I'll try to figure out how to fix this myself (and if so send an appropriate PR), but wanted to open the issue so that it's documented and possibly someone else can implement a fix first if I don't.

Also, it's possible that this has been fixed already, and I missed it. We're currently on commit `22502c24cdaa8ed51e85d2f64d6ce2caafb06948` from Oct 12 2014. I haven't yet been able to test this against master.

**Comment by jonathanvaughn** [comment]
Master still has the same behavior, I just tested it.

**Comment by jonathanvaughn** [comment]
To be more specific with regards to RFC, per RFC3279 https://tools.ietf.org/html/rfc3279#section-2.2.1 using RSA encryption in X509:
>When any of these three OIDs appears within the ASN.1 type
>   AlgorithmIdentifier, the parameters component of that type SHALL be
>   the ASN.1 type NULL.

I think the output result of `['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters']` needs to end up being NULL - that seems to be the relevant structure. It's currently defined as optional in File/X509.php around line 370.

So far, I have tried: 
- making optional false
- setting the `['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters']['value']` to null 

I noticed there's a filter set to make it a string? or to filter out strings? Not sure what the intent is. In either case, nothing is output for parameter. Around line 1500.

**Comment by metaclassing** [comment]
I attempted something very similar for an hour yesterday after reading your original post, I validated that the null (while it doesn't appear to actually functionally do anything meaningful) is missing, and attempted to force phpseclib to insert it (fumbling around) by commenting out the optional line which resulted in loadX509 failing to read my certs... I am waiting for someone more familiar with the library to weigh in on the best fix as well. While not mission critical for me, Firefox breaking is a minor annoyance. Regenerating a BUNCH of certificates is going to be far more painful.

**Comment by metaclassing** [comment]
So somebody much more knowledgeable will probablly smack me for posting this, but here is a one-liner that i just cooked up to see what it would do:
```
# svn diff
Index: include/phpseclib/File/ASN1.php
===================================================================
--- include/phpseclib/File/ASN1.php     (revision 18)
+++ include/phpseclib/File/ASN1.php     (working copy)
@@ -934,6 +934,7 @@
                 }
 
                 foreach ($mapping['children'] as $key => $child) {
+                    if (isset($child['type']) && $child['type'] == FILE_ASN1_TYPE_NULL) { $source[$key] = array(); }
                     if (!isset($source[$key])) {
                         if (!isset($child['optional'])) {
                             return false;
Index: include/phpseclib/File/X509.php
===================================================================
--- include/phpseclib/File/X509.php     (revision 18)
+++ include/phpseclib/File/X509.php     (working copy)
@@ -387,7 +387,7 @@
             'children' => array(
                 'algorithm'  => array('type' => FILE_ASN1_TYPE_OBJECT_IDENTIFIER),
                 'parameters' => array(
-                                    'type'     => FILE_ASN1_TYPE_ANY,
+                                    'type'     => FILE_ASN1_TYPE_NULL,
                                     'optional' => true
                                 )
             )
```

**Comment by jonathanvaughn** [comment]
That will probably work. I'll hopefully test it today.

**Comment by jonathanvaughn** [comment]
I just tried this, and it doesn't appear to work (I'm not seeing any NULLs at all). Though, it seems we're working against different versions of phpseclib since the line numbers didn't match up (I am on master now).

**Comment by jonathanvaughn** [comment]
Oops, due to ID10T error at some point I accidentally started using PECL installed version, not the version in my project's directory. So, above comment may be false.

**Comment by metaclassing** [comment]
You are correct, I am running a very different version of phpseclib in my environment. The master branch on github has gone through a number of rewrites and I have enough code dependent on the old version I have not updated in quite a while.

I forked the repo here and gave patching it a try. Again, maybe not the final fix but I think its working on my limited test case: https://github.com/phpseclib/phpseclib/compare/master...metaclassing:add-null-after-algorithm are the exact line numbers and changes I made off the master here.

**Comment by jonathanvaughn** [comment]
Yeah, it probably works. Meanwhile I think I came up with a slightly less terrible hack, but I can't fully test because one of the changes that master has gone through is namespace changes and the project I'm using it in is based in Yii 1.x which is terrible at handling PSR style namespacing ... so I'm fighting with it currently to get the autoloader to behave. I was able to reissue my test root certificate and it looks okay, but trying to then use it to sign the reissue of my test server cert is running into this namespace nonsense ... 

I may just roll back to where I was, and apply the fix there, and worry about it later...

**Comment by jonathanvaughn** [comment]
I THINK this will work for master:
```
diff --git a/phpseclib/File/X509.php b/phpseclib/File/X509.php
index 05f23dd..813c0ce 100644
--- a/phpseclib/File/X509.php
+++ b/phpseclib/File/X509.php
@@ -1482,6 +1482,7 @@ class X509
             default:
                 switch ($algorithm) {
                     case 'rsaEncryption':
+                        $cert['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters']['value'] = null;
                         $cert['tbsCertificate']['subjectPublicKeyInfo']['subjectPublicKey']
                             = base64_encode("\0" . base64_decode(preg_replace('#-.+-|[\r\n]#', '', $cert['tbsCertificate']['subjectPublicKeyInfo']['subjectPublicKey'])));
                 }
@@ -1496,7 +1497,14 @@ class X509
         $filters['tbsCertificate']['signature']['issuer']['rdnSequence']['value'] = $type_utf8_string;
         $filters['tbsCertificate']['issuer']['rdnSequence']['value'] = $type_utf8_string;
         $filters['tbsCertificate']['subject']['rdnSequence']['value'] = $type_utf8_string;
-        $filters['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters'] = $type_utf8_string;
+        if ($cert['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters']['value'] == null)
+        {
+            $filters['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters'] = array('type' => ASN1::TYPE_NULL);
+        }
+        else
+        {
+            $filters['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters'] = $type_utf8_string;
+        }
         $filters['signatureAlgorithm']['parameters'] = $type_utf8_string;
         $filters['authorityCertIssuer']['directoryName']['rdnSequence']['value'] = $type_utf8_string;
         //$filters['policyQualifiers']['qualifier'] = $type_utf8_string;
```

My actual code against the commit we were working with previously (since I couldn't get the namespace/autoload changes to work in Yii properly without major surgery):
```
diff --git a/phpseclib/File/X509.php b/phpseclib/File/X509.php
index 0b4e291..5668da9 100644
--- a/phpseclib/File/X509.php
+++ b/phpseclib/File/X509.php
@@ -1496,6 +1496,7 @@ class File_X509 {
             default:
                 switch ($algorithm) {
                     case 'rsaEncryption':
+                        $cert['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters']['value'] = null;
                         $cert['tbsCertificate']['subjectPublicKeyInfo']['subjectPublicKey'] =
                             base64_encode("\0" . base64_decode(preg_replace('#-.+-|[\r\n]#', '', $cert['tbsCertificate']['subjectPublicKeyInfo']['subjectPublicKey'])));
                 }
@@ -1524,6 +1525,10 @@ class File_X509 {
         $filters['policyQualifiers']['qualifier'] =
             array('type' => FILE_ASN1_TYPE_IA5_STRING);

+        if ($cert['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters']['value'] == null)
+        {
+            $filters['tbsCertificate']['subjectPublicKeyInfo']['algorithm']['parameters'] = array('type' => FILE_ASN1_TYPE_NULL);
+        }
         $asn1->loadFilters($filters);

         $this->_mapOutExtensions($cert, 'tbsCertificate/extensions', $asn1);
```

**Comment by metaclassing** [comment]
My knowledge is rather limited, are there any cases where an algorithm block of ASN1 would have non-null parameters?

**Comment by jonathanvaughn** [comment]
In theory, if you use something other than RSA type algorithms. That's what it's there for, but RSA type algo's dont have any parameters.

Seems better to only force it when it's supposed to be forced, just in case someone needs the functionality?

**Comment by jonathanvaughn** [comment]
Okay my code for master branch works, I managed to hack my way around the autoloading nightmare (sort of - I had to make one extra change to File_X509.php where there's an array_map causing autoloading fail) so I could test it.

The first diff I posted works fine against master.

**Comment by jonathanvaughn** [comment]
To be specific about which algo's need the parameters, it seems RSA doesn't need it but DSA and elliptic curve (ECDSA) variations do. There might be others defined in newer RFCs, those are just the ones I see mentioned in RFC 3279.

**Comment by metaclassing** [comment]
Did new certs validate with FF for you? I tried both my change and yours and can validate from an ASN1 dump that nulls are inserted either way, but im still getting sec_error_bad_der in FF37

**Comment by jonathanvaughn** [comment]
They did work for me in FF38?

There may be something else that you're missing that we're "doing right" perhaps? I know it also will reject IPs listed as dNSname (which is annoying, because to support IE before Windows 10 you must do that instead of using IPs listed as ipv4)

**Comment by jonathanvaughn** [comment]
Here are the certs I tested with, for example.com :

CA cert:
```
-----BEGIN CERTIFICATE-----
MIIF1TCCA7+gAwIBAgIBOzALBgkqhkiG9w0BAQswcTELMAkGA1UECxMCSVQxEDAO
BgNVBAoTB2V4YW1wbGUxEzARBgNVBAcTClJpY2hhcmRzb24xCzAJBgNVBAgTAlRY
MQswCQYDVQQGEwJVUzEhMB8GA1UEAxMYZXhhbXBsZS5jb20gUm9vdCBDQSB0ZXN0
MB4XDTE1MDYxODA1MDAwMFoXDTE4MDYwMzA1MDAwMFowcTELMAkGA1UECxMCSVQx
EDAOBgNVBAoTB2V4YW1wbGUxEzARBgNVBAcTClJpY2hhcmRzb24xCzAJBgNVBAgT
AlRYMQswCQYDVQQGEwJVUzEhMB8GA1UEAxMYZXhhbXBsZS5jb20gUm9vdCBDQSB0
ZXN0MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEApNFb3raO1ZtaZXOP
5F6miWGteCYvU1921tdBLk2cwKs/7Id73V7QBj9/EQF5tlDnsNAMy+KLo/bUPD6c
j6C91AGTv03+8u9j+Rx2th1l7ZEeIf0aLa9mZWJufR2aVUN2cXntQ8OFczOVlKtg
HVG4MLeFDI6EGu8f2YeQKQgttJDffQakFWM3ZrbzOAjCkboGG8V9T/a517OQRvg9
UxW7tJ607czThPCNi2BYbzuuKnNTVM1Tad6z3RVaTynOqlPZr5KfmyyMFeNFvFFB
Mb8poY7mLfqTs2HsD9coXMtgRJ++C1voFyfSOnSxnFDARsgmOlNOWbH9216nAPAd
5+xxrhkf8rSj3FvS/SqNwqAUX30I9cgD/M73xuvAaxE8QCQNSL2TVy7WLD2dY4LW
FqiE53wHVU47kZCL+awmgSH+6g2tXG7edxoUyuhP3B2PvB5OpNxp/fU+9EMNWjPS
C26ucchqyCVKBlVObvfAavNCWf84HTnzQpKCS3F6aqRsb+WON18i7ec75i/3bbRq
tTzDsSO3dgC/gXMs1gtrWQWD/klkfeTnLQQ+UlotgrUMpXlH12b+32FS7oaCSc09
HTxYIBJzxoICLNM/TOLbhWo6qDCXDePzhOwoVbgVJLvPhNC7dTwJcSSeFjfpcI9w
+/MhygYPHhkJ7VSuG0624e2ejH0CAwEAAaN8MHowCwYDVR0PBAQDAgEGMA8GA1Ud
EwEB/wQFMAMBAf8wHQYDVR0OBBYEFCr7Iqlpr5jFBfDt5RdT6grj8bsyMDsGA1Ud
JQQ0MDIGCCsGAQUFBwMCBggrBgEFBQcDAQYIKwYBBQUHAwQGCCsGAQUFBwMDBggr
BgEFBQcDCDALBgkqhkiG9w0BAQsDggIBAGa1gG7HXEBjC5Ke0m+88ReFKSjIS0g2
/XNYKuTUG7a0iOKFFaS2/5YcKemPdHJcKWTwz9rNgvKshcYIXk6xFGYHqanWOiV5
d4fF27ovAUTE8qWsjQbfXgB1HnCkLUSjUU5jUiJSP3D6d1Y5KfJg2VVFwRe4chKX
MQ95+axZATwrRmPspDvkD4AL7l7avb0A8GJggnR6OBurFQynS6ee9Vk9ycpXP+4j
xWMT18EL9KSkVihcW+s3scSBMEVJ1tFJ1uftJPWMCc68bpbZQ8G/rEWiXEZaD+Tq
t4gxYPIJzH2n/wx8qxB71957RaE0hF+FxDszJbPmiXSAiMuz+FDf7Gqzh4CxjIJR
twqSyuGWK19cgZwSuuDRqzzCJFy1OdFAf2Dz+3MH+wrbnJ0dtdlXpOVHKm4i7tSh
UoAdQljI3OdJ+48CPaSRDLPs22HqRklvhKBuyTCQYGEcT/TwCj0zHq1LXvBBwQdT
fiN3uuHi8a3I+r34icNig+slO/oneW0NmFbOIJ3hMQoztmQo3pUILRmg73iu+/Qp
RMgUVui7bEkQaj9wZEhp6dGNNB2vUPUIGF6FyTGdHCF2rCcFAnJJ7z58RzhP4ne2
wPboJX/dPipevLEcgLQcko3DiGM6/Yj6Huq6rEX5jE9KVW6UkV5jwb7ohvEsnwKZ
gEWaoK9tNyTA
-----END CERTIFICATE-----
```

Server cert
```
-----BEGIN CERTIFICATE-----
MIIErTCCApegAwIBAgIBPTALBgkqhkiG9w0BAQswcTELMAkGA1UECxMCSVQxEDAO
BgNVBAoTB2V4YW1wbGUxEzARBgNVBAcTClJpY2hhcmRzb24xCzAJBgNVBAgTAlRY
MQswCQYDVQQGEwJVUzEhMB8GA1UEAxMYZXhhbXBsZS5jb20gUm9vdCBDQSB0ZXN0
MB4XDTE1MDYxODA1MDAwMFoXDTE4MDYwMzA1MDAwMFowZDELMAkGA1UECxMCSVQx
EDAOBgNVBAoTB2V4YW1wbGUxEzARBgNVBAcTClJpY2hhcmRzb24xCzAJBgNVBAgT
AlRYMQswCQYDVQQGEwJVUzEUMBIGA1UEAxMLZXhhbXBsZS5jb20wggEiMA0GCSqG
SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDXGdngGjnGwDTYM6WVh5YNg9hZafaM0lvG
nhRPo+JraVZOw9jxfbQpCGoW1ZAGzsxcthD6h5Ars9Q0TUOgQOsFjqW7Pjws5lax
R0cYf50of2XEWx82whF+0ixlZCfeb3qeprEAbkIb7WKAphzgM3wUubKHckhuOJrM
IZ60mKDd6PfZyFpVM/A2IL3+v+FbVeAy40UrCGXj9M6SU7XmgeNtkHNtTORv0F55
jzjJOAYuQyo/42bTu+x64NqOArNmq1xalx8/4lKHOpzmcRr4pMtDXeFV2a2RlB7y
V89M2Jm8tC5lakhK0NJQ5Gk7MUfffsaTqM/tpUZj1cADhVP/Yu6xAgMBAAGjYTBf
MBMGA1UdJQQMMAoGCCsGAQUFBwMBMCcGA1UdEQQgMB6CC2V4YW1wbGUuY29tgg93
d3cuZXhhbXBsZS5jb20wHwYDVR0jBBgwFoAUKvsiqWmvmMUF8O3lF1PqCuPxuzIw
CwYJKoZIhvcNAQELA4ICAQBJ3QLXJ8HzVemd+XukcwS7zGa0hpNnWRcYZtwS4YXY
mqC+3VWhHhFrzT53OczwD05neOYOgNLltJZ8NCnG6O9OMPcoBqC9y0mzlcVk3JGN
UXDJ5u+AKb+o36kV81o9lE+RcgJ8jys5M1iNcYGCFX7YdNQEJohMBrvMbbdq8nQ6
3KkiGxKCqFLp5XiGyW7xJFNghvN4ynkpa2y+p0rWaWjOx/aYEfcty/76tV5Wkg/l
RzQyHmLA9WUP135GQlEloLkvUhEqzNJ41pjua6resHSMcfgFxtPRwmuBVtdWruVC
Mm50hKSLRpWZFxcGJOJo1uHri1OgHTkfy6i+jnuWRIiR/IrUK202FC/SCm1g6oCa
/Ois/NwEzw1IJ1DQadUS6YPqX/D2YA55MZw0yFzHXtpFdR8wF4THJtOo2j11a6pl
GNq3Kx5LimGdKLz0G9KMJOMlUL8nKHAqrpQbMUUqY7HC3izB+0a9zo1fEFBGVO6w
KMp0gZcUeBBPl6wESPFVpnQo9zsOqqPdrdgxtPa60kMAZY1H1C0rrTRm+GZsPLvr
kRZ0yEVpJZtmcoQsyAnrD24C0tz0xn5v+cV9iDTDFfhGmRHICyYlfU+AHV0csBNj
A+8ASHPe81OOgC3pfVPf0wTW5Eqg13HvbdwIiJgmoiuPV2IkVrMf6dhYyvkecRne
BQ==
-----END CERTIFICATE-----
```

**Comment by metaclassing** [comment]
Hi again,

So I went through a lot of pain and test cases and made some discoveries:

1) The reason none of my regenerated certs were working was because both the root AND intermediate certs had to be regenerated with the NULL patch applied. Even if the server cert is OK, any upstream certs must also be corrected.

2) Doing some ASN1 dumps of OpenSSL generated certs, I discovered several other fields that had the same NULL parameter requirement:
```
   18:d=3  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
   29:d=3  hl=2 l=   0 prim: NULL              
...
  124:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  135:d=4  hl=2 l=   0 prim: NULL              
...
  609:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
  620:d=2  hl=2 l=   0 prim: NULL          
```
Those fields equate to the SignatureAlgorithm pieces at the top and bottom of a cert:
```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number: 20 (0x14)
>    Signature Algorithm: sha256WithRSAEncryption
...
        Subject Public Key Info:
>            Public Key Algorithm: rsaEncryption
                Public-Key: (2048 bit)
                Modulus:
                    00:ea:70:56:35:4f:22:b3:b8:6a:67:c1:3c:ba:ed:
                    27:ea:a6:3f:c2:15:57:d9:f2:c9:72:ef:86:cb:ad:
...
        X509v3 extensions:
            X509v3 Basic Constraints: critical
                CA:FALSE
            X509v3 Key Usage: 
                Digital Signature, Non Repudiation, Key Encipherment
            X509v3 Extended Key Usage: 
                TLS Web Server Authentication
            X509v3 CRL Distribution Points: 
...
            X509v3 Authority Key Identifier: 
                keyid:E2:56:54:25:F8:A6:86:52:07:37:A6:82:28:5F:F5:D0:21:14:D1:C9
>   Signature Algorithm: sha256WithRSAEncryption
         83:fc:c6:5b:ee:4a:ea:3a:2d:4d:52:77:a3:cc:36:5c:0a:d9:
         c5:c1:8f:29:00:81:4c:30:cf:04:af:a7:70:b8:a4:2d:96:5a:
...
```
It looks like the Microsoft Windows Server 2012r2 enterprise CA follows the same logic as OpenSSL and inserts NULL parameters as well after any algorithm block (all of mine use RSA so I don't have an alternative to compare with)

After regenerating (and issuing new serial numbers, etc.) all the root, intermediate, and server certs FF37 is "happy" for the time being.

3) There is an unrelated FF37 bug i'm running into importing my personal / user certificate. I get unknown error from the GUI but don't know if that's related or not... I don't have the heart to fight with that piece right now lol

I inserted a few other random fixes in my fork as well, i'm debating if anything is of value for a PR or not, ill leave that up to more capable devs to decide on more elegant solutions to the speedbumps I tend to flatten with dynamite haha

**Comment by metaclassing** [comment]
Oh and if anybody runs into the mismatch SubjectAlternativeNames type/content issue, this is a snippit of code from an unrelated project for dealing with that:
```
    protected function altnames($ALTNAMES)
    {
        //Sort names and IPs into two different arrays
        $DOMAINS = array(); $IPS = array(); $EMAILS = array();
        foreach ($ALTNAMES as $ALTNAME)
        {
            if      ( filter_var($ALTNAME, FILTER_VALIDATE_EMAIL) ) {
                array_push($EMAILS  ,$ALTNAME);
            }elseif ( filter_var($ALTNAME, FILTER_VALIDATE_IP   ) ) {
                array_push($IPS     ,$ALTNAME);
            }else                                                   {
                array_push($DOMAINS ,$ALTNAME);
            }
        }
        // Create our altname array for the subjectAltName parser
        $RETURN = array();
        foreach ($DOMAINS   as $DOMAIN  )   { array_push($RETURN, array("dNSName"   => $DOMAIN  ) ); }
        foreach ($IPS       as $IP      )   { array_push($RETURN, array("iPAddress" => $IP      ) ); }
        foreach ($EMAILS    as $EMAIL   )   { array_push($RETURN, array("rfc822Name"=> $EMAIL   ) ); }
        return $RETURN;
    }
```
It just uses filter_var's to assign a bulk list of names regardless of type into the correct associative containers to quickly feed into phpseclib for processing.

If generating a x509 v3 extended attribute cert WITHOUT a CSR, it is still apparently necessary to double-sign it from the CA. (old workaround: sign once, re-read newly signed cert, apply V3 attributes, resign again to make them stick)

**Comment by terrafrost** [comment]
#707 did not fix the issue for me but #721 / #722 did. 

The next to last post suggests that the following is an issue as well:

```
   18:d=3  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
   29:d=3  hl=2 l=   0 prim: NULL              
...
  124:d=4  hl=2 l=   9 prim: OBJECT            :rsaEncryption
  135:d=4  hl=2 l=   0 prim: NULL              
...
  609:d=2  hl=2 l=   9 prim: OBJECT            :sha256WithRSAEncryption
  620:d=2  hl=2 l=   0 prim: NULL          
```

#721 / #722 do not address that - I'll do another PR for that I guess.

I'm not sure what the "SubjectAlternativeNames type/content issue" is?

Also, how many issues are we at in this ticket? There's the one with rsaEncryption. There's the sha256WithRSAEncryption and maybe some issue with SubjectAlternativeNames. Is that it?

If you're going to include multiple issues in the same ticket maybe edit the first post and if you can't or don't feel that's appropriate or whatever maybe create whole new tickets.

**Comment by jonathanvaughn** [comment]
Sorry all, I haven't had time to focus on this (always something else being higher priority than functioning PKI...). 

The only issue we were currently stumbling on (at least, as far as we knew) was the one for rsaEncryption, though the fix may have fixed the others as well, if they were also issues? In either case, I haven't had a chance to do more than test that the issue is fixed with a test certificate - haven't had time to deploy this to production or regenerate certificates and I also haven't tested the #721 / #722 commits vs my PR myself, but I'll take your word for it that they work and are a better fix (updated tests and all!) - feel free to reject my PR.

**Comment by terrafrost** [comment]
metaclassing's subjaltname stuff is interesting but atm there's not really an "official" way to utilize non-domain subjaltname's. Maybe that'll change but in the interim I think all the bugs this ticket brought to light have been fixed.

Thanks!
