### ISSUE TITLE
disableStatCache

### ISSUE THREAD

**Issue by michael4test** [phpseclib/phpseclib#712]
Hi,

I downloaded the latest 1.0 branch and found a bug, but this bug depends on disableStatCache.

Although my program disables the cache with ($sftp->disableStatCache),
the internal function Net_SFTP::_update_stat_cache/_remove_from_stat_cache
is called very often.

$rcode = $sftp->disableStatCache();
$files = $sftp->rawlist();
foreach($files as $name => $stat) {    ...    }

1.
Either this is by design. 
Then I will send you the bug report as soon as you will decide if this issue is a bug or by design.

2.
Or this is a bug, because if I disable the cache, the cache should be frozen
and no update (_update_stat_cache) or remove is allowed.
In this case my program runs without errors because of my workaround:
function _update_stat_cache($path, $value)
{
    if ($this->use_stat_cache===false) return; #wordaround disableStatCache
    ....

3.
I personally vote for point 2.

Best Regards
Michael

**Comment by bantu** [comment]
I'd say that disableStatCache() should empty the cache and then there should be no further writes to the cache.
