### ISSUE TITLE
PHP Notice in line 1218

### ISSUE THREAD

**Issue by michael4test** [phpseclib/phpseclib#716]
With the latest 1.0 branch I get following PHP Notice:
PHP Notice: Undefined property: stdClass::$lstat in SFTP.php on line 1218

My Program:
$files = $sftp->nlist();
foreach($files as $name)
{
    $stat = $sftp->lstat($name);
    ...
}

SFTP.php:
function lstat($filename)
{
...
        if ($this->use_stat_cache) {
            $result = $this->_query_stat_cache($filename);
            if (is_array($result) && isset($result['.'])) {
                return $result['.']->lstat;  # <======================= line 1218 ====
            }
            if (is_object($result) && isset($result->lstat)) {
                return $result->lstat;
            }
        }
...
}

**Comment by bantu** [comment]
We are claiming this was fixed by #719. Closing as such. Please test.

**Comment by michael4test** [comment]
With the latest 1.0 branch it works OK now.
