### ISSUE TITLE
unpack error

### ISSUE THREAD

**Issue by hanspagel** [phpseclib/phpseclib#733]
I'm trying to connect with phpseclib to a server to run some tasks. Running the first task throws an error:

	ErrorException in SSH2.php line 2827:
	unpack(): Type N: not enough input, need 4, have 1

The same code works when I connect to another server, but it fails when I connect to uberspace/CentOS.

	include('Net/SSH2.php');
	$ssh = new Net_SSH2($settings['host']);
	if (!$ssh->login($settings['user'], $settings['password'])) {
	    exit('Login Failed');
	}

	echo $ssh->exec('pwd');

Do you have any idea how I can debug this?

**Comment by terrafrost** [comment]
Looks like you're running 0.3.10. This issue has been fixed in the latest Git version. In particular, with PR #674

**Comment by hanspagel** [comment]
Nice, this works!
