### ISSUE TITLE
stat vs lstat

### ISSUE THREAD

**Issue by michael4test** [phpseclib/phpseclib#735]
Hi,

With the latest 2.0 branch (489a723d33) I get the following bug.
The results should be equal, regardless of cache is disabled or not.

### My sample files:

    lrwxrwxrwx 1 root root    6 Jun 17 09:04 linkdir -> subdir
    lrwxrwxrwx 1 root root    8 Jun 17 09:04 link.txt -> text.txt
    drwxr-xr-x 2 root root 4096 Jun 17 09:04 subdir
    -rw-r--r-- 1 root root    5 Jun 17 09:03 text.txt

### My program:

    if ($is_cache === false) $sftp->disableStatCache();
    $files = $sftp->nlist();
    foreach($files as $name)
    {
        if ($name === "."  ||  $name === "..") continue;

        $stat = $sftp->stat($name);
        printf("%-11s: %6s %s %s\n", $name, $stat["size"], $stat["mtime"], $stat["type"]);

        $stat = $sftp->lstat($name);
        printf("%-11s: %6s %s %s\n", $name, $stat["size"], $stat["mtime"], $stat["type"]);
    }

### Wrong results with $is_cache==true  (Cache is enabled):

    linkdir    :      6 1434524668 3    <== wrong (stat)
    linkdir    :      6 1434524668 3
    link.txt   :      8 1434524693 3    <== wrong (stat)
    link.txt   :      8 1434524693 3
    text.txt   :      5 1434524636 1
    text.txt   :      5 1434524636 1
    subdir     :   4096 1434524643 2
    subdir     :   4096 1434524643 2

### Right results with $is_cache==false (Cache is disabled):

    linkdir    :   4096 1434524643 2
    linkdir    :      6 1434524668 3
    link.txt   :      5 1434524636 1
    link.txt   :      8 1434524693 3
    text.txt   :      5 1434524636 1
    text.txt   :      5 1434524636 1 
    subdir     :   4096 1434524643 2
    subdir     :   4096 1434524643 2

Best Regards
Michael

**Comment by terrafrost** [comment]
I think this branch should fix it (1.0):

https://github.com/terrafrost/phpseclib/tree/another-stat-cache-update-1.0

The commit:

https://github.com/terrafrost/phpseclib/commit/41e72e71f9b2979774d8fc2a1d2df19ac6eadd6a

**Comment by michael4test** [comment]
Thanks. My program works ok now.

**Comment by bantu** [comment]
Fixed by #743
