### ISSUE TITLE
1.0.0 / 2.0.0 release this weekend

### ISSUE THREAD

**Issue by terrafrost** [phpseclib/phpseclib#756]
I'd like to make releases of 1.0.0 and 2.0.0 this weekend. Maybe we should do a feature freeze until after the weekend?

I don't plan on making a PEAR channel for 2.0. 2.0 will just be installable via composer (or by download).

**Comment by bantu** [comment]
I'd suggest by starting with closing all the open support questions that are stuck (missing information).

**Comment by bantu** [comment]
Do we want to look into PHP7 support before 2.0? I assume we can also do that against master, maybe PHP7 will be in RC soon.

**Comment by terrafrost** [comment]
> I'd suggest by starting with closing all the open support questions that are stuck (missing information).

I'll take a look.

> Do we want to look into PHP7 support before 2.0? I assume we can also do that against master, maybe PHP7 will be in RC soon.

Yah - if that can be done before the weekend that'd be great.

**Comment by terrafrost** [comment]
1.0.0 has been released. I'll be tagging 1.0.0 and 2.0.0 later today. Need to update the README.md and the CHANGELOG.md file before doing that tho.

**Comment by bantu** [comment]
Something went wrong during merge. https://github.com/phpseclib/phpseclib/blob/2.0.0/composer.json#L62 does not belong there.

**Comment by bantu** [comment]
Not a reason to make another retag though.

**Comment by bantu** [comment]
https://github.com/phpseclib/phpseclib/commit/844134df95e42b93ed5506a2d11ca5accda99412 added a phpseclib/phpseclib1.0.0.zip file to the repository history. @terrafrost Please just stick to pull requests.

**Comment by terrafrost** [comment]
That file was deleted in a later commit.

Anyway, I don't have any problems with doing PR's for releases, assuming they're merged in a timely fashion. I mean, if I update the website to announce a new release, the README.md should be updated shortly there after (a few days delay is acceptable imho).

Whomever merges it would need to do `git push origin --tags` (or whatever the name of the remote is) and not just use github.com's built-in merge tool.

**Comment by bantu** [comment]
> That file was deleted in a later commit.

As you probably know, that is not how repositories work. Without rewriting its history, which you should never do for blessed branches anyway, the file is locked permanently and forever in the repository, contributing to the repositories size.

> I mean, if I update the website to announce a new release, the README.md should be updated shortly there after (a few days delay is acceptable imho).

We should change the workflow to no longer make release changes necessary in the repository at all. Just don't link to the latest and greatest version. Instead, just link to the download page.

**Comment by GrahamCampbell** [comment]
> Without rewriting its history, which you should never do for blessed branches anyway, the file is locked permanently and forever in the repository, contributing to the repositories size.

Yeh. :(

**Comment by GrahamCampbell** [comment]
> We should change the workflow to no longer make release changes necessary in the repository at all. 

Probably a good idea.

**Comment by terrafrost** [comment]
> We should change the workflow to no longer make release changes necessary in the repository at all. Just don't link to the latest and greatest version. Instead, just link to the download page.

That works for README.md but what about CHANGELOG.md? It's existence is due to #496 .

**Comment by bantu** [comment]
@terrafrost CHANGELOG needs to be changed longer before the release, not right at/before the release.

**Comment by terrafrost** [comment]
I guess it can be changed as features are committed but then what about the release date?

Maybe we could just stop updating CHANGELOG.md all together and manage releases via https://github.com/phpseclib/phpseclib/releases/new ..
