### ISSUE TITLE
remove SSH1.php from master branch

### ISSUE THREAD

**Issue by terrafrost** [phpseclib/phpseclib#760]
It would be kept in the 1.0 and 2.0 branches but the overall impression I get is that people don't really use SSH1.php so it's just an extra file that needs to be maintained for no real reason what-so-ever.

If people do want it it can be re-added. Removing is defintely a BC breaking change - adding it back...  not so much.

**Comment by bantu** [comment]
Fine with me.

**Comment by metaclassing** [comment]
While I agree SSHv1 needs to disappear, I am one of the few unlucky users that is stuck with 1-2% of legacy network devices (embedded operating systems) that are v1 only with no upgrade path (thankyou vendors)

Most of my code is using the master branch for obvious performance improvements and features/bugfixes. I am willing to manually include the older file pulled from the 2.0 branch but wonder what kind of structural changes will be required on my end to keep it working? OO/namespace conversion etc.

**Comment by terrafrost** [comment]
I can keep it too lol. SSH1.php is already namespaced - the only thing I'd need to add it to it to bring it in line with where master will be exceptions.  But then again maybe in your case using phpseclib v1 vs v2.1 or something would be good too? I intend to main to maintain v1 for a long time and adding non-BC breaking features to it.

I want to totally redo the X509 API but that'll be a huge BC break so that'll be master branch only. But for something like adding SFTP v4/5/6 support...  that can be in v1 and v2 and master.

**Comment by metaclassing** [comment]
If you merge exception implementation for SSHv2 I can try to duplicate them in v1 for you and send a PR for review? My sucky 3rd world equipment shouldn't mean more wasted time and work for others lol.

**Comment by terrafrost** [comment]
> If you merge exception implementation for SSHv2 I can try to duplicate them in v1 for you and send a PR for review? My sucky 3rd world equipment shouldn't mean more wasted time and work for others lol.

Works for me!

**Comment by terrafrost** [comment]
@metalclassing - if you want to go ahead and start adding exceptions to SSHv1 that'd be great. SSHv2 is pretty much done. See #739 for more info.

Thanks!

**Comment by metaclassing** [comment]
@terrafrost Hi, sorry for the slow response - its been a busy week. I will take a stab at adding exceptions and have something for you to review after the holiday. Have a good weekend!

**Comment by metaclassing** [comment]
FYI, I hope to have the last couple dozen SSHv1 devices removed from my infrastructure by Q4 sometime... After that hopefully any vested interest I have for that 20 year old protocol will vanish lol
