### ISSUE TITLE
Where is Net_SCP in the pear channel?

### ISSUE THREAD

**Issue by gdelvalle** [phpseclib/phpseclib#764]
Hi,
I can not find Net_SCP in pear channel.  Is the the recommended way to get these packages?   See [1].  Let me know if I'm crazy or you need further details.

[1]
Channel phpseclib Available packages:

Package          Version
Crypt_AES        1.0.0
Crypt_Base       1.0.0
Crypt_Blowfish   1.0.0
Crypt_DES        1.0.0
Crypt_Hash       1.0.0
Crypt_RC4        1.0.0
Crypt_RSA        1.0.0
Crypt_Random     1.0.0
Crypt_Rijndael   1.0.0
Crypt_TripleDES  1.0.0
Crypt_Twofish    1.0.0
File_ANSI        1.0.0
File_ASN1        1.0.0
File_X509        1.0.0
Math_BigInteger  1.0.0
Net_SFTP         1.0.0
Net_SSH1         1.0.0
Net_SSH2         1.0.0
System_SSH_Agent 1.0.0

**Comment by gdelvalle** [comment]
I'd also like to add that I downloaded everything in the pear channel in hopes the file was in 1 of the listed packages

**Comment by terrafrost** [comment]
I guess that file was an oversight. It's a little too late for me to do anything about this today, however. I'll try tomorrow, time permitting.

**Comment by arcaderob** [comment]
Hello @terrafrost Do you think that you will be able to have a look at this today?

**Comment by gdelvalle** [comment]
Okay,  I'll keep an eye out.  Appreciate it.

**Comment by terrafrost** [comment]
Try it now.

**Comment by terrafrost** [comment]
Looks like Net_SCP has never been in the PEAR channel FWIW.

**Comment by gdelvalle** [comment]
thanks!
