### ISSUE TITLE
Authentication with id_rsa doesn't work for me

### ISSUE THREAD

**Issue by felixkiss** [phpseclib/phpseclib#766]
phpseclib version:
```
"name": "phpseclib/phpseclib",
"version": "2.0.0",
"source": {
    "type": "git",
    "url": "https://github.com/phpseclib/phpseclib.git",
    "reference": "a74aa9efbe61430fcb60157c8e025a48ec8ff604"
},
```
I am trying to connect from my computer to a vagrant box via SSH.

I have my public key (`~/.ssh/id_rsa.pub`) in `/home/vagrant/.ssh/authorized_keys`.

I can successfully connect via command line:
```
$ ssh vagrant@192.168.10.10
```

It doesn't work via phpseclib (Authentication via password works).

Here is my code to load the RSA key:

```php
<?php namespace App\Remote;

use phpseclib\Crypt\RSA;

class RsaKeyAuthentication implements AuthenticationMethod
{
    private $pathToPrivateKey;

    private $key;

    public function __construct($pathToPrivateKey = './.ssh/id_rsa')
    {
        $this->pathToPrivateKey = $pathToPrivateKey;
    }

    public function getCredentials()
    {
        if ($this->key === null)
        {
            $keyContents = file_get_contents($this->pathToPrivateKey);
            $this->key = new RSA;
            $this->key->loadKey($keyContents);
        }

        return $this->key;
    }
}
```

The file gets successfully loaded into `$keyContents`.

Any suggestions?

**Comment by bantu** [comment]
Your example is incomplete as there is no SSH involved.

**Comment by felixkiss** [comment]
```
private function connect()
    {
        if ($this->ssh === null)
        {
            $this->ssh = new SSH2($this->host);
            $login = $this->ssh->login(
                $this->username,
                $this->authenticationMethod->getCredentials()
            );

            if (!$login)
            {
                throw new \Exception('Could not connect.');
            }
        }

        return $this->ssh;
    }
```

**Comment by bantu** [comment]
@felixkiss A shot in the dark: Your id_rsa is password protected. You can see whether it is or not by looking at the file content, e.g. `Proc-Type: 4,ENCRYPTED`. I think you can specify a password using `$this->key->setPassword(...)`. Calling `ssh` will likely ask you for the password on first use and then keep the decrypted key in a process called `ssh-agent`. phpseclib also supports login using an SSH Agent. You simply pass an instance of `phpseclib\System\SSH\Agent` to SSH2's login method.

**Comment by felixkiss** [comment]
You hit the nail on the head.

My private key is in fact encrypted and I forgot about it, because OS X's `ssh-agent` completely hides it from me (stored in login keychain).

`phpseclib\System\SSH\Agent` sounds promising, but I couldn't find it in the docs. Did I miss it?

Anyway, thanks for the help :heart:
