### ISSUE TITLE
RSA PSS default salt length handling changed since v1.0.0

### ISSUE THREAD

**Issue by nov** [phpseclib/phpseclib#768]
These lines set `$sLen = NULL` if  `$this->sLen === NULL`.
https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA.php#L2573
https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RSA.php#L2611

Before https://github.com/phpseclib/phpseclib/commit/2fee2d4f98761b6543d467166ad5143780aa0830, it was `$this->sLen == false` and used `$this->hLen` as default
(I mean default as `$this->sLen === NULL`)

Is this change intended?
Then do we have to call `setSaltLength(false)` explicitly?

**Comment by bantu** [comment]
I can indeed imagine that 2fee2d4f98761b6543d467166ad5143780aa0830 actually broke something. The original PR was at #668

**Comment by bantu** [comment]
Left a comment the original PR: https://github.com/phpseclib/phpseclib/commit/2fee2d4f98761b6543d467166ad5143780aa0830#commitcomment-12612196

**Comment by terrafrost** [comment]
I wish I had never merged that PR meh :( I'll submit a PR shortly to revert this.

**Comment by bantu** [comment]
@terrafrost Hehe. Shit happens. I guess the takeaway from this is that things aren't always as easy as they seem.

**Comment by bantu** [comment]
Fixed by #769
