### ISSUE TITLE
Use PHP7 random_bytes() when possible

### ISSUE THREAD

**Issue by cweagans** [phpseclib/phpseclib#784]
I haven't done any benchmarking yet, but I think conceptually it makes sense to use this function when it's available. `openssl_random_pseudo_bytes()` is usually good enough, but there are some rare cases where it won't return cryptographically secure random bytes. `random_bytes()` works on all PHP-supported platforms and guarantees security in all cases.

**Comment by GrahamCampbell** [comment]
Yeh, Laravel does this.

**Comment by GrahamCampbell** [comment]
> random_bytes() works on all PHP-supported platforms and guarantees security in all cases.

In PHP 7.0+ only though. ;)

**Comment by cweagans** [comment]
Right :)

**Comment by terrafrost** [comment]
I agree. I think we can add it in the current versions with the caveat that a check be done on the PHP version to make sure it's available.

**Comment by bantu** [comment]
Fixed by #794
