### ISSUE TITLE
Using phpseclib in laravel 5

### ISSUE THREAD

**Issue by rvu95** [phpseclib/phpseclib#788]
How to include Crypt/RSA.php in my model/controller in laravel 5? I'm trying to include that but this always appear "AppClass 'App\Crypt_RSA' not found". Any idea? Thanks in advance.

**Comment by GrahamCampbell** [comment]
What?

**Comment by GrahamCampbell** [comment]
Put `use Crypt_RSA;` at the top of the file, then just reference `Crypt_RSA`. You want nothing to do with "App".

**Comment by GrahamCampbell** [comment]
Laravel 5 is no different to any other psr4 php project in existance.

**Comment by rvu95** [comment]
i see, my bad, thanks in advance
