### ISSUE TITLE
Adopt PSR-2 (coding standards)

### ISSUE THREAD

**Issue by cweagans** [phpseclib/phpseclib#795]
I think that phpseclib should adopt PSR-2 for the following reasons:

1. It's easy. Simply run it through https://github.com/FriendsOfPhp/PHP-CS-Fixer
2. phpcs, scrutinizer-ci, and SensioLabs Insight all understand PSR-2, and can accurately detect and flag coding standards errors on every PR.
3. I don't see any place where the phpseclib's coding standards are officially stated/documented, and doing this avoids having to go through the process of doing so - we can just say "PSR-2" and people will immediately understand what it is.
4. Many PHP IDEs have built-in support/configuration for PSR-2 coding standards.

**Comment by cweagans** [comment]
I guess build/code-sniffer-ruleset.xml already sort of uses PSR-2? Maybe? There's a lot of exceptions though. Would it be worthwhile to fully adopt the standard?

**Comment by GrahamCampbell** [comment]
How about you enable https://styleci.io?

**Comment by GrahamCampbell** [comment]
> phpcs, scrutinizer-ci, and SensioLabs Insight all understand PSR-2, and can accurately detect and flag coding standards errors on every PR.

StyleCI will do a much better job of that, and actually provide a diff contributors can apply in seconds. Also, if a PR does get merged that has cs errors, after merge, you can get styleci to actually send you a pull request with the fixes. :P

**Comment by bantu** [comment]
PSR2 is basically already adopted. For exceptions and why, please read https://github.com/phpseclib/phpseclib/blob/master/build/code-sniffer-ruleset.xml#L6 Code Sniffer can a) be used locally and b) on Travis CI to enforce coding style PRs and blessed branches. I think this ticket should be closed.
