### ISSUE TITLE
Travis CI PHP versions

### ISSUE THREAD

**Issue by cweagans** [phpseclib/phpseclib#796]
Right now, Travis tests these versions:

```
php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm
```

Most of these make sense, but I'm a little confused about why we're explicitly testing PHP 5.3.3. Is there some reason for that?

**Comment by GrahamCampbell** [comment]
Yes, because php 5.3.3 is the lowest version supported, and we have version specific code for that version too, and for 5.3.4 too, for example.

**Comment by GrahamCampbell** [comment]
Unless we test on 5.3.3, there is 0 evidence it's actually supported.

**Comment by bantu** [comment]
Yes, tests are run on 5.3.3 because that is the minimum supported version. Please note that code coverage has improved but could still be better. http://phpseclib.bantux.org/code_coverage/master/latest/PHP-5.5.9/
