### ISSUE TITLE
PHP 5.4 incompatibility

### ISSUE THREAD

**Issue by splufer** [phpseclib/phpseclib#831]
Parsing the source code with PHP Compatibility check for PHP_CodeSniffer [https://github.com/wimg/PHPCompatibility] i found this errors

FILE: phpseclib1.0.0/File/X509.php
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
----------------------------------------------------------------------
 4417 | ERROR | Using a call-time pass-by-reference is prohibited since php 5.4
 4442 | ERROR | Using a call-time pass-by-reference is prohibited since php 5.4
 4509 | ERROR | Using a call-time pass-by-reference is prohibited since php 5.4
 4581 | ERROR | Using a call-time pass-by-reference is prohibited since php 5.4
----------------------------------------------------------------------

**Comment by terrafrost** [comment]
You've created this ticket before. #337. That tool was in error then and it is in error now.
