### ISSUE TITLE
Incorrect use of clone

### ISSUE THREAD

**Issue by splufer** [phpseclib/phpseclib#832]
Parsing the source code with PHP Compatibility check for PHP_CodeSniffer [https://github.com/wimg/PHPCompatibility] i found this errors:

FILE: phpseclib1.0.0/File/ANSI.php
----------------------------------------------------------------------
FOUND 5 ERRORS AFFECTING 5 LINES
----------------------------------------------------------------------
 191 | ERROR | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)
 192 | ERROR | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)
 333 | ERROR | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)
 403 | ERROR | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)
 422 | ERROR | 'clone' is a reserved keyword introduced in PHP version 5.0 and cannot be invoked as a function (T_CLONE)
----------------------------------------------------------------------

An object copy is created by using the clone keyword
$copy_of_object = clone $object;

**Comment by terrafrost** [comment]
```php
<?php
error_reporting(E_ALL);

clone(new stdClass());
```

I don't get any sort of error at all. Not an E_NOTICE, not an E_STRICT, nothing.

Give me a version of PHP that this is an issue on and appropriate action can be taken but being red flagged by some static code analysis tool just isn't a reason to change.

The reason why it's doing it is to maintain BC. The 1.0 branch is compatible with PHP assuming the use of PHP_Compat. Here's how PHP_Compat emulates `clone` on PHP 4:

https://github.com/pear/PHP_Compat/blob/master/Compat/Function/clone.php
