### ISSUE TITLE
SFTP via SOCKS5 or HTTP(S) proxy

### ISSUE THREAD

**Issue by auro1** [phpseclib/phpseclib#839]
Hey.

I'm in a cloud environment and I need to access specific services via static IPs. I have found a service where I can get static IPs via a SOCKS5 or HTTP(S) proxy.

I need to access a SFTP-server to retrive various files and the server is protected by a firewall which whitelists IPs.

I've looked through stackoverflow and the entire documentation to no avil.

**Comment by terrafrost** [comment]
In theory it should be possible. You set the socket up as appropriate and then pass the socket to the Net_SSH2 constructor. Here's an example:

https://github.com/phpseclib/phpseclib/issues/742#issuecomment-122351289

In practice, however, I've not really had much luck with SOCKS5 tunneling. Here's the test script I've been using:

```php
<?php
$port = 22;
$host = 'www.domain.tld';
$user = 'username';
$pass = 'password';

//$port = 80;
//$host = 'www.google.com';

include('Net/SFTP.php');

$start = microtime(true);
$fsock = fsockopen('127.0.0.1', 9150);

echo "fsockopen success\n";

$port = chr($port >> 8) . chr($port & 255);
$address = gethostbyname($host);
$address = implode('', array_map('chr', explode('.', $address)));

$request = "\5\1\0";

if (fputs($fsock,$request) != strlen($request)) {
   exit("premature termination"); 
}
echo "first packet sent\n";
$response = fgets($fsock);
echo "first packet rcvd\n";

if (strlen($response) != 2 && substr($response, 0, 2) != "\5\0") {
   exit("Unsupported protocol or unsupported method");
}

$request = "\5\1\0\1" . $address . $port;
if (fputs($fsock, $request) != strlen($request)) {
   exit("premature termination");
}
echo "second packet sent\n";

$response = fgets($fsock);
echo "second packet rcvd\n";

$elapsed = microtime(true) - $start;

echo "took $elapsed seconds"; exit;

// we don't check the response size since that can very depending on whether or not the outside world sees an IPv4 or IPv6 address.  Why the outside world would see an IPv6 address when IPv4 is all that this script uses, I don't know, but bleh 
if (substr($response, 0, 2) != "\5\0") {
   exit("Unsupported protocol or connection refused");
}
/*
fputs($fsock, "GET / HTTP/1.0\r\n");
fputs($fsock, "Host: www.google.com\r\n\r\n");

while (!feof($fsock)) {
	echo fread($fsock, 1024);
} exit;
*/
echo "connecting via sftp\n";

$ssh = new Net_SFTP($fsock);
$ssh->login($user, $pass);

print_r($ssh->nlist());
```

Using that script I can get a response from google.com, through the SOCK5 proxy, but I've not had any luck actually connecting to an SSH server. The SOCKS5 proxy I tried it on was created by PuTTY and, well, here's a post on superuser.com describing the issue:

http://superuser.com/q/983503/172193

I've also tried to connect to an SSH server through a Tor-created SOCKS5 proxy to no avail. I have no idea as to why.

The above test script is definitely hacked together and if I could actually get it working I'd clean it up but I just can't. Not with SSH..

**Comment by auro1** [comment]
I've got a pull request and a repo branch for working with this. Anyone who wants to lend a hand, I'll give you write access

https://github.com/phpseclib/phpseclib/pull/872
https://github.com/MunkSoftware/phpseclib

**Comment by terrafrost** [comment]
#1460 demos SOCKS5 proxy support. https://github.com/phpseclib/phpseclib/issues/1339#issuecomment-462224179 demonstrates HTTP proxy support.
