### ISSUE TITLE
Now got a full-time job

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#841]
Hey,

I recently accepted a full-time position. Not sure I will have the time to contribute to this project in the long run. I certainly will need quite some time adjusting to it and probably can not contribute any of my time the next few weeks.

Cheers

**Comment by terrafrost** [comment]
Well I hope we don't lose you! I value your feedback and your contributions.

None-the-less, congrats on the full-time job and good luck with it!!

**Comment by bantu** [comment]
Thank you.
