### ISSUE TITLE
Clarifying random_bytes() behavior in PHP 7

### ISSUE THREAD

**Issue by paragonie-scott** [phpseclib/phpseclib#843]
Re: https://github.com/phpseclib/phpseclib/blob/0ba1a04c05de04fba9d09ae5b7b33b2399541dca/phpseclib/Crypt/Random.php#L60

`random_bytes()` will throw:

* `Exception` in the event of a catastrophic CSPRNG failure
* `TypeError` if `zend_parse_parameters` fails
* `Error` if `$length` is less than or equal to 0

**Comment by paragonie-scott** [comment]
Also

https://github.com/phpseclib/phpseclib/blob/0ba1a04c05de04fba9d09ae5b7b33b2399541dca/phpseclib/Crypt/Random.php#L73

Probably should pass `MCRYPT_DEV_URANDOM` to `mcrypt_create_iv()` ;)

**Comment by GrahamCampbell** [comment]
So we need to catch Throwable rather than Error?

**Comment by GrahamCampbell** [comment]
> Probably should pass MCRYPT_DEV_URANDOM to mcrypt_create_iv() ;)

Could you send a PR please?

**Comment by paragonie-scott** [comment]
Sure. Want me to address both?

**Comment by GrahamCampbell** [comment]
Could you do it in two PRs please?

**Comment by terrafrost** [comment]
I'm gonna close this since it's addressed by PR's now.

**Comment by bantu** [comment]
@terrafrost Please do not close ticket that have not actually been addressed yet (i.e. PR actually merged).
