### ISSUE TITLE
can not use loadKey with generated OpenPGP key

### ISSUE THREAD

**Issue by DanielRuf** [phpseclib/phpseclib#858]
When I try to use `loadKey` with a generated public key from OpenPGP (RSA 1024), `encrypt` results in false. Are these keys not supported? Tried it with phpseclib 1.0.0 and 2.0.0.

**Comment by terrafrost** [comment]
No. Based on my limited understanding, PGP / GPG keys have a lot more info in them then just an RSA key. In that regard they're more akin to an X.509 certificate than they are a pure RSA key. ie. X.509 certificates are essentially containers for the transport of public keys so based on that one might think that RSA.php ought to be able to load X.509 certs, but I think X509.php is better suited for that purpose. And similarly, it seems like a PGP.php would be similarly better for PGP keys.
