### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by Ferbla** [phpseclib/phpseclib#859]
I am getting errors when I try to use the login function. I looked around and couldn't seem to find a fix for it. 

Here is the output of my logs.

Notice: No compatible server to client encryption algorithms found in /var/www/html/noc/functions/Net/SSH2.php on line 1375 

<- 00000000 53:53:48:2d:32:2e:30:2d:4f:70:65:6e:53:53:48:5f SSH-2.0-OpenSSH_ 00000010 36:2e:36:2e:31:0d:0a 6.6.1.. -> 00000000 53:53:48:2d:32:2e:30:2d:70:68:70:73:65:63:6c:69 SSH-2.0-phpsecli 00000010 62:5f:30:2e:33:20:28:6f:70:65:6e:73:73:6c:2c:20 b_0.3 (openssl, 00000020 67:6d:70:29:0d:0a gmp).. <- NET_SSH2_MSG_KEXINIT (since last: 0.0201, network: 0.005s) 00000000 a6:e2:cc:44:22:ab:e1:d9:27:8c:75:63:09:41:ef:95 ...D"...'.uc.A.. 00000010 00:00:00:d4:63:75:72:76:65:32:35:35:31:39:2d:73 ....curve25519-s 00000020 68:61:32:35:36:40:6c:69:62:73:73:68:2e:6f:72:67 ha256@libssh.org 00000030 2c:65:63:64:68:2d:73:68:61:32:2d:6e:69:73:74:70 ,ecdh-sha2-nistp 00000040 32:35:36:2c:65:63:64:68:2d:73:68:61:32:2d:6e:69 256,ecdh-sha2-ni 00000050 73:74:70:33:38:34:2c:65:63:64:68:2d:73:68:61:32 stp384,ecdh-sha2 00000060 2d:6e:69:73:74:70:35:32:31:2c:64:69:66:66:69:65 -nistp521,diffie 00000070 2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d:65 -hellman-group-e 00000080 78:63:68:61:6e:67:65:2d:73:68:61:32:35:36:2c:64 xchange-sha256,d 00000090 69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72 iffie-hellman-gr 000000a0 6f:75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61 oup-exchange-sha 000000b0 31:2c:64:69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e 1,diffie-hellman 000000c0 2d:67:72:6f:75:70:31:34:2d:73:68:61:31:2c:64:69 -group14-sha1,di 000000d0 66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f ffie-hellman-gro 000000e0 75:70:31:2d:73:68:61:31:00:00:00:27:73:73:68:2d up1-sha1...'ssh- 000000f0 72:73:61:2c:65:63:64:73:61:2d:73:68:61:32:2d:6e rsa,ecdsa-sha2-n 00000100 69:73:74:70:32:35:36:2c:73:73:68:2d:65:64:32:35 istp256,ssh-ed25 00000110 35:31:39:00:00:00:e9:61:65:73:31:32:38:2d:63:74 519....aes128-ct 00000120 72:2c:61:65:73:31:39:32:2d:63:74:72:2c:61:65:73 r,aes192-ctr,aes 00000130 32:35:36:2d:63:74:72:2c:61:72:63:66:6f:75:72:32 256-ctr,arcfour2 00000140 35:36:2c:61:72:63:66:6f:75:72:31:32:38:2c:61:65 56,arcfour128,ae 00000150 73:31:32:38:2d:67:63:6d:40:6f:70:65:6e:73:73:68 s128-gcm@openssh 00000160 2e:63:6f:6d:2c:61:65:73:32:35:36:2d:67:63:6d:40 .com,aes256-gcm@ 00000170 6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:63:68:61:63 openssh.com,chac 00000180 68:61:32:30:2d:70:6f:6c:79:31:33:30:35:40:6f:70 ha20-poly1305@op 00000190 65:6e:73:73:68:2e:63:6f:6d:2c:61:65:73:31:32:38 enssh.com,aes128 000001a0 2d:63:62:63:2c:33:64:65:73:2d:63:62:63:2c:62:6c -cbc,3des-cbc,bl 000001b0 6f:77:66:69:73:68:2d:63:62:63:2c:63:61:73:74:31 owfish-cbc,cast1 000001c0 32:38:2d:63:62:63:2c:61:65:73:31:39:32:2d:63:62 28-cbc,aes192-cb 000001d0 63:2c:61:65:73:32:35:36:2d:63:62:63:2c:61:72:63 c,aes256-cbc,arc 000001e0 66:6f:75:72:2c:72:69:6a:6e:64:61:65:6c:2d:63:62 four,rijndael-cb 000001f0 63:40:6c:79:73:61:74:6f:72:2e:6c:69:75:2e:73:65 c@lysator.liu.se 00000200 00:00:00:e9:61:65:73:31:32:38:2d:63:74:72:2c:61 ....aes128-ctr,a 00000210 65:73:31:39:32:2d:63:74:72:2c:61:65:73:32:35:36 es192-ctr,aes256 00000220 2d:63:74:72:2c:61:72:63:66:6f:75:72:32:35:36:2c -ctr,arcfour256, 00000230 61:72:63:66:6f:75:72:31:32:38:2c:61:65:73:31:32 arcfour128,aes12 00000240 38:2d:67:63:6d:40:6f:70:65:6e:73:73:68:2e:63:6f 8-gcm@openssh.co 00000250 6d:2c:61:65:73:32:35:36:2d:67:63:6d:40:6f:70:65 m,aes256-gcm@ope 00000260 6e:73:73:68:2e:63:6f:6d:2c:63:68:61:63:68:61:32 nssh.com,chacha2 00000270 30:2d:70:6f:6c:79:31:33:30:35:40:6f:70:65:6e:73 0-poly1305@opens 00000280 73:68:2e:63:6f:6d:2c:61:65:73:31:32:38:2d:63:62 sh.com,aes128-cb 00000290 63:2c:33:64:65:73:2d:63:62:63:2c:62:6c:6f:77:66 c,3des-cbc,blowf 000002a0 69:73:68:2d:63:62:63:2c:63:61:73:74:31:32:38:2d ish-cbc,cast128- 000002b0 63:62:63:2c:61:65:73:31:39:32:2d:63:62:63:2c:61 cbc,aes192-cbc,a 000002c0 65:73:32:35:36:2d:63:62:63:2c:61:72:63:66:6f:75 es256-cbc,arcfou 000002d0 72:2c:72:69:6a:6e:64:61:65:6c:2d:63:62:63:40:6c r,rijndael-cbc@l 000002e0 79:73:61:74:6f:72:2e:6c:69:75:2e:73:65:00:00:01 ysator.liu.se... 000002f0 92:68:6d:61:63:2d:6d:64:35:2d:65:74:6d:40:6f:70 .hmac-md5-etm@op 00000300 65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73 enssh.com,hmac-s 00000310 68:61:31:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e ha1-etm@openssh. 00000320 63:6f:6d:2c:75:6d:61:63:2d:36:34:2d:65:74:6d:40 com,umac-64-etm@ 00000330 6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63 openssh.com,umac 00000340 2d:31:32:38:2d:65:74:6d:40:6f:70:65:6e:73:73:68 -128-etm@openssh 00000350 2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32 .com,hmac-sha2-2 00000360 35:36:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63 56-etm@openssh.c 00000370 6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32 om,hmac-sha2-512 00000380 2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d -etm@openssh.com 00000390 2c:68:6d:61:63:2d:72:69:70:65:6d:64:31:36:30:2d ,hmac-ripemd160- 000003a0 65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c etm@openssh.com, 000003b0 68:6d:61:63:2d:73:68:61:31:2d:39:36:2d:65:74:6d hmac-sha1-96-etm 000003c0 40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61 @openssh.com,hma 000003d0 63:2d:6d:64:35:2d:39:36:2d:65:74:6d:40:6f:70:65 c-md5-96-etm@ope 000003e0 6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:6d:64 nssh.com,hmac-md 000003f0 35:2c:68:6d:61:63:2d:73:68:61:31:2c:75:6d:61:63 5,hmac-sha1,umac 00000400 2d:36:34:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c -64@openssh.com, 00000410 75:6d:61:63:2d:31:32:38:40:6f:70:65:6e:73:73:68 umac-128@openssh 00000420 2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:32:2d:32 .com,hmac-sha2-2 00000430 35:36:2c:68:6d:61:63:2d:73:68:61:32:2d:35:31:32 56,hmac-sha2-512 00000440 2c:68:6d:61:63:2d:72:69:70:65:6d:64:31:36:30:2c ,hmac-ripemd160, 00000450 68:6d:61:63:2d:72:69:70:65:6d:64:31:36:30:40:6f hmac-ripemd160@o 00000460 70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d penssh.com,hmac- 00000470 73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:6d:64:35 sha1-96,hmac-md5 00000480 2d:39:36:00:00:01:92:68:6d:61:63:2d:6d:64:35:2d -96....hmac-md5- 00000490 65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c etm@openssh.com, 000004a0 68:6d:61:63:2d:73:68:61:31:2d:65:74:6d:40:6f:70 hmac-sha1-etm@op 000004b0 65:6e:73:73:68:2e:63:6f:6d:2c:75:6d:61:63:2d:36 enssh.com,umac-6 000004c0 34:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f 4-etm@openssh.co 000004d0 6d:2c:75:6d:61:63:2d:31:32:38:2d:65:74:6d:40:6f m,umac-128-etm@o 000004e0 70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d penssh.com,hmac- 000004f0 73:68:61:32:2d:32:35:36:2d:65:74:6d:40:6f:70:65 sha2-256-etm@ope 00000500 6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68 nssh.com,hmac-sh 00000510 61:32:2d:35:31:32:2d:65:74:6d:40:6f:70:65:6e:73 a2-512-etm@opens 00000520 73:68:2e:63:6f:6d:2c:68:6d:61:63:2d:72:69:70:65 sh.com,hmac-ripe 00000530 6d:64:31:36:30:2d:65:74:6d:40:6f:70:65:6e:73:73 md160-etm@openss 00000540 68:2e:63:6f:6d:2c:68:6d:61:63:2d:73:68:61:31:2d h.com,hmac-sha1- 00000550 39:36:2d:65:74:6d:40:6f:70:65:6e:73:73:68:2e:63 96-etm@openssh.c 00000560 6f:6d:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2d:65 om,hmac-md5-96-e 00000570 74:6d:40:6f:70:65:6e:73:73:68:2e:63:6f:6d:2c:68 tm@openssh.com,h 00000580 6d:61:63:2d:6d:64:35:2c:68:6d:61:63:2d:73:68:61 mac-md5,hmac-sha 00000590 31:2c:75:6d:61:63:2d:36:34:40:6f:70:65:6e:73:73 1,umac-64@openss 000005a0 68:2e:63:6f:6d:2c:75:6d:61:63:2d:31:32:38:40:6f h.com,umac-128@o 000005b0 70:65:6e:73:73:68:2e:63:6f:6d:2c:68:6d:61:63:2d penssh.com,hmac- 000005c0 73:68:61:32:2d:32:35:36:2c:68:6d:61:63:2d:73:68 sha2-256,hmac-sh 000005d0 61:32:2d:35:31:32:2c:68:6d:61:63:2d:72:69:70:65 a2-512,hmac-ripe 000005e0 6d:64:31:36:30:2c:68:6d:61:63:2d:72:69:70:65:6d md160,hmac-ripem 000005f0 64:31:36:30:40:6f:70:65:6e:73:73:68:2e:63:6f:6d d160@openssh.com 00000600 2c:68:6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d ,hmac-sha1-96,hm 00000610 61:63:2d:6d:64:35:2d:39:36:00:00:00:15:6e:6f:6e ac-md5-96....non 00000620 65:2c:7a:6c:69:62:40:6f:70:65:6e:73:73:68:2e:63 e,zlib@openssh.c 00000630 6f:6d:00:00:00:15:6e:6f:6e:65:2c:7a:6c:69:62:40 om....none,zlib@ 00000640 6f:70:65:6e:73:73:68:2e:63:6f:6d:00:00:00:00:00 openssh.com..... 00000650 00:00:00:00:00:00:00:00 ........ -> NET_SSH2_MSG_KEXINIT (since last: 0.0007, network: 0s) 00000000 5a:cc:50:86:48:db:f8:10:1e:f1:98:34:59:7a:5b:11 Z.P.H......4Yz[. 00000010 00:00:00:7e:64:69:66:66:69:65:2d:68:65:6c:6c:6d ...~diffie-hellm 00000020 61:6e:2d:67:72:6f:75:70:31:2d:73:68:61:31:2c:64 an-group1-sha1,d 00000030 69:66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72 iffie-hellman-gr 00000040 6f:75:70:31:34:2d:73:68:61:31:2c:64:69:66:66:69 oup14-sha1,diffi 00000050 65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f:75:70:2d e-hellman-group- 00000060 65:78:63:68:61:6e:67:65:2d:73:68:61:31:2c:64:69 exchange-sha1,di 00000070 66:66:69:65:2d:68:65:6c:6c:6d:61:6e:2d:67:72:6f ffie-hellman-gro 00000080 75:70:2d:65:78:63:68:61:6e:67:65:2d:73:68:61:32 up-exchange-sha2 00000090 35:36:00:00:00:0f:73:73:68:2d:72:73:61:2c:73:73 56....ssh-rsa,ss 000000a0 68:2d:64:73:73:00:00:00:00:00:00:00:00:00:00:00 h-dss........... 000000b0 39:68:6d:61:63:2d:73:68:61:32:2d:32:35:36:2c:68 9hmac-sha2-256,h 000000c0 6d:61:63:2d:73:68:61:31:2d:39:36:2c:68:6d:61:63 mac-sha1-96,hmac 000000d0 2d:73:68:61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39 -sha1,hmac-md5-9 000000e0 36:2c:68:6d:61:63:2d:6d:64:35:00:00:00:39:68:6d 6,hmac-md5...9hm 000000f0 61:63:2d:73:68:61:32:2d:32:35:36:2c:68:6d:61:63 ac-sha2-256,hmac 00000100 2d:73:68:61:31:2d:39:36:2c:68:6d:61:63:2d:73:68 -sha1-96,hmac-sh 00000110 61:31:2c:68:6d:61:63:2d:6d:64:35:2d:39:36:2c:68 a1,hmac-md5-96,h 00000120 6d:61:63:2d:6d:64:35:00:00:00:04:6e:6f:6e:65:00 mac-md5....none. 00000130 00:00:04:6e:6f:6e:65:00:00:00:00:00:00:00:00:00 ...none......... 00000140 00:00:00:00 ....

**Comment by terrafrost** [comment]
My guess: your include path isn't properly setup.

Since 0.3.6, phpseclib has been building the list of symmetric ciphers that it supports off of the loadable symmetric cipher libraries available:

https://github.com/phpseclib/phpseclib/commit/adf8afd4eb7566615decfc65892266d21f49612c#diff-82a5983a6daace4acbcc65edf2dfb605

It's evolved away from `file_exists` since that commit but, none-the-less, it builds that list based off of what it thinks is loadable.

Also, it's hard to really read your logs since you didn't use the <pre> tags when getting the output (I'm guessing you got it via a web browser?). Of course the fact that you didn't get <pre> tags makes me think you're using a really old version of phpseclib since phpseclib has been outputting <pre> if the sapi isn't CLI since 0.3.6:

https://github.com/phpseclib/phpseclib/commit/093a18290493635a697471a8a67ace5335001335

And before that - since 0.3.0 - it was adding <pre> tags unconditionally:

https://github.com/phpseclib/phpseclib/commit/7ef3108d0092d5c639fb378c3cd41ed42bc136fd

Also, since 0.3.6, phpseclib has been building the list of symmetric ciphers that it supports off of the loadable symmetric cipher libraries available:

https://github.com/phpseclib/phpseclib/commit/adf8afd4eb7566615decfc65892266d21f49612c#diff-82a5983a6daace4acbcc65edf2dfb605

So I'd recommend two things.

1. Make sure you're running the latest version of phpseclib
2. Check your include_path

**Comment by Ferbla** [comment]
I reinstalled phpseclib, and now it is working. Something must have went wrong on the first install. Thanks for your help

**Comment by emxjay** [comment]
I've encountered the same issue with v1.0.1, and as mentioned by @terrafrost, the include path must be set correctly.

For instance, in order for [this example](http://phpseclib.sourceforge.net/ssh/auth.html) to work properly, you should add something like this at the beginning:

`set_include_path(get_include_path() . PATH_SEPARATOR . 'phpseclib1.0.1');`

Cheers.
