### ISSUE TITLE
cd seems not to work

### ISSUE THREAD

**Issue by Ne00n** [phpseclib/phpseclib#860]
Hey,

I am try to figure out why cd isnt working since some hours, for example:

echo  $ssh->exec('cd /home/'.$user.'/templates/'.$row[1] . '; pwd;');
echo  $ssh->exec('pwd');

Gives me this:

/home/prometheus/templates/Garrysmod
/home/prometheus 

Eh? I am using the 1.0 Release on PHP 5.6

Thanks.

**Comment by terrafrost** [comment]
See http://phpseclib.sourceforge.net/ssh/examples.html#chdir

Basically, each exec() is performed in it's own self contained session. It's like each exec() is opening up it's own terminal window, running the command and then immediately closing the terminal window. So the second pwd is essentially being executed in an entirely different terminal window.

Interactive shell does not behave this way:

http://phpseclib.sourceforge.net/ssh/examples.html#interactive

**Comment by Ne00n** [comment]
Ah Okay, Thanks!

**Comment by shreyansh9226** [comment]
@terrafrost Thanks so much, I was messing around with this for 2 hours now & finally stumbled upon your answer.
