### ISSUE TITLE
IPV6 Connectivity

### ISSUE THREAD

**Issue by MaximilianKindshofer** [phpseclib/phpseclib#869]
Hi Iam trying to connect via SFTP to an IPV6 Host (via Owncloud) apperently there is a Problem parsing the Adress (with and without Bracets): 

Cannot connect to 2a00:61e0. Error 0. php_network_getaddresses: getaddrinfo failed: Name or service not known at /var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#1011 

Cannot connect to [2a00:61e0. Error 0. Failed to parse IPv6 address "[2a00:61" at /var/www/owncloud/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php#1011

**Comment by bantu** [comment]
We are using fsockopen(). See the IPv6 hint on http://php.net/manual/en/function.fsockopen.php which says that v6 addresses are supposed to be entered using brackets. However, "[2a00:61e0" is not syntactially correct as it has an opening bracket but no closing bracket. My guess would be that you entered the address correctly, but ownCloud does not support it properly. cc @PVince81

**Comment by MaximilianKindshofer** [comment]
I double checked if I entered the IP Adress correctly:
[2a00:61e0:4068:XXXX:XXX:XXXX:XXXX:XXXX]
However only the first two doubleoctets are handed over as it seams. As I am not familiar with the codebase I don't know where the error occours.

Apperently it had worked some time ago:
https://forum.owncloud.org/viewtopic.php?f=29&t=24802

**Comment by bantu** [comment]
@MaximilianKindshofer Which version of ownCloud are you using?

**Comment by MaximilianKindshofer** [comment]
Iam using
ownCloud 8.2.0 (stable)

**Comment by bantu** [comment]
Problem is likely here: https://github.com/owncloud/core/blob/v8.2.0/apps/files_external/lib/sftp.php#L70-L75 Feel free to report to ownCloud.

**Comment by MaximilianKindshofer** [comment]
Thanks for your time!
