### ISSUE TITLE
Something wrong with the PHP7 environments,

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#878]
https://travis-ci.org/phpseclib/phpseclib/builds/91995569
https://travis-ci.org/phpseclib/phpseclib/builds/91995578

**Comment by GrahamCampbell** [comment]
Just travis being shit. It's happening to everyone.

**Comment by bantu** [comment]
Can you link to the upstream ticket then?

**Comment by terrafrost** [comment]
This seems to be working now.
