### ISSUE TITLE
Unit_Crypt_RSA_LoadKeyTest::testPKCS8Only fails on master.

### ISSUE THREAD

**Issue by bantu** [phpseclib/phpseclib#879]
https://travis-ci.org/phpseclib/phpseclib/builds/91995578

**Comment by terrafrost** [comment]
Seems to be working fine here?:

https://travis-ci.org/terrafrost/phpseclib/builds/92517587

**Comment by terrafrost** [comment]
I was able to reproduce the problem in the 2.0 branch. #893 fixes it. I couldn't, however, duplicate it in the master branch. #894 elaborates.
