### ISSUE TITLE
No output from command on one particular server

### ISSUE THREAD

**Issue by marcelgwerder** [phpseclib/phpseclib#880]
Today I was unable to deploy my application with rocketeer and I tracked the issue down to phpseclib.

Rocketeer executes the following command to check if a file or directory exists:
```
[ -e "/var/www/example.com" ] && echo "true"
```
When I execute the command in putty it outputs `true` if the file/directory exists and nothing if it doesn't, like it should. 

When executed via phpseclib the output is always empty.
I was able to reproduce the issue outside of rocketeer and using the master branch:
```php
<?php 
require __DIR__ . '/vendor/autoload.php';

use phpseclib\Net\SSH2;

$ssh = new SSH2('example.com');
if (!$ssh->login('user', 'pw')) {
    exit('Login Failed');
}

echo $ssh->exec('[ -e "/var/www/example.com" ] && echo "true"');
```

This only happens on this particular server which is actually a managed server so I can't give you a lot of information at least not without opening a support ticket.
It also only happens with this command or this is at least the first one I ran into.

Any ideas what could be the issue here and what I can do to debug it?

**Comment by terrafrost** [comment]
The first thing I'd do is look at the logs. You can get them by doing `define('NET_SSH2_LOGGING', SSH2::LOG_COMPLEX);` at the top of the file (well, after you include your auto loader) and then `$ssh->getLogs()` after the `$ssh->exec()`.

In lieu of having seen the logs...  it's possible enabling a PTY would help:

http://phpseclib.sourceforge.net/ssh/pty.html

You may also need to run the command in an interactive shell:

http://phpseclib.sourceforge.net/ssh/examples.html#interactive

**Comment by marcelgwerder** [comment]
Hmm neither enabling pty nor the interactive shell solve the problem. I figured out that the `&&` construct is the problem and it doesn't matter which command I use with it.

```
echo "1" && echo "2"
``` 
On one of my servers I get `1 2` and on the other one I get `1`.

Here is the part of the log I suspect to be the part where the command is executed. I don't know this ssh stuff well so I cut out what looks like the auth part to me just to avoid posting sensitive information.

Success (output `1 2`):
```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0004, network: 0.0001s) 00000000 00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:00:7f ....session..... 00000010 ff:ff:ff:00:00:40:00 .....@. <- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.0028, network: 0.0001s) 00000000 00:00:00:00:00:00:00:00:00:00:00:00:00:00:80:00 ................ -> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0004, network: 0.0001s) 00000000 00:00:00:00:00:00:00:04:65:78:65:63:01:00:00:00 ........exec.... 00000010 14:65:63:68:6f:20:22:31:22:20:26:26:20:65:63:68 .echo "1" && ech 00000020 6f:20:22:32:22 o "2" <- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.0014, network: 0.0001s) 00000000 00:00:00:00:00:20:00:00 ..... .. <- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0002, network: 0.0001s) 00000000 00:00:00:00 .... <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0022, network: 0.0002s) 00000000 00:00:00:00:00:00:00:02:31:0a ........1. <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.0004, network: 0.0001s) 00000000 00:00:00:00:00:00:00:02:32:0a ........2. <- NET_SSH2_MSG_CHANNEL_EOF (since last: 0.0002, network: 0s) 00000000 00:00:00:00 .... <- NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s) 00000000 00:00:00:00:00:00:00:0b:65:78:69:74:2d:73:74:61 ........exit-sta 00000010 74:75:73:00:00:00:00:00 tus..... <- NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0004, network: 0s) 00000000 00:00:00:00 .... -> NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0003, network: 0.0001s) 00000000 00:00:00:00 ....
```

Fail (output `1`):
```
-> NET_SSH2_MSG_CHANNEL_OPEN (since last: 0.0004, network: 0.0001s) 00000000 00:00:00:07:73:65:73:73:69:6f:6e:00:00:00:00:7f ....session..... 00000010 ff:ff:ff:00:00:40:00 .....@. <- NET_SSH2_MSG_CHANNEL_OPEN_CONFIRMATION (since last: 0.2702, network: 0.0001s) 00000000 00:00:00:00:00:00:00:00:00:00:00:00:00:00:80:00 ................ -> NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0004, network: 0.0001s) 00000000 00:00:00:00:00:00:00:04:65:78:65:63:01:00:00:00 ........exec.... 00000010 14:65:63:68:6f:20:22:31:22:20:26:26:20:65:63:68 .echo "1" && ech 00000020 6f:20:22:32:22 o "2" <- NET_SSH2_MSG_CHANNEL_WINDOW_ADJUST (since last: 0.0063, network: 0.0002s) 00000000 00:00:00:00:00:20:00:00 ..... .. <- NET_SSH2_MSG_CHANNEL_SUCCESS (since last: 0.0005, network: 0.0001s) 00000000 00:00:00:00 .... <- NET_SSH2_MSG_CHANNEL_DATA (since last: 0.1379, network: 0.0001s) 00000000 00:00:00:00:00:00:00:02:31:0a ........1. <- NET_SSH2_MSG_CHANNEL_EOF (since last: 0.0002, network: 0s) 00000000 00:00:00:00 .... <- NET_SSH2_MSG_CHANNEL_REQUEST (since last: 0.0002, network: 0s) 00000000 00:00:00:00:00:00:00:0b:65:78:69:74:2d:73:74:61 ........exit-sta 00000010 74:75:73:00:00:00:00:00 tus..... <- NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0002, network: 0s) 00000000 00:00:00:00 .... -> NET_SSH2_MSG_CHANNEL_CLOSE (since last: 0.0002, network: 0.0001s) 00000000 00:00:00:00 ....
```

Does this help in any way? The only thing I can directly see is that the log from the failing server lacks a second `NET_SSH2_MSG_CHANNEL_DATA `.

**Comment by marcelgwerder** [comment]
I was finally able to reproduce this issue on the CLI so this definitely is not related to phpseclib but rather some faulty server setup.

**Comment by terrafrost** [comment]
Glad to here it! And again, sorry for not responding sooner - after the DC conference I was in NYC for Thanksgiving / vacation, so I was a bit distracted with that!
