### ISSUE TITLE
Windows OpenSSH navigation

### ISSUE THREAD

**Issue by mwienk** [phpseclib/phpseclib#892]
Hi,

I cannot use phpseclib as an SFTP client to a Windows server. This is is caused by the fact that the SFTP::_realpath() uses a / in front of the path. Commenting out 

```
if ($path[0] != '/') {
    $path = $this->pwd . '/' . $path;
}
```

and changing

```
return '/' . implode('/', $new);
```

into

```
return implode('/', $new);
```

Lets it all work. But I don't think those statements were made just for fun. Is there any possibility on checking if the root path (/) is actually that system's root path?

**Comment by terrafrost** [comment]
What are you using as your SFTP server software? I've tried phpseclib with a number of different SFTP clients but I don't have a comprehensive list.

**Comment by mwienk** [comment]
I installed sftp as per https://winscp.net/eng/docs/guide_windows_openssh_server, which uses the https://github.com/PowerShell/Win32-OpenSSH sftp server

**Comment by terrafrost** [comment]
The server's implementation of SFTP is buggy. I created a ticket for them. See https://github.com/PowerShell/Win32-OpenSSH/issues/48 . In theory, I could look at the server identifier and handle their server differently but that doesn't work either per https://github.com/PowerShell/Win32-OpenSSH/issues/49 .

So for the time being I'd just stick with your solution until they fix their bugs.

**Comment by terrafrost** [comment]
What I didn't mention in the PowerShell bug reports is that I also tested this on http://www.freesshd.com/ (which identifies as SSH-2.0-WeOnlyDo 2.4.3) and https://www.bitvise.com/ssh-server-download (which identifies as SSH-2.0-SilverSHielD), both of which run on Windows, and neither of them behave as https://github.com/PowerShell/Win32-OpenSSH does.

ie. PowerShell's behavior is departing even from more established Windows SFTP servers.

**Comment by mwienk** [comment]
Ohw wow, thanks for your effort! I'll install another server, I never guessed that the server would've been the problem.
