### ISSUE TITLE
required php extensions

### ISSUE THREAD

**Issue by nimasdj** [phpseclib/phpseclib#905]
Which php extension does this lib use for AES and RSA? mcrypt or openssl?

**Comment by terrafrost** [comment]
AES: openssl, if it's available. If it's not then it uses mcrypt, if that's available. If neither openssl or mcrypt are available it uses it's own internal implementation.

RSA: internal. openssl is only used for key generation and only then if the keys are of a type that openssl can generate. BigInteger.php may use openssl for modular exponentiation. But it'll preferentially use gmp if it's available. If not it'll use openssl (if it's available) in conjunction with bcmath or it's own internal implementation.

The thing with RSA is that OpenSSL just doesn't provide the features that phpseclib offers. It doesn't support multi-prime RSA and in looking at `openssl_public_encrypt` it doesn't look like you can change the hash for OAEP or PKCS1 encryption. `openssl_sign` doesn't appear to support PSS signatures either. And the key formats...  OpenSSL doesn't come anywhere close to supporting the multitude of key formats phpseclib supports. I suppose, in theory, phpseclib could convert the keys and then pass PKCS1 formatted keys to OpenSSL, but meh.
