### ISSUE TITLE
default hash method

### ISSUE THREAD

**Issue by nimasdj** [phpseclib/phpseclib#906]
You should consider to set sha256 as default hash method instead of a weak method like sha1.

**Comment by nimasdj** [comment]
Do you want me a pull request for this?

**Comment by terrafrost** [comment]
It's already the default hash algorithm in the master branch's Hash.php and there's a pending pull request that makes it the default hash algorithm in RSA.php: See #902.

The default will not be changed in either the 1.0 or 2.0 branches as that would be a BC break.

**Comment by nimasdj** [comment]
I meant for AES. See https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/Base.php#L611
Do you consider to have a pending PR for this one too?
