### ISSUE TITLE
How to setIV?

### ISSUE THREAD

**Issue by nimasdj** [phpseclib/phpseclib#910]
Hi,

As we will not now if OpenSSL/MCrypt/Internal will be used, how we will know the iv size of method then call OpenSSL/MCrypt function to generate an IV and assign it to setIV? does phpseclib provide some methods that we can use to generate an IV?

**Comment by nimasdj** [comment]
as about question above I think I found the solution:

```php
switch ($cipher->getEngine()) {

        case 3: // openssl
               $iv_size = openssl_cipher_iv_length('AES-256-CBC');
               $iv = openssl_random_pseudo_bytes($iv_size);
               break;
        case 2: // mcrypt
               $iv_size = mcrypt_get_iv_size(MCRYPT_RIJNDAEL_256, MCRYPT_MODE_CBC);
               $iv = mcrypt_create_iv($iv_size, MCRYPT_RAND);
               break;
        case 1: //internal
               $iv = just something random.
}
```
but as about internal which length do you suggest?

**Comment by terrafrost** [comment]
I would just do `\phpseclib\Crypt\Random::string($iv_size)` (if you're using the 2.0 or master branches).

As for the length of the IV...  do `$cipher->getBlockLength()`.

**Comment by nimasdj** [comment]
@terrafrost there is no getBlockLength() in AES class in v2. There is only one setter method. It seems you forgot to add it for AES.
I added that method in Rijndael as below and it works fine:
```php
/* start my custome */
    function getBlockLength()
    {
        return $this->block_size;
    }
/* end my custome */
```
But I am afraid whenever I update it to a new version my custom goes too. It would be good that you add this method. I am going to do a PR with this method.
