### ISSUE TITLE
phpseclib not autoload with composer loader

### ISSUE THREAD

**Issue by remotehelp** [phpseclib/phpseclib#913]
phpseclib installed via composer and namespaces registered in /vendor/composer/autoload_namespaces.php ('Crypt' => array($vendorDir . '/phpseclib/phpseclib/phpseclib')), but when I try use:
```<?php
use Crypt\RSA;
$loader = require( ../vendor/autoload.php');
$rsa = new RSA;
```
I get
> 'Fatal error: Class 'Crypt\RSA' not found in ...'

Why autoload not work?;(

**Comment by remotehelp** [comment]
Oh... This issue for 0.3.10. After update to 2.0, autoload worked fine as:
```use phpseclib\Crypt\RSA;
$loader = require( ../vendor/autoload.php');
$rsa = new RSA;
```

**Comment by tribulant** [comment]
Without the use of namespaces, you can use autoload and then initialize the class like this:

`$loader = require( ../vendor/autoload.php');
$rsa = new phpseclib\Crypt\RSA();`
