### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by nimasdj** [phpseclib/phpseclib#915]
Hi,

Aren't you going to release a new version that we will have getBlockLength() method as you said and my two methods I did pull request? Is this repository still maintained at all??

**Comment by GrahamCampbell** [comment]
> Is this repository still maintained at all??

Yes...

**Comment by nimasdj** [comment]
So, why don't you consider to release a new version for new methods?

**Comment by GrahamCampbell** [comment]
Because there's no rush to release.

**Comment by nimasdj** [comment]
But your users may rush to use it! :-)

**Comment by GrahamCampbell** [comment]
Well if you want, you can just require `1.0.*@dev`.

**Comment by terrafrost** [comment]
> Aren't you going to release a new version that we will have getBlockLength() method as you said and my two methods I did pull request? Is this repository still maintained at all??

You made your pull request three days ago and you're now wondering if this repo is maintained?

Do realize that I have a regular job and maintaining phpseclib isn't a part of that job's job description.
