### ISSUE TITLE
class_exits with autoload = true breaks spl_autoload_register

### ISSUE THREAD

**Issue by tburschka** [phpseclib/phpseclib#919]
Using class_exists method with autoload = true (which is default) breaks any application if this is using spl_autoload_register. set autoload to false should fix it.

**Comment by terrafrost** [comment]
Composer uses `spl_autoload_register` and phpseclib's current use of `class_exist` isn't breaking anything for that:

https://github.com/composer/composer/blob/5752559ae8837d975dc65976a7ffb77c00276568/src/Composer/Autoload/ClassLoader.php#L279

I mean I think it might make sense to disabling autoloading for this stuff:

https://github.com/phpseclib/phpseclib/blob/94fdbba2aab0a0c6a3554ed879e3fedc94428538/phpseclib/Net/SSH2.php#L1231

But then again if autoloading does take place whenever class_exists is called...  well, having more Crypt_* objects than is required certainly won't hurt anything..

**Comment by terrafrost** [comment]
If you could provide some example code where it is a problem that'd be helpful.

Thanks!

**Comment by torstenburschkaigniti** [comment]
Hi,

sure, i can provide an example, but sleep over it also solves the problem.

	spl_autoload_extensions('.php');
	spl_autoload_register(function ($class) {
	    if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
		$class = str_replace('\\', '/', $class);
	    }
	    if (!file_exists($class . '.php')) {
			throw new \Exception($class . ' not found!');
	    }
	    require_once $class . '.php';
	});

Since \Sodium is an Extension it will crash:

https://github.com/phpseclib/phpseclib/blob/94fdbba2aab0a0c6a3554ed879e3fedc94428538/phpseclib/Net/SSH2.php#L1174

I've modified it first to make it work:

	spl_autoload_extensions('.php');
	spl_autoload_register(function ($class) {
	    if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
		$class = str_replace('\\', '/', $class);
	    }
	    if (file_exists($class . '.php')) {
	        require_once $class . '.php';
	    }
	});

It's working but in my case the best solution is using composer autoload.php file which generate an map for my classes.

But the Case still exits... maybe you should add an condition for extension like this:

https://github.com/phpseclib/phpseclib/blob/94fdbba2aab0a0c6a3554ed879e3fedc94428538/phpseclib/Net/SSH2.php#L1222

**Comment by tburschka** [comment]
Hi,

sure, i can provide an example, but sleep over it also solves the problem.

	spl_autoload_extensions('.php');
	spl_autoload_register(function ($class) {
	    if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
		$class = str_replace('\\', '/', $class);
	    }
	    if (!file_exists($class . '.php')) {
			throw new \Exception($class . ' not found!');
	    }
	    require_once $class . '.php';
	});

Since \Sodium is an Extension it will crash:

https://github.com/phpseclib/phpseclib/blob/94fdbba2aab0a0c6a3554ed879e3fedc94428538/phpseclib/Net/SSH2.php#L1174

I've modified it first to make it work:

	spl_autoload_extensions('.php');
	spl_autoload_register(function ($class) {
	    if (strtoupper(substr(PHP_OS, 0, 3)) !== 'WIN') {
		$class = str_replace('\\', '/', $class);
	    }
	    if (file_exists($class . '.php')) {
	        require_once $class . '.php';
	    }
	});

It's working but in my case the best solution is using composer autoload.php file which generate an map for my classes.

But the Case still exits... maybe you should add an condition for extension like this:

https://github.com/phpseclib/phpseclib/blob/94fdbba2aab0a0c6a3554ed879e3fedc94428538/phpseclib/Net/SSH2.php#L1222

**Comment by bantu** [comment]
As far as I remember, we don't care whether \Sodium is provided by an extension or a third party library, so calling autoloader is intentional.

**Comment by bantu** [comment]
@tburschka I'd argue that this is a bug in your autoloader implementation (the first example you posted). Autoloaders in PHP form a queue and are called one by one until a class is found. By throwing an exception you're interrupting this queue. Any autoloaders registered to run after your autoloader will mever execute at all. Also see e.g. http://stackoverflow.com/a/3813335

**Comment by bantu** [comment]
@tburschka I'll go ahead and assume that what I said makes sense and close this ticket.
