### ISSUE TITLE
Warning while reading identities

### ISSUE THREAD

**Issue by pkruithof** [phpseclib/phpseclib#923]
The `requestIdentities` function in the SSH Agent class yields a warning:

```
PHP Warning:  fread(): Length parameter must be greater than 0 in /home/peter/git/phpseclib/phpseclib/System/SSH/Agent.php on line 172
```

I never had this issue before. I've restarted the ssh-agent, but same result. I'm not sure how to debug this, any ideas?

**Comment by terrafrost** [comment]
Should be fixed with this commit:

https://github.com/phpseclib/phpseclib/commit/0905143fc1f42f7486614060a95a57a433ee5c7c

That commit has been merged into the 2.0 and master branches as well. LMK if it works for you!

**Comment by pkruithof** [comment]
Yep, that fixed it, thanks!

When is a patch release coming out?

**Comment by terrafrost** [comment]
Normally I'd say "whenever I feel like doing the next release" but I was already planning on doing a release this weekend so this'll just be in that release.

**Comment by pkruithof** [comment]
Nice, thanks so much!

**Comment by terrafrost** [comment]
v1.0.1 and v2.0.1 have been tagged and released.
