### ISSUE TITLE
PEAR release 1.0.1 is broken

### ISSUE THREAD

**Issue by remicollet** [phpseclib/phpseclib#930]
All the component released in pear channel as 1.0.1 provides exactly the same file than previos version

     $ tar xf Crypt_RSA-1.0.0.tgz
     $ grep RSA.php package.xml
         <file baseinstalldir="Crypt" name="RSA.php" role="php" md5sum="507829d2c80114c00caf725aa953acd1">

     $ tar xf Crypt_RSA-1.0.0.tgz
     $ grep RSA.php package.xml
         <file baseinstalldir="Crypt" name="RSA.php" role="php" md5sum="507829d2c80114c00caf725aa953acd1">

Same md5sum

     $ grep CRYPT_RSA_PRIVATE_FORMAT_PKCS8 Crypt_RSA-1.0.1/RSA.php 
     define('CRYPT_RSA_PRIVATE_FORMAT_PKCS8', 3);

According to 7339112e1076197566cbd0d2bb8fdb42f008d742 should be 8

This seems critical for people using the PEAR channel and expecting using the last version, especially for a security library.

**Comment by terrafrost** [comment]
Try it now. Thanks for the heads up!

> This seems critical for people using the PEAR channel and expecting using the last version, especially for a security library.

1.0.1 wasn't a critical release. It was more of a "I haven't done a release in a while" release lol

**Comment by remicollet** [comment]
Everything seems ok now
