### ISSUE TITLE
PHP fatal error when generating a random string

### ISSUE THREAD

**Issue by DavidAnderson684** [phpseclib/phpseclib#932]
I have a user, for whom this section in crypt_random_string() / Random::String() (depending on your version) in Crypt/Random.php is causing a PHP fatal error:

```
$v = $seed = $_SESSION['seed'] = pack('H*', sha1(
                serialize($_SERVER) .
                serialize($_POST) .
                serialize($_GET) .
                serialize($_COOKIE) .
                serialize($GLOBALS) .
                serialize($_SESSION) .
                serialize($_OLD_SESSION)
            ));
```
The fatal error is "Fatal error: Call to private method Vc_Manager::__sleep()", and it's coming from the attempt to serialize $GLOBALS.

The object Vc_Manager appears to be from the popular WordPress plugin "Visual Bakery Composer". Looking at https://secure.php.net/manual/en/language.oop5.magic.php#object.sleep, it appears that that's a bug in that plugin - that __sleep() ought to be a public, not a private method. However... it's a bit unfortunate to be triggering PHP fatal errors in other plugins simply in an attempt to get some random data. serialize() can cause other code to be run, which doesn't seem an optimal thing to be doing at this point in the code.

I'd suggest that you have a method which first parses all the things in the to-be-serialized arrays, and removes all the objects, prior to serialisation.

e.g. instead of calling serialize($GLOBALS), call serialize($this->remove_objects($GLOBALS)), with something like this (untested) method:

```
function remove_objects($from) {
  foreach ($from as $k => $v) {
    if (is_object($v)) {
      unset($from[$k]);
    } elseif (is_array($v)) {
      $from[$k] = $this->remove_objects($v);
    }
  }
  return $from;
}
```

In case it's necessary to say, the above snippet is public domain, full permission given for any/all use in anything.

**Comment by DavidAnderson684** [comment]
Or perhaps, to keep some random-ness, instead of...

```
      unset($from[$k]);
```

... you could have:

```
$from[$k] = "is_a_".get_class($v);
```

**Comment by terrafrost** [comment]
It looks like "Visual Bakery Composer" is not available for free download. It'd be nice to be able to view the source to confirm that `__sleep` is private instead of public but whatever.

Anyway, it looks like this behaves differently on different PHP versions. Here's my test script:

```php
<?php
class test {
    private function __sleep() {
        return array();
    }
}

$a = new test();
echo serialize($a);
```

I was only able to get a fatal error on PHP 5.2 and earlier. 5.3+ gave warnings instead. I was able to eliminate the error if I did `json_encode` instead of `serialize` but `json_encode` is only available as of PHP 5.2 so for 5.1 and earlier I employed a modified version of your method.

See #934 and LMK if that fixes the issue for you.

Thanks!

**Comment by DavidAnderson684** [comment]
Thank you.

I was only passed the error message, and inferred the cause from there (I don't have a copy of Visual Bakery Composer either). But, having test PHP installs from PHP 5.2 to 7 available, I got the same result as you: that serialize() on this test object causes a fatal error on PHP 5.2, but only a warning after that.

The error message I passed was as follows, from which I infer that the customer was on PHP 5.2 (and on Windows, from the back-slash path style). (The product in question doesn't support earlier PHP versions than 5.2).

```
Fatal error: Call to private method Vc_Manager::__sleep() from context '' in (snip)\phpseclib\Crypt\Random.php on line 156
```

However... I wonder whether calling json_encode() on arrays ($GLOBALS, etc.) of arbitrary PHP objects is the best idea. json_encode can't cope with anything except booleans, arrays or strings, and silently drops them. i.e. it's doing what serialize() is doing, except a) not emitting a warning when it silently drops stuff and b) you're getting less bits of information into the result, since it drops the object entirely (whereas serialize() on PHP 5.3+ is retaining the class name in the serialized output). i.e. The switch to json_encode() is basically just relying on another of those well-loved quirks of PHP, that json_encode() arbitrarily omits no warning whilst serialize() does.

**Comment by terrafrost** [comment]
> you're getting less bits of information into the result, since it just puts in an unnamed object (because that's all the JSON format supports) (whereas serialize() on PHP 5.3+ is retaining the PHP class name in the serialized output).

It's definitely less entropy (well for those applications that have objects assigned to $_SESSION or whatever) but it's not like having objects assigned to $_SESSION is a prerequisite. $_OLD_SESSION, $GLOBALS, $_COOKIE, etc, could all, in theory, be empty. I don't think it's possible for $_SERVER to be empty (unless  you overwrote it).

**Comment by DavidAnderson684** [comment]
>  it's not like having objects assigned to $GLOBALS is a prerequisite

Right. My bigger concern though was that by swapping serialize() for json_encode(), you're implicitly relying on json_encode() being well behaved. The reason for dropping serialize() is that it's not well-behaved (on PHP < 5.3) - however, serialize() is designed for arbitrary PHP objects, whereas JSON-encoding isn't.

From reading the PHP manual page and experimenting, I just discovered this one, for example.

This will print out lots of stuff:
```
<?php print json_encode($GLOBALS); ?>
```

But this will print absolutely nothing, because json_encode() will output nothing if anything in the passed array is a resource:

```
<?php $fh = fopen('/etc/localtime', 'rb'); print json_encode($GLOBALS); ?>
```

At least, that's what happens on PHP 5.5 up to 5.7. On PHP 5.2 to 5.4, it does print something, but accompanied by 3 PHP warnings.

Also, since $GLOBALS contains all the other variables ($_GET, $_POST, $_SERVER, etc.), doing something to more than $GLOBALS seems redundant, if the aim is to collect entropy (unless passing $GLOBALS to a function that may discard any unwanted input types...)

**Comment by DavidAnderson684** [comment]
P.S. Also: json_encode($GLOBALS) always results in a PHP warning, on all PHP versions (when there is output - i.e. unless prevented by an issue like the above), because of the recursion (the self-reference of $GLOBALS['GLOBALS']).

**Comment by terrafrost** [comment]
I've removed the `json_decode` calls and am instead just doing `safe_serailize`. Well, actually, `phpseclib_safe_serialize` (I renamed it to avoid name conflicts)

**Comment by Joey3000** [comment]
@DavidAnderson684 
> Also, since $GLOBALS contains all the other variables ($_GET, $_POST, $_SERVER, etc.), doing something to more than $GLOBALS seems redundant, if the aim is to collect entropy (unless passing $GLOBALS to a function that may discard any unwanted input types...)

That $GLOBALS contains all the other "superglobals" doesn't seem to be explicitly documented anywhere. I checked `print_r($GLOBALS);` on http://sandbox.onlinephpfunctions.com/ and it seems to be PHP version and/or php.ini configuration dependent whether, e.g., `$_SERVER` is contained (with `$_SESSION` never?).

**Comment by Joey3000** [comment]
This should be fixed per https://github.com/phpseclib/phpseclib/pull/934#discussion_r53465694
