### ISSUE TITLE
X509 SubjectAltNames IPv6 Support

### ISSUE THREAD

**Issue by metaclassing** [phpseclib/phpseclib#935]
Hi all,

IP address handling for X509v3 SubjectAltNames is currently in File/X509.php @ ~line 2193:
```
    /**
     * Decodes an IP address
     *
     * Takes in a base64 encoded "blob" and returns a human readable IP address
     *
     * @param string $ip
     * @access private
     * @return string
     */
    function _decodeIP($ip)
    {
        $ip = base64_decode($ip);
        list(, $ip) = unpack('N', $ip);
        return long2ip($ip);
    }
    /**
     * Encodes an IP address
     *
     * Takes a human readable IP address into a base64-encoded "blob"
     *
     * @param string $ip
     * @access private
     * @return string
     */
    function _encodeIP($ip)
    {
        return base64_encode(pack('N', ip2long($ip)));
    }
```
Obviously passing an IPv6 address (2001:1fc:30:9::123) will not survive the ip2long conversion in the current function.

From testing it appears both v4 and v6 addresses use the same OID: 2.5.29.17 and are just each represented by an octet string. Other than the octet string length (v4 are 4 bytes long, while v6 are 16 bytes long) I didn't see any other differences between their representation from ASN.1 dumps.

I would like to implement IPv6 support for the encode and decode functions and wanted to ask a couple questions before going further.

1) Are the encode/decode functions the only touch point to alter? Are there pieces elsewhere in the library I have neglected to account for?

2) inet_pton and ntop were introduced in PHP 5.1 (5.3 for Windows), are those acceptable functions to use? Or do I need to duplicate their functionality in a more-backwards-compatible way?

Please let me know your thoughts. Thanks!

**Comment by terrafrost** [comment]
> 1) Are the encode/decode functions the only touch point to alter? Are there pieces elsewhere in the library I have neglected to account for?

I think what you mentioned is sufficient.

> 2) inet_pton and ntop were introduced in PHP 5.1 (5.3 for Windows), are those acceptable functions to use? Or do I need to duplicate their functionality in a more-backwards-compatible way?

I'd say just have it target the 2.0 and master branches. Don't bother with the 1.0 branch. If push comes to shove a shim can be created for the 1.0 branch.

**Comment by metaclassing** [comment]
I forgot to close this after the PR was merged. Thanks!
