### ISSUE TITLE
sodium extension

### ISSUE THREAD

**Issue by fjqtp** [phpseclib/phpseclib#944]
/Net/SSH2.php file has line 1163

`if (!class_exists('\Sodium')) {`

I haven't Sodium installed in my server so yii app just falls down:

```
PHP Error[2]: include(Sodium.php): failed to open stream: No such file or directory
```

However, if i change line to

`if (!class_exists('\Sodium', false)) {`

all works just fine. false means turn autoload off. Is it necessary for autoload to be turned on? I'd suggest to turn it off if no.

**Comment by bantu** [comment]
See https://github.com/phpseclib/phpseclib/issues/919#issuecomment-181928242

**Comment by fjqtp** [comment]
Thanks. I've read whole thread but can't understand how it can help me. If I disable autoloader, everything other is not loaded, too.

I call

`$this->sftp = new \phpseclib\Net\SFTP($this->host);`

if i disable autoloader before, I see

`PHP Fatal error:  Class 'phpseclib\Net\SFTP' not found`

I solved my problem by creating fake (empty) Sodium class so now I'm just curious why is autoload for Sodium needed at all. Fake class seems to work just fine.

**Comment by bantu** [comment]
The point is, your autoloader (yii autoloader?, although the website
suggests it is using composer) is not behaving properly. If it can not
handle a specific class name it should not fail fatally.

**Comment by terrafrost** [comment]
#947 should fix this.

**Comment by fjqtp** [comment]
Thanks, that fixed the issue!

**Comment by advicente** [comment]
I'm unable to find the referenced correction on [#947](https://github.com/phpseclib/phpseclib/pull/947) while using version 2.0.1.
And have the same error: 
`include(Sodium.php): failed to open stream: No such file or directory`

I'm using Yii and composer autoloader. And haven't installed any PHP extension related to Sodium.
What am I missing?
Thanks.

**Comment by fjqtp** [comment]
@advicente you need to switch to dev-master branch:
```
"require": {
        "phpseclib/phpseclib": "dev-master"
    },
```

**Comment by advicente** [comment]
@fjqtp I understand but I am using phpseclib on a production environment. I think that I shoudn't use the "dev" version.
Thanks.
