### ISSUE TITLE
php 5.4.24 compatible?

### ISSUE THREAD

**Issue by alton-g** [phpseclib/phpseclib#948]
The company that I work for has php version 5.4.24 installed.  Is the new version of phpseclib compatilble with it?

Thanks,
Al

**Comment by GrahamCampbell** [comment]
yes

**Comment by terrafrost** [comment]
phpseclib 1.0 is compatible with PHP 4.4 through PHP 7 and anything in between (altho PHP 7 will give E_DEPRACTED notices due to 1.0's use of PHP4 style constructors).

phpseclib 2.0 and master require PHP 5.3 minimum but work with all later versions as well.
