### ISSUE TITLE
RC2 crypt not working - using parent::encrypt in decrypting function

### ISSUE THREAD

**Issue by piotrgolasz** [phpseclib/phpseclib#952]
https://github.com/phpseclib/phpseclib/blob/master/phpseclib/Crypt/RC2.php#L416

This line should be parent::decrypt, has parent::encrypt instead.

**Comment by terrafrost** [comment]
Fixed in the 1.0, 2.0 and master branches:

https://github.com/phpseclib/phpseclib/commit/da36b5c91ef81fd422661dc164e14c65ba077278

Thanks!

**Comment by pg7812** [comment]
GOOD JOB!
