### ISSUE TITLE
Math/BigInteger.php 1827

### ISSUE THREAD

**Issue by abhishektaneja** [phpseclib/phpseclib#954]
the loop throws a warning undefined offer 6 at Math/BigInteger.php:1827

        // calculate the appropriate window size.
        // $window_size == 3 if $window_ranges is between 25 and 81, for example.
        for ($i = 0, $window_size = 1; $e_length > $window_ranges[$i] && $i < count($window_ranges); ++$window_size, ++$i) {
        }

It should be 

        // calculate the appropriate window size.
        // $window_size == 3 if $window_ranges is between 25 and 81, for example.
        for ($i = 0, $window_size = 1; $i < count($window_ranges) && $e_length > $window_ranges[$i] ; ++$window_size, ++$i) {
        }

**Comment by abhishektaneja** [comment]
you can merge the pull request if you find this correct.
https://github.com/phpseclib/phpseclib/pull/955

**Comment by terrafrost** [comment]
Fixed with #955. Thanks!
