### ISSUE TITLE
Update readme with note about php5.3 invalid hmac issue and phpseclib1.0.1

### ISSUE THREAD

**Issue by codewise-nicolas** [phpseclib/phpseclib#968]
TerraFrost maybe you could add a little note to the download link on the main readme for phpseclib1.0.1 that if you get a Invalid HMAC error the user should try applying the patch referenced in https://github.com/phpseclib/phpseclib/issues/938#issuecomment-180788588 the patch being this one https://github.com/terrafrost/phpseclib/commit/bfd467532bf75c03960a5454cb734bba61c96406

Since most users will download that version of the lib and I assume many are running php5.3+ then many will undoubtedly get the Invalid HMAC error but when googling they will try to change the protocols in the SSH2.php to no avail. 

The alternative is to create a new release 1.0.2 and link to that, but this can be more cumbersome and most people will probably not download the master branch and use the download link instead.

Thanks for the lib.

**Comment by bantu** [comment]
I would prefer a new release.

**Comment by terrafrost** [comment]
Yah - I'd prefer a new release too. I'll try to do one in the next week or two (I have a pretty full plate this week so idk that this week will work). But people using the download link isn't really a problem - the master branch isn't BC compatible with the 1.0 branch anyway.

**Comment by codewise-nicolas** [comment]
I know a new release is ideal, as it fixes many things. but as https://github.com/phpseclib/phpseclib/issues/964#issuecomment-209798460 and my own situation shows, people are having this problem and can be easily resolved.
The readme can be updated with a small note quite quickly versus a whole new release, as an interim solution.
"PHP5.3+ users please apply patch here..."

Id make a new release for you, but last time I tried to grab the 1.0 branch it didnt work for me.

**Comment by terrafrost** [comment]
There are a number of issues that have been fixed in the 1.0 branch that aren't in the 1.0.1 release. If we mention this issue in the README.md file do we mention all those issues as well? Have it be like a running changelog?

Anyway, you couldn't make a release anyway. A release involves me updating the PEAR stuff on phpseclib.sourceforge.net, tagging the release, updating the download links, uploading a zip file to sourceforge.net, etc.

But I'm aware of no issues with the 1.0 branch. With the 2.0 branch there's some confusion w.r.t. a newly introduced dependency but that's not the 1.0 branch. What is the issue you're having with the 1.0 branch? All the unit tests are passing..

**Comment by codewise-nicolas** [comment]
You are very right it is a slippery slope. Possibly a "known issues" section would be handy.

I wanted to help the many people that had the Invalid HMAC error - I spent a good 3 days researching and testing only to find out it was the php version + library incompatibility (with simple fix)

I dont recall the issues I had with the 1.0 branch, ill give it a try later on this week when i have some time. Its most likely an issue on my end.

**Comment by codewise-nicolas** [comment]
Let me know if there is some way I can help.

**Comment by terrafrost** [comment]
> I wanted to help the many people that had the Invalid HMAC error - I spent a good 3 days researching and testing only to find out it was the php version + library incompatibility (with simple fix)

And I'm definitely appreciative of your efforts :)

Like in that one thread...  I wasn't at all on the right track, evidently, lol, but you were :)

**Comment by terrafrost** [comment]
I'll try to do this release tonight. I had intended on doing it this weekend but this weekend wound up being busier than I had anticipated.

**Comment by DavidAnderson684** [comment]
I've had a user with this issue too.

**Comment by terrafrost** [comment]
v1.0.2 has been released. I'm gonna hold off on releasing 2.0.2 for now.

https://github.com/phpseclib/phpseclib/releases/tag/1.0.2
