### ISSUE TITLE
validateSignature can't find certificate

### ISSUE THREAD

**Issue by klatoszewski** [phpseclib/phpseclib#971]
I have problem with validateSignature() function in X509.php file. This function check whether one certificate sign other certificate. I have two certificate that cause validateSignature() function fail. The problem is in this line:
`
if ($this->currentCert['tbsCertificate']['issuer'] === $ca['tbsCertificate']['subject'])
`

In first certificate all properties have type printableString in other certificate all properties have type utf8String and this cause that validateSignature() function can't find parent of certificate. My solution of this problem is repleace this condition by:
`
if($this->getDN(self::DN_STRING, $this->currentCert['tbsCertificate']['issuer']) == $this->getDN(self::DN_STRING, $ca['tbsCertificate']['subject']))
`

In this condition i compare only two string not array with types. See screenshot: http://imgur.com/F10dVvL

**Comment by terrafrost** [comment]
Can you post the certificates?

**Comment by klatoszewski** [comment]
Here is: http://pastebin.com/Mr4YS3DP

**Comment by terrafrost** [comment]
I'll take a look tonight - this was kinda a busy weekend for me.

Thanks!

**Comment by klatoszewski** [comment]
Have you done any investigation about that?

**Comment by terrafrost** [comment]
Yes.

So there are a couple of issues.

First, the intermidate cert's subject DN and in the third certs subject DN the types don't match. The strings have the same content but in the CA cert the OU and CN are utf8String's whereas in the third cert they're printableString's.

In the past it would have validated but that is now no longer the case. The commit that changed this behavior:

https://github.com/phpseclib/phpseclib/commit/340ee0cd2d7bf33316238fed8e9ab2e459d676ce

The reasoning behind that change:

https://github.com/phpseclib/phpseclib/pull/25#issuecomment-9596411

Second, the subject DN of the third cert has a weird DN. postalAddress (2.5.4.16). Here's the ASN.1 definition for the DN's:

```
   Certificate  ::=  SEQUENCE  {
        tbsCertificate       TBSCertificate,
        signatureAlgorithm   AlgorithmIdentifier,
        signatureValue       BIT STRING  }

   TBSCertificate  ::=  SEQUENCE  {
        version         [0]  EXPLICIT Version DEFAULT v1,
        serialNumber         CertificateSerialNumber,
        signature            AlgorithmIdentifier,
        issuer               Name,
        validity             Validity,
        subject              Name,
        subjectPublicKeyInfo SubjectPublicKeyInfo,
        issuerUniqueID  [1]  IMPLICIT UniqueIdentifier OPTIONAL,
                             -- If present, version MUST be v2 or v3
        subjectUniqueID [2]  IMPLICIT UniqueIdentifier OPTIONAL,
                             -- If present, version MUST be v2 or v3
        extensions      [3]  EXPLICIT Extensions OPTIONAL
                             -- If present, version MUST be v3
        }

   Name ::= CHOICE { -- only one possibility for now --
     rdnSequence  RDNSequence }

   RDNSequence ::= SEQUENCE OF RelativeDistinguishedName

   RelativeDistinguishedName ::=
     SET SIZE (1..MAX) OF AttributeTypeAndValue

   AttributeTypeAndValue ::= SEQUENCE {
     type     AttributeType,
     value    AttributeValue }

   AttributeType ::= OBJECT IDENTIFIER

   AttributeValue ::= ANY -- DEFINED BY AttributeType
```
http://www.alvestrand.no/objectid/2.5.4.16.html / https://tools.ietf.org/html/rfc4517#section-3.3.28 define postalAddress thusly:

```
PostalAddress ::= SEQUENCE SIZE (1..ub-postal-address) 
	OF DirectoryString {ub-postal-string}
```

In 99% of cases AttributeValue is some sort of string but here it's a SEQUENCE of strings.

I've done a number of code changes to accommodate all of this but I think there may be a little more that are necessary. Need to do more testing..

**Comment by terrafrost** [comment]
To add from my notes from the other day...  I made some changes to getDN() to accomodate your DN.

Some of them don't work very well with `FILE_X509_DN_CANON` or `FILE_X509_DN_HASH`, which were added with this commit:

https://github.com/phpseclib/phpseclib/commit/916dcff8a894f2f504ddcb26dc011d7aaac5e463

The justification for that change was sent to me in a private email. Quoting it:

> 3) The $string parameter of get{Subject|Issuer|}DN() has been replaced
> by a $format integer parameter. For compatibility reasons, Boolean
> values behave as the old $string parameter. The new getDN() options are:
>
> FILE_X509_DN_ARRAY      Internal array representation. Equivalent to old
> $string = false. Is default.
> FILE_X509_DN_STRING     String. Equivalent to old $string = true.
> FILE_X509_DN_ASN1               ASN.1 Name as a string.
> FILE_X509_DN_OPENSSL    OpenSSL compatible DN array.
> FILE_X509_DN_CANON      Canonical ASN.1 Name string. Used to compute
> openSSL file hashes.
> FILE_X509_DN_HASH               Openssl SHA.1 file name hash as a
> string.
>
> No provision has been made for old openssl file hashes since there are
> obsolescent. However, it is easy to compute those hashes using md5 and
> FILE_X509_DN_CANON.

I'm not sure how one uses OpenSSL to get sha1 hashes for DNs atm. I'll have to do some research to figure that out.

Unless I can figure this out I'm thinking maybe those two options can just be nixed in the master branch.

There's also the `$withType` parameter for the `getDNProp` method. I'm not sure what it's purpose is. It was added with this commit:

https://github.com/phpseclib/phpseclib/commit/340ee0cd2d7bf33316238fed8e9ab2e459d676ce

I'm not sure what it's point is so I think it's fair game for being removed from the master branch as well.

Anyway, an updated branch can be found here:

https://github.com/terrafrost/phpseclib/tree/x509-constructed-dns

I still need to add unit tests and mess with `setDN` and `setDNProp`.

To do what you're wanting to do do `define('FILE_X509_IGNORE_TYPE', true);` before you try to do `validateSignature()`.

The changes to `getDN()` were necessary to accommodate this for your cert specifically. In particular, `getDN()` did not work with your cert and I'm using `getDN()` to perform the non-strict comparison.

**Comment by terrafrost** [comment]
So I'll be breaking this in an upcoming commit.

To recap, the cert in this post had a number of issues

- The distinguished name had constructed elements to it which phpseclib didn't support at the time (it now does support them)
- The subject distinguished name, in the signing cert, used printablestrings for the organization name whereas the issuer distinguished name, in the signed cert, used utf8string's for the organization name. Since they matched if you ignored the type I added a new mode - define('FILE_X509_IGNORE_TYPE', true)`

In #1213 additional issues in the signature validation routines were identified and fixed. One of these issues involves the fact that the unit test that tested `FILE_X509_IGNORE_TYPE` using the certificates provided in this example is now failing. In reviewing things I believe the failure is correct.

So in the signing cert the serial number (`$cert['tbsCertificate']['serialNumber']`) is as follows;

217198998308647125865152742095828931970476817786

In the signed cert the authority cert serial number (`$cert['tbsCertificate']['extensions'][5]['extnValue']['authorityCertSerialNumber']`) is as follows:

23542

I tried to validate the certs in OpenSSL by doing `openssl verify -verbose -CAfile ca.pem signed.pem` and got this error:

```php
error 20 at 0 depth lookup:unable to get local issuer certificate
```

Thinking that maybe the string type mismatch was causing the error I created my own cert where the types matched exactly but for whom the serial numbers didn't match and I got the same exact error. For posterity those certs are as follows:

Signing:

```
-----BEGIN CERTIFICATE-----
MIIB0TCCATqgAwIBAgICAP8wDQYJKoZIhvcNAQEFBQAwHDEaMBgGA1UECgwRcGhw
c2VjbGliIGRlbW8gQ0EwIBcNMTcxMjEyMTM0ODM2WhgPOTk5OTEyMzEyMzU5NTla
MBwxGjAYBgNVBAoMEXBocHNlY2xpYiBkZW1vIENBMIGfMA0GCSqGSIb3DQEBAQUA
A4GNADCBiQKBgQC+ccJkHyAX9gbsoWCkYLhDzZnqGEV7m/chT+Jgjpza7Fw08oFK
uGRGxHBuMcnSx/1i8qpTtN3mz72ej1/kEtnXBdosaxSX0Vf0Dn/rRCnGD9McH1Em
46dkR92wUDnjP2p2rbLXGne3suw3VVaAtFNyLMMAcbtxRx95rIDWkbZfvwIDAQAB
oyAwHjALBgNVHQ8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQUF
AAOBgQBWuaCvA8NyjfZi1GPOaiRsQ2nnX0PQ/GRLhfqtDe18x4VOaESY6Btv/xFM
/wm5y0k2Q/y1QQrN5oLFuRdPfB0ypKaE3ITqkyLBMTcVaLuDpfkCo+pfGuVLAA4M
lzRJySwTvS+tbohoSo+eaP4xLJmoKTzzFBt+8SVJU3ecbXOSBg==
-----END CERTIFICATE-----
```

Signed:

```
-----BEGIN CERTIFICATE-----
MIICBTCCAW6gAwIBAgIUBjg6Arsg2FgiEviVyHkCZq2kPtwwDQYJKoZIhvcNAQEF
BQAwHDEaMBgGA1UECgwRcGhwc2VjbGliIGRlbW8gQ0EwIBcNMTcxMjEyMTM0ODM2
WhgPOTk5OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAoME3BocHNlY2xpYiBkZW1vIGNl
cnQwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAK2ZsceBTjdgAlsfc3R+vAbL
EwUoZ5fayfUeyJcop1hrU0hIkCLKNF1ZF+WJGwHIzp0pIAuAl8VomdvyEVcVxOh7
ZDaWCnceaOvTrKQCmYVAgfhZTXOhIKI4DXw3aZVbb0g+PeeRfZxdZWlcOR2UTbSr
UvyeEQJKwV5DtpoxcB0tAgMBAAGjQDA+MC4GA1UdIwQnMCWhIKQeMBwxGjAYBgNV
BAoMEXBocHNlY2xpYiBkZW1vIENBggEAMAwGA1UdDgQFBAN6enowDQYJKoZIhvcN
AQEFBQADgYEAC1dBLtMiSQnLlZV/lLCZZ8lEpDIXNjjrlIRRIOFfX7VALy9Yruqn
az9Da8CxDk0nMeMH4BenPWGSeTT82CVKT2z1gSaiqVTyYqVorQe4StelV/fvUU6a
wa0kPUQrDRIVAh0/9pbywYmFUSTpW6DSFJX8LdiY70qf12bsgd2YTL8=
-----END CERTIFICATE-----
```

As a sanity check I creating a signed / signing cert where the serial number _did_ match as well:

Signer:
```
-----BEGIN CERTIFICATE-----
MIIB0TCCATqgAwIBAgICAP8wDQYJKoZIhvcNAQEFBQAwHDEaMBgGA1UECgwRcGhw
c2VjbGliIGRlbW8gQ0EwIBcNMTcxMjEyMTM1OTM3WhgPOTk5OTEyMzEyMzU5NTla
MBwxGjAYBgNVBAoMEXBocHNlY2xpYiBkZW1vIENBMIGfMA0GCSqGSIb3DQEBAQUA
A4GNADCBiQKBgQDsGTwTfUHqjBTsluCMEVTjOFwiewbt3j9zOn+j98LlXmhN3Y6X
Un7RYZDBuRH5sbH7Flg5fT18GHtuWQaiJ97kZCkKfeDY3UasIOJTXKnPe+EPyD0i
yuqagKwpY7uC4gXAe3sLWrjHX5S31/Zp7b82xP4MtgyK96sbcv8gKNULhQIDAQAB
oyAwHjALBgNVHQ8EBAMCAQYwDwYDVR0TAQH/BAUwAwEB/zANBgkqhkiG9w0BAQUF
AAOBgQDDXhHG4OCkDbOIQiOV0wslzOpYfc60coXy34Yvq5PG9sZqbwnUFYZEBXa7
tCFVG0mygJZEH1PuDA0xuWPTeY2gCNNshKQ97uO+2Bz+bbutEp+IpdoWszB5M58a
xmgPdQx04p00+4CGPRF++71DWPv9cvmJioCmmnqpGmfuQthlww==
-----END CERTIFICATE-----
```

Signed:
```
-----BEGIN CERTIFICATE-----
MIICBjCCAW+gAwIBAgIUO0gWvemMDSyhZKCjHZejic8+2iIwDQYJKoZIhvcNAQEF
BQAwHDEaMBgGA1UECgwRcGhwc2VjbGliIGRlbW8gQ0EwIBcNMTcxMjEyMTM1OTM3
WhgPOTk5OTEyMzEyMzU5NTlaMB4xHDAaBgNVBAoME3BocHNlY2xpYiBkZW1vIGNl
cnQwgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBAKvkH1L/76cMtH+/oMlI3v64
bBO6yuh/qiX/fSAAAk3xM3oi104vwAtVJyHq4UQjBOPIOJQlqqBdTN39e1Qla4yJ
Dy4OqSFBFFictty7W4A1Hi9Tm52TZBJn2Sh0WNBQkht7qSRQ2owi0zijlBPAmP18
B4a2GF8RhESdSKAhpW+nAgMBAAGjQTA/MC8GA1UdIwQoMCahIKQeMBwxGjAYBgNV
BAoMEXBocHNlY2xpYiBkZW1vIENBggIA/zAMBgNVHQ4EBQQDenp6MA0GCSqGSIb3
DQEBBQUAA4GBALIdIebttXyvV5OhsxevmM38BFOxEudWIBpFkYFzkBIH/9vj6Wmu
T26c77+YyWJv7NVv/TNiPmLwlwxGCrnun/kAAI5ykCZrXx/ZiYDV241JKtG5IhXo
hntViwDIuYCmP+KcCJ4LTg6fz4V36vUQ8fUsRNh9zCdx6KeuRygp+43n
-----END CERTIFICATE-----
```

Those certs validate with OpenSSL.

Since neither the new changes nor OpenSSL think the certs are valid I'm gonna go ahead and remove the last unit test that this issue resulted in.

I would be interested in knowing what package actually said these certs validate (outside of phpseclib).  OpenSSL 1.0.2j doesn't like them...  what does?
