### ISSUE TITLE
[Enhancement] mode GCM

### ISSUE THREAD

**Issue by piotrgolasz** [phpseclib/phpseclib#972]
@terrafrost would it be burdensome to code GCM mode (Galois Counter Mode)?
afaik openssl already supports it, reason for implementation is to prevent lucky13 attack

**Comment by terrafrost** [comment]
I'm not sure - I'll have to look into it. I'll do so at some point and get back to you.

**Comment by bantu** [comment]
I am closing this as a duplicate of #47 if you don't mind.
