### ISSUE TITLE
CSR are not quite generated to RFC, apparently.

### ISSUE THREAD

**Issue by tyjtyj** [phpseclib/phpseclib#975]
As per issue reported by https://github.com/phpseclib/phpseclib/issues/705. 

The issue does not seem to resolve for generating CSR
 
ASN parser for CSR generated from phplibsec
  201:d=2  hl=4 l= 288 cons:   SEQUENCE
  205:d=3  hl=2 l=  11 cons:    SEQUENCE
  207:d=4  hl=2 l=   9 prim:     OBJECT            :rsaEncryption
  218:d=3  hl=4 l= 271 prim:    BIT STRING
  493:d=1  hl=2 l=  11 cons:  SEQUENCE
  495:d=2  hl=2 l=   9 prim:   OBJECT            :sha256WithRSAEncryption
  506:d=1  hl=4 l= 257 prim:  BIT STRING

ASN parser for CSR generated from OPENSSL
  209:d=2  hl=4 l= 290 cons:   SEQUENCE
  213:d=3  hl=2 l=  13 cons:    SEQUENCE
  215:d=4  hl=2 l=   9 prim:     OBJECT            :rsaEncryption
  226:d=4  hl=2 l=   0 prim:     NULL
  228:d=3  hl=4 l= 271 prim:    BIT STRING
  503:d=2  hl=2 l=   0 prim:   cont [ 0 ]
  505:d=1  hl=2 l=  13 cons:  SEQUENCE
  507:d=2  hl=2 l=   9 prim:   OBJECT            :sha256WithRSAEncryption
  518:d=2  hl=2 l=   0 prim:   NULL
  520:d=1  hl=4 l= 257 prim:  BIT STRING

Any work around would be appreciate at this moment.

**Comment by metaclassing** [comment]
What version/branch are you using?

**Comment by tyjtyj** [comment]
Master

**Comment by tyjtyj** [comment]
Appear to be duplicated from 
https://github.com/phpseclib/phpseclib/issues/914
