### ISSUE TITLE
Connection closed prematurely

### ISSUE THREAD

**Issue by jamieburchell** [phpseclib/phpseclib#985]
Hey

When downloading a file over SFTP (approx 3MB) and then deleting it from the remote server we get these notices:

```
PHP Notice:  Connection closed prematurely in phpseclib/phpseclib/phpseclib/Net/SSH2.php on line 3396
PHP Notice:  Expected SSH_FXP_STATUS in /phpseclib/phpseclib/phpseclib/Net/SFTP.php on line 2150
```

I'm unable to paste the full FTP log as it contains sensitive information, but I can hint that the problem appears to be the connection is closed before the delete is called. There is a process intensive code block that runs which takes a minute or so before the script resumes to attempt the file delete.

FTP log:

```
-> NET_SFTP_INIT (0.0001s)
00000000  00:00:00:03                                      ....

<- NET_SFTP_VERSION (0.0186s)
00000000  00:00:00:03                                      ....

-> NET_SFTP_REALPATH (0.0001s)
00000000  00:00:00:01:2e                                   .....

<- NET_SFTP_NAME (0.0456s)
(redacted)

-> NET_SFTP_OPENDIR (0.0001s)
(redacted)

<- NET_SFTP_HANDLE (0.0355s)
00000000  00:00:00:03:32:31:39                             ....219

-> NET_SFTP_CLOSE (0.0001s)
00000000  00:00:00:03:32:31:39                             ....219

<- NET_SFTP_STATUS (0.0185s)
00000000  00:00:00:00:00:00:00:00:00:00:00:00              ............

-> NET_SFTP_OPENDIR (0.0001s)
(redacted)

<- NET_SFTP_HANDLE (0.0184s)
00000000  00:00:00:03:32:32:30                             ....220

-> NET_SFTP_READDIR (0.0001s)
00000000  00:00:00:03:32:32:30                             ....220

<- NET_SFTP_NAME (0.0307s)
(redacted, verified full file contents listed here - not truncated)

-> NET_SFTP_READ (0.0001s)
00000000  00:00:00:03:32:32:31:00:00:00:00:00:2f:7a:ea:00  ....221...../z..
00000010  00:80:00                                         ...

<- NET_SFTP_STATUS (0.0185s)
00000000  00:00:00:01:00:00:00:0b:45:6e:64:20:6f:66:20:46  ........End of F
00000010  69:6c:65:00:00:00:00                             ile....

-> NET_SFTP_CLOSE (0.0001s)
00000000  00:00:00:03:32:32:31                             ....221

<- NET_SFTP_STATUS (0.0187s)
00000000  00:00:00:00:00:00:00:00:00:00:00:00              ............

-> NET_SFTP_REMOVE (0.0002s)
(redacted, attempting to remove file downloaded above)
```

```
$ php -v
PHP 5.5.35 (cli) (built: May  1 2016 14:00:28)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

Using phpseclib v2.0.1 on CentOS 6

Issue is consistently repeatable

**Comment by terrafrost** [comment]
In this case the SSH logs would probably be more helpful. You can get them by doing `define('NET_SSH2_LOGGING', 2)` and then doing `$ssh->getLog()`. What I'm specifically interested are the last few packets.

Thanks!

**Comment by jamieburchell** [comment]
Hey

I might not be able to reproduce this now since I rewrote the application in question to avoid pausing with computationally expensive tasks between getting a file and deleting it. I now get all files I need and store them locally for processing and delete them after. If I get an opportunity I'll see if I can set up a simulation to try.

It looks to me that the remote server disconnected after the get, while my script was running for 10-15 seconds and by the time it had finished and tried to delete the file the connection was closed. I would have expected the library to handle this and reconnect though.

**Comment by terrafrost** [comment]
> It looks to me that the remote server disconnected after the get, while my script was running for 10-15 seconds and by the time it had finished and tried to delete the file the connection was closed.

Sounds plausible.

> I would have expected the library to handle this and reconnect though, but it was neither able to delete the file or get the next ones.

It's a good idea for a feature. I guess I never thought about it and never got a request for it either lol.

In theory what'd be better are keep-alive packets, but alas, that doesn't really work with PHP. You'd need multi-threading or some such for that.

**Comment by terrafrost** [comment]
> I would have expected the library to handle this and reconnect though, but it was neither able to delete the file or get the next ones.

So I did some experimenting along these lines and...  well I think this is only going to be a feature I'll implement in the master branch. My preliminary work was promising but then I realized...  I'm gonna have to replay login's for this to work. In light of that I think I'm just gonna put it on the backburner.

Here's my experimental code:

https://github.com/terrafrost/phpseclib/commit/222c525d7907e77da83bd86ead55384c7f9f4d09

**Comment by jamieburchell** [comment]
No problem; thanks for looking in to it. It's one of those things that was causing problems in our app but we couldn't work out what was failing but now we know the limitations of the library we can work around these issues. Keeping the connection open for as short a time as possible seems like a more robust and better approach anyway.

**Comment by lukepolo** [comment]
I've had similar issues , i wrote something like : 

```
} catch (\ErrorException $e) {
            if ($e->getMessage() == "Unable to open channel") {
                \Log::warning('retrying to connect to');
                $this->ssh($this->server, $this->user);
                $this->run($command, $read);
            } 
```

Basically i reconnect and re-run the command I was doing (pretty crappy but it seems to be holding up for now)

**Comment by jamieburchell** [comment]
Can this issue now be closed @terrafrost?

I'm not certain, but it looks like you have fixed this in newer versions of the library?

**Comment by terrafrost** [comment]
> I'm not certain, but it looks like you have fixed this in newer versions of the library?

Yah - `ping()` is a new method that's been introduced that should take care of this.

Thanks!
