### ISSUE TITLE
Changelog was not updated for 1.0.2

### ISSUE THREAD

**Issue by fingolfin** [phpseclib/phpseclib#987]
Very minor thing, but: It seems `CHANGELOG.md` was not updated for release 1.0.2. There are some release notes on https://github.com/phpseclib/phpseclib/releases/tag/1.0.2 but not in https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md

Perhaps this information (in particular: the date of the release) could be added to the CHANGELOG.md now, so that it's there for 1.0.3, assuming that will ever happen?

PS: I noticed while updating <http://ssh-comparison.quendi.de/impls/phpseclib.html>.

**Comment by terrafrost** [comment]
Done:

https://github.com/phpseclib/phpseclib/blob/master/CHANGELOG.md

Thanks!
