### ISSUE TITLE
NativeSessionStorage fatal error when profiling and phpseclib library is utilized

### ISSUE THREAD

**Issue by PabloJoan** [phpseclib/phpseclib#990]
I've been profiling an http get request with blackfire.io where I utilize phpseclib and symfony ( https://github.com/symfony/symfony ) to ssh in to a server and execute a command.

the fatal error is this

`request.CRITICAL: Uncaught PHP Exception RuntimeException: "Failed to start the session because headers have already been sent by "/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php" at line 3255." at /app/cache/prod/classes.php line 114 {"exception":"[object] (RuntimeException(code: 0): Failed to start the session because headers have already been sent by \"/vendor/phpseclib/phpseclib/phpseclib/Net/SSH2.php\" at line 3255. at /app/cache/prod/classes.php:114)"} []`

in phpseclib, line 3255 is as follows

`user_error('Unable to open channel');`

and the fatal error comes from the native session storage class symfony/symfony/src/Symfony/Component/HttpFoundation/Session/Storage/NativeSessionStorage.php

```
if (ini_get('session.use_cookies') && headers_sent($file, $line)) {
            throw new \RuntimeException(sprintf('Failed to start the session because headers have already been sent by "%s" at line %d.', $file, $line));
}
```
i'm not sure how headers_sent and user_error are related, maybe something else is the issue, but when profiling this with blackfire, it happens all the time

Symfony 2.8
Phpseclib 2.0

Php 5.4
Mac OS X 10.11.4

**Comment by terrafrost** [comment]
To get rid of the error you can use an error handler:

http://php.net/manual/en/function.set-error-handler.php

Another possibility: you could use the error suppression operator (`@`) on whatever phpseclib method call is causing that error. eg. if you're doing `$ssh->login()` you could instead do `@$ssh->login()`, etc. To know what method you'd need to use that operator on I'd need to see a stack trace.

The master branch has replaced errors like this with exceptions but the master branch is still under development and the API is unstable (like it could change drastically from commit to commit).
