### ISSUE TITLE
Unable to connect - BigInteger times out

### ISSUE THREAD

**Issue by MadTomT** [phpseclib/phpseclib#991]
Hi
I'm trying to do a very simple connection:

```
	include('includes/Net/SSH2.php');
	$ssh = new Net_SSH2('192.168.1.1');
	if (!$ssh->login('user', 'pass')) {
		exit('Login Failed');
	}

	echo $ssh->exec('pwd');
```

But it always fails with : 

> Fatal error: Maximum execution time of 30 seconds exceeded in /WebHost/includes/Math/BigInteger.php on line 1325

Looking on the device I'm ssh'ing to  I see:

> Child connection from 192.168.1.10:43159
> authpriv.info dropbear: exit before auth: Exited normally
> 

The device the page is running on is an old PHP4 based module that I have no control over updating.  I'm only using this as its the only device in the same range as the one I need to ssh to.

Any way I can get this to work ?
Thanks

**Comment by terrafrost** [comment]
What version of phpseclib are you using? If you don't know maybe you could copy / paste the code of Math/BigInteger.php to pastebin.com and then post the link here? I should be able to figure out the version you're running from that.

That said, per http://phpseclib.sourceforge.net/math/intro.html PHP 4 is pretty slow. Especially if you don't have BCMath or OpenSSL installed.

When you're SSH'ing you have to do diffie-hellman key exchange:

```php
        $x = $one->random($one, $max);
        $e = $g->modPow($x, $prime);
```

`modPow` is an expensive operation so it's possible that's where the slow down is but it's hard to say for sure.

Something that might provide a little more insight as well: the SSH logs. You can get them by doing `define('NET_SSH2_LOGGING', 3);` at the top of the file. That'll print the raw SSH packets out real time. If you could post those here, as well, that'd be helpful.

Thanks!

**Comment by MadTomT** [comment]
Thanks for the reply.
The pastebin is: http://pastebin.com/0p9JDqTJ

Will the debug raw SSH Packets contain any personal information about the host or the device being connected to ?

Thanks

**Comment by terrafrost** [comment]
Looks like you're using phpseclib 1.0.0. The latest version is 1.0.2.

> Will the debug raw SSH Packets contain any personal information about the host or the device being connected to ?

Nope. You're using password authentication in your example and phpseclib replaces whatever your password is with "password" and the username with "username". The IP address isn't recorded either.
