### ISSUE TITLE
PHP Notice: Undefined variable: key_comment 

### ISSUE THREAD

**Issue by gulios** [phpseclib/phpseclib#994]
Can you release stable version 2.x with fixed

PHP Notice: Undefined variable: key_comment in phar:///usr/local/bin/dep/vendor/phpseclib/phpseclib/phpseclib/System/SSH/Agent.php on line 180

Thank you.

**Comment by terrafrost** [comment]
2.0.2 has been released, which includes the fix for this:

https://github.com/phpseclib/phpseclib/commit/6a97ddfa725b6e099c3af7fc830f8ff92f7c00ac#diff-a67ac2ad29eab9e856911a1571f69ea5
